### ISSUE TITLE
PHP 7: Stack trace on PHP fatal error does not point to actual error

### ISSUE THREAD

**Issue by olavmrk** [simplesamlphp/simplesamlphp#1002]
The exception handler configured for SimpleSAMLphp hides the actual location of error when handling fatal errors in PHP 7. Instead we get a stack trace pointing to the error handler:

> SimpleSAML_Error_Exception: Error 1 - Call to undefined function invalidfunction()
> Backtrace:
> 2 /www/simplesamlphp/www/_include.php:58 (SimpleSAML_error_handler)
> 1 /www/simplesamlphp/www/_include.php:26 (SimpleSAML_exception_handler)
> 0 [builtin] (N/A)

This is caused by a change in the way that errors are handled in PHP 7. Before PHP 7, PHP would directly call our [error handler](https://github.com/simplesamlphp/simplesamlphp/blob/v1.16.2/www/_include.php#L34) from the location of the error. This allowed us to capture a stack trace pointing to the location the error occurred.

After PHP 7, the error is handled like a normal exception. This means that PHP will unwind the stack looking for an exception handler, before finally passing it to the [`SimpleSAML_exception_handler()`-function](https://github.com/simplesamlphp/simplesamlphp/blob/v1.16.2/www/_include.php#L10).

This function handles errors by invoking the old error handler:
https://github.com/simplesamlphp/simplesamlphp/blob/v1.16.2/www/_include.php#L20-L27

Unfortunately, that loses the information about where the error occurred, since that is only stored in the original exception.

The best way to solve this would be to not call the original error handler, but simply wrap the error in a normal unhandled exception:

```
if (class_exists('Error') && $exception instanceof Error) {
    $e = new \SimpleSAML\Error\Error('UNHANDLEDEXCEPTION', $exception);
    $e->show();
}
```

This would log the exception like any other unhandled exception:

> SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
> Backtrace:
> 1 /www/simplesamlphp/www/_include.php:20 (SimpleSAML_exception_handler)
> 0 [builtin] (N/A)
> Caused by: Error: Call to undefined function invalidfunction()
> Backtrace:
> 1 /www/simplesamlphp/modules/somemodule/www/index.php:10 (require)
> 0 /www/simplesamlphp/www/module.php:135 (N/A)

The problem is that the [`Error` class](http://php.net/manual/en/class.error.php) does not inherit from the [`Exception` class](http://php.net/manual/en/class.exception.php). Thus the [constructor for `SimpleSAML\Error\Exception`](https://github.com/simplesamlphp/simplesamlphp/blob/v1.16.2/lib/SimpleSAML/Error/Exception.php#L44) does not allow us to include it as the `$cause` parameter.

To fix that will require changing the `SimpleSAML\Error\Exception` class and other related classes to accept both a `Exception` and a `Error` object as the `$cause`-parameter.

The [`Throwable`-interface](http://php.net/manual/en/class.throwable.php) is common between `Exception` and `Error`, but that only exists in PHP 7, so we cannot use that while supporting PHP 5.

**Comment by tvdijen** [comment]
We should be able to define a Throwable interface ourselves if PHP-version is <7, so I don't see much of a problem there...
The problem I see is that changing the footprint of the constructor is a BC-change, so we might as well rethink the whole error handling for 2.0

**Comment by jornane** [comment]
How would existing Exception and Error classes extend from this ad-hoc Throwable? I think it's better to just accept both.

**Comment by tvdijen** [comment]
I wonder if this still applies... I'm running PHP 7.3 and when I call a non-existing method I get:

```
Aug  7 17:43:48 webapp-10 simplesamlphp-idp[39314]: 3 [6810ea4612] SimpleSAML\Error\Exception: Error 1 - Attempted to call function "callSomething" from namespace "SimpleSAML\Module\admin\Controller". at /apps/installation/simplesamlphp/simplesamlphp-master/modules/admin/lib/Controller/Config.php:114
Aug  7 17:43:48 webapp-10 simplesamlphp-idp[39314]: 3 [6810ea4612] Backtrace:
Aug  7 17:43:48 webapp-10 simplesamlphp-idp[39314]: 3 [6810ea4612] 3 /apps/installation/simplesamlphp/simplesamlphp-master/www/_include.php:48 (SimpleSAML_error_handler)
Aug  7 17:43:48 webapp-10 simplesamlphp-idp[39314]: 3 [6810ea4612] 2 /apps/installation/simplesamlphp/simplesamlphp-master/www/_include.php:25 (SimpleSAML_exception_handler)
Aug  7 17:43:48 webapp-10 simplesamlphp-idp[39314]: 3 [6810ea4612] 1 /apps/installation/simplesamlphp/simplesamlphp-master/vendor/symfony/error-handler/ErrorHandler.php:589 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
Aug  7 17:43:48 webapp-10 simplesamlphp-idp[39314]: 3 [6810ea4612] 0 [builtin] (N/A)
```

**Comment by tvdijen** [comment]
OK, with the changes from #1365 I get a more elaborate trace:

```
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] Backtrace:
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] 2 /apps/installation/simplesamlphp/simplesamlphp-master/www/_include.php:20 (SimpleSAML_exception_handler)
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] 1 /apps/installation/simplesamlphp/simplesamlphp-master/vendor/symfony/error-handler/ErrorHandler.php:589 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] 0 [builtin] (N/A)
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] Caused by: Symfony\Component\ErrorHandler\Error\UndefinedFunctionError: Attempted to call function "callSomething" from namespace "SimpleSAML\Module\admin\Controller".
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] Backtrace:
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] 5 /apps/installation/simplesamlphp/simplesamlphp-master/modules/admin/lib/Controller/Config.php:114 (SimpleSAML\Module\admin\Controller\Config::main)
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] 4 /apps/installation/simplesamlphp/simplesamlphp-master/vendor/symfony/http-kernel/HttpKernel.php:158 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] 3 /apps/installation/simplesamlphp/simplesamlphp-master/vendor/symfony/http-kernel/HttpKernel.php:80 (Symfony\Component\HttpKernel\HttpKernel::handle)
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] 2 /apps/installation/simplesamlphp/simplesamlphp-master/vendor/symfony/http-kernel/Kernel.php:201 (Symfony\Component\HttpKernel\Kernel::handle)
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] 1 /apps/installation/simplesamlphp/simplesamlphp-master/lib/SimpleSAML/Module.php:208 (SimpleSAML\Module::process)
Aug  7 17:52:05 webapp-10 simplesamlphp-idp[39313]: 3 [6810ea4612] 0 /apps/installation/simplesamlphp/simplesamlphp-master/www/module.php:10 (N/A)
```

I guess it makes sense to merge that PR and backport it to 1.19

**Comment by tvdijen** [comment]
It's also much more user-friendly because we go from a white screen of death to a neatly formatted UNHANDLEDEXCEPTION page
