### ISSUE TITLE
Symfony 4.1 and SimplesamlPHP 1.16.2

### ISSUE THREAD

**Issue by tweismanBC** [simplesamlphp/simplesamlphp#1003]
So I'm having an issue installing simplesamlphp via composer into my Symfony 4.1.7 build. I've used simplesamlphp in Symfony 3.4 in the past to successfully implement an SSO implementation. 

The issue seems similar to this: https://github.com/simplesamlphp/simplesamlphp/issues/925
However, I can't quite grasp what they did to get around the issue as I've tried forcing Robrichard's package to dev-master and it still won't allow me to install simplesamlphp.

The error I'm getting is as follows:
 Problem 1
    - simplesamlphp/simplesamlphp 1.16.1 requires robrichards/xmlseclibs dev-master#93f8c07976b36b6050ab341ab5850484dc897ce0 as 3.0.2 -> satisfiable by robrichards/xmlseclibs[dev-master] but these conflict with your requirements or minimum-stability.
    - simplesamlphp/simplesamlphp 1.16.0 requires robrichards/xmlseclibs dev-master#93f8c07976b36b6050ab341ab5850484dc897ce0 as 3.0.2 -> satisfiable by robrichards/xmlseclibs[dev-master] but these conflict with your requirements or minimum-stability.
    - Conclusion: remove symfony/http-kernel v4.1.7
    - Conclusion: don't install symfony/http-kernel v4.1.7
    - twig/twig 1.3.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig 1.4.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig 1.5.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig 1.5.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig 1.6.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig 1.6.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig 1.6.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig 1.6.3 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig 1.6.4 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig 1.6.5 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.10.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.10.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.10.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.10.3 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.11.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.11.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.12.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.12.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.12.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.12.3 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.13.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.13.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.13.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.14.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.14.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.14.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.15.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.15.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.16.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.16.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.16.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.16.3 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.17.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.18.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.18.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.18.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.19.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.20.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.21.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.21.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.21.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.22.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.22.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.22.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.22.3 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.23.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.23.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.23.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.23.3 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.24.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.24.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.24.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.25.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.26.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.26.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.27.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.28.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.28.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.28.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.29.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.30.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.31.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.32.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.33.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.33.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.33.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.7.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.8.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.8.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.8.2 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.8.3 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.9.0 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.9.1 conflicts with symfony/http-kernel[v4.1.7].
    - twig/twig v1.9.2 conflicts with symfony/http-kernel[v4.1.7].
    - Installation request for symfony/http-kernel (locked at v4.1.7) -> satisfiable by symfony/http-kernel[v4.1.7].
    - Installation request for simplesamlphp/simplesamlphp ^1.16 -> satisfiable by simplesamlphp/simplesamlphp[1.16.0, 1.16.1, 1.16.2].
    - Conclusion: don't install twig/twig v2.5.0|install twig/twig 1.3.0|install twig/twig 1.4.0|install twig/twig 1.5.0|install twig/twig 1.5.1|install twig/twig 1.6.0|install twig/twig 1.6.1|install twig/twig 1.6.2|install twig/twig 1.6.3|install twig/twig 1.6.4|install twig/twig 1.6.5|install twig/twig v1.10.0|install twig/twig v1.10.1|install twig/twig v1.10.2|install twig/twig v1.10.3|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.7.0|install twig/twig v1.8.0|install twig/twig v1.8.1|install twig/twig v1.8.2|install twig/twig v1.8.3|install twig/twig v1.9.0|install twig/twig v1.9.1|install twig/twig v1.9.2
    - Conclusion: remove twig/twig v2.5.0|install twig/twig 1.3.0|install twig/twig 1.4.0|install twig/twig 1.5.0|install twig/twig 1.5.1|install twig/twig 1.6.0|install twig/twig 1.6.1|install twig/twig 1.6.2|install twig/twig 1.6.3|install twig/twig 1.6.4|install twig/twig 1.6.5|install twig/twig v1.10.0|install twig/twig v1.10.1|install twig/twig v1.10.2|install twig/twig v1.10.3|install twig/twig v1.11.0|install twig/twig v1.11.1|install twig/twig v1.12.0|install twig/twig v1.12.1|install twig/twig v1.12.2|install twig/twig v1.12.3|install twig/twig v1.13.0|install twig/twig v1.13.1|install twig/twig v1.13.2|install twig/twig v1.14.0|install twig/twig v1.14.1|install twig/twig v1.14.2|install twig/twig v1.15.0|install twig/twig v1.15.1|install twig/twig v1.16.0|install twig/twig v1.16.1|install twig/twig v1.16.2|install twig/twig v1.16.3|install twig/twig v1.17.0|install twig/twig v1.18.0|install twig/twig v1.18.1|install twig/twig v1.18.2|install twig/twig v1.19.0|install twig/twig v1.20.0|install twig/twig v1.21.0|install twig/twig v1.21.1|install twig/twig v1.21.2|install twig/twig v1.22.0|install twig/twig v1.22.1|install twig/twig v1.22.2|install twig/twig v1.22.3|install twig/twig v1.23.0|install twig/twig v1.23.1|install twig/twig v1.23.2|install twig/twig v1.23.3|install twig/twig v1.24.0|install twig/twig v1.24.1|install twig/twig v1.24.2|install twig/twig v1.25.0|install twig/twig v1.26.0|install twig/twig v1.26.1|install twig/twig v1.27.0|install twig/twig v1.28.0|install twig/twig v1.28.1|install twig/twig v1.28.2|install twig/twig v1.29.0|install twig/twig v1.30.0|install twig/twig v1.31.0|install twig/twig v1.32.0|install twig/twig v1.33.0|install twig/twig v1.33.1|install twig/twig v1.33.2|install twig/twig v1.7.0|install twig/twig v1.8.0|install twig/twig v1.8.1|install twig/twig v1.8.2|install twig/twig v1.8.3|install twig/twig v1.9.0|install twig/twig v1.9.1|install twig/twig v1.9.2
    - simplesamlphp/simplesamlphp 1.16.2 requires twig/twig ~1.0 -> satisfiable by twig/twig[1.3.0, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, v1.10.0, v1.10.1, v1.10.2, v1.10.3, v1.11.0, v1.11.1, v1.12.0, v1.12.1, v1.12.2, v1.12.3, v1.13.0, v1.13.1, v1.13.2, v1.14.0, v1.14.1, v1.14.2, v1.15.0, v1.15.1, v1.16.0, v1.16.1, v1.16.2, v1.16.3, v1.17.0, v1.18.0, v1.18.1, v1.18.2, v1.19.0, v1.20.0, v1.21.0, v1.21.1, v1.21.2, v1.22.0, v1.22.1, v1.22.2, v1.22.3, v1.23.0, v1.23.1, v1.23.2, v1.23.3, v1.24.0, v1.24.1, v1.24.2, v1.25.0, v1.26.0, v1.26.1, v1.27.0, v1.28.0, v1.28.1, v1.28.2, v1.29.0, v1.30.0, v1.31.0, v1.32.0, v1.33.0, v1.33.1, v1.33.2, v1.34.0, v1.34.1, v1.34.2, v1.34.3, v1.34.4, v1.35.0, v1.35.1, v1.35.2, v1.35.3, v1.35.4, v1.7.0, v1.8.0, v1.8.1, v1.8.2, v1.8.3, v1.9.0, v1.9.1, v1.9.2].
    - Can only install one of: twig/twig[v1.35.0, v2.5.0].
    - Can only install one of: twig/twig[v1.35.1, v2.5.0].
    - Can only install one of: twig/twig[v1.35.2, v2.5.0].
    - Can only install one of: twig/twig[v1.35.3, v2.5.0].
    - Can only install one of: twig/twig[v1.35.4, v2.5.0].
    - Can only install one of: twig/twig[v1.34.0, v2.5.0].
    - Can only install one of: twig/twig[v1.34.1, v2.5.0].
    - Can only install one of: twig/twig[v1.34.2, v2.5.0].
    - Can only install one of: twig/twig[v1.34.3, v2.5.0].
    - Can only install one of: twig/twig[v1.34.4, v2.5.0].
    - Installation request for twig/twig (locked at v2.5.0) -> satisfiable by twig/twig[v2.5.0].

So it appears I'm getting not only the error with robrichards package, but a compatibility issue with twig as well. Is simplesamlphp able to even run in symfony 4? Any information or insight would be greatly appreciated.

**Comment by tvdijen** [comment]
Symfony 4 uses Twig 2, which requires PHP7.
SimpleSAMLphp 1.16.2 uses Twig 1, because we support PHP<7... There's your conflict!
Lucky for you, this will be solved in the next 1.17 release!

**Comment by tweismanBC** [comment]
Thanks tvdijen, when can we expect 1.17 to be released?

**Comment by tvdijen** [comment]
We're nearly done! https://simplesamlphp.org/releaseplan
I expect a release candidate over the next few weeks..

**Comment by tweismanBC** [comment]
> We're nearly done! https://simplesamlphp.org/releaseplan
> I expect a release candidate over the next few weeks..

Thanks tvdijen! Also I tried installing from dev-master and this is the error I received this time and it's only one error.

Problem 1
    - Installation request for simplesamlphp/simplesamlphp master -> satisfiable by simplesamlphp/simplesamlphp[dev-master].
    - simplesamlphp/simplesamlphp dev-master requires symfony/config ^3.4 -> no matching package found.

Looks like if you remove the dependency on symfony/config ^3.4 it may actually take via composer?

**Comment by tvdijen** [comment]
That must be some local issue on your end because I could just install it:

```
bash-4.2$ /apps/installation/composer/composer.phar update symfony/config
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating symfony/config (v3.4.18 => v3.4.19): Downloading (100%)
Writing lock file
```

**Comment by tweismanBC** [comment]
> That must be some local issue on your end because I could just install it:
> 
> ```
> bash-4.2$ /apps/installation/composer/composer.phar update symfony/config
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 0 installs, 1 update, 0 removals
>   - Updating symfony/config (v3.4.18 => v3.4.19): Downloading (100%)
> Writing lock file
> ```
> Perhaps you need to clear your composer-cache?

So I attempted to install symfony/config on my local system in a symfony 4.1.8 build. Symfony 4.1 cannot and refuses to install 3.4 and instead wants to require symfony/config 4.1.* > 

I think an acceptable fix would be to change the require on simplesamlphp/simplesamlphp to symfony/config 3.4 | 4.1 rather then only 3.4 as 3.4 is a pretty dated package? Is there any reason to require symfony/config 3.4 in particular and not move forward with their updated package.

**Comment by tvdijen** [comment]
We need 3.x because we still support PHP5 and Symfony 4 has a minimum of PHP7.
I've added the `|| ^4,0` version constraint to all symfony-related packages on `master`. Does that fix your problem?

**Comment by tweismanBC** [comment]
Yeah that worked! Everything installed and all dependencies were added via composer. Thank you for taking the time to add 4.0 as a version.

Leaving 3.4 as an alternative as you've done makes sense since you're still supporting PHP5. This just also allows updated versions of Symfony specifically 4.1 to install it's minimum dependencies as well. Now that it actually installed I'll make sure the actual service provider bits are working on my end and get back to you if we experience any hurdles. This was a huge help, so thank you again!
