### ISSUE TITLE
Could not find the metadata of an IdP with entity ID upon logout

### ISSUE THREAD

**Issue by deep80** [simplesamlphp/simplesamlphp#1007]
Right now i am working an a project that requires SSO using SAML and Okta as IDP. I'm completely new to this concept and had no prior idea of SAML. I am using simplesamlphp toolkit for this.

Here's my demo of what i made before finally moving onto production.

http://okta.karmickdev.com/simplesamlphp/www/
This thing is playing the role of IDP as well as SP. Connected to Okta IDP as SP and serving as IDP to other sites. the urls are as follows:

http://okta.karmickdev.com/simbus/ (Alias: Site A)
http://karmickdev.com/supplysir/site-two/ (Alias: Site B)

Both the sites above have simplesaml in them (E.g. http://okta.karmickdev.com/simbus/simplesaml/www) to make them saml enabled. I first developed the sites locally by creating apache vhosts. It's working fine in my local machine. But it's not working in a hosting environment. rather it's behaving strangely especially during single logout. Login in successfull.

Here's the issue. 

![screenshot from 2018-11-30 17-29-30](https://user-images.githubusercontent.com/10944348/49288021-8ad8d180-f4c5-11e8-87d0-0bd22e9fcfcb.png)

It's giving me exception 'Could not find the metadata of an IdP with entity ID'.

Please advice on this.

**Comment by jaimeperez** [comment]
Hi @deep80,

This is an issue tracker, not a support forum. Please ask [in the mailing list]() for help on using the software. One thing you should take into account is that you should only expose the `www` directory through your web server, as explained [in the documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_6). If you don't do so, you may end up exposing [your own private keys](http://okta.karmickdev.com/simplesamlphp/cert/) or any other sensitive information.
