### ISSUE TITLE
namespaces: still a lot deprecation warnings

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1010]
**Describe the bug**
Despite de fact that all classes have been migrated to namespaces, I still see a lot of deprecation-warnings in the logs..

**To Reproduce**
1. Turn debug-logging on.. Actually level 4 (INFO) is enough for this
2. For example, try an authentication flow
3. See logfile

**Expected behavior**
The log-line below shouldn't occur., because everything has been migrated. It's just a few of many (equal) lines that are printed.

**Screenshots or logs**
Dec  2 18:16:57 webapp-1 simplesamlphp-idp[3172]: 4 [39c1af90a2] The class or interface 'SimpleSAML_Utilities' is now using namespaces, please use 'SimpleSAML\Utilities'.
Dec  2 18:16:57 webapp-1 simplesamlphp-idp[3172]: 4 [39c1af90a2] The class or interface 'sspmod_core_Stats_Output_Log' is now using namespaces, please use 'SimpleSAML\Module\core\Stats\Output\Log' instead.

**Comment by jaimeperez** [comment]
I think the warnings regarding `SimpleSAML_Utilities` are coming from the SAML2 library. However, the ones on `sspmod_core_Stats_Output_Log` puzzle me. Have you tried grepping for that in your SSP installation? If there's absolutely no code using that class name, you should never get the warning...

**Comment by tvdijen** [comment]
I did grep, also on the SAML2 library.. In fact, I have replaced all old namespaces there in the 3.3.0 release.
My best guess is that it comes from the authproc-filters where translate something like `core:TargetedID` to a class-name.. Needs further investigation

**Comment by jaimeperez** [comment]
Uhm, that translation should be done in `SimpleSAML\Module`, and there it should already use namespaces... 🤔

**Comment by tvdijen** [comment]
I think on this line (https://github.com/simplesamlphp/simplesamlphp/blob/cbc727ce6b4c2941cb9ea22bdb831d37f1a01a1d/lib/SimpleSAML/Module.php#L400) we shouldn't use the autoloaders

**Comment by jaimeperez** [comment]
No more warnings in the log then?

**Comment by tvdijen** [comment]
Nope, all gone! :smile:
