### ISSUE TITLE
LDAP Client x509 Certificate Authentication

### ISSUE THREAD

**Issue by precurse** [simplesamlphp/simplesamlphp#1014]
Google announced their LDAP service: https://support.google.com/cloudidentity/answer/9089736 and we wanted to see if we could get it working for our users.

However, it requires a client certificate to authenticate to the server, which SimpleSAMLphp doesn't support: https://simplesamlphp.org/docs/stable/ldap:ldap . It seems to only support username/password for client authentication.

It would be nice to be able to support client cert/key for authentication in addition to username/password. OpenLDAP supports it using TLS_CERT and TLS_KEY.

Thanks!

**Comment by tvdijen** [comment]
PHP's LDAP-module isn't very well documented, but if my assumptions are right, providing a cert isn't supported until PHP 7.1:  http://php.net/manual/en/function.ldap-set-option.php

**Comment by tvdijen** [comment]
@precurse  Would you mind filing this issue again at https://github.com/simplesamlphp/simplesamlphp-module-ldap ? Thanks much!
