### ISSUE TITLE
Exception: Could not resolve 'sqlauth:SQL': no class named 'sspmod_sqlauth_Auth_Source_SQL' or 'SimpleSAML\Module\sqlauth\Auth\Source\SQL'. Backtrace:

### ISSUE THREAD

**Issue by ajaysoa** [simplesamlphp/simplesamlphp#1018]
Hi All,

We have installed SimpleSAMLphp 1.16.2 in my Ubuntu 16 system and php version is 7.1.24.

We have followed the steps which is mention in the below link.
https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-simplesamlphp-for-saml-authentication-on-ubuntu-16-04

Please see the below error.
**Describe the bug**
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Could not resolve 'sqlauth:SQL': no class named 'sspmod_sqlauth_Auth_Source_SQL' or 'SimpleSAML\Module\sqlauth\Auth\Source\SQL'.
Backtrace:
6 lib/SimpleSAML/Module.php:194 (SimpleSAML\Module::resolveClass)
5 lib/SimpleSAML/Auth/Source.php:314 (SimpleSAML_Auth_Source::parseAuthSource)
4 lib/SimpleSAML/Auth/Source.php:359 (SimpleSAML_Auth_Source::getById)
3 lib/SimpleSAML/Auth/Simple.php:56 (SimpleSAML\Auth\Simple::getAuthSource)
2 lib/SimpleSAML/Auth/Simple.php:160 (SimpleSAML\Auth\Simple::login)
1 modules/core/www/authenticate.php:36 (require)
0 www/module.php:135 (N/A)

**Screenshots**
![image](https://user-images.githubusercontent.com/45844938/49931185-51a05880-feec-11e8-86d8-c5b3da847ce1.png)

Please help us ASAP.

**Comment by tvdijen** [comment]
You need to enable the sqlauth module.
Please use the mailinglist for future support questions instead of filing a bug-report.
