### ISSUE TITLE
DigiD SAML requires more specific error handling

### ISSUE THREAD

**Issue by pdenooijer** [simplesamlphp/simplesamlphp#1019]
**Background:**
I am currently developing an Drupal 8 website that uses the [SimpleSAMLphp Authentication](https://www.drupal.org/project/simplesamlphp_auth) module to login as a user. This module uses this project as a service provider to handle the SAML login flow. We use the DigiD single sign-on service to authenticate our users. DigiD (Digital Identification) is a government-related online ID in the Netherlands.

**Problem**
To comply with the requirements the DigiD providers sets, we need to distinguish different SAML exceptions when logging in. Currently the implementation in the `SimpleSAML_exception_handler` function (`_include.php`) is limited to `SimpleSAML Errors`, generic `Exceptions` and `Errors`. Exceptions are currently shown in my domain when an SAML exception occurs. With a custom `errors.show_function` it is very hard to distinguish between the different exceptions. I would have to do a string search and compare in the `exceptionMsg`. To me this is not the best approach and with a big change on buggy results.

**Solution**
I use the following patch on SimpleSAMLphp 1.16.2 to quick fix the problem:
```
diff --git a/www/_include.php b/www/_include.php
index 7c18a252..cd8d1e43 100644
--- a/www/_include.php
+++ b/www/_include.php
@@ -13,6 +13,14 @@ function SimpleSAML_exception_handler($exception)
 
     if ($exception instanceof SimpleSAML_Error_Error) {
         $exception->show();
+    } elseif ($exception instanceof sspmod_saml_Error) {
+        $errorCode = [
+            0 => 'UNHANDLEDEXCEPTION',
+            'status' => $exception->getStatus(),
+            'sub_status' => $exception->getSubStatus()
+        ];
+        $e = new SimpleSAML_Error_Error($errorCode, $exception);
+        $e->show();
     } elseif ($exception instanceof Exception) {
         $e = new SimpleSAML_Error_Error('UNHANDLEDEXCEPTION', $exception);
         $e->show();
```
With this patch my errors show class can check if the parameters `status` & `sub_status` are set and use those accordingly. 

**Suggested better solution option 1**
Implement the hook `exception_handler` in the saml module to extract the data from the `sspmod_saml_Error` and put this in the parameters for later use in the `errors.show_function`.

**Suggested better solution option 2**
Implement the show function for all `SimpleSAML_Error_Exception` and use that in `_include.php` to just show the exception.

**Comment by pdenooijer** [comment]
Please discus this, so we could find a solution and I will find some time to implement this solution and provide the PR to merge this 🙂.

**Comment by jaimeperez** [comment]
Hi @pdenooijer!

What's preventing you from implementing all of this in a hook in your own module? The hook doesn't need to reside in the _saml_ module, so you can have your own module implementing just this hook if you want. You don't even need to use the `errors.show_function`, you can show it yourself with the information you've gathered.

**Comment by pdenooijer** [comment]
Ah I see it's possible to define a new module outside simplesamlphp with [composer-module-installer](https://github.com/simplesamlphp/composer-module-installer). Sadly did not find this in the documentation 😢.

**Comment by jaimeperez** [comment]
There is [documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-modules) on creating your own modules, although it doesn't mention the possibility to install them with composer (which came much, much later in time).

**Comment by pdenooijer** [comment]
Yes, this explains how to add a module in the SimpleSAMLphp module folder. Seeing we use composer to require all dependencies, we are not a big fan of changing those dependencies with like a symlink solution. That's why I was searching for an other approach to fix the problem I am facing 🙂.

**Comment by jaimeperez** [comment]
I see... Then that's precisely what _composer-module-installer_ is for, so that you don't have to worry about an upgrade throwing your custom module to the trash can...
