### ISSUE TITLE
newUI: jquery-ui is not available

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1020]
I noticed tabs were broken on the newui because the jquery-ui functions are not available..
Now, this has been temporarily fixed by manually loading the old jquery-ui 529ace9d0f8312872e5a02e65022f514e6a80d37 and 77fb41cde8cf0e85afa46ddc9a37d852b9d852bc..
Some further investigation learned me that, eventhough we have jquery-ui in our package.json, it needs to be exposed somehow in the webpack configuration..
Now, I know squat about Webpack and even with a bunch of howto's from the interwebz I couldn't get it to work, so help here is appreciated!

**Comment by jaimeperez** [comment]
I don't think there's anything we do that justifies the dependency on jquery-ui, so I would actually prefer to stop using it completely and implementing tabs in some other way (like in the admin module)...

**Comment by jaimeperez** [comment]
Not urgent in any way though, I don't think we need to have that in place for 1.17. Your solution to add it back is perfectly fine 😉

**Comment by thijskh** [comment]
Agreed that it is fine to add it explicitly as it's still needed, and then migrate those components away from it.

**Comment by ghalse** [comment]
> Ok, I think that would require us to modify the templates of consentAdmin, discopower and statistics to use your alternative.

A workaround that would allow you to stop shipping it with SSP simply for e.g. discopower would be to include it from code.jquery.com or another CDN only when it was required in those modules.

**Comment by tvdijen** [comment]
Since we're in the process of externalizing the modules, I think it's a good idea to include it there so our base repo is clean. Then we can create individual issues in the module-repos and they become someone else's problem :'D

**Comment by tvdijen** [comment]
For the newui the statistics-module now relies on the jQuery version shipped with SSP and includes the latest jquery-ui in the module itself. If we manage to do the same for discopower and consentAdmin, we can safely get rid of jQuery 1.8

**Comment by tvdijen** [comment]
All three modules mentioned above are now 1) externalized, 2) have their own copy of jQuery and 3) have their jQuery-version upgraded from 1.8 to 1.12.4.. It's a start!
Ideally we'd upgrade it up unto the version included in the SSP base repository, but that work may continue in the individual repositories.

Leaving this issue open as a reminder that we can safely remove jQuery 1.8 from the repo for SSP 2.0. Therefore also moving the milestone to 2.0
