### ISSUE TITLE
xh defined twice in dictionaries/login.translation.json

### ISSUE THREAD

**Issue by rcnsheppardp** [simplesamlphp/simplesamlphp#1022]
In 1.17-RC1 (and HEAD) dictionaries/login.translation.json language xh is defined multiple times with different strings for some of the translations.

**Comment by tvdijen** [comment]
Thanks for reporting this @rcnsheppardp !

@ghalse Could you please take a look at this and figure out which translations are the correct ones?

**Comment by dmcoetzee** [comment]
Thanks for letting us know! :-) file has been corrected, and pull request created
