### ISSUE TITLE
New Routing: breaks Apache Aliases (module

### ISSUE THREAD

**Issue by dbollaer** [simplesamlphp/simplesamlphp#1023]
I use apache aliases in Simplesamlphp to allow easier access to my custom module.

1. Create an alias in your apache config:
Alias /login.php "/var/www/simplesamlphp/www/module.php/core/www/authenticate.php"
2. Restart apache
3. Go to the page

**Expected behavior**
You will receive a page not found exception, with the following message:

SimpleSAML\Error\NotFound: The requested page 'http://localhost/login.php' could not be found. The URL must at least contain a module name followed by a slash.

In the past this used to just show the authenticate page.

When you look in the logs, you see that login.php page is in the front, normally it should not be part of the path and it replaced module.php.

**Screenshots or logs**
```
Dec 19 19:12:21 localhost simplesamlphp[8138]: 2 [a9caccd0cf] /login.php/core/www/authenticate.php - Localization directory missing/broken for langcode 'nl' and domain 'themes'
Dec 19 19:12:21 localhost simplesamlphp[8138]: 3 [a9caccd0cf] /login.php/core/www/authenticate.php - Something went wrong when trying to get path to language file, cannot load domain 'themes'.
Dec 19 19:12:21 localhost simplesamlphp[8138]: 3 [a9caccd0cf] SimpleSAML\Error\NotFound: The requested page 'https://localhost/login.php' could not be found. The URL must at least contain a module name followed by a slash.
Dec 19 19:12:21 localhost simplesamlphp[8138]: 3 [a9caccd0cf] Error report with id 9709a3dd generated.
```

**Additional context**
I rewrote some parameters, (privacy)

I use php7.1-fpm

If it is possible to use the routing directly, the aliases would no longer be necessary.

**Comment by tvdijen** [comment]
As a workaround/fix you could use:
`Redirect "/login.php" "/module.php/core/authenticate.php"`

We should probably mention this in the upgrade notes, but other than that I don't think there's a solution for this if we want to move forward with routing.

**Comment by dbollaer** [comment]
I understand you want to move forward and I will use your redirect in the meantime, but I will probably end up fixing it in the coming months. Could you please provide me some hint where I can start looking.

Also I was wondering why you did not go for full routing or is this something you plan for in the future.
I think having nice custom urls is one of the major benefits of using routing.

**Comment by tvdijen** [comment]
You should probably start with https://github.com/simplesamlphp/simplesamlphp/pull/966 and go from there. Maybe @jaimeperez can comment on this as well, as it was his idea.

Right now the functionality is limited to routing for modules and a showcase was added in the new admin module. It will be implemented for all modules in 1.18

**Comment by dbollaer** [comment]
Just to let you know, I patched it in my own version to use PATH_INFO instead of request.
```
diff --git a/lib/SimpleSAML/Module.php b/lib/SimpleSAML/Module.php
index 4cbd4165..69702d21 100644
--- a/lib/SimpleSAML/Module.php
+++ b/lib/SimpleSAML/Module.php
@@ -130,7 +130,8 @@ class Module
             throw new Error\NotFound('No PATH_INFO to module.php');
         }
 
-        $url = $request->getPathInfo();
+        $url = $_SERVER['PATH_INFO'];
+
         assert(substr($url, 0, 1) === '/');
 
         /* clear the PATH_INFO option, so that a script can detect whether it is called with anything following the
```
I don't think this is a good solution, but it seems to work.

**Comment by tvdijen** [comment]
Thanks @dbollaer !
I wonder though.. How are the values different? I would expect them to be equal

**Comment by dbollaer** [comment]
The difference is the lack of the module name:
```
$request->getPathInfo() => /url.php
$_SERVER['PATH_INFO'] => /module/url.php
```

**Comment by tvdijen** [comment]
Ahh, I see... The key here is that `$request->getPathInfo()` returns a value _relative_ to the current script (which is module.php)

**Comment by klausdk** [comment]
We just upgraded to simplesaml v1.17.1 and had the same issue.

Before we could use 

`Alias /cas /var/www/simplesamlphp/www/module.php/casserver/cas.php`

Now we use 

`RewriteRule ^/cas/(.*) /saml/module.php/casserver/cas.php/$1 [P]`

We had to use the [P] option because we have a service provider which for some reason failed when redirecting.

Hope it helps

/Klaus

**Comment by dbollaer** [comment]
@klausdk thank you for feedback.

I tried to implement it, but I am afraid it does not work in my use case.

We are using proxy:fcgi

Log
```
[Fri Mar 29 12:03:57.573250 2019] [proxy:warn] [pid 24642:tid 139907737540352] [client 157.193.49.84:60686] AH01144: No protocol handler was valid for the URL /login.php. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.
```
config
```
<FilesMatch ".+(\.php)$">
        SetHandler proxy:fcgi://127.0.0.1:9003
 </FilesMatch>
```

Note: Modules are loaded.

**Comment by klausdk** [comment]
> 
> 
> The difference is the lack of the module name:
> 
> ```
> $request->getPathInfo() => /url.php
> $_SERVER['PATH_INFO'] => /module/url.php
> ```

I wonder if the problem can be solved in the cas.php file instead.

It excepts PATH_INFO to contain url.php and not /url.php

Maybe it will help to do this change : 
```
$function = substr($_SERVER['PATH_INFO'], 1);
+// remove slashes
+$function = preg_replace('#/#','',$function);
```

**Comment by dbollaer** [comment]
First: with fix, I no longer enter the module.php, so it just doesn't work.
Sorry I should have more explicit.

Second: This is not really an option I prefer. I am using this also for other custom modules.
So one location is better for me.

**Comment by klausdk** [comment]
The main reason might be they switched to use symfony/httpfoundation for URL-handling.  ( Checkout  https://github.com/simplesamlphp/simplesamlphp-module-casserver/issues/18 )

So you might have to investigate in that area. But then it might break other things :-/

**Comment by dbollaer** [comment]
@jaimeperez thank you for fixing it. I ll test it this week.

**Comment by dbollaer** [comment]
I am very sorry I did not get back to you earlier.
Everything works like expected. Thank you very much!

**Comment by tvdijen** [comment]
This should have ended up in the 1.19 branch as well.. A release candidate is due later this week.
