### ISSUE TITLE
installed simplesamlphp-1.16.2 on Suse Linux Enterprise Server 12.3

### ISSUE THREAD

**Issue by shrikantbhagwat** [simplesamlphp/simplesamlphp#1025]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

Does is work on php7

**To Reproduce**

**Expected behavior**

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.

**Additional context**

**Comment by thijskh** [comment]
This is an issue tracker, not a support forum. Please direct your question to the [simpleSAMLphp user's mailing list](https://simplesamlphp.org/lists).

**Comment by shrikantbhagwat** [comment]
> PHP Notice:  Undefined offset: 1 in 
> /idm/idmt_home/simplesamlphp-1.16.2/modules/core/templates/frontpage_c
> onfig.tpl.php on line 71, referer: 
> http://sab-web-dev01.med.umich.edu/simplesaml/module.php/core/frontpag
> e_welcome.php

A "PHP Notice" is not an error. Esp if you have not modified that template file I wouldn't worry about it.

If you want something to be done about that notice I guess you'd need to provide more info about how you installed the software, what version of PHP you're running it with, etc. -- then report all that in an issue in the issue tracker.

-peter

**Comment by thijskh** [comment]
Said notice has been fixed in Git in 513d2a591d827d5002bda998a98368fd9799261c

**Comment by tvdijen** [comment]
Well... It was something I could relate to, so I've fixed what I could... Not entirely sure this will fix all of @shrikantbhagwat issues... I would not say this is fixed entirely, because the info is missing to ensure that...
