### ISSUE TITLE
Infinite recursion in autoloader

### ISSUE THREAD

**Issue by weirdan** [simplesamlphp/simplesamlphp#1030]
**Describe the bug**
`temporaryLoader` is prone to infinite recursion

**To Reproduce**
1. `git clone git@github.com:weirdan/simplesaml-autoloader-recursion.git`
2. `cd simplesaml-autoloader-recursion`
3. `composer install`
4. `php test.php`

**Expected behavior**
Shouldn't produce any errors

**Screenshots or logs**
```console
$ php test.php 
PHP Fatal error:  Uncaught Error: Maximum function nesting level of '256' reached, aborting! in /home/weirdan/src/simplesaml-autoloader-recursion/vendor/composer/ClassLoader.php:335
Stack trace:
#0 /home/weirdan/src/simplesaml-autoloader-recursion/vendor/composer/ClassLoader.php(321): Composer\Autoload\ClassLoader->findFile('RobRichards\\XML...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('RobRichards\\XML...')
#2 [internal function]: spl_autoload_call('RobRichards\\XML...')
#3 /home/weirdan/src/simplesaml-autoloader-recursion/vendor/simplesamlphp/simplesamlphp/lib/_autoload_modules.php(24): class_exists('\\RobRichards\\XM...', true)
#4 [internal function]: temporaryLoader('RobRichards\\XML...')
#5 [internal function]: spl_autoload_call('RobRichards\\XML...')
#6 /home/weirdan/src/simplesaml-autoloader-recursion/vendor/simplesamlphp/simplesamlphp/lib/_autoload_modules.php(24): class_exists('\\RobRichards\\XM...', true)
#7 [internal function]: temporaryLoader('RobRichards\\XML...')
#8 [internal function]: s in /home/weirdan/src/simplesaml-autoloader-recursion/vendor/composer/ClassLoader.php on line 335
```

**Additional context**
Refs vimeo/psalm#1162

**Comment by tvdijen** [comment]
Nice catch!

**Comment by weirdan** [comment]
What I've actually been doing is a research on the bug reported in Psalm, so I really have no idea  :laughing:

**Comment by tvdijen** [comment]
Yeah, I'm pretty sure that would fix it..  With `true` and your fix, we would eventually end up here:

https://github.com/simplesamlphp/simplesamlphp/blob/2042707a59f0febba831086982d4fbd8b5c17903/lib/_autoload_modules.php#L64-L69

With `false`, we'd basically be doing the same (except for the log-message)

**Comment by tvdijen** [comment]
I have fixed this on `master`, taking a slightly different approach by eliminating the recursion at all..
Could you give it a try?

**Comment by weirdan** [comment]
It appears the idea behind that part of code was to load `RobRichards\XmlSecLibs\<class_name>` where someone attempted to instantiate `<class_name>`.  Your fix drops that behavior, since XmlSecLibs PSR-4 autoloader is no longer triggered (unless corresponding class was already loaded).

I've added another test to verify this behavior is  preserved, and fixed undefined variable notice triggered by the log message.

**Comment by tvdijen** [comment]
Thanks @weirdan!

**Comment by weirdan** [comment]
You're welcome. Are you going to fix the test yourself?

**Comment by tvdijen** [comment]
Oh crap, I totally missed the failed test because you said you've found what you need...
I'll fix it

**Comment by weirdan** [comment]
> because you said you've found what you need

Turned out it was only a part (initializing a logger) of what was needed. I haven't been able to suppress the warning or otherwise catch it.

**Comment by tvdijen** [comment]
I can make the test run, but it always fails... I think the XMLseclibs autoloader doesn't run when tests are executed, so class_exists always returns false

**Comment by weirdan** [comment]
Is that assertion failure?

Locally I'm getting 
```PHPUnit_Framework_Exception: Jan 02 19:19:20 SimpleSAMLphp WARNING [CL29047d8f] The class or interface 'XMLSecEnc' is now using namespaces, please use '\RobRichards\XMLSecLibs\XMLSecEnc'.
```
indicating that autoloader works as expected, but the error is not handled properly in the test case.

I've added the following `setUp` method to get to that point:
```php
    public function setUp()
    {
        \SimpleSAML\Configuration::loadFromArray([], '[ARRAY]', 'simplesaml');
    }
```

**Comment by tvdijen** [comment]
Yeah, I did the exact same thing:

``
There was 1 error:
1) SimpleSAML\Test\AutoloadModulesTest::autoloaderSubstitutesNamespacedXmlSecClassesWhereNonNamespacedClassWasUsed
PHPUnit_Framework_Exception: Jan 02 19:59:20 SimpleSAMLphp WARNING [CLc2ae1f23] The class 'XMLSecEnc' is now using namespaces, please use '\RobRichards\XMLSecLibs\XMLSecEnc'.
FAILURES!
Tests: 398, Assertions: 1086, Errors: 1.
The command "if [[ "$TRAVIS_PHP_VERSION" == "5.6" ]]; then php vendor/phpunit/phpunit/phpunit; else php vendor/phpunit/phpunit/phpunit --no-coverage; fi" exited with 2.
``

**Comment by weirdan** [comment]
So that's the warning (converted to error by PHPUnit), which is kinda expected there as you explicitly logging it in the autoloader. The question is how to suppress / catch it in the testing environment.

**Comment by tvdijen** [comment]
Yeah, well this appears to be an error that can't be caught in a unit test...

**Comment by weirdan** [comment]
Keep in mind that dropping it means subsequent tests run in an environment slightly different from those preceding this test (`XMLSecEnc` class alias will persist, unless you isolate the test in a separate process). But then it's true for any autoloaded class, so it might not be a real issue.

**Comment by tvdijen** [comment]
I’m totally fine with that, unless you have a better way of catching this...
Already spent way too much time testing a piece of legacy code...

**Comment by weirdan** [comment]
I suspect properly addressing this would require changes to how logger behaves in cli environment so that `@runInSeparateProcess` could be used. Not going to pursue this though.
