### ISSUE TITLE
Using redis cluster ?

### ISSUE THREAD

**Issue by svgta1** [simplesamlphp/simplesamlphp#1037]
Hi everybody,

Is there a way to configure to using a redis cluster ? I don't find a good configuration. All I see is we can just give one host. But if the host is down, redis can't been accessed.

Regards.

**Comment by thijskh** [comment]
Currently only one host can be configured.

**Comment by tvdijen** [comment]
Is a cluster different from a redis sentinel? If not, then the work may have already been done:
https://github.com/simplesamlphp/simplesamlphp/pull/701
