### ISSUE TITLE
SmartID module no longer appending Authentication Authority

### ISSUE THREAD

**Issue by precurse** [simplesamlphp/simplesamlphp#1038]
Hello,

I recently upgraded from SSP 1.15 to 1.16 and noticed the Authentication Authority wasn't being appended to the attribute that SmartID was returning to TargetedID. Because TargetedID hashes this value, it changes all user IDs.

We use SSP as a SAML Proxy like so:
App + Shib SP <-> (Internal SSP IDP) / (Internal SSP SP) <-> (External SAML IDP)

We use SmartID since we also proxy for Microsoft and Google accounts using the cirrusidentity/simplesamlphp-module-authoauth2 module. 

We have debugged the issue and can confirm that this is the change that's causing the issues we've been experiencing: https://github.com/simplesamlphp/simplesamlphp/issues/841 and https://github.com/tvdijen/simplesamlphp/commit/e1d4a3b1374cfbf77625fe89beff1b8c73d483f8 . What's odd is that this was working fine before the change -- something the change was supposed to resolve. I'm wondering if it has to do with the fact we are proxying for another IDP?

In version 1.15, this is what we see when adding print statements to the TargetedID module:
```
$userID: batman@domain.example.com!https://domain.example.com/simplesaml/saml2/idp/metadata.php
```

After we upgraded to 1.16, this is what we were seeing:
```
$userID: batman@domain.example.com
```

When we switch between version, or this reverting this change, it goes back to the userID with the proper Authentication Authority added. 

This is the SmartID Config that's being used:
```
        20 => array(
            'class' => 'smartattributes:SmartID',
            'candidates' => array('eduPersonTargetedID', 'eduPersonPrincipalName')
            'add_authority' => TRUE,
            'add_candidate' => FALSE,
            'id_attribute' => 'smart_id',
        ),
```

Thanks!
Andrew

**Comment by tvdijen** [comment]
I'm pretty sure it's the proxy-mode that's causing this..

**Comment by precurse** [comment]
Hi @jaimeperez!

This change only seemed to affect when authenticating against external SAML IDPs. Google and Microsoft behavior stayed the same between versions: no Authenticating Authority added to the smartID attribute, so I'm not concerned with them.

I gave 1.16.3 a try, and am experiencing the same issue as 1.16.2. This issue is only when proxying  for SAML IDP entities. Google and Microsoft behavior hasn't changed between 1.15 and 1.16 -- in both versions there is no Authenticating Authority added to the SmartID attribute. 

I've dumped the `$request` while SmartID is being triggered, and I can't see any `saml:sp:State` key listed in it. 

I've also noticed this error in the logs being triggered, which could be related:
```
simplesamlphp[14218]: 3 [f2728db5c3] SimpleSAML_Error_Exception: Error 8 - Undefined index: saml:sp:State
```
Which is triggered by this line: https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.16/modules/smartattributes/lib/Auth/Process/SmartID.php#L83

Hope that helps.

Thanks!

**Comment by tvdijen** [comment]
Right, so you have basically two use-cases:
App + Shib SP <-> (Internal SSP IDP) / (Internal SSP SP) <-> (External SAML IDP)
App + Shib SP <-> (Internal SSP IDP) / Local authsource (Social ID)
Correct?

What Jaime tried to explain is that `saml:sp:State` is only set when the Internal SSP SP is being triggered, so that's why it's not working for both use-cases..

The AuthenticatingAuthority is something that is specific to SAML-proxies... In a one-on-one IDP/SP relation you will not see this field added to your SAMLresponse.

That said, I really wonder why it is set in the $request at all and where, because I can't find the code responsible for this... On a more pragmatic level, I'd say this is quite easy to fix like this:

```php
if (($this->add_authority)) {
    if (isSet($request['saml:sp:State'])) { // SAML proxy mode
        $authority =  $state['saml:AuthenticatingAuthority'][0];
    } else { // Fall back to local IDP entity ID
        $mh = \SimpleSAML\Metadata\MetaDataStorageHandler::getMetadataHandler();
        $mh->getMetaDataCurrentEntityID('saml20-idp-hosted');
    }
    return ($this->add_candidate ? $idCandidate.':' : '').$attributes[$idCandidate][0].'!'.
        $authority;
} else {
    return ($this->add_candidate ? $idCandidate.':' : '').$attributes[$idCandidate][0];
}
```

**Comment by precurse** [comment]
Thanks @tvdijen 

I was able to test this out, but still getting that same error: ` SimpleSAML_Error_Exception: Error 8 - Undefined index: saml:sp:State` . We'll continue to look into this over the next few days. 

Just to make sure we're on the same page, would this be considered "SAML proxy mode"?:
App + Shib SP <-> (Internal SSP IDP) - (Internal SSP SP) <-> (External SAML IDP)

And for the authentication flow:
User accesses the application and Shibboleth SP redirects user to the Internal SSP IDP. 
The user is presented with multiple SAML IDPs from the drop-down list and chooses their SAML IDP.
The user is redirected to their SAML IDP (the External SAML IDP above), which they authenticate against and their SAML Assertion is returned to our Internal SAML SP where SmartID + TargetedID is triggered.
Then their browser redirects back to Shibboleth SP and Application.

Thanks again!
Andrew

**Comment by tvdijen** [comment]
Hi Andrew,

All correct, we are on the same page..

The 'Undefined index' is my bad... My example code wasn't complete.. You'd also have to remove this line: https://github.com/tvdijen/simplesamlphp/blob/simplesamlphp-1.16/modules/smartattributes/lib/Auth/Process/SmartID.php#L83

**Comment by jaimeperez** [comment]
@precurse, I'm assuming when you say "_Internal SSP IDP_" and "_Internal SSP SP_", you actually mean the same instance of SimpleSAMLphp, with the IdP part enabled and configured in the SAML20 hosted metadata, and a SAML authentication source configured in the `authsources.php` file. Is that correct?

In that case, yes, we're on the same page, that's a proxy. As I said previously, the `saml:AuthenticatingAuthority` is set in the `saml20-acs.php` endpoint, where you get the SAML response from the "_external_" IdP. This is set in the state array, and later passed to the authproc filters  by the SP auth source inside the `$request['saml:sp:State']` array. This means the authproc filter **must be run by the _SP_**. Are you, by any chance, running the _smartattributes:SmartID_ filter on the "_internal_" IdP?

**Comment by jtopjian** [comment]
Hi all,

@precurse asked me to look into this while he's skiing for the next few days. That's fair.

> This means the authproc filter must be run by the SP. Are you, by any chance, running the smartattributes:SmartID filter on the "internal" IdP?

Yes, it looks like we had this misconfigured. For completeness, here's our before configuration:

```php
    'authproc.idp' => array(
        1 => array(
            'class' => 'core:AttributeMap', 'urn2name'
        ),
        20 => array(
            'class' => 'smartattributes:SmartID',
            'candidates' => array('eduPersonTargetedID', 'eduPersonPrincipalName', 'email', 'windowslive_targetedID'),
            'add_authority' => TRUE,
            'add_candidate' => FALSE,
            'id_attribute' => 'smart_id',
        ),
        21 => array(
            'class' => 'core:TargetedID',
            'attributename' => 'smart_id',
            'nameId' => FALSE,
        ),
        45 => array(
            'class'         => 'core:StatisticsWithAttribute',
            'attributename' => 'realm',
            'type'          => 'saml20-idp-SSO',
        ),
        50 => 'core:AttributeLimit',
        100 => array(
            'class' => 'core:AttributeMap', 'name2oid'
        ),
    ),

    'authproc.sp' => array(
        90 => 'core:LanguageAdaptor',
    ),
```

And here's after:

```php
    'authproc.idp' => array(
        1 => array(
            'class' => 'core:AttributeMap', 'urn2name'
        ),
        45 => array(
            'class'         => 'core:StatisticsWithAttribute',
            'attributename' => 'realm',
            'type'          => 'saml20-idp-SSO',
        ),
        50 => 'core:AttributeLimit',
        100 => array(
            'class' => 'core:AttributeMap', 'name2oid'
        ),
    ),

    'authproc.sp' => array(
        1 => array(
            'class' => 'core:AttributeMap', 'urn2name'
        ),
        20 => array(
            'class' => 'smartattributes:SmartID',
            'candidates' => array('eduPersonTargetedID', 'eduPersonPrincipalName', 'email', 'windowslive_targetedID'),
            'add_authority' => TRUE,
            'add_candidate' => FALSE,
            'id_attribute' => 'smart_id',
        ),
        21 => array(
            'class' => 'core:TargetedID',
            'attributename' => 'smart_id',
            'nameId' => FALSE,
        ),
        90 => 'core:LanguageAdaptor',
    ),
```

After implementing this, the user ID looks very similar to what we had before with SSP 1.15. The data is slightly different, since it's a different point of view, but it validates your ideas on where our problem was.

I'll review all of this with @precurse next week and see if he has any follow-up questions.

Thank you both for your patience. 🙂

**Comment by jaimeperez** [comment]
No problem @jtopjian! Glad we're on the right track now 😄
