### ISSUE TITLE
How do you create dictionary files for your own module? They don't seem to work for me.

### ISSUE THREAD

**Issue by dalemoore** [simplesamlphp/simplesamlphp#1040]
I've looked at the other modules included in the modules folder for examples to follow, but following them doesn't seem to work for me.

I've tried creating dictionary files in my own custom module to replace the terms from `simplesamlphp/dictionaries/login.definition.json`, by copying login.definition.json into `simplesamlphp/modules/module-name/dictionaries/login.definition.json` Then I changed the value of one of the key value pairs, for example:
```
"help_header": {
  "en": "Help! I don't remember my password."
},
```
to
```
"help_header": {
  "en": "Help! I don't remember my password. I'm dumb."
},
```

I then duplicated `simplesamlphp/modules/core/templates/loginuserpass.php` into `simplesamlphp/modules/module-name/themes/theme-name/core/loginuserpass.php`, made what changes I wanted, and updated the dictionary terms from, for example:

`echo('<h2>'.$this->t('{login:help_header}').'</h2>');`
to
`echo('<h2>'.$this->t('{module-name:login:help_header}').'</h2>');`

When I refresh the page, it says it's not translated. I've tried using a different name than login.definition.json (like modulename.definition.json), and updating the string to
`echo('<h2>'.$this->t('{module-name:modulename:help_header}').'</h2>');`

Still says not translated.

What am I missing?

**Comment by dalemoore** [comment]
Aaaand, of course, as soon as I post I figure out the issue. It doesn't work if you have dashes in your module's/theme's folder names. Never saw anywhere in the documentation you can't have dashes/underscores for readability.

**Comment by jaimeperez** [comment]
Hi @dalemoore!

I don't recall any particular changes to the code that handles this, so I'd say that limitation has always been in place, probably.

In any case, bear in mind that the old dictionaries will go away soon, same as the old templates.

**Comment by tvdijen** [comment]
@jaimeperez this relates to my earlier questions in the Valencia-app-group...
Is there any documentation on how this is supposed to work? Old and new style? I couldn't get it to work..

For my use-case I need to override the 'login:username' tag to say 'Email address' on the login-screen and I'd like to keep that override in my theme-module..

**Comment by jaimeperez** [comment]
Sorry Tim, I totally forgot about that. I don't think there's a way to override dictionaries in the old translation system, unfortunately...

**Comment by jaimeperez** [comment]
I believe it should be automatic, but I haven't tested. The thing is, when you are using a theme, you are getting your translations loaded _automagically_. Since we're getting rid of string IDs and using the strings themselves to index the translations, you would have the code search in the translation files available, and pick the first one. The only question here is whether the translation files registered for the module take precedence or not. If not, I think we should definitely fix that.

**Comment by tvdijen** [comment]
I got it working, thanks.. Seems that lots of the translations are in the locales files twice. In some cases I need the sentence-style tag, and for some other cases i need the {string} tags to make it work... We definitely need to sort them out!

**Comment by jaimeperez** [comment]
Yes, the idea is that tags would eventually just disappear in favour of the full text strings.
