### ISSUE TITLE
RequestedAttribute elements should have NameFormat

### ISSUE THREAD

**Issue by jiscfoo** [simplesamlphp/simplesamlphp#1044]
**Description**
Generated metadata with `<RequestedAttribute ...>` elements should be able to include a `NameFormat` value which is required by some federations.

See https://www.ukfederation.org.uk/content/Documents/RequestedAttribute

**To Reproduce**
In `authsources.php` -> `default-sp`:

```php
`'attributes' => array(`
            `'mail' => 'urn:oid:0.9.2342.19200300.100.1.3',`
        `),`
`'attributes.required' => array (`
            `'urn:oid:0.9.2342.19200300.100.1.3',`
        `),`
```

Generated metadata includes:

```xml
    <md:AttributeConsumingService index="0">
      <md:RequestedAttribute Name="urn:oid:0.9.2342.19200300.100.1.3" FriendlyName="mail" isRequired="true"/>
    </md:AttributeConsumingService>
```

**Expected behavior**

Generated metadata should include:

```xml
    <md:AttributeConsumingService index="0">
      <md:RequestedAttribute Name="urn:oid:0.9.2342.19200300.100.1.3" FriendlyName="mail" isRequired="true" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"/>
    </md:AttributeConsumingService>
```

**Comment by jaimeperez** [comment]
Hi Matthew!

As far as I know, the `NameFormat` is *optional*, so it's perfectly fine not to include it. If you want to include it in the `md:RequestedAttribute` elements of the metadata, you can do that easily by setting the `attributes.NameFormat` configuration option, [as described in the documentation](https://simplesamlphp.org/docs/stable/saml:sp).

**Comment by jiscfoo** [comment]
Just a thought, and I don't know if it would ever be needed in practice… if different Requested attributes needed different `NameFormat`s, this wouldn't let it work? It could be (optionally) another associative array (like the `attributes.required`) with an element for each requested attribute.
