### ISSUE TITLE
Incorrect Nginx config block in docs

### ISSUE THREAD

**Issue by neerolyte** [simplesamlphp/simplesamlphp#1047]
**Describe the bug**

The config block at https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_7 doesn't work completely.

**To Reproduce**

1. Use configuration snippet from https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_7
2. Try to auth SimpleSAMLphp as a SP
3. End up at a 404 of http://example.com/module.php/saml/sp/saml2-acs.php/another-sp

**Expected behavior**

The config to work for standard module behaviour.

**Additional context**

The block discussed in https://github.com/simplesamlphp/simplesamlphp/issues/751 is more accurate.

Specifically I changed:

```
    location ~ \.php$ {
```

to:

```
    location ~ \.php(/|$) {
```

**Comment by tvdijen** [comment]
Thanks @neerolyte ! I've updated the docs: 546f988fcfc8246e3c726c5b8e928627c998a705
