### ISSUE TITLE
Inconsistency in LDAP attribute resolution

### ISSUE THREAD

**Issue by m0ark** [simplesamlphp/simplesamlphp#1048]
[ldap_get_entries](http://php.net/manual/de/function.ldap-get-entries.php) returns lower case attribute keys while [ldap_get_attributes](http://php.net/manual/de/function.ldap-get-attributes.php) returns the original case.

In [modules/ldap/lib/Auth/Source/LDAP.php](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/ldap/lib/Auth/Source/LDAP.php) (resp. [modules/ldap/lib/ConfigHelper.php](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/ldap/lib/ConfigHelper.php)) `ldap_get_attributes` is used to fetch attributes (i.e. `eduPersonPrincipalName`).
In [modules/ldap/lib/Auth/Process/AttributeAddFromLDAP.php](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/ldap/lib/Auth/Process/AttributeAddFromLDAP.php) `ldap_get_entries` is used to fetch attributes (i.e. `edupersonprincipalname`).

Telling from having a look at the attribute maps SimpleSAMLphp seems to prefer the case sensitive notion of LDAP attributes, so this should be addressed somehow.

**Expected behavior**
Attribute keys should be fetched either in lower or original case, not both.

**Comment by tvdijen** [comment]
It is possible to define case-sensitive attributes in LDAP-schema's.. Even though this is rare, I think we should always keep the original case intact.
The catch is that this would be a potentially bc-breaking change that should probably wait until the next major release.

**Comment by tvdijen** [comment]
Hi @m0ark, would you mind filing this issue again @ https://github.com/simplesamlphp/simplesamlphp-module-ldap
