### ISSUE TITLE
Regex problem (dependency issue?)

### ISSUE THREAD

**Issue by vanrar68** [simplesamlphp/simplesamlphp#1057]
While testing a SAML authentication scenario with simplesamlphp 1.16.3  I bumped into the following exception:

Apache2 error.log:
[Thu Mar 07 11:06:09.705491 2019] [php7:warn] [pid 29] [client 172.17.0.1:44962] PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 8 in /usr/share/simplesamlphp/vendor/robrichards/xmlseclibs/src/Utils/XPath.php on line 42, referer: https://[edited]/simplesaml/module.php/core/loginuserpass.php?

SimpleSAMLPHP simplesamlphp.log:
Mar 07 11:06:09 simplesamlphp ERROR [e21c9e37d4] SimpleSAML_Error_Exception: Err
or 2 - preg_replace(): Compilation failed: invalid range in character class at offset 8

This problem shows up in the following context:
- Debian testing: simplesamlphp 1.16.3 -> php 7.3 -> libapache2-mod-php7.3 -> libpcre2
- Debian sid: simplesamlphp 1.16.3 -> php 7.3 -> libapache2-mod-php7.3 -> libpcre2

This problem doesn't show up in the following context:
- Ubuntu disco: simplesamlphp 1.16.3 -> php 7.2 -> libapache2-mod-php7.2 -> libpcre3
- Ubuntu cosmic: simplesamlphp 1.15.4 -> php 7.2 -> libapache2-mod-php7.2 -> libpcre3
- Ubuntu bionic: simplesamlphp 1.15.3 -> php 7.2 -> libapache2-mod-php7.2 -> libpcre3
- Ubuntu xenial: simplesamlphp 1.14.0 -> php 7.0 -> libapache2-mod-php7.0 -> libpcre3
- Debian stable: simplesamlphp 1.14.11 -> php 7.0 ->libapache2-mod-php7.0 -> libpcre3

My guess is that all linux distributions that still link with the old libpcre3 (Debian stable, all Ubuntus) are workging ok and all the distributions that link with the new libpcre2 (Debian testing, Debian sid, maybe others) are not. Something changed between libpcre3 (old version) and libpcre2 (new version) in the way char range are interpreted in regex and it now messes up with simplesamlphp.

Prerequisite: Ensure your php setup links against the libpcre2 library and that you have a remote IDP configured
1. Go to the SSPHP portal
2. Select "Authentication"
3. Select "Test configured authentication sources"
3. Select "default-sp"
4. Select an IDP
5. Authenticate on the IDP
6. Exception occurs after being redirected

**Comment by thijskh** [comment]
This is a PHP 7.3 specific issue in our depedency XmlSecLibs. SSP 1.17 rc3 has the updated version of XmlSecLibs so this should work for you. SSP 1.17 is to be released rsn. Alternatively you can composer update only this dependency.
