### ISSUE TITLE
"Federation" admin page / metadata generation

### ISSUE THREAD

**Issue by restena-sw** [simplesamlphp/simplesamlphp#1067]
**Describe the bug**

I see a discrepancy when I display the IdP metadata. In config, and in the "simpleSAMLphp flat file format", I have:

'UIInfo' => 
  array (
    'DisplayName' => 
    array (
      'en' => 'RESTENA Staff (internal)',
      'fr' => 'RESTENA Employees (interne)',
      'de' => 'RESTENA Mitarbeiter (intern)',
      'lb' => 'RESTENA Matärbeschter (intern)',
    ),
[...]

but the accompanying "in SAML 2.0 Metadata format" listing does not include any DisplayName. If one were to copy&paste that into a federation metadata, this would result in the entity not having a <DisplayName> at all (but I'm not doing that on this IdP).

**To Reproduce**

1. Use the following saml20-idp-hosted metadata:

$metadata['https://clueless-private.restena.lu/simplesaml/saml2/idp/metadata.php'] = array (
  'metadata-set' => 'saml20-idp-remote',
  'entityid' => 'https://clueless-private.restena.lu/simplesaml/saml2/idp/metadata.php',
  'SingleSignOnService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://clueless-private.restena.lu/simplesaml/saml2/idp/SSOService.php',
    ),
  ),
  'SingleLogoutService' => 
  array (
    0 => 
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://clueless-private.restena.lu/simplesaml/saml2/idp/SingleLogoutService.php',
    ),
  ),
  'keys' => 
  array (
    0 => 
    array (
      'type' => 'X509Certificate',
      'signing' => true,
      'encryption' => true,
      'X509Certificate' => 'MIIC/TCCAl+gAwIBAgIJANE6YfCisovgMAkGByqGSM49BAEwgZYxCzAJBgNVBAYTAkxVMRkwFwYDVQQHDBBFc2NoLXN1ci1BbHpldHRlMRswGQYDVQQKDBJSRVNURU5BIEZvdW5kYXRpb24xMDAuBgNVBAMMJ1N0YWZmIFNBTUwgSWRlbnRpdHkgUHJvdmlkZXIgLSBJbnRlcm5hbDEdMBsGCSqGSIb3DQEJARYObm9jQHJlc3RlbmEubHUwIBcNMTgwNDMwMDg0NjIzWhgPMjA3MzAxMzEwODQ2MjNaMIGWMQswCQYDVQQGEwJMVTEZMBcGA1UEBwwQRXNjaC1zdXItQWx6ZXR0ZTEbMBkGA1UECgwSUkVTVEVOQSBGb3VuZGF0aW9uMTAwLgYDVQQDDCdTdGFmZiBTQU1MIElkZW50aXR5IFByb3ZpZGVyIC0gSW50ZXJuYWwxHTAbBgkqhkiG9w0BCQEWDm5vY0ByZXN0ZW5hLmx1MIGbMBAGByqGSM49AgEGBSuBBAAjA4GGAAQBfHVZhrs2KFRdEa4hxVkg9XNYInDcC0a6RgA1ONMOkQIjeKc9XpynJkEMEXLfgZsm0OsfpLpiQZIsiSR33jnEm/wAgYWrmVdWumWhVGz716UR38pIDSqnRNIhFLyDzAw4LAWaEBjiGrA4SPp6j2U+AV6/EOBApjx5RNj0NZa5IaOuUPWjUDBOMB0GA1UdDgQWBBSajZblBUXfx63QQz+Uja1rqP9/WTAfBgNVHSMEGDAWgBSajZblBUXfx63QQz+Uja1rqP9/WTAMBgNVHRMEBTADAQH/MAkGByqGSM49BAEDgYwAMIGIAkIBQFFCc4YGASWxNl59di0oaQWwEMGi96qW0ZZl5qLuvrsxAll7FYL9GxXuULAMxFWvb0+y8EuHWlZmnVIrvcyAuX0CQgEwj47G8YRxjHcmuKhN+l+49CTyOOBy+7/WlvdITnCgjTGsGqM5zO3kLeHJqyxIQd8bKIn+qoLNU/uIOvIDH1q3Dg==',
    ),
    1 => 
    array (
      'type' => 'X509Certificate',
      'signing' => true,
      'encryption' => false,
      'X509Certificate' => 'MIIEVTCCAz2gAwIBAgICAIUwDQYJKoZIhvcNAQEFBQAwQTETMBEGCgmSJomT8ixkARkTA25ldDEVMBMGCgmSJomT8ixkARkTBWdlYW50MRMwEQYDVQQDEwplZHVHQUlOU0NBMB4XDTA4MDYwOTE3MzIzN1oXDTA5MDYwOTE3MzIzN1owXDETMBEGCgmSJomT8ixkARkWA25ldDEVMBMGCgmSJomT8ixkARkWBWdlYW50MRAwDgYDVQQKEwdSRVNURU5BMRwwGgYDVQQDExNjbHVlbGVzcy5yZXN0ZW5hLmx1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAucRIYLzcNxql3bx5d65fgT16vVfohwyb9zOfpgtuSe0UW/te/QqXG5K6Z5Nkw7n8YPyJpJ4bOWLspuGmSZ///NXr9Nw0HasXTZftkm96GDU6XCeJYrGZDnUXz8iMfj6fnlB/zkKJS9rxbkPGubqld69LfyJDCSxmcbb7WZ5xJs9EFF8RQc1pb5nXn76h6AiOwZUY5TsbyaEdQANZQ9NHTFkHuhHbIFzTz3uTMaRAv71mt2MYR4B1BEMX3zglbuyuQbHaid5kbWlDRYGy4tLvwMZisy/qeBzLnlN2SMlfnymMyyouzPHXyFbRGEv3cdoeVLmiYr5Ed45+XZSqV6UyAQIDAQABo4IBOjCCATYwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUNhT6nHMeCTwMNmTJebWWfQq84lkwHwYDVR0jBBgwFoAUiw+PJ4DSk9dGXZGEuy6YYq4E8dIwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjBjBgNVHREEXDBahlhodHRwczovL3JlZ2lzdHJ5LmVkdWdhaW4ub3JnL3Jlc29sdmVyP3Vybj11cm46Z2VhbnQ6ZWR1Z2Fpbjpjb21wb25lbnQ6aWRwOmZyZXNjbzpyZXN0ZW5hMDUGA1UdHwQuMCwwKqAooCaGJGh0dHA6Ly9zY2EuZWR1Z2Fpbi5vcmcvY3JsL2NhY3JsLmRlcjAbBgNVHSAEFDASMBAGDisGAQQBgdR+AQwCAAAEMA0GCSqGSIb3DQEBBQUAA4IBAQAEb26AIpWaWLQlhLg+mu2I/fboO0ERWJO0rDS3MSsagY0XtlrPOFwIyW9sfqIg16cYD+UuzhJp9m/rr5kW1tb+u3ndPRjvVBpaxta5afvdK6jtKfXR9jLxfH6GKvFg0AEq3vV6vLx/Tn+8YeumBAyk7M1ZDC/P5VuwDl4ilSSLQEAam+PorkG83qzwZ9b0M5Z6BQypsOActmOj12fjlOQfE7vMGJcdU/fluPf2UJCIAqunwcJ14b+wS+EfFh04UlJRA3Z7UHbxLu8gqVq1/Q2o75GMNESx3sKEIR/mG8SI8ZYlVXDOoWzHlEg5X0m8r6cbEm3CJ61h2vLCLIhMGGQ8',
    ),
  ),
  'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  'OrganizationName' => 
  array (
    'en' => 'RESTENA Foundation',
    'fr' => 'Fondation RESTENA',
    'de' => 'Stiftung',
    'lb' => 'Fondatioun RESTENA',
  ),
  'OrganizationDisplayName' => 
  array (
    'en' => 'RESTENA Foundation',
    'fr' => 'Fondation RESTENA',
    'de' => 'Stiftung',
    'lb' => 'Fondatioun RESTENA',
  ),
  'OrganizationURL' => 
  array (
    'en' => 'http://www.restena.lu/restena/en/EN-Presentation.html',
    'fr' => 'http://www.restena.lu/restena/fr/FR-Presentation.html',
  ),
  'UIInfo' => 
  array (
    'DisplayName' => 
    array (
      'en' => 'RESTENA Staff (internal)',
      'fr' => 'RESTENA Employees (interne)',
      'de' => 'RESTENA Mitarbeiter (intern)',
      'lb' => 'RESTENA Matärbeschter (intern)',
    ),
    'Description' => 
    array (
      'en' => 'Identity Provider for members of staff of RESTENA Foundation',
      'fr' => 'Fournisseur d\'Identité pour employés de la Fondation RESTENA',
      'de' => 'Identitätsprovider für Mitarbeiter der Stiftung RESTENA',
    ),
    'Keywords' => 
    array (
      'en' => 
      array (
        0 => 'RESTENA',
        1 => 'staff',
        2 => 'login',
      ),
    ),
    'Logo' => 
    array (
      0 => 
      array (
        'url' => 'https://clueless.restena.lu/restena.png',
        'height' => 100,
        'width' => 78,
        'lang' => 'en',
      ),
    ),
  ),
  'DiscoHints' => 
  array (
    'IPHint' => 
    array (
      0 => '158.64.0.0/16',
      1 => '2001:a18::0/32',
    ),
    'DomainHint' => 
    array (
      0 => 'restena.lu',
      1 => 'lu',
    ),
    'GeolocationHint' => 
    array (
      0 => 'geo:49.50,6.00',
    ),
  ),
  'contacts' => 
  array (
    0 => 
    array (
      'contactType' => 'other',
      'emailAddress' => 'mailto:csirt@restena.lu',
      'givenName' => 'RESTENA',
      'surName' => 'CSIRT',
      'company' => 'RESTENA Foundation',
      'attributes' => 
      array (
        'xmlns:remd' => 'http://refeds.org/metadata',
        'remd:contactType' => 'http://refeds.org/metadata/contactType/security',
      ),
    ),
    1 => 
    array (
      'emailAddress' => 'stefan.winter@restena.lu',
      'contactType' => 'technical',
      'givenName' => 'Stefan',
      'surName' => 'Winter',
    ),
  ),
);
2. Go to admin area.
3. Click on 'Federation' -> 'Show Metadata'
4. See error: XML does not contain DisplayName

**Expected behavior**
The generated XML snippet should contain a UIInfo/DisplayName block

**Additional context**

Another IdP, still running 1.15.x, converts correctly between the two formats. But this is also the only time I use (parentheses) in a display name; it could also be that.

**Comment by restena-sw** [comment]
This applies to 1.17.1

**Comment by tvdijen** [comment]
Just for the record, are you using the old endpoint /module.php/core/frontpage_federation.php or the new /admin/federation ?

My guess is that this is an issue in the saml2-library or in the way we're using it.

**Comment by tvdijen** [comment]
Speaking of the devil:
https://github.com/simplesamlphp/saml2/issues/168

This could very well be the case for you as well.. Can you check the ini-setting on your end?

**Comment by restena-sw** [comment]
I am using the old endpoint. How do I get the new one anyway? Just going to /simplesaml/admin/ doesn't work (redirects to module.php/admin which is not found).

**Comment by restena-sw** [comment]
zend.assertions is -1 here. I didn't see any negative consequences, so will wait for you fix.

**Comment by tvdijen** [comment]
That redirect shouldn't happen and is likely to be an issue on your webserver-configuration...
/simplesaml/admin/ (the last slash should be there) should just work

**Comment by restena-sw** [comment]
Right, our FPM handler was serving cached files from the old 1.15 installation which naturally resulting in fubar. A reload helped.

Just for the record, the generated XML is still the same - it is missing the entire UIInfo block, not just DisplayName. It was like that before, I didn't notice that the extent was larger when I submitted the issue.

**Comment by tvdijen** [comment]
It was in fact related to the saml2 library bug. I have released v3.3.9 of the library just now so you could run a `composer update` or wait for 1.17.2 to be released.
