### ISSUE TITLE
Feature request: Support for OpenID Connect

### ISSUE THREAD

**Issue by marclaporte** [simplesamlphp/simplesamlphp#107]
The main focus of SimpleSAMLphp is SAML 2.0 but simplesamlphp.org indicates that it also supports some other identity protocols, such as Shibboleth 1.3, A-Select, CAS, OpenID, WS-Federation and OAuth.

The natural next step is to support OpenID Connect:
- http://en.wikipedia.org/wiki/OpenID_Connect
- http://openid.net/developers/libraries/

Thank you!

**Comment by bradjones1** [comment]
@jaimeperez @marclaporte I would enjoy your feedback on https://github.com/BradJonesLLC/simplesamlphp-module-openidconnect

**Comment by tvdijen** [comment]
There are at least two composer-installable modules available, so this can probably be closed
