### ISSUE TITLE
\SimpleSAML\Auth\State::loadExceptionState() does not load the exception state.

### ISSUE THREAD

**Issue by pverbaan** [simplesamlphp/simplesamlphp#1077]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
`\SimpleSAML\Auth\State::loadExceptionState()` does not load the exception state anymore.

**To Reproduce**
The issue can be reproduced by testing an invalid  authentication source. The source in my example is invalid because there is no metadata configured for the _'unknown-idp'_ IdP.
1. Add the following authentication source to `config/authsources.php`:
>     'invalid-source' => [
>        'saml:SP',
>        'idp' => 'unknown-idp',
>     ],
2. Go to '/simplesaml/module.php/core/authenticate.php?as=invalid-source'
3. Observe the error (the page will attempt to redirect indefinitely)

**Expected behavior**
An error page showing an Unexpected error.

**Additional context**
The exception state is stored in the `$_REQUEST` array,
using the `\SimpleSAML\Auth\State::EXCEPTION_PARAM` constant. This constant contains a period (.), which is automatically translated to an underscore (_) by PHP. Because of this translation, the call to `array_key_exists()` will always return `false`, and the method will return `null`.

The constant value was changed from `'\SimpleSAML\Auth\State_exceptionId'` to `'\SimpleSAML\Auth\State.exceptionId'` in 1.17.1, which is the cause of this issue. Changing the underscore back to a period will restore the previous behaviour.

**Comment by tvdijen** [comment]
I remember changing this, because it didn’t match the other constants, nor did it match the documentation which specifically mentions the use of the dot.  If this is an issue here, then it may be an issue in other places as well

**Comment by pverbaan** [comment]
It should only be an issue for constants that are used as keys in special arrays such as $_REQUEST, $_GET and $_POST (maybe $_SESSION as well)?

**Comment by tvdijen** [comment]
Thanks.. Can you point me to the documentation that describes this automatic translation? I’m totally unaware of this behaviour

**Comment by pverbaan** [comment]
The official documentation is supposed to be here [http://ca.php.net/variables.external](url) but I didn't find it that clear.

I actually found the cause from this StackOverflow issue [](url)https://stackoverflow.com/questions/68651/get-php-to-stop-replacing-characters-in-get-or-post-arrays

**Comment by pverbaan** [comment]
Given the note from the documentation, it probably doesn't apply to $_SESSION. I haven't tested this though.

**Comment by tvdijen** [comment]
Thanks, I wil look into this asap

**Comment by thijskh** [comment]
Great research @pverbaan! I've checked it and indeed it seems on purpose how Olav named it originally. It's the only one of these constants used in _REQUEST context. Confirmed that the fix solved the problem.

**Comment by tvdijen** [comment]
I still wonder if _ would be the way to go on all constants... I want to make sure this can never happen again..

**Comment by thijskh** [comment]
What documentation does it contradict exactly? I did add a comment in my commit right above the constant definition that explains why it is different from the others.

**Comment by tvdijen** [comment]
This documentation:
https://github.com/simplesamlphp/simplesamlphp/blob/b701898dfcfa62b7f7ce2662dd1520635947aa70/lib/SimpleSAML/Auth/State.php#L8-L21

**Comment by pverbaan** [comment]
Well, the `EXCEPTION_PARAM` const isn't used as a key for the state array, so lines 8-9 of the documentation don't really apply.

Lines 20-21 seem to be about the value of the `STAGE` key, so that also doesn't really apply.

I'd say @thijskh's comment is more accurate in this case.

**Comment by tvdijen** [comment]
Ah right, so the documentation is technically right, but it's still confusing

**Comment by thijskh** [comment]
Indeed, different constants have different roles. I've added some more explicit documentation on why this is.
