### ISSUE TITLE
Class 'SimpleSAML\Module\saml\IdP\SAML2' not found

### ISSUE THREAD

**Issue by MarcusMoeller** [simplesamlphp/simplesamlphp#1091]
We have upgraded from 1.13.2 to 1.17.2 and now get an exception while calling the SAML2 module:

 SimpleSAML\Error\Exception: Error 1 - Class 'SimpleSAML\Module\saml\IdP\SAML2' not found at /var/simplesamlphp_1.17.2/www/saml2/idp/SSOService.php:21

**Comment by MarcusMoeller** [comment]
Backtrace:
simplesamlphp[50773]: 3 [994b082a9b] 2 /var/simplesamlphp_1.17.2/www/_include.php:48 (SimpleSAML_error_handler)
simplesamlphp[50773]: 3 [994b082a9b] 1 /var/simplesamlphp_1.17.2/www/_include.php:25 (SimpleSAML_exception_handler)
simplesamlphp[50773]: 3 [994b082a9b] 0 [builtin] (N/A)

**Comment by MarcusMoeller** [comment]
But in on-site customizations.

**Comment by shaheryar420** [comment]
I am having the same issue. U have closed the issue at your end can you guide me also on how u resolved this?

**Comment by Poggen** [comment]
We're also experiencing this issue. Did you manage to solve the issue, @shaheryar420 @LiohMoeller?

**Comment by jaimeperez** [comment]
How have you upgraded SimpleSAMLphp? If you are not using the package, you need to run composer to install dependencies and generate autoloaders.

**Comment by Poggen** [comment]
Yea, we just installed fresh with composer. 
```json
    "require": {
        "simplesamlphp/simplesamlphp": "^1.18",
        "simplesamlphp/composer-module-installer": "^1.1",
        [...]
    },
```

**Comment by jaimeperez** [comment]
Hi again,

I've just created an empty directory, and dropped the following `composer.json` on it:

```json
{
    "require": {
        "simplesamlphp/simplesamlphp": "^1.18",
        "simplesamlphp/composer-module-installer": "^1.1"
    }
}
```

I then installed with `composer install`. Everything gets into the `vendor` directory. If I go to the SImpleSAMLphp directory and run PHP, I can load the class without problems:

```php
php > include_once('www/_include.php');
php > $saml2 = new SimpleSAML\Module\saml\IdP\SAML2();
php > var_dump($saml2);
object(SimpleSAML\Module\saml\IdP\SAML2)#2 (0) {
}
```

**Comment by jahrralf** [comment]
So if anybody finds here because of the error message, in our case we had disabled the saml module because we followed some documentation too closely. This helped, notice the true for saml (from config.php):

```
    /*
     * Configuration to override module enabling/disabling.
     *
     * Example:
     *
     * 'module.enable' => [
     *      'exampleauth' => true, // Setting to TRUE enables.
     *      'consent' => false, // Setting to FALSE disables.
     *      'core' => null, // Unset or NULL uses default.
     * ],
     *
     */

    'module.enable' => [
         'exampleauth' => true, // Setting to TRUE enables.
         'saml' => true, // Setting to FALSE disables.
         'core' => null, // Unset or NULL uses default for this module.
    ],
```

**Comment by thijskh** [comment]
Thanks. This is indeed an unclear message, so I've improved our code to more explicitly check in the SAML IdP endpoints whether the module is actually enabled.
