### ISSUE TITLE
PHP error "Cannot change session name" after clicking Test configured authentication sources 

### ISSUE THREAD

**Issue by roeiben** [simplesamlphp/simplesamlphp#1092]
I use the newest simplesaml version (1.17.2) and the newest php version (7.3.4 - VC15 x64 Non Thread Safe). I installed the simplesaml succesfully but when I try to Test configured authentication sources or when I do a Sanity check of your SimpleSAMLphp setup I got the following error message:

`PHP Warning:  session_name(): Cannot change session name when headers already sent in C:\simplesamlphp_sp\lib\SimpleSAML\SessionHandlerPHP.php on line 72`
`PHP Warning:  session_id(): Cannot change session id when headers already sent in C:\simplesamlphp_sp\lib\SimpleSAML\SessionHandlerPHP.php on line 173`
`PHP Warning:  ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in C:\simplesamlphp_sp\lib\SimpleSAML\SessionHandlerPHP.php on line 225`
`PHP Warning:  session_id(): Cannot change session id when headers already sent in C:\simplesamlphp_sp\lib\SimpleSAML\SessionHandlerPHP.php on line 173`

1. Go to simplesaml
2. Sanity check of your SimpleSAMLphp setup or Test configured authentication sources 
3. See error

I already seen some errors like this one on the solved issue's. But the answers in there didn't solve my problem. What do I have to do to solve this? Thank you very much

**Comment by tvdijen** [comment]
Hi @roeiben!
Just so you know, I just closed https://github.com/simplesamlphp/simplesamlphp/issues/1006 a couple of days ago because we're unable to reproduce this.. I'm also running 7.3.4 NTS and I don't get any of those warnings..
Without being able to reproduce this, it's gonna be hard to solve this.

What is interesting though, is that both you and the original poster of #1006 are running Windows.. I guess that's a smoking gun..

**Comment by roeiben** [comment]
![Untitled](https://user-images.githubusercontent.com/49481961/55889092-d193b200-5bb0-11e9-838f-bc9fc30ba8fe.png)

I saw that issue indeed. But the difference is that he/she could proceed with the simplesaml. I can't. I put a screenshot with it to show what I got. 
So I can't proceed with simplesaml right now. When I at the following line in the php-file `echo "<script type='text/javascript'>window.top.location='http://website.com/';</script>"; exit;` the page will load. But it keeps refreshing, so I can't proceed with it to. So the only option is to proceed on linux?

**Comment by tvdijen** [comment]
That's one option, but the other option is to squash this bug!
Could you share the simplesamlphp-log with us? And perhaps the Apache server log?
There must be a hint in there, I'm sure of it...

**Comment by inblueswithu** [comment]
I can confirm that when switched to php:7.2-apache docker image from 7.3, I didn't get any of those errors and it also took care of the segmentation fault I was getting inconsistently.
There must be some configuration php7.3 is not liking from SimpleSAMLphp. I'll try to replicate the issue and share the docker file when I'm free.

P.S: I'm a participant in the #1006 issue.

**Comment by roeiben** [comment]
I solved the problem now. I'm not sure what it fixed. But I tried to copy a new config and a new saml20-idp-remote file and now the problem is not showing up anymore. I guess I made a little fault in one of that files.  So if someone else got this problem it's probably because there is something wrong with one of that files. The sad thing is that I don't have the old one's anymore so I can't really compare them. But I guess I made a mistake in of of the files with a syntax or I didn't copy all from  the parsed the XML file. 

But thank you for your time. btw, I didn't turned on the log on simplesaml so there was no information about it in it. The webserver log only displayed an 500 internal error.

**Comment by roeiben** [comment]
Okay I come once back more cause something changed again. The same problem was popping up today, while I did not change anything. So I trying the same solution as I did yesterday but this time it didn't work. The weird thing was that when I used the simplesaml for an idp instead of a sp it didn't give the same problem. But when I used all same settings again for a new host, the problem was popping up again.  So I was thinking to changed the host, but that didn't work either. The same problem was still there. So at the end I used 3 host. Where 1 was working but 2 host did not work. They all had the same configuration.
Next thing I did was downgrade the PHP version. So I downloaded and installed the 7.2.xx NTS version. Still the same problem occured..
Now I download a PHP version with the Web Platform Installer on IIS and all is working fine now. So my guess is that somehow simplesaml can't work fine with the windows NTS php version(s). So if someone is having the same problem, use the Web Platform Installer instead to install php. Just wanna let you know.

**Comment by tvdijen** [comment]
What you and the others described can imho never be a bug in SSP.. Feels like something on the IIS/PHP-for-windows side..

**Comment by totpet** [comment]
I noticed a very similar bug on the metadata page, I've created  a docker image for reproduction: https://github.com/totpet/docker-test-saml-idp

```
docker run --rm -p 9080:80 tothp/test-saml-idp:7.3
```

```
curl -v http://127.0.0.1:9080/simplesaml/saml2/idp/metadata.php?output=xhtml
```

➜ end of output:
`<b>Warning</b>:  session_name(): Cannot change session name when headers already sent in <b>/var/www/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php</b> on line <b>72</b><br />`

The warning is present on both PHP 7.3 and 7.2, but not no 7.1.

**Comment by dbollaer** [comment]
Hello, I might have encountered something similar, when developing a custom module.
When a logger gets called before a session is created, it creates a session. The solution for me, was to initiate a session before the logger gets called. Then I received type of error.


Could you please give it a try.

`
use SimpleSAML\Session;

$session = Session::getSessionFromRequest();
`

**Comment by totpet** [comment]
Hi @dbollaer ! Thanks, I was suspecting that logging is somehow involved, but didn't know where to fix the issue.

I pasted your snippet at [www/saml2/idp/metadata.php#L10 @ v1.17.3](https://github.com/simplesamlphp/simplesamlphp/blob/v1.17.3/www/saml2/idp/metadata.php#L10), which made warning disappear, but I'm not sure that that's the correct place to check for a session.
