### ISSUE TITLE
Problem with "single logout"

### ISSUE THREAD

**Issue by gunterunq** [simplesamlphp/simplesamlphp#1104]
[simplesamlphp.log](https://github.com/simplesamlphp/simplesamlphp/files/3118337/simplesamlphp.log)
Simplesamlphp versión 1.17.2 IDP:

- After closing session on a SP we are redirected properly to /module.php/core/idp/logout-iframe.php?id=_2ba0ca3c88fcb233b605b7573T16f5bea44b77d4b7

And then we see:

> You are now successfully logged out from SP-1.
> You are also logged in on these services:
> -	SP-2
> -	SP-3
> Do you want to logout from all the services above? 
> Yes, all services   No, only SP-1.
> 

- Answering "Yes" and waiting 5 seconds see this:

> Unable to log out of one or more services. To ensure that all your sessions are closed, you are encouraged to close your webbrowser.

But we verify on SP-2 and SP-3 that sessions are closed properly.

Doing a "refresh" in the web browser the warning disappears, and all appears to be good.

See attached log file fragment in debug mode, with no errors for me.

**Comment by jaimeperez** [comment]
Hi,

This is an issue tracker, not a support forum. If you need help using SimpleSAMLphp, you may ask in [the mailing list](http://groups.google.com/group/simplesamlphp).

In any case, it looks like those SPs are misbehaving. The fact that the actually close their sessions and that reloading the page makes the warning disappear does not mean there is a bug in SimpleSAMLphp. On the contrary, it indicates that the SPs are not replying properly with a SAML response after being requested to log out.

**Comment by gunterunq** [comment]
Hi,

Thanks for your help. I will try on the mailing list.
I just want to add that the problem does not exist if I use simplesamlhp version 1.16.3 as IDP, with the same configurations and SP.
