### ISSUE TITLE
Add support for sending email via SMTP rather than calling mail()

### ISSUE THREAD

**Issue by brycejlowe** [simplesamlphp/simplesamlphp#1108]
**Is your feature request related to a problem? Please describe.**
I am going through my SimpleSAMLphp environment to docker-ize it for hosting inside of Amazon ECS.  Currently I host it just on a Linux server which has access to the mail command, but my plan is to move it to a Docker container that might not.  It looks like the core email functionality in /SimpleSAML/XHTML/Email.php is just a wrapper around the mail() function.  Have you thought of replacing it with something like or PhpMailer or SwiftMailer?

**Describe the solution you'd like**
The end goal is to provide email connectivity from a Docker container with minimal dependencies and modification of php.ini.

**Additional info**
I would be happy to open a pull request to integrate PhpMailer into the project if you would like someone to do it, I wasn't sure what the roadmap for email was.

**Comment by thijskh** [comment]
You are in luck. Recently phpmailer was introduced in SimpleSAML: see #1058.

This was merged to master and will be part of 1.18. Maybe you can check out if that works for you as it has been implemented now?

**Comment by brycejlowe** [comment]
This was very close to what I needed.  I wanted to get able to remove the MTA dependency from my container and connect via SMTP to an external mail system.  I went ahead and made the changes necessary to use the SMTP functionality in PHPMailer.  I will be creating a PR momentarily of the changes I have made.

Please let me know if something needs to be changed.  I wrote a couple of new test cases as well, mostly validating the configuration piece (since I added two new keys into config.php).
