### ISSUE TITLE
saml:PersistentNameID2TargetedID does not add "NameFormat" to attribute

### ISSUE THREAD

**Issue by fkooman** [simplesamlphp/simplesamlphp#1135]
When using authproc `saml:PersistentNameID2TargetedID` the `NameFormat` attribute is missing from the `eduPersonTargetedID` (`urn:oid:1.3.6.1.4.1.5923.1.1.1.10`) raw attribute NameID.

It *is* added when using `core:TargetedID`.

The `NameFormat` has to be `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`, because otherwise, according to the specification it is `urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified ` which is no good...

**Comment by fkooman** [comment]
https://github.com/fkooman/php-saml-sp/compare/ssp-fix

**Comment by fkooman** [comment]
Hopefully this can be fixed in SSP soon, I don't plan to apply the `ssp-fix` to the code unless it turns out I read the SAML specification wrong... It should be trivial to fix in SSP, right? I'd have sent a patch for SSP, but there are few layers of abstraction too many to figure out where to do this exactly... Any hints?

**Comment by thijskh** [comment]
I think it might be a matter of interpretation. ePTID is guaranteed to be persistent so absense of a specific declaration the logic default would be that it’s persistent (since nothing else is allowed anyway).

Regardless it would be good to make it explicit to remove all doubt. I can look into that.

**Comment by fkooman** [comment]
> I'm not sure where the NameID-object used here is actually being created though..

That was exactly what I was wondering... :)

**Comment by tvdijen** [comment]
Yup, we've got a boo boo here... These are the contents of `$state['saml:NameID']`:

``
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]: 4 [5e3a422b30] array (
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:  'urn:oasis:names:tc:SAML:2.0:nameid-format:transient' =>
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:  SAML2\XML\saml\NameID::__set_state(array(
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'nodeName' => 'saml:NameID',
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'Format' => NULL,
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'SPProvidedID' => NULL,
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'value' => '_13a8606396c0f8a2c173c05c73e750d6215a45f74c',
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'NameQualifier' => NULL,
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'SPNameQualifier' => 'https://engine.openconext.moo-archive.nl/authentication/sp/metadata',
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'element' => NULL,
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:  )),
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:  'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent' =>
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:  SAML2\XML\saml\NameID::__set_state(array(
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'nodeName' => 'saml:NameID',
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'Format' => NULL,
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'SPProvidedID' => NULL,
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'value' => '22a4a39192e72d6c328e4ce3ca663283a4a660ab',
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'NameQualifier' => NULL,
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'SPNameQualifier' => 'https://engine.openconext.moo-archive.nl/authentication/sp/metadata',
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:     'element' => NULL,
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]:  )),
Jun  3 20:38:36 webapp-1 simplesamlphp-idp[18948]: )
``

**Comment by tvdijen** [comment]
It appeared to be a long standing issue, not related to recent changes.
@fkooman Could you test if this PR works for you?

**Comment by fkooman** [comment]
Unfortunately I don't have a simpleSAMLphp IdP running at the moment, I am reporting on behalf of another IdP, I can ask them to try and add the one-liner fix. Could be a nice unit test ;-)

**Comment by tvdijen** [comment]
Ohh, we could use a LOT more unit tests.. coverage is pretty low unfortunately.

**Comment by thijskh** [comment]
Seems like the proper fix, does the trick in my installation. Would be great if Paul could verify it.

**Comment by fkooman** [comment]
> Would be great if Paul could verify it.

He uses the Debian package, and manually patching it doesn't seem to work...

**Comment by fkooman** [comment]
I'm trying to figure out if this fix is part of any current release already? What is the expected release this will be fixed in? 1.18? I can then document that in my code. Thanks for the fix!

**Comment by jaimeperez** [comment]
Hi @fkooman!

It's not on a release yet, but will be in 1.17.5.
