### ISSUE TITLE
attributeencodings for idp-hosted

### ISSUE THREAD

**Issue by Jockel007** [simplesamlphp/simplesamlphp#1140]
In the example of this documentation (https://simplesamlphp.org/docs/stable/core:authproc_targetedid) the attributeencodings is useable in saml20-idp-hosted.php.

In the documentation of idp-hosted (https://simplesamlphp.org/docs/stable/simplesamlphp-reference-idp-hosted) this directive isn't listed. 

Using the attributeencodings in the file saml20-idp-hosted.php will change the encoding format.

**Comment by Jockel007** [comment]
Recommendation:

Adding the directive "attributeencodings" to the documentation of idp-hosted (https://simplesamlphp.org/docs/stable/simplesamlphp-reference-idp-hosted) like here in the sp-remote:
https://simplesamlphp.org/docs/stable/simplesamlphp-reference-sp-remote

**Comment by Jockel007** [comment]
Some code using the attributeencodings is modules/saml/lib/IdP/SAML2.php:

        $srcEncodings = $idpMetadata->getArray('attributeencodings', []);
        $dstEncodings = $spMetadata->getArray('attributeencodings', []);
        /*
         * Merge the two encoding arrays. Encodings specified in the target metadata
         * takes precedence over the source metadata.
         */
        $encodings = array_merge($srcEncodings, $dstEncodings);

**Comment by tvdijen** [comment]
Thanks @Jockel007! We will add the setting in the saml2-idp-hosted docs.
I see the list of options needs an alphabetical reorder as well!
