### ISSUE TITLE
Base URL rewriting is broken after 1.17.2 upgrade

### ISSUE THREAD

**Issue by ParhamG** [simplesamlphp/simplesamlphp#1142]
I have just upgraded from 1.16.2 to 1.17.2 and I am no longer able to access any of the web endpoints. I am receiving a page not found error:

> The given page was not found. The reason was: No PATH_INFO to module.php The URL was: https://site.com/simplesaml/module.php/core/frontpage_welcome.php

This is my rewrite rule in .htaccess:

`RewriteRule ^simplesaml/(.*)$ wp-content/lib/vendor/simplesamlphp/simplesamlphp/www/$1 [QSA,L]`

In config.php I have 

`'baseurlpath'            => 'https://site.com/simplesaml/',`

I tried to debug and I found out in `Symfony\Component\HttpFoundation->preparePathInfo()` right before building the `$pathInfo` the values for `$requestUri` and `$baseUrl` are as follows, and therefore `substr($requestUri, \strlen($baseUrl))` returns an empty string :

```
$requestUri: '/simplesaml/module.php/core/frontpage_welcome.php'
$baseUrl: '/wp-content/lib/vendor/simplesamlphp/simplesamlphp/www/module.php'
```

**Comment by tvdijen** [comment]
I think you shouldn't use RewriteRule to do this..
What happens if you do:
Alias /simplesaml /path/to/your/wp-site/wp-content/lib/vendor/simplesamlphp/simplesamlphp/www

**Comment by ParhamG** [comment]
@tvdijen Thanks for the comment! I ended up creating a symlink instead, as I wanted it to be portable across environments and not requiring Apache configuration and it worked great!
