### ISSUE TITLE
the actual SAML AuthnRequest received was not signed

### ISSUE THREAD

**Issue by devbanana** [simplesamlphp/simplesamlphp#1145]
I'm trying to set up simplesaml to communicate with a remote IdP from Aptify. Everything seems correct on my end but I get this error when attempting to login:

SAMLSSOServiceProvider__c.VerifySAMLResponseXMLSignature is checked but the actual SAML AuthnRequest received was not signed.

The thing is that I see the signature parameter in the query string.

I'm not sure if this is an issue with SimpleSAML or with the configuration of the IdP. Any ideas would be appreciated as I'm not very familiar with SSO.

**Comment by thijskh** [comment]
Hi. I do not understand that error message. It is not from SimpleSAMLphp I assume.

It talks about *response* signature being "checked" but the *request* was not signed (the SAML AuthnRequest goes in the direction of the IdP and the Response comes back to the SP, so they are different messages). I do not know how to reconcile that. If it's indeed an error from Aptify, it might be better to ask them what is going wrong.

**Comment by jaimeperez** [comment]
That's definitely not an error from SimpleSAMLphp.

In any case, it doesn't seem this is an issue with the software but a configuration/usage problem. If you need support with SimpleSAMLphp, you should probably use the [mailing list](http://groups.google.com/group/simplesamlphp).
