### ISSUE TITLE
Change SAML XML AuthnRequest

### ISSUE THREAD

**Issue by blu-regard** [simplesamlphp/simplesamlphp#1147]
The IdP i'm trying to send an authentication request to is expecting an XML formatted such as:
<saml2p:AuthnRequest

but my simplesamlphp is actually sending:
<samlp:AuthnRequest

How can I change the authentication request that is being sent out?

**Comment by tvdijen** [comment]
The IdP should be perfectly capable of processing the AuthnRequest, no matter what XML namespace is being used. You shouldn't have to change it..
