### ISSUE TITLE
Align website with GitHub milestone

### ISSUE THREAD

**Issue by foaadnami** [simplesamlphp/simplesamlphp#1148]
Website indicates next release is 1.17.3
GitHub milestones indicates next release is 1.18
Not a major issue but thought I highlight :)
Again thanks for the great project
Looking forward to the next release (when?)

**Comment by thijskh** [comment]
This is both true. We have the current stable branch, 1.17, where only bugfixes will be cherry picked on. The next point release for this branch will be 1.17.3. In parallel we're working on the next stable release for after 1.17, which includes new features and larger changes, which will be 1.18.

**Comment by tvdijen** [comment]
Where does the website indicate 1.17.3? The roadmap-page indicates 1.18?

**Comment by foaadnami** [comment]
In GitHub we dont have a 1.17.3 milestone
In the website, we have 1.17.3 in changelog page and 1.18 in roadmap page
Technically, if its not released (1.17.3) shouldnt it go into roadmap too ? Again, nothing major but hey its an observation :)

**Comment by tvdijen** [comment]
It’s hard to plan bugfix/security releases, so no, 1.17.3 shouldn’t be on the roadmap.. it may very well never be released..

The changelog on the website is the one from the master-branch.. perhaps it makes sense to use the one from the latest release if the GitHub API allows us to pick that one programmatically

**Comment by tvdijen** [comment]
I've checked the API and there is no such reference available.. Can't even get the commit that's related to the latest release, let alone the changelog that comes with it..
Only thing we can promise is that we don't add changelogs to `master` for bugfix-releases until we actually release it and keep them in the release-branch until then
