### ISSUE TITLE
Better Caching directives

### ISSUE THREAD

**Issue by ddmusc** [simplesamlphp/simplesamlphp#1149]
I noticed some situation whereby cache-control is not set to its best to tell browser not to cache.

In Particular I suggest this change in doRedirect() function in file  lib/SimpleSAML/Utilities.php line 265 shoudl be changed as follows:

From : 
`      // Disable caching of this response  ` 
`        header('Pragma: no-cache');`   
 `       header('Cache-Control: no-cache, must-revalidate');`   
 
To: 
`// Disable caching of this response`
      `  header('Pragma: no-cache');`
        `header('Cache-Control: no-cache, no-store, must-revalidate');`
  

I've also noticed that when an exception is thrown for unsupported passive authentication, SSOService.php will return a 200 with javascript to redirect for POST, with no Cache-Control and Pragma Headers. Unfortunately, I could not locate the right code to edit to have the headers inserted.

**Comment by tvdijen** [comment]
`lib/SimpleSAML/Utilities.php` is deprecated and is not actively being used and is not being used around the codebase anymore.

**Comment by tvdijen** [comment]
This shouldn't be an issue anymore.. Maybe on older versions or using the old UI.. We're not fixing the old UI anymore since we're so close to releasing a new major.
