### ISSUE TITLE
Cannot insert data in Microsoft SQL Server

### ISSUE THREAD

**Issue by sarbajitdutta** [simplesamlphp/simplesamlphp#1155]
I am using Microsoft Sql server for the data store it gives me this error- 
I have seen the tables that were created with prefix SimpleSAMLphp. What needs to be changed to fix this.

![image](https://user-images.githubusercontent.com/16959056/60451808-efdedc00-9bfa-11e9-8969-6dc797de44df.png)

**Comment by tvdijen** [comment]
The TIMESTAMP-type has a totally different meaning in MSSQL compared to other DBMS's..
The fix appears to be pretty straight forward:  change the column-type to DATETIME.

For reference:
https://stackoverflow.com/questions/10262426/sql-server-cannot-insert-an-explicit-value-into-a-timestamp-column

This probably needs fixing, but it need to run a few tests with other DBMS's. Thanks for reporting this and please let me know it the fix works for you!

**Comment by tvdijen** [comment]
Hi @sarbajitdutta ! It would be really helpful if you could run a test with the fix I just committed in cdd4236

**Comment by biuyy** [comment]
DATETIME does not exist in Postgresql.

**Comment by tvdijen** [comment]
I've commited a fix for Postgresql.. Could you see if it works for you?
