### ISSUE TITLE
Special characters in attribute value not escaped in XML

### ISSUE THREAD

**Issue by davidc** [simplesamlphp/simplesamlphp#1160]
Special characters in attribute values need to be escaped in XML. Specifically "objectSid" returned by ldap:LDAP is being transmitted in the XML with unescaped characters:

```<saml:Attribute Name="objectSid" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"><saml:AttributeValue xsi:type="xs:string">^A^E</saml:AttributeValue></saml:Attribute>```

```
00000000  3c 73 61 6d 6c 3a 41 74  74 72 69 62 75 74 65 20  |<saml:Attribute |
00000010  4e 61 6d 65 3d 22 6f 62  6a 65 63 74 53 69 64 22  |Name="objectSid"|
00000020  20 4e 61 6d 65 46 6f 72  6d 61 74 3d 22 75 72 6e  | NameFormat="urn|
00000030  3a 6f 61 73 69 73 3a 6e  61 6d 65 73 3a 74 63 3a  |:oasis:names:tc:|
00000040  53 41 4d 4c 3a 32 2e 30  3a 61 74 74 72 6e 61 6d  |SAML:2.0:attrnam|
00000050  65 2d 66 6f 72 6d 61 74  3a 75 72 69 22 3e 3c 73  |e-format:uri"><s|
00000060  61 6d 6c 3a 41 74 74 72  69 62 75 74 65 56 61 6c  |aml:AttributeVal|
00000070  75 65 20 78 73 69 3a 74  79 70 65 3d 22 78 73 3a  |ue xsi:type="xs:|
00000080  73 74 72 69 6e 67 22 3e  01 05 3c 2f 73 61 6d 6c  |string">..</saml|
00000090  3a 41 74 74 72 69 62 75  74 65 56 61 6c 75 65 3e  |:AttributeValue>|
000000a0  3c 2f 73 61 6d 6c 3a 41  74 74 72 69 62 75 74 65  |</saml:Attribute|
000000b0  3e                                                |>|
```

Related: https://github.com/Uninett/mod_auth_mellon/issues/178

Workaround: Remove the attribute by adding this to authproc:

```
'authproc.idp' => array(
...
         25 => array(
             'class' => 'core:PHP',
             'code' => 'unset($attributes["objectSid"]);'
         ),
...
);
```

**Comment by tvdijen** [comment]
How is removing it a workaround? Don't pull it if you don't need it..

**Comment by tvdijen** [comment]
What special characters would that be?

**Comment by davidc** [comment]
As shown, 0x01 and 0x05. But it is irrelevant what they are, where they come from, if they are correct, or even if they should be there at all.

The simple fact is that SimpleSAMLphp should always be generating well-formed XML and never put something on the wire that can't be parsed.

**Comment by tvdijen** [comment]
> What happens when someone has an attribute value with a "<" in it, for example?
That does exactly what it's supposed to do... There are only five characters in XML that should be escaped, being the ampersand, less than, greater than, single- and double quotes..

![afbeelding](https://user-images.githubusercontent.com/841045/61171080-b733f080-a572-11e9-93dd-d9ac1d328854.png)

0x01-0x08 are actually restricted characters in XML because they're control characters.. It doesn't make sense to me that you have them in an objectSid to be honest... I would need to investigate what the appropriate way is to handle them.. Either strip them or escape them..

**Comment by tvdijen** [comment]
I totally forgot that we keep a list of binary attributes in the code... It didn't include objectSid.
This patch will solve your issue:  https://github.com/simplesamlphp/simplesamlphp-module-ldap/commit/99764789907b4310cb9cd09d06bdce098bd7942e

**Comment by tvdijen** [comment]
Any luck @davidc ?

**Comment by davidc** [comment]
Apologies, I did not get a chance to test this until now.

My version is slightly different (1.16.3-1 from Debian Buster) but I made the equivalent change to what I believe is the same file:

```
# diff -u /usr/share/simplesamlphp/lib/SimpleSAML/Auth/LDAP.php~ /usr/share/simplesamlphp/lib/SimpleSAML/Auth/LDAP.php
--- /usr/share/simplesamlphp/lib/SimpleSAML/Auth/LDAP.php~      2018-12-20 18:26:28.000000000 +0100
+++ /usr/share/simplesamlphp/lib/SimpleSAML/Auth/LDAP.php       2019-08-06 11:11:43.651207099 +0200
@@ -414,7 +414,9 @@
                 // decide whether to base64 encode or not
                 for ($k = 0; $k < $attribute['count']; $k++) {
                     // base64 encode binary attributes
-                    if (strtolower($name) === 'jpegphoto' || strtolower($name) === 'objectguid') {
+                    if (strtolower($name) === 'jpegphoto' || strtolower($name) === 'objectguid'
+                        || strtolower($name) === 'objectsid'
+                    ) {
                         $results[$i][$name][$k] = base64_encode($attribute[$k]);
                     }
                 }
@@ -590,7 +592,9 @@
                 }

                 // Base64 encode binary attributes
-                if (strtolower($name) === 'jpegphoto' || strtolower($name) === 'objectguid' || strtolower($name) === 'ms-ds-consistencyguid') {
+                if (strtolower($name) === 'jpegphoto' || strtolower($name) === 'objectguid' || strtolower($name) === 'ms-ds-consistencyguid'
+                    || strtolower($name) === 'objectsid'
+                ) {
                     $values[] = base64_encode($value);
                 } else {
                     $values[] = $value;
```

However it does not help:

![image](https://user-images.githubusercontent.com/1050152/62527467-7c546e00-b83b-11e9-91a0-7502cb7ce588.png)

**Comment by tvdijen** [comment]
I've just tested and triple checked this on master..
Sending a control character leads to a 'Unable to parse XML string' exception without this fix in place.. With the fix in place, it works just fine..

**Comment by davidc** [comment]
Well I'm not sure what else I can do besides repost the screenshot of the XML message showing that it is still being sent unencoded. I'm also not sure what kind of exception you are referring to since it has never given an exception, it has just generated invalid XML that the receiver can't parse.

**Comment by tvdijen** [comment]
Well we're a good 1200 commits past v1.16.3 and a lot has changed..
The way I have been testing this is:

Adding an attribute containing the control characters mentioned:
``
         25 => array(
             'class' => 'core:PHP',
             'code' => '$attributes["foobar"][] = "foo".chr(1).chr(5)."bar";'
         ),
``
If I try to send this to an SP, SimpleSAMLphp prevents us from doing so because:
> DOMException: Error parsing XML string.

If I wrap a base64_encode around it, I send a base64-encoded string to the SP as we would expect..

**Comment by jaimeperez** [comment]
@davidc I fully agree with your statement that SSP should never create malformed XML (it's hard to disagree with that). However, note that the screenshot you attached does not demonstrate invalid characters in XML, as all of those are perfectly valid.

**Comment by antibarbie** [comment]
Hello, I just hit the same problem today with "userParameters", which, I guess should also be base64 encoded. 

The simpleSaml debug view show something ugly like this, and the XML parser chokes on 0x01 : 

```
userParameters | m:                     d                         PCtxCfgPresent㔵攱戰ぢCtxCfgFlags1〰て〲〹CtxShadow㄰〰〰〰*CtxMinEncryptionLevel㄰
-- | --

```

**Comment by tvdijen** [comment]
Thanks @antibarbie !
I'm going to try and find a generic solution for binary attributes instead of keeping a list of attributes in the code.

**Comment by tvdijen** [comment]
@antibarbie I've released a new version of the ldap-module that solves this. You can use `composer update simplesamlphp/simplesamlphp-module-ldap [--no-dev]` to install it. It will be included in a next version of SimpleSAMLphp

**Comment by enricocavalli** [comment]
Maybe I'm wrong but I think that as a side effect of this, objectGUID is no longer extracted correctly from LDAP - see https://groups.google.com/forum/#!topic/simplesamlphp/zR_J6kTQMJw

**Comment by tvdijen** [comment]
Hi @enricocavalli ! I've just released a new version of the ldap-module that should fix this the case from the mailing list... This should however have nothing to do with the original problem which has been almost a year ago

**Comment by tvdijen** [comment]
Would you mind running 'composer require simplesamlphp/simplesamlphp-module-ldap:v0.9.6' and see if that solves your issue?

**Comment by enricocavalli** [comment]
sorry  @tvdijen  for posting in this issue (I just saw it closed 14 days ago and not opened 1 year ago) anyway, module ldap v0.9.6 seems to work for me
thanks a lot
p.s. I suppose this fix will soon be included in a new release ?

**Comment by tvdijen** [comment]
I can't say for SSP, because we've only had a new release a couple of days ago.. Also, even though I maintain this module, releases are out of my control how funny that may seem..

There's no reason to not stick to 1.18.6 though, I mean there are no security related issues that require you to upgrade...
