### ISSUE TITLE
Wrong composer.json file after checking out new tag

### ISSUE THREAD

**Issue by semimodal** [simplesamlphp/simplesamlphp#1163]
**The master version of composer.json received instead of the version for 1.17.3?**

**To Reproduce**
1. git clone https://github.com/simplesamlphp/simplesamlphp.git
2. cd simplesamlphp
3. git checkout -b v1.17.3
4. composer install

**Expected behavior**
I expect to see the composer.json file that belongs to the  v1.17.3 tag, not the version that is currently in master (which is very different, with dependencies our setup cannot currently meet).

**Screenshots or logs**
```
composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for simplesamlphp/simplesamlphp-module-ldap v0.9.0 -> satisfiable by simplesamlphp/simplesamlphp-module-ldap[v0.9.0].
    - simplesamlphp/simplesamlphp-module-ldap v0.9.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
  Problem 2
    - Installation request for simplesamlphp/simplesamlphp-module-negotiate v0.9.0 -> satisfiable by simplesamlphp/simplesamlphp-module-negotiate[v0.9.0].
    - simplesamlphp/simplesamlphp-module-negotiate v0.9.0 requires ext-krb5 * -> the requested PHP extension krb5 is missing from your system.
  Problem 3
    - simplesamlphp/simplesamlphp-module-ldap v0.9.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
    - simplesamlphp/simplesamlphp-module-cas v0.9.0 requires simplesamlphp/simplesamlphp-module-ldap ^0.9 -> satisfiable by simplesamlphp/simplesamlphp-module-ldap[v0.9.0].
    - Installation request for simplesamlphp/simplesamlphp-module-cas v0.9.0 -> satisfiable by simplesamlphp/simplesamlphp-module-cas[v0.9.0].
```

**Additional context**
Experienced the same behavior for v1.17.2 as well.  Was able to restore the correct composer files manually, but for those people who are just getting started and cloning for the first time, this could be an issue for them.

**Comment by tvdijen** [comment]
This is because you checkout `master` and then create a new branch based on `master` called `v1.17.3`.
The correct syntax would be `git checkout tags/v1.17.3`
