### ISSUE TITLE
MetaDataStorageHandlerPdo::getMetaData() broken since 1.17.3 (no return value)

### ISSUE THREAD

**Issue by jhermans** [simplesamlphp/simplesamlphp#1165]
**Describe the bug**
After receiving several errors about metadata not being found, it turns out that `MetaDataStorageHandlerPdo::getMetaData()` simply has no `return` anymore after executing the database query. 
The last statement in `MetaDataStorageHandlerPdo::getMetaData()` is:
```php
        if (!$stmt->execute()) {
            throw new \Exception('PDO metadata handler: Database error: '.var_export($this->db->getLastError(), true));
        }
```
This should obviously be followed by processing of the statement results and returning the metadata, but this seems to be missing.

**To Reproduce**
Simply use any PDO metadata source.

**Expected behavior**
Non-null result from getMetaData()

**Additional context**
It seems that the resolution for issue #926 that was committed to the master branch did not end up completely in the 1.17-branch. The master branch version of `MetaDataStorageHandlerPdo::getMetaData()` includes processing of the pdo statement result.

**Comment by tvdijen** [comment]
It's really strange because I cherry-picked it into 1.17... I've just commited a fix

**Comment by ct27stf** [comment]
And could you please also update the tags so it can be available in composer

**Comment by BAGELreflex** [comment]
@tvdijen Is there any way you can tag this to 1.17.5?

We just ran into this issue and I was about to open a new issue about it, but found that it was fixed on master. Then I managed to track down this existing issue. We do not deploy updates from master, but instead from tags (i.e. `git checkout tags/v1.17.4 -b 1.17.4`). I have created a custom nagios plugin which alerts us when systems are using a non-tag branch (such as master), and alerts us if the systems are not on the latest tag. I've had to modify our plugin to accept 1.17.2 as an acceptable "latest version" in lieu of copying old code into place to patch this on each system, so we stop getting alerted.

**Comment by tvdijen** [comment]
1.17.5 is coming up soon! We're working on it..

**Comment by BAGELreflex** [comment]
I was looking at the changelog on master and saw it jump from 1.17.4, but I see now on the 1.17 branch that the changelog has 1.17.5 in the works. Thank you!
