### ISSUE TITLE
"Not allowed." when attempting to use SAML Login in Safari on a Drupal site

### ISSUE THREAD

**Issue by bradleymellen** [simplesamlphp/simplesamlphp#1167]
I believe this may actually be a browser bug in Safari.  I'm posting here both to see if anyone else has experienced it or can reproduce it, and also in the hopes that someone may be able to set me on the path to a reasonable workaround if there is one.  The site I'm seeing it on is a Drupal site, using the simplesamlphp_auth Drupal module.

**To Reproduce**
1. From the Drupal site, I click a link to use SAML login. (I am not currently logged into the SSO provider.)
2. The Drupal module responds to this path and hands things off to the simplesamlphp library, which 303 redirects me to the SSO identity provider to enter my login credentials. (I do so.)
3. I am redirected back to the SAML login path at the Drupal site, where
4. I get a plain, blank page that just says "Not allowed."  (I don't think Drupal's generating it.)
5. If I manually go to another page on the Drupal site, I'm still not logged in to Drupal.

**Expected behavior**
Upon being redirected back to the SAML login path at the Drupal site, code in the Drupal module should be finishing login and 302 redirecting me to another path on the site.  If I hit the refresh button I still get the "Not allowed." page, but if I manually go to the SAML login path again (by clicking the URL bar and hitting enter, or copying the path into another tab, or going back to the first Drupal page I was on and clicking the link to the SAML login again), then it successfully logs me into the Drupal site.

Our best theory currently is that Safari is getting confused by the initial 303 to the IDP somehow, perhaps caching it (along the lines of this very old bug report: https://discussions.apple.com/thread/5652283) the first time it hits the SAML login path, and therefore not correctly picking up on the different 302 redirect it should be getting (from the Drupal module) when it's sent back there after logging into the IDP.

**Additional context**
The site is using 8.x-3.0 of simplesamlphp_auth Drupal module, and 1.17.2 of the simplesamlphp library.

**Comment by tvdijen** [comment]
The Drupal-module has a configuration setting called `header_no_cache` with a default of `false`..
What happens if you set it to `true`?

**Comment by bradleymellen** [comment]
For the record, we already had the no cache setting on, and we also tried turning it off just for science; no difference.

**Comment by tvdijen** [comment]
Then I suggest you refer to the authors of the Drupal module.. We cannot help you with this.

**Comment by bradleymellen** [comment]
Understood, and thanks for the quick response.  And it's helpful to know that the "Not allowed." response isn't coming from the simpleSAMLphp library.

**Comment by tvdijen** [comment]
One thing that comes to mind is that 'Not Allowed' sounds a lot like 'Method not allowed' (HTTP/405). Could it be that you're returning to your application with the wrong SAML binding? (i.e. HTTP-POST instead in HTTP-REDIRECT)..
