### ISSUE TITLE
Please add a note to docu - No input file specified / php-fpm / fcgi 

### ISSUE THREAD

**Issue by vsatmydynipnet** [simplesamlphp/simplesamlphp#1170]
Hi,

i looked 2 days till i found a solution to my problem with "No input file specified" after Apache 2.4 / pHP 7.2 FCGI / php-fpm setup on FreeBSD.

"Alright, i found a fix.
You should enable the following setting in your php.ini file (and restart php-fpm)
cgi.fix_pathinfo=1"

Now i can access the web interface.

hank you for this cool software.

**Comment by tvdijen** [comment]
We're not documenting platform-specifics... An administrator should know this.
