### ISSUE TITLE
FreeBSD 11.2 /Apache 2.4 /PHP 7.2: "Failed to read FastCGI header" 

### ISSUE THREAD

**Issue by vsatmydynipnet** [simplesamlphp/simplesamlphp#1171]
HI,

Setup is FreeBSD 11.2 /Apache 2.4 /PHP 7.2. Everything works fine, except if browser is open longer and Simplesamle was startet in it once after some time, when trying to authenticate, I receive:

[Tue Jul 23 08:28:14.052467 2019] [proxy_fcgi:error] [pid 61747:tid 34498350336] [client XX.XXX.XXX.XXX:57416] AH01067: Failed to read FastCGI header

Already tried to disable opcache and ACPu, but none helps. On this server other stuff (Wordpress, aso. ) is running fine.

[23/Jul/2019:08:28:14 +0200] "GET /simplesaml/module.php/ad
min/ HTTP/2.0" 503 299 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60
.0 port:443"
I am out of ideas. We are short before opening the non-profit website, so any help would be greatly appreziated.

Thank you!

**Comment by vsatmydynipnet** [comment]
Updated PHP from 7.2.18 to 7.2.20 which is available on FreeBSD now. 503's are gone actually, will continue to test.

**Comment by vsatmydynipnet** [comment]
To bad, the AH01067: is back, so updating to 7.2.20 was no solution.

If I close Firefox and open again, everything works wthout doing anything on the server.

**Comment by tvdijen** [comment]
Hi @vsatmydynipnet !
This is an issue tracker, not a support forum.
You may find better respons on our [mailing lists](https://simplesamlphp.org/lists), however, this seems like a configuration issue, not a SimpleSAMLphp-issue.
