### ISSUE TITLE
no such function: _authSource

### ISSUE THREAD

**Issue by happydude** [simplesamlphp/simplesamlphp#1177]
**Describe the bug**
Starting in 1.17.5 when using sqlite driver on a new database (sqlite file does not exist) there is a sql error when creating the logout store.

**To Reproduce**
1. SSP as a SP
2. RequireAuth sends user to IdP
3. Upon return to the SP a PDOException occurs

**Screenshots or logs**
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: PDOException: SQLSTATE[HY000]: General error: 1 no such function: _authSource
Backtrace:
6 modules/saml/lib/SP/LogoutStore.php:96 (PDO::exec)
5 modules/saml/lib/SP/LogoutStore.php:96 (SimpleSAML\Module\saml\SP\LogoutStore::createLogoutTable)
4 modules/saml/lib/SP/LogoutStore.php:149 (SimpleSAML\Module\saml\SP\LogoutStore::addSessionSQL)
3 modules/saml/lib/SP/LogoutStore.php:285 (SimpleSAML\Module\saml\SP\LogoutStore::addSession)
2 modules/saml/www/sp/saml2-acs.php:204 (require)
1 lib/SimpleSAML/Module.php:236 (SimpleSAML\Module::process)
0 www/module.php:9 (N/A)
```

**Additional context**
Problem goes away if I downgrade to 1.17.4

**Comment by tvdijen** [comment]
I'm afraid I can fix this a hundred times, and every time one DBMS will choke...
I'm out of ideas.. I think we all are.. Not confident with database-related changes

**Comment by tvdijen** [comment]
Would any of you guys be able to run a test with this patch in place?
https://github.com/simplesamlphp/simplesamlphp/commit/ce99eafe7da2ece809bf4f5a565bdb8a9d7293df

I made the change in #1120 specific for MySQL, leaving other DBMS-es untouched (at least, that's the plan)

**Comment by happydude** [comment]
Running with ce99eafe7da2ece809bf4f5a565bdb8a9d7293df gives a PDOException of "SQLSTATE[HY000]: General error: 1 near ",": syntax error"

If I echo out the query string I just get ```', _nameID, _sessionIndex) )'```

It looks like the ternary is not preserving the whole query string. I changed
```php
        $query = 'CREATE TABLE '.$store->prefix.'_saml_LogoutStore (
            _authSource VARCHAR('.$store->driver === 'mysql' ? '191' : '255'.') NOT NULL,
            _nameId VARCHAR(40) NOT NULL,
            _sessionIndex VARCHAR(50) NOT NULL,
            _expire DATETIME NOT NULL,
            _sessionId VARCHAR(50) NOT NULL,
            UNIQUE (_authSource'.$store->driver === 'mysql' ? '(191)' : ''.', _nameID, _sessionIndex)
        )';
```
to have parenthesis
```php
        $query = 'CREATE TABLE '.$store->prefix.'_saml_LogoutStore (
            _authSource VARCHAR('. ($store->driver === 'mysql' ? '191' : '255').') NOT NULL,
            _nameId VARCHAR(40) NOT NULL,
            _sessionIndex VARCHAR(50) NOT NULL,
            _expire DATETIME NOT NULL,
            _sessionId VARCHAR(50) NOT NULL,
            UNIQUE (_authSource'.($store->driver === 'mysql' ? '(191)' : '').', _nameID, _sessionIndex)
        )';
```
and 
```php
$query .= $store->prefix.'_saml_LogoutStore (_authSource'.($store->driver === 'mysql' ? '(191)' : '').', _nameId)';
```
and that seems to resolve the issue

**Comment by tvdijen** [comment]
Ah, how stupid of me.. Thanks @happydude, this is really helpful!

**Comment by rcrawfords** [comment]
I've applied this patch, but it looks like it was specific to MySQL. I'm still receiving this error message when using SQLite.

**Comment by tvdijen** [comment]
Hi @rcrawfords !
After @happydude told us about a possible issue, an additional patch was made:
https://github.com/simplesamlphp/simplesamlphp/pull/1185/commits/810952a7a71bfbbe30240d2e46044a64e5d4be62
This should fix SQLite.. Let me know if this works for you

**Comment by rcrawfords** [comment]
Excellent, that worked! Thank you.

**Comment by Oxymoron290** [comment]
Hey guy, this worked for me too :+1: thanks!
