### ISSUE TITLE
ADFS idp for sharepoint integration incorrect claim mapping

### ISSUE THREAD

**Issue by dbollaer** [simplesamlphp/simplesamlphp#118]
When configuring sharepoint to use simplesamlphp as an adfs idp, after configuring sharepoint did not find my attributes
The attributes sharepoint was looking for was

$emailClaimMap = New-SPClaimTypeMapping -IncomingClaimType "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress" -IncomingClaimTypeDisplayName "EmailAddress" -SameAsIncoming

After applying the patch, the attributes came trough.

The mapping is incorrect when using default mapping guidelines.
If have already made a patch. But I want to be sure it's not a bad configuration on my case, before I create a pull request.

https://github.com/dbollaer/simplesamlphp/tree/adfs_claims_sharepoint

I am also planning on writing a small tutorial for people who want to do the same.

**Comment by abhinav-maheshwari** [comment]
Hey dbollaer, did you finally write the tutorial ? I am going to work on exactly same task, i.e. configuring simplesamlphp as idp for sharepoint. So just wanted to know which version of SharePoint did you use. I could complete the tutorial as I go about it, if you didn't get a chance, and thanks in advance for any pointers you have for me.

**Comment by dbollaer** [comment]
We are using sharepoint 2013.
I can always send you my configuration and my code changes.
Good enough for you?

**Comment by dbollaer** [comment]
http://omgimlovinit.blogspot.be/2014/10/configuring-simplesamlphp-adfs-sp-idp.html

Code change:
In modules/adfs/lib/IdP/ADFS.php


``` php
public static function after_last($symbol, $target){
        	if (!is_bool(sspmod_adfs_IdP_ADFS::strrevpos($target, $symbol))){
        		return substr($target, sspmod_adfs_IdP_ADFS::strrevpos($target, $symbol)+strlen($symbol));
        	}
        }
  	public static function before_last($symbol, $target){
        	return substr($target, 0, sspmod_adfs_IdP_ADFS::strrevpos($target, $symbol));
    	}
    	
	public static function strrevpos($instr, $needle){
    		$rev_pos = strpos (strrev($instr), strrev($needle));
    		if ($rev_pos===false){
    			return false;	
    		} else {
    			return strlen($instr) - $rev_pos - strlen($needle);
    		}
	}
	public static function ADFS_GenerateResponse($issuer, $target, $nameid, $attributes) {
	//	$nameid = 'UGENT\dbollaer';
		$issueInstant = SimpleSAML_Utilities::generateTimestamp();
		$notBefore = SimpleSAML_Utilities::generateTimestamp(time() - 3000);
		$assertionExpire = SimpleSAML_Utilities::generateTimestamp(time() + 60 * 800);
		$assertionID = SimpleSAML_Utilities::generateID();
		$nameidFormat = 'http://schemas.xmlsoap.org/claims/UPN';
		$result =
'<wst:RequestSecurityTokenResponse xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust">
   <wst:RequestedSecurityToken>
     <saml:Assertion Issuer="' . $issuer . '" IssueInstant="' . $issueInstant . '" AssertionID="' . $assertionID . '" MinorVersion="1" MajorVersion="1" xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion">
       <saml:Conditions NotOnOrAfter="' . $assertionExpire . '" NotBefore="' . $notBefore . '">
         <saml:AudienceRestrictionCondition>
           <saml:Audience>' . $target .'</saml:Audience>
         </saml:AudienceRestrictionCondition>
       </saml:Conditions>
       <saml:AuthenticationStatement AuthenticationMethod="urn:oasis:names:tc:SAML:1.0:am:unspecified" AuthenticationInstant="' . $issueInstant . '">
         <saml:Subject>
           <saml:NameIdentifier Format="' . $nameidFormat . '">' . htmlspecialchars($nameid) . '</saml:NameIdentifier>
         </saml:Subject>
       </saml:AuthenticationStatement>
       <saml:AttributeStatement>
         <saml:Subject>
           <saml:NameIdentifier Format="' . $nameidFormat . '">' . htmlspecialchars($nameid) . '</saml:NameIdentifier>
         </saml:Subject>';
		foreach ($attributes as $name => $values) {
			if ((!is_array($values)) || (count($values) == 0)) continue;
			$hasValue = FALSE;
			$r = '<saml:Attribute AttributeNamespace="http://schemas.xmlsoap.org/claims" AttributeName="' . htmlspecialchars($name) .'">';
			if(strpos($name,'/') !== FALSE) {
                        	$r = '<saml:Attribute AttributeNamespace="' . htmlspecialchars(sspmod_adfs_IdP_ADFS::before_last('/',$name)) . 
                                	'" AttributeName="' . htmlspecialchars(sspmod_adfs_IdP_ADFS::after_last('/',$name)) .'">';
                        }
			foreach ($values as $value) {
				if ( (!isset($value)) or ($value === '')) continue;
				$r .= '<saml:AttributeValue>' . htmlspecialchars($value) . '</saml:AttributeValue>';
				$hasValue = TRUE;
			}
			$r .= '</saml:Attribute>';
			if ($hasValue) $result .= $r;
		}
		$result .= '
       </saml:AttributeStatement>
     </saml:Assertion>
   </wst:RequestedSecurityToken>
   <wsp:AppliesTo xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"><wsa:EndpointReference xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing">
     <wsa:Address>' . $target . '</wsa:Address>
   </wsa:EndpointReference></wsp:AppliesTo>
 </wst:RequestSecurityTokenResponse>';
		return $result;
	}

´´´

**Comment by abhinav-maheshwari** [comment]
Thanks a lot, Danny. This is very much helpful. Thankfully, the version I
need to configure is also SharePoint 2013.

I am waiting for the SharePoint details from my customer and once received,
will configure and simultaneously complete the tutorial you started.

**Comment by dbollaer** [comment]
Perfect, looking forward to it.


For the configuration of sharepoint, you will need to do with powershell.
There are already some good tutorials with shibboleth for this.

Make sure you test if you submit all attributes. Debugging is painful.

For your sharepoint config.
your adfs-sp-remote.php should look like:

Will need:
``` php
$sharepointId="urn:sharepoint:$nameOfSharepoint";

$metadata[$sharepointId] = array(
 'prp' => "https://$sharepointServer/_trust/default.aspx",
// this depends on when you do your conversion of your attributes    
'simplesaml.nameidattribute' => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress',
//have fun
   );

**Comment by abhinav-maheshwari** [comment]
Thanks again, Danny :)

Configured simplesamlphp with Office 365 a month ago and there also
debugging was also quite painful, kept getting "some error occurred". Don't
know whats with MS and SAML !

**Comment by aletabu** [comment]
Hi guys,
I'm having troubles configuring the sharepoint integration with simplesamlphp using ADFS as idp.
Basically I configured the sharepoint claim based with the expected mapping, and the simplesamlphp part. When authenticates, seems that it works, no errors at all, but I'm being redirected to the login page again (no errors). I'm missing something? Perhaps a configuration on a ADFS server? I didn't do anything at the ADFS server, it's necesary or Sharepoint contains an ADFS plugin? Thanks,

Alejandro

**Comment by dbollaer** [comment]
Hello Alejandro,

What is your set-up? Simplesamlphp ADFS IDP=> ADFS server => sharepoint, or
Simplesamlphp ADFS IDP => sharepoint?
Could you show me your config. Have you decoded you "adfs response". To see
name attribute is present?
Have you configured your sharepoint to use your email address or other
attribute as an identifier?
Which version of sharepoint are you using?

Danny

**Comment by aletabu** [comment]
Hi Danny, thanks for your help.
My idea is to connect directly simplesamlphp with Sharepoint 2013 using claim based authentication.
I've read from this page that I can configure simplesamlphp as a ADFS IDP (using my custom auth method) and configure the remote sp with the Sharepoint prp endpint (created with the ADFS server).
I'm using the claims mapping UPN and EMAIL:
```
$attributemap = array(
	...
	'mail' => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress',
	'uid' => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn',
	...
);
```

Here  is simplesaml conf:

**adfs-idp-hosted.php**
```
$metadata['safewalk-gateway.ddns.net'] = array(
    'host' => '__DEFAULT__',
    'auth' => 'safewalk-native',
    22 => 'saml:NameIDAttribute',
      60 => array(
        'class' => 'core:TargetedID',
        'nameId' => TRUE,
    ),
    'simplesaml.nameidattribute' => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn',
    'metadata.sign.enable' => FALSE,
    98 => array('class' => 'core:AttributeMap', 'name2MyClaim'),
);
```

 **adfs-sp-remote.php**

```
$metadata['urn:sharepoint:safewalk'] = array(
        'prp' => "https://spoint/_trust/default.aspx",
        'simplesaml.nameidattribute' => 'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress',
        'authproc' => array(
                98 => array('class' => 'core:AttributeMap', '**name2MyClaim**'),
        )
);
```

> Note: the 'prp' (.../_trust) was configured from the ADFS server using that claims and with the 'urn:sharepoint:safewalk' identifier

The HTTP result status of the PRP is 302, then redirects to Authenticate.aspx (also 302 to the login page again). I don't see any error in the middle. If I pass out the wrong parameters I'm redirect to the forbidden site html.

Thanks a lot.

Alejandro

**Comment by dbollaer** [comment]
Could you pls include a decoded message, I want to see the xml response
send from simplesamlphp to sharepoint, after a successful authentication. I
thought it was the wcresult param.

**Comment by aletabu** [comment]
Here it is

```
wresult:<?xml version="1.0"?>
<wst:RequestSecurityTokenResponse xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust">
   <wst:RequestedSecurityToken>
     <saml:Assertion xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion" Issuer="safewalk-gateway.ddns.net" IssueInstant="2016-09-05T21:32:20Z" AssertionID="pfx4c7f9b4a-2309-9257-b3ae-2c384c4de448" MinorVersion="1" MajorVersion="1">
       <saml:Conditions NotOnOrAfter="2016-09-05T21:37:20Z" NotBefore="2016-09-05T21:31:50Z">
         <saml:AudienceRestrictionCondition>
           <saml:Audience>urn:sharepoint:safewalk</saml:Audience>
         </saml:AudienceRestrictionCondition>
       </saml:Conditions>
       <saml:AuthenticationStatement AuthenticationMethod="urn:oasis:names:tc:SAML:1.0:am:unspecified" AuthenticationInstant="2016-09-05T21:32:20Z">
         <saml:Subject>
           <saml:NameIdentifier Format="http://schemas.xmlsoap.org/claims/emailaddress">adfstest2@owl.idm</saml:NameIdentifier>
         </saml:Subject>
       </saml:AuthenticationStatement>
       <saml:AttributeStatement>
         <saml:Subject>
           <saml:NameIdentifier Format="http://schemas.xmlsoap.org/claims/emailaddress">adfstest2@owl.idm</saml:NameIdentifier>
         </saml:Subject><saml:Attribute AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims" AttributeName="upn"><saml:AttributeValue>adfstest2@owl.idm</saml:AttributeValue></saml:Attribute><saml:Attribute AttributeNamespace="http://schemas.xmlsoap.org/ws/2005/05/identity/claims" AttributeName="emailaddress"><saml:AttributeValue>adfstest2@owl.idm</saml:AttributeValue></saml:Attribute>
       </saml:AttributeStatement>
     <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
  <ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
    <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
  <ds:Reference URI="#pfx4c7f9b4a-2309-9257-b3ae-2c384c4de448"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>ZDrjzdXRyRyA1NGzHHiGbHGX1fY=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>P9QcpgTAZXnDvVXab2xoPzf+CyZJCiMcf5qKOJoMrEv91SHpavUnKRvuxxQgQF5qhiJV1LiEwoAVs+n0hlf3btm7GBVn38nL50q7QwLhpU77kugR/q7RH1j2ZjRO5eSHScEhX+ykfLJ5J3a20S3pjleaaBGHqUXhNORXC3TZAH7YG6wGYMFPuhxDwxD8/JoamrP/jt+y0u1y6sw1LGQfgo6fsgEKgokHJvV/jqjI6PdhFPkNRDHfZQAde+DWPnikfOw+BFiqcYi+1s0ZP1kx71OrpeBPtUaxuAHsiIENGgOrYfNuHRZam9afiRiD9Ym3qXKMEjAK1Kexys2HnzwKPw==</ds:SignatureValue>
<ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIDXTCCAkWgAwIBAgIJAJyf/2oy4hxPMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwHhcNMTYwODIzMTY0NTIxWhcNMjYwODIzMTY0NTIxWjBFMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA99Lq1s5aVIO9NAakzPJmIfR7o9RwfF/+kEf58LDgKrfHCSfoX7xJYqwNSb+szgKYq0C8B54YqwhWSOH7snwrYb+66IGRAbJq0zvX7YVNt0NT8NDnx6sDadVy9UBxMc//aQBArRLL272DgO9ijxlZPq6Rn6+O+WVK7XyY6ebwqOBBkyWZhJu2xP07Es8txnqeEW+0iVJp2Q9yYYW0nNlh+FoxqF/g3eHpH2FHZRybywxHQZixWuZkDlp+GrdIkA2VmKMVS/mP6MgeMDHSGGePe60cUNJLE8ht086VG15wuxtDoaOqJAa4oxWVxKVtdnOaU2YMTfGYhcUY5hc8eyV0MwIDAQABo1AwTjAdBgNVHQ4EFgQUs2AONbCPq6uAsThksdRCT6siR+AwHwYDVR0jBBgwFoAUs2AONbCPq6uAsThksdRCT6siR+AwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAFVFu4hrOXdPfRYiObkNqq8VTEdIcSnXEI9/e9VM5dPmO+dIScLcoboG6y/fzGiDMZRg3BT7O3sLhaC1g6z4uoNbR+68ihl87D10LgiV0yuqr6jjdnjdC0aE3XJskI4ILqXqyggCC2pbtJeiHO92eadunDnbZh8iYHkSeZp5a/MNfrka/jnAAz3Yp9dTeECfrV4Ythpj0K6Qfz7JejOoxxpFmpmuknryHS2i7kh9/G1+qtEYYXUCgsp5HKBz989ZxMODRb4qv0b3EQicpXkQ1sPNVivMJOVzfZ3n06ZbvIe+JGbIoZfnTPUh+uugVQ1rlt4fkF95d+bZEx08H79mvLA==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature></saml:Assertion>
   </wst:RequestedSecurityToken>
   <wsp:AppliesTo xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"><wsa:EndpointReference xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing">
     <wsa:Address>urn:sharepoint:safewalk</wsa:Address>
   </wsa:EndpointReference></wsp:AppliesTo>
 </wst:RequestSecurityTokenResponse>
wctx:https://spoint.safewalk.info/_layouts/15/Authenticate.aspx?Source=%2F
```

**Comment by dbollaer** [comment]
All looks good. So I think you will need to look in the configuration of the sharepoint.
Can you check the following:
- Sharepoint configuration, of the simplesamlphp metadata should be set to sha-1 (default is scha-256)
- Servers are in sync with NTP server.
- Mapping configuration with attributes.

**Comment by aletabu** [comment]
Thanks for your feedback!
Seems that at simplesaml and Sharepoint all the conf is OK. I guess there is some error in the ADFS relaying party trust.
- I already set sha-1.
- I guess I need to check the "Enable support for the WS-Federation Passive Protocol", right?
conf url: "https://spoint/_trust/"
Anything else?

**Comment by aletabu** [comment]
Here some logs: Seems that is authenticated but then is signed out and the cookie is removed (it says expired, but all the clocks are correct):

Claims Authentication         	ajrho	Monitorable	security token '0e.t|safewalk|adfstest2@owl.idm1811b230-cb37-4c16-b992-52b6ee762ee6_Default' is found in the local cache, but it is expired. Returing Null..	ef30a19d-f715-4041-2afd-a43a1279200d
09/06/2016 21:03:20.16 	w3wp.exe (0x27A8)                       	0x27F0	SharePoint Foundation         	Claims Authentication         	fr16	Verbose 	Token Cache: Entry missing for user '0e.t|safewalk|adfstest2@owl.idm'.	ef30a19d-f715-4041-2afd-a43a1279200d
09/06/2016 21:03:20.16 	w3wp.exe (0x27A8)                       	0x27F0	SharePoint Foundation         	Claims Authentication         	af30i	Verbose 	Token Cache: Failed to find token for user

**Comment by dbollaer** [comment]
http://sharepoint.stackexchange.com/questions/180435/sharepoint-2010-permissions-corruption-after-server-updates
Why not try experimenting with your token lifetime. Also don't forget to
clean your cookies.

Good luck. Alternative is setting up an adfs server in between, that works
perfectly.

**Comment by aletabu** [comment]
Thanks Danny! Playing with the token lifetime helped me a lot. Now I'm having a different issue but I guess I can handle.

Just a question, Is it possible to setup up simplesamlphp (as SAML IDP) with Sharepoint (as SP) without using a ADFS server (or an intermediary token service)?

Thanks for your great help again

**Comment by dbollaer** [comment]
Yes, I have set up both with and without adfs server in the past.
Could you please update me and this issue about your discoveries, so it
might help feature users.

**Comment by aletabu** [comment]
After running the following Poweshell commands and restarting IIS the token expiration problem was resolved. 

$sts = Get-SPSecurityTokenServiceConfig
$sts.FormsTokenLifetime = (New-TimeSpan -minutes 2)
$sts.WindowsTokenLifetime = (New-TimeSpan -minutes 2)
$sts.LogonTokenCacheExpirationWindow = (New-TimeSpan -minutes 1)
$sts.Update()

I'm using SharePoint 2013.
Now I'm getting an Access Denied to enter to the site. Perhaps I'm missing some claims or additional information.

I'll try in parallel to setup SAML directly with Sharepoint, do you have some tutorial?

Thanks,

Ale

**Comment by dbollaer** [comment]
Here is a copy of our documentation.

#Sharepoint
# Get signing certificate Simplesamlphp

# Add signing certificate to SharePoint
$Cert = New-Object
System.Security.Cryptography.X509Certificates.X509Certificate2("C:\temp\simplesamlphp.cer")

# Trust signing certificate in SharePoint
New-SPTrustedRootAuthority -Name "Simplesamlphp IdP" -Certificate $cert

# Define mappings in SharePoint STS
$emailClaimMap = New-SPClaimTypeMapping -IncomingClaimType "
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress"
-IncomingClaimTypeDisplayName "EmailAddress" -SameAsIncoming
$upnClaimMap = New-SPClaimTypeMapping -IncomingClaimType "
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn"
-IncomingClaimTypeDisplayName "UPN" -SameAsIncoming

# Specify Realm
$realm = "urn:SharePoint:TST"

# Login URL of IdP
$url= "https://simplesamlphp/module.php/adfs/idp/prp.php"

# Add Claims Based Authentication Provider to SharePoint
$ap = New-SPTrustedIdentityTokenIssuer -Name "Simplesamlphp" -Description
"Simplesamlphp as an ADFS IdP" -realm $realm -ImportTrustCertificate $cert
-ClaimsMappings $emailClaimMap,$upnClaimMap -SignInUrl $url
-IdentifierClaim $emailClaimmap.InputClaimType

# Define Logout URL
$ap = Get-SPTrustedIdentityTokenIssuer Simplesamlphp
$ap.ProviderSignOutUri = "https://Simplesamlphp/module.php/adfs/idp/prp.php
"
$ap.Update()

# Assign Authentication Provider to SharePoint WebApplication (Zone/url) in
Central Admin

#Simplesamlphp
#Enable adfs module
SIMPLESAMLPHP_HOME/config/config.php adfs
   'enable.adfs-idp'               => true,


    'module.enable' => array(
        'adfs'                  => true,
    ),


add metadata adfs (idp)
SIMPLESAMLPHP_HOME/metadata/adfs-idp-hosted.php


$metadata['__DYNAMIC:1__'] = array(
    'host' => '__DEFAULT__',
    'privatekey' => 'Simplesamlphp.key',
    'certificate' => 'Simplesamlphp.pem',
    'auth' => 'myAuth',
    'userid.attribute' => 'uid',
   'simplesaml.nameidattribute' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
    22 => 'saml:NameIDAttribute',
    60 => array(
        'class' => 'core:TargetedID',
        'nameId' => TRUE,
    ),
    'metadata.sign.enable' => FALSE,
    'authproc' => array(
        // Convert LDAP names to WS-Fed Claims.
        100 => array('class' => 'core:AttributeMap', 'name2claim'),
    ),
);



add metadata sp(sharepoint)
SIMPLESAMLPHP_HOME/metadata/adfs-sp-remote.php


$metadata['urn:SharePoint:TST'] = array(
    'prp' => 'https://sharepoint/_trust/default.aspx',
    'simplesaml.nameidattribute' => '
http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress',

);



Set expiration time token
  $notBefore = SimpleSAML_Utilities::generateTimestamp(time() - 3000);
   $assertionExpire = SimpleSAML_Utilities::generateTimestamp(time() + 60 *
800);

**Comment by aletabu** [comment]
Thanks Danny, I could make it work the simplesaml + ADFS integration (A site permission was missing).
I just read from your conf, you made the same scenario than me. Now I would like to use Sharepoint directly with simplesaml, excluding ADFS (In our case we are using the PRP: 'https://sharepoint/_trust/default.aspx', which is the ADFS endpoint we've defined from the ADFS)
Any idea? Maybe using Shib13 or saml2 idp?

**Comment by dbollaer** [comment]
One more thing, sharepoint and SAML directly does not work. Sharepoint can
talk only talk ADFS, the documentation talks about saml tokens. But not
SAML itself.

**Comment by aletabu** [comment]
Yes, I'm trying to find any ADFS replacement as I need to provide an "in box" solution for sharepoint without installing additional components (like one login does: https://support.onelogin.com/hc/en-us/articles/201173964-Configuring-SAML-for-SharePoint-2010-2013)
Seems they provide a passive requestor fed service that does the magic

**Comment by dbollaer** [comment]
Hello Alejandro,

We needed to use adfs for sharepoint because we could not get sharepoint to
work directly with saml. I don't think it is possible without the
additional component.
Also please don't forget to support logout functionality.

Good luck

**Comment by aletabu** [comment]
Yes, I had same experience as you. Thank you very much for your help Danny!
I'll update you if I discover something interesting

**Comment by tvdijen** [comment]
The ability to set attribute namespaces for Microsoft-product like Sharepoint and DynamicsCRM was added in https://github.com/simplesamlphp/simplesamlphp/pull/680 and is part of the 1.15 release. Closing this issue.
