### ISSUE TITLE
Package jaimeperez/twig-configurable-i18n is abandoned

### ISSUE THREAD

**Issue by porcospino** [simplesamlphp/simplesamlphp#1190]
**Describe the bug**

Installing v1.17.5 via composer I get the following error:

`Package jaimeperez/twig-configurable-i18n is abandoned, you should avoid using it. Use simplesamlphp/twig-configurable-i18n instead.`

This is because composer.lock calls for `jaimeperez/twig-configurable-i18n` instead of `simplesamlphp/twig-configurable-i18n`

**Comment by tvdijen** [comment]
This has already been fixed on master.

**Comment by porcospino** [comment]
Sorry.  I checked the Issues and the PRs.  Should've checked master.

**Comment by jaimeperez** [comment]
Hi @porcospino,

Note also that this is a warning, not an error, so you are still able to install SimpleSAMLphp.
