### ISSUE TITLE
SingleLogoutResponse.php returns raw twig template

### ISSUE THREAD

**Issue by melanger** [simplesamlphp/simplesamlphp#1191]
**Describe the bug**
In SimpleSAMLphp version 1.17.5, when not using the new UI and with logout type iframe, when logging out of multiple services, the raw twig template is returned (which results in invalid Javascript and unsuccessful logout from "all" services). This was probably introduced by e0da40397b7a98ddf4b

**To Reproduce**
1. Configuration
```
'usenewui' => false, // or not set

'logouttype' => 'iframe',
```
2. Log in to multiple services
3. Log out of all services
4. An error occurs, in dev console you can see the raw twig template.

**Expected behavior**
The template should be processed.

**Screenshots or logs**
![screenshot](https://i.postimg.cc/9M8gQSw6/rawtwig.png)

**Additional context**
I was able to fix this by setting `usenewui` to `true`, but this forces me to rewrite my theme to use the new UI as well.

**Comment by tvdijen** [comment]
Thanks for reporting this @melanger .. 
Could you try something out for me? Would it fix things if you replace `$t->show();` with `$t->send();`?

> [...] but this forces me to rewrite my theme to use the new UI as well
It is probably a good idea to start working on that anyway, but we should fix this nonetheless

**Comment by melanger** [comment]
If I replace
https://github.com/simplesamlphp/simplesamlphp/blob/8a4fe192f64046f4080333a57744c9c73456380e/lib/SimpleSAML/IdP/IFrameLogoutHandler.php#L101
with
```
$t->send();
```
there is no output and it results in an error:
```
SimpleSAML\Error\Exception: Error 1 - Call to a member function render() on boolean at /var/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:477
```
which is
https://github.com/simplesamlphp/simplesamlphp/blob/8a4fe192f64046f4080333a57744c9c73456380e/lib/SimpleSAML/XHTML/Template.php#L477

When I dump the template object, it has
```
"twig_template" => NULL
```

**Comment by tvdijen** [comment]
Hmm, yeah I could have expected that...  I know there is a workaround for parsing Twig-templates without initializing the whole newui, because we do it in a few other places as well.. Just gotta look it up..

**Comment by tvdijen** [comment]
Can you see what this does?
https://github.com/simplesamlphp/simplesamlphp/commit/f6d6e587c6cad30b34dc0acee2b4cc67011abf0c

**Comment by melanger** [comment]
When I replace the whole file (this means also introducing changes between 1.17.5 and master):
```
Undefined variable: template at /var/simplesamlphp/lib/SimpleSAML/IdP/IFrameLogoutHandler.php:123
```

When only replacing the method, the namespaces do not work as expected, so I had to change
`Error\Exception` to `\Error\Exception`
`Configuration` to `\SimpleSAML\Configuration`
`Template` to `\SimpleSAML\XHTML\Template`

Then it gives
```
SimpleSAML\Error\Exception: Error 8 - Undefined variable: template at /var/simplesamlphp/lib/SimpleSAML/IdP/IFrameLogoutHandler.php:116
```
but when changing `$template` into `$t`:
```
InvalidArgumentException: The module 'HTTP/1.0 200 OK
Cache-Control' is not enabled.
```

**Comment by tvdijen** [comment]
My bad! It should read the name of the template:
https://github.com/simplesamlphp/simplesamlphp/commit/7c70015589454f39b5e1ca2ef747cb5eff9abd6b#diff-2d18dbe33a1e9ab8d634b6af414a459cL123

**Comment by melanger** [comment]
Yes, that seems to work. This is the code I have now:
```php
public function onResponse($assocId, $relayState, \SimpleSAML\Error\Exception $error = null)
    {
        assert(is_string($assocId));

        $this->idp->terminateAssociation($assocId);

        $config = \SimpleSAML\Configuration::getInstance();
        $usenewui = $config->getBoolean('usenewui', false);

        // Force the use of Twig for this method. Remove if-clause in 2.0
        if ($usenewui === false) {
            $config = \SimpleSAML\Configuration::loadFromArray([
                'usenewui' => true,
            ]);
        }

        $t = new \SimpleSAML\XHTML\Template($config, 'IFrameLogoutHandler.twig');
        $t->data['assocId'] = var_export($assocId, true);
        $t->data['spId'] = sha1($assocId);
        if (!is_null($error)) {
            $t->data['errorMsg'] = $error->getMessage();
        } 

        if ($usenewui === false) {
            $twig = $t->getTwig();
            if (!isset($twig)) {
                throw new \Exception('Even though we explicitly configure that we want Twig, the Template class does not give us Twig. This is a bug.');
            }
            $result = $twig->render('IFrameLogoutHandler.twig', $t->data);
            echo $result;
        } else {
            $t->show();
        }
    }
```

**Comment by tvdijen** [comment]
Excellent! Did you try both old & newui?
I'd like to try one more thing if that okay with you, before making this into a PR..

**Comment by melanger** [comment]
On old ui it started working as expected.
With new ui, it seems to do the same thing as before (works).
(Setting `'usenewui' => true` in 1.17.5 changes loginuserpass.php but logout-iframe.php stays the same, judging by the fact that my old theme still works on the logout page)

**Comment by tvdijen** [comment]
logout-iframe was only recently migrated to Twig, so it's not part of 1.17 yet..
