### ISSUE TITLE
Minor UI-glitches admin-module

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1195]
- ~~If UIInfo['DisplayName'] exists, it should be used for entities rather than the 'name'.~~
- ADFS metadata will result in `Array()` instead of an entity name; an example of UI-breaking metadata is attached.

![afbeelding](https://user-images.githubusercontent.com/841045/64349086-975efd00-cff6-11e9-9d61-9b020a376c48.png)
[example_adfs_metadata.txt](https://github.com/simplesamlphp/simplesamlphp/files/3579657/example_adfs_metadata.txt)

**Comment by jaimeperez** [comment]
Regarding `DisplayName`, it's already like that if metadata has been processed by SSP. [`UIInfo` is prioritised and populated into the `name` entry of metadata](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Metadata/SAMLParser.php#L766-L769).

Regarding ADFS metadata, what's the reason for that? Have you debugged it? I don't see any practical difference with other metadata...

**Comment by tvdijen** [comment]
I'd have to triple check the DisplayName, but I'm pretty confident the last three 'OpenConext - Engineblock' entries have a UIInfo-displayname set in their metadata..

I haven't done any debugging done on the ADFS-metadata.. Only thing I can imagine at this point is that it fails on the `en-US` language-code as that one is not known to SSP.

Haven't really done anything with this other than filing this issue so I would not forget ;)

**Comment by tvdijen** [comment]
Ok, so I triple checked the first case:
``
  'name' =>
  array (
    'en' => 'OpenConext - Engineblock SP',
  ),
  'UIInfo' =>
  array (
    'DisplayName' =>
    array (
      'en' => 'IdP-broker VWS',
    ),
  ),
``
Metadata (saml20-sp-metadata) containing the above will display 'OpenConext - Engineblock SP' where I would expect it to display 'IdP-broker VWS'

**Comment by jaimeperez** [comment]
> I haven't done any debugging done on the ADFS-metadata.. Only thing I can imagine at this point is that it fails on the en-US language-code as that one is not known to SSP.

Yep, that's what I was thinking as well...

> Metadata (saml20-sp-metadata) containing the above will display 'OpenConext - Engineblock SP' where I would expect it to display 'IdP-broker VWS'

I know, and it's intended to work like that, that's what I was trying to say. The thing here is that if this metadata was generated by SSP, the value in `name` should be the same in `DisplayName`. When we generate it, we populate `name` from whatever we have available in the original metadata, and `DisplayName` has the highest priority.

**Comment by tvdijen** [comment]
OK, the first one is no issue.. I must have messed up somewhere (what's new).

**Comment by tvdijen** [comment]
It is indeed the en-US bugging us here...
My suggestion would be that if no translation is found and fallback to 'en' is not available, we should resort to just display the entityID like this:
https://github.com/simplesamlphp/simplesamlphp/blob/71c8330e5af938991fd02954e60631895b660628/modules/admin/lib/FederationController.php#L121-L123

How does that sound?

**Comment by jaimeperez** [comment]
Quite reasonable! 👍🏻
