### ISSUE TITLE
Move WS-Federation code to seprate module (was #267)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#12]
_From [andreass...@gmail.com](https://code.google.com/u/102889613336421617108/) on January 26, 2010 11:31:23_

Remove www/ws-fed directory.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=267_

**Comment by tvdijen** [comment]
Directory was completely removed in the 1.14 release
