### ISSUE TITLE
use LDAP_OPT_DIAGNOSTIC_MESSAGE for better error reporting in LDAP

### ISSUE THREAD

**Issue by jhaar** [simplesamlphp/simplesamlphp#120]
Hi there

I implemented my own LDAP-based authentication module in SSP and figured out how to improve error reporting. I noticed the standard module doesn't support it, so I'd recommend SSP do something similar

By calling 

ldap_set_option($ldapconn, LDAP_OPT_PROTOCOL_VERSION, 3);

before the ldap_bind, if the bind fails you call call

ldap_get_option($ldapconn, LDAP_OPT_DIAGNOSTIC_MESSAGE, $extended_error);

and then gain access to the root-cause of the bind failure

eg

* password expired
* user must reset password
* account expired
* No such user
* etc

Obviously there may be security concerns with exposing these details to attackers, but frankly the positives outweighed the negative for us: support issues are much quicker to remediate when users could see via the error page that their valid password no longer worked (ie expired). For "no such user" we report that to the user as "bad username/password" but our syslog logging reports it as "no such user" - so we didn't entirely throw out security ;-)

Anyway, I discovered this via the following URLs. Hopefully these are as useful to you as they were to me

https://forge.typo3.org/issues/60881
http://php.net/manual/en/function.ldap-bind.php

**Comment by jaimeperez** [comment]
Hi @jhaar!

Thanks for your suggestion! I've just merged PR #235 implementing this :smile:
