### ISSUE TITLE
Authentication custom attributes

### ISSUE THREAD

**Issue by thebatclaudio** [simplesamlphp/simplesamlphp#1203]
**Is your feature request related to a problem? Please describe.**
I don't know if this is a real feature request or if this is not compliant with SAML Standards. I'm trying to add an attribute "roles" that is an array of arrays.
For example:

```
'roles' => [
    [
        'application': 'application_1',
        'role': 'admin'
    ],
    [
        'application': 'application_2',
        'role': 'member'
    ]
]
```

But when I put this attribute in my Custom Authentication module, the result is:

```
'roles' => ['Array', 'Array']
```

Can I put custom object in my attributes? If not, how can I do something similar to my idea?

**Comment by jornane** [comment]
SAML is XML, so purely speaking about SAML you can put XML in your attributes.

In SimpleSAMLphp, attributes are represented as an unindexed array of strings, which is why you see `['Array', 'Array']`; casting an array to string results in `Array`.

**Comment by thebatclaudio** [comment]
Hi @jornane,
thank you for your reply. There is a "standard way" to return roles in SimpleSamlPHP?

I was thinking to return roles in this way:

```
'roles' => ['application1:admin', 'application2:member', 'application3:student']
```

But I'm not sure that I'm doing it in a right way.

**Comment by jaimeperez** [comment]
Hi @thebatclaudio,

You could, as @jornane says, create your own XML structure as the value of the attributes. However, I wonder if there's a need for that. From your description, it looks like you want to control authorization based on the role that a user has for every service. What is it exactly that you are trying to achieve (in general terms)?

**Comment by thebatclaudio** [comment]
Hi @jaimeperez,
I have different applications that use IDP to let their users log in. Each user can have different roles for each applications, so I want to return an array of object (or something similar) to know what role has the user for each application.

**Comment by BAGELreflex** [comment]
@thebatclaudio you can limit the attributes returned from the IdP to your SP. You can do:

- Application 1 is configured to only need these attributes
  - application1:admin
  - application1:member
  - application1:blocked
- Application 2 is configured to only need these attributes
  - application2:designer
  - application2:editor
  - application2:godmode

From the docs: https://simplesamlphp.org/docs/stable/saml:sp#section_4

**attributes**
List of attributes this SP requests from the IdP. This list will be added to the generated metadata.
The attributes will be added without a NameFormat by default. Use the attributes.NameFormat option to specify the NameFormat for the attributes.

An associative array can be used, mixing both elements with and without keys. When a key is specified for an element of the array, it will be used as the friendly name of the attribute in the generated metadata.

```php
// Metadata for application1 ...
'attributes' => ['application1:admin','application1:member','application1:blocked'],
// ...
```
