### ISSUE TITLE
Cron module not working on web UI after PR #1181

### ISSUE THREAD

**Issue by klention** [simplesamlphp/simplesamlphp#1220]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
After update to the last commit **4c7f8ff** cron module does not work anymore when clicking **Cron module information page** link on web ui. From logs I can see the following error:
SimpleSAML\Error\Exception: Error 1 - Call to a member function render() on null at /var/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:512

**To Reproduce**
1. Update to latest commit on branch master
2. Click on 'domain.com/simplesaml/module.php/cron/croninfo.php'
Shows blank page.

**Comment by tvdijen** [comment]
Are you on old UI or new UI?

**Comment by tvdijen** [comment]
My guess is that you're on the old UI...
What happens if you change `send` to `show` in this line?:  https://github.com/simplesamlphp/simplesamlphp/blob/4c7f8ffa99c510f0829db533d601d9477661ebea/modules/cron/www/croninfo.php#L19

**Comment by klention** [comment]
> My guess is that you're on the old UI...
> What happens if you change `send` to `show` in this line?:
> 
> https://github.com/simplesamlphp/simplesamlphp/blob/4c7f8ffa99c510f0829db533d601d9477661ebea/modules/cron/www/croninfo.php#L19

I am using the old UI.
When changing from `send` to `show` it displays OK on old UI.

I start using the new UI and change from `show()` to original value `send()` and it is working fine.
Thank you.

**Comment by tvdijen** [comment]
Leaving this open as a reminder..
I need to fix this case and perhaps a few more and make sure that new UI keeps working as well...

**Comment by tvdijen** [comment]
Closed in 9bb75dd
