### ISSUE TITLE
Allow configuration of database number for Redis store

### ISSUE THREAD

**Issue by garylocke** [simplesamlphp/simplesamlphp#1223]
**Describe the solution you'd like**
I would like a way to configure a database number for my Redis store by editing `config/config.php`.

I believe this is a very straightforward change, but let me know if I've missed anything or if this is already possible through other methods.

I will submit a PR shortly with a change to include this option.

**Comment by garylocke** [comment]
See PR #1224

**Comment by tvdijen** [comment]
This was added only days ago in #1222?

**Comment by garylocke** [comment]
Excellent. I will close this request.
