### ISSUE TITLE
exampleauth External.php  does not retrieve well the source id 

### ISSUE THREAD

**Issue by ddmusc** [simplesamlphp/simplesamlphp#1225]
The authentication source for exampleauth is referred to badly in a way that it will not work if the configuration in authsource is changed.

I suggest the following line in External.php is changed
Code: https://github.com/simplesamlphp/simplesamlphp/blob/86cd5fffc9c126e8f07d9be64c3a0196b239a9ea/modules/exampleauth/lib/Auth/Source/External.php#L132

Changed from:        $state['exampleauth:AuthID'] = self::AUTHID;

Changed To:  $state['exampleauth:AuthID'] = $this->authId;

The problem is that in line 215 there is:
https://github.com/simplesamlphp/simplesamlphp/blob/86cd5fffc9c126e8f07d9be64c3a0196b239a9ea/modules/exampleauth/lib/Auth/Source/External.php#L215

Therefore $state['exampleauth:AuthID'] must refer to source defined in the authsources configuration file and not to some constant stated in code.

**Comment by tvdijen** [comment]
Hmmmm, it used to be like that and then at some point I changed it in a commit that has no clue of why I did it... I'll change it back and see what happens
