### ISSUE TITLE
New fix for getPathInfo() needs to be added other places

### ISSUE THREAD

**Issue by Baggerone** [simplesamlphp/simplesamlphp#1227]
In 1.18.0 rc2 
lib/SimpleSAML/Module.php
line 132 should be changed to look like line 136, right?  And maybe the same for line 569?

**Comment by tvdijen** [comment]
Why? Are you experiencing issues?

**Comment by Baggerone** [comment]
Sorry, you probably wanted more information about it.  

The two ways of trying to get the path info give different results. With our reverse proxy usage of simplesamlphp, the way the code is now, it sees the path as "/" and gives an error.  However, using `if ($request->server->get('PATH_INFO') === '/')`, it sees it as `/memcookie/auth.php`.

I assumed that the reasons why you changed line 136, would apply to making a similar change on line 132.

**Comment by tvdijen** [comment]
OK, I've ran a few tests and I doesn't appear to break anything..
I've created a PR and like a second pair of eyes from @jaimeperez before I merge this

**Comment by Baggerone** [comment]
Hi @jaimeperez,
We used 1.17.7 but applied a patch with that change (on lines 132 and 136) and that fixed the issue for us.
