### ISSUE TITLE
1.19: Mysterious TypeError with strict_types=1

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1229]
**Describe the bug**
After fiddling around with `declare(strict_types=1);` on all files in the lib-directory, the following TypeError was thrown:

> 4) SimpleSAML\Test\Web\TemplateTest::testSyntax
> TypeError: strtr() expects parameter 1 to be string, null given
> 
> 
> /apps/development/simplesamlphp-php70/lib/SimpleSAML/Locale/Translate.php:477
> /apps/development/simplesamlphp-php70/vendor/simplesamlphp/twig-configurable-i18n/src/Twig/Extensions/Extension/I18n.php:74
> /apps/development/simplesamlphp-php70/vendor/twig/twig/src/Template.php:216
> /apps/development/simplesamlphp-php70/vendor/twig/twig/src/Template.php:216
> /apps/development/simplesamlphp-php70/vendor/twig/twig/src/Template.php:455
> /apps/development/simplesamlphp-php70/vendor/twig/twig/src/Template.php:422
> /apps/development/simplesamlphp-php70/vendor/twig/twig/src/Template.php:455
> /apps/development/simplesamlphp-php70/vendor/twig/twig/src/Template.php:422
> /apps/development/simplesamlphp-php70/vendor/twig/twig/src/Template.php:434
> /apps/development/simplesamlphp-php70/vendor/twig/twig/src/TemplateWrapper.php:47
> /apps/development/simplesamlphp-php70/vendor/twig/twig/src/Environment.php:384
> /apps/development/simplesamlphp-php70/lib/SimpleSAML/XHTML/Template.php:514
> /apps/development/simplesamlphp-php70/lib/SimpleSAML/XHTML/Template.php:543
> /apps/development/simplesamlphp-php70/tests/www/TemplateTest.php:39

After a lot of debugging and banging my head against the wall, I have managed to trace this issue back to this line in a Twig-template:
https://github.com/simplesamlphp/simplesamlphp/blob/master/templates/error.twig#L6

**Expected behavior**
The TypeError should not happen and if something's wrong with a Twig-Template or one of the Twig-functions, we should print a clear exception message on the reason why..

**Comment by tvdijen** [comment]
I've figured this out.. It's mostly because the unit test that fails doesn't set any variables, which isn't an issue for variables used in a regular manner.
`null | trans` works fine

However, because the unit test doesn't set any vars, the failing [line](https://github.com/simplesamlphp/simplesamlphp/blob/master/templates/error.twig#L6) in the Twig-template becomes:
`null | trans(null)` and fails
`null | default('') | trans(null)` also works fine

The fact remains that if someone fails to set a crucial variable, they end up with a horrible headache that's hard to debug.

**Comment by tvdijen** [comment]
I was able to make it work the same with strict_types=1 as it was without:
https://github.com/simplesamlphp/simplesamlphp/commit/751dae6437dd7527e483d2aad4b588cbeb7cbe5c

**Comment by tvdijen** [comment]
Perhaps a better solution is to add the 'strict_variables'-option to the Twig Environment, which will raise a `\Twig\Error\RuntimeError` if a variable is not set.

**Comment by tvdijen** [comment]
We need to decide whether to:
1) take the easy way out and use the 'fix' commit mentioned above, or
2) work with strict variables in Twig and be prepared to go over all Twig-templates again to fix them (most of them break with strict mode enabled)

I think (2) is the way to go as a 1.19 milestone.. If we manage to fix all templates we can truly say our templating system has properly matured and is ready to be the default in 2.0.

**Comment by jaimeperez** [comment]
I agree with your final argument. If we can make it easier to develop templates (in this case, easier to debug them), and we can uncover mistakes in the process, then that's a good idea 👍

**Comment by tvdijen** [comment]
Closed in 09f4ee1
