### ISSUE TITLE
NameIDPolicy configuration format in 1.17 not backwards compatible

### ISSUE THREAD

**Issue by Paragin** [simplesamlphp/simplesamlphp#1230]
**Describe the bug**
Because of the security issue published yesterday, we kind of rushed into an upgrade from 1.16 to 1.17.7. In the changelog documentation is mentioned that there is a new preferred method for specifying NameIDPolicy, namely `[ 'Format' => format, 'AllowCreate' => true/false ]`.

For most of our SP's, the NameIDPolicy is specified using the old format (as string) like "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent". We expected no difficulties here since nothing is mentioned about backwards incompatibility, but we ran into errors with some identity providers.

 The difference between using a string for configuring NameIDPolicy in 1.17 (compared to 1.16) is that allowCreate is now omitted in authentication requests while in 1.16 it was added with value `TRUE`.
This leads to errors on different IdP platforms since allowCreate defaults to `FALSE`  in the SAML spec which means that configuring the NameIDPolicy using a string results in a different authentication request in 1.17 compared to 1.16.

When I look at the code, I think I can explain the behavior: In [/Utils/Config/Metadata.php](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/Config/Metadata.php) there is a new function called `public static function parseNameIdPolicy($nameIdPolicy)`. When using the string configuration type, it converts to `$policy = ['Format' => $nameIdPolicy];`.

As far as I can see, the behavior in 1.16 was different, since it always added the AllowCreate attribute and defaulted to `TRUE`:
```php
$policy = array(
    'Format'      => $nameIdPolicy_cf->getString('Format', \SAML2\Constants::NAMEID_TRANSIENT),
    'AllowCreate' => $nameIdPolicy_cf->getBoolean('AllowCreate', true),
);
```

I think it would be better to revert to the old behavior and add `'AllowCreate' => true` to Metadata.php:296 to make sure users that are switching to simplesamlphp 1.17 do not experience the same problems (and downtime) as we did.

**To Reproduce**
1. Configure a IdP using NameIDPolicy "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" 
2. Try to authenticate on the IdP for a new user for which no NameID was previously generated
3. SAML-tracer shows no AllowCreate-parameter is added to the `<samlp:NameIDPolicy>` element in the authentication request
3. IdP (in this case NetIQ IDP) gives error since the AllowCreate parameter is missing and it doesn't want to create a new NameID

**Expected behavior**
I expected simplesamlphp to still add the AllowCreate parameter to the authentication request since my configuration hasn't changed.

**Comment by jaimeperez** [comment]
Thanks a lot for reporting this @Paragin!

I've just committed a fix for this issue, and it will be available in 1.18.0.
