### ISSUE TITLE
Permission issue in 1.18.0 due to vimeo/psalm requiring muglug/package-versions-56

### ISSUE THREAD

**Issue by BAGELreflex** [simplesamlphp/simplesamlphp#1239]
**Describe the bug**
I just upgraded a development environment from v1.17.7 to v1.18.0 via the repository. During the composer install I receive an error from `muglug/package-versions-56` stating that it could not execute a `chmod()` operation.

```
[astclair@dev-auth ~]$ ./upgrade-simplesamlphp.sh -t v1.18.0
fatal: A branch named 'v1.18.0' already exists.
warning: refname 'v1.18.0' is ambiguous.
Already on 'v1.18.0'
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 20 updates, 11 removals
  - Removing symfony/service-contracts (v1.1.8)
  - Removing symfony/polyfill-php73 (v1.12.0)
  - Removing symfony/polyfill-php72 (v1.12.0)
  - Removing symfony/polyfill-intl-idn (v1.12.0)
  - Removing symfony/mime (v4.3.8)
  - Removing symfony/event-dispatcher-contracts (v1.1.7)
  - Removing mtdowling/jmespath.php (2.4.0)
  - Removing league/oauth2-client (2.4.1)
  - Removing cirrusidentity/simplesamlphp-module-authoauth2 (v2.1.0)
  - Removing bagelreflex/simplesamlphp-module-cloudfront (v1.0.2)
  - Removing aws/aws-sdk-php (3.118.0)
  - Downgrading simplesamlphp/saml2 (v4.1.1 => v3.4.2):  Checking out 3806d276ed
  - Downgrading symfony/routing (v4.3.8 => v3.4.35): Loading from cache
  - Downgrading symfony/filesystem (v4.3.8 => v3.4.35):  Checking out 00e3a6ddd7
  - Downgrading symfony/config (v4.3.8 => v3.4.35): Loading from cache
  - Installing symfony/polyfill-util (v1.12.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.12.0): Loading from cache
  - Downgrading symfony/debug (v4.3.8 => v3.4.35): Loading from cache
  - Downgrading paragonie/random_compat (v9.99.99 => v2.0.18): Loading from cache
  - Installing symfony/polyfill-php70 (v1.12.0): Loading from cache
  - Downgrading symfony/http-foundation (v4.3.8 => v3.4.35): Loading from cache
  - Downgrading symfony/event-dispatcher (v4.3.8 => v3.4.35):  Checking out f9031c22ec
  - Downgrading symfony/http-kernel (v4.3.8 => v3.4.35): Loading from cache
  - Downgrading symfony/dependency-injection (v4.3.8 => v3.4.35): Loading from cache
  - Downgrading symfony/yaml (v4.3.8 => v3.4.35): Loading from cache
  - Downgrading twig/twig (v2.12.2 => v1.42.4):     The package has modified files:
    M drupal_test.sh
    Discard changes [y,n,v,d,s,?]? y
 Checking out e587180584
  - Downgrading doctrine/instantiator (1.3.0 => 1.0.5): Loading from cache
  - Downgrading myclabs/deep-copy (1.9.3 => 1.7.0): Loading from cache
  - Downgrading phpdocumentor/reflection-common (2.0.0 => 1.0.1): Loading from cache
  - Downgrading phpdocumentor/type-resolver (1.0.1 => 0.4.0): Loading from cache
  - Downgrading phpdocumentor/reflection-docblock (4.3.2 => 3.3.2): Loading from cache
  - Downgrading phpunit/php-token-stream (2.0.2 => 1.4.12): Downloading (100%)
  - Downgrading symfony/console (v4.3.8 => v3.4.35): Loading from cache
  - Downgrading symfony/stopwatch (v4.3.8 => v3.4.35): Loading from cache
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
muglug/package-versions-56:  Generating version class...


  [ErrorException]
  chmod(): Operation not permitted

```

I am not certain if this is causing any negative functionality yet. It seems that Vimeo's Psalm static PHP analysis tool has been added to v1.18.0 but I don't see anything about that [in the changelog](https://simplesamlphp.org/docs/development/simplesamlphp-changelog#section_2). The Vimeo package requires `"muglug/package-versions-56": "1.2.4"` in `/var/simplesamlphp/vendor/vimeo/psalm/composer.json`.

It's fairly standard that Composer should not be run as root/sudo. So, I'm not sure why that package would assume it has proper authority to change the permission for the owner of the file. The offending line in the muglug package is here: https://github.com/muglug/PackageVersions/blob/master/src/PackageVersions/Installer.php#L145

```php
    /**
     * @param string $versionClassSource
     * @param Composer $composer
     * @param IOInterface $io
     *
     * @return void
     *
     * @throws \RuntimeException
     */
    private static function writeVersionClassToFile($versionClassSource, Composer $composer, IOInterface $io)
    {
        $installPath = self::locateRootPackageInstallPath($composer->getConfig(), $composer->getPackage())
            . '/src/PackageVersions/Versions.php';
        if (! file_exists(dirname($installPath))) {
            $io->write('<info>muglug/package-versions-56:</info> Package not found (probably scheduled for removal); generation of version class skipped.');
            return;
        }
        $io->write('<info>muglug/package-versions-56:</info>  Generating version class...');
        file_put_contents($installPath, $versionClassSource);
        chmod($installPath, 0664);
        $io->write('<info>muglug/package-versions-56:</info> ...done generating version class');
    }
```

**To Reproduce**
My environment:
* CentOS Linux release 7.6.1810
* Apache/2.4.6
* SELinux is **enforcing**

1. Here is my upgrade script: https://gist.github.com/BAGELreflex/1e8abe0931f61c9d4587450aef28f367
2. Run this script. If you do not want to run the whole script then the primary important piece is the `setPermissions()` function. 

**Expected behavior**
I would expect the Composer package to not attempt to modify the owner's permission via chmod, as composer should not be run as root/sudo. However, that project is outside of SSPHP. The giant red block that composer prints for this error is bothersome during upgrades.

What is the goal with the vimeo static analysis tool? Have others been considered? Here is a list of alternative tools if there is no way to mute this warning: https://github.com/exakat/php-static-analysis-tools

What permissions are others setting on their `simplesamlphp` installation directory so that this error does not arise? Are your deployments being run as root or a dedicated non-root user?

**Additional context**
I wasn't sure if I should open this as a bug, but since 1.18.0 is now considered a stable release I thought I should bring it to someone's attention.

**Comment by tvdijen** [comment]
It's not mentioned in the changelog, because it should not affect end-users or even be of any interest to them.. It's a dev-dependency for a reason.
I do agree that a dependency should not try and alter permissions.. It seems to be an edge case though, because I have the exact same setup and do not experience this issue (I'd have to see what happens with your script though.. not tried it yet)..

Your solution here is to fix your script to install SSP with `--no-dev`, as dev-dependencies serve you no good unless you develop on SSP..

**Comment by BAGELreflex** [comment]
@tvdijen I agree, this is not impacting my staging/production environment (where I install with --no-dev), however in my development environment I do tend to install with dev dependencies so that I can test any core changes that I may need to make and create a PR.

I thought I should report this in case it did start causing issues during SSP development. If you are not concerned about the above issue then I will not be either, and this issue can be closed.

**Comment by tvdijen** [comment]
I'll try and reproduce it with your script.. It might be that your security policy is more strict than mine (I thought mine was pretty strict already!).. Psalm is a great tool and the muglug-dependency can be rid of in 1.19 if we push towards PHP 7.0

**Comment by BAGELreflex** [comment]
https://www.php.net/supported-versions.php
PHP 5.6 was EoL on December 31, 2018
PHP 7.0 was EoL on January 10, 2019
**PHP 7.1 is EoL on December 1, 2019**

Given that SimpleSAMLphp is a solution that provides such a sensitive service as authentication federation, I believe the project would be completely justified in changing the minimum PHP version to be 7.2, as 5.6/7.0 are already EoL and 7.1 is EoL in just 12 days.

**Comment by tvdijen** [comment]
Support from PHP means nothing as RedHat still provides security fixes.. RHEL7 is still at 5.5 if I'm not mistaken and it's still supported.. Our plan is 7.0 for 1.19 and 7.2 for 2.0.. It's gonna take a while due to limited resources though (we all have day jobs)

**Comment by tvdijen** [comment]
btw, do you use our .spec file for your hardening?

**Comment by BAGELreflex** [comment]
I was unaware of the .spec file. Do you mean use it just for reference, or is there some way to run a .spec file outside of RPM? I'm running on CentOS so I'm not installing via RPM.

I will review the changes in the .spec file and make my script perform the same actions. Thank you for pointing this file out.

I also did not know that RHEL was back-porting such old versions of PHP.

**Comment by jaimeperez** [comment]
I understand this is a deployment issue, so I'm closing this issue for now. Feel free to reopen it if needed, of course!
