### ISSUE TITLE
Upgrading to v1.18.0 breaks custom templates

### ISSUE THREAD

**Issue by BAGELreflex** [simplesamlphp/simplesamlphp#1240]
**Describe the bug**
I just upgraded a development environment from v1.17.7 to v1.18.0 via the repository. I am using a custom template. I can no longer browse to my login screens at all. An unhandled exception is being thrown trying to locate `loginuserpass.tpl.php` and no error screen is shown because it also cannot find `error.php`.

```
Nov 19 10:57:04 simplesamlphp CRITICAL [7295f6e50a] /saml/module.php/core/loginuserpass.php - Template: Could not find template file [core:loginuserpass.tpl.php] at [/var/simplesamlphp/modules/core/templates/loginuserpass.twig]
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] Backtrace:
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] 1 /var/simplesamlphp/www/_include.php:17 (SimpleSAML_exception_handler)
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] 0 [builtin] (N/A)
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] Caused by: Exception: Template: Could not find template file [core:loginuserpass.tpl.php] at [/var/simplesamlphp/modules/core/templates/loginuserpass.twig]
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] Backtrace:
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] 4 /var/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:637 (SimpleSAML\XHTML\Template::findTemplatePath)
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] 3 /var/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:543 (SimpleSAML\XHTML\Template::show)
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] 2 /var/simplesamlphp/modules/core/www/loginuserpass.php:136 (require)
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] 1 /var/simplesamlphp/lib/SimpleSAML/Module.php:254 (SimpleSAML\Module::process)
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] 0 /var/simplesamlphp/www/module.php:10 (N/A)
Nov 19 10:57:04 simplesamlphp ERROR [7295f6e50a] Error report with id 0e5f784c generated.
Nov 19 10:57:04 simplesamlphp CRITICAL [7295f6e50a] /saml/module.php/core/loginuserpass.php - Template: Could not find template file [error.php] at [/var/simplesamlphp/templates//error.twig]
```

I have reviewed the latest build and it seems that all template files have been changed to have a naming convention of `loginuserpass.tpl.php` instead of `loginuserpass.php`. I can find no mention of this [in the changelog](https://simplesamlphp.org/docs/1.18/simplesamlphp-changelog#section_1) or in the [1.18 documentation for custom themes](https://simplesamlphp.org/docs/1.18/simplesamlphp-theming).

**To Reproduce**
1. Have your config set to use a custom template that worked in v1.17.7 and below
2. Upgrade to v1.18.0
3. Browse to your site

**Expected behavior**
I would expect a change this drastic to be documented somewhere. I'm not sure what all considerations I need to make in order to handle the changes that v1.18.0 expects with the naming conventions.

Do I simply need to rename my files?

I also notice that stock files such as `templates/error.php` have not been renamed to be `templates/error.tpl.php`. Why have these not changed to match the same naming convention in the `core/templates`?

Please advise.

**Comment by tvdijen** [comment]
Thanks for reporting this, @BAGELreflex !
I feel stupid for not overseeing this consequence.. This change should not have ended up in a minor release and I wish it would have come to light when we released our RC's..

Now that we've ended up here, I don't think it should be reverted.. All old-style templates should be renamed to `.tpl.php`, we should mention the change in the upgrade notes and we should start to actively persuade our users to migrate to Twig-templates

**Comment by tvdijen** [comment]
On second thought this should just work, even if the default template is called `x.tpl.php` and your theme override `x.php`..  It shouldn't matter..
Would you be able to get me a trace log at debug level?

**Comment by BAGELreflex** [comment]
I changed the config to have `'logging.level' => SimpleSAML\Logger::DEBUG`, but I do not see much more useful information than my original error. Here is the latest:

```
Nov 19 14:44:00 simplesamlphp DEBUG [7295f6e50a] Session: 'admin' not valid because we are not authenticated.
Nov 19 14:44:00 simplesamlphp DEBUG [7295f6e50a] Session: 'login-admin' not valid because we are not authenticated.
Nov 19 14:44:00 simplesamlphp DEBUG [7295f6e50a] Saved state: '_3f341a80ccf647f54e11e6dad9b01d6d018f84d235:https://dev-auth.ecrs.com/saml/module.php/core/as_login.php?AuthId=admin&ReturnTo=https%3A%2F%2Fdev-auth.ecrs.com%2Fsaml%2Fmodule.php%2Fcore%2Ffrontpage_welcome.php'
Nov 19 14:44:00 simplesamlphp DEBUG [7295f6e50a] Loading state: '_3f341a80ccf647f54e11e6dad9b01d6d018f84d235:https://dev-auth.ecrs.com/saml/module.php/core/as_login.php?AuthId=admin&ReturnTo=https%3A%2F%2Fdev-auth.ecrs.com%2Fsaml%2Fmodule.php%2Fcore%2Ffrontpage_welcome.php'
Nov 19 14:44:00 simplesamlphp DEBUG [7295f6e50a] Localization: using old system
Nov 19 14:44:00 simplesamlphp DEBUG [7295f6e50a] /saml/module.php/core/loginuserpass.php - Template: Could not find template file [core:loginuserpass.tpl.php] at [/var/simplesamlphp/modules/ssphpecrs/themes/golden-e/core/loginuserpass.twig] - now trying the base template
Nov 19 14:44:00 simplesamlphp CRITICAL [7295f6e50a] /saml/module.php/core/loginuserpass.php - Template: Could not find template file [core:loginuserpass.tpl.php] at [/var/simplesamlphp/modules/core/templates/loginuserpass.twig]
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] Backtrace:
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] 1 /var/simplesamlphp/www/_include.php:17 (SimpleSAML_exception_handler)
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] 0 [builtin] (N/A)
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] Caused by: Exception: Template: Could not find template file [core:loginuserpass.tpl.php] at [/var/simplesamlphp/modules/core/templates/loginuserpass.twig]
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] Backtrace:
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] 4 /var/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:637 (SimpleSAML\XHTML\Template::findTemplatePath)
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] 3 /var/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:543 (SimpleSAML\XHTML\Template::show)
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] 2 /var/simplesamlphp/modules/core/www/loginuserpass.php:136 (require)
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] 1 /var/simplesamlphp/lib/SimpleSAML/Module.php:254 (SimpleSAML\Module::process)
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] 0 /var/simplesamlphp/www/module.php:10 (N/A)
Nov 19 14:44:00 simplesamlphp ERROR [7295f6e50a] Error report with id 3fbf8fc8 generated.
Nov 19 14:44:00 simplesamlphp DEBUG [7295f6e50a] Localization: using old system
Nov 19 14:44:00 simplesamlphp DEBUG [7295f6e50a] Translate: Reading dictionary [/var/simplesamlphp/dictionaries/errors]
Nov 19 14:44:00 simplesamlphp DEBUG [7295f6e50a] /saml/module.php/core/loginuserpass.php - Template: Could not find template file [error.php] at [/var/simplesamlphp/modules/ssphpecrs/themes/golden-e/default/error.twig] - now trying the base template
Nov 19 14:44:00 simplesamlphp CRITICAL [7295f6e50a] /saml/module.php/core/loginuserpass.php - Template: Could not find template file [error.php] at [/var/simplesamlphp/templates//error.twig]
```

Here is information about my custom module:

```
[astclair@dev-auth ssphpecrs]$ pwd
/var/simplesamlphp/modules/ssphpecrs

[astclair@dev-auth ssphpecrs]$ ls
attributemap  common-head-elements.php  composer.json  default-disable  dictionaries  lib  README.md  satis.json  templates  themes  www

[astclair@dev-auth ssphpecrs]$ tree themes/ templates/
themes/
└── golden-e
    ├── authorize
    │   └── authorize_403.php
    ├── core
    │   └── loginuserpass.php
    ├── default
    │   └── error.php
    └── multiauth
        └── selectsource.php
templates/
└── newpasswordform.php

5 directories, 5 files
```

**Comment by tvdijen** [comment]
Thanks, this is really useful! We'll try and it fix it asap

**Comment by attalbialami** [comment]
+1

I'm facing the same problem when upgrading to 1.18.0

```
2019/11/20 11:55:03 [error] 24769#24769: *20374 FastCGI sent in stderr: "PHP message: PHP Fatal 
error:  Uncaught Exception: Template: Could not find template file [error.php] at 
[/usr/share/simplesamlphp/templates//error.twig] in /usr/share/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:637
```

**Comment by tvdijen** [comment]
Thanks @attalbialami, we've been able to reproduce it and a fix is prepared as we speak

**Comment by techgourmet** [comment]
Any update how to work around it, or timeline to deliver the fixed code?

We are running into exactly the same issue

**Comment by techgourmet** [comment]
Manually added the changed the code in line 230 of Template.php as described in the fix.
This does the trick.

**Comment by jaimeperez** [comment]
Hi all,

We have just released SimpleSAMLphp 1.18.1 fixing this issue.

**Comment by ghalse** [comment]
> I wish it would have come to light when we released our RC's..
@tvdijen I feel bad now. I found this in RC1, and I eluded to it in passing. But I simply didn't get round to digging into it enough to work out whether it was a bug in my theme or in the underlying code, so I never submitted an issue :(.

**Comment by puneetjain321** [comment]
Thanks, The Fix also works on v1.19.0-rc1

**Comment by tvdijen** [comment]
Yes, we were aware of the 1.19-RC1 issue @puneetjain321! It has been fixed on the 1.19-branch and will be part of the RC2

**Comment by jguilhermeam** [comment]
Hi, i use custom templates and i've updated my simplesamlphp to 1.19.0-rc1 but this error keeps showing on my custom template (not twig)

Fatal error: Uncaught Exception: Template: Could not find template file [error.php] at [/var/www/html/sso/templates//error.twig] in /var/www/html/sso/lib/SimpleSAML/XHTML/Template.php:653 Stack trace: #0 /var/www/html/sso/lib/SimpleSAML/XHTML/Template.php(560): SimpleSAML\XHTML\Template->findTemplatePath('error.php') #1 /var/www/html/sso/lib/SimpleSAML/Error/Error.php(273): SimpleSAML\XHTML\Template->show() #2 /var/www/html/sso/www/_include.php(18): SimpleSAML\Error\Error->show() #3 [internal function]: SimpleSAML_exception_handler(Object(Exception)) #4 {main} thrown in /var/www/html/sso/lib/SimpleSAML/XHTML/Template.php on line 653


i don't know why this error is ocurring as you've fixed, or i think it is another one... could you help me?

**Comment by tvdijen** [comment]
The fix hasn't been released yet..  You can wait for RC2 or manually fix it, see https://github.com/simplesamlphp/simplesamlphp/commit/3e9381452b9ff82f3a2a66d29b6129276e499d6a
