### ISSUE TITLE
Installing SimpleSAML 1.18 with composer requires LDAP extension

### ISSUE THREAD

**Issue by MaximilianKresse** [simplesamlphp/simplesamlphp#1241]
Composer output:
```
 Problem 1
     - simplesamlphp/simplesamlphp-module-ldap v0.9.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
     - simplesamlphp/simplesamlphp-module-ldap v0.9.0 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
     - simplesamlphp/simplesamlphp v1.18.0 requires simplesamlphp/simplesamlphp-module-ldap ^0.9 -> satisfiable by simplesamlphp/simplesamlphp-module-ldap[v0.9.0, v0.9.1].
     - Installation request for simplesamlphp/simplesamlphp 1.18.* -> satisfiable by simplesamlphp/simplesamlphp[v1.18.0].
```

Like the error says SimpleSAML 1.18.0 requires "simplesamlphp/simplesamlphp-module-ldap" and "simplesamlphp/simplesamlphp-module-ldap" requires the ldap extension. But this also means that you cannot install SimpleSAML 1.18.0 without the LDAP extension even you don't want to use the LDAP module.

**Comment by tvdijen** [comment]
The ext-dependency should be removed from the 0.9 branch of the ldap-module..

**Comment by tvdijen** [comment]
https://github.com/simplesamlphp/simplesamlphp-module-ldap/releases/tag/v0.9.2 fixes this and we'll tag a 1.18.1 release soon

**Comment by francoisfreitag** [comment]
`v1.18.1` is out, but I see `simplesamlphp-module-ldap` was left in version 0.9.1 in `composer.lock`.

https://github.com/simplesamlphp/simplesamlphp/blob/040cd228b414cb505e05607b8255a59d25f71c18/composer.lock#L1260-L1310

**Comment by jaimeperez** [comment]
Hi @francoisfreitag,

The `composer.lock` is irrelevant here. Installing SimpleSAMLphp with composer you will get version `0.9.3` of the module.

**Comment by francoisfreitag** [comment]
Hi @jaimeperez,

I am installing SimpleSAMLphp from `git` (following https://simplesamlphp.org/docs/1.18/simplesamlphp-install-repo). When running `php composer.phar install`, I get the failure from this issue because `simplesamlphp-module-ldap` is pinned to `0.9.1`.

**Comment by tvdijen** [comment]
I'm with you on this one @francoisfreitag, we should have updated the lock-file..
I do however hope you realise that the instruction you're using will give you `master` instead of `1.18`

**Comment by francoisfreitag** [comment]
Thanks for the warning!
I am using the [Ansible `git` module](https://docs.ansible.com/ansible/latest/modules/git_module.html) to clone the repo and specify the git tag. It makes upgrading very easy and allows to serve static assets from reverse proxy servers where `composer` is not installed. The web servers running PHP-FPM have composer installed and run the `composer install` command in the `simplesamlphp` repo (but do not have `ext-ldap`, which is why I run into this issue).

**Comment by tvdijen** [comment]
You can safely remove `ext-ldap` from the composer.json file and we'll update the lock-file.. I don't think it justifies for a new bugfix release though

**Comment by jaimeperez** [comment]
Actually, I'd say that's not an option, because `ext-ldap` is not in SimpleSAMLphp's `composer.json` file, but in the _ldap_ module's, right?

**Comment by francoisfreitag** [comment]
Yes, that’s correct. The following patch allows me to run `composer install` successfully, but that’s not something I would advocate to use or deploy.

<details>
<pre>
diff --git a/composer.lock b/composer.lock
index eab36c8..415ab6f 100644
--- a/composer.lock
+++ b/composer.lock
@@ -843,8 +843,7 @@
             },
             "require": {
                 "php": ">=5.5",
-                "simplesamlphp/composer-module-installer": "~1.1",
-                "simplesamlphp/simplesamlphp-module-ldap": "^0.9"
+                "simplesamlphp/composer-module-installer": "~1.1"
             },
             "require-dev": {
                 "phpunit/phpunit": "~4.8.36",
@@ -946,7 +945,6 @@
             "require": {
                 "php": ">=5.6",
                 "simplesamlphp/composer-module-installer": "~1.1",
-                "simplesamlphp/simplesamlphp-module-ldap": "^0.9",
                 "webmozart/assert": "~1.4"
             },
             "require-dev": {
@@ -1258,57 +1256,6 @@
             "time": "2019-05-29T14:43:00+00:00"
         },
         {
-            "name": "simplesamlphp/simplesamlphp-module-ldap",
-            "version": "v0.9.1",
-            "source": {
-                "type": "git",
-                "url": "https://github.com/simplesamlphp/simplesamlphp-module-ldap.git",
-                "reference": "6945bfde7f91527240a5151674247c83c347506c"
-            },
-            "dist": {
-                "type": "zip",
-                "url": "https://api.github.com/repos/simplesamlphp/simplesamlphp-module-ldap/zipball/6945bfde7f91527240a5151674247c83c347506c",
-                "reference": "6945bfde7f91527240a5151674247c83c347506c",
-                "shasum": ""
-            },
-            "require": {
-                "ext-ldap": "*",
-                "php": ">=5.6",
-                "simplesamlphp/composer-module-installer": "~1.1",
-                "webmozart/assert": "~1.4"
-            },
-            "require-dev": {
-                "phpunit/phpunit": "~5.7",
-                "simplesamlphp/simplesamlphp": "^1.17"
-            },
-            "type": "simplesamlphp-module",
-            "autoload": {
-                "psr-4": {
-                    "SimpleSAML\\Module\\ldap\\": "lib/"
-                }
-            },
-            "notification-url": "https://packagist.org/downloads/",
-            "license": [
-                "LGPL-3.0-or-later"
-            ],
-            "authors": [
-                {
-                    "name": "Tim van Dijen",
-                    "email": "tvdijen@gmail.com"
-                },
-                {
-                    "name": "Olav Morken",
-                    "email": "olavmrk@gmail.com"
-                }
-            ],
-            "description": "A module that provides authentication against LDAP stores",
-            "keywords": [
-                "ldap",
-                "simplesamlphp"
-            ],
-            "time": "2019-07-13T12:07:27+00:00"
-        },
-        {
             "name": "simplesamlphp/simplesamlphp-module-memcachemonitor",
             "version": "v0.9.0",
             "source": {
@@ -1465,7 +1412,6 @@
             "require": {
                 "php": ">=5.6",
                 "simplesamlphp/composer-module-installer": "~1.1",
-                "simplesamlphp/simplesamlphp-module-ldap": "^0.9",
                 "webmozart/assert": "~1.4"
             },
             "require-dev": {
</pre>
</details>

**Comment by jaimeperez** [comment]
I wouldn't recommend you to deploy the way you are doing it, actually. At least, you should be running `composer update`, because otherwise you are using dependencies that are not the best fit for your PHP version. Typically, we try to keep the `composer.lock` file to the absolutely minimum PHP version supported. If you are running PHP 7.3 and deploying like you are doing now, you will be using very old software for no good reason.

In any case, I've just released `1.18.2` to address this issue.

**Comment by francoisfreitag** [comment]
Thanks a lot for the new release and your recommendation, I’ll look into alternative installation methods.

**Comment by hparadiz** [comment]
The best practice for composer packages is to use `composer update` during development only and to commit your lock file to your project's git repo. Then run only `composer install` during deployment. `composer install` will always use the lock file if it's present and only install the specific version in there.

In my deployment script I also add `--ignore-platform-reqs` to `composer install` for exactly the reason for this ticket. Sometimes package maintainers get overzealous with the requirements.
