### ISSUE TITLE
Documentation: Link to "Automated Metadata Management" is dead

### ISSUE THREAD

**Issue by lmaylein** [simplesamlphp/simplesamlphp#1243]
Small "bug" in documentation:
The URL https://simplesamlphp.org/docs/stable/simplesamlphp-automated_metadata doesn't work.

**Comment by tvdijen** [comment]
Good catch.. It has been moved to the metarefresh-module:
https://github.com/simplesamlphp/simplesamlphp-module-metarefresh/blob/master/docs/simplesamlphp-automated_metadata.md

**Comment by tvdijen** [comment]
Closed in 9e76790
