### ISSUE TITLE
Documentation Links for stable aka 1.18 are broken

### ISSUE THREAD

**Issue by jonas-weismueller-jdas** [simplesamlphp/simplesamlphp#1245]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
Some stable documentation links are broken, e.g.:
https://simplesamlphp.org/docs/stable/consent:consent
If I replace stable with "1.17" it show the documentation of the previous stable version.

**To Reproduce**

1. Go to https://simplesamlphp.org/docs/stable/
2. Scroll down to 
> 'Consent module'
3. Click on the link of the 'Consent module' which is https://simplesamlphp.org/docs/stable/consent:consent
4. See error "404 - Not Found"

**Expected behavior**
To see similar content as given by https://simplesamlphp.org/docs/1.17/consent:consent

**Comment by jaimeperez** [comment]
Hi @jonas-weismueller-jdas!

Thanks a lot for letting us know. This one in particular is already fixed, and other issues that we've noticed have just been fixed as well and being deployed to the website.
