### ISSUE TITLE
composer install gives an error Failed to execute unzip -qq  './modules/ldap/79fac65b4802bcc31f65f001e1be84ea' -

### ISSUE THREAD

**Issue by jeroenos** [simplesamlphp/simplesamlphp#1253]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
When execute the command: composer install  , I getr the following error:

Installing simplesamlphp/simplesamlphp-module-ldap (v0.9.3): Loading from cache
    Failed to execute unzip -qq  './modules/ldap/04bb8741e53997e6bba301745902de23' -d '/Users/jeroen/Sites/simplesamlphp/vendor/composer/df2459a9'
replace /Users/jeroen/Sites/simplesamlphp/vendor/composer/df2459a9/simplesamlphp-simplesamlphp-module-ldap-e783f9e/lib/Auth/Ldap.php? [y]es, [n]o, [A]ll, [N]one, [r]ename:  NULL
(EOF or read error, treating as "[N]one" ...)
  The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class

**To Reproduce**
1. Open a terminal and navigate to the simplesamlphp directory.
2. Execute: composer install

**Expected behavior**
An installation with no errors.

**Additional context**

**Comment by tvdijen** [comment]
Is this with a checkout of `master`?

**Comment by jaimeperez** [comment]
It makes full sense. In case-insensitive filesystems, you can't have a file named `LDAP.php` and another one named `Ldap.php` in the same directory. If we want to rename that class, we need to get rid of the old file and add a mapping to the autoloader in SSP.

**Comment by jeroenos** [comment]
It is a checkout of the master.

**Comment by jeroenos** [comment]
I work on a mac, by the way, so a case-insensitive filesystem indeed.

**Comment by tvdijen** [comment]
Mac, I could've guessed :/  Thanks for reporting this @jeroenos

**Comment by jaimeperez** [comment]
@jeroenos, independently of this issue (which we should fix), I'd recommend you to create a volume with a case-sensitive filesystem on it and put all your source code in there. Otherwise, you'll have this issue again and again.

**Comment by jeroenos** [comment]
fortunately, I've got a linux too :+1:

**Comment by tvdijen** [comment]
This was fixed in 1.18.3
