### ISSUE TITLE
Custom login errors

### ISSUE THREAD

**Issue by thebatclaudio** [simplesamlphp/simplesamlphp#1256]
Sorry if this feature already exists, but I didn't know what type i had to use for this issue.
I developed a custom auth source in simplesamlphp IDP, and now I need to prevent access to users that were inactive for 180 days.
I tried to return a custom error in this way (in my auth source code):

`throw new \SimpleSAML\Error\Error('USERINACTIVE');`

I added two entries in `errors.definition.json`: `title_USERINACTIVE` and `descr_USERINACTIVE`.
I also added the same two entries in `errors.translation.json`

But when I try to log in with a user that is inactive it says "not translated () not translated ()"

I'm sure that I'm forgetting to do some things, but what? Can you help me or link me some documentation page where is explained how to define custom errors?

Thank you

**Comment by thebatclaudio** [comment]
I think that I just found my problem: I had to add my custom error in `/lib/SimpleSAML/Error/ErrorCodes.php`.
It's right?

**Comment by jaimeperez** [comment]
Hi @thebatclaudio,

No, you should never modify the source code of SimpleSAMLphp (or any other library, for that matter).

In this case, the easiest is to just create your own exception. Place it in your module and raise it from there. Then you can also create your own template if you need, or even extend the existing one and modify the error message you need to display.
