### ISSUE TITLE
[statistics] Could not get configuration: The configuration (config/module_statistics.php) is invalid: Missing configuration file

### ISSUE THREAD

**Issue by shiwani-at** [simplesamlphp/simplesamlphp#1257]
Hello,

Please help in fixing below issue while configuring SimpleSAML:

[statistics] Could not get configuration: The configuration (config/module_statistics.php) is invalid: Missing configuration file

**Comment by jaimeperez** [comment]
Hi @shiwani-at,

This is not a support forum. If you need support, I recommend you to use [the mailing list](https://groups.google.com/forum/#!forum/simplesamlphp).

In this case, you just need to disable the statistics module.

**Comment by djdevin** [comment]
Would have been nice to know that this actually was a bug, instead of closing it as a support issue.

Fixed in 1.18.3: https://simplesamlphp.org/docs/stable/simplesamlphp-changelog
