### ISSUE TITLE
Metaparser (metarefresh) seems to ignore isDefault and index on SSO endpoints

### ISSUE THREAD

**Issue by creativeprogramming** [simplesamlphp/simplesamlphp#126]
To reproduce: 

1) Configure your simplesamlphp instance to use metarefresh and parse this metadata URL that is an example ADFS XML SAML metadata: https://gist.githubusercontent.com/creativeprogramming/363aa9b0191a5c63dc6b/raw/

(don't try to validate metadata signature as I obfuscated the server name, so I edited the metadata content, use just the default metarefresh config, the easy way)

2) Notice that the metadata XML contains this:

```xml
<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" 

Location="https://adfs.server.url/adfs/ls/" index="0" isDefault="true"/>

<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" 

Location="https://adfs.server.url/adfs/ls/" index="1"/>

<AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" 

Location="https://adfs.server.url/adfs/ls/" index="2"/>
```
*notice the *isDefault* and index=0 attributes on HTTP-POST endpoint

3) But resulting simplesamlphp cached metadata will contain this:

```php
array (
    0 =>
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://adfs.server.url/adfs/ls/',
    ),
    1 =>
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
      'Location' => 'https://adfs.server.url/adfs/ls/',
    ),
  ),
```

ending up using HTTP-Redirect as preferred endpoint while the IdP instead specifies HTTP-POST

**Comment by jaimeperez** [comment]
I think this was just a confusion, and therefore I'm closing the issue.

**Comment by creativeprogramming** [comment]
right it was confusion, i confirm, was parsed correctly, sorry for delay

**Comment by jaimeperez** [comment]
No problem @creativeprogramming, thanks a lot for confirming! :smile:
