### ISSUE TITLE
Session handling for PHP version 7.3.13 broken

### ISSUE THREAD

**Issue by sunny-udhani** [simplesamlphp/simplesamlphp#1262]
PHP = `7.3.13`
SimpleSAML = `1.18.3`

On the call of `new \SimpleSAML\Auth\Simple('default-sp');` it tries to create a new session or use the existing session for SimpleSAML, where it fails with an error

```
Fatal error: Uncaught SimpleSAML\Error\Exception: Cannot load PHP session with a specific ID. in /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:268 
Stack trace: 
#0 /var/simplesamlphp/lib/SimpleSAML/Session.php(344): SimpleSAML\SessionHandlerPHP->loadSession('...') 
#1 /var/simplesamlphp/lib/SimpleSAML/Session.php(259): SimpleSAML\Session::getSession() 
#2 /var/simplesamlphp/lib/SimpleSAML/Auth/Simple.php(51): SimpleSAML\Session::getSessionFromRequest() 
#3 /var/www/html/*.php(14): SimpleSAML\Auth\Simple->__construct('default-sp') 
#4 /var/www/html/*.php(186): .....
#5 {main} thrown in /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 268
```

I went through issue #1006 to find a solution but it seems there is an ask regarding this same issue in last comment of that issue.

**Comment by sunny-udhani** [comment]
@tvdijen Can you point me to a fix or configuration problem I'm overlooking?

**Comment by jaimeperez** [comment]
Hi @sunny-udhani,

I just brought up a docker container with the exact same versions of PHP and SimpleSAMLphp, and created a dead-simple test like the one you are suggesting. I also configured it to use PHP sessions. I'm afraid I'm unable to reproduce the issue, so it looks like a deployment or integration issue.

**Comment by sunny-udhani** [comment]
@jaimeperez can you share a little about the config you deployed?

For me, the authentication source works on the simpleSAML test page i.e. https://[::]/simplesaml/module.php/core/authenticate.php

But for a validation page in the application, it fails after it has user authenticated with IDP and has the auth token already in session.

**Comment by jaimeperez** [comment]
You can actually see the entire [config file](https://github.com/simplesamlphp/docker-simplesamlphp/blob/master/sp1/config.php).

If testing authentication works fine, but you are getting that error in your integration, I'd say there's likely a configuration error wrt your sessions, although it could also be some issue in the integration code. Hard to say without seeing it, though.

**Comment by sunny-udhani** [comment]
@jaimeperez I have been looking into sessions configuration and stumbled upon these error messages generated by simplesaml, this is after the authentication is done from the IDP.

```
simplesamlphp ERR [TR78233f58] Error creating session: Headers already sent., referer: https://[::]/

simplesamlphp WARNING [37688e2436] Could not load state specified by InResponseTo: NOSTATE Processing response as unsolicited., referer: https://[::]/
```

And after the auth is done, it comes back to the validation PHP page where I have this `var_dump(session_status());` to check whether SSP started a session, but it returns `PHP_SESSION_NONE`

But the cookies SimpleSAML and SimpleSAMLAuthToken have values and as seen from the error message I shared in the issue, it tries to load the session using that session id from cookie SimpleSAML.

**Comment by jaimeperez** [comment]
If I recall correctly, trying to load a session in PHP 7.3 when headers have already been sent (output was generated) fails. That would explain why you are seeing this after upgrading to PHP 7.3. It looks like something is generating output in your setup (could be configuration, or your own app, or something else), and that's what's preventing the session from being loaded.

**Comment by sunny-udhani** [comment]
Got your point, I researched this and found out that sessions can't be started after any HTML is sent as output and that was the case with my auth setup. 
So I just moved the call to SSP before sending any HTML and it works as expected now. 
Thanks for all the help @jaimeperez

**Comment by arunarch84** [comment]
Hi,
Recently I have upgraded php from 7.1 to 7.4 and we are seeing issue of infinite loop, also we have latest version of simplesaml 1.19 is in placee

Could you please help me to debug abd fix the issue.

Notes :- We see only warning related to couldn't able to load the state.

**Comment by tvdijen** [comment]
@arunarch84 State issues are setup-related.. It's pretty much impossible to debug them for you.
Please go over this; https://github.com/simplesamlphp/simplesamlphp/wiki/State-Information-Lost

And if it doesn't work out, please ask your question with enough information to help you to our [mailing list](https://groups.google.com/g/simplesamlphp).
Right here is an issue tracker, not a support forum, so the mailing list will get your question/issue much more exposure!

**Comment by souheyltoumi** [comment]
@arunarch84  were you able to get the fix for this issue
