### ISSUE TITLE
SimpleSamlPHP compatibility with PHP 7.2

### ISSUE THREAD

**Issue by sairamsrirangam** [simplesamlphp/simplesamlphp#1265]
Hello,

We have upgraded SimpleSamlPHP to the latest version(1.18.3). We found that it is compatible with PHP 7.2  from the official site but on checking, we found out that it has compatibility issues with PHP 7.2.

Below are some of the issues,

simplesamlphp\vendor\phpmailer\phpmailer\src\PHPMailer.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 845 | WARNING | INI directive 'mbstring.func_overload' is deprecated
     |         | since PHP 7.2
----------------------------------------------------------------------
saml2\src\SAML2\Signature\MissingConfigurationException.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 7 | ERROR | The interface Throwable cannot be implemented directly,
   |       | extend the Exception class instead.
----------------------------------------------------------------------

Could you please confirm if latest version of SimpleSamlPHP compatible with PHP 7.2 and if there are any patches available.

Thanks and Regards
Sairam Srirangam

**Comment by tvdijen** [comment]
First issue should be examined, but the second one is a false positive by whatever tool you're running against the code. A similar issue was reported before; https://github.com/simplesamlphp/saml2/issues/113

**Comment by tvdijen** [comment]
Actually the first one is also just an issue with your tool..
According to [PHP documentation](https://www.php.net/manual/en/function.ini-get#refsect1-function.ini-get-returnvalues) it's perfectly legal to use `ini_get()` on non-existing values.. It will simply return `false`..

**Comment by sairamsrirangam** [comment]
Thanks, 

Apart from those two errors, there are some more errors that are reported by the tool(Code Sniffer), could you please confirm if these are also false positives.

\aleweb\simplesamlphp\lib\SimpleSAML\Locale\Translate.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 69 | WARNING | Since PHP 7.0, functions inspecting arguments, like
    |         | debug_backtrace(), no longer report the original
    |         | value as passed to a parameter, but will instead
    |         | provide the current value. The parameter
    |         | "$configuration" was used, and possibly changed (by
    |         | reference), on line 63.
----------------------------------------------------------------------

vendor\paragonie\random_compat\lib\random_bytes_mcrypt.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 1 LINE
----------------------------------------------------------------------
 60 | ERROR | Extension 'mcrypt' is deprecated since PHP 7.1 and
    |       | removed since PHP 7.2; Use openssl (preferred) or
    |       | pecl/mcrypt once available instead
 60 | ERROR | Function mcrypt_create_iv() is deprecated since PHP 7.1
    |       | and removed since PHP 7.2; Use random_bytes() or
    |       | OpenSSL instead
 60 | ERROR | The constant "MCRYPT_DEV_URANDOM" is deprecated since
    |       | PHP 7.1 and removed since PHP 7.2
----------------------------------------------------------------------

vendor\symfony\config\Resource\ClassExistenceResource.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
  12 | WARNING | 'resource' is a soft reserved keyword as of PHP
     |         | version 7.0 and should not be used to name a class,
     |         | interface or trait or as part of a namespace
     |         | (T_NAMESPACE)
 164 | WARNING | Since PHP 7.0, functions inspecting arguments, like
     |         | debug_backtrace(), no longer report the original
     |         | value as passed to a parameter, but will instead
     |         | provide the current value. The parameter "$previous"
     |         | was used, and possibly changed (by reference), on
     |         | line 142.
----------------------------------------------------------------------

simplesamlphp\vendor\symfony\config\Tests\Util\XmlUtilsTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 145 | ERROR | The behaviour of hexadecimal numeric strings was
     |       | inconsistent prior to PHP 7 and support has been
     |       | removed in PHP 7. Found: '0xFF'
----------------------------------------------------------------------

simplesamlphp\vendor\symfony\http-foundation\JsonResponse.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 176 | ERROR | The constant "JSON_THROW_ON_ERROR" is not present in
     |       | PHP version 7.2 or earlier
----------------------------------------------------------------------

aleweb\simplesamlphp\vendor\twig\twig\src\Profiler\Profile.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
 174 | WARNING | Method name "Profile::__serialize" is discouraged;
     |         | PHP has reserved all method names with a double
     |         | underscore prefix for future use.
 182 | WARNING | Method name "Profile::__unserialize" is discouraged;
     |         | PHP has reserved all method names with a double
     |         | underscore prefix for future use.
----------------------------------------------------------------------

Thanks,
Sairam

**Comment by tvdijen** [comment]
You can perfectly do that yourself by taking a look at the code...

**Comment by jaimeperez** [comment]
SimpleSAMLphp is compatible with PHP 7.2 and 7.3.

Warnings are not errors. The only actual error you are reporting in our codebase is a false positive, as Tim already told. The rest are in third-party libraries used by SimpleSAMLphp, so not even in our codebase.

If you want to get rid of those errors and warnings, probably the easiest solution is to run `composer update` in your SimpleSAMLphp installation so that it pulls and installs dependencies tailored to your platform. As you will surely understand, the single package we distribute cannot be tailored to all the different deployments. That's what composer is for.

In any case, the simplest solution I would recommend you is to stop running automated tools on the code you deploy and assuming it won't work if you get any output and you don't really understand what's going on. It will only generate noise and confusion. If you find an actual bug (i.e. something is not working) your should of course report it.

**Comment by sairamsrirangam** [comment]
Hello Jaime Pérez Crespo,

Thanks for your confirmation.
