### ISSUE TITLE
Deprecate support for SAML 1.1

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#1267]
We should mark support for SAML 1.1 as deprecated in 1.19.

**Comment by tvdijen** [comment]
I'm pretty sure I have already done this for 1.18

**Comment by jaimeperez** [comment]
Yep, I saw it in the upgrade notes at least, but still wanted to add an issue as a reminder to check every place and maybe even add warnings in the logs.

**Comment by tvdijen** [comment]
I have done some preparations in this regard;  9c3913f83432fb8e0dac206b3e5f3db491c57acc
That's all I could find..

**Comment by jaimeperez** [comment]
Looks pretty exhaustive! But that's actually resolving #1268, not this one, right?

**Comment by tvdijen** [comment]
Correct

**Comment by thijskh** [comment]
I have:

- Noted it in changelog and upgrade notes.
- Noted it in config and metadata templates.
- Noted it in Shib 1.3 specific documentation chapters
- Added logging notices in the acs and sso endpoint.

For the last bullet, I chose to only add it there so you get things in your logs if the protocol is actually in use (not if you happen to have some config around for it).
