### ISSUE TITLE
Very short errorreport with using oldui

### ISSUE THREAD

**Issue by pajavyskocil** [simplesamlphp/simplesamlphp#1269]
**Describe the bug**
After adding this commit https://github.com/simplesamlphp/simplesamlphp/commit/4c6ce9569d63c97f6d32f10e327f18a38d95885c error report send email only with the text from the user with using oldui.

**To Reproduce**
1. Set 'newui'  => false
2. Send some errorreport

**Expected behavior**
I think that is useful to send more information as 'trackId' and other information or enforcing the twig template as it was before adding the commit https://github.com/simplesamlphp/simplesamlphp/commit/4c6ce9569d63c97f6d32f10e327f18a38d95885c.

**Comment by thijskh** [comment]
Thanks! We test too much with newui enabled I'm afraid...
