### ISSUE TITLE
baseurlpath has been set, still get "session_set_cookie_params() expects parameter 3 to be string, null given"

### ISSUE THREAD

**Issue by bentterp** [simplesamlphp/simplesamlphp#1270]
Hi, I'm trying to build simplesamlphp on OpenShift.
(The existing 2-year old image cannot be used as it requires root permissions.)

I've configured baseurlPath and the redirect from / to /module.php/core/frontpage_welcome.php works as expected, but the welcome page throws an error:
Uncaught TypeError: session_set_cookie_params() expects parameter 3 to be string, null given in /opt/app-root/src/lib/SimpleSAML/SessionHandlerPHP.php:102

Stack trace:
#0 /opt/app-root/src/lib/SimpleSAML/SessionHandlerPHP.php(102): session_set_cookie_params(0, '/', NULL, false, true)
#1 /opt/app-root/src/lib/SimpleSAML/SessionHandler.php(140): SimpleSAML\SessionHandlerPHP-&gt;__construct()
#2 /opt/app-root/src/lib/SimpleSAML/SessionHandler.php(43): SimpleSAML\SessionHandler::createSessionHandler()
#3 /opt/app-root/src/lib/SimpleSAML/Session.php(329): SimpleSAML\SessionHandler::getSessionHandler()
#4 /opt/app-root/src/lib/SimpleSAML/Session.php(260): SimpleSAML\Session::getSession()
#5 /opt/app-root/src/lib/SimpleSAML/Logger.php(325): SimpleSAML\Session::getSessionFromRequest()
#6 [internal function]: SimpleSAML\Logger::shutdown()
#7 {main}
  thrown in /opt/app-root/src/lib/SimpleSAML/SessionHandlerPHP.php on line 102

The only things I've been able to find leads me to baseurlPath but I can't figure out why it's not working.

PHP 7.1.8 (cli) (built: Aug  8 2017 09:01:08) ( NTS )
Apache/2.4.34 (Red Hat)

**Comment by tvdijen** [comment]
Your quick fix is probably to set `session.cookie.domain` to an empty string in your config.php..

**Comment by bentterp** [comment]
I tried both the quick fix and the new version (building straight from Git), but unfortunately the behaviour remains the same.

**Comment by tvdijen** [comment]
That's weird.. what's the line number where it breaks on the git-version?

**Comment by bentterp** [comment]
[fbte61@SEA37LT16653 ~]$ curl http://simplesamlphp.###################/module.php/core/frontpage_welcome.php
<br />
<b>Fatal error</b>:  Uncaught TypeError: session_set_cookie_params() expects parameter 3 to be string, null given in /opt/app-root/src/lib/SimpleSAML/SessionHandlerPHP.php:377
Stack trace:
#0 /opt/app-root/src/lib/SimpleSAML/SessionHandlerPHP.php(377): session_set_cookie_params(0, '/', NULL, false, true)
#1 /opt/app-root/src/lib/SimpleSAML/Session.php(170): SimpleSAML\SessionHandlerPHP-&gt;setCookie('SimpleSAML', '31bec9ade371112...', Array)
#2 /opt/app-root/src/lib/SimpleSAML/Session.php(296): SimpleSAML\Session-&gt;__construct()
#3 /opt/app-root/src/lib/SimpleSAML/Logger.php(325): SimpleSAML\Session::getSessionFromRequest()
#4 [internal function]: SimpleSAML\Logger::shutdown()
#5 {main}
  thrown in <b>/opt/app-root/src/lib/SimpleSAML/SessionHandlerPHP.php</b> on line <b>377</b><br />
[fbte61@SEA37LT16653 ~]$

**Comment by tvdijen** [comment]
Ahh, I see.. It's basically the same issue, but in a different file!

**Comment by tvdijen** [comment]
Would you mind giving it a try with a new git checkout??

**Comment by bentterp** [comment]
Sorry, missed that you had a fix waiting. I'll give it a shot tomorrow if I get a little free time.

**Comment by tvdijen** [comment]
Any luck @bentterp ?

**Comment by bentterp** [comment]
Yes, that got me past that one, thank you very much.

I think the blank page I meet next is because I don't have a MySQL configured.....

**Comment by tvdijen** [comment]
The default config should not require any database whatsoever.. Can you find any clues in the webserver logs?

**Comment by bentterp** [comment]
Not really :-(
I get to the frontpage which looks like the docs says only parts are missing.
If I click one of the language links, I get a blank page.
I can go through the login dialogue but end up at the loginuserpass.php url and it's blank
No errors in the logs

**Comment by reswild** [comment]
I got a related error after updating to version 1.18.4:
`PHP Fatal error:  Uncaught TypeError: setcookie() expects parameter 5 to be string, null given in /var/www/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php:1260`
Changing session.cookie.domain from null to an empty string in config.php solved the problem for me.

**Comment by bentterp** [comment]
`session.cookie.domain = '';` seems to work better than `session.cookie.domain = null;`
Thanks @reswild
