### ISSUE TITLE
PATH_INFO issue with SSP behind reverse proxy

### ISSUE THREAD

**Issue by vanrar68** [simplesamlphp/simplesamlphp#1271]
Hello,

Since 1.18.0 I can't get SSP to work anymore on my hosted environment (SSP on Apache behind a nginx reverse proxy).Everthing was fine up to 1.17.7

Logs:
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] Backtrace:
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 3 /htdocs/public/sp/lib/SimpleSAML/Error/Assertion.php:83 (SimpleSAML\Error\Assertion::onAssertion)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 2 [builtin] (assert)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 1 /htdocs/public/sp/lib/SimpleSAML/Module.php:139 (SimpleSAML\Module::process)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 0 /htdocs/public/sp/simplesaml/module.php:10 (N/A)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] SimpleSAML\Error\Exception: Error 2 - strpos(): Offset not contained in string at /htdocs/public/sp/lib/SimpleSAML/Module.php:147
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] Backtrace:
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 3 /htdocs/public/sp/simplesaml/_include.php:48 (SimpleSAML_error_handler)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 2 [builtin] (strpos)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 1 /htdocs/public/sp/lib/SimpleSAML/Module.php:147 (SimpleSAML\Module::process)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 0 /htdocs/public/sp/simplesaml/module.php:10 (N/A)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] SimpleSAML\Error\NotFound: The requested page '[CUT]/simplesaml/module.php/core/frontpage_welcome.php' could not be found. The URL must at least contain a module name followed by a slash.
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] Backtrace:
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 1 /htdocs/public/sp/lib/SimpleSAML/Module.php:152 (SimpleSAML\Module::process)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] 0 /htdocs/public/sp/simplesaml/module.php:10 (N/A)
Jan 16 08:25:59 simplesamlphp ERROR [e093bd1540] Error report with id ceeea48d generated.

I tracked down the issue to be linked to commit [https://github.com/simplesamlphp/simplesamlphp/commit/29b63583d527f568fa8ab2c2d25e11c83f89c33d#diff-af02f7f3daea842b5289008d5d2704c1]

If I revert the change in Module.php everything works great again:
- $url = $request->getPathInfo();
+ $url = $request->server->get('PATH_INFO');

Regards

-- 
Joaquim

**Comment by vanrar68** [comment]
Forgot to mention: the commit change that triggers the issue is located in lib/SimpleSAML/Module.php

**Comment by vanrar68** [comment]
And also forgot to mention that the problem can be triggered by simply accessing /simplesaml/index.php

**Comment by tvdijen** [comment]
Hi @vanrar68 ! This has to do with your nginx configuration of the path_info parameter..

**Comment by vanrar68** [comment]
Yeah, I've seen that. But it's a global reverse proxy on a hosted environment so they probably won't let me change that :-)
A fix that seems to do the trick is to get the PATH_INFO from the ORIG_PATH_INFO like this:

if (!isset($GLOBALS["_SERVER"]['PATH_INFO']) && isset($GLOBALS["_SERVER"]['ORIG_PATH_INFO']))
{
	$GLOBALS["_SERVER"]['PATH_INFO'] = $GLOBALS["_SERVER"]['ORIG_PATH_INFO'];
}
$GLOBALS["_SERVER"]['PATH_INFO'] = preg_replace ("/\/+/","/",$GLOBALS["_SERVER"]['PATH_INFO']);

**Comment by tvdijen** [comment]
Sure, you can fix anything by messing with globals, but that's not what we should be doing.
I'm sure your global reverse proxy has a specific vhost-config for your SSP-instance that you can change without touching anything else..

**Comment by vanrar68** [comment]
Ok, I'll ask my hosting provider if this is possible. Thanks for your time

Regards

**Comment by BAGELreflex** [comment]
From the PHP docs: https://www.php.net/manual/en/reserved.variables.server.php

I found:

> Note: As of PHP 4.3.2, PATH_TRANSLATED is no longer set implicitly under the Apache 2 SAPI in contrast to the situation in Apache 1, where it's set to the same value as the SCRIPT_FILENAME server variable when it's not populated by Apache. This change was made to comply with the CGI specification that PATH_TRANSLATED should only exist if PATH_INFO is defined. Apache 2 users may use AcceptPathInfo = On inside httpd.conf to define PATH_INFO.

So, can you try adding the `AcceptPathInfo = On` to your Apache?

I also found in a comment: https://www.php.net/manual/en/reserved.variables.server.php#120979

> Data: $_SERVER['PATH_INFO']
> Data type: String
> Purpose: Find the path-info, which is data after the .php filename in the URL call. It's a strange concept.
> Caveat: Some environments may not support it, it is best avoided unless you have complete server control
> Works on web mode: Yes
> Works on CLI mode: No

So, it not working in CLI mode makes me think that it may not work correctly behind a reverse proxy, depending on how the proxy is configured. Similarly to why the HTTP-Artifact binding exists, not all User Agents are implemented the same way, and handle proxy/redirect/etc as expected.
