### ISSUE TITLE
Upgrade to Twig 3

### ISSUE THREAD

**Issue by simonberger** [simplesamlphp/simplesamlphp#1273]
Can you please support Twig 3? It is more or less compatible to 2. But as Twig 1 is currently supported as well there might be some things to do or to drop Twig 1.

**Comment by tvdijen** [comment]
I had investigated this a while ago and there was an issue that I couldn't get around...
Twig 3 no longer relies on Twig Extensions, meaning we would have to rewrite https://github.com/simplesamlphp/twig-configurable-i18n and somehow keep it compatible with Twig 2 as well..
It's a bit of a nightmare ...

**Comment by paulrwest** [comment]
I'm also in need for twig 3 to be supported as I use cakePHP framework on version 4 which has Twig package fixed to v3.1.1 I noticed even dev-master is not on v3 of twig so I'm a bit stuck. 

Any suggestions how to get around this I've not hit a composer conflict like this before?

**Comment by tvdijen** [comment]
I don't understand.. CakePHP doesn't have a dependency on Twig?  Anyway, no there is no solution.. This issue needs to be resolved

**Comment by paulrwest** [comment]
Thanks for the reply, sorry my mistake it is the [cakephp/bake](https://packagist.org/packages/cakephp/bake) package that relies on [cakephp/twig-view](https://packagist.org/packages/cakephp/twig-view) package which relies on [twig/twig:3](https://packagist.org/packages/twig/twig#3). 

This is a "require-dev" package so I have found a solution of removing that package. It's not ideal having to remove a feature from something I use to be able to pull down simplesamlphp. I think I'll end up removing simplesamlphp and adding bake package when I need to bake.

**Comment by tvdijen** [comment]
I can eee how that's suboptimal.. Hopefully we can work out this issue in the new year if we can get a little bit more resourcing..

**Comment by ajibarra** [comment]
+1 for this feature. Another CakePHP user here having issues with twig 3.

**Comment by drjayvee** [comment]
Our project is relying on SimpleSAMLphp and Twig heavily, so we might be able to donate some of our tech debt time budget on this issue.

Instead of fixing `twig-configurable-i18n` - which, according to its own documentation, "is a hack" - could this project migrate to Twig's `trans`?

**Comment by tvdijen** [comment]
Help is very much appreciated here @drjayvee !  For us it would make the most sense to use the `symfony/twig-bridge`, but I'm not sure it can fully replace `twig-configurable-i18n`..  Perhaps @jaimeperez can remember the exact need for the 'hack'

**Comment by thijskh** [comment]
Fixed in #1531

**Comment by greew** [comment]
A huge thanks to @mrbase for his contribution!
