### ISSUE TITLE
exampleauth module not working with its default twig template

### ISSUE THREAD

**Issue by gitator** [simplesamlphp/simplesamlphp#1275]
I've just installed 1.18.4 and enabled exampleauth in order to test a new module I'm working on, but I'm getting this exception:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: Template: Could not find template file [exampleauth:authenticate.twig] at [/mnt/data/apache/htdocs/xmlrpc-2fa/simplesamlphp-1.18.4/modules/exampleauth/templates/authenticate.twig]
Backtrace:
4 lib/SimpleSAML/XHTML/Template.php:639 (SimpleSAML\XHTML\Template::findTemplatePath)
3 lib/SimpleSAML/XHTML/Template.php:545 (SimpleSAML\XHTML\Template::show)
2 modules/exampleauth/www/authpage.php:86 (require)
1 lib/SimpleSAML/Module.php:254 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

At a first glance it's like findTemplatePath() in lib/SimpleSAML/XHTML/Template.php is not able to 
find filename when it receives a .twig template and then it doesn't return it but a exception. Here:

626         $filename = $this->normalizeTemplateName($filename);
627         foreach ($extensions as $extension) {
628             if (file_exists($filename . $extension)) {
629                 return $filename . $extension;
630             }
631         }
632 
633         // not found in default template
634         if ($throw_exception) {
635             // log error and throw exception
636             $error = 'Template: Could not find template file [' . $template . '] at [' . $filename . ']';
637             Logger::critical($_SERVER['PHP_SELF'] . ' - ' . $error);
638 
639             throw new \Exception($error);
640         } else {

**Comment by tvdijen** [comment]
Are you using the old or new UI?

**Comment by tvdijen** [comment]
I fact, we never had a template in the old UI, which is bugging is now..
Need an old-style template for exampleauth for BC-purposes..

**Comment by gitator** [comment]
> You must be using the old UI.. For some reason we have removed the old-UI template for exampleauth..

Exampleauth is running as configured by default, I've not touched it.

**Comment by thijskh** [comment]
Thanks!
