### ISSUE TITLE
add redirection after login authentication

### ISSUE THREAD

**Issue by richardhdc** [simplesamlphp/simplesamlphp#1277]
Currently, the service provider after login is redirected to the authenticate page with details of attributes and cookie expiration. Is there a way to redirect them to another page of the domain that is not part of the saml installation like another framework that will receive the attributes etc.?

**Comment by thijskh** [comment]
What you are using is just the interface to test authentication. Please see this part of the manual to learn how to perform the actual integration in your application:
https://simplesamlphp.org/docs/stable/simplesamlphp-sp#section_6
