### ISSUE TITLE
tests directory is missing in the release source assets *.zip, *.tar.gz

### ISSUE THREAD

**Issue by maxplatonov** [simplesamlphp/simplesamlphp#1278]
The directory `tests` is included in the composer.json `autoload-dev`, but is missing in the releases source archives:

https://github.com/simplesamlphp/simplesamlphp/blob/master/composer.json#L28-L32

**To Reproduce**
1. `composer create-project simplesamlphp/simplesamlphp`
2. Configure a webserver
3. Navigate to the app's homepage

![Capture d’écran de 2020-02-14 11-04-33](https://user-images.githubusercontent.com/25581965/74521560-d7b59600-4f19-11ea-8bc5-6585a735a87e.png)

**Comment by thijskh** [comment]
I think if you want to include dev dependencies, it makes sense to install from git checkout. If you want to use release archives, you should use composer only with the production dependencies.

**Comment by maxplatonov** [comment]
Hello Thijs,

Thanks, I'd like to install the app via composer as per https://packagist.org/packages/simplesamlphp/simplesamlphp

The `tests` directory is present in the packages on https://simplesamlphp.org/download?latest 
but not on github. Is there a reason for that?

Maybe you should update the installation instructions on https://packagist.org/packages/simplesamlphp/simplesamlphp to:
- `composer create-project simplesamlphp/simplesamlphp --no-dev`
and/or
- `composer create-project simplesamlphp/simplesamlphp --prefer-source --remove-vcs`

**Comment by jaimeperez** [comment]
Hi @maxplatonov!

The packages on our own website are, actually, the tarballs generated and uploaded here. The packages you are probably downloading by calling `composer create-project` are probably the zip files github is generating automatically, which are out of our control.

In any case, using `create-project` doesn't make any sense if you are using SimpleSAMLphp as an SP, as it would just be another dependency of your application. Perhaps what we should do is provide different guidance depending on how you plan to use the software, as `create-project` makes definitely much more sense when deploying it as an IdP.

**Comment by maxplatonov** [comment]
Hi @jaimeperez,

Thanks for your feedback. Indeed my intention is to use SimpleSAMLphp as an IdP on a dev environment in the first place.

I consider the issue resolved and will close it.

Kind regards,

**Comment by maxplatonov** [comment]
FYI, 

I think the reason why the directory `tests` is missing from the github releases sources is this line in https://github.com/simplesamlphp/simplesamlphp/blob/master/.gitattributes#L4

**Comment by jaimeperez** [comment]
Good catch! Thanks a lot for the feedback!
