### ISSUE TITLE
redirection after successful authentication missing port number

### ISSUE THREAD

**Issue by richardhdc** [simplesamlphp/simplesamlphp#1279]
Using a service provider, I authentiated to the idP and redirected back to my SP but the RelayState does not contain the port. Do you think that the RelayState should automatically include the port if there is a port present in the SP?

**Comment by jaimeperez** [comment]
Hi @richardhdc!

The spec is pretty clear about this, the `RelayState` must be returned **untouched**:

> #### 3.1.1 Use of RelayState
>Some bindings define a "RelayState" mechanism for preserving and conveying state information. When such a mechanism is used in conveying a request message as the initial step of a SAML protocol, it places requirements on the selection and use of the binding subsequently used to convey the response. Namely, if a SAML request message is accompanied by RelayState data, then the SAML responder MUST return its SAML protocol response using a binding that also supports a RelayState mechanism, and **it MUST place the exact RelayState data it received with the request into the corresponding RelayState parameter in the response**.
