### ISSUE TITLE
after Authentication session is not being created.

### ISSUE THREAD

**Issue by richardhdc** [simplesamlphp/simplesamlphp#1283]
I call requireAuth and I'm redirected to the login and after filling the User/Password and successfully logged in. I redirected back to the ReturnTo. But on the ReturnTo, I used the attributes to set the sessions and try to redirect to my dashboard page but the session is not created. Does anyone know if there is a print/echo somewhere or something that can halt the creation of session?  Thanks

`
public function loginSso(Guard $authGuard)    

    {  

        $this->idP = new \SimpleSAML\Auth\Simple('default-sp');  

        $attributes = $this->idP->getAttributes();  

        $bool = $authGuard->attempt($attributes); //returns true and try to set the sessions   

        return redirect()->route("dashboard");  

    }  
`

**Comment by jaimeperez** [comment]
Hi @richardhdc,

This is an issue tracker, not a support forum. In any case, [as the documentation says](https://simplesamlphp.org/docs/stable/simplesamlphp-sp#section_6), if you are using PHP sessions in both your application and SimpleSAMLphp, you need to make sure you close SimpleSAMLphp's session after calling it.
