### ISSUE TITLE
handle concurrent user sessions

### ISSUE THREAD

**Issue by jignagandhi1989** [simplesamlphp/simplesamlphp#1284]
Is there a way in simplesamlphp by which we can control how many active sessions for a user can be present at a given time? We have one issue where user are logging in from multiple systems causing lot of active sessions per user and we want to limit to only 1 active session per user.

**Comment by BAGELreflex** [comment]
I feel like you're doing something fundamentally incorrect if your users are generating multiple sessions in SSPHP. A few questions:

- How are you storing your user sessions?
- Are you referring to PHP sessions? Files, memory, memcache, database, etc?
- Are you referring to many cookies being set?
- Are you using the ForceAuthn attribute on your SP or IDP config?
- Exactly how are "many" sessions causing you issues? Is it impacting performance?

**Comment by jaimeperez** [comment]
Hi @jignagandhi1989,

SimpleSAMLphp keeps only one session per user (or, more precisely, per web browser), regardless of how many authentication sources have been used to authenticate them. If you are observing a behaviour different than that, then you might have misconfigured something. If you need support, I'd recommend you to ask in the [mailing list](http://groups.google.com/group/simplesamlphp).
