### ISSUE TITLE
Deprecation warning for lib/SimpleSAML/Auth/Default.php in composer 1.10.0

### ISSUE THREAD

**Issue by cwood-cartera** [simplesamlphp/simplesamlphp#1298]
**Describe the bug**

As of [composer 1.10.0](https://github.com/composer/composer/releases/tag/1.10.0), we are now seeing the following warning regarding psr-4 autoloading:

> Deprecation Notice: Class SimpleSAML\Auth\DefaultAuth located in ./vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Default.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185

**To Reproduce**
1. Install composer 1.10.0
2. Run "composer install" with composer.json containing simplesamlphp
3. See deprecation warning

**Expected behavior**
Clean output from composer without any deprecation warnings.

**Comment by tvdijen** [comment]
Luckily that class will disappear as it is marked deprecated.. It's already removed on our `master`-branch..
However, I don't see how this class does not comply to PSR-4.. Will investigate..

**Comment by tvdijen** [comment]
I'm having trouble reproducing this.. Can you share a composer.json-file that will trigger this?

**Comment by cwood-cartera** [comment]
Aha.  Looks like we are not using the latest version which may be the culprit:
`"simplesamlphp/simplesamlphp": "1.17.1",`

**Comment by tvdijen** [comment]
Ah yes, that makes quite the difference!!
Back then, the class-name didn't match the file-name, which breaks PSR-4..

I can only advice you to use the latest version, as the 1.17-branch has several critical security issues..
