### ISSUE TITLE
Issues in Nginx expecting trailing slash

### ISSUE THREAD

**Issue by cybercorey** [simplesamlphp/simplesamlphp#1300]
**Describe the bug**
Expects trailing slash on all pages (doesn't do this on our old stack nginx/1.4.6, Ubuntu 14.04, php-fpm7.0 & simplesamlphp (1.13.2))
Setting up on nginx/1.17.8, Ubuntu 18.04, php-fpm7.2 & simplesamlphp (1.18.4)

Using nginx config:
```
        location ^~ /simplesamlphp/ {
                alias /{path}/simplesamlphp/www/;

                location ~ ^(?<prefix>/simplesamlphp)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
                        include fastcgi_params;
                        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
                        fastcgi_index index.php;
                        fastcgi_param SCRIPT_FILENAME $request_filename;
                        fastcgi_param SCRIPT_FILENAME $document_root$phpfile;
                        fastcgi_param SCRIPT_NAME $prefix$phpfile;
                        fastcgi_param PATH_INFO $pathinfo;
                        fastcgi_param PHP_VALUE "open_basedir=\"/{path}:/usr/bin:/proc:/tmp\"";
                }
        }
```

**To Reproduce**
Go to https://{domain}/simplesamlphp/module.php/core/frontpage_auth.php

**Expected behavior**
Page loads

**What happens**
The given page was not found. The reason was: The URL must at least contain a module name followed by a slash. The URL was: https://{domain}/simplesamlphp/module.php/core/frontpage_auth.php 

However it works if I add a trailing slash: https://{domain}/simplesamlphp/module.php/core/frontpage_auth.php/

**Comment by tvdijen** [comment]
Please have look at the example here: https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-install.md#configuring-nginx

**Comment by cybercorey** [comment]
Thanks for you quick reply,
This is the config i had started with, I've set the config back to the following to match:

```
        location ^~ /simplesamlphp {
                alias /{path}/simplesamlphp/www;

                location ~ ^(?<prefix>/simplesamlphp)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
                        include          fastcgi_params;
                        fastcgi_pass     unix:/var/run/php/php7.2-fpm.sock;

                        fastcgi_param SCRIPT_FILENAME $document_root$phpfile;

                        # Must be prepended with the baseurlpath
                        fastcgi_param SCRIPT_NAME /simplesamlphp$phpfile;

                        fastcgi_param PATH_INFO $pathinfo if_not_empty;
                        fastcgi_param PHP_VALUE "open_basedir=\"/{path}:/usr/bin:/proc:/tmp\"";
                }
        }
```

Sadly I still get the same result
Does anything stand out to yourself here?

**Comment by cybercorey** [comment]
Hey again, I've reverted the path to just "simplesaml" as per config examples and turned on nginx debugging:
Request to: https://{domain}/simplesaml/module.php/core/frontpage_welcome.php

```
[notice] "^/(.*\.php)(/)(.*)$" matches "/simplesaml/module.php/core/frontpage_welcome.php", request: "GET /simplesaml/module.php/core/frontpage_welcome.php HTTP/1.1", host: "{domain}"
[notice] rewritten data: "/simplesaml/module.php", args: "file=/core/frontpage_welcome.php", request: "GET /simplesaml/module.php/core/frontpage_welcome.php HTTP/1.1", host: "{domain}"
```

Request to: https://{domain}/simplesaml/module.php/core/frontpage_welcome.php/

```
[notice] "^/(.*\.php)(/)(.*)$" matches "/simplesaml/module.php/core/frontpage_welcome.php/", request: "GET /simplesaml/module.php/core/frontpage_welcome.php/ HTTP/1.1", host: "{domain}"
[notice] rewritten data: "/simplesaml/module.php/core/frontpage_welcome.php", args: "file=/", request: "GET /simplesaml/module.php/core/frontpage_welcome.php/ HTTP/1.1", host: "{domain}"
```
Using the trailing slash if fine until I try use query params, then it seems to fall over.

**Comment by cybercorey** [comment]
Found the issue on our end. Looks like something required for moodle to work was breaking this. Thanks for the assist.
