### ISSUE TITLE
kick packagist for 1.18.5

### ISSUE THREAD

**Issue by djdevin** [simplesamlphp/simplesamlphp#1301]
it looks like v1.18.5 hasn't made it there yet

https://packagist.org/packages/simplesamlphp/simplesamlphp

**Comment by jaimeperez** [comment]
Hi @djdevin,

There must be some issue with packagist, because it's not updating even if I ask it to.

**Comment by thijskh** [comment]
The version number was not bumped in `composer.json`. I've now updated the release instructions to add this step.

**Comment by thijskh** [comment]
Fixed now, thanks for reporting!

**Comment by djdevin** [comment]
awesome. thanks!

**Comment by jaimeperez** [comment]
My bad, apologies for overlooking this!
