### ISSUE TITLE
POST to GET redirect loses username parameter

### ISSUE THREAD

**Issue by luqmana** [simplesamlphp/simplesamlphp#1313]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
I have SimpleSAMLphp setup as an IdP and noticed that it always seems to redirect SP-initiated POST requests, made to the saml2/idp/SSOService.php endpoint, to the module.php/core/loginuserpass.php endpoint as a GET request.

Now, login still works fine but since the SP passed a username hint as a POST parameter initially, and SimpleSAMLphp doesn't preserve that, the username field doesn't get pre-filled.

**To Reproduce**
1. Go to SP (portal.azure.com in my case)
2. Enter email 'foo@example.com'
3. Click 'Next and get redirected to SimpleSAMLphp login form

**Expected behavior**
'foo@example.com' in the username field.

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.

**Additional context**

**Comment by jaimeperez** [comment]
Hi @luqmana,

This login hint mechanism is a proprietary mechanism not defined in the SAML standard and SimpleSAMLphp does not support it.

**Comment by luqmana** [comment]
Hi @jaimeperez 

Hmm, did I misunderstand what these are supposed to do? https://github.com/simplesamlphp/simplesamlphp/blob/0c55a0b6a4e5527dbbf263d5f7687cab39298db6/modules/core/www/loginuserpass.php#L29 and https://github.com/simplesamlphp/simplesamlphp/blob/0c55a0b6a4e5527dbbf263d5f7687cab39298db6/modules/core/templates/loginuserpass.twig#L50

**Comment by jaimeperez** [comment]
I'm afraid so. That's just an internal argument used by the login form, so that if there's an error during authentication, the username is prefilled with whatever you used. But definitely not part of any messaging mechanism to pre-select the username in the IdP.

**Comment by luqmana** [comment]
Ah, well thanks for the clarification!

**Comment by jaimeperez** [comment]
No prob! The proper way to do this is using the `Subject` element in the SAML request, but I'm not sure Azure will support that if they are passing it as a query parameter. In any case, SimpleSAMLphp does not support that either, unfortunately.
