### ISSUE TITLE
Provide the version number 

### ISSUE THREAD

**Issue by carnnia** [simplesamlphp/simplesamlphp#1315]
**Is your feature request related to a problem? Please describe.**
As a web developer, dev-ops engineer or server admin I don't have an easy and reliable way to determine the version of simplesamlphp installed on a given server. 

**Describe the solution you'd like**
Add the version number in the README.md

**Describe alternatives you've considered**
The UI did not provide the version. Logging into UI as admin did not help either. 

**Additional context**

**Comment by jaimeperez** [comment]
Hi @carnnia,

Both the new and the old user interface explicitly tell you the version of SimpleSAMLphp you are running. If they don't, you are simply using an ancient version of it. The `getVersion()` function of the `SimpleSAML\Configuration` class (`$SSPROOT/lib/SimpleSAML/Configuration.php` will also tell you the version if you have access to the server.

As a general rule, you should always keep your software up to date.

**Comment by carnnia** [comment]
Hi @jaimeperez 
On some installations i see this in the UI under Configuration tab:
/var/simplesamlphp (1.17.7)

On others I see:
/var/simplesamlphp (master)

Is there a clever way that I could run that getVersion() function from command line?

**Comment by jaimeperez** [comment]
Hi again,

> Is there a clever way that I could run that getVersion() function from command line?

```sh
php -r "require('vendor/autoload.php'); echo SimpleSAML\Configuration::getVersion();"
```

Also, never run master, unless you are doing SimpleSAMLphp development or you know what you are doing.

**Comment by carnnia** [comment]
Thank you @jaimeperez 
That worked nicely:
[simplesamlphp]$ php -r "require('vendor/autoload.php'); echo SimpleSAML\Configuration::getVersion();"
1.18.6
