### ISSUE TITLE
Misbehaviour setting SameSite property on PHP-managed session cookie for PHP<7.3.0

### ISSUE THREAD

**Issue by faragom** [simplesamlphp/simplesamlphp#1320]
**I have tracked the cause to the PHP runtime, so this issue is opened just for the record of this anomalous situation and can be closed as is** 

When the session cookie is marked to set the SameSite property, the first time the cookie is set, the Set-Cookie header does not include the SameSite property, but on a second access, a new Set-Cookie header (this time correct) is issued.

1. Set up your IdP to set SameSite=None on the session cookie
2. Open a clean (Incognito, or clear cookies) client
3. Access the IdP through a requesting SP
4. If the traffic is captured (SAML Tracer will do the trick), the wrong Set-Cookie header can be noticed on the call to SSOService.
5. If steps 2-3 are repeated, the proper Set-Cookie header can be noticed on the call to SSOService 
 
**I have observed this behaviour when using 'phpsession' to keep the session on a `PHP 7.2.30` runtime, but works fine when using 'memcache', so this is the obvious solution until `PHP 7.3.0` or above is installed**.

Proper behaviour has been checked down to the call to `session_set_cookie_params`, and **input parameters are exactly** the same in both successive calls, the one that gives a faulty result and the one that gives a proper result. `session_set_cookie_params` is a PHP builtin, that is called in a tricky way as a workaround when run in `PHP<7.3.0`, as those versions do not support the SameSite parameter yet. 

For the above reason, it is impossible to solve this issue and needs to be worked around using another session keeping mechanism like `memcache`.

Details of the environment where the issue was detected:

```
CentOS 7.3
Linux 3.10.0-514.16.1.el7.x86_64
Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.2.30
```

**Comment by jaimeperez** [comment]
¡Hola Paco!

I've looked into this and I was able to reproduce the issue. I believe the problem here is that the hack for PHP 7.2 was being done at a certain point in the code, completely ignoring every other place where the session is initialized. I've committed a patch that should hopefully fix this.
