### ISSUE TITLE
1.18 and metarefresh: how to upgrade, how to install

### ISSUE THREAD

**Issue by drjayvee** [simplesamlphp/simplesamlphp#1330]
I switched a checkout from `1.17` to `1.18` through `git checkout v1.18.7 && composer install` (basically).

I noticed that `modules/metarefresh/enable` was gone. This very much surprised me, as I had read the [Upgrade notes](https://simplesamlphp.org/docs/stable/simplesamlphp-upgrade-notes-1.18) and the [Changelog](https://simplesamlphp.org/docs/stable/simplesamlphp-changelog#section_9), and nothing prepared me for this.

The latter specifically writes

> Most modules have been externalized. They will not be included in our future releases by default, but will be easily installable using composer. For now, they are still included in the package.

However, changeset ec24be2ff removes `modules/metarefresh`, and that diff is applied to existing repos.

Pouring over the docs I found the page for [Automated Metadata Management](https://github.com/simplesamlphp/simplesamlphp-module-metarefresh/blob/master/docs/simplesamlphp-automated_metadata.md) (now a GitHub page), which writes

> [root@simplesamlphp] cd /var/simplesamlphp
[root@simplesamlphp simplesamlphp] touch modules/cron/enable
[root@simplesamlphp simplesamlphp] cp modules/cron/config-templates/*.php config/
[root@simplesamlphp simplesamlphp] touch modules/metarefresh/enable
[root@simplesamlphp simplesamlphp] cp modules/metarefresh/config-templates/*.php config/

But `modules/metarefresh` doesn't exist anymore!

I want to raise two issues:
 * The upgrade / changelog documentation does not prepare users for this change. It _looks like_ the module is deactivated after the upgrade. (I didn't check, but since `modules/metarefresh/enable` doesn't exist, I'm assuming the module is disabled, since the docs still say it needs to exist.)
 * In fact, the documentation doesn't seem to explain at all how the new external module is supposed to work. Is enabling required at all? Should users `cp vendor/simplesamlphp/simplesamlphp-module-metarefresh/config-templates/config-metarefresh.php config/`?

Let me know if I can help by submitting issues for individual modules.

**Comment by tvdijen** [comment]
`modules/metarefresh/enable` has never been set by default.. You always had to enable the modules you want to use and that hasn't changed in any way between 1.17 and 1.18.

> However, changeset ec24be2 removes modules/metarefresh, and that diff is applied to existing repos.

Yes, the module has been moved to a separate repository, but it is still automatically installed if you do `composer install`..

> But modules/metarefresh doesn't exist anymore!

Sure it does, but only after running `composer install`.. That's when it's being pulled into the modules-directory. If this is not the case for you, then something funny happened during the upgrade..

**Comment by drjayvee** [comment]
I assumed that composer installs dependencies in `vendor` (except if [`vendor-dir`](https://getcomposer.org/doc/06-config.md#vendor-dir) is configured). Nor does simplesamlphp use [composer/installers or `extra/installer-paths`](https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md).

I still don't understand how some end up in `modules`. Could you please enlighten me?

I just ran all the steps again, and `modules/metarefresh/enable` did survive the upgrade from 1.17 to 1.18, so something weird did happen (in five different repos though).

**Comment by tvdijen** [comment]
We _are_ using composer installers;   https://github.com/simplesamlphp/composer-module-installer
