### ISSUE TITLE
Configuration for Nginx - fix

### ISSUE THREAD

**Issue by quenenni** [simplesamlphp/simplesamlphp#1338]
Hello,

Just tried the last 2 days to make simpleSaml works with Nginx, and it doen't work with the config showed the doc.

Finally got it working.

The error is a missing line (`fastcgi_param PATH_INFO $pathinfo if_not_empty;`) in the doc (https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_5) that can be seen in the ticket the config is taken from (https://github.com/simplesamlphp/simplesamlphp/issues/751#issuecomment-353614223)

Thanks for the app.
Very much appreciated.

[Edit: Forgot some details)]
It was on a fresh Debian Buster installation with just Nginx v1.14.2 and Simplesaml git cloned yesterday.

**Comment by tvdijen** [comment]
Thanks @quenenni !!

I'm a bit weary of merging this, because every now and then nginx issues pop up and they always seem to contradict one another.. I had at least 4 or 5 'fixes' and doc updates over the last couple of months..

**Comment by quenenni** [comment]
Totally understandable <br />
I didn't know it was so problematic with Nginx. I'm more used to Apache, but needed Nginx this time (tested also with Apache and all worked on first try).<br />
In the meantime, people will have this ticket to find / test a solution if they are in the same situation, so all is good.

**Comment by tvdijen** [comment]
Yes, I'm also used to Apache and so are my fellow devs.. Nginx always felt non-intuitive to me, but due to high demand, at some point I tried out an Nginx install to at least have some documentation..  I guess a year or two old.. It worked for me back then, but I get an issue regarding Nginx about every month..

**Comment by marcell-ferenc** [comment]
Hello,

I would like to share my nginx config and simlplesamlphp adventures with [Themosis framework](https://framework.themosis.com/) (a custom Wordpress stack) what just worked for me in the following environment:

- nginx version: **nginx/1.14.0** (Ubuntu)
- **PHP 7.4.8** (fpm-fcgi) (built: Jul 13 2020 16:45:47)
- **Ubuntu 18.04.3 LTS**

Basically I used the solution from _@niallfleming https://github.com/simplesamlphp/simplesamlphp/issues/751#issuecomment-393509612_.

Here is the server block that is currently working for my case, the real domain name replaced to `example.com` and I cut out irrelevant parts:

```
server {
    listen 80;
    server_name example.com;
    return 301 https://example.com$request_uri;
}

server {
    listen 443 ssl;

    root /var/www/example.com/htdocs;
    access_log off;
    error_log /var/log/nginx/example.com.error.log warn;

    index index.php index.html index.htm;

    server_name example.com;

    ssl_certificate /etc/nginx/certs/example.com.pem;
    ssl_certificate_key /etc/nginx/certs/example.com.key;

    location ^~ /simplesaml {
        alias /var/www/example.com/simplesaml/www;

        location ~ \.php(/|$) {
          fastcgi_split_path_info ^(.+?\.php)(/.+)$;
          fastcgi_param SCRIPT_FILENAME $request_filename;
          fastcgi_param PATH_INFO $fastcgi_path_info;
          fastcgi_pass unix:/run/php/php7.4-fpm-example.com.sock;
          fastcgi_index index.php;
          include fastcgi_params;
        }
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
    
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php/php7.4-fpm-example.com.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
  
}
```

The ungreedy regex really simplifies the nested php location inside `/simplesaml`, it reduces the need of named captures (`^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$  `) to build up SCRIPT_FILENAME variable.

May the following line causes contradiction from the [stable documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-install#section_5):

`fastcgi_param    SCRIPT_FILENAME $document_root$fastcgi_script_name;`

From [nginx tips](https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/#use-request-filename-for-script-filename):

> Use `$request_filename` instead of `$document_root$fastcgi_script_name`.
> 
> If you use the alias directive with `$document_root$fastcgi_script_name`, `$document_root$fastcgi_script_name` will return the wrong path.

I see this already corrected in the [development version](https://simplesamlphp.org/docs/development/simplesamlphp-install#section_6) using named captures and `fastcgi_param SCRIPT_FILENAME $document_root$phpfile;`.

**Comment by thijskh** [comment]
So I think what is in the development branch now https://simplesamlphp.org/docs/development/simplesamlphp-install#section_6 matches the solution stated above. We've ensured the same snippet will land in the stable documentation.

Given the positive experiences in this thread with that version of the docs I'm closing this now. But please _do_ let us know if we should improve on https://simplesamlphp.org/docs/development/simplesamlphp-install#section_6 even further.

**Comment by francescozanoni** [comment]
Hi,
I've found another issue with nginx example configuration:

- this `location ~ ^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {` does not populate named captures,
- while this `location ~^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {` does.

The difference is the blank space between `~` and `^`, which must not be added, according to [nginx documentation](http://nginx.org/en/docs/http/server_names.html#regex_names).

Here's my environment:

- nginx/1.16.1
- CentOS 7

Unfortunately I'm not sure whether this is related to a specific nginx version.
In case it is not, please please please update nginx examples! :-) For the sake of poor programmers' sanity...

Thanks in advance,

Francesco
