### ISSUE TITLE
Simple coding mistakes/bugs in ArtifactResolutionService.php

### ISSUE THREAD

**Issue by suvera** [simplesamlphp/simplesamlphp#1343]
This is a simple coding mistakes cause saml not working, surprised to see that nobody has reported it.

Version:  latest, 1.18*
## File: ArtifactResolutionService.php

**Coding Issue-1:**

```
// Following method return a "String".  so, type of $idpEntityId = STRING
$idpEntityId = $metadata->getMetaDataCurrentEntityID('saml20-idp-hosted');


// .... after few lines ...


// Following method expect a Object of type "\SAML2\XML\saml\Issuer"
$artifactResponse->setIssuer($idpEntityId);

```

**Coding Issue-2:**

```

// Following method returns Object of type "\SAML2\XML\saml\Issuer"
$issuer = $request->getIssuer();

// And following method expects $issuer to be "String"
$spMetadata = $metadata->getMetaDataConfig($issuer, 'saml20-sp-remote');
```

**Comment by jaimeperez** [comment]
Hi @suvera,

Both are indeed issues, although it makes full sense that they weren't reported yet, since very few people use the artifact resolution profile, and also these bugs are only happening when using version 4.x of the SAML2 library. We should fix them anyway to guarantee interoperability with both versions 3.x and 4.x.

**Comment by tvdijen** [comment]
Wasn't this already fixed? https://github.com/simplesamlphp/saml2/issues/229

**Comment by tvdijen** [comment]
Hi @suvera ! Are you able to test my PR?
I think if it works I can apply it cleanly to 1.19 as well

**Comment by suvera** [comment]
> Hi @suvera ! Are you able to test my PR?
> I think if it works I can apply it cleanly to 1.19 as well

@tvdijen , yes it worked !

**Comment by tvdijen** [comment]
The fix will be in the next bugfix release
