### ISSUE TITLE
Support ProviderName attribute

### ISSUE THREAD

**Issue by Lasering** [simplesamlphp/simplesamlphp#1346]
**Is your feature request related to a problem? Please describe.**
The SAML schema protocol specifies that the [AuthnRequest](https://github.com/simplesamlphp/simplesamlphp/blob/8727f0d73169aebf6a30b8e836ef4c28bfe14df9/schemas/saml-schema-protocol-2.0.xsd#L152) supports the[ ProviderName](https://github.com/simplesamlphp/simplesamlphp/blob/8727f0d73169aebf6a30b8e836ef4c28bfe14df9/schemas/saml-schema-protocol-2.0.xsd#L169) attribute. However the saml:SP configuration does not provide any way to set it.

**Describe the solution you'd like**
[saml:SP](https://simplesamlphp.org/docs/stable/saml:sp) should have an option named `ProviderName` that sets the ProviderName in the AuthnRequest for every SAML request emitted for that SP.

**Additional context**
I was able to implement a solution for it, but since I dont know the code base very well its probably in the wrong place.

In `modules/saml/lib/Auth/Source/SP.php` inside the method [`startSSO2`](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Auth/Source/SP.php#L453) I've added these lines:
```php
$providerName = $this->metadata->getString("ProviderName");
if ($providerName !== null) {
  $ar->setProviderName($providerName);
}
```

**Comment by tvdijen** [comment]
Hi @Lasering !  I think that's the right place to put it.. Would you mind creating a PR?
