### ISSUE TITLE
Support saml:Extensions inside Authsources.php

### ISSUE THREAD

**Issue by Lasering** [simplesamlphp/simplesamlphp#1347]
**Is your feature request related to a problem? Please describe.**
The documentation for [saml:SP](https://simplesamlphp.org/docs/stable/saml:sp) references the `saml:Extensions` parameter, however its use seems to be limited to the \SimpleSAML\Auth\Simple class. This makes using SAML extensions in a bridge (an IdP acting as an SP to another IdP) impossible.

**Describe the solution you'd like**
`saml:Extensions` should be supported for bridges.

**Additional context**
I was able to implement a solution for it, but since I dont know the code base very well its probably in the wrong place.

In `modules/saml/lib/Auth/Source/SP.php` inside the method [`startSSO2`](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Auth/Source/SP.php#L453) I've added these lines:
```php
$extensions = $this->metadata->getArray('saml:Extensions');
if ($extensions !== null) {
  $ar->setExtensions($extensions);
}
```

**Comment by tvdijen** [comment]
This one's a little harder, because we don't officially support bridging..
I guess it would work, but it should only be done if it's not already set in the state:
https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Auth/Source/SP.php#L599

**Comment by Lasering** [comment]
> This one's a little harder, because we don't officially support bridging..

You could fool me, the [Identity Provider QuickStart](https://simplesamlphp.org/docs/stable/simplesamlphp-idp) lists `saml:SP` in the authentication modules with the following description:
> Authenticate against a SAML IdP. Can be used for bridging.

Like this?
```php
if (isset($state['saml:Extensions'])) {
  $ar->setExtensions($state['saml:Extensions']);
} else if ($this->metadata->getArray('saml:Extensions') !== null) {
  $ar->setExtensions($this->metadata->getArray('saml:Extensions'));
}
```

**Comment by tvdijen** [comment]
> 
> 
> > This one's a little harder, because we don't officially support bridging..
> 
> You could fool me, the [Identity Provider QuickStart](https://simplesamlphp.org/docs/stable/simplesamlphp-idp) lists `saml:SP` in the authentication modules with the following description:
> 
> > Authenticate against a SAML IdP. Can be used for bridging.

That's protocol-bridging between i.e. Shibboleth <> SAML2..
What you call bridging is actually a SAML proxy..

> Like this?
> 
> ```
> if (isset($state['saml:Extensions'])) {
>   $ar->setExtensions($state['saml:Extensions']);
> } else if ($this->metadata->getArray('saml:Extensions') !== null) {
>   $ar->setExtensions($this->metadata->getArray('saml:Extensions'));
> }
> ```

I think that should work, yes.. Is your use-case still working if you do that?

**Comment by Lasering** [comment]
Ok, I calling it by the wrong name.


> I think that should work, yes.. Is your use-case still working if you do that?

Still works :) I can make a PR.

**Comment by Lasering** [comment]
@tvdijen I've made a PR

**Comment by tvdijen** [comment]
I know, but I want it to be reviewed because I'm not sure about the order

**Comment by Lasering** [comment]
After some more testing it does not solve my use case completely.

I have the following setup `Test SP` <=> `Proxy IDP` <=> `IDP A`, where the arrow means a trust relationship.

1. If `Test SP` defines extensions they are correctly sent to `IDP A`, the proxy does the right thing.
2. If `Test SP` does not define extensions but the SP inside the `Proxy IDP` does, then no extensions are sent to `IDP A`. I was expecting the extensions of the SP inside `Proxy IDP` to be sent.
3. If both `Test SP` and the SP inside `Proxy IDP` define extensions then the `Test SP` extensions are being sent, which is expected.

**Comment by tvdijen** [comment]
Try switching the order in the if-statements.. I think in that case, the proxy-SP-settings should prevail over the test-SP-settings..
Whether that's the right way to do is hard to say, as the concept of a 'proxy' is not described in the SAML standards at all..

**Comment by Lasering** [comment]
Right on the money. It worked! Do you want me to change the PR?

**Comment by tvdijen** [comment]
I’m actually not sure... I think it should be the way it is, except scenario 2 should work.. and scenario 3 is difficult, but I guess the Proxy SP should be able to override things sent by the Test IDP for maximum flexibility...

**Comment by Lasering** [comment]
After switching the order all scenarios are working correctly.
