### ISSUE TITLE
SimpleSAML Class Error

### ISSUE THREAD

**Issue by redolphn** [simplesamlphp/simplesamlphp#1356]
I just upgraded SimpleSAMLphp to the latest version via git and when I attempt a SAML login, I got the following error in the logs:

**SimpleSAML\Error\Exception: Error 1 - Attempted to load class "ServiceRouterLoader" from namespace "Symfony\Component\Routing\Loader\DependencyInjection" Did you forget a "use" statement for another namespace? at /tmp/simplesaml/cache/store/ContainerCvWnyPd/SimpleSAML_KernelProdContainer.php:199**

I followed all of the instructions for a git-based upgrade at the following location:
https://simplesamlphp.org/docs/stable/simplesamlphp-install-repo

Any ideas why or how this broke?  Thank you!

**Comment by tvdijen** [comment]
It's because you're using master, and running compose update... Master is currently broken, composer update may cause unexpected behaviour every day

**Comment by redolphn** [comment]
Thank you @tvdijen  If master is broken, which branch should I be using (to get the latest stable version)?  I was just following the documentation (at the link that I provided above).  Is there updated/corrected documentation?
