### ISSUE TITLE
Can't install with composer require simplesamlphp/simplesamlphp

### ISSUE THREAD

**Issue by adiatma85** [simplesamlphp/simplesamlphp#1372]
**Describe the bug**
When I install dependency in my laravel app with `composer require simplesamlphp/simplesamlphp`, it can not be installed.

**To Reproduce**
1. Open terminal in laravel app
2. Type `composer require simplesamlphp/simplesamlphp`
3. Waiting the loading to add new dependency
4. Error message that tell the dependency can not be installed

**Expected behavior**
After loading, the dependency is installed

**Screenshots or logs**
Error messages:
`
Can only install one of: symfony/event-dispatcher[v4.4.11, v5.1.3].
Installation request for symfony/event-dispatcher (locked at v5.1.3) -> satisfiable by symfony/event-dispatcher[v5.1.3].
`
Screenshots:
![Issue](https://user-images.githubusercontent.com/57523711/91381839-8421ee80-e852-11ea-86db-5a393e18f10b.PNG)

What should I do?
Thanks

**Comment by tvdijen** [comment]
Hi @adiatma85 ! You could try running our stable version instead of the development branch..
Try `composer require simplesamlphp/simplesamlphp:@stable`
