### ISSUE TITLE
Incorrect MODIFY syntax for SQLServer in LogoutStore.php

### ISSUE THREAD

**Issue by Krisell** [simplesamlphp/simplesamlphp#1379]
**Describe the bug**
The correct SQLServer syntax is 
```sql
ALTER TABLE table_name ALTER COLUMN column_name datatype;
```
but the current syntax (the default case) is
```sql
ALTER TABLE table_name MODIFY COLUMN column_name datatype;
```

This happens in the switch-statement in two places, and it looks like the `sqlsrv` could be handled in the same way as `pgsql`:
https://github.com/simplesamlphp/simplesamlphp/blob/3d7d094d01bdf5c2b02ddc3ad2016027e0bec2ea/modules/saml/lib/SP/LogoutStore.php#L39
https://github.com/simplesamlphp/simplesamlphp/blob/3d7d094d01bdf5c2b02ddc3ad2016027e0bec2ea/modules/saml/lib/SP/LogoutStore.php#L116

Documentation for the SQLServer syntax:
https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-table-transact-sql?view=sql-server-ver15

I have not been able to test or PR this, but might be able to so within a few weeks if no-one else beats me to it (please do).

**Comment by tvdijen** [comment]
I can do the change, but if you'd be so kind to test it for us then? I don't have MSSQL available for testing

**Comment by tvdijen** [comment]
This one probably needs the same change then;
https://github.com/simplesamlphp/simplesamlphp/blob/3d7d094d01bdf5c2b02ddc3ad2016027e0bec2ea/modules/saml/lib/SP/LogoutStore.php#L119

**Comment by Krisell** [comment]
Sounds great, and yes I should be able to test this.
If the change is to simply use the same syntax as `pgsql`, I can test this right away and send in a PR, but there might be other changes that have to be made that I'm not seeing?

**Comment by Krisell** [comment]
The`sqlsrv` syntax is not identical to `pgsql`, so I started to add a `sqlsrv` case to the switch statements. I was unable to try this though, as it turns out that the database user used in our application only has read/write-access, and not alter-access. I'm wondering if this is unusual or of the automatic table-migration might fail for more people (it only throws a warning and keeps using the old schema, but tries to migrate on every request).

I'm hoping to find the time to create a more consistent Docker-setup to test SQLServer. I'm guessing there are no automated tests against different database drivers in this project?

![image](https://user-images.githubusercontent.com/25909128/92950580-336ae200-f45d-11ea-8394-0fe3e36c554b.png)

**Comment by tvdijen** [comment]
Unfortunately there are no automated tests, no.. We are working on getting rid of some technical debt, but with limited resources.. One of our focusses is to raise coverage significantly and to start using proper database migrations and a database abstraction layer like the one from Symfony... We've started with our low-level saml2 library and some other mutual repo's, which are ~90% done and covered, and we should be able to work our way up to this one in the foreseeable future

**Comment by Krisell** [comment]
I reproduced the issue in Docker and could also verify that my changes fixes the issue. 
Here's the PR: https://github.com/simplesamlphp/simplesamlphp/pull/1380

**Comment by tvdijen** [comment]
Excellent @Krisell !!   I've been struggling so much with these different DBMS's, it's not fun anymore, but I'm glad you have tested this against MSSQL
