### ISSUE TITLE
Eliminate need for shipped jQuery UI 1.5

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/simplesamlphp#138]
simpleSAMLphp currently ships two versions of jQuery and jQuery UI under `www/resources/`; a set corresponding to jQuery UI 1.5 and one corresponding to 1.6.

All code now uses 1.6 except for `logout-iframe.php`. If `logout-iframe.php` could be updated for 1.6, the 1.5 files could be removed.

**Comment by jaimeperez** [comment]
Done.

At some point we should also get rid of the antediluvian 1.6 and update to the latest version. However, that's an entire different story in terms of work. I'd also like to take the chance to rewrite SSP's UI, so let's just postpone that until we get to work on the interface.
