### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by torrk2** [simplesamlphp/simplesamlphp#1384]
**Is your feature request related to a problem? Please describe.**
i was trying to update the password and this error came up.
**Describe the solution you'd like**
i want to be able to log in to my farmingdale account
**Describe alternatives you've considered**

**Additional context**

**Comment by jaimeperez** [comment]
Hi,

This project is not related in any way to Farmingdale. This is just a software project that they seem to be using. Please contact their user support.
