### ISSUE TITLE
MEMCACHEDOWN

### ISSUE THREAD

**Issue by ocimjr** [simplesamlphp/simplesamlphp#1385]
Hi, 

We are using a couchebase server that can be used as memcache serveur, when we are using with mahara we have this error :

[WAR] 7e (lib/errors.php:536) [SimpleSAML\Error\Error]: MEMCACHEDOWN at simplesamlphp/lib/SimpleSAML/Memcache.php:128

Edting this file at line 56 we have : 

`                // either the server is down, or we don't have the value stored on that server
                $mustUpdate = true;
                $up = $server->getStats();
                if ($up !== false) {
                    $allDown = false;
                }
                continue;`

GetStats returns empty for our case, but using getVersion we have an answer :

We modified to : 

`                // either the server is down, or we don't have the value stored on that server
                $mustUpdate = true;
                $up = $server->getStats();
                if ($up !== false || $server->getVersion() !== false) {
                    $allDown = false;
                }
                continue;`

And now simplesaml works normally

**Comment by tvdijen** [comment]
What version are you on? I think the Memcache class had significant changes and I can't find a recent release where that line number matches

**Comment by ocimjr** [comment]
I got from here https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Memcache.php

**Comment by tvdijen** [comment]
Ah, my bad.. I didn't see through the multiline code you put into one..
I know for a fact that getStats() is exactly the place we memcache and memcache**d** differ.. So that's probably the catch

**Comment by tvdijen** [comment]
@ocimjr I'm starting to think you have installed the wrong PHP-extension.. Can you paste the info from phpinfo() regarding the memcache(d) extension?

**Comment by ocimjr** [comment]
Yes no problem.


![Capture d’écran, le 2020-10-27 à 13 31 23](https://user-images.githubusercontent.com/37626833/97339291-c8346e00-1858-11eb-85a8-f30ef9156296.png)

Also, I'd like to note that we have a couchbase server that we use as memcached.

**Comment by tvdijen** [comment]
OK, that's just fine.. Same as mine.. But why on earth would the `getStats()` return false?

I'm quite sure it's couchebase returning `false` or an empty array on the `getStats` call.. Not sure why, but it's probably not something I can fix..
I could go with your proposed fix and it would probably help, but what other 'memcache'-like backend would break on that? It's probably not a long-term solution

**Comment by ocimjr** [comment]
Yeah, i understand. We had this problem also with mahara project https://bugs.launchpad.net/mahara/+bug/1814316
For your question answer is `bool(false)`

**Comment by tvdijen** [comment]
Right, so the only way to end with with `false` is in this case;
https://github.com/php-memcached-dev/php-memcached/blob/master/php_memcached.c#L2809
Meaning that the pecl memcached-extension thinks the memcache-server is unreachable.. Since you say that everything else is working just fine, this is probably a bug in the memcached-extension..  I suggest you file a bug there

**Comment by tvdijen** [comment]
I see you haven't filed a bug and since this is nothing we can fix, I'm closing the issue.
