### ISSUE TITLE
Simplesaml KO mysql SSL Connection

### ISSUE THREAD

**Issue by quadrinho** [simplesamlphp/simplesamlphp#1386]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
I'm trying to connect mysimplesamlphp  to Azure SSL Mysql but on the logs we recieve this error:

[06-Oct-2020 18:04:02 Europe/Amsterdam] PHP Fatal error:  Uncaught Exception: Database error: SQLSTATE[HY000] [2002]  in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php:64
Stack trace:
#0 /data/simplesamlphp_multitenant/lib/SimpleSAML/Store.php(49): SimpleSAML\Store\SQL->__construct()
#1 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(132): SimpleSAML\Store::getInstance()
#2 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(41): SimpleSAML\SessionHandler::createSessionHandler()
#3 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(161): SimpleSAML\SessionHandler::getSessionHandler()
#4 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(424): SimpleSAML\Session->__construct(true)
#5 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(277): SimpleSAML\Session::useTransientSession()
#6 /data/simplesamlphp_multitenant/lib/SimpleSAML/Error/Error.php(180): SimpleSAML\Session::getSessionFromRequest()
#7 /data/simplesamlphp_multitenant/lib/SimpleSAML/Error/Error.php(219): SimpleSAML\Error\Error->saveError in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php on line 64
[06-Oct-2020 18:04:02 Europe/Amsterdam] PHP Fatal error:  Uncaught Exception: Database error: SQLSTATE[HY000] [2002]  in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php:64
Stack trace:
#0 /data/simplesamlphp_multitenant/lib/SimpleSAML/Store.php(49): SimpleSAML\Store\SQL->__construct()
#1 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(132): SimpleSAML\Store::getInstance()
#2 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(41): SimpleSAML\SessionHandler::createSessionHandler()
#3 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(161): SimpleSAML\SessionHandler::getSessionHandler()
#4 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(424): SimpleSAML\Session->__construct(true)
#5 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(277): SimpleSAML\Session::useTransientSession()
#6 /data/simplesamlphp_multitenant/lib/SimpleSAML/Logger.php(288): SimpleSAML\Session::getSessionFromRequest()
#7 [internal function]: SimpleSAML\Logger::shutdown()
#8 {main}
  thrown in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php on line 64[06-Oct-2020 18:04:02 Europe/Amsterdam] PHP Fatal error:  Uncaught Exception: Database error: SQLSTATE[HY000] [2002]  in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php:64
Stack trace:
#0 /data/simplesamlphp_multitenant/lib/SimpleSAML/Store.php(49): SimpleSAML\Store\SQL->__construct()
#1 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(132): SimpleSAML\Store::getInstance()
#2 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(41): SimpleSAML\SessionHandler::createSessionHandler()
#3 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(161): SimpleSAML\SessionHandler::getSessionHandler()
#4 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(424): SimpleSAML\Session->__construct(true)
#5 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(277): SimpleSAML\Session::useTransientSession()
#6 /data/simplesamlphp_multitenant/lib/SimpleSAML/Error/Error.php(180): SimpleSAML\Session::getSessionFromRequest()
#7 /data/simplesamlphp_multitenant/lib/SimpleSAML/Error/Error.php(219): SimpleSAML\Error\Error->saveError in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php on line 64
[06-Oct-2020 18:04:02 Europe/Amsterdam] PHP Fatal error:  Uncaught Exception: Database error: SQLSTATE[HY000] [2002]  in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php:64
Stack trace:
#0 /data/simplesamlphp_multitenant/lib/SimpleSAML/Store.php(49): SimpleSAML\Store\SQL->__construct()
#1 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(132): SimpleSAML\Store::getInstance()
#2 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(41): SimpleSAML\SessionHandler::createSessionHandler()
#3 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(161): SimpleSAML\SessionHandler::getSessionHandler()
#4 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(424): SimpleSAML\Session->__construct(true)
#5 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(277): SimpleSAML\Session::useTransientSession()
#6 /data/simplesamlphp_multitenant/lib/SimpleSAML/Logger.php(288): SimpleSAML\Session::getSessionFromRequest()
#7 [internal function]: SimpleSAML\Logger::shutdown()
#8 {main}
  thrown in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php on line 64

Can anyone help me?

**To Reproduce**
this is the configuration that we used:

        'store.type' => 'sql',
        'store.sql.dsn' => 'mysql:host=db.aip.accenture.local;dbname=simplesamlmulti',
        'store.sql.username' => 'xxxxx@safeworkerdb',
        'store.sql.password' => 'xxxxxx',
        'store.sql.prefix' => '',
        'store.sql.options' => array(\PDO::MYSQL_ATTR_SSL_CA => '/data/ca_db_drupal/db_azure_ca.crt',), 

**Expected behavior**

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.

**Additional context**

**Comment by tvdijen** [comment]
You simple have a connectivity error... Try adding the port to the dsn, because I know with Azure it's not always the default 3306..
If that didn't help you, we can't help you here with your specific use case.. please refer to the [mailing list](http://groups.google.com/group/simplesamlphp)..

**Comment by quadrinho** [comment]
Hello tvdijen,

before enabling SSL, i can connect to Azure MYSQL Database. Now i try to change the configuration in this way:

        'store.type' => 'sql',
        'store.sql.dsn' => 'mysql:host=db.aip.accenture.local;dbname=simplesamlmulti',
        'store.sql.username' => 'xxxxx',
        'store.sql.password' => 'xxxx',
        'store.sql.prefix' => '',
        'store.sql.options' => array(
            array(
                array(\PDO::MYSQL_ATTR_SSL_CA => '/data/ca_db_drupal/db_azure_ca.crt'),
                array(\PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false),
            ),
        ),

but now i receive this error:


[06-Oct-2020 18:39:38 Europe/Amsterdam] PHP Fatal error:  Uncaught Exception: Database error: SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry. in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php:64
Stack trace:
#0 /data/simplesamlphp_multitenant/lib/SimpleSAML/Store.php(49): SimpleSAML\Store\SQL->__construct()
#1 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(132): SimpleSAML\Store::getInstance()
#2 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(41): SimpleSAML\SessionHandler::createSessionHandler()
#3 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(161): SimpleSAML\SessionHandler::getSessionHandler()
#4 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(424): SimpleSAML\Session->__construct(true)
#5 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(277): SimpleSAML\Session::useTransientSession()
#6 /data/simplesamlphp_multitenant/lib/SimpleSAML/Error/Error.php(180): SimpleSAML\Session::getSessionFromRequest()
#7 /data/simplesamlphp_multitenant/lib/S in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php on line 64
[06-Oct-2020 18:39:38 Europe/Amsterdam] PHP Fatal error:  Uncaught Exception: Database error: SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry. in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php:64
Stack trace:
#0 /data/simplesamlphp_multitenant/lib/SimpleSAML/Store.php(49): SimpleSAML\Store\SQL->__construct()
#1 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(132): SimpleSAML\Store::getInstance()
#2 /data/simplesamlphp_multitenant/lib/SimpleSAML/SessionHandler.php(41): SimpleSAML\SessionHandler::createSessionHandler()
#3 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(161): SimpleSAML\SessionHandler::getSessionHandler()
#4 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(424): SimpleSAML\Session->__construct(true)
#5 /data/simplesamlphp_multitenant/lib/SimpleSAML/Session.php(277): SimpleSAML\Session::useTransientSession()
#6 /data/simplesamlphp_multitenant/lib/SimpleSAML/Logger.php(288): SimpleSAML\Session::getSessionFromRequest()
#7 [internal function]: SimpleSAML\Logger::sh in /data/simplesamlphp_multitenant/lib/SimpleSAML/Store/SQL.php on line 64

I have open also a conversiation on mailing list.

Can you help me?

**Comment by tvdijen** [comment]
I can't.. I know shit about Azure...
Google may help;  https://stackoverflow.com/questions/51928543/php-azure-db-connection-error-hy000-9002

**Comment by tvdijen** [comment]
You probably need to specify a client certificate in the options..
```
PDO::MYSQL_ATTR_SSL_KEY =>'/path/to/client-key.pem',
PDO::MYSQL_ATTR_SSL_CERT=>'/path/to/client-cert.pem'
```
I hope the mailing list can help you

**Comment by quadrinho** [comment]
I have solved the issue during this night, the right configuration is:

'store.sql.options' => array(\PDO::MYSQL_ATTR_SSL_CA => 'FULL_PATH_TO_CA', \PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false),

**Comment by tvdijen** [comment]
Disabling certificate verification is hardly 'the right configuration'..
