### ISSUE TITLE
Unregistered redirect_uri when deployed to nginx.ingress.kubernetes

### ISSUE THREAD

**Issue by hpyjoy** [simplesamlphp/simplesamlphp#1391]
I am having issues getting the sso to work.  I am not sure if it is related to when I access the url:  https:/..../simplesaml/saml2/.... to validate the configuration I get "Unregistered redirect_uri".  I do not receive this error if I type a complete url path, example: /simplesaml/saml2/idp/metadata.php?output=xhtml.  If I click on any of the navigation on this page, I receive the "Unregistered redirect_uri" error. 

Bad Request
Unregistered redirect_uri ("https://.../oauth2/callback").

**Comment by tvdijen** [comment]
This is not a support forum
