### ISSUE TITLE
entity_data field size is insufficient with PDO metadata storage

### ISSUE THREAD

**Issue by aaronhark** [simplesamlphp/simplesamlphp#1392]
**Describe the bug**
When initializing a PDO-based metadata store, the `entity_data` column is set as type `TEXT`  (refer to line 291 of `MetaDataStorageHandlerPdo.php`). Under MySQL, the `TEXT` column type is limited to 65,535 characters and is insufficient. Many metadata sets, specifically those from ADFS, regularly exceed 90,000 characters in length. As a result, these are truncated without warning when loaded to the database as encoded json, and throw a json_decode error when they are retrieved.

**To Reproduce**
1. Set `config.php` to use a PDO metadata store.
2. Add the following two example metadata source URLs to your `saml20-idp-remote` set, either manually or with the metarefresh module:
https://login.microsoftonline.com/95e25911-16d0-49ca-9f95-114e82264bd7/federationmetadata/2007-06/federationmetadata.xml  (will work fine)
https://adfederation1.cookman.edu/FederationMetadata/2007-06/FederationMetadata.xml  (metadata is too long)
3. Run `bin/initMDSPdo.php` to set up the PDO metadata storage.
4. Run `bin/importPdoMetadata.php` to read the flatfiles that metarefresh produced and import these two entries to the database.
5. Log into the SimpleSAMLphp admin panel, and click on the "Federation" tab. An error will be thrown as it attempts to decode the JSON of that second metadata entry.

**Solution**
At least for MySQL, `lib\SimpleSAML\Metadata\MetaDataStorageHandlerPdo.php` should be adjusted at line 290-293 from:
```
$rows = $this->db->write(
                "CREATE TABLE IF NOT EXISTS $tableName (entity_id VARCHAR(255) PRIMARY KEY NOT NULL, entity_data ".
                "TEXT NOT NULL)"
            );
```
to read:
```
$rows = $this->db->write(
                "CREATE TABLE IF NOT EXISTS $tableName (entity_id VARCHAR(255) PRIMARY KEY NOT NULL, entity_data ".
                "MEDIUMTEXT NOT NULL)"
            );
```

**Comment by tvdijen** [comment]
The fix is easy enough, but we have to make sure things keep working no MSSQL, SQLlite and PostgreSQL as well..

**Comment by tvdijen** [comment]
Investigation:
- SQLite: TEXT (practical 31 bit limit)
- MySQL: MEDIUMTEXT (24 bits limit)
- MSSQL: TEXT (32 bits limit)
- PostGreSQL:  TEXT (size doesn't matter)

Conclusion:
Only change to MEDIUMTEXT for MySQL as an exception

**Comment by thijskh** [comment]
Use `$db->getAttribute(PDO::ATTR_DRIVER_NAME);` to get the current driver?

In any case I don't think it's blocking for 2.0 since the issue also affects 1.19.

**Comment by tvdijen** [comment]
@thijskh `$this->db` is pointing to `\SimpleSAML\Database` and not to the PDO handler, so it cannot be done right now.

**Comment by thijskh** [comment]
Yes, a pragmatic solution without too much overhead.

**Comment by tvdijen** [comment]
@aaronhark I don't have MySQL available to test this patch.. Could you help us test it?
