### ISSUE TITLE
1.19.0-rc1 doesn't work on php7.0

### ISSUE THREAD

**Issue by mrvanes** [simplesamlphp/simplesamlphp#1393]
1.19.0-rc1 introduces nullable return type Throwable (if I understand the syntax correct) and my Debian Stretch 7.0 spits out an error while parsing lib/SimpleSAML/Error/Exception.php on line 130, which reads:
```
public function getCause(): ?Throwable
```
PHP Changelog refers this construct to be introduced in 7.1:
https://www.php.net/manual/en/migration71.new-features.php

I think the goal for 1.19 was minimum 7.0?

**Comment by tvdijen** [comment]
No, Martin! As you can read from the [composer.json](https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.19/composer.json) and the [upgrade notes](https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-1.19/docs/simplesamlphp-upgrade-notes-1.19.md), the goal was set to PHP >=7.1!

**Comment by mrvanes** [comment]
So this is stale information?
https://github.com/simplesamlphp/simplesamlphp/pull/1242

Anyway, can be closed by not paying attention by submitter

**Comment by tvdijen** [comment]
Yes, that's old..
Symfony v3 is EOL and doesn't receive any security updates anymore, so we had to make the move.. Symfony v4 requires PHP 7.1

**Comment by thijskh** [comment]
The config check should indicate this correctly btw

**Comment by tvdijen** [comment]
I've tripple checked and it does

**Comment by mrvanes** [comment]
I download tar and point apache to webroot... that's a whole different cookie

**Comment by mrvanes** [comment]
I got a 500 and a syntax error in Apache error log
