### ISSUE TITLE
Language cookie cannot be set if domain value isn't specified

### ISSUE THREAD

**Issue by christof-b** [simplesamlphp/simplesamlphp#1395]
**Description**
Currently the Language class falls back to _NULL_ for the domain value of the cookie.
As _NULL_ isn't allowed as parameter in \setcookie() an error occures:

Fatal error: Uncaught TypeError: setcookie() expects parameter 5 to be string, null given in /lib/SimpleSAML/Utils/HTTP.php:1260 
Stack trace:
#0/lib/SimpleSAML/Utils/HTTP.php(1260): setcookie('language', 'de', 1682345457, '/', NULL, false, false)
#1 /lib/SimpleSAML/Locale/Language.php(433): SimpleSAML\Utils\HTTP::setCookie('language', 'de', Array, false)
#2 /lib/SimpleSAML/Locale/Language.php(212): SimpleSAML\Locale\Language::setLanguageCookie('de')
#3 /lib/SimpleSAML/Locale/Language.php(157): SimpleSAML\Locale\Language-&gt;setLanguage('de', true)
#4 //lib/SimpleSAM in lib/SimpleSAML/Utils/HTTP.php on line 1260

**To Reproduce**
Seen in v1.18.8 and 1.19.0-rc1

1. Use default configuration for language cookie
2. Go to admin page
3. Select any language besides the current one

**Expected behavior**
An empty value should be treated as an empty string.

Compare to /lib/SimpleSAML/SessionHandler.php Line 161 were the value is explicitly parsed as string.
So my suggestion ist to change to the same behavior for /lib/SimpleSAML/Locale/Language.php Line 426

`'domain'   => strval($config->getString('language.cookie.domain', null)),`

**Comment by tvdijen** [comment]
Fixed in https://github.com/simplesamlphp/simplesamlphp/commit/4a928334db9070e4c0a69b30f157bb4c85083798 for 1.19
I can't explain the issue in 1.18.8 because we didn't use `strict types` there yet, so the `null` should just be casted to the empty string

**Comment by tvdijen** [comment]
@christof-b This should be fixed in v1.19.0... I'm not sure if this still exists in 1.18, but we're not going to fix that one anymore now that 1.19 is the new stable!
