### ISSUE TITLE
Remove support for deprecated dictionary format (was #274)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#14]
_From [andreass...@gmail.com](https://code.google.com/u/102889613336421617108/) on January 26, 2010 12:45:07_

Remove support for deprecated dictionary format

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=274_

**Comment by thijskh** [comment]
What does this mean?

**Comment by jaimeperez** [comment]
Can't recall any longer. Maybe @olavmrk remembers?

**Comment by thijskh** [comment]
If we don't know what this is I say we remove it from the 2.0 milestone or close it outright.

**Comment by jaimeperez** [comment]
I'd assume it was related to the translation system, in which case, the old system is going to die entirely for 2.0 (and that makes sense since I tagged this issue for that version) so we can just close this.
