### ISSUE TITLE
Symfony 5 support in 1.19 is gone

### ISSUE THREAD

**Issue by htto** [simplesamlphp/simplesamlphp#1401]
**Describe the bug**
Branch 1.19 used to have working symfony 5 support via 575dacf850454876ae4b51dd1705264c74ad8de7 but it got (most likely accidentally) removed with d5081ec2984bed5b4fb58c8a3a493564c0fb93cb.

**To Reproduce**
1. Have an symfony 5 app tracking SSP 1.19
2. composer up
3. `simplesamlphp/simplesamlphp dev-simplesamlphp-1.19 requires symfony/cache ^4.4 -> no matching package found.`

**Additional context**
SF5 support added in https://github.com/simplesamlphp/simplesamlphp/commit/575dacf850454876ae4b51dd1705264c74ad8de7
SF5 support removed in https://github.com/simplesamlphp/simplesamlphp/commit/d5081ec2984bed5b4fb58c8a3a493564c0fb93cb

**Comment by tvdijen** [comment]
I think you're right.. Thanks!
