### ISSUE TITLE
Ubuntu installation

### ISSUE THREAD

**Issue by philiprbrenan** [simplesamlphp/simplesamlphp#1404]
After installing on Apache/Ubuntu 20 I get: 

`"GET /simplesaml HTTP/1.1" 404 495 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0".  
`
Please tell me how to fix this?

My Configuration:

```
-rw-r--r-- 1 root root 365 Nov 27 21:25 /etc/apache2/sites-available/www.appaapps.com.conf

 <VirtualHost *>
         ServerName www.appaapps.com
         DocumentRoot /var/www/www.appaapps.com

         SetEnv SIMPLESAMLPHP_CONFIG_DIR /var/simplesamlphp/config

         Alias /simplesaml /var/simplesamlphp/www

         <Directory /var/simplesamlphp/www/>
             Require all granted
         </Directory>
 </VirtualHost>

tree /var/www
/var/www
├── html
│   └── index.html
└── www.appaapps.com
    └── public_html

drwxrwxrwx  3 www-data www-data 4096 Nov 27 20:31 www.appaapps.com

drwxrwxrwx 22 www-data www-data 4096 Nov 27 20:21 /var/simplesamlphp/

"GET /simplesaml HTTP/1.1" 404 495 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"


```

**Comment by tvdijen** [comment]
What happens if you specifically access `/simplesaml/index.php` ?

**Comment by philiprbrenan** [comment]
Thank you!  The same response: 

ls: cannot access '/var/simplesamlphp/index.php': No such file or directory

"GET /simplesaml/index.php HTTP/1.1" 404 495 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:83.0) Gecko/20100101 Firefox/83.0"

**Comment by tvdijen** [comment]
OK, it was a wild guess, but obviously something is wrong with the Apache config..  Seems like your request is being handled by another vhost.. You have more than just this one?

**Comment by philiprbrenan** [comment]
ls -la sites-enabled/
total 8
drwxr-xr-x 2 root root 4096 Nov 27 22:36 .
drwxr-xr-x 8 root root 4096 Nov 27 17:53 ..
lrwxrwxrwx 1 root root   40 Nov 27 21:00 www.appaapps.com.conf -> ../sites-available/www.appaapps.com.conf

**Comment by tvdijen** [comment]
Sorry, we can't help you with your webserver config.. This isn't a support forum in the first place..
