### ISSUE TITLE
Action to install on Ubuntu

### ISSUE THREAD

**Issue by philiprbrenan** [simplesamlphp/simplesamlphp#1405]
Please consider creating a github action that demonstrates the steps needed to successfully install simplesamlphp on a Ubuntu 20 server? I could contribute an outline of such an action if helpful?

**Comment by tvdijen** [comment]
Using Actions for this makes zero sense to me... You just unpack the tarball and follow the installation notes?

**Comment by philiprbrenan** [comment]
I wish it were that simple!  The great things about actions is that the exact install sequence is made visible.  Written instructions leave too much leeway for things to go wrong....

**Comment by tvdijen** [comment]
But your issues have nothing to do with SimpleSAMLphp.. It's webserver configuration and that really depends on someone's OS, webserver software and deployment..

**Comment by philiprbrenan** [comment]
All true - but never the less part of the installation - I followed the documentation closely - but found myself unable to discover the reason for the failure.  With an action one might be able to start apache and then curl to the local host to check that everything works as expected.Every installation procedure, should, IMO,  provide an automated acceptance test.

**Comment by tvdijen** [comment]
I'm sorry, I don't agree with you that it's part of the installation... We do have such a unit test in place, but it's webserver independent..  Even Apache config is completely different over several Linux distributions, so it's impossible to provide examples for all of them..

**Comment by tvdijen** [comment]
I've discussed this with fellow developers and it still doesn't make any sense to use.
Perhaps this repo can help you;  https://github.com/simplesamlphp/docker-simplesamlphp
