### ISSUE TITLE
State information lost in postredirect.php due to SameSite=LAX

### ISSUE THREAD

**Issue by thegreatanon** [simplesamlphp/simplesamlphp#1411]
**Describe the bug**
When setting `SameSite=Lax` for the session cookie, on successful return from the IdP (which performs a POST), no cookie is sent
This causes state to be lost. 

In one of our applications the path to the code calling simplesamlphp can be reached through a GET, and when we encounter `$as->requireAuth()` the second time, the login information is recovered.

In other application the simplesamlphp login code can only be reached using a POST with specific parameters, hence we need the `postredirect.php` functionality of simplesamlphp. Because no cookies are sent (due to `SameSite=Lax`), the saved POST data cannot be retrieved resulting in a hard exception. 

**To Reproduce**
1. implement the simplesamlphp login using a POST-able page
2. set SameSite=Lax 
3. attempt to login
4. the following error occurs:

```
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
1 www/_include.php:45 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: The POST data we should restore was lost.
Backtrace:
1 modules/core/www/postredirect.php:38 (require)
0 www/module.php:135 (N/A)
```

**Expected behavior**
Error would not occur, and the login would work as expected

**Additional context**
I understand this could constitute a 'wrong configuration' scenario. If this is the case, you might consider adding this to the https://simplesamlphp.org/docs/stable/simplesamlphp-nostate page as a potential cause.

Additionally, since the SameSite=Lax property is (or at least can be) defined in the internal config, you could theoretically know this issue will occur when loading the postredirect.php page. 

Instead of starting a fresh session (overwriting the old) at that point, you could trigger a page refresh. Since the origin would then be same-site, the existing cookies set as Lax or Strict would then be available.

**Comment by thijskh** [comment]
Indeed, in these cases you need to set the SameSite cookie to `None` in the `session.cookie.samesite` config parameter. It's a good suggestion to add this to the nostate documentation. I've done that now. Thanks!
