### ISSUE TITLE
If auth.adminpassword contains a hash, the hash itself can be used to login.

### ISSUE THREAD

**Issue by goozak** [simplesamlphp/simplesamlphp#1418]
Not sure if this is an actual bug or a misunderstanding on my part as to why someone would hash the password in the `config.php` file...

**Describe the bug**
If a hashed password is used in the `auth.adminpassword` value in  `config.php`, both the original password and the hash itself can be used to login.

**To Reproduce**
1. Generate a password hash with `"bin/pwgen.php"`.
For exemple, `password` is hashed as `$2y$10$ozHG4CXjZ07mN4uIu4g7NeLvmE257oi6L/DX3IbaJVR5Xay/L4iAC`.
2. Enter this hash as the value for `auth.adminpassword` in the `\config\config.php` file.
3. Also set the `admin.protectindexpage` value to `true`.
4. Go to the SimpleSAMLphp installation page.
5. You can log in with either the original password (`password`, as expected) or the hash itself (`$2y$10$ozHG4CXjZ07mN4uIu4g7NeLvmE257oi6L/DX3IbaJVR5Xay/L4iAC`).

**Expected behavior**
The hashed string itself should not allow access.
As it is, there is no difference in putting the plain text password or the hash in the `config.php` file.

**Comment by tvdijen** [comment]
This is a side-effect of having old-style & new-style admin passwords live together..
I could try and prevent this by refusing passwords starting with `$2y$`, but I'm not sure if that would cover every case.  This should no longer be possible in the new 2.0 version

**Comment by thijskh** [comment]
Indeed, it's because of the overloading of the parameter. SimpleSAMLphp cannot know if you intend the string in that field to be your actual password or a hash of it, and I see no feasible attempt for heuristically determining it. I think it's an oversight in the original design of this change, but any fix would break BC, so I think it's fine to accept that this will be/has been fixed in 2.0.

**Comment by goozak** [comment]
This 'issue' is also present in the new UI (with `usenewui`) in 1.18.

From the `master` branch here, which I _think_ contains the 2.0 code:
https://github.com/simplesamlphp/simplesamlphp/blob/f548aba16b14fb806cc402bae990393d6a8da0d7/lib/SimpleSAML/Utils/Crypto.php#L357-L363

**Comment by thijskh** [comment]
I think it can also be fixed in the older branches. See PR #1419.
