### ISSUE TITLE
SAML2INT: add support for errorURL

### ISSUE THREAD

**Issue by ghalse** [simplesamlphp/simplesamlphp#1425]
**Is your feature request related to a problem? Please describe.**

SAML2INT V2.0 now [requires the inclusion of an errorURL](https://kantarainitiative.github.io/SAMLprofiles/saml2int.html#_metadata_and_trust_management) in identity provider metadata:

> [SDP-MD12]
> An IdP’s metadata MUST include the errorURL attribute on its <md:IDPSSODescriptor> element. The content of the errorURL attribute MUST be an https URL resolving to an HTML page. 

So far as I can tell, SSP has no support for including an errorURL in metadata or processing one that exists in consumed metadata.

**Describe the solution you'd like**

1) SSP acting as an identity provider should be able to include an errorURL in metadata

2) SSP acting as a service provider should be able to process an errorURL from metadata, and display error messages that provide appropriate links.

**Additional context**

The REFEDS [Best Practice around Error Handling](https://wiki.refeds.org/display/GROUPS/Best+Practice+around+Error+Handling) working group has made some recommendations for URL substitutions that should be supported in the error URL.

As an enhancement to 1) it would be nice if a module existed that could act as an endpoint for the errorURL, and that could provide a set of pre-built error messages in line with the best practices. This would make it much easier for IdPs to set up their own errorURL solutions.

**Comment by ghalse** [comment]
That's even better than my suggestion :) But strictly SAML2INT only requires the inclusion of the metadata element; it is a REFEDS best practice to have specific error messages at that location (not that that is is bad thing!)

**Comment by tvdijen** [comment]
I understand, but if we are required to include the errorUrl, it should also be a valid existing endpoint and not some dummy url.. Might as well implement the REFEDS best practise on an actual endpoint then, right?

**Comment by pradtke** [comment]
@ghalse I am also interested in adding this support into SSP.  Have you done any code changes in the area? If not that I can start looking in to what codes changes are needed and where. Our initial interest is primarily on the IdP side, so that is what we would focus an initial PR on.

**Comment by ghalse** [comment]
@pradtke I opened the issue as a placeholder so it didn't get forgotten. However, I've not had a chance to look at it in any detail yet. If you've got the time, please go ahead.
