### ISSUE TITLE
Restore support for Composer 1.8

### ISSUE THREAD

**Issue by imrejonk** [simplesamlphp/simplesamlphp#1427]
**Is your feature request related to a problem? Please describe.**
I'm running Debian 10, which comes with Composer 1.8. Unfortunately SSP 1.19 seems to have dropped support for Composer 1.8 and now I can't upgrade from 1.18.

**Describe the solution you'd like**
If feasible, I would like to have support for Composer 1.8 again in SSP 1.19 so that Debian 10 users can use it to install modules from Packagist.

**Describe alternatives you've considered**
I'm looking into backporting the composer package from Debian Testing. This package is currently at version 2.0.

**Additional context**
This is the exception trace when running Debian 10's Composer (1.8.4-1) in SSP 1.19:
```
Exception trace:
 () at /usr/share/php/Composer/Package/Loader/ArrayLoader.php:44
 Composer\Package\Loader\ArrayLoader->load() at /usr/share/php/Composer/Repository/FilesystemRepository.php:63
 Composer\Repository\FilesystemRepository->initialize() at /usr/share/php/Composer/Repository/ArrayRepository.php:185
 Composer\Repository\ArrayRepository->getPackages() at /usr/share/php/Composer/Plugin/PluginManager.php:256
 Composer\Plugin\PluginManager->loadRepository() at /usr/share/php/Composer/Plugin/PluginManager.php:76
 Composer\Plugin\PluginManager->loadInstalledPlugins() at /usr/share/php/Composer/Factory.php:384
 Composer\Factory->createComposer() at /usr/share/php/Composer/Factory.php:576
 Composer\Factory::create() at /usr/share/php/Composer/Console/Application.php:345
 Composer\Console\Application->getComposer() at /usr/share/php/Composer/Console/Application.php:458
 Composer\Console\Application->getPluginCommands() at /usr/share/php/Composer/Console/Application.php:156
 Composer\Console\Application->doRun() at /usr/share/php/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /usr/share/php/Composer/Console/Application.php:104
 Composer\Console\Application->run() at /usr/bin/composer:57
```

**Comment by tvdijen** [comment]
I'm having a hard time understanding what you mean with 'Debian 10 comes with Symfony 3.4'....    Symfony is part of the SSP package and should not be related to the OS you're using

**Comment by imrejonk** [comment]
Right, I suspected that Symfony was the culprit after reading [this comment](https://github.com/simplesamlphp/simplesamlphp-module-webauthn/issues/34#issuecomment-769208310) and the entry in SSP 1.19.0's release notes. But as you say, Symfony is part of the SSP package. I guess I would like to have support for Composer 1.8 restored :)

Would that be possible? I'm looking into backporting Composer right now, but it's unfortunately not straightforward.

**Comment by tvdijen** [comment]
But why? Composer is literally just one php-file.....
Also, with just half of an exception and not even an error message, there's not much I can do to investigate this..

**Comment by tvdijen** [comment]
Just tried php 7.3, composer 1.8.4 and SSP 1.19 and it installed just fine...  Really not sure what the problem is, but it really is something local

**Comment by tvdijen** [comment]
How are you installing SSP 1.19?  Looking at the stack trace and the location where it breaks, gives me the impression that you've somehow corrupted the composer.json file;   see [this](https://github.com/composer/composer/blob/1.8.4/src/Composer/Package/Loader/ArrayLoader.php#L44)

**Comment by imrejonk** [comment]
SSP 1.19 indeed installs fine with Composer 1.8.4, but using Composer 1.8.4 inside a SSP 1.19 installation (as downloaded from [simplesamlphp.org](https://simplesamlphp.org/download)) results in the aforementioned exception. I've pasted the full `composer -vvv` output [here](https://gist.github.com/imrejonk/07e29358c00578386783621c2f08d8ef).

As for 'But why?', it's because of backwards compatibility. We are using Composer 1.8 in production and would like to use that until the next Debian Stable release. It might be trivial to maintain compatibility with Composer 1.8, it could be as simple as a syntax change in composer.json or something (but not necessarily, my Composer knowledge is limited).

**Comment by imrejonk** [comment]
To clarify: our production environment installs SSP from the release tarball, then installs the webauthn module with Composer 1.8. You can find the Ansible role that we're using for this [here](https://gitlab.com/ciphermail/debops.simplesamlphp).

**Comment by tvdijen** [comment]
NOW we're getting somewhere... It's something in the tarball that's borked..
You should do something about your logging, because the actual error message is _way_ more than the part you  gave us earlier

**Comment by tvdijen** [comment]
OK, so I've figured it out!  It's a bug in composer that was fixed in v1.8.5.. I could reproduce your issue and verify it breaks with v1.8.4 and works with v1.8.5...
It has something to do with parsing the composer lock-file...  Good luck trying to find out what triggers it.. I really don't think we can help you..  It would mean we have to roll back all our dependencies to the way they were in 1.18.8 and that's really not going to happen with all the known upstream vulnerabilities..

**Comment by imrejonk** [comment]
Thanks for diving into this! If it works with 1.8.5, then there is a bug in Debian 10's Composer. I'm going to submit a bug report there. If there is anything more you can share about this bug, please let me know.

For my Ansible setup, I'll look into having it check out the Git repository and building the assets as well. But I'd be happier if the bug in Debian's Composer gets fixed :)

**Comment by imrejonk** [comment]
@tvdijen Here is the commit done between the Composer 1.8.4 and 1.8.5 releases that fixed this for me: https://github.com/composer/composer/commit/ba346ef04d7cc6fdbf9423b06f51e48485d20b77. This explains why Composer only failed on the SSP 1.19.0 release tarball; the tarball includes a Composer v2 installed.json file, which Composer 1.8.4 and before can't parse. I guess that this issue is still somewhat relevant: maybe the SSP developers can keep using the v1 installed.json format in their release tarballs a bit longer? Let's say until Debian 11 gets released later this year?

I've submitted a bug report to the maintainer of the composer package in Debian. The problem has of course been addressed in composer 2.0.9-1 in Debian Testing already.

**Comment by tvdijen** [comment]
Very interesting.. But I'm still not 100% convinced, because the composer.json file is exactly the same in the tarball.. and I can only reproduce the issue with the tarball..
Also, I've been comparing the files against v1.18.8 and besides the content, they are structurally the same.
The only thing I can think of is that one of our dependencies upstream have a v2 formatted file..

**Comment by tvdijen** [comment]
I think I found the smoking gun in the composer v2.00 upgrade notes;

```
vendor/composer/installed.json format changed:

    packages are now wrapped into a "packages" top level key instead of the whole file being the package array
    packages now contain an "installed-path" key which lists where they were installed
    there is a top level "dev" key which stores whether dev requirements were installed or not
```

That explains why I didn't have the issue with a git checkout, only with the tarball..
@olavmrk Any chance you've used composer v2 when building the tarball? Or ran `composer self-update` somewhere during the build process?

**Comment by tvdijen** [comment]
Yup, never mind...  I see we just download the latest version from the build-script;

https://github.com/simplesamlphp/simplesamlphp/blob/c8106cea0ff64cab0c9486087db4fa5bf0ebaca9/bin/build-release.sh#L40

I'm going to change the build-script to downgrade composer to v1.

**Comment by tvdijen** [comment]
@imrejonk To prove my theory you could `rm -rf vendor` before running the `composer require simplesamlphp/simplesamlphp-module-webauthn`..  This should be temporary until v1.19.1 is released.. Since we have a reasonable workaround and this is probably an edge case (I've never heard someone using composer as a Debian-package), I'm not going to push on a new bugfix release

**Comment by imrejonk** [comment]
> @imrejonk To prove my theory you could `rm -rf vendor` before running the `composer require simplesamlphp/simplesamlphp-module-webauthn`.

Yep, this works. I also thought it was the installed.json format change, see the commit I was linking to.

The workaround I'm currently using is [a custom Composer Debian package](https://ftp.ciphermail.com/debian/pool/main/c/composer/composer_1.8.4-1%2Bciphermail1_all.deb). It's just the package from Debian 10 with the minimal changes applied. I like deploying software from Debian packages :)

**Comment by tvdijen** [comment]
To each their own! :rofl:  Glad we could kill this issue
