### ISSUE TITLE
Unresolved class in ArtifactResolutionService.php

### ISSUE THREAD

**Issue by rcnsheppardp** [simplesamlphp/simplesamlphp#1428]
**Describe the bug**
In the 1.19 branch, my IDE is showing an unresolvable class on the recent addition of a module enablement check in the ArtifactResolutionService.

**To Reproduce**
1. Open www/saml2/idp/ArtifactResolutionService.php in an IDE that checks type resolution
2. Observe an error on line 14

**Expected behavior**
Should probably be `\SimpleSAML\Module::` rather than just `Module::`

**Comment by tvdijen** [comment]
Thanks for reporting this @rcnsheppardp !
I see the `www`-directory is not taken into account during code inspection, so that's why this went unnoticed.
I've fixed this in  89c25f1 and it will be part of the next bugfix release..
