### ISSUE TITLE
Putting SimpleSAMLphp in a non web accessible location forces users to click the 'Submit' button

### ISSUE THREAD

**Issue by alexmorrisnz** [simplesamlphp/simplesamlphp#1429]
**Is your feature request related to a problem? Please describe.**
We're using SimpleSAMLphp in the auth_saml2 plugin for Moodle, it's placed under a .extlib directory so we aren't serving any SimpleSAMLphp files. Because of this the post.js and post.css do not get loaded and users have to click the Submit button to carry on. 
The files are very tiny so I do not see a problem with serving the content inline.

**Describe the solution you'd like**
Remove the post.js and post.css files and put them as inline JS and CSS.

**Describe alternatives you've considered**
We are going to modify the plugin's simplesamlphp version to serve from the root of the plugin and place the post.js and post.css files there, but getting a fix into SimpleSAMLphp would be the best option.

**Additional context**
![Screenshot from 2021-02-22 15-20-09](https://user-images.githubusercontent.com/6424711/108649182-ba021000-7521-11eb-9d6f-92881834d3e2.png)

**Comment by tvdijen** [comment]
That would make it impossible to protect SSP with a content security policy to block inline JS/CSS entirely and that is imho unacceptable for a security-related software product like this.
Why go over all this hassle instead of just exposing SSP's necessary assets?

**Comment by alexmorrisnz** [comment]
Hi, I wasn't apart of the discussion around the change to hide SSP but the ticket for it says "Just move this to somewhere non web visible by default for better security"

**Comment by tvdijen** [comment]
That's totally fine, but the www-directory is meant to be exposed..
My suggestion would be to create a /simplesaml alias on webserver-level and point to to SSP's www-directory

**Comment by alexmorrisnz** [comment]
No problem, thanks for the info.
