### ISSUE TITLE
Problem with BOM in config.php ?

### ISSUE THREAD

**Issue by TonHaver** [simplesamlphp/simplesamlphp#1432]
**Describe the bug**
After installing and configuring 1.19.0 on windows got warnings
simplesamlphp WARNING [97cb3944f5] The configuration file [filename] generates output. Please review your configuration. 

So far no problems, only the logfile warning

**To Reproduce**
1. Install 1.19.0 on windows
2. Open config.php in notepad, change technicalcontact_name, save file
3. Navigate browser to SimpleSAMLphp installation page
4. View log 

**Expected behavior**
No warning

**Screenshots or logs**
simplesamlphp WARNING [97cb3944f5] The configuration file [filename] generates output. Please review your configuration.

**Additional context**
Warning is generated in lib/SimpleSAML/Configuration.php
`$spurious_output = ob_get_length() > 0;`
Didn't see anything when outputting the buffer, found ob_get_length () had value 3

Noticed config.php is UTF-8 encoded, unlike other files in config
```
acl.php:         PHP script text, ASCII text
authsources.php: PHP script text, ASCII text
config.php:      PHP script text, UTF-8 Unicode text

```
While editing an UTF-8 file in windows, a Byte Order Mark is added, which is 3 bytes long.
It seems processing the config.php warns on that.

Saving config.php with encoding ANSI made warnings go away

**Comment by thijskh** [comment]
Indeed, the config template is UTF-8 unicode text. Although we could respond that your editor should just not be adding BOM marks to files, there's no real need for this config file to be UTF-8. So I've made it ASCII text to avoid this hassle where we can. Thanks for reporting.

**Comment by TonHaver** [comment]
I agree an editor shouldn't add the BOM, but notepad does :-(
Thanks for the change, hopefully it prevents others to burn a few hours like I did.

Maybe some users would want to use UTF-8 characters in names in config.php

An alternative woud be a change of the check in Configuration.php. 
I think this works

```
            $bom = pack('H*','EFBBBF');
            $config_output = preg_replace("/^$bom/", '', ob_get_contents() );
            $spurious_output = strlen($config_output ) > 0;

```

**Comment by jaimeperez** [comment]
I'm not sure I agree with this change, @thijskh. There are things in the configuration file that can indeed contain non-ASCII characters, and as such, it should be ok to have a unicode file. If some editors modify it in a predefined way that we can control, we can probably accommodate for those. But I wouldn't enforce ASCII as the encoding, as in some situations it might not even be reasonable.

**Comment by thijskh** [comment]
We do not enforce it at all, we just change the default encoding. To be the same as that for eg authsources.php, which is already ASCII.

**Comment by thijskh** [comment]
I think the proposal to actively filter out BOM's would be good for robustness. I'm a bit hesitant with "messing" with the files that the user supplied but it seems safe enough. Would there be anything against this?

**Comment by tvdijen** [comment]
I think there's only one way to find out.. Go!

**Comment by thijskh** [comment]
So the proposed solution just circumvents the check... but shouldn't we strip the BOM from config files entirely then before loading them?

**Comment by thijskh** [comment]
The proposed solution only influences the check, while a BOM in the file will at that point already have been output to the browser and causing problems. I'm not sure we can do anything about that to influence what require() does when a BOM-containing file has been loaded. So the warning seems about the right thing we can do. I'm not sure what else to do about this.
