### ISSUE TITLE
Reverse proxy and redirection

### ISSUE THREAD

**Issue by WebSabaki** [simplesamlphp/simplesamlphp#1437]
When relying on a reverse proxy such as Nginx and a server such as Apache, SSP seems to "incorrectly" handle redirections and cookies, depending on browsers.

Note that I do no really know here how to find if the issue is on the SP or the IdP side. IdP is not SSP based. Only the SP is. 

**Browsers**
***Impacted Browsers***
Chrome (88.0.4324.190) and Edge
***Safe Browser***
Firefox

**To Reproduce**
***case 1***
1. setup up SSP as a SP over port 8443 behind a proxy on port 443
2. perform login requests
3. error occurs with issue as NO STATE ("ld not load state specified by InResponseTo: NOSTATE Processing response as unsolicited")

***case 2***
1. setup up SSP as a SP over port 8443 behind a proxy on port 443
2. force cookies to be secure (HTTPS only) on config file of SSP
3. perform login requests
4. Redirections is made to port 8443

**Expected behavior**
Redirections is made to port 443

**Temporary Fix**
 make a PREROUTING redirect (with iptables) from 8443 to 443

**Comment by tvdijen** [comment]
@WebSabaki You should set `baseurlpath` in `config.php` to the url used externally.. Can you verify that specific setting?

**Comment by WebSabaki** [comment]
Hi @tvdijen 

yes, set at 'baseurlpath' => 'https://CLIENT.com/saml-service/'

**Comment by tvdijen** [comment]
Ohhh, I see the error now... NOSTATE.. That's an issue with PHP sessions... Can't really help you with that

**Comment by WebSabaki** [comment]
@tvdijen 

no, that is not the problem :)

for NOSTATE, the fix was to force cookie to be secure. Weird enough I did not see this issue before for someone thought
This maybe thus be related to case 2

for case 2, the redirection to port 8443 would IMHO be related to internal SSP behavior.

if I am on Firefox, neither case 1 (need for secure cookie) nor case 2 (incorrect redirect) occur
However, with Chrome and Edge, both occur.

Both cases are thus likely to be connected  and reverse proxy related, not PHP sessions

**Comment by tvdijen** [comment]
So, what if you log on to the admin page and check the 'Diagnostics' link, do you see anything regarding port 8443 there?

**Comment by WebSabaki** [comment]
Here is the diagnostics status

|  |  | 
| ------------- | ------------- | 
| HTTP_HOST | CLIENT.com:8443 | 
| HTTPS | on | 
 |SERVER_PROTOCOL | HTTP/1.0 | 
 |SERVER_PORT | 8443 | 
 |getBaseURL() | https://CLIENT.com/saml-service/ | 
 |getSelfHost() | CLIENT.com | 
 |getSelfHostWithNonStandardPort() | CLIENT.com | 
 |selfURLhost() | https://CLIENT.com | 
 |selfURLNoQuery() | https://CLIENT.com/saml-service/admin/hostnames.php | 
 |getSelfHostWithPath() | CLIENT.com/saml-service | 
 |getFirstPathElement()  | /saml-service | 
 |selfURL() | https://CLIENT.com/saml-service/admin/hostnames.php

**Comment by tvdijen** [comment]
Something is wrong there.. I've just checked it myself by putting my Apache webserver on port 8443 behind a reverse proxy and HTTP_HOST is without port-number and SERVER_PORT is still 443...

**Comment by tvdijen** [comment]
I see you use Nginx..  It's always a real bitch to get that working and I personally have no experience with it.
You may have better chances on our [mailinglist](http://groups.google.com/group/simplesamlphp) because this is an issue tracker, not a support forum.. (almost) nobody is reading this.

**Comment by WebSabaki** [comment]
Sure.

As you pinpoint to probably being nginx (config) sided, I will see with ML. Makes sense! Thanks for the clarifications @tvdijen
However, both issues still seem really strange to me (forcing secure cookies).

maybe the issue with NO STATE (https://simplesamlphp.org/docs/stable/simplesamlphp-nostate) shall also mention the cookie secure side as for me this was the way to fix it.

And maybe I will come back with an "Issue statement"  later :)

**Comment by tvdijen** [comment]
I guess it makes sense to add it there.. I think your NOSTATE issue is related to sameSite cookies.. It's fairly recent that browsers are enforcing this (about a year now), so that explains why it isn't mentioned in docs yet.

This may be a thing though..  We've automated this as much as possible, but I can imagine it not working on a non-standard port like 8443..  Would it be possible for you to test this setup with the backend running on port 443?

**Comment by WebSabaki** [comment]
Well, if I put the backend on 443, yes, I presume it will work as everything adds up :)

I will try that ASAP as current issue was discovered on production environment so I rather not touch that one

**Comment by tvdijen** [comment]
I'm just curious.. If it's not too much of a hastle for you..
Trying to find out if this is a possible bug or an Nginx configuration issue

**Comment by tvdijen** [comment]
Actually it's probably the latter, since I've tested with Apache on a non-default port..
Was this something encountered during upgrade from 1.18 to 1.19?

**Comment by WebSabaki** [comment]
No upgrade at all.
Simply added latest version as is.

When I say "I will try ASAP" it is just because my dev environment does not have the same settings and I can not alter the prod setup of the client :)

But as soon as I can reproduce the issue on dev / tests platform, I will update you. 

Hopefully by Saturday.

**Comment by tvdijen** [comment]
Ok, well feel free to reply on this thread and if reason enough I will reopen this issue..
If setting the backend-port to 443 gives the same issue, it would be interesting to know if v1.18.8 has the same problems.. v1.19.0 is fairly new..
