### ISSUE TITLE
Adding namespace and/or attribute to Extensions tag

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [simplesamlphp/simplesamlphp#1443]
Hi, 
I've a request that seems to be somehow related with @jaimeperez 's issues [[1]](https://github.com/simplesamlphp/saml2/issues/211) [[2]](https://github.com/simplesamlphp/saml2/issues/187).

In fact, some national (for instance, the [italian SPID](https://www.spid.gov.it/?lang=en-001),) and supranational (for instance, the european [eIDAS](https://en.wikipedia.org/wiki/EIDAS)) SAML-based  electronic identification systems require to customize metadata and/or AuthnRequest with Extensions with specific namespaces and/or attributes.

For instance, according to [SPID's technical reference](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n18_v.2-_autenticazione_persona_giuridica_o_uso_professionale_per_la_persona_giuridica.pdf) and in order to require an identification for legal persons,  AuthnRequests must be extended with the following Extensions:

```
<samlp:Extensions xmlns:spid="https://spid.gov.it/saml-extensions">
       <spid:Purpose>LP</spid:Purpose>
</samlp:Extensions>
```

In [Simplesamlphp's documentation is explained how to generate an Extensions' child with namespace](https://simplesamlphp.org/docs/development/saml:sp), but it's not clear if it's possible to add a namespace to Extensions tag itself, or, in general, to add an attribute.

If it's possible to do so, I would ask to edit the documentation in order to explain how to add a namespace to Extensions, otherwise, I would ask to consider to add this feature.

**Comment by tvdijen** [comment]
We also have set up a basic module-system for the saml2-libary where it becomes possible, as an SP, to override the default saml2 classes to be able to conform SPID and other SAML2-spinoffs..
A basic example for that is https://github.com/simplesamlphp/saml2-module-spid, but please bare in mind that this is experimental work for the next major release of both SSP and the saml2-library

**Comment by AntonioGiovanniSchiavone** [comment]
Hi @tvdijen 
Thanks for your reply.
The example you cited should generate the following xml snippet:  

```
<samlp:Extensions>
      <spid:Purpose xmlns:spid="https://spid.gov.it/saml-extensions">LP</spid:Purpose>
</samlp:Extensions>
```

which is different from SPID reference ( namespace is not for Extensions element, but for its child).

I'm currently supporting @damikael on [this Simplesamlphp - based project](https://github.com/italia/spid-php), but a native support will be great!

**Comment by tvdijen** [comment]
Ah right, yes this is not possible because it simply breaks SAML2 compliancy... The only way to get this working is with the aforementioned experimental module. We would have to override the samlp:Extensions class there, just like we did with the Issuer-class

**Comment by tvdijen** [comment]
It's actually ridiculous that spid breaks, because it doesn't matter where the xmlns is added... It's both valid 🤷‍♂️

**Comment by AntonioGiovanniSchiavone** [comment]
Hi @tvdijen,
I've read again the [aforementioned technical reference](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n18_v.2-_autenticazione_persona_giuridica_o_uso_professionale_per_la_persona_giuridica.pdf), and I noticed thai I missed this sentence:

> Ove la denominazione del namespace SPID https://spid.gov.it/saml-extensions mediante l’attributo xmlns
sia stata già inserita in altro elemento XML antenato dell’elemento Extensions, non deve essere inserita
nuovamente

It means that if an Extensions' ancestor has already defined the spid namespace (i.e. it has the attribute xmlns:spid="https://spid.gov.it/saml-extensions"), you can omit the namespace from Extensions tag.

Therefore a (legal!) workaround is to insert the spid namespace as attribute for AuthnRequest tag.

According to this [eIDAS document (paragraph 6.3)](https://ec.europa.eu/cefdigital/wiki/download/attachments/82773108/eidas_message_format_v1.0.pdf?version=1&modificationDate=1497252920416&api=v2), this should be valid also for eIDAS AuthnRequests (for the corrisponding namespace  xmlns:eidas="http://eidas.europa.eu/samlextensions" )

Now the question becomes: is there a way to dynamically decide whether to add the namespace to the AuthnRequest or not, depending on whether Extensions is required or not ?

**Comment by tvdijen** [comment]
No, this is not possible.. A namespace is added on the first element requiring it.. That's just common for XML, so I would be really surprised if SPID actually refuses an AuthnRequest with the spid-namespace set on the spid:Purpose-element

**Comment by thijskh** [comment]
As Tim describes, it should be possible now to add the namespace in an XML compliant way, that is, on the first element that uses it. If this is rejected then I doubt the receiving end uses a standard XML processing library?

I'm not sure if there's something for us left to do about this issue if the receiving end does not parse the XML correctly. Then the bug is on their side? Or am I missing something?

**Comment by tvdijen** [comment]
You're not missing something Thijs!
However, I would like to know if this is still an issue before we close it..  SPID has a few quirks where they go against the SAML2-specs, which is why we've created https://github.com/simplesamlphp/saml2-module-spid .  I could imagine adding a custom Extensions-element there that deals with this scenario.
