### ISSUE TITLE
logout fails using Firefox >=85.x with STATE INFORMATION LOST message

### ISSUE THREAD

**Issue by EnzephaloN** [simplesamlphp/simplesamlphp#1445]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
We're using simplesamlphp with out IDP since years. All works fine with Chrome, Edge and older Firefox. But with Firefox > 85.x logout isn't possible anymore. Instead of logout, you will recieve the simplesamlphp-error-page with "STATE INFORMATION LOST" message.

**To Reproduce**
1. use Firefox > 85.x
2. login
3. browse page or not
4. click on logout
5.1. sometimes you will see login-page from IDP which might suggested, but if you use browser's back-button, you are back loggedin
5.2. sometimes you will see simplesamlphp-error-page with STATE INFORMATION LOST message
6. logout not possible

**Expected behavior**
should logout and redirect to "RedirectTo"-page.

**Additional context**
As described above: It works with Vivaldi, Chrome, Edge and FirefoxESR. It fails on new Firefox.

````
//login-code example
try {
            $this->loggedin = new \SimpleSAML\Auth\Simple('default-sp');
            $this->loggedin->requireAuth();
            $this->attributes = $this->loggedin->getAttributes();
            $this->logLogin();
        }catch(\SimpleSAML\Error\Exception $e){
            error_log($e->getMessage() . " Redirecting to DEFAULT https://..............." );
            header('Location: https://.......');
        } 
````

````
//logout-code-example
            $this->auth->logLogout();
            unset($_SESSION['alskdfjalskj']);
            //rows below needed because of reverse-proxy
            $redirectTo = "https://";
            $redirectTo .= (isset($_SERVER['HTTP_X_FORWARDED_HOST'])) ? trim($_SERVER['HTTP_X_FORWARDED_HOST']) : trim($_SERVER['HTTP_HOST']);
            $logoutURL = $this->auth->loggedin->getLogoutURL();
            $url = substr($logoutURL, 0, stripos($logoutURL, "ReturnTo")) . "ReturnTo=".urlencode($redirectTo);
            header('Location: '.$url);
````

**Comment by tvdijen** [comment]
Without having looked into this yet;  you shouldn't be doing the rev. proxy 'fix'.. It's bad practise.
Just properly configure the `baseurlpath` in `config.php` and set it to the publically exposed url. SimpleSAMLphp will generate the correct urls for you

**Comment by EnzephaloN** [comment]
> Just properly configure the `baseurlpath` in `config.php` and set it to the publically exposed url. SimpleSAMLphp will generate the correct urls for you

Hello @tvdijen 
Thanx for your idea, but this isn't possible because the site is accessible from two different networks with two different addresses and two different IDPs (in fact this is the same IDP with different circle-of trusts). Because of this I have to build my redirect-url by myself.

**Comment by tvdijen** [comment]
Yikes!
Anyway, I've been testing and so far unable to reproduce with Firefox 86.0.1..
What SSP version are you using?

**Comment by EnzephaloN** [comment]
We use SSP 1.19.0.

I tested a lot last days...
Today I tried to call/link the SSP-logoutUrl directly, instead of calling/linking my route "/logout" which redirects to the SSP-logoutUrl (code above), which seemed to work better. But for today I can't test this on the production-server.
Sadly this cannot be a solution, cause I "need" to call/link my route for doing some logging `$this->auth->logLogout();`

But - just a thought - maybe FF does some weird caching or doen't redirect to the redirect or somthing like that...

**Comment by tvdijen** [comment]
It would be interesting to know what happens in the developer tools... Maybe something is blocked, like a piece of javascript?

**Comment by tvdijen** [comment]
I suspect your issue may be related to #1444 and cookies / cookie flags..  What have you set `session.cookie.secure` and `session.cookie.samesite` set to?

**Comment by EnzephaloN** [comment]
Hello

From our config.php:
````
session.cookie.name' => 'SimpleSAMLSessionID',

    'session.cookie.lifetime' => 0,

    'session.cookie.path' => '/',

    'session.cookie.domain' => null,

    'session.cookie.secure' => false,

    'enable.http_post' => false,

    'session.phpsession.cookiename' => null,
    'session.phpsession.savepath' => null,
    'session.phpsession.httponly' => true,

    'session.authtoken.cookiename' => 'kvtskeks',
````

**Comment by tvdijen** [comment]
Sorry I never got back to you..   If you set `session.cookie.secure` to `true` and `session.cookie.samesite` to `None` or the default computed value, it should work just fine...
The cache-settings you are referring to mean nothning to me..  What are they? And how are they related to SimpleSAMLphp?

**Comment by EnzephaloN** [comment]
Hello @tvdijen . 
Newer Firefox (and maybe Chrome also) are caching too much. If your cookie is set to "expire at end of session", these browsers do cache the session and the cookie never expires. But SimpleSAML doesn't know the cookie anymore. In our installation the default PHPSESSID was the problem.

We managed this by setting a new cookie-name and an expiredate set. 

...I think my english is to bad to write down the whole story...
