### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by abirinci** [simplesamlphp/simplesamlphp#1446]
Hello there,
I installed version 1.19.0. When I click Admin Login I get "ERR_TOO_MANY_REDIRECTS" Error.

I could not find out why. I am open to suggestions for solutions :)

**Comment by tvdijen** [comment]
Is there any chance you have `session.cookie.secure` set to false?

**Comment by lucasdavila86** [comment]
I've got the same problem on Chrome, but worked ok in Firefox.
I've solved the issue with chrome, configuring SSL on the webserver and `session.cookie.secure` set to true.
