### ISSUE TITLE
"redirect url after logging out" with URL "Shibboleth.sso/Logout?return=" doesn't work

### ISSUE THREAD

**Issue by hollyhw15** [simplesamlphp/simplesamlphp#1450]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
Hi, out portal site has integrated with simplesamlphp, so our user was direct to our Shibboleth service during sign in process. However, the log out doesn't terminate user's Shibboleth session. User has to close browser to terminate Shibboleth cookie session. 
1. The Shibboleth support team give me this url to sign out, said that it worked for other application:
"https://myapigeesite/Shibboleth.sso/Logout?return=https://shb.ourshibbolethsite.edu/shibboleth-idp/Logout?entityId=myapigeesiteentityId"
2. I have saved about url in the simplesamlphp configuration page. It doesn't work. I will load screenshots later

3. I have verified that setcookie('NO_CACHE', '1') in acquia_config.php was commented out

/**
 * Cookies No Cache.
 *
 * Allow users to be automatically logged in if they signed in via the same
 * SAML provider on another site by uncommenting the setcookie line below.
 *
 * Warning: This has performance implications for anonymous users.
 *
 * @link https://docs.acquia.com/resource/simplesaml/
 */
// Commenting out NO_CACHE cookie to prevent Varnish caching bypass.
// setcookie('NO_CACHE', '1');

**To Reproduce**
I have tested in our stage and PROD site, both integrated with Shib, both site don't work

**Expected behavior**
When user click "log out", shib session will be terminated without close the browser. User will be re-direct to shib service if need to log in again in the same browser. 

**Screenshots or logs**
config
![image](https://user-images.githubusercontent.com/69690136/113649003-7d5a2600-9642-11eb-802e-93ddd73d5ed6.png)
User click on log out
![image](https://user-images.githubusercontent.com/69690136/113649205-dfb32680-9642-11eb-9680-83e8cab96005.png)

User click "login" can login directly to portal without shib signin 

Thank you for your help

Holly

**Comment by tvdijen** [comment]
Try removing the first bit of the return-url... Just set it to the logout-url for the Shib IDP

**Comment by hollyhw15** [comment]
> Try removing the first bit of the return-url... Just set it to the logout-url for the Shib IDP

TV, 
Yes, I did exactly you said, in the logout url box, I have
"/Shibboleth.sso/Logout?return=https://shb.ourshibbolethsite.edu/shibboleth-idp/Logout?entityId=myapigeesiteentityId" 

The traffic was forwarded to the correct url (shib team provided), but I saw that Sorry page

**Comment by tvdijen** [comment]
That's not a valid url...  Why would you expect that to work?

**Comment by hollyhw15** [comment]
> That's not a valid url... Why would you expect that to work?

This is what my shib team told me
"EntityID is the SP entityID that’s configured  in your shibboleth2.xml (in case of shib SP) or SAML configuration (in case of SAML base SP). Application location is also a part of Apigee setup (note that the location includes path of the application,  for example, developer.api.ucla.edu/PATH – again, PATH here is also a placeholder). Once you find the accurate information, plug them in https://APIGEEurl/Shibboleth.sso/Logout?return=https://shb.ais.ucla.edu/shibboleth-idp/Logout?entityId=SHIBENTITYIDofAPIGEE. It should work." 

This is the URL I got when I click Logout
https://developer.api.ucla.edu/Shibboleth.sso/Logout?return=https://shb.ais.ucla.edu/shibboleth-idp/Logout?entityId=developer.api.ucla.edu 

My shib team can't tell what went wrong. They said that the other team configed the same way, and it should work

**Comment by tvdijen** [comment]
Now you're talking about both a Shib IDP and SP... Where does SimpleSAMLphp fit into this, because none of what you've showed so far has anything to do with SimpleSAMLphp...

**Comment by hollyhw15** [comment]
TV, the logout url has to be saved in SimpleSAMLphp configure setting.

**Comment by tvdijen** [comment]
That's not SimpleSAMLphp...  That's some kind of third party interface I've never seen before

**Comment by hollyhw15** [comment]
TV, 
This is the workflow we usually follow to include a new module: 
1. composer update with the required module name
2. log in into the portal site, "Extend", and enable this module
3. Click on the config part and config this module

SimpleSAMLphp was included into our portal by a contractor, with some configuration modification in PHP and config files.  I am not sure if I did the the right way to modify the logout url.

**Comment by tvdijen** [comment]
No way for me to tell either.. You should probably ask your contractor

**Comment by hollyhw15** [comment]
please don't close this issue. The contractor has gone. Hope someone here can share some experience
