### ISSUE TITLE
Confusion about removal of 'authlinkedin'

### ISSUE THREAD

**Issue by drybjed** [simplesamlphp/simplesamlphp#1451]
The https://github.com/simplesamlphp/simplesamlphp/commit/0bbe3de11a9f32acde1d14b19f7fa4dbf93f2e0e commit removed support for `authlinkedin` authentication source due to LinkedIn no longer providing OAuth1. However it seems that this commit removed the `twitter` example instead of `linkedin` example from `config-templates/authsources.php`. Was that a mistake? Perhaps both configuration examples could be swapped to make it clear what services are supported.

**Comment by tvdijen** [comment]
Thanks! The examples have been restored.
authlinkedin is broken to due API changes at LinkedIn..  authtwitter is suffering from the same issue and is likely to be removed as well in a future release, unless anyone wants to fix it.
