### ISSUE TITLE
How to add a module to https://simplesamlphp.org/modules ?

### ISSUE THREAD

**Issue by RoSk0** [simplesamlphp/simplesamlphp#1452]
Hello. Spend good half an hour trying to figure out how to "Let us know about your module so we can reference it in this web site, so that our users can easily find it." from <https://simplesamlphp.org/modules> but that not as easy as it sounds. All subscribe to mail list and Google group links looks broken - no luck subscribing to anything.

For one of our hi-profile clients using SSP we wanted to integrate [Sentry]([url](url)) for error reporting from SSP. I done some googling but haven't found anything. Our company, [Catalyst IT](https://www.catalyst.net.nz/) uses SSP quite a lot for many clients so I asked and no one new about existing integration. Also <https://packagist.org/?query=sentry&type=simplesamlphp-module> had nothing.

Being unable to find existing solution I created one - <https://gitlab.com/kroskolii/simplesamlphp-module-sentry>. It's pretty basic at the moment but serves the purpose - it reports missed exceptions to Sentry. I would love to see this module added to <https://simplesamlphp.org/modules> so people know it's there because when you search for "sentry and SSP" all you will find is instruction on how to set up SSO into Sentry with SSP.

**Comment by tvdijen** [comment]
Hi @RoSk0 !  Our website had its own repository where you can add the module; https://github.com/simplesamlphp/simplesamlphp.github.io

Your implementation however, is wrong... Hooks are only called from the admin pages..
There's an (undocumented, I must admit) feature that allows you to set `syslog.handler` in config.php to a custom class.. as long as it implements `SyslogHandlerInterface`.  This would be the more future proof way to implement Sentry integration.
