### ISSUE TITLE
Infinite loop testing default source

### ISSUE THREAD

**Issue by ob1chewy** [simplesamlphp/simplesamlphp#1453]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
I installed the latest version (1.19)
When I try to test default-sp, I reach my Microsoft Login (correct)
And the Redirect URL brings me back to the page that display the credentials.

But if I perform the same thing again (being already logged in) the redirect URL ends up in an infinite loop and never reaches the page that display the credentials.

**Additional context**
The problem only occurs with Chrome, not Firefox, Opera or Safari.
Reading some forum about the same issue, someone points out that the previous version (1.18.8) was behaving correctly.
I installed version 1.18.8 and all went well !

**Comment by tvdijen** [comment]
See https://github.com/simplesamlphp/simplesamlphp/issues/1446
