### ISSUE TITLE
[newbie - help - request]

### ISSUE THREAD

**Issue by lblabr** [simplesamlphp/simplesamlphp#1457]
i jsut started to simplesamlphp and i have some problems to get it up and running....

environment:
i try to get it working on shared hosting provider plattform (www.ionos.de)

1) copied version 1.19 to webspace subdir simplesamlphp
2) connected subdomain (https://samlidp.lb-automation.de) with folder simplesamlphp (now the subdmain has it as root ?? like alias in your apache config ?)
3) changed baseurlpath to 'www/' (simplesamlphp is available at https://samlidp.lb-automation.de/www)

$url = $request->server->get('PATH_INFO');
Assert::same(substr($url, 0, 1), '/');

throws an execption

i just use the throw exception and the displayed path is:

https://samlidp.lb-automation.de/www/module.php/core/frontpage_welcome.php

do i need some special things an a shared installation ?

thanks in advance

Lars

**Comment by tvdijen** [comment]
This is not a support forum and based on the info you've shared there is no way anyway could help you

**Comment by lblabr** [comment]
where exactly i get help ?

**Comment by lblabr** [comment]
as i could see, in the past there were problems with 

i have seen those issues:
https://github.com/simplesamlphp/simplesamlphp/issues/1093
https://github.com/simplesamlphp/simplesamlphp/pull/1095

I'm not that expert, i would the product give a try... but it's not working, what informations are needed ?

**Comment by tvdijen** [comment]
It's important to know your Apache config and the directory structure your working with..
Setting baseurlpath to `www/` doesn't make much sense to me..

For support;  https://simplesamlphp.org/support
