### ISSUE TITLE
Testing other providers with this software

### ISSUE THREAD

**Issue by elfring** [simplesamlphp/simplesamlphp#1462]
How do you think about the possibility to check the conformance of other provider implementations to involved software standards with this software?

**Comment by tvdijen** [comment]
Hi @elfring !
There is actually a programme that addresses this and aims at testing interoperability with/between the most commonly used products.. I've asked the key person of the programme to fill you in

**Comment by elfring** [comment]
* Would you like to point  any more information sources out for the desired software interoperability?
* How many test cases can be reused (or improved) for checking the collaboration status with involved data formats?

**Comment by tvdijen** [comment]
What exactly is the goal of all this?, because we virtually have no resources to do anything right now..

**Comment by elfring** [comment]
I am trying to clarify the current software development (and test) situation another bit for available provider implementations.

**Comment by tvdijen** [comment]
I'm still not sure what info you are looking for...
Development is close to non-existing at the moment and so are tests....   Our saml2-library does have a lot of unit-tests to cover the protocol-specifications.

**Comment by elfring** [comment]
* I find your view about the development status interesting.
  May it be influenced by any factors?
* Which unit-tests do refer to requirements from the protocols (and data formats)?

**Comment by tvdijen** [comment]
Just the fact that I'm the only active developer at the moment...

An example of a unit test could be this one;  https://github.com/simplesamlphp/saml2/blob/master/tests/SAML2/XML/md/ContactPersonTest.php#L98 or https://github.com/simplesamlphp/saml2/blob/d2f9e61ad496092636bfbf3ff978d3cfc4d57767/tests/SAML2/XML/samlp/StatusTest.php#L77

Those test for specific parts of the SAML2-specs..

**Comment by elfring** [comment]
Thanks for your background information.

* My knowledge is also evolving according to the distribution of test approaches between development repositories.
* I hope to achieve a better understanding for the current support of data formats and their test coverage.

Are there any remaining open issues to reconsider under special circumstances?

**Comment by tvdijen** [comment]
What do you mean by data formats? :raised_eyebrow:

**Comment by elfring** [comment]
Further examples:
* Which attributes should be considered for the proper data processing according to users (or principals) by identity providers?
* Time constraints for certificates

**Comment by tvdijen** [comment]
That's all up to you and your federation partners.. In some larger federations there usually exists something like a common baseline or 'trust-framework' where this stuff is defined.

**Comment by elfring** [comment]
Another development concern:
I imagine that the selection of desired and required properties can vary for users (or principals) in special application areas.

**Comment by elfring** [comment]
We come along different views for the mentioned software aspects.

* Federation can become another development challenge, can't it?
* I find your feedback also helpful already.
* I hope that desirable software evolution can be clarified further.
* How do you think about to compare available implementations for the registration of users (or principals) and corresponding identity/service providers?

**Comment by tvdijen** [comment]
I get the feeling I'm talking to a bot 😕

**Comment by elfring** [comment]
:thinking: Would you like to try any other communication tools out so that probabilities will increase to get better impressions?

**Comment by tvdijen** [comment]
Clearly a bot. Blocked & reported
