### ISSUE TITLE
Error 'PHP message: Error: Call to undefined method SimpleSAML\\Utils\\HTTP::canSetSameSiteNone()

### ISSUE THREAD

**Issue by PeideAmonNg** [simplesamlphp/simplesamlphp#1465]
Configured SimpleSamlphp to run as idp. Using Drupal 8.

Getting the following error when running SimplesamlPHP as Idp:

[Wed May 19 01:31:12.647975 2021] [proxy_fcgi:error] [pid 29045:tid 139989853579008] [client 192.168.88.1:63157] AH01071: Got error 'PHP message: Error: Call to undefined method SimpleSAML\\Utils\\HTTP::canSetSameSiteNone() in /var/simplesamlphp/config/config.php on line 581 #0 /var/www/drupalvm/drupal/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Configuration.php(128): require()\n#1 /var/www/drupalvm/drupal/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Configuration.php(262): SimpleSAML\\Configuration::loadFromFile('/var/simplesaml...', true)\n#2 /var/www/drupalvm/drupal/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Configuration.php(346): SimpleSAML\\Configuration::getConfig()\n#3 /var/www/drupalvm/drupal/web/modules/drupalauth4ssp/drupalauth4ssp.module(112): SimpleSAML\\Configuration::getInstance()\n#4 /var/www/drupalvm/drupal/web/modules/drupalauth4ssp/drupalauth4ssp.module(37): _drupalauth4ssp_get_simplesamlphp_config()\n#5 /var/www/drupalvm/drupal/web/modules/drupalauth4ssp/drupalauth4ssp.module(23): drupalauth4ssp_set_user_cookie(Object(Drupal\\user\\Entity\\User))\n#6 [internal function]: drupalauth4ssp_user_login(Object...', referer: https://drupalvm.test/user/login?ReturnTo=https%3A%2F%2Fdrupalvm.test%2Fsimplesaml%2Fmodule.php%2Fdrupalauth%2Fresume.php%3FState%3D_0e6d58df982f2d01e4a7221d9786f7f2716df02bd8%253Ahttps%253A%252F%252Fdrupalvm.test%252Fsimplesaml%252Fsaml2%252Fidp%252FSSOService.php%253Fspentityid%253Dhttp%25253A%25252F%25252F192.168.33.10%2526RelayState%253Dhttp%25253A%25252F%25252F192.168.33.10%25252Fsaml%25252F%2526cookieTime%253D1621387868

To get SAML authentication working for now, in config.php, I replaced

`'session.cookie.samesite' => \SimpleSAML\Utils\HTTP::canSetSameSiteNone() ? 'None' : null,
`

with 

`'session.cookie.samesite' => 'None',
`

**Comment by tvdijen** [comment]
That means you're using the config for 1.19, with a pre-1.19 release of SimpleSAMLphp

**Comment by tvdijen** [comment]
But the drupalauth-module you're using also uses SimpleSAMLphp under the hood and that's probably the older version..
What PHP-version are you on?

**Comment by PeideAmonNg** [comment]
Oh interesting its running on PHP 7.4. I am running Drupal inside the Drupal VM https://www.drupalvm.com/

**Comment by PeideAmonNg** [comment]
You are right. I looked at composer.lock in the drupal set up and it's installed simplesamlphp/simplesamlphp version v1.18.8.

Not sure why it didn't install the latest version 1.19, since in composer.json, I had "drupal/drupalauth4ssp": "^1.1", and drupalauth4ssp requires  "simplesamlphp/simplesamlphp": "~1.0"

**Comment by PeideAmonNg** [comment]
simplesamlphp 1.19 is compatible with PHP 7.4 as well it seems

**Comment by tvdijen** [comment]
I'm not sure either, but there are probably some secondary dependencies that are conflicting..
Set it to  "simplesamlphp/simplesamlphp": "^1.19" and run `composer update` and see what happens..

**Comment by PeideAmonNg** [comment]
ah looks like simplesamlphp 1.19.x requires twig/twig ~2.0, where as drupal/core-recommended requires twig/twig v1.42.

However, Drupal 9 uses twig version 2, but upgrading to Drupal 9 is not an option because the module drupalauth4ssp only supports up to Drupal 8. So looks like I will have to downgrade simplesamlphp to 1.18.x

**Comment by tvdijen** [comment]
Yeah we see this a a lot with drupal and some other product that uses SSP in some kind of plugin/module...
It's really up to them to update.. I can't really recommend to stay on 1.18.8, because it will _never_ receive any updates..
There are no known vulnerabilities to 1.18.8 right now, so no immediate reason to panic.

Since this is not an SSP-issue and we cannot solve this for you, this issue will be closed.

**Comment by PeideAmonNg** [comment]
Thanks a lot for your help @tvdijen
