### ISSUE TITLE
Bug after login

### ISSUE THREAD

**Issue by pmarquesmota** [simplesamlphp/simplesamlphp#1467]
**Describe the bug**
After login, we receive the following error message :
![bug](https://user-images.githubusercontent.com/25176232/119969441-d98c5700-bfae-11eb-9b55-24b6fdfeeb0a.png)

**Additional context**
The issue occur with both install via composer and simplesamlphp-1.19.1.tar.gz

**Comment by tvdijen** [comment]
It means your IDP responded with a 'Responder error'.
Contact them to figure out what the problem is..
