### ISSUE TITLE
[BUG] iDP-First initiated SAML sessions not passing additional parameters to RelayState URL

### ISSUE THREAD

**Issue by areis422** [simplesamlphp/simplesamlphp#1473]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
v1.19.1 - iDP-initiated SAML with extra parameters not being passed through

**To Reproduce**
go to idp.example.com/some/url/to/the/entityid?foo=bar
IDP redirects to relaystate after successful authentication
Middle ware/RelayState page that parses and unwraps SAML Response doesn't include/see foo=bar
actions that should be taken when foo=bar are ignored because $_REQUEST['foo']='bar' is not set/exists

**Expected behavior**
RelayState should include/see foo=bar when idp initiated

**Additional context**
Used to work with v1.10.0, recently upgraded to v1.19.1. Using SP-first initiation works without a problem on v1.19.1.

**Comment by tvdijen** [comment]
We know from the linked issue that this was introduced somewhere between 1.11.0 and 1.18.4 ...
It would help us a lot if you can help is pinpoint the version where this got broken...
There's a lot of changes between Nov 2013 and Jan 2020...............

**Comment by tvdijen** [comment]
Going over the changelog, these are the 'suspicious' changes;

1.17.0:
    IdP initiated login: add compatibility with Shibboleth parameters.

1.15.2:
    Resolved a security issue with the open redirect protection mechanism. See SSPSA 201801-02.

1.14.0:
    Fixed an issue with replay detection in IdP-initiated flows.

**Comment by tvdijen** [comment]
We had actually already fixed this on `master`, but it was never backported to the 1.19-branch.
Cherry-picked 96375af5606ad0cf035ccdae069bb4992b017ddc
