### ISSUE TITLE
Silently fail on missing epTID identifyingAttribute

### ISSUE THREAD

**Issue by mrvanes** [simplesamlphp/simplesamlphp#1476]
https://github.com/simplesamlphp/simplesamlphp/blob/1cec777e1ad17fd93c2a92f1c2f650a482da80c4/modules/core/lib/Auth/Process/TargetedID.php#L103

I had a usecase where we optionally want to hand-out epTID depending on whether the identifyingAttribute is available or not and where availability is unpredictable. Breaking this hard on the absence of this attribute seemed a bit harsh and maybe could be made optional at least?

**Comment by tvdijen** [comment]
Agreed, that should not be an `Assert` but a simple if-statement that will log a notice and silently returns.. Will fix

**Comment by tvdijen** [comment]
The initial commit was broken, but I've fixed it just now
