### ISSUE TITLE
The exampleauth Module Is Disabled by Default

### ISSUE THREAD

**Issue by ilyabakhlin** [simplesamlphp/simplesamlphp#1477]
According to the documentation about [setting up the identity provider](https://simplesamlphp.org/docs/stable/simplesamlphp-idp), there's no reference to the following line of code:

https://github.com/simplesamlphp/simplesamlphp/blob/64fca25a48c6ad3fb490b7039eeee3b6eb19153f/config-templates/config.php#L486

In the mentioned documentation, you can enable the module by creating the `enable` file. However, the application ignores that, forcing the developer to look for this key and set it to `true`.

Why is that, and why is it not documented? The module is not enabled by default as the `enable` file is not present in the module's directory.

**Comment by thijskh** [comment]
There are/were different ways to handle it, which can indeed be confusing. I've now changed it to the modern way. Thanks for spotting.

**Comment by ilyabakhlin** [comment]
Thank you very much for fixing this issue so quickly!

However, I'm confused. What do you mean by the *modern way* of enabling the module?

**Comment by thijskh** [comment]
The way as described in the docs in my change
