### ISSUE TITLE
Make specfile cross-distro

### ISSUE THREAD

**Issue by SchoolGuy** [simplesamlphp/simplesamlphp#1479]
**Is your feature request related to a problem? Please describe.**

Yes. Currently I can't build this with openSUSE which I do want to unbundle this dependency from [Resourcespace]()

**Describe the solution you'd like**

That the specfile I will develop at https://build.opensuse.org/package/show/home:SchoolGuy/simplesamlphp will be merged upstream.

**Describe alternatives you've considered**

- Leaving it downstream: Well possible because maintainers traditionally leave distro-specific patches out of upstream but that would make the upstream specfile out of date at some point
- Creating a seperate specfile: If desired we can also go this route.

**Additional context**

If this is ever submitted to the openSUSE distro that would be great but I have too much on my plate to maintain it, it would be great if a maintainer by the simplesamlphp community is found and this doesn't stick with me.

**Comment by tvdijen** [comment]
@thijskh I think you've worked with spec-files for Debian before, am I right?

**Comment by SchoolGuy** [comment]
@tvdijen That would require debbuild but yes it is possible, although not native in the end. I was referring to something like CentOS 7, 8 and openSUSE 15.x, Oracle Linux, ...

**Comment by thijskh** [comment]
Debian does not use specfiles usually, this is primarily for RPM-based distros, I'd be open to a PR to make our shipped spec file more generically usable though.

**Comment by SchoolGuy** [comment]
Good. I get started on it this week.

**Comment by tvdijen** [comment]
@SchoolGuy Is this still something you want to work on? If not, I'd like to close this issue
