### ISSUE TITLE
Fatal error: Uncaught Error: Using $this when not in object context in /var/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php on line 985

### ISSUE THREAD

**Issue by davidbuzz** [simplesamlphp/simplesamlphp#1483]
**Describe the bug**
I have SSP configured as a SDP and IDP for testing of my SDP integration code with my app.   Using  php sessions. I have the IDP on a different virtual hostname on hte same host,to make this possible.  SDP is configured to auth to IDP. IDP is configured to auth to example-user-pass.   my app uses php sessions as well ,but i have been careful to avoid those gotchas, and now with thius fix its working as-expected.  I am able to browse to /simplesaml/ on both virtual hosts and login to a session, and logout to no session, etc. 

reason... $this is not defined   in  redirect() call in HTTPRedirect.php as returns a class method not an object, and so you cant use $this inside it.   I've changed the MINIMUM number of '$this->' references to '\SimpleSAML\Utils\HTTP::' to make my problem go away. see patch

**To Reproduce**

```
... 
require_once('/var/simplesamlphp/lib/_autoload.php');
$auth = new \SimpleSAML\Auth\Simple('default-sp'); 
$auth->requireAuth(); 
...
```

**Error**
Fatal error: Uncaught Error: Using $this when not in object context in  /var/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php on line 985
Error: Using $this when not in object context in /var/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php on line 985

**Expected behavior**
No error.

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.

**Additional context**

------------------
diff that fixes it for me:
```
diff --git a/lib/SimpleSAML/Utils/HTTP.php b/lib/SimpleSAML/Utils/HTTP.php
index dbddd18b4..e4078e84b 100644
--- a/lib/SimpleSAML/Utils/HTTP.php
+++ b/lib/SimpleSAML/Utils/HTTP.php
@@ -157,7 +157,7 @@ class HTTP
      */
     public function getServerPort(): string
     {
-        $default_port = $this->getServerHTTPS() ? '443' : '80';
+        $default_port = \SimpleSAML\Utils\HTTP::getServerHTTPS() ? '443' : '80';
         $port = isset($_SERVER['SERVER_PORT']) ? $_SERVER['SERVER_PORT'] : $default_port;
 
         // Take care of edge-case where SERVER_PORT is an integer
@@ -217,12 +217,12 @@ class HTTP
             throw new \InvalidArgumentException('Invalid input parameters.');
         }
 
-        if (!$this->isValidURL($url)) {
+        if (! \SimpleSAML\Utils\HTTP::isValidURL($url)) {
             throw new Error\Exception('Invalid destination URL.');
         }
 
         if (!empty($parameters)) {
-            $url = $this->addURLParameters($url, $parameters);
+            $url = \SimpleSAML\Utils\HTTP::addURLParameters($url, $parameters);
         }
 
         /* Set the HTTP result code. This is either 303 See Other or
@@ -843,14 +843,14 @@ class HTTP
                 $port = !empty($port) ? ':' . $port : '';
             } else {
                 // no base URL specified for app, just use the current URL
-                $protocol = $this->getServerHTTPS() ? 'https' : 'http';
-                $hostname = $this->getServerHost();
-                $port = $this->getServerPort();
+                $protocol = \SimpleSAML\Utils\HTTP::getServerHTTPS() ? 'https' : 'http';
+                $hostname = \SimpleSAML\Utils\HTTP::getServerHost();
+                $port = \SimpleSAML\Utils\HTTP::getServerPort();
             }
             return $protocol . '://' . $hostname . $port . $_SERVER['REQUEST_URI'];
         }
 
-        return $this->getBaseURL() . $url_path . substr($_SERVER['REQUEST_URI'], $uri_pos + strlen($url_path));
+        return \SimpleSAML\Utils\HTTP::getBaseURL() . $url_path . substr($_SERVER['REQUEST_URI'], $uri_pos + strlen($url_path));
     }
 
 
@@ -914,7 +914,7 @@ class HTTP
      */
     public function normalizeURL(string $url): string
     {
-        $url = $this->resolveURL($url, $this->getSelfURL());
+        $url = \SimpleSAML\Utils\HTTP::resolveURL($url, \SimpleSAML\Utils\HTTP::getSelfURL());
 
         // verify that the URL is to a http or https site
         if (!preg_match('@^https?://@i', $url)) {
@@ -982,8 +982,10 @@ class HTTP
      */
     public function redirectTrustedURL(string $url, array $parameters = []): void
     {
-        $url = $this->normalizeURL($url);
-        $this->redirect($url, $parameters);
+        $url = \SimpleSAML\Utils\HTTP::normalizeURL($url);
+        \SimpleSAML\Utils\HTTP::redirect($url, $parameters);
+        //$url = $this->normalizeURL($url);
+        //$this->redirect($url, $parameters);
     }
 
```

**Comment by davidbuzz** [comment]
Quick additional note...   The place where "...redirect(...)" gets called from is ./vendor/simplesamlphp/saml2/src/SAML2/HTTPRedirect.php  around line 90.     the call is ``` Utils::getContainer()->redirect($destination);```.    

Oh, and yes, i'm using 'master' not 'release'.

**Comment by tvdijen** [comment]
Don't use master

**Comment by davidbuzz** [comment]
U know , you could have been a bit nicer about it... I found a bug in master and made a fix for it...

**Comment by tvdijen** [comment]
I wasn't being rude, I just replied in a hurry..

You didn't find a bug.. master is a work in progress and it's supposed to be like this.
We're moving everything to non-static where possible. What needs to be changed is the saml2-library and that's already done there in it's master-branch..
