### ISSUE TITLE
MDQ metadata source not generating the correct query

### ISSUE THREAD

**Issue by lonoak** [simplesamlphp/simplesamlphp#1487]
**bug description**
I'm using SSp together seamless access (see this article: https://redir.is/4FTQ3), and an MDQ server to resolve entities' metadata (description of my configuration below).

It could be the code in this line:

https://github.com/simplesamlphp/simplesamlphp/blob/5f52496a6f924250e8c5c0cc4e24a43f9582ff44/lib/SimpleSAML/Metadata/Sources/MDQ.php#L267

is not working because of the urlencode call not returning the URL correctly encoded. (logs below).

**To Reproduce**
My environment is RedHat Enterprise with PHP 7.4.15 installed from the ius repo (ius.io).

Steps to reproduce the behaviour:
1. Configure an external discovery as in the guide above
2. Configure the MDQ metadata resolver as here:

`     'metadata.sources' => [
           [
               'type' => 'mdq',
               'server' => 'https://mdq.sir2.rediris.es/edugain',
               'cachedir' => '/home/spool/SIR/test.sir2.rediris.es/esi-sp/mdq-cache',
               'cachelength' => 86400
           ]
      ],`

 3. Access the default-sp, and choose any identity provider

**Expected behavior**
I'm redirected to the selected remote IdP.

**Screenshots or logs**

`Jul 24 14:29:10 sir2test simplesamlphp[11494]: 6 [d77a88ed3a] Unable to fetch metadata for "https://www.rediris.es/sir/redirisidp" from https://mdq.sir2.rediris.es/edugain/entities/https.rediris.es: file_get_contents(https://mdq.server.org/edugain/entities/https.rediris.es): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found`

**Additional context**

**Comment by tvdijen** [comment]
I'm linking the mailing list thread for reference;  https://groups.google.com/g/simplesamlphp/c/-81KZ1d1hJk

@lonoak :  I'm tempted to say that the url `https://mdq.sir2.rediris.es/edugain/entities/https://www.rediris.es/sir/redirisidp` is not syntactically valid, but I have to consult the specs to be sure..  However I'm pretty sure that `:` colons are not valid

**Comment by lonoak** [comment]
An urlencoded url is fine... the thing is, the query url MDQ is generating (in my environment at least) is not the encoded original url... for some reason urlencode() is not working here as it should... I mean, the resulting url should have been:

`https://mdq.sir2.rediris.es/edugain/entities/https%3A%2F%2Fwww.rediris.es%2Fsir%2Fredirisidp`

While the generated url was:

`https://mdq.sir2.rediris.es/edugain/entities/https.rediris.es`

The logic is that urlencode, as it is in the code, should generate the first one, but it's generating the second... a similar code running under the same web server and PHP version produces the expected value.

**Comment by tvdijen** [comment]
@lonoak You have a proxy set?

**Comment by lonoak** [comment]
Hmmmm... I'm behind a proxy, yes... :(

**Comment by tvdijen** [comment]
I was thinking at loud..  Looking at this code;  https://github.com/simplesamlphp/simplesamlphp/blob/5f52496a6f924250e8c5c0cc4e24a43f9582ff44/lib/SimpleSAML/Utils/HTTP.php#L491-L507

I thought maybe the preg_match or parse_url could affect things.. But if you had no proxy configured, we can rule this out

**Comment by sgomez** [comment]
There are two problems here, and one is in the Logger:

Line [L280 in MDQ](https://github.com/simplesamlphp/simplesamlphp/blob/5f52496a6f924250e8c5c0cc4e24a43f9582ff44/lib/SimpleSAML/Metadata/Sources/MDQ.php#L280) log the error:

```php
if (empty($xmldata)) {
    $error = error_get_last();
    Logger::info('Unable to fetch metadata for "' . $entityId . '" from ' . $mdq_url . ': ' .
        (is_array($error) ? $error['message'] : 'no error available'));
    return null;
}
```

There are no way than `$mdq_url` could have a value distinct than expected, because `$entityId` is well defined. So the logger is not working well.

This happens because you are using [ErrorLogLoggingHandler](https://github.com/simplesamlphp/simplesamlphp/blob/5f52496a6f924250e8c5c0cc4e24a43f9582ff44/lib/SimpleSAML/Logger/ErrorLogLoggingHandler.php#L81) that does that with log string:

```php
$string = preg_replace('/%\w+(\{[^\}]+\})?/', '', $string);
```
This line is replacing urlencoded strings with nothing, so you can't trust into the log messages. Probably this should be tagged as a bug.

The real problem, I guess, your php server is not able to reach the mdq server. (in the log appears `mdq.server.org`, did you change the name on the example or this could be a clue?).

**Comment by lonoak** [comment]
Hi,

  Thanks for also looking into this, Sergio.

The problem could be in the MDQ server side (more on this below), but I agree the logger is dropping the urlencoded URL:

> There are two problems here, and one is in the Logger:
> 
> Line [L280 in MDQ](https://github.com/simplesamlphp/simplesamlphp/blob/5f52496a6f924250e8c5c0cc4e24a43f9582ff44/lib/SimpleSAML/Metadata/Sources/MDQ.php#L280) log the error:
> 
> ```
> if (empty($xmldata)) {
>     $error = error_get_last();
>     Logger::info('Unable to fetch metadata for "' . $entityId . '" from ' . $mdq_url . ': ' .
>         (is_array($error) ? $error['message'] : 'no error available'));
>     return null;
> }
> ```

That exact line outputs this:

`Jul 27 08:02:59 sir2test simplesamlphp[11650]: 6 [d77a88ed3a] Unable to fetch metadata for "https://www.rediris.es/sir/ucoidp" from https://mdq.sir2.rediris.es/edugain/entities/https.rediris.es: file_get_contents(https://mdq.sir2.rediris.es/edugain/entities/https.rediris.es): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found`

> There are no way than `$mdq_url` could have a value distinct than expected, because `$entityId` is well defined. So the logger is not working well.

The mdq_url prefix is fine (as it’s taken from configuration and doesn’t need to be url encoded), but the part of the entityId is not logged properly… 

For reference, the MDQ draft suggests the URL to be queried needs to be url encoded:

https://tools.ietf.org/id/draft-young-md-query-08.html#protocol.request.identifier

_"A single identifier, percent-encoded appropriately for use as a URL path segment (see sections 2.1 and 3.3 of [STD66])."_

> This happens because you are using [ErrorLogLoggingHandler](https://github.com/simplesamlphp/simplesamlphp/blob/5f52496a6f924250e8c5c0cc4e24a43f9582ff44/lib/SimpleSAML/Logger/ErrorLogLoggingHandler.php#L81) that does that with log string:
> 
> ```
> $string = preg_replace('/%\w+(\{[^\}]+\})?/', '', $string);
> ```
> 
> This line is replacing urlencoded strings with nothing, so you can't trust into the log messages. Probably this should be tagged as a bug.

Could be because of this, definitely… but not the real problem...

> The real problem, I guess, your php server is not able to reach the mdq server. (in the log appears `mdq.server.org`, did you change the name on the example or this could be a clue?).

Hmm… forget about the mdq.server.org… I didn’t want to show a server that is not yet publicly available, but then I changed my mind and didn’t restitute the original mdq server in my message.

On the other hand, I’m observing traffic going out and in, and the requests are logged in the MDQ server.

I have been digging a little bit more on the MDQ server side:

  - the MDQ server is behind a reverse proxy… this reverse proxy could probably be the cause of the problem, I’ll investigate this further… @tvdijen  already suggested this could be a proxy problem, but I was thinking in the client side, not the server side… 

  - forgetting about the client part (I’m assuming now SSp works fine in that respect), if I query the mdq directly, I get a 404 error if I build a query following what the draft says (and SimpleSAMLphp correctly builds):

https://mdq.sir2.rediris.es/edugain/entities/https%3A%2F%2Fwww.rediris.es%2Fsir%2Fucoidp

  - but I get the correct metadata if I use the ‘wrong' URL without encoding the entityId part:

https://mdq.sir2.rediris.es/edugain/entities/https://www.rediris.es/sir/ucoidp

(This returns the correct metadata)

So my assumption now is that the problem is either:

  - the reverse proxy (will check this now) is not working as expected
  - the mdq server itself does not work correctly… I see this less probable, even if I’m not using the last version…  
  
I’ll post here my findings later.

**Comment by lonoak** [comment]
Got it working... I just used (mdq server side) [this apache directive](https://httpd.apache.org/docs/2.4/mod/core.html#allowencodedslashes), and this solved the issue.

@tvdijen the logger issue probably would need a new bug to be filled-in, as suggested by @sgomez ... 

Thanks for helping me solve this mistery...

**Comment by tvdijen** [comment]
I think we should just remove that preg_replace from the logger..   The only purpose it is serving right now is to replace untranslated placeholders with an empty string.. That doesn't make much sense to me in the first place.
