### ISSUE TITLE
Cleanup the SimpleSAML_Session class

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#149]
The following must be done:

* Remove the default `NULL` value for the `$authority` parameter in the `getAuthState()` method. :+1: 
* Remove the `getAttribute()` method. :+1: 
* Remove the `setAttribute()` method. :+1: 
* Remove the `setAttributes()` method. :+1: 
* Remove the `getInstance()` method. :+1: 
  * Refactor. Should be renamed to `getCurrentSession()`. :+1: (see comment below)
  * The error handling code should disappear.
    * `session.disable_fallback` defaults to TRUE and goes away (exception is always thrown)
  * Some functionality to avoid recursive loops, maybe solved in `Logger::getTracktId()`.
  * Cleanup session initialization. Two flows:
    * load by ID
    * load by `$_REQUEST`
* Remove the `getAuthority()` method. :+1: 
* Remove the `getAuthnRequest()` method. :+1: 
* Remove the `setAuthnRequest()` method. :+1: 
* Remove the `getIdP()` method. :+1: 
* Remove the `setIdP()` method. :+1: 
* Remove the `getSessionIndex()` method. :+1: 
* Remove the `setSessionIndex()` method. :+1: 
* Remove the `getNameId()` method. :+1: 
* Remove the `setNameId()` method. :+1: 
* Remove the `setSessionDuration()` method. :+1: 
* Remove the `remainingTime()` method. :+1: 
* Remove the `isAuthenticated()` method. :+1: 
* Remove the `getAuthInstant()` method. :+1: 
* Remove the `getAttributes()` method. :+1: 
* Remove the `getSize()` method. :+1: 
* Remove the `get_sp_list()` method. :+1: 
* Remove the `expireDataLogout()` method. :+1: 
* Remove the `getLogoutState()` and `setLogoutState()` methods. If there's callers, change the call with a direct access to `$state['LogoutState']`. :+1: 
* Remove the `$authority` property. :+1: 
* Remove the `DATA_TIMEOUT_LOGOUT` constant. Check dependencies in: :+1: 
  * `lib/SimpleSAML/Auth/Source.php` and :+1: 
  * `lib/SimpleSAML/IdP.php` :+1: 
* Modify the `registerLogoutHandler()` method to add the `$authority` as a parameter. This is a previous step to wrapping this functionality into `SimpleSAML_Auth_Simple`. :+1:

**Comment by jaimeperez** [comment]
The `getInstance()` method has been already replaced by a `getSessionFromRequest()` method that's much more explicit and coherent with the two paths to obtain sessions (from ID and from `$_REQUEST`).

**Comment by thijskh** [comment]
Maybe you want to use `- [ ] Remove something` to define task lists which gives you actual checkboxes :)

**Comment by jaimeperez** [comment]
Oh, that's a great tip. Thanks @thijskh!
