### ISSUE TITLE
Session::getSession() results in "Cannot change session id when session is active" error

### ISSUE THREAD

**Issue by forevermatt** [simplesamlphp/simplesamlphp#1491]
**Describe the bug**
When trying to get the current session (such as in an Auth Proc or Auth Source) under certain circumstances, calling `\SimpleSAML\Session::getSession()` results in an error like the following:
```
simplesamlphp ERROR [a8ee963889] SimpleSAML\Error\Exception: Error 2 - session_id(): Cannot change session id when session is active at /data/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:206
```

Changing the `getSession()` call to instead be a `getSessionFromRequest()` call avoids the error. However, based on `getSession()`'s description, it looks like it is supposed to be able to retrieve the current session:
```
Get a session from the session handler.

@param string|null $sessionId The session we should get, or null to get the current session.

@return Session|null The session that is stored in the session handler, or null if the session wasn't
found.
```

This looks like either a bug in `getSession()` or information that needs to be corrected in its description. It's always possible, however, that we're misusing/misconfiguring something... if so, I'd love to know.

**To Reproduce**
I don't currently have a simple "clone this and do that" way to reproduce the error message. If that ends up being necessary to resolve this, let me know and I'll try to come up with one. (It wasn't worth that time if this is merely a "You're using it wrong" problem.)

**Expected behavior**
I expected to be able to call `\SimpleSAML\Session::getSession()`, not providing any parameters, and get the current session back.

**Screenshots or logs**
Here is a stack trace of what lead to that error. Note that the `SimpleSAML\Module\expirychecker\Auth\Process\ExpiryDate` occurrences refer to our own custom expirychecker module at <https://github.com/silinternational/simplesamlphp-module-expirychecker>.
```
SimpleSAML\Error\Exception: Error 2 - session_id(): Cannot change session id when session is active at /data/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:206
Backtrace:
15 /data/vendor/simplesamlphp/simplesamlphp/www/_include.php:48 (SimpleSAML_error_handler)
14 [builtin] (session_id)
13 /data/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:206 (SimpleSAML\SessionHandlerPHP::getCookieSessionId)
12 /data/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Session.php:332 (SimpleSAML\Session::getSession)
11 /data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker/lib/Auth/Process/ExpiryDate.php:160 (SimpleSAML\Module\expirychecker\Auth\Process\ExpiryDate::hasSeenSplashPageRecently)
10 /data/vendor/simplesamlphp/simplesamlphp/modules/expirychecker/lib/Auth/Process/ExpiryDate.php:322 (SimpleSAML\Module\expirychecker\Auth\Process\ExpiryDate::process)
9 /data/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/ProcessingChain.php:215 (SimpleSAML\Auth\ProcessingChain::processState)
8 /data/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/IdP.php:335 (SimpleSAML\IdP::postAuth)
7 [builtin] (call_user_func)
6 /data/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Source.php:246 (SimpleSAML\Auth\Source::loginCompleted)
5 [builtin] (call_user_func)
4 /data/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Source.php:159 (SimpleSAML\Auth\Source::completeAuth)
3 /data/vendor/simplesamlphp/simplesamlphp/modules/core/lib/Auth/UserPassBase.php:329 (SimpleSAML\Module\core\Auth\UserPassBase::handleLogin)
2 /data/vendor/simplesamlphp/simplesamlphp/modules/core/www/loginuserpass.php:84 (require)
1 /data/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Module.php:260 (SimpleSAML\Module::process)
0 /data/vendor/simplesamlphp/simplesamlphp/www/module.php:10 (N/A)
```

**Comment by tvdijen** [comment]
You can use `getSessionFromRequest()` for the current session or `getSession()` for a specific one..
I'll see if we can improve the descriptions and maybe even make `getSession()` private, because I don't think it should be used outside the Session-class.

**Comment by forevermatt** [comment]
Ahh, okay. So I really should just be using `getSessionFromRequest()`. Thanks for confirming that.

Feel free to close this issue unless it's helpful to you for tracking the possible changes you mentioned.

**Comment by forevermatt** [comment]
I think what planted the idea in my mind that this might be a bug was that even if I passed in the current session ID, it logged that error rather than simply returning the current session.
