### ISSUE TITLE
On logout it shows "To completely reset please close the browser once."

### ISSUE THREAD

**Issue by ohm1998** [simplesamlphp/simplesamlphp#1493]
This might be dumb but i am new to simplesaml and i need to clear the cookies or whatever and somehow , make the user logout . Currently using the logout from the documentation give this statement "To completely reset please close the browser once." I need to apply logout such that the user need not close the browser.

Let me know how to do it,  is it some config or some other way of logging out.

Thanks for helping.

**Comment by thijskh** [comment]
Is your installation an IdP or SP?

**Comment by ohm1998** [comment]
> Is your installation an IdP or SP?
> What is the “logout from the documentation” that you implemented exactly?

I think it is SP / not sure. Have started working on code received from someone else and i have to figure out this bug.
have used code from here 
https://simplesamlphp.org/docs/stable/simplesamlphp-sp-api#section_5


here's how logout.php looks like: 

`<?php
//remove all session variables
 session_start(); 
session_unset();

// destroy the session
 session_destroy();
  unset($_SESSION);
echo "<h1 style='text-align:center;'> You are signed out successfully</h1>";
 echo "<div align='center'>  You are not login. Please <a href='index.php'>login </a>First </div>";
 require_once ('./../../simplesaml/lib/_autoload.php');
 
$as = new SimpleSAML_Auth_Simple('default-sp');
$as->logout(array(
    'ReturnTo' => 'https://indonetonline.com/logged_out.php',
    'ReturnStateParam' => 'LogoutState',
    'ReturnStateStage' => 'MyLogoutState',
));
SimpleSAML_Session::getSessionFromRequest()->cleanup();
?>`

and here's how logged_out.php looks like : 

`<?php
 
require_once ('./../../simplesaml/lib/_autoload.php');

print_r($_REQUEST);
try {
  
	if ($_REQUEST['LogoutState']) {
		$state = SimpleSAML_Auth_State::loadState((string)$_REQUEST['LogoutState'], 'MyLogoutState');
    print_r($state);
	}
	else {
		echo "Were you logged in?";
		exit;
	}
}
catch (Exception $e) {
	echo 'Caught exception: ',  $e->getMessage(), "\n";
	exit;
}
$ls = $state['saml:sp:LogoutStatus']; // Only works for SAML SP
print_r($ls);
if ($ls['Code'] === 'urn:oasis:names:tc:SAML:2.0:status:Success' && !isset($ls['SubCode'])) {
    // Successful logout.
    echo("You have been logged out.");
} else {
    echo("You've been logged out, but the ADFS token is active and you'll be able to authenticate using it. To completely reset please close the browser once.");
}
?>`

**Comment by thijskh** [comment]
The string “To completely reset please close the browser once.” is not part of SSP sources, nor is it in the code fragments you give above. So it must come from somewhere else.

In any case, if you completely destroy the PHP session before calling logout(), SSP has not much left to act upon?

**Comment by ohm1998** [comment]
thanx for the prompt reply.
If is call session_destroy() before the $as->logout() function should that be enough or should I be making some other changes too?

**Comment by thijskh** [comment]
I would investigate where the message then comes from that you report is presented, otherwise I think we don’t understand what is happening.

I’m also not sure what the session_destroy is supposed to do.

**Comment by ohm1998** [comment]
session_destroy() usually removes all variables associated with the current session,
I think in the documentation it is mentioned that we need to close the browser to remove the cookies, 
Is there any way to remove the cookies using Js? I can change the config file or some other file through which this might be possible.

The result I need to achieve is the user need not close the browser, should be redirected to the login page.

**Comment by thijskh** [comment]
The problem with federated logout is that you cannot delete the remote party (IdP)’s cookies.

I’m not completely sure what you want to achieve exactly. Maybe I’m overlooking it but with me the word “reset” is not on that web page let alone the full sentence.

**Comment by ohm1998** [comment]
I am talking about the quote     echo("We were unable to log you out of all your sessions. To be completely sure that you are logged out, you need to close your web browser.");

Currently what is happening is that even after removing the session the user still does get authenticated, 

What i am asking or have to achieve is like a normal facebook logout when a person logouts and that's it , they need not close the browser . Let me know if you need more code details or any thing i should provide to make it clear?

**Comment by thijskh** [comment]
Do they need to be logged out of your application or also of their IdP?

**Comment by ohm1998** [comment]
Yes of the application and their IDP also

**Comment by ohm1998** [comment]
Here's the error that I am facing currently 

Activity ID: cdf9e587-72d9-4c22-a705-0080010000f8
Error details: MSIS7054: The SAML logout did not complete properly.
Node name: ec804bfc-2c79-455b-be11-9cb9fbc809e9
Error time: Mon, 09 Aug 2021 10:06:44 GMT
Proxy server name: IC***AP
Cookie: enabled
User agent string: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

**Comment by thijskh** [comment]
Your IdP apparently does not support Single Log Out. I would consult with the vendor of your IdP why this is the case and whether it can be solved. Since the IdP is not SimpleSAML it’s not something we can help with.

**Comment by ohm1998** [comment]
Is there any other logout that can be used?

**Comment by thijskh** [comment]
You can log out your local application just by destroying the session and not calling the logout function and leave it at that.

That is more like the Facebook Login you talked about earlier, if you implement Facebook Login you can log the user out again from your own app but you cannot/should not log them out of Facebook itself…

**Comment by ohm1998** [comment]
Here's the flow: 
1. MyAppUrl.com redirects to AdfsServerUrl.com (if not logged in)
2. User enters username and password, gets authenticated on AfsServerUrl.com, and is redirected to the dashboard
3. On Dashboard on clicking logout, if I destroy the session , i see the cookies of SimpleSAMLAuthToken and PHPSESSID are not removed
4. Also after the session destroy, when I again redirect to the MyAppUrl.com (which redirects to AdfsServerUrl.com) it again redirects to the dashboard as the user is authenticated on AdfsServerUrl.com

This is the overall problem I am facing.

If I use logout() from the simpleSaml documentation then it shows the "SAML logout did not complete successfully" on the AdfsServerUrl.com.

PS: The logout redirect configured on the server is : 

https://MyAppUrl.com/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp

Let me know if i am missing out on something.

**Comment by tvdijen** [comment]
Ask the administrator for AdfsServerUrl.com why logout failed.. Let them check their event viewer.

**Comment by ohm1998** [comment]
@tvdijen That might be an issue, the current SAMLphp version is (1.14.8) i will be trying to migrate to the latest version. Let me know if you have any suggestions for easy migration.

**Comment by tvdijen** [comment]
You could diff your config- and metadata files... There isnt really an easy way

**Comment by ohm1998** [comment]
Hey just upgraded to /var/simplesaml (1.19.1)

But still facing this error : 

Activity ID: cd955cb7-75cd-456b-1d0f-0080010000fb
Error details: MSIS7054: The SAML logout did not complete properly.
Node name: ec804bfc-2c79-455b-be11-9cb9fbc809e9
Error time: Mon, 16 Aug 2021 12:14:21 GMT
Proxy server name: IC***AP
Cookie: enabled
User agent string: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36

**Comment by tvdijen** [comment]
OK, so at least you're not vulnerable anymore for old security bugs...  Have you contacted the ADFS admin to have him check the event log?

**Comment by ohm1998** [comment]
Hey here's the activity log :  

The event id list would be : [320,362,364]

320 : 

The verification of the SAML message signature failed. 
Message issuer: https://base_url/simplesaml/module.php/saml/sp/metadata.php/default-sp 
Exception details: 
MSIS7084: SAML logout request and logout response messages must be signed when using SAML HTTP Redirect or HTTP POST binding. 

This request failed. 

User Action 
Verify that the message issuer configuration in the AD FS configuration database is up to date. 
Configure the signing certificate for the specified issuer. 
Verify that the issuer's certificate is up to date. 
Verify the issuer and server message signing requirements.

362 : 


Encountered error during federation passive sign-out. 

Additional Data 

Exception details: 
Microsoft.IdentityServer.RequestFailedException: MSIS7054: The SAML logout did not complete properly.
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.BuildSamlLogoutResponse(SamlContext samlContext, Boolean partialLogout, Boolean& logoutComplete)
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.ProcessSignOut(SamlContext samlContext, String redirectUri, List`1 iFrameUris, Boolean partialLogout)


364:



Encountered error during federation passive request. 

Additional Data 

Protocol Name: 
Saml 

Relying Party: 
 

Exception details: 
Microsoft.IdentityServer.RequestFailedException: MSIS7054: The SAML logout did not complete properly.
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.BuildSamlLogoutResponse(SamlContext samlContext, Boolean partialLogout, Boolean& logoutComplete)
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.ProcessSignOut(SamlContext samlContext, String redirectUri, List`1 iFrameUris, Boolean partialLogout)
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.Signout(ProtocolContext context, String redirectUri, List`1 iFrameSignoutUris)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.ProcessProtocolSignoutRequest(ProtocolContext protocolContext, PassiveProtocolHandler protocolHandler)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.ProcessProtocolRequest(ProtocolContext protocolContext, PassiveProtocolHandler protocolHandler)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)

**Comment by tvdijen** [comment]
So there is your problem.. You haven't configured signed requests..
Either you configure them or ask the IDP admin to not require signed LogoutRequests

**Comment by ohm1998** [comment]
Can you help me how to configure that? And the login does work without that so let me know?

**Comment by tvdijen** [comment]
Add these settings to your authsource;

```
        'redirect.sign' => true,
        'privatekey' => 'example.key',
        'privatekey_pass' => 'secret',
        'certificate' => 'example.crt',
```

**Comment by ohm1998** [comment]
The xml from the ADFS when parsed using the tool generates the following two config files : 

**saml20-sp-remote :** 

```



$metadata['http://icf.indostarcapital.com/adfs/services/trust'] = [
    'entityid' => 'http://icf.indostarcapital.com/adfs/services/trust',
    'contacts' => [
        [
            'contactType' => 'support',
        ],
    ],
    'metadata-set' => 'saml20-sp-remote',
    'AssertionConsumerService' => [
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            'Location' => 'https://icf.indostarcapital.com/adfs/ls/',
            'index' => 0,
            'isDefault' => true,
        ],
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact',
            'Location' => 'https://icf.indostarcapital.com/adfs/ls/',
            'index' => 1,
        ],
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            'Location' => 'https://icf.indostarcapital.com/adfs/ls/',
            'index' => 2,
        ],
    ],
    'SingleLogoutService' => [
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            'Location' => 'https://icf.indostarcapital.com/adfs/ls/',
        ],
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            'Location' => 'https://icf.indostarcapital.com/adfs/ls/',
        ],
    ],
    'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    'keys' => [
        [
            'encryption' => true,
            'signing' => false,
            'type' => 'X509Certificate',
            'X509Certificate' => 'some string',
        ],
        [
            'encryption' => false,
            'signing' => true,
            'type' => 'X509Certificate',
            'X509Certificate' => 'somestring',
        ],
    ],
    'saml20.sign.assertion' => true,
];

```
**saml20-idp-remote:**
```

$metadata['http://icf.indostarcapital.com/adfs/services/trust'] = [
    'entityid' => 'http://icf.indostarcapital.com/adfs/services/trust',
    'contacts' => [
        [
            'contactType' => 'support',
        ],
    ],
    'metadata-set' => 'saml20-idp-remote',
    'SingleSignOnService' => [
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            'Location' => 'https://icf.indostarcapital.com/adfs/ls/',
        ],
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            'Location' => 'https://icf.indostarcapital.com/adfs/ls/',
        ],
    ],
    'SingleLogoutService' => [
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            'Location' => 'https://icf.indostarcapital.com/adfs/ls/',
        ],
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            'Location' => 'https://icf.indostarcapital.com/adfs/ls/',
        ],
    ],
    'ArtifactResolutionService' => [],
    'NameIDFormats' => [
        'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
        'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
        'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
    ],
    'keys' => [
        [
            'encryption' => true,
            'signing' => false,
            'type' => 'X509Certificate',
            'X509Certificate' => 'some string',
        ],
        [
            'encryption' => false,
            'signing' => true,
            'type' => 'X509Certificate',
            'X509Certificate' => 'somestring',
        ],
    ],
];
```

**Comment by tvdijen** [comment]
Yes, you still need to configure a signing certificate for your own SP and share it with the ADFS-admin

**Comment by ohm1998** [comment]
Noted. I have asked the ADFS admin for certificate files.I have a .crt file already i assume we can convert that into pvt key etc right?

**Comment by tvdijen** [comment]
Uhm, no..  What you have is the public key from ADFS to be able to verify their signed messages..
What you need is exactly the other way around.. You need your own certificate to be able to sign messages towards ADFS.
That's the thing;  ADFS expects signed logout requests and currently you're not signing them.

**Comment by ohm1998** [comment]
> Add these settings to your authsource;
> 
> ```
>         'redirect.sign' => true,
>         'privatekey' => 'example.key',
>         'privatekey_pass' => 'secret',
>         'certificate' => 'example.crt',
> ```

Okay,
I have got cert.pem and privatekey.pem in my /etc/letsencryptfolder

`
'redirect.sign' => true,
        'privatekey' => '/var/simplesaml/cert/private.key',
        'privatekey_pass' => 'secret',
        'certificate' => '/var/simplesaml/cert/server.crt',
`
I don't have the privatekey_pass
I converted .pem to key and crt using the openssl commands:

openssl x509 -outform der -in cert.pem -out server.crt

openssl rsa -outform der -in privkey.pem -out private.key

**Comment by ohm1998** [comment]
`
<?php

$config = array(

    // This is a authentication source which handles admin authentication.
    'admin' => array(
        // The default is to use core:AdminPassword, but it can be replaced with
        // any authentication source.

        'core:AdminPassword',
    ),

        

    // An authentication source which can authenticate against both SAML 2.0
    // and Shibboleth 1.3 IdPs.
    'default-sp' => array(
        'saml:SP',
          
        'redirect.sign' => true,
        'privatekey' => '/var/simplesaml/cert/private.key',
        'privatekey_pass' => 'secret',
        'certificate' => '/var/simplesaml/cert/server.crt', 
      
        // The entity ID of this SP.
        // Can be NULL/unset, in which case an entity ID is generated based on the metadata URL.
        'entityID' => null,
//       'entityID' => "https://indostar.1kosmos.in/default/idp1",

        // The entity ID of the IdP this should SP should contact.
        // Can be NULL/unset, in which case the user will be shown a list of available IdPs.
        'idp' => 'http://icf.indostarcapital.com/adfs/services/trust',
//       'idp' => 'https://indostar.1kosmos.in/default/idp1',

        // The URL to the discovery service.
        // Can be NULL/unset, in which case a builtin discovery service will be used.
        'discoURL' => null,
        'NameIDPolicy' => false,
        /*
         * WARNING: SHA-1 is disallowed starting January the 1st, 2014.
         *
         * Uncomment the following option to start using SHA-256 for your signatures.
         * Currently, SimpleSAMLphp defaults to SHA-1, which has been deprecated since
         * 2011, and will be disallowed by NIST as of 2014. Please refer to the following
         * document for more information:
         *
         * http://csrc.nist.gov/publications/nistpubs/800-131A/sp800-131A.pdf
         *
         * If you are uncertain about identity providers supporting SHA-256 or other
         * algorithms of the SHA-2 family, you can configure it individually in the
         * IdP-remote metadata set for those that support it. Once you are certain that
         * all your configured IdPs support SHA-2, you can safely remove the configuration
         * options in the IdP-remote metadata set and uncomment the following option.
         *
         * Please refer to the hosted SP configuration reference for more information.
          */
        'signature.algorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',

        /*
         * The attributes parameter must contain an array of desired attributes by the SP.
         * The attributes can be expressed as an array of names or as an associative array
         * in the form of 'friendlyName' => 'name'.
         * The metadata will then be created as follows:
         * <md:RequestedAttribute FriendlyName="friendlyName" Name="name" />
         */
        /*'attributes' => array(
            'attrname' => 'urn:oid:x.x.x.x',
        ),*/
        /*'attributes.required' => array (
            'urn:oid:x.x.x.x',
        ),*/
    ),


    /*
    'example-sql' => array(
        'sqlauth:SQL',
        'dsn' => 'pgsql:host=sql.example.org;port=5432;dbname=simplesaml',
        'username' => 'simplesaml',
        'password' => 'secretpassword',
        'query' => 'SELECT uid, givenName, email, eduPersonPrincipalName FROM users WHERE uid = :username AND password = SHA2(CONCAT((SELECT salt FROM users WHERE uid = :username), :password),256);',
    ),
    */

    /*
    'example-static' => array(
        'exampleauth:Static',
        'uid' => array('testuser'),
        'eduPersonAffiliation' => array('member', 'employee'),
        'cn' => array('Test User'),
    ),
    */

    /*
    'example-userpass' => array(
        'exampleauth:UserPass',

        // Give the user an option to save their username for future login attempts
        // And when enabled, what should the default be, to save the username or not
        //'remember.username.enabled' => FALSE,
        //'remember.username.checked' => FALSE,

        'student:studentpass' => array(
            'uid' => array('test'),
            'eduPersonAffiliation' => array('member', 'student'),
        ),
        'employee:employeepass' => array(
            'uid' => array('employee'),
            'eduPersonAffiliation' => array('member', 'employee'),
        ),
    ),
    */

    /*
    'crypto-hash' => array(
        'authcrypt:Hash',
        // hashed version of 'verysecret', made with bin/pwgen.php
        'professor:{SSHA256}P6FDTEEIY2EnER9a6P2GwHhI5JDrwBgjQ913oVQjBngmCtrNBUMowA==' => array(
            'uid' => array('prof_a'),
            'eduPersonAffiliation' => array('member', 'employee', 'board'),
        ),
    ),
    */

    /*
    'htpasswd' => array(
        'authcrypt:Htpasswd',
        'htpasswd_file' => '/var/www/foo.edu/legacy_app/.htpasswd',
        'static_attributes' => array(
            'eduPersonAffiliation' => array('member', 'employee'),
            'Organization' => array('University of Foo'),
        ),
    ),
    */

    /*
    // This authentication source serves as an example of integration with an
    // external authentication engine. Take a look at the comment in the beginning
    // of modules/exampleauth/lib/Auth/Source/External.php for a description of
    // how to adjust it to your own site.
    'example-external' => array(
        'exampleauth:External',
    ),
    */

    /*
    'yubikey' => array(
        'authYubiKey:YubiKey',
         'id' => '000',
        // 'key' => '012345678',
    ),
    */

    /*
    'openid' => array(
        'openid:OpenIDConsumer',
        'attributes.required' => array('nickname'),
        'attributes.optional' => array('fullname', 'email',),
        // 'sreg.validate' => FALSE,
        'attributes.ax_required' => array('http://axschema.org/namePerson/friendly'),
        'attributes.ax_optional' => array('http://axschema.org/namePerson','http://axschema.org/contact/email'),
        // Prefer HTTP redirect over POST
        // 'prefer_http_redirect' => FALSE,
    ),
    */

    /*
    // Example of an authsource that authenticates against Google.
    // See: http://code.google.com/apis/accounts/docs/OpenID.html
    'google' => array(
        'openid:OpenIDConsumer',
        // Googles OpenID endpoint.
        'target' => 'https://www.google.com/accounts/o8/id',
        // Custom realm
        // 'realm' => 'http://*.example.org',
        // Attributes that google can supply.
        'attributes.ax_required' => array(
            //'http://axschema.org/namePerson/first',
            //'http://axschema.org/namePerson/last',
            //'http://axschema.org/contact/email',
            //'http://axschema.org/contact/country/home',
            //'http://axschema.org/pref/language',
        ),
        // custom extension arguments
        'extension.args' => array(
            //'http://specs.openid.net/extensions/ui/1.0' => array(
            //	'mode' => 'popup',
            //	'icon' => 'true',
            //),
        ),
    ),
    */

    /*
    'papi' => array(
        'authpapi:PAPI',
    ),
    */


    /*
    'facebook' => array(
        'authfacebook:Facebook',
        // Register your Facebook application on http://www.facebook.com/developers
        // App ID or API key (requests with App ID should be faster; https://github.com/facebook/php-sdk/issues/214)
        'api_key' => 'xxxxxxxxxxxxxxxx',
        // App Secret
        'secret' => 'xxxxxxxxxxxxxxxx',
        // which additional data permissions to request from user
        // see http://developers.facebook.com/docs/authentication/permissions/ for the full list
        // 'req_perms' => 'email,user_birthday',
    ),
    */

    /*
    // LinkedIn OAuth Authentication API.
    // Register your application to get an API key here:
    //  https://www.linkedin.com/secure/developer
    'linkedin' => array(
        'authlinkedin:LinkedIn',
        'key' => 'xxxxxxxxxxxxxxxx',
        'secret' => 'xxxxxxxxxxxxxxxx',
    ),
    */

    /*
    // Twitter OAuth Authentication API.
    // Register your application to get an API key here:
    //  http://twitter.com/oauth_clients
    'twitter' => array(
        'authtwitter:Twitter',
        'key' => 'xxxxxxxxxxxxxxxx',
        'secret' => 'xxxxxxxxxxxxxxxx',

        // Forces the user to enter their credentials to ensure the correct users account is authorized.
        // Details: https://dev.twitter.com/docs/api/1/get/oauth/authenticate
        'force_login' => FALSE,
    ),
    */

    /*
    // MySpace OAuth Authentication API.
    // Register your application to get an API key here:
    //  http://developer.myspace.com/
    'myspace' => array(
        'authmyspace:MySpace',
        'key' => 'xxxxxxxxxxxxxxxx',
        'secret' => 'xxxxxxxxxxxxxxxx',
    ),
    */

    /*
    // Microsoft Account (Windows Live ID) Authentication API.
    // Register your application to get an API key here:
    //  https://apps.dev.microsoft.com/
    'windowslive' => array(
        'authwindowslive:LiveID',
        'key' => 'xxxxxxxxxxxxxxxx',
        'secret' => 'xxxxxxxxxxxxxxxx',
    ),
    */

    /*
    // Example of a LDAP authentication source.
    'example-ldap' => array(
        'ldap:LDAP',

        // Give the user an option to save their username for future login attempts
        // And when enabled, what should the default be, to save the username or not
        //'remember.username.enabled' => FALSE,
        //'remember.username.checked' => FALSE,

        // The hostname of the LDAP server.
        'hostname' => 'ldap.example.org',

        // Whether SSL/TLS should be used when contacting the LDAP server.
        'enable_tls' => TRUE,

        // Whether debug output from the LDAP library should be enabled.
        // Default is FALSE.
        'debug' => FALSE,

        // The timeout for accessing the LDAP server, in seconds.
        // The default is 0, which means no timeout.
        'timeout' => 0,

        // The port used when accessing the LDAP server.
        // The default is 389.
        'port' => 389,

        // Set whether to follow referrals. AD Controllers may require FALSE to function.
        'referrals' => TRUE,

        // Which attributes should be retrieved from the LDAP server.
        // This can be an array of attribute names, or NULL, in which case
        // all attributes are fetched.
        'attributes' => NULL,

        // The pattern which should be used to create the users DN given the username.
        // %username% in this pattern will be replaced with the users username.
        //
        // This option is not used if the search.enable option is set to TRUE.
        'dnpattern' => 'uid=%username%,ou=people,dc=example,dc=org',

        // As an alternative to specifying a pattern for the users DN, it is possible to
        // search for the username in a set of attributes. This is enabled by this option.
        'search.enable' => FALSE,

        // The DN which will be used as a base for the search.
        // This can be a single string, in which case only that DN is searched, or an
        // array of strings, in which case they will be searched in the order given.
        'search.base' => 'ou=people,dc=example,dc=org',

        // The attribute(s) the username should match against.
        //
        // This is an array with one or more attribute names. Any of the attributes in
        // the array may match the value the username.
        'search.attributes' => array('uid', 'mail'),

        // The username & password the SimpleSAMLphp should bind to before searching. If
        // this is left as NULL, no bind will be performed before searching.
        'search.username' => NULL,
        'search.password' => NULL,

        // If the directory uses privilege separation,
        // the authenticated user may not be able to retrieve
        // all required attribures, a privileged entity is required
        // to get them. This is enabled with this option.
        'priv.read' => FALSE,

        // The DN & password the SimpleSAMLphp should bind to before
        // retrieving attributes. These options are required if
        // 'priv.read' is set to TRUE.
        'priv.username' => NULL,
        'priv.password' => NULL,

    ),
    */

    /*
    // Example of an LDAPMulti authentication source.
    'example-ldapmulti' => array(
        'ldap:LDAPMulti',

        // Give the user an option to save their username for future login attempts
        // And when enabled, what should the default be, to save the username or not
        //'remember.username.enabled' => FALSE,
        //'remember.username.checked' => FALSE,

        // The way the organization as part of the username should be handled.
        // Three possible values:
        // - 'none':   No handling of the organization. Allows '@' to be part
        //             of the username.
        // - 'allow':  Will allow users to type 'username@organization'.
        // - 'force':  Force users to type 'username@organization'. The dropdown
        //             list will be hidden.
        //
        // The default is 'none'.
        'username_organization_method' => 'none',

        // Whether the organization should be included as part of the username
        // when authenticating. If this is set to TRUE, the username will be on
        // the form <username>@<organization identifier>. If this is FALSE, the
        // username will be used as the user enters it.
        //
        // The default is FALSE.
        'include_organization_in_username' => FALSE,

        // A list of available LDAP servers.
        //
        // The index is an identifier for the organization/group. When
        // 'username_organization_method' is set to something other than 'none',
        // the organization-part of the username is matched against the index.
        //
        // The value of each element is an array in the same format as an LDAP
        // authentication source.
        'employees' => array(
            // A short name/description for this group. Will be shown in a dropdown list
            // when the user logs on.
            //
            // This option can be a string or an array with language => text mappings.
            'description' => 'Employees',

            // The rest of the options are the same as those available for
            // the LDAP authentication source.
            'hostname' => 'ldap.employees.example.org',
            'dnpattern' => 'uid=%username%,ou=employees,dc=example,dc=org',
        ),

        'students' => array(
            'description' => 'Students',

            'hostname' => 'ldap.students.example.org',
            'dnpattern' => 'uid=%username%,ou=students,dc=example,dc=org',
        ),

    ),
    */

);


`

This is how the authsources.php looks like after adding the variables.

**Comment by tvdijen** [comment]
You can't use DER-formatted certificates, only PEM-formatted certificates can work

**Comment by ohm1998** [comment]
> You can't use DER-formatted certificates, only PEM-formatted certificates can work

can i directly replace example.key and example.crt with .pem files?

**Comment by tvdijen** [comment]
Yes, should work

**Comment by ohm1998** [comment]
On adding the following to authsources.php

`
 'redirect.sign' => true,
        'privatekey' => '/var/simplesaml/cert/privkey.pem',
        'certificate' => '/var/simplesaml/cert/cert.pem', 
`

I get this error for login : 
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML\Module\saml\Error: Responder
Backtrace:
4 modules/saml/lib/Message.php:503 (SimpleSAML\Module\saml\Message::getResponseError)
3 modules/saml/lib/Message.php:635 (SimpleSAML\Module\saml\Message::processResponse)
2 modules/saml/www/sp/saml2-acs.php:145 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)
```

Do I need to again check on the ADFS server for this?

**Comment by tvdijen** [comment]
Yes, ADFS has to process your metadata again because it has changed

**Comment by ohm1998** [comment]
> Yes, ADFS has to process your metadata again because it has changed

I have to pass on the .pem files to the ADFS server config for my website correct?

**Comment by tvdijen** [comment]
Only the certificate, not the private key

**Comment by ohm1998** [comment]
> Only the certificate, not the private key

Noted

**Comment by tvdijen** [comment]
Have you figured it out? What's the status?

**Comment by ohm1998** [comment]
Still trying to contact the ADFS admin, might take a couple of days more.

**Comment by ohm1998** [comment]
Hey talked to the admin.
They seem to be adamant about the logout issue and 

I have to make my own login form (currently the login form comes from the adfs server).
So the login and logout sessions will be handled by my app and only auth will take place through the adfs.

Is it possible to set up a custom login page and get the creds authenticated via ajax using simplesamlphp?

Here's the current index.php code

```
<?php 

  session_start();
  include("model/config.php");
  require_once("./../../simplesaml/lib/_autoload.php");
  $as = new SimpleSAML_Auth_Simple('default-sp');

  $as->requireAuth();

  $attributes = $as->getAttributes();

  SimpleSAML_Session::getSessionFromRequest()->cleanup();
  foreach($attributes as $key => $value)
  {
    $_SESSION[end(explode("/",$key))] = $value[0];
  }

 //Skipped the code for getting the values(attributes) into session 
?>
```

**Comment by tvdijen** [comment]
No, that kinda defeats the whole purpose of federated authentication... If your IDP admin is not cooperating you're doomed
