### ISSUE TITLE
SP Metadata Gives 403 Forbidden Error

### ISSUE THREAD

**Issue by bhavikshah92** [simplesamlphp/simplesamlphp#1494]
I have connected SimpleSAMLPHP with Azure Active Directory and It's working fine.

But I just wanted to try to generate the SP Metadata and request for some additional attributes just for learning purpose, but while clicking on **Show Metadata(default-sp)** in Federation Tab it redirects me to _saml/www/module.php/saml/sp/metadata.php/default-sp?output=xhtml_ but it gives me 403 Forbidden Error.

![image](https://user-images.githubusercontent.com/12729601/128677955-b440cb7c-38d0-4410-b262-4dc0c99c8503.png)

**Comment by tvdijen** [comment]
Then you haven't properly configured your webserver..

**Comment by thijskh** [comment]
This is indeed not an error from SimpleSAMLphp so not much we can do about it
