### ISSUE TITLE
Data store MySQL over SSL

### ISSUE THREAD

**Issue by vanakool1001** [simplesamlphp/simplesamlphp#1498]
Hello everyone!

I have a problem with configuring PDO options for MySQL SSL connection. SimpleSAMLphp is running besides MediaWiki.

Anyway, I've added the following lines...

'store.sql.options' => array(
        array(\PDO::MYSQL_ATTR_SSL_CA => '/home/site/ssl/BaltimoreCyberTrustRoot.crt.pem'),
        array(\PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false),
	array(\PDO::MYSQL_ATTR_SSL_KEY => '/home/site/ssl/server_key.pem'),
        array(\PDO::MYSQL_ATTR_SSL_CERT => '/home/site/ssl/server_cert.pem'),
	),

after the

**store.type**,
**store.sql.dsn**,
**store.sql.username**,
**store.sql.password**
and
**store.sql.prefix**

Yet I still don't understand why SimpleSAMLphp is reporting the following to me:

[cc9186b211448d53e3bf03d9] /index.php/Toiminnot:PluggableAuthLogin Exception from line 67 of /home/site/wwwroot/simplesamlphp/lib/SimpleSAML/Store/SQL.php: Database error: SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry.

Backtrace:

#0 /home/site/wwwroot/simplesamlphp/lib/SimpleSAML/Store.php(52): SimpleSAML\Store\SQL->__construct()
#1 /home/site/wwwroot/simplesamlphp/lib/SimpleSAML/SessionHandler.php(138): SimpleSAML\Store::getInstance()
#2 /home/site/wwwroot/simplesamlphp/lib/SimpleSAML/SessionHandler.php(43): SimpleSAML\SessionHandler::createSessionHandler()
#3 /home/site/wwwroot/simplesamlphp/lib/SimpleSAML/Session.php(332): SimpleSAML\SessionHandler::getSessionHandler()
#4 /home/site/wwwroot/simplesamlphp/lib/SimpleSAML/Session.php(263): SimpleSAML\Session::getSession()
#5 /home/site/wwwroot/simplesamlphp/lib/SimpleSAML/Auth/Simple.php(53): SimpleSAML\Session::getSessionFromRequest()
#6 /home/site/wwwroot/extensions/SimpleSAMLphp/includes/SimpleSAMLphp.php(209): SimpleSAML\Auth\Simple->__construct(string)
#7 /home/site/wwwroot/extensions/SimpleSAMLphp/includes/SimpleSAMLphp.php(104): SimpleSAMLphp::getSAMLClient()
#8 /home/site/wwwroot/extensions/PluggableAuth/includes/PluggableAuthLogin.php(36): SimpleSAMLphp->authenticate(NULL, NULL, NULL, NULL, NULL)
#9 /home/site/wwwroot/includes/specialpage/SpecialPage.php(600): PluggableAuthLogin->execute(NULL)
#10 /home/site/wwwroot/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run(NULL)
#11 /home/site/wwwroot/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath(Title, RequestContext)
#12 /home/site/wwwroot/includes/MediaWiki.php(940): MediaWiki->performRequest()
#13 /home/site/wwwroot/includes/MediaWiki.php(543): MediaWiki->main()
#14 /home/site/wwwroot/index.php(53): MediaWiki->run()
#15 /home/site/wwwroot/index.php(46): wfIndexMain()
#16 {main}

Am I doing something wrong or why is it not taking the specified options in account?

Everything works well if I disable the SSL requirement in MySQL database, but that is not a solution.

**Comment by tvdijen** [comment]
9002 indicates a mismatch in server/client TLS-version used..

**Comment by vanakool1001** [comment]
> 
> 
> 9002 indicates a mismatch in server/client TLS-version used..

**Comment by vanakool1001** [comment]
> 
> 
> 9002 indicates a mismatch in server/client TLS-version used..

I now tried to lower the MySQL server minimum required TLS version from 1.2 to 1.0, but the issue persists

NB! Don't mind the "case closed" and "case opened", I accidentally did that

**Comment by tvdijen** [comment]
So, why are you wrapping each option in an array? I think it  should be like this;

```
'store.sql.options' => [
\PDO::MYSQL_ATTR_SSL_CA => '/home/site/ssl/BaltimoreCyberTrustRoot.crt.pem',
\PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
\PDO::MYSQL_ATTR_SSL_KEY => '/home/site/ssl/server_key.pem',
\PDO::MYSQL_ATTR_SSL_CERT => '/home/site/ssl/server_cert.pem',
],
```

**Comment by vanakool1001** [comment]
> 
> 
> So, why are you wrapping each option in an array? I think it should be like this;
> 
> ```
> 'store.sql.options' => [
>     \PDO::MYSQL_ATTR_SSL_CA => '/home/site/ssl/BaltimoreCyberTrustRoot.crt.pem',
>     \PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false,
>     \PDO::MYSQL_ATTR_SSL_KEY => '/home/site/ssl/server_key.pem',
>     \PDO::MYSQL_ATTR_SSL_CERT => '/home/site/ssl/server_cert.pem',
> ],
> ```

Tried that also now, but issue still persists unfortunately

**Comment by tvdijen** [comment]
And what do the mysql-logs say?

**Comment by vanakool1001** [comment]
I commented out the last two options and it works now

**Comment by vanakool1001** [comment]
Ohh and I left the VERIFY_SERVER_CERT back to **true** :)

Left it to **false** for testing purposes only
