### ISSUE TITLE
Remove deprecated SAML SP code, in www/saml2/sp and www/shib13/sp (was #275)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#15]
_From [andreass...@gmail.com](https://code.google.com/u/102889613336421617108/) on January 26, 2010 12:45:37_

Remove depdecated SAML SP code, in www/saml2/sp and www/shib13/sp

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=275_

**Comment by jaimeperez** [comment]
More specifically:

* `www/saml2/sp/`
  * `metadata.php` which has the following dependencies:
    * `lib/SimpleSAML/Metadata/MetaDataStorageHandlerFlatFile.php:125`
    * `modules/core/www/frontpage_federation.php:83`
  * `AssertionConsumerService.php`
  * `SingleLogoutService.php`
  * `idpdisco.php`
  * `initSLO.php`
  * `initSSO.php`
* `www/shib13/sp/`
  * `metadata.php`
  * `AssertionConsumerService.php`
  * `idpdisco.php`
  * `initSSO.php`
* `www/wsfed/sp/`
  * `idpdisco.php`
  * `initSLO.php`
  * `initSSO.php`
  * `prp.php`
