### ISSUE TITLE
Remove the SimpleSAML_Auth_Default class

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#151]
This one is tricky, as there's lots of code currently in use. Try to reallocate those parts into `SimpleSAML_Auth_Source` and `SimpleSAML_Session`.

**Comment by jaimeperez** [comment]
The class has been deprecated now, all the code in use reallocated, and nothing points to it any longer.

**Comment by tvdijen** [comment]
We should be able to safely remove this after 3yrs of deprecation
