### ISSUE TITLE
Facing Error "Caused by: SimpleSAML\Error\Exception: Error decrypting assertion: No private key found in metadata."

### ISSUE THREAD

**Issue by ohm1998** [simplesamlphp/simplesamlphp#1519]
Facing the following error on login : 

```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML\Error\Exception: Error decrypting assertion: No private key found in metadata.
Backtrace:
5 modules/saml/lib/Message.php:422 (SimpleSAML\Module\saml\Message::decryptAssertion)
4 modules/saml/lib/Message.php:691 (SimpleSAML\Module\saml\Message::processAssertion)
3 modules/saml/lib/Message.php:659 (SimpleSAML\Module\saml\Message::processResponse)
2 modules/saml/www/sp/saml2-acs.php:145 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)
```

Am I missing out on any config?

**Comment by tvdijen** [comment]
Probably `privatekey` in your SP authsource configuration.

**Comment by ohm1998** [comment]
Works!
thankyou!

**Comment by murraycollingwood** [comment]
I'm getting the same error, but I don't understand what the solution here was.  
I don't believe the iDP is supposed to upload the private key to the SP.
Similarly, the metadata from the iDP shouldn't contain a private key.
Similarly, the metadata from the SP won't contain any private key.

So, can somebody help explain why we are missing a privatekey?

**Comment by tvdijen** [comment]
This is about symmetric encryption where both IdP and SP share a secret passphrase. The exception message is a bit misleading, because you obviously don't share this in metadata.. It does have to be configured in the SP authsource though

**Comment by murraycollingwood** [comment]
I should preface this with a rather substantial AFAIK.

Thanks Tim, but there is an easy way to solve this problem, and it's good to document it here.
The SAML conversation takes place over an SSL connection, so everything is encrypted.  
Somehow the SAML designers determined that they should add an additional layer of security for the assertions, although this is simply an encryption layer on top of another encryption layer.

If you follow the channels I do you will be reasonably confident that the encryption we use (eg SHA-256) is pretty strong and as yet does not feature in any hacking events.  So a single layer of encryption is still quite adequate for most people's needs.  

So, knowing that our assertion are already protected by the SSL encryption, we don't really need a second layer of encryption on top of this.  Fortunately SAML does provide us an option, whether we want to add the additional encryption on these assertions.  The good news is, it can be turned off.

In my configuration metadata I have the following:
```
// Add a default entry 
$data = array(
	"assertion.encryption" => FALSE
);
```

ADFS has an option to disable assertion encryption, I'm recommending this as the simplest option:
```
Follow these steps in Active Directory Federation Services (ADFS):
Expand Trust Relationships folder and click on Relying Party Trusts
Right click the SOBS relying party (or whatever you may have named it) and select Properties.
Click the Encryption tab. Click Remove to remove the certificate for encryption.
Hit OK to close out the screens.
```

We disabled the assertion encryption on the ADFS server and then the error message disappeared and the SAML authentication worked.

If you want to enable the assertion encryption you can, but you need to include your private key in one of those conf-simplesamlphp/metadata/saml*.php files. Sorry, I'm not sure which one.  If you know perhaps you could reply to this comment.

I hope this helps others.  (PS It will probably help me again in the future when I google for this solution in another year or two).

Cheers
Murray

**Comment by tvdijen** [comment]
I'm not sure what channels you are following, but the general consensus in the world of SAML is that encryption of assertions is necessary evil;

To quote the Kantara initiative:

> While encryption is viewed in some quarters as onerous or unnecessary, interoperability is enhanced by uniformity. Moreover, a spate of recent vulnerabilities across the industry would have been almost entirely mitigated by its use, demonstrating that it is no longer acceptable to view it as an optional part of front-channel delivery of assertions, if it ever was.

Also, you still need to set a private key to sign your metadata and/or AuthnRequests

**Comment by murraycollingwood** [comment]
Some channel examples:
https://www.componentspace.com/forums/8819/is-it-required-to-encrypted-the-assertion-in-idp-sso-response-what-is-the-benefit-of-encrypting-the-
https://security.stackexchange.com/questions/204667/saml-assertion-encryption-and-using-same-key-for-encryption-as-signing
https://support.pingidentity.com/s/article/PingOne-How-to-disable-assertion-encryption-in-ADFS
https://www.componentspace.com/Forums/8819/Is-it-required-to-encrypted-the-Assertion-in-IDP-SSO-Response-What-is-the-benefit-of-encrypting-the-?Keywords=ServiceProvider+initiate+SSO%2C+ADFS+identityProvider%2C+re-authenticate+every+%7E2min%3FJumpToFirstUnreadPost%3D1
https://support.umbrella.com/hc/en-us/articles/230649267-Cisco-Umbrella-SAML-Integration-ADFS-3-0-Integration-Instructions
https://support.panopto.com/s/article/adfs-saml-integration
https://help.mypurecloud.com/articles/add-microsoft-adfs-single-sign-provider/

Some of the above are specific applications that don't support AssertionEncryption.
The more I read about the AssertionEncryption, is that the encryption happens automatically from the iDP (which is often passing the attributes) but is optional for the SP (as it frequently does not pass any information to the iDP).  We certainly don't pass any attributes back to the iDP, so there is little reason to encrypt an empty string.

Am I understanding this correctly?  Maybe I'm wrong, I have been wrong before.

**Comment by tvdijen** [comment]
ADFS IdP's will do this automatically if the metadata provided by an SP contains an encryption cert. Other products may require some configuration.
