### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by AdrianPascual2020** [simplesamlphp/simplesamlphp#1521]
Hello,

I am using this package https://github.com/simplesamlphp/simplesamlphp | https://packagist.org/packages/simplesamlphp/simplesamlphp#dev-master with composer

Currently I use PHP 8 but version 1.19.1 I cannot use it since it does not allow PHP 8. In your case I am using the "dev-master" version temporarily but I don't like to use it. Are you going to publish a version to allow PHP 8? or is there a version that allows PHP 8 other than the one mentioned?

Thank you.
Excuse my English.
All the best.

**Comment by tvdijen** [comment]
Hi Adrian!  We're working really hard on releasing version 2.0 based on the current master-branch.
I'm expecting this release towards the end of this year..

You can also run 1.19.1 with PHP8 if you use `composer install --ignore-platform-reqs`.. Should work just fine.

**Comment by tvdijen** [comment]
Currently the only known issue with 1.19 + PHP 8.0 is with database storage;
https://github.com/simplesamlphp/simplesamlphp/pull/1422/commits/ea7c23a11b7b64f6d96f3c6719f2d390fd47a50f

**Comment by AdrianPascual2020** [comment]
Hello again,

good news. Thanks for that version 2.
It worked for me correctly with --ignore-platform-reqs

Thank you very much for the quick response and a weekend.
All the best.

**Comment by RickKukiela** [comment]
Can anyone confirm that the latest 1.19.x is also compatible with php8.1 with `--ignore-platform-reqs`?

**Comment by tvdijen** [comment]
It's not

**Comment by RickKukiela** [comment]
@tvdijen Do you have any idea when it will be compatible or if 2.0 will be compatible and when that will be released? 7.x is hitting EOL in under 2 months and we're planning on going straight to 8.1 on our server...

**Comment by tvdijen** [comment]
The deal-breaker right now is https://github.com/simplesamlphp/saml2/issues/295 and the fact that none of us understands what the frag is going on there.
If we can solve that, we can fix PHP 8.1 support for both 1.19.x and 2.0 transparently

**Comment by safetypins** [comment]
> It's not

Release 1.19.2 (October 27, 2021) says it restored compatibility with 8.0, and it's working with PHP v8.0.24 in my staging environment: https://simplesamlphp.org/docs/stable/simplesamlphp-changelog.html

Is this a temporary workaround? I see the issue you mentioned is still open, but v1.19.4 (October 13, 2021) includes the note `The library has been quick-fixed to support PHP 8.1 (#1545)`.

**Comment by tvdijen** [comment]
We thought we had fixed it in 1.19.4, but we didn't. We have had several reports of issues.

**Comment by RickKukiela** [comment]
FTR I believe I got the 2.x-RC working on 8.1 in production. I have not had any reports. Its installed as an SP, but I have an IDP version set up locally for testing against the SP and that is also running on 8.1 locally.

**Comment by safetypins** [comment]
@tvdijen Has this been resolved in 1.19.7 (to the best of your knowledge, of course)? That's amazing! Thanks so much for all your work on this!

**Comment by tvdijen** [comment]
Should be, yes! Please let us know if you run into any issues
