### ISSUE TITLE
How authenticate an application inside an iframe

### ISSUE THREAD

**Issue by ebz-jeaanmichel** [simplesamlphp/simplesamlphp#1535]
Hello,

We have an application, I will call App2, running inside an another application (App1) in a iframe, both applications are running in different domains. 

So, the use case is: 

1. The user clicks in a button on App1;
2. App1 redirects the user to authenticate in SimpleSamlPHP;
3. SimpleSamlPHP autheticates the user and redirects to App1;
**4. And finally, App2 needs to authenticate the user without redirect to SimpleSamlPHP;**

What is the best approach for step 4?

Best regards.

**Comment by tvdijen** [comment]
This is an issue tracker, not a support forum. Please divert your questions to one of our [mailing lists](https://simplesamlphp.org/lists).
