### ISSUE TITLE
HTTP 2.0 Infinite Redirects from HTTP 302 Response

### ISSUE THREAD

**Issue by orangejuice23123** [simplesamlphp/simplesamlphp#1537]
An infinite redirect loop occurs on login with HTTP 2.0 enabled. 

In [lib/SimpleSAML/Utils/HTTP.php#redirect](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/HTTP.php#L233) there is a check for HTTP/1.1 that sets the header HTTP 303. With HTTP 2.0 enabled, the header HTTP 302 is set and an infinite redirect loop occurs on login. 

Is HTTP 2.0 unsupported? 
Any repercussions from patching a HTTP/2.0 check?

Configuration:
- simplesaml: 1.17.2
- PHP: 7.3.32
- nginx: 1.20.1

**Comment by tvdijen** [comment]
Could you give it a try to add `|| $_SERVER['SERVER_PROTOCOL'] === 'HTTP/2.0'` and see if that works for you?

**Comment by tvdijen** [comment]
I was able to track this line of code back to 14 yrs ago..  https://github.com/simplesamlphp/simplesamlphp/commit/4760be6915bf4611898abdee9ce81c14abd8d7f5

It is my wild guess that something changed between HTTP/1.0 and HTTP/1.1 that required this.. If we could figure out what it was exactly, then we may be able to solve this in a more clever way.

**Comment by tvdijen** [comment]
Interesting post; https://stackoverflow.com/questions/5129076/after-a-post-should-i-do-a-302-or-a-303-redirect

**Comment by tvdijen** [comment]
So, from what I'm reading, we should use 302 for HTTP POST version <= 1.0 and 303 for anything else.

**Comment by tvdijen** [comment]
The fix is pending review.. I'm still not sure why HTTP/2.0 would fail on a 302 code though

**Comment by thijskh** [comment]
I think the whole distinction get/post and 1.0 is completely unnecessary now. Just drop all the legacy and if’s and always send 303.

**Comment by tvdijen** [comment]
Uhm, well, apparently according to the TS, a 303 + HTTP/2.0 leads to an infinite loop where a 302 doesn't..
I've discussed this with Jaime tonight and we both cannot see why, and in general agree with you @thijskh .. But we should figure this out

**Comment by tvdijen** [comment]
@thijskh I agree on the 303, but what about the distinction between GET/POST.. I've discussed this with Jaime tonight and we both are unsure of the consequences, even though we fully agree with your opinion.. It just needs some testing.

**Comment by tvdijen** [comment]
Ok the HTTP/2 discussion can be cleared... "About 97% of web browsers used have the capability" - Wikipedia is always right..
The distinction between GET/POST is still an uncertainty to me..

**Comment by thijskh** [comment]
There's no need to even have the HTTP/2.0 capability. You just don't need to break on 303. So you need to have HTTP/1.1 compatibility. Which is everything.

I'm not sure what the problem would be with GET. If you change to GET after GET it's still GET. So 303 does not change a thing there so can safely be sent.

**Comment by orangejuice23123** [comment]
We're still investigating the issue, but tvdijen you were correct that the 302 response was not the cause of the infinite redirects.

**Comment by tvdijen** [comment]
Those infinite redirects are usually related to session management and/or cookies. Since you're running an old 1.17.x version, it could be that your issue is with the sameSite-flag on the session cookie..

**Comment by orangejuice23123** [comment]
Thank you for your help! 

In the end, the redirect loop was an nginx configuration issue. At least this lead to a slight codebase improvement.

Here's our working configuration if it helps anyone in the future:

```
location ^~ /simplesaml {
    alias $document_root/simplesaml/www;

    location ~ \.php(/|$) {
      include fastcgi_params;
      fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
      fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
      fastcgi_param SCRIPT_FILENAME $request_filename;
      fastcgi_param PATH_INFO $fastcgi_path_info if_not_empty;
    }
 }
```

**Comment by tvdijen** [comment]
Oh please, if you can improve our Ngynx docs!  https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-install.md#configuring-nginx

Although they can be very specific to your setup

**Comment by orangejuice23123** [comment]
Sorry we don't have anything to contribute. We based our configuration from another thread https://github.com/simplesamlphp/simplesamlphp/issues/751#issuecomment-789059253
