### ISSUE TITLE
Office365 refuses assertions with saml:AuthenticatingAuthority

### ISSUE THREAD

**Issue by enricocavalli** [simplesamlphp/simplesamlphp#1539]
Please, keep in mind that I'm completely missing the full meaning of what I am reporting below. I just "implemented" a quick and dirty workaround.

**Office365 assertion malformed when using external IDP as authentication source**

While experimenting with a second authentication source configured as external IDP, assertion from my SimpleSAMLphp IDP are
not accepted by Office365 federation with a generic error

```
AADSTS500132: Assertion is malformed and cannot be read.
```

**Expected behavior**
Maybe an option to remove saml:AuthenticatingAuthority ?

**Additional context**
I empirically observed that Office365 refuses to validate assertions containing 

 ```
 <saml:AuthenticatingAuthority>ENTITY_ID_OF_EXTERNAL_IDP</saml:AuthenticatingAuthority>
```

and wrote an ugly authentication processing filter that basically removes that information from assertions

```
unset($state['saml:sp:State']['saml:AuthenticatingAuthority']);
unset($state['saml:sp:State']['PersistentAuthData']['saml:AuthenticatingAuthority']);
```

It works but I absolutely don't know if I'm doing the right thing.

**Comment by tvdijen** [comment]
Did you see this behaviour when accessing  portal.azure.com ?

**Comment by enricocavalli** [comment]
I just reproduced the issue, disabling the proc filter, and starting with a fresh browser session and yes, it happens with portal.azure.com too.

If you think this can be beneficial to SimpleSAML, I'll ask the University involved to open an issue with Microsoft.  I was not able to find a similar case anywhere.

Thank you,
Enrico.

**Comment by tvdijen** [comment]
I've had portal.azure.com working with OpenConext which, I know for 100% certain, releases the AuthenticatingAuthority in their assertions, so this may just be a bug in Azure..

Even if Microsoft doesn't use the element, it shouldn't throw an exception but just ignore it!
"Ignore what you don't understand" is one of the primary rules in XML-parsing..

**Comment by thijskh** [comment]
We always send authenticating authority and this works for us with Office 356. So it must be more subtle than the need to leave out the entire block.

Can you give us the actual content of your AuthenticatingAuthority instead of the redacted version you posted above?

**Comment by enricocavalli** [comment]
AuthenticatingAuthority is the only significant difference I can spot while using this auth source vs default one (ldap).

This is what I'm getting 
```
            <saml:AuthnContext>        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
                <saml:AuthenticatingAuthority>9hbwwk2rnpn1</saml:AuthenticatingAuthority>
            </saml:AuthnContext>
```

where that string is actually the entity ID of an RSA IDP used to test their 2FA solution

```
$metadata['9hbwwk2rnpn1'] = [
    'entityid' => '9hbwwk2rnpn1',
...
    'contacts' => [],
    'metadata-set' => 'saml20-idp-remote',
    'SingleSignOnService' => [
        [
            'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            'Location' => 'https://rsa.iulm.it/IdPServlet?idp_id=9hbwwk2rnpn1',
        ],
    ],
...
```

**Comment by tvdijen** [comment]
Your entityID is not a valid [URI](https://en.wikipedia.org/wiki/Uniform_Resource_Identifier).. That may be something you can change to test if it makes any difference?

**Comment by enricocavalli** [comment]
I tried doing that in a naive way ( doing a replace of the value instead of the "unset") but probably entityID in metadata must match. Or at least I'm not able to do it with my limited knowledge.

 I will ask the guys who manage the RSA server if they can change the format of the entityID
Thank you for all replies.

**Comment by tvdijen** [comment]
They should be able, because I am not aware of any product that doesn't have this possibility..  It may have consequences depending on how many SP-trusts the IdP has, but following the specs it should be a URI.  Microsoft sometimes can be _very_strict in specs or leave them all together, that's why I suspect something like this is a probable cause.

**Comment by thijskh** [comment]
Yes, I suspect that the entityID not being an uri breaks it. MS products tend to do that.

**Comment by enricocavalli** [comment]
Unfortunately the University involved does not want to modify the entityid right now, but given all replies I think the problem is clear and the issue may be closed. Thank you all again.
