### ISSUE TITLE
Unable to generate metadata for the IDP

### ISSUE THREAD

**Issue by murraycollingwood** [simplesamlphp/simplesamlphp#1544]
When trying to generate the metadata download I am getting a blank screen.  I'm not going to include a screen shot as I'm sure you know exactly what a blank screen looks like.
The URL I'm using is below (the URL includes a schoolid to identify a particular school client to the application - this is required): 
`https://sobs.com.au/simplesaml/module.php/saml/sp/metadata.php/sobs-sp?schoolid=1417
`
Previously, using this same URL, SSP would generate an XML document to my browser window that could be loaded back to the IDP to complete the configuration.  I'm not sure when it stopped working, but it has been a few months since I last used this option.

Tonight I upgraded SSP from 1.19.1 to 1.19.3 (using composer) and the problem still exists.  I'm using these settings:
```
       "simplesamlphp/simplesamlphp": ">=1.19",
       "simplesamlphp/simplesamlphp-module-metarefresh": "@stable",

```

In the config.php file I found these settings, I'm fairly sure these are the only ones related to the metadata generation:
```
    'metadata.sources' => [
        [
          'type' => 'flatfile',
          'directory' => '../../../simplesamlphp/dev/metadata/',
        ],
      ],

```

In August / September this year I was implementing the metarefresh module, I'm fairly sure it was working prior to this update, but I don't think I have used it since.  So it may or may not have anything to do with changes made at that time.

I have checked the server logs but I can't find any messages regarding any errors or problems.  
I had a quick look for a debug option but couldn't find any.

Are you able to help me get this metadata generation working again please?

Cheers
Murray

**Comment by tvdijen** [comment]
Known issue with this version;  https://github.com/simplesamlphp/simplesamlphp/issues/1533
You can either wait for 1.19.4 to be released or manually fix the version of the metarefresh-module by running `composer require simplesamlphp/simplesamlphp-module-metarefresh:^0.9`

**Comment by murraycollingwood** [comment]
Composer gave me these results:
```
Package operations: 0 installs, 4 updates, 0 removals
  - Downgrading simplesamlphp/simplesamlphp (v1.19.3 => v1.19.1): Extracting archive
  - Removing simplesamlphp/simplesamlphp-module-metarefresh (v1.0.0)
  - Downgrading simplesamlphp/simplesamlphp-module-discopower (v0.10.1 => v0.9.1): Extracting archive
  - Upgrading simplesamlphp/saml2 (v4.2.3 => v4.2.4): Extracting archive
 0/4 [>---------------------------]   0%  - Installing simplesamlphp/simplesamlphp-module-metarefresh (v0.9.6): Extracting archive
    Failed to extract simplesamlphp/simplesamlphp-module-metarefresh: (9) '/usr/bin/unzip' -qq '/home/sobs/vendor/composer/tmp-04efe5e70febae311962f4b170d946b5' -d '/home/sobs/vendor/composer/965e45c7'

unzip:  cannot find or open /home/sobs/vendor/composer/tmp-04efe5e70febae311962f4b170d946b5.

    This most likely is due to a custom installer plugin not handling the returned Promise from the downloader
    See https://github.com/composer/installers/commit/5006d0c28730ade233a8f42ec31ac68fb1c5c9bb for an example fix

```

I'm still getting no output from the metadata generation.
Sorry.

**Comment by tvdijen** [comment]
Oh, you were on 1.19.1 when it happened? I thought after upgrading..
A white screen indicated a PHP fatal error and should show up in your logs.. Depending on your configuration, either the system log (i.e. /var/log/messages), the Apache or Ngynx logs, or PHP logs

**Comment by murraycollingwood** [comment]
In order to enable customers to login I reverted to my previous setting:
```
       "simplesamlphp/simplesamlphp": "dev-php-session-handler-1.19",
       "simplesamlphp/simplesamlphp-module-metarefresh": "@stable",

```

Currently nobody can log in:
```
[7-12-21 6:49am] [0]: Uncaught exception "SimpleSAML\Error\Exception" with message "Could not find the metadata of an IdP with entity ID 'https://sts.windows.net/5c3b69f7-9c59-4b27-8042-6520b514571c/'" in /home/sobs/vendor/simplesamlphp/simplesamlphp/modules/saml/lib/Auth/Source/SP.php on line 317 school=[null] username=[null]

```

Is there any stable configuration I can use currently?
I'm running Debian Linux with Apache2 and PHP 7.3

Thanks for your help.

**Comment by murraycollingwood** [comment]
I had changed one other parameter, the metadata sources:

```
 'metadata.sources' => [
        [
          'type' => 'flatfile',
          'directory' => '../../../simplesamlphp/dev/metadata/',
        ],
      ],

```

I removed the 'directory' entry from this and the login is once again working.

Unfortunately I am back where I started - I am unable to generate any metadata - I'm still getting a blank screen.

**Comment by tvdijen** [comment]
What happens if you leave out the schoolid from the url?  That seems like something you've added yourself...
Also, can you verify that you receive an HTTP/50x on the blank screen? If so, there should be something logged..

**Comment by murraycollingwood** [comment]
Hi Tim

The schoolid is required for our application as it identifies which metadata to access.  (The metadata settings are stored in a database and we load these dynamically when SSP starts).

There are no 50x errors or any other error messages appearing anywhere I can find.  I've checked my application error log, the generic access logs, and other php logs.  The access log shows a successful execution:
```
119.17.43.86 - - [07/Dec/2021:07:13:48 +1000] "GET /simplesaml/module.php/saml/sp/metadata.php/sobs-sp?schoolid=1347 HTTP/1.1" 200 269 "https://sobs.com.au/ui/config.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36"
```

There are no other error messages I can find.
Where can I add some debug messages that will help me track down the problem?

**Comment by tvdijen** [comment]
I see... It just returns a HTTP/200 OK with no content.. That's very strange..
The file you are looking for to add debug statements is `modules/saml/www/sp/metadata.php`

**Comment by murraycollingwood** [comment]
Hi Tim

This is getting stranger and stranger.
My client emailed today as they were able to download the XML metadata (although it came down without the .xml extension.  I asked them if there were some additional instructions I needed to document, their response was:

> The only thing I noticed was that when I clicked the ‘Generate Metadata’ button in SOBS, it would download the XML file without the xml file extension and the file extension needed to be added in manually. I don’t know if that’s something you want to make note of in the documentation or not but other than that the documentation had everything I needed for Azure. The missing fields I emailed about last week ended up getting filled in by the metadata file I uploaded to azure from sobs

When I go to the same page and click the "Generate Metadata" button in SOBS I get a blank screen.
I will add some debugging and try and find out what is happening, just wanted to let you know that it seems to be working in some instances, but not all, so it could well be something to do with my application.

Cheers
Murray

**Comment by tvdijen** [comment]
SOBS being?

**Comment by murraycollingwood** [comment]
Hi Tim

Sorry for the long delay.
I added some debug code to metadata.php and found the following:
![image](https://user-images.githubusercontent.com/5810216/150676977-5d489c4b-c8d0-49d7-851a-cf9742ea7235.png)

I'm looking into Source::getById

**Comment by murraycollingwood** [comment]
From Auth/Source.php
![image](https://user-images.githubusercontent.com/5810216/150677526-d18c668e-255b-4003-94a0-c4cb3cd85893.png)

And my server log messages then show:
![image](https://user-images.githubusercontent.com/5810216/150677546-19a79219-4059-44b0-9abd-88c21cc53f93.png)

I'm looking into Configuration::getConfig

**Comment by murraycollingwood** [comment]
The error was in authsources.php - I was missing a valid school identifier, so it was not finding the correct records to export.
I have corrected the error and it appears to be working again - hurrah!  So, after all that, it's not you, it's me. 
Thanks for being so patient.

**Comment by tvdijen** [comment]
Glad you have it solved @murraycollingwood !  Are you using some kind of custom code to deal with those school IDs?
I was thinking if we could improve error handling somehow..

**Comment by murraycollingwood** [comment]
Yes - for us all of these SSP calls need to include a school ID so that we know which school to process.
The main call back from authentication was one of our early challenges during implementation, we had to use the SSP session to store the school ID, but that has been working fine for many years now.

Error handling seems fine to me.

In this instance I would have benefited from you treating the output from customised files like config.php and authsources.php as "user input", and therefore perform more assertions on the values being returned.
My code had been running quite happily for a number of years, so I had no idea I wasn't returning valid values.

Cheers
Murray
