### ISSUE TITLE
Database options are overriden by persistent

### ISSUE THREAD

**Issue by melanger** [simplesamlphp/simplesamlphp#1546]
https://github.com/simplesamlphp/simplesamlphp/blob/0eca58c393d5ba2fde18a506c29ccebe1e3a5be9/lib/SimpleSAML/Database.php#L86

https://github.com/simplesamlphp/simplesamlphp/blob/0eca58c393d5ba2fde18a506c29ccebe1e3a5be9/lib/SimpleSAML/Database.php#L87

When `'database.persistent'` is not explicitly set to `false` and `'database.driver_options'` are set, they are overriden by the persistent setting. Instead, the persistent option should be added to the driver options array, keeping all other items.

To reproduce, use a config like:

```
'database' => [
  'database.dsn' => '...',
  'database.username' => '...',
  'database.password' => '...',
  'database.driver_options' => [\PDO::ATTR_EMULATE_PREPARES => true],
],
```

With this config, the `ATTR_EMULATE_PREPARES` is not applied, because it is overriden by `[PDO::ATTR_PERSISTENT => true]`.

As a temporary work-around, this works:

```
'database' => [
  'database.dsn' => '...',
  'database.username' => '...',
  'database.password' => '...',
  'database.driver_options' => [\PDO::ATTR_EMULATE_PREPARES => true],
  'database.persistent' => false, // work-around
],
```

Also, the `'database.persistent'` has default `true` in [one place](https://github.com/simplesamlphp/simplesamlphp/blob/0eca58c393d5ba2fde18a506c29ccebe1e3a5be9/lib/SimpleSAML/Database.php#L86) but `false` in [another](https://github.com/simplesamlphp/simplesamlphp/blob/0eca58c393d5ba2fde18a506c29ccebe1e3a5be9/lib/SimpleSAML/Database.php#L131).

**Comment by melanger** [comment]
Also, the consent module, which does not use `SimpleSAML\Database` but [it's own Database class](https://github.com/simplesamlphp/simplesamlphp-module-consent/blob/v0.9.7/lib/Consent/Store/Database.php) does not have this problem, although it does not support slaves/secondaries etc.

**Comment by thijskh** [comment]
@melanger Please see #1555 for a proposed fix

**Comment by melanger** [comment]
> @melanger Please see #1555 for a proposed fix

@tvdijen Looks good, thanks
