### ISSUE TITLE
1.19.4 (with PHP 7.2) throws exception

### ISSUE THREAD

**Issue by msalle** [simplesamlphp/simplesamlphp#1547]
As soon as an error occurs, simplesamlphp-1.19.4 throws exception:
```
Fatal error: Class Symfony\Component\DependencyInjection\Exception\ExceptionInterface cannot implement previously implemented interface Throwable in /var/simplesamlphp-1.19.4-devel/vendor/symfony/dependency-injection/Exception/ExceptionInterface.php on line 22
```

this is caused because 1.19.4 uses symfony/dependency-injection 5.4 which appears to be broken:
symfony/dependency-injection 5.4 has been updated to a change in psr/container, see https://github.com/symfony/dependency-injection/commit/651a0d7c69949c98d81881e209f638fa23e604ec but requires psr/container 1.1.1 which itself has actually retracted that change. See for psr/container
- https://github.com/php-fig/container/releases/tag/1.1.1
- https://github.com/php-fig/container/pull/31
- https://github.com/php-fig/container/issues/30

(note that psr/container 1.1.2 breaks for PHP <7.4).

Manually reverting the commit in symfony/dependency-injection/Exception/ExceptionInterface.php fixes the problem.

**Comment by tvdijen** [comment]
Could it be that you've ran a `composer update` yourself, because we build with PHP 7.1 and include `psr/container` v1.0.0 in the tarball..

**Comment by msalle** [comment]
No I don't use composer but after looking again, it's indeed different than I thought:
According to simplesamlphp-1.19.4/vendor/composer/installed.json:
- it has installed psr/container 1.1.2 (as can also be seen from the PHP requirement of >=7.4.0 in simplesamlphp-1.19.4/vendor/psr/container/composer.json)
- it has installed symfony/dependency-injection is 5.4.1 (as can also  be seen from simplesamlphp-1.19.4/vendor/symfony/dependency-injection/CHANGELOG.md)

That symfony/dependency-injection 5.4.1 should be fine, but the psr/container 1.1.2 is the problem and I'm actually seeing https://github.com/php-fig/container/issues/30 directly. 

It's not clear however why it's using version 1.1.2. Maybe it needs an explicit conflict with 1.1.2 since there are some requirements on `"^1.1"` instead of `"^1.1.1"` ?

I'm afraid I'm not really an expert on composer's dependency resolution, but we should stick to 1.1.1 for psr/container for PHP 7.2 compatibility.

**Comment by tvdijen** [comment]
I think something went wrong during the build-process of the tarball.. I've uploaded a new one.. Would you mind checking if this solves your issue?

**Comment by msalle** [comment]
It works fine, thanks!
Shall I close the issue?

**Comment by tvdijen** [comment]
Thanks for testing!

**Comment by supryantowp** [comment]
I also got the same error like this. but I'm using pimcore version 6.5 and I don't know how to fix it. please help me please i've been almost a week

**Comment by supryantowp** [comment]
![code](https://user-images.githubusercontent.com/52796494/146345456-69975ca8-1d50-4360-af65-ddd2bed98e8a.png)

when I try to fix the above method remove / Thowrable. it causes another problem

**Comment by supryantowp** [comment]
![Screen Shot 2021-12-16 at 16 34 21](https://user-images.githubusercontent.com/52796494/146345835-430884e2-1779-46d2-95f7-4a8e7f2b4b59.png)

**Comment by supryantowp** [comment]
```
{
  "name": "pimcore/skeleton",
  "type": "project",
  "license": "GPL-3.0-or-later",
  "config": {
    "optimize-autoloader": true,
    "sort-packages": true
  },
  "require": {
    "php": ">=7.2",
    "ext-dom": "*",
    "ext-json": "*",
    "elasticsearch/elasticsearch": "7.4.0",
    "excelwebzone/recaptcha-bundle": "^1.5",
    "hwi/oauth-bundle": "^0.6.3",
    "php-http/guzzle6-adapter": "^1",
    "php-http/httplug-bundle": "^1.16",
    "phpoffice/phpspreadsheet": "^1.18",
    "pimcore/customer-management-framework-bundle": "^2.4",
    "pimcore/pimcore": "~6.5.0",
    "predis/predis": "^1.1",
    "saltid/pimcore-elasticsearchbundle": "~1.0@beta",
    "saltid/pimcore-extensionmanagerbundle": "~1.0@beta",
    "saltid/pimcore-seoserpbundle": "~1.0@beta",
    "sentry/sentry-symfony": "^3.4",
    "spatie/schema-org": "3.3.0",
    "vlucas/phpdotenv": "^3",
    "wikimedia/composer-merge-plugin": "^1.4",
    "yuliusardian/validation": "^1.0"
  },
  "require-dev": {
    "cache/integration-tests": "^0.16.0",
    "codeception/codeception": "~2.4.5"
  },
  "autoload": {
    "psr-4": {
      "": ["src/"],
      "Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
      "Pimcore\\Model\\Object\\": "var/classes/Object",
      "Website\\": "legacy/website/lib"
    },
    "classmap": [
      "app/AppKernel.php"
    ]
  },
  "scripts": {
    "post-create-project-cmd": "Pimcore\\Composer::postCreateProject",
    "post-install-cmd": [
      "Pimcore\\Composer::postInstall",
      "@pimcore-scripts"
    ],
    "post-update-cmd": [
      "Pimcore\\Composer::postUpdate",
      "@pimcore-scripts",
      "Pimcore\\Composer::executeMigrationsUp",
      "@pimcore-scripts"
    ],
    "pimcore-scripts": [
      "Pimcore\\Composer::clearCache",
      "Pimcore\\Composer::installAssets"
    ]
  },
  "extra": {
    "symfony-app-dir": "app",
    "symfony-bin-dir": "bin",
    "symfony-var-dir": "var",
    "symfony-web-dir": "web",
    "symfony-tests-dir": "tests",
    "symfony-assets-install": "relative",
    "merge-plugin": {
      "include": [
        "composer.local.json"
      ],
      "recurse": true,
      "replace": true,
      "merge-dev": true,
      "merge-extra": false,
      "merge-extra-deep": false,
      "merge-scripts": false
    }
  }
}
```

this my composer.json

**Comment by tvdijen** [comment]
You're not using SimpleSAMLphp, so we cannot help you.. You have to address your depencies
