### ISSUE TITLE
Clearing up some confusion around the 1.19.4 release, suggestion for future releases

### ISSUE THREAD

**Issue by imrejonk** [simplesamlphp/simplesamlphp#1548]
Hi,

I've received two conflicting announce mails regarding the 1.19.4 release, which both claim that the tarball has a certain SHA-256 checksum:

Email from Mon, 13 Dec 2021 12:48:05 -0800: f7c208f87158c5cd808bf97508df86b76551045e3c2895796622efd4b6f779b5
Email from Tue, 14 Dec 2021 03:56:04 -0800: 34c8e7781514f71bb58859db8a3690147a269279b6e88b983e23b2b0aac4a39f

The emails were identical otherwise. I read in https://github.com/simplesamlphp/simplesamlphp/issues/1547 that the 1.19.4 tarball was re-released because of a build process issue, so that explains the second announce mail with a different SHA-256 checksum. However, I don't see the new checksum (or any checksum for that matter) on the [download page](https://simplesamlphp.org/download).

I have two suggestions:

1. Please add the correct checksum to the download page.
2. Consider if re-releases should happen like this in the future. It may be less confusing if the second tarball was just sent out as 1.19.5. This also makes it easier for SSP users to verify whether they are impacted by https://github.com/simplesamlphp/simplesamlphp/issues/1547 or not. I understand that no code changes were made and that increasing the version number may feel a bit off in this case, but it can't hurt really. Git also allows tagging a commit with multiple tags. In `git describe`, the last tag wins.

Thanks for your consideration.

**Comment by thijskh** [comment]
Hi Imre. Thanks for the feedback. We are in a transition in two ways regarding releases: from Uninett-maintained to community-maintained, and from 1.x to 2.x. Both things can lead to some rough edges in the release process. I believe one solution I'd prefer is to further automate release creation. We will certainly keep your comments in mind with this.
