### ISSUE TITLE
Log messages containing % characters garbled 

### ISSUE THREAD

**Issue by abmaymic** [simplesamlphp/simplesamlphp#1549]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
In lib/SimpleSAML/Logger/SyslogLoggingHandler.php#L81 there is a regexp   
`$string = preg_replace('/%\w+(\{[^\}]+\})?/', '', $string);`  
which will garble strings that should get logged, if they contain % characters. % characters are typical for URL-encoded values.

**To Reproduce**
Try to log a string containing % characters - it happened for me, when a URL should be logged, that contained some urlencoded parameters.

**Expected behavior**
dont't garble the message.

**Screenshots or logs**
some values anonymized....

$string before Line 81:

`%date{%b %d %H:%M:%S}  7 [487515afbe] authoauth2:  redirecting to authorizeURL=https://test.example.org/connect/authorize?scope=openid%20profile%20email%20boards&state=authoauth2%7C_8f8fb87f02e6ecb68b01ada35919e76ea9f5800fe8%3Ahttps%3A%2F%2Fssobridge.example.com%2Fsimplesamlphp%2Fsaml2%2Fidp%2FSSOService.php%3Fspentityid%3Dhttps%253A%252F%252Fssolanding.example.com%252Fshibboleth%26RelayState%3Dss%253Amem%253Ae171c61ae72a13091a35219891285b46d3e942bb611fed32f2c32646201243d8%26cookieTime%3D1639782086&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2Fssobridge.example.com%2Fsimplesamlphp%2Fmodule.php%2Fauthoauth2%2Flinkback.php&client_id=sso-blabla-test`

After Line 81:
`  7 [487515c101] authoauth2:  redirecting to authorizeURL=https://test.example.org/connect/authorize?scope=openid&state=authoauth2.example.com.php.example.com&response_type=code&approval_prompt=auto&redirect_uri=https.example.com.php.php&client_id=sso-blabla-test`

**Comment by thijskh** [comment]
You are correct. This has been added in 0e2f2ec441b25dfa3d5136e400b324dc54310f0b as a feature to allow to specify the log format. However, the code should not be interpolating the variables over the entire logged string at all. Just over the log format itself. So this is indeed buggy and should be changed.

**Comment by tvdijen** [comment]
I somehow remember fixing a similar issue recently, but I can't find it...
Anyway, the fix seems easy enough; remove the preg_match and live with the fact that unknown placeholders are not replaced and end up in the log verbatim.. Right?

**Comment by thijskh** [comment]
It still means that if you have a string %msg or %stat in the log message (not the format) somewhere it will be replaced which does not seem right.

**Comment by tvdijen** [comment]
Uhm, maybe I'm overlooking something, but that's what the preg_match is responsible for, right?  The replacement of placeholders is done by str_replace which is more than enough.

If I'm overlooking something, then we should just add str_replace statements for all individual placeholders..

**Comment by thijskh** [comment]
I think the intention should be to replace only inside “format”, not inside the logmessage itself.

**Comment by tvdijen** [comment]
Ah yes, that would of course be even better!
