### ISSUE TITLE
ADFS IdP loads metadata of disabled SAML IdP

### ISSUE THREAD

**Issue by m0ark** [simplesamlphp/simplesamlphp#1564]
**Describe the bug**
ADFS IdPs load available SAML IdP metadata even though they are not enabled .
In combination with the install instructions provided in the documentation, which suggests copying the whole `metadata-templates/` content to `metadata/`, probably erroneous configuration (in my case certificates not being available as `saml20-idp-hosted.php` expects) is loaded.
This will only interfere when using the created associationGroup, especially during SLO requests.

https://github.com/simplesamlphp/simplesamlphp/blob/43c1caf3fdefe7e900e6c719c7422c96c87bca42/lib/SimpleSAML/IdP.php#L94-L100

**To Reproduce**
1. Setup SimpleSAMLphp as suggested in https://simplesamlphp.org/docs/stable/simplesamlphp-install (especially copying each and every metadata template to active configuration)
2. In `config/config.php`:
```
'enable.saml20-idp' => false,
'enable.shib13-idp' => false,
'enable.adfs-idp' => true,
```
3. Configure `adfs-idp-hosted.php` (e.g. with customized certificate location)
4. Sign in using an ADFS RP
5. Logout leads to an error (unconfigured certificate path of disabled `saml20-idp-hosted.php` not found)

**Expected behavior**
SAML IdP metadata should only be loaded if it has been enabled at all (`'enable.saml20-idp' => true,` ).

**Comment by thijskh** [comment]
Maybe I'm not understanding it right, but simply adding an if for the setting around the code you quote would do it?

**Comment by m0ark** [comment]
It should. I did not test it yet.

I will check later and create a PR.
