### ISSUE TITLE
Remove selectize JS-dependency

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1566]
Thee selectize-package hasn't been maintained very well and contains known vulnerabilities for a long time already.
We only use this in two places;

- `modules/core/templates/loginuserpass.twig`
- `templates/_header.twig`

We should find another package to provide this functionality and remove the dependency on the selectize-package (and probably backport this to 1.19 as well).

Possible alternatives;  https://alternativeto.net/software/selectize-js/

**Comment by thijskh** [comment]
Yes, it’s also not very well accessible

**Comment by tvdijen** [comment]
I really like https://github.com/Choices-js/Choices as an alternative.. Mainly because it doesn't depend on jQuery.

**Comment by thijskh** [comment]
But we already depend on jQuery, right?

**Comment by tvdijen** [comment]
Yes, but if we need to patch that (and JQuery has security issues pretty often), we should just be able to update it without having to worry about other packages that still rely on older versions of JQuery

**Comment by thijskh** [comment]
Fixed in #1567
