### ISSUE TITLE
v2.0: Non-static method SimpleSAML\Utils\Crypto::pwHash() cannot be called statically in pwgen.php:24

### ISSUE THREAD

**Issue by AlphaJack** [simplesamlphp/simplesamlphp#1568]
**Describe the bug**
`pwgen.php` is unusuable in v2.0.0-beta4 as the "SimpleSAML\Utils\Crypto::pwHash()" method is called statically, even if starting from v2.0 the "\SimpleSAML\Utils\Crypto" class has been migrated to non-static

Also the password is printed in cleartext, I'm not a big fan of that

**To Reproduce**
1. Install the latest beta
2. Run `php pwgen.php`
3. Get the error

**Expected behavior**
A password hash is generated

**Screenshots or logs**

```
$ php simplesamlphp/bin/pwgen.php
Enter password: hunter2
PHP Fatal error:  Uncaught Error: Non-static method SimpleSAML\Utils\Crypto::pwHash() cannot be called statically in /path/to/simplesamlphp/bin/pwgen.php:24
Stack trace:
#0 {main}
  thrown in /path/to/simplesamlphp/bin/pwgen.php on line 24
```

**Additional context**

From https://simplesamlphp.org/docs/development/simplesamlphp-upgrade-notes-2.0: 

> The following classes have been migrated to non-static:
>
>   [...]
>    \SimpleSAML\Utils\Crypto
>   [...]
>
> If you use any of these classes in your modules or themes, you will now have to instantiate them so that:
> 
> // Old style $x = \SimpleSAML\Utils\Arrays::arrayize($someVar)
>
> becomes:
> 
> // New style $arrayUtils = new \SimpleSAML\Utils\Arrays(); $x = $arrayUtils->arrayize($someVar);

**Comment by tvdijen** [comment]
Thanks, I have fixed this in the `master`-branch.
Unfortunately there is no reliable way to obfuscate the password
