### ISSUE TITLE
[PHP8.1] Deprecated function: SimpleSAML\Session implements the Serializable interface, which is deprecated

### ISSUE THREAD

**Issue by ideb** [simplesamlphp/simplesamlphp#1579]
**Describe the bug**
Using SimpleSAMLphp on PHP8.1 triggers the following deprecation notice:

Deprecated function: SimpleSAML\Session implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in include() (line 571 of /[..]/vendor/composer/ClassLoader.php)

For more information, see https://php.watch/versions/8.1/serializable-deprecated

**To Reproduce**
Use PHP8.1

**Expected behavior**
Using PHP8.1 does not trigger a deprecation notice.

**Comment by ideb** [comment]
See pull request #1580

**Comment by tvdijen** [comment]
Closed in #1588 .. This will end up in 1.19.6  and 2.0
