### ISSUE TITLE
Should Module.php alter the status code from 200 to 404 when an asset is not found?

### ISSUE THREAD

**Issue by kishba** [simplesamlphp/simplesamlphp#1585]
**Is your feature request related to a problem? Please describe.**
I'm creating a module for my school that uses Twig theming. I was researching what would happen if the `asset('missing-filename.css', 'module-name')` referred to a file that does not exist. I was surprised to find that an HTML page is rendered with a status code of 200. You can simulate this yourself by going to a URL like `/simplesaml/module.php/module-name/assets/missing-filename.css`.

(The specific error message is slightly different if `module-name` doesn't exist in your project, but I think it's still a variation of the `Error\NotFound` thrown error.)

I was slightly worried that this HTML page would be cached by a browser, but it looks like the cache headers are not generated when these errors (`Error\NotFound`) are caught and rendered as an HTML page.

**Describe the solution you'd like**
I'm okay with the HTML page being rendered, but could the status code be changed from 200 to 404?

**Describe alternatives you've considered**
If there's a way to customize an error page in a module, I wonder if I could change the status code myself? I appreciate any advice/suggestions.

**Comment by tvdijen** [comment]
I've tested this against master and I get a HTTP/404, so apparently this is already fixed..
You can customize the Twig-template in a custom theming-module, but I don't think you can control the returned status code.

**Comment by kishba** [comment]
Oh, that's exciting to hear. I tried to run master to confirm myself, but I'm getting Compose autoloader errors when I try to run it.

The version that is giving me the status code of 200 for not found files is the latest release, 1.19.5. I wish I had shared that version number in my original post!

I thought that perhaps this was because I had `'production' => false,` or `'showerrors' => true,` in my config, but I've tried changing those and still see 200 being returned in my browser's network tab.

Would you be able to try 1.19.5 to confirm you see 200 status codes @tvdijen ? I'll be happy to close this as already fixed assuming it's not because of my configuration. :)

**Comment by thijskh** [comment]
It worked in 1.18.x, is broken in 1.19.x and fixed in 2.0.

The commit that broke it is this one 60689bd8172ecb58acd41294dfea4f44bbd3f988. Moving the setHTTPcode back to outside of the if (as it was before) resolves the issue. Maybe that's the simplest fix for the 1.19 branch. Apparently for 2.0 this is no longer necessary. Probably related to the split brain templating situation in 1.19?

**Comment by tvdijen** [comment]
What happens if you change this line from `$this->send` to `$this->show`?

https://github.com/simplesamlphp/simplesamlphp/blob/dfbb7e65f412af092572ceef674a7ad14eb42d4f/lib/SimpleSAML/Error/Error.php#L284

**Comment by thijskh** [comment]
If you mean change `show` to `send`, then yes, that seems to fix the issue.

**Comment by kishba** [comment]
Confirmed! Changing `show` to `send` changed the behavior to return a 404 status code instead of a 200 for missing asset files. Visual Studio code even had a line through `show()` and I hadn't picked up on that!

Thank you @thijskh and @tvdijen for helping me figure this out for my 1.19.5-based project. I don't suppose there's a 1.19.6 planned before the big 2.0 release? :)

**Comment by thijskh** [comment]
Probably not for this change alone, but I've committed the change on the 1.19 branch, so if there's a reason to release 1.19.6, this fix will be part of it.
