### ISSUE TITLE
NameID hash mismatch in session handling causes logout to fail

### ISSUE THREAD

**Issue by siilike** [simplesamlphp/simplesamlphp#1586]
`SimpleSAML\Module\saml\SP\LogoutStore` manages sessions and for SQL stores uses the hash of NameId as the session identifier along with the auth source.

In `SimpleSAML\Module\saml\SP\LogoutStore::addSession()` the received NameId is serialized and hashed:
```
$strNameId = serialize($nameId);
$strNameId = sha1($strNameId);
```
For example, the NameId upon creating a sample session is (from debugger):
```
SAML2\XML\saml\NameID::__set_state(array(
   'nodeName' => 'saml:NameID',
   'Format' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
   'SPProvidedID' => NULL,
   'value' => 'xxx@xxx.com',
   'NameQualifier' => NULL,
   'SPNameQualifier' => NULL,
))
```
When a `samlp:LogoutRequest` is received `SimpleSAML\Module\saml\SP\LogoutStore::logoutSessions()` is called and the same method is used for hashing the received NameId.

Unfortunately, the NameId there is without the Format attribute:
```
SAML2\XML\saml\NameID::__set_state(array(
   'nodeName' => 'saml:NameID',
   'Format' => NULL,
   'SPProvidedID' => NULL,
   'value' => 'xxx@xxx.com',
   'NameQualifier' => NULL,
   'SPNameQualifier' => NULL,
))
```
which means that the hash is different and looking up the session from database will fail.

Logs:
```
DEBUG Received message:
DEBUG <samlp:LogoutRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_fc36dbbe-022a-4bbc-a390-61ab677aaf3f" Version="2.0" IssueInstant="2022-02-08T19:12:01.394Z" Destination="https://xxx/simplesaml/module.php/saml/sp/saml2-logout.php/df" NotOnOrAfter="2022-02-08T20:12:01.394Z">
DEBUG   <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">https://sts.windows.net/xxx/</Issuer>
DEBUG   <NameID xmlns="urn:oasis:names:tc:SAML:2.0:assertion">xxx@xxx.com</NameID>
DEBUG   <samlp:SessionIndex>_f70d0164-33f5-4439-be59-984b25e7c700</samlp:SessionIndex>
DEBUG </samlp:LogoutRequest>
DEBUG module/saml2/sp/logout: Request from https://sts.windows.net/xxx/
NOTICE STAT saml20-idp-SLO idpinit https://xxx/simplesaml/module.php/saml/sp/metadata.php/df https://sts.windows.net/xxx/
INFO saml.LogoutStore: Logout requested for unknown SessionIndex.
WARNING Logged out of 0 of 1 sessions.
DEBUG Sending message:
DEBUG <samlp:LogoutResponse xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_23802ae727b69f0533ddf1fbb976c6b2b517b10bd7" Version="2.0" IssueInstant="2022-02-08T19:12:01Z" Destination="https://login.microsoftonline.com/xxx/saml2" InResponseTo="_fc36dbbe-022a-4bbc-a390-61ab677aaf3f">
DEBUG   <saml:Issuer>https://xxx/simplesaml/module.php/saml/sp/metadata.php/df</saml:Issuer>
DEBUG   <samlp:Status>
DEBUG     <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
DEBUG   </samlp:Status>
DEBUG </samlp:LogoutResponse>
```
You can see `Logout requested for unknown SessionIndex`, because `self::getSessionsSQL($store, $authId, $strNameId)` in `logoutSessions()` will return an empty array as the `$strNameId` is different due to the missing `Format` attribute.

Using only the value of NameId, for example, resolves the issue.

**Comment by tvdijen** [comment]
So Azure isn't sending back the `Format`... Not sure what we can do about it..
Of course using only the value solves things, but the `Format` is kinda like a namespace.. You can't change or omit it without changing the 'value'..
This seems like an issue you have to report to Microsoft..

**Comment by siilike** [comment]
Indeed according to the standard both the format and value must match:
```
3.7 Single Logout Protocol
3.7.3.1 Session Participant Rules
[--]
The subject of the assertion strongly matches the <saml:BaseID>, <saml:NameID>, or
<saml:EncryptedID> element in the <LogoutRequest>, as defined in Section 3.3.4.
```
and 3.3.4 states that `S1 and S2 cannot contain a <saml:NameID> element with different Format values and element content, even if the two identifiers are considered to refer to the same principal.`

But still, would be useful to consider optionally matching only the value until this gets fixed.

**Comment by thijskh** [comment]
Maybe start with reporting the issue to MS and see what they can do about it? I’m not opposed to workarounds but let’s first just try to fix the software that violates the spec

**Comment by siilike** [comment]
I already did that, let's see.

**Comment by tvdijen** [comment]
Any update on this @siilike ?

**Comment by siilike** [comment]
It is still being "reviewed".

**Comment by siilike** [comment]
VULN-061858, case number 70154.

**Comment by tvdijen** [comment]
I must say I haven't poked MS anymore.. Have you received a status update from them @siilike ?

**Comment by siilike** [comment]
Nothing. No-one logs out anyway.

**Comment by tvdijen** [comment]
Since this is not something we can fix on our end, I'm closing this issue. If you ever hear back from Microsoft, please update this issue!

**Comment by siilike** [comment]
Microsoft has confirmed that this isssue is now fixed.
