### ISSUE TITLE
Uncaught exception 'SimpleSAML\Error\Exception' with message 'No private key found in metadata.' in /var/www/vhosts/example.com/httpdocs/auth/lib/SimpleSAML/Utils/Crypto.php:208 #1590

### ISSUE THREAD

**Issue by burhan-njom** [simplesamlphp/simplesamlphp#1591]
Fatal error: Uncaught exception 'SimpleSAML\Error\Exception' with message 'No private key found in metadata.' in /var/www/vhosts/example.com/httpdocs/auth/lib/SimpleSAML/Utils/Crypto.php:208 Stack trace: #0 /var/www/vhosts/example.com/httpdocs/auth/modules/saml/lib/Message.php(52): SimpleSAML\Utils\Crypto::loadPrivateKey(Object(SimpleSAML\Configuration), true) https://github.com/simplesamlphp/simplesamlphp/pull/1 /var/www/vhosts/example.com/httpdocs/auth/modules/saml/lib/Message.php(120): SimpleSAML\Module\saml\Message::addSign(Object(SimpleSAML\Configuration), Object(SimpleSAML\Configuration), Object(SAML2\AuthnRequest)) https://github.com/simplesamlphp/simplesamlphp/issues/2 /var/www/vhosts/example.com/httpdocs/auth/modules/saml/lib/Message.php(544): SimpleSAML\Module\saml\Message::addRedirectSign(Object(SimpleSAML\Configuration), Object(SimpleSAML\Configuration), Object(SAML2\AuthnRequest)) https://github.com/simplesamlphp/simplesamlphp/issues/3 /var/www/vhosts/example.com/httpdocs/auth/modules/saml/lib/Auth/Source/SP.php(512): SimpleSAML\Module\saml\Message::buildAuthnRequest(Object(SimpleSAML\Configuration), Object(SimpleSAML\Configuration)) https://github.com/simplesamlphp/simplesamlphp/issues/4 /var/www/vh in /var/www/vhosts/example.com/httpdocs/auth/lib/SimpleSAML/Utils/Crypto.php on line 208

What am I missing? Doesn't the idp meta provide the required key info?

**Comment by thijskh** [comment]
This is an issue tracker, not a support forum. Please direct your question to the [simpleSAMLphp user's mailing list](https://simplesamlphp.org/lists).

**Comment by tvdijen** [comment]
> What am I missing? Doesn't the idp meta provide the required key info?

So it seems.. At least your SP doesn't know how to encrypt it's AuthnRequest towards the IDP.. Make sure to read the docs on encrypted messages.
