### ISSUE TITLE
Fix up markdown of documentation

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/simplesamlphp#1594]
The documentation in the repository is not always vanilla markdown and hence is not well rendered in every environment, e.g. GitHub itself.

What to do?

1. Find a document under [`docs/`](https://github.com/simplesamlphp/simplesamlphp/tree/master/docs) or `modules/*/docs/`
2. See how it looks on GitHub in rendered output
3. Edit the document, improve the [Markdown formatting](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) until it looks good
4. Save and commit and/or send as pull request.

All can be done, if you want, from within the GitHub interface. Improving just one document is already helpful.

**Comment by tvdijen** [comment]
Are you aware of any syntax-test for markdown? We might as well add it to the unit tests under 'Quality control'

**Comment by tvdijen** [comment]
As per Slack discussion, it makes sense to at least run a linter..
I will add one to catch the immediate violations.. The rest is up to us

**Comment by tvdijen** [comment]
Additionally, I've added a config file for the linter to disable the long line checks. The reason for this is that some lines are really difficult to cut, especially tables. Github however is very good at wrapping these long lines.

**Comment by tvdijen** [comment]
@thijskh Syntax checking was added, auto-push to the docs repo as well..  Is there anything you want with this issue, or can we close this?

**Comment by thijskh** [comment]
Lets close this and make issues for anything concrete we find
