### ISSUE TITLE
2.0: translations for modules don't work

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1599]
Translations are broken for the modules, probably due to the gettext-upgrade that was done last week.

**Comment by tvdijen** [comment]
I'd hate to see 2.0 ship with an unsupported version of gettext.
I've already spent some time investigating this and it likely has something to do with the translation domains.. The translations _are_ loaded

**Comment by thijskh** [comment]
Have you seen my comment on the PR? https://github.com/simplesamlphp/simplesamlphp/pull/1600#discussion_r813276501
It's clear to me what the cause is.

In any case it's good to upgrade but in all honesty we keep expanding the scope of 2.0 instead of working towards a release...

**Comment by tvdijen** [comment]
Ah, I've missed that comment!  Nice work checking it out!!
I think the only remainder for 2.0 is the last few controllers for the saml-library and then cleaning up the translations
