### ISSUE TITLE
Fontawesome:  icon not showing in dropdown in Firefox

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1607]
**Describe the bug**
Fontawesome icon is not showing in the dropdown-box of the language selector. Only happens in Firefox.

![afbeelding](https://user-images.githubusercontent.com/841045/158357889-f6e55252-31d6-4b6b-bbd9-6886ae21da17.png)

Should look like:

![afbeelding](https://user-images.githubusercontent.com/841045/158365929-afec385f-9069-4d07-8d38-7163fa4ec146.png)

**Comment by thijskh** [comment]
This seems to be unfixable in a cross-platform way.

**Comment by thijskh** [comment]
Fixed in 6a6f9d2b7

**Comment by tvdijen** [comment]
We may want to consider stepping away from fontawesome completely.. It's become a horrible library that doesn't care about it's community since they're gone commercial.. Upgrading always gives headaches.

**Comment by thijskh** [comment]
We don't use it a lot so replacing it with an alternative is feasible, the question of course being what is the better solution then...

**Comment by tvdijen** [comment]
https://github.com/astrit/css.gg
This one seems pretty straightforward and is completely free / open-source under MIT license.

**Comment by tvdijen** [comment]
After some more research it may be better to remove fontawesome completely and replacee any uses with unicode symbols.
css.gg works pretty well, but it's not possible to insert images in a dropdown-bar like we want for the language bar without resorting to dirty hacks like fonts (fontawesome) or javascript for custom drop-downs
