### ISSUE TITLE
ADFS IdP broken when 'usenewui' is _not_ set.

### ISSUE THREAD

**Issue by rjaffey** [simplesamlphp/simplesamlphp#1613]
SSP 1.19.5 and 'usenewui' _not_ configured.

When using the ADFS IdP, assertions were not being sent to the remote SP.  The following error was thrown at the point when an assertion should have been loaded into the browser for posting to the remote SP:

/module.php/core/loginuserpass.php - Template: Could not find template file [adfs:postResponse.twig] at [/var/www/simplesamlphp-1.19.5-live/modules/adfs/templates/postResponse.twig]
Caused by: Exception: Template: Could not find template file [adfs:postResponse.twig] at [/var/www/simplesamlphp-1.19.5-live/modules/adfs/templates/postResponse.twig]

My fix was to reinstate code which supported both UI's that was removed at some point.  Here's a patch based on code I retrieved from simplesamlphp-module-adfs v0.9.6.  See attachment.

[adfs.txt](https://github.com/simplesamlphp/simplesamlphp/files/8354347/adfs.txt)

**Comment by tvdijen** [comment]
The wrong version of the ADFS-module was included. You can manually install v1.x of the adfs-module
