### ISSUE TITLE
Missing PDO connection details in documents (https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-metadata-pdostoragehandler.md)

### ISSUE THREAD

**Issue by vijaygodhasara** [simplesamlphp/simplesamlphp#1615]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
Issue like missing information about to PDO connection configure into config.php file

**To Reproduce**
check like as https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-metadata-pdostoragehandler.md

**Expected behavior**
should be have proper information for configure PDO connection.

**Screenshots or logs**

**Additional context**

**Comment by vijaygodhasara** [comment]
Please find details in this thread :
https://groups.google.com/g/simplesamlphp/c/OQ7MhxMzq5A/m/VFzZDGNSBwAJ
https://groups.google.com/g/simplesamlphp/c/OQ7MhxMzq5A/m/gvBo1o83BwAJ

**Comment by tvdijen** [comment]
I don't think you need the settings in the `metadata.sources` array at all..  They are only needed to _override_ the `database.`-settings.
