### ISSUE TITLE
External simplesaml class

### ISSUE THREAD

**Issue by rustybucket145** [simplesamlphp/simplesamlphp#1616]
I'm trying to utilize the external class on my idp install of simple saml.  The idp works fine for logging in user/pass but I need the external to help verify some types of users.

I keep getting this php fatal error

 PHP Fatal error:  Declaration of SimpleSAML\\Module\\mymodule\\Auth\\Source\\MyAuth::authenticate() must be compatible with SimpleSAML\\Auth\\Source::authenticate(&$state) in /var/simplesamlphp/modules/mymodule/lib/Auth/Source/MyAuth.php on line 355, referer: https://xxxxxxxyyyyyzzzzz.com/

I've googled and cannot seem to find anything relating to this.  Any ideas where I might have gone wrong or what I may try to fix?

**Comment by tvdijen** [comment]
Your MyAuth.php is extending SimpleSAMLphp's `Auth\Source` class. If you are overloading any methods from the base class, like in this case `authenticate`, you must follow the exact same method signature.. This is basic PHP knowledge.
Just add the `&$state` parameter to your implementation of `authenticate` and if will work.

**Comment by rustybucket145** [comment]
Thanks tvdijen, the source code on github had this:

public function authenticate(array &$state)

I modified it to this (at your guidance), and everything seems to work now.  I'm not quite sure why they had 'array' in the method signature?

Thanks for your guidance!
public function authenticate(&$state)
