### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by jringoot** [simplesamlphp/simplesamlphp#1618]
![Screenshot from 2022-04-07 09-27-59](https://user-images.githubusercontent.com/2686933/162152949-72e64487-7ddc-4d3a-9b45-369f11fa0539.png)
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
When trying to connect to the idp module via a service provider we get an error.

**To Reproduce**
https://filesender.belnet.be/

1. Go to  'https://filesender.belnet.be/
2. click on 'login'
3. Select 'Royal Meteorological Institute of Belgium' and click 'select'
on this url
https://saml.meteo.be/saml2/idp/SSOService.php?SAMLRequest=fVJdT8MgFP0rDe9taZ12I9uS6WJcom5Zpw%2B%2BGFpuHQmFyqV%2B%2FHsZnVEf3BPh3Hs%2BOGGKvFUdW%2FRur7fw2gO66KNVGlkYzEhvNTMcJTLNW0DmalYu7m5ZnlDWWeNMbRT5RTnN4IhgnTSaRKvljDyPR3UFnFfZJC%2FOM9o0tBZFJehEZPSsyYqL80bAmBYXFYkewaJnzogX8nTEHlYaHdfOQzTPYzqKabGjY5blbESfSLT0r5Gau8DaO9chS9NDyKQFByapINzyVIouLct1CfZN1pB0%2B45Ei%2B%2BoV0Zj34I9Th%2B2tz9ijVSAoAVYL6Y0uKAp287DXjltjehVEAxOKQ5nHvMaAzqw4h%2BdGL335ljspdRC6pfTnVbDErKb3W4Tb9bljsynBxcWOrLzU2Gn6e%2FN6fAb7r3HarkxStaf0bWxLXf%2FR8iSLCBSxE1YZb3GDmrZSBC%2BRqXM%2B5UF7mBGnO2BpPPB9O%2Bvm38B&RelayState=https%3A%2F%2Ffilesender.belnet.be%2F%3Fs%3Dupload&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=Ot3QhD1eUhAHNN1gwXCWu10Gqvpf5I5OUwCKCA6YqPTq8XTbjD6mKaylu%2BWnHMmTMFXRVJt4kqzA4ZyLGdPlnKxfOPdIbE3U66ZRB2fX%2FAvOsdq%2FoEDZNNw2n5m7nXWpz51g9cQ6LjwwVfPWP%2Bn2BWDKRI1otkQrnu%2BJKp%2Bx9NckeB5NH433CUIo0iZbRvr3kNveX6t5TMhDAXfxkdj%2ByvK3Fe6scQCFzB9LQNGRTRXgteQFArj49VKN3kiG365Ptt7Zgl3G11M8%2BpiS%2BFW8LIqrmo0mpP7SFfpbqQWil54UD%2F3zRjYR8GXP80gKMab4qieZJvgF4UvtL5%2Fw0eX6WdwFfr1Mz5lLwIxBrT4FOFYUlnHCTbN%2BQGAJQHIdwX6OJSbfMKprg2mBQT665WvmfDMj53mFyK1nwOqdHmaKJIB%2BA1CQ%2F7aSnAZqgD0jn2vRmW5EJi37GyzlPESpjaJiQ8CRN4VqYN4Ma0hHJ9OpCh4z%2FM54MzE1XsZhxmTXXpYvNciS4tS9GMh2chr9kcv2TTLuyOSVR5ABIqiEH9VltR6VdW0jmWL774%2FBUNpS%2BnlSvxY6MJBl2n2oCD795vummS2o6RsHMsO%2B4UGlQzzLnJJWv2CU5aq3gOcLQSggwRFhjqhNjBZR%2BhgAm6A5Cj55gjvQXw6BtYXHE0EIdL6h3EA%3D

Unhandled exception
An unhandled exception was thrown.
If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator:

b473a4ecfe￼￼
How to get help
This error probably is due to some unexpected behaviour or to misconfiguration of SimpleSAMLphp. Contact the administrator of this login service, and send them the error message above.

**Expected behavior**
able to login via our ldap and use the filesender

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.

**Additional context**

The log directory  in simplesaml is empty, and no relevant error found elsewhere

**Comment by tvdijen** [comment]
Hi @jringoot !  Apparently "Royal Meteorological Institute of Belgium" has an issue with their SimpleSAMLphp installation.. You should contact their helpdesk.. It's not something we can help you with.

**Comment by jringoot** [comment]
Hi  @tvdijen thanks for reaching out.

Well, it is me the sysadmin of "Royal Meteorological Institute of Belgium", I am trying to set up the connection to the federation as Identity provider.
Could you give me a hand or a direction in troubleshooting this?
(where can I get more details about the issue? logfile is empty)
Thanks a lot.

Joost

**Comment by tvdijen** [comment]
Sorry Joost, I totally missed that last line about the log file!
Tell me a bit more about your setup.. Windows / Linux? Apache/Nginx? PHP-module or PHP-FPM?

**Comment by jringoot** [comment]
> Sorry Joost, I totally missed that last line about the log file! Tell me a bit more about your setup.. Windows / Linux? Apache/Nginx? PHP-module or PHP-FPM?

Ubuntu 20.04
apache 2
apache2/focal-updates,focal-security,now 2.4.41-4ubuntu3.10 amd64 [installed]
  Apache HTTP Server
openssl/focal-updates,focal-security,now 1.1.1f-1ubuntu2.12 amd64 [installed,automatic]
  Secure Sockets Layer toolkit - cryptographic utility
php7.4/focal-updates,focal-security,now 7.4.3-4ubuntu2.10 all [installed]
  server-side, HTML-embedded scripting language (metapackage)

from 
/etc/apache2/sites-enabled/000-default.conf 
`
LoadModule ssl_module modules/mod_ssl.so
LoadModule php7_module modules/libphp7.4.so
`
apt update
Hit:1 http://be.archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://be.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:3 http://be.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:4 http://be.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 http://be.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [1,711 kB]
Get:6 http://be.archive.ubuntu.com/ubuntu focal-updates amd64 Contents (deb) [110 MB]
Get:7 http://be.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [916 kB]
Get:8 http://be.archive.ubuntu.com/ubuntu focal-security amd64 Contents (deb) [99.9 MB]
Fetched 213 MB in 36s (5,920 kB/s)                                                                                                 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.

**Comment by jringoot** [comment]
tail /var/log/apache2/error.log

[Thu Apr 07 08:12:40.130859 2022] [php7:notice] [pid 1413] [client 192.168.20.153:44930] simplesamlphp ERR [b473a4ecfe] Caused by: Exception: Metadata for the entity [https://filesender.belnet.be] expired 450759 seconds ago., referer: https://ds.belnet.be/
[Thu Apr 07 08:12:40.130865 2022] [php7:notice] [pid 1413] [client 192.168.20.153:44930] simplesamlphp ERR [b473a4ecfe] Backtrace:, referer: https://ds.belnet.be/
[Thu Apr 07 08:12:40.130871 2022] [php7:notice] [pid 1413] [client 192.168.20.153:44930] simplesamlphp ERR [b473a4ecfe] 3 /var/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:329 (SimpleSAML\\Metadata\\MetaDataStorageHandler::getMetaData), referer: https://ds.belnet.be/
[Thu Apr 07 08:12:40.130877 2022] [php7:notice] [pid 1413] [client 192.168.20.153:44930] simplesamlphp ERR [b473a4ecfe] 2 /var/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:363 (SimpleSAML\\Metadata\\MetaDataStorageHandler::getMetaDataConfig), referer: https://ds.belnet.be/
[Thu Apr 07 08:12:40.130882 2022] [php7:notice] [pid 1413] [client 192.168.20.153:44930] simplesamlphp ERR [b473a4ecfe] 1 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php:381 (SimpleSAML\\Module\\saml\\IdP\\SAML2::receiveAuthnRequest), referer: https://ds.belnet.be/
[Thu Apr 07 08:12:40.130888 2022] [php7:notice] [pid 1413] [client 192.168.20.153:44930] simplesamlphp ERR [b473a4ecfe] 0 /var/simplesamlphp/www/saml2/idp/SSOService.php:26 (N/A), referer: https://ds.belnet.be/
[Thu Apr 07 08:12:40.130910 2022] [php7:notice] [pid 1413] [client 192.168.20.153:44930] simplesamlphp ERR [b473a4ecfe] Error report with id be303599 generated., referer: https://ds.belnet.be/
root@saml-me:/var/log/apache2#

**Comment by jringoot** [comment]
this is from /var/log/apache2/error.log after most recent authentication attempt, this is even before authentication

> [Thu Apr 07 09:21:28.428256 2022] [php7:warn] [pid 1414] [client 192.168.20.153:46248] PHP Warning:  session_create_id(): Failed to create new ID in /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 173, referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428468 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] SimpleSAML\\Error\\Exception: Error 2 - session_create_id(): Failed to create new ID at /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:173, referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428507 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] Backtrace:, referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428528 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 8 /var/simplesamlphp/www/_include.php:44 (SimpleSAML_error_handler), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428561 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 7 [builtin] (session_create_id), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428582 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 6 /var/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php:173 (SimpleSAML\\SessionHandlerPHP::newSessionId), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428600 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 5 /var/simplesamlphp/lib/SimpleSAML/Session.php:171 (SimpleSAML\\Session::__construct), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428617 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 4 /var/simplesamlphp/lib/SimpleSAML/Session.php:299 (SimpleSAML\\Session::getSessionFromRequest), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428643 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 3 /var/simplesamlphp/lib/SimpleSAML/Auth/Simple.php:53 (SimpleSAML\\Auth\\Simple::__construct), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428662 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 2 /var/simplesamlphp/lib/SimpleSAML/IdP.php:106 (SimpleSAML\\IdP::__construct), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428685 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 1 /var/simplesamlphp/lib/SimpleSAML/IdP.php:139 (SimpleSAML\\IdP::getById), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428703 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 0 /var/simplesamlphp/www/saml2/idp/SSOService.php:23 (N/A), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.428721 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp WARNING [482c68f58a] Secure session ID generation failed, falling back to custom ID generation., referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430648 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] SimpleSAML\\Error\\Error: UNHANDLEDEXCEPTION, referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430709 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] Backtrace:, referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430735 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 1 /var/simplesamlphp/www/_include.php:17 (SimpleSAML_exception_handler), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430755 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 0 [builtin] (N/A), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430774 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] Caused by: Exception: Metadata for the entity [https://filesender.belnet.be] expired 454887 seconds ago., referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430806 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] Backtrace:, referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430825 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 3 /var/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:329 (SimpleSAML\\Metadata\\MetaDataStorageHandler::getMetaData), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430846 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 2 /var/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:363 (SimpleSAML\\Metadata\\MetaDataStorageHandler::getMetaDataConfig), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430879 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 1 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php:381 (SimpleSAML\\Module\\saml\\IdP\\SAML2::receiveAuthnRequest), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430902 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] 0 /var/simplesamlphp/www/saml2/idp/SSOService.php:26 (N/A), referer: https://filesender.belnet.be/
> [Thu Apr 07 09:21:28.430963 2022] [php7:notice] [pid 1414] [client 192.168.20.153:46248] simplesamlphp ERR [482c68f58a] Error report with id 68534b98 generated., referer: https://filesender.belnet.be/
> 
> 
>

**Comment by tvdijen** [comment]
Right, so the key here is "Exception: Metadata for the entity [https://filesender.belnet.be] expired 450759 seconds ago".
Metadata usually has a lifetime of several hours.. You can do two things:

- In `metadata/saml20-sp-remote.php` find the entry for `https://filesender.belnet.be` and remove the `expire` key.. Their metadata will be valid forever.
- Configure the metarefresh-module to automatically collect their metadata every x hours.

**Comment by jringoot** [comment]
There is no entry for filesender in saml20-sp-remote.php

 cat /var/simplesamlphp/metadata-templates/saml20-sp-remote.php
```
<?php

/**
 * SAML 2.0 remote SP metadata for SimpleSAMLphp.
 *
 * See: https://simplesamlphp.org/docs/stable/simplesamlphp-reference-sp-remote
 */

/*
 * Example SimpleSAMLphp SAML 2.0 SP
 */
$metadata['https://saml2sp.example.org'] = [
    'AssertionConsumerService' => 'https://saml2sp.example.org/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp',
    'SingleLogoutService' => 'https://saml2sp.example.org/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp',
];

/*
 * This example shows an example config that works with Google Workspace (G Suite / Google Apps) for education.
 * What is important is that you have an attribute in your IdP that maps to the local part of the email address at
 * Google Workspace. In example, if your Google account is foo.com, and you have a user that has an email john@foo.com, then you
 * must set the simplesaml.nameidattribute to be the name of an attribute that for this user has the value of 'john'.
 */
$metadata['google.com'] = [
    'AssertionConsumerService' => 'https://www.google.com/a/g.feide.no/acs',
    'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    'simplesaml.nameidattribute' => 'uid',
    'simplesaml.attributes' => false,
];

$metadata['https://legacy.example.edu'] = [
    'AssertionConsumerService' => 'https://legacy.example.edu/saml/acs',
    /*
     * Currently, SimpleSAMLphp defaults to the SHA-256 hashing algorithm.
     * Uncomment the following option to use SHA-1 for signatures directed
     * at this specific service provider if it does not support SHA-256 yet.
     *
     * WARNING: SHA-1 is disallowed starting January the 1st, 2014.
     * Please refer to the following document for more information:
     * http://csrc.nist.gov/publications/nistpubs/800-131A/sp800-131A.pdf
     */
    //'signature.algorithm' => 'http://www.w3.org/2000/09/xmldsig#rsa-sha1',
];

```

**Comment by jringoot** [comment]
I added this at the end of that file and restarted apache
```
$metadata['filesender.belnet.be'] = [
    'AssertionConsumerService' => 'https://filesender.belnet.be',
    'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
    'simplesaml.nameidattribute' => 'uid',
    'simplesaml.attributes' => false,
];

```
still same error

```

[Thu Apr 07 10:08:08.679127 2022] [mpm_prefork:notice] [pid 2516] AH00169: caught SIGTERM, shutting down
[Thu Apr 07 10:08:10.364845 2022] [so:warn] [pid 2575] AH01574: module ssl_module is already loaded, skipping
[Thu Apr 07 10:08:10.364899 2022] [so:warn] [pid 2575] AH01574: module php7_module is already loaded, skipping
[Thu Apr 07 10:08:10.389194 2022] [mpm_prefork:notice] [pid 2576] AH00163: Apache/2.4.41 (Ubuntu) OpenSSL/1.1.1f configured -- resuming normal operations
[Thu Apr 07 10:08:10.389381 2022] [core:notice] [pid 2576] AH00094: Command line: '/usr/sbin/apache2'
[Thu Apr 07 10:09:08.690219 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] SimpleSAML\\Error\\Error: UNHANDLEDEXCEPTION, referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690333 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] Backtrace:, referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690359 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] 1 /var/simplesamlphp/www/_include.php:17 (SimpleSAML_exception_handler), referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690379 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] 0 [builtin] (N/A), referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690394 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] Caused by: Exception: Metadata for the entity [https://filesender.belnet.be] expired 457747 seconds ago., referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690414 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] Backtrace:, referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690432 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] 3 /var/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:329 (SimpleSAML\\Metadata\\MetaDataStorageHandler::getMetaData), referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690451 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] 2 /var/simplesamlphp/lib/SimpleSAML/Metadata/MetaDataStorageHandler.php:363 (SimpleSAML\\Metadata\\MetaDataStorageHandler::getMetaDataConfig), referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690469 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] 1 /var/simplesamlphp/modules/saml/lib/IdP/SAML2.php:381 (SimpleSAML\\Module\\saml\\IdP\\SAML2::receiveAuthnRequest), referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690488 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] 0 /var/simplesamlphp/www/saml2/idp/SSOService.php:26 (N/A), referer: https://filesender.belnet.be/
[Thu Apr 07 10:09:08.690526 2022] [php7:notice] [pid 2577] [client 192.168.20.153:47536] simplesamlphp ERR [482c68f58a] Error report with id 419c0c3c generated., referer: https://filesender.belnet.be/
```
still same error

**Comment by tvdijen** [comment]
Then how did you connect your IDP to Filesender? you must have exchanged metadata somehow?

**Comment by jringoot** [comment]
> Then how did you connect your IDP to Filesender? you must have exchanged metadata somehow?
I uploaded the metadata to
https://federation.belnet.be/md-mgmt/apply/

**Comment by tvdijen** [comment]
You must have imported something in SimpleSAMLphp as well..  Otherwise it wouldn't complain about expired metadata..

**Comment by jringoot** [comment]
@tvdijen it looks resolved and it appears that this is what did it:
I had to refress the metadata from belnet federation sp on our server after uploading our metadata to them.

https://saml.meteo.be/module.php/metarefresh/fetch.php

Thanks a lot for the help

**Comment by tvdijen** [comment]
Glad it got resolved!!
It is usual to do this automatically using a cron job.
