### ISSUE TITLE
Demo site Logout not working properly

### ISSUE THREAD

**Issue by chris-ryu** [simplesamlphp/simplesamlphp#1620]
**Describe the bug**
When I select IdP again after clicking the logout button on the Demo site, I do not go to the IdP login page and enter the authentication completed state immediately.

**To Reproduce**
0. After login Idp successfully in Demo site
1. Click on 'Logout'
2. Go to '[Test configured authentication sources](https://demo/simplesaml/module.php/core/authenticate.php)'
3. Click on SP (default-sp)
4. Select again same IdP
5. See Demo Example page, SAML Subject.. Auth Data

**Expected behavior**
When you click the Logout button and select the Idp again, you should be redirected to the login page of the IdP.

**Comment by thijskh** [comment]
Is it perhaps your IdP that does Single Sign On here? SSP is logged out but because your IdP implements SSO you are seamlessly relogged in.

**Comment by chris-ryu** [comment]
> Is it perhaps your IdP that does Single Sign On here? SSP is logged out but because your IdP implements SSO you are seamlessly relogged in.

When the browser is closed and turned on again, it is redirected to the IdP login page normally.
If so, shouldn't it be assumed that I'm logged out of SSP?

**Comment by tvdijen** [comment]
I think your demo-site is only logging you out locally and not using single logout..

**Comment by thijskh** [comment]
I'd advise to use your browser's debug toolbar, Network tab, it will likely show that you _are_ redirected to the IdP again, however this IdP performs SSO so immediately reauthenticates you.

**Comment by chris-ryu** [comment]
I'm not testing my custom SP, but  SimpleSamlPHP's Demo Example page.
![image](https://user-images.githubusercontent.com/1624211/163576520-ce94f10a-1a9a-465f-8008-83d394a3617a.png)

Dose this Logout button only make local logout not idp SSO ?

**Comment by chris-ryu** [comment]
I think my SimpleSamlPHP site have trouble with PHP session handling.
Log file 

Apr 15 22:24:08 simplesamlphp ERROR [TR93105f84] Error loading session: Cannot load PHP session with a specific ID.
Apr 15 22:24:11 simplesamlphp WARNING [6d7d31b151] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 15 22:24:11 simplesamlphp WARNING [6d7d31b151] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 15 22:24:12 simplesamlphp WARNING [6d7d31b151] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 15 22:24:13 simplesamlphp WARNING [TRf858b9ae] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 15 22:24:13 simplesamlphp ERROR [TRf858b9ae] Error loading session: Cannot load PHP session with a specific ID.
Apr 15 22:24:14 simplesamlphp WARNING [6d7d31b151] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 15 22:24:14 simplesamlphp WARNING [6d7d31b151] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 15 22:24:17 simplesamlphp WARNING [6d7d31b151] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 15 22:24:17 simplesamlphp WARNING [6d7d31b151] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 15 22:24:17 simplesamlphp WARNING [6d7d31b151] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 15 22:24:17 simplesamlphp WARNING [6d7d31b151] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.

**Comment by thijskh** [comment]
Have you done what I suggested?

**Comment by tvdijen** [comment]
You are running an extremely old version of SimpleSAMLphp.. Maybe it's a bug that was already fixed on a newer version..

**Comment by chris-ryu** [comment]
> 

1.19.5

> I'd advise to use your browser's debug toolbar, Network tab, it will likely show that you _are_ redirected to the IdP again, however this IdP performs SSO so immediately reauthenticates you.

I was able to check the flow exactly the same in the network tab as you advised.
If so, is the IdP logout not executed properly?

**Comment by chris-ryu** [comment]
> You are running an extremely old version of SimpleSAMLphp.. Maybe it's a bug that was already fixed on a newer version..

I'm using 1.19.5 latest version..
![image](https://user-images.githubusercontent.com/1624211/163593010-349cfb6c-10fd-4717-a130-b4155da2aa0e.png)

**Comment by chris-ryu** [comment]
I tried turning on the Debug log and logging the logout situation.
 namespaces, please use 'SimpleSAML\Logger'.
Apr 16 20:24:47 simplesamlphp DEBUG [0596541c58] Session: Valid session found with 'default-sp'.
Apr 16 20:24:47 simplesamlphp DEBUG [0596541c58] Session: doLogout('default-sp')
Apr 16 20:24:47 simplesamlphp DEBUG [0596541c58] Session: 'default-sp' not valid because we are not authenticated.
Apr 16 20:24:47 simplesamlphp DEBUG [0596541c58] Saved state: '_e00adaf8e21fabddf7049cefa91670d5fc2e81d289'
**Apr 16 20:24:47 simplesamlphp INFO [0596541c58] No logout endpoint for IdP 'https://idp.xxxxxx/idp/shibboleth'.**
Apr 16 20:24:47 simplesamlphp WARNING [0596541c58] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Apr 16 20:24:47 simplesamlphp DEBUG [0596541c58] Localization: using old system
Apr 16 20:24:47 simplesamlphp DEBUG [0596541c58] Translate: Reading dictionary [/var/simplesamlphp/dictionaries/logout]

"No logout endpoint for IdP.." message is showing.
Do you have any advice for this message cause?

**Comment by tvdijen** [comment]
It means the metadata didn't provide an endpoint for Single logout.. This means that your Shibboleth IDP doesn't support SLO, or it wasn't configured.

**Comment by chris-ryu** [comment]
Thank you
I just find Shibboleth generated metadata has SingleLogoutService tags commented out.
