### ISSUE TITLE
Can we please have a composer update?

### ISSUE THREAD

**Issue by murraycollingwood** [simplesamlphp/simplesamlphp#1624]
I've been regularly running my composer update to ensure I have the latest PHP libraries.

My composer entry looks like this:
```
       "simplesamlphp/simplesamlphp": "@stable",
```

My current version
```
name     : simplesamlphp/simplesamlphp
descrip. : A PHP implementation of a SAML 2.0 service provider and identity provider, also compatible with Shibboleth 1.3 and 2.0.
keywords : SAML2, idp, oauth, shibboleth, sp, ws-federation
versions : * v1.15.4
```

So when a small problem has appeared and I go looking for answers, I find that I'm way behind the current version: 1.19

What's the solution here?  
a) Do I stop using composer and just download the library manually?
b) Do we get regular updates to the composer download, marked stable?
c) Something else?

(I should add I have multiple servers to be updated, so composer has been excellent in this regard.  Installing the software manually on each one sound time consuming)

**Comment by tvdijen** [comment]
Hi @murraycollingwood !  I'm not sure why this isn't working for you..
I just did a test in an empty composer project and ran `composer require simplesamlphp/simplesamlphp:@stable` and it just downloaded the latest version.

**Comment by murraycollingwood** [comment]
Hi @tvdijen 
Sorry, I'm still learning the intricacies of 'composer'. There is a difference between:
```
composer update simplesamlphp/simplesamlphp
```
and
```
composer update
```
The latter worked fine.  
Thank you.

**Comment by tvdijen** [comment]
Composer will consider all dependencies, so it will not just update `simplesamlphp/simplesamlphp` to a newer version, if other packages rely on an older version. `composer update` will check interoperability for all your dependencies and gets you the best possible result. It seems like one of your other dependencies required v1.15.4 and kept composer from updating?
