### ISSUE TITLE
PairwiseID

### ISSUE THREAD

**Issue by arnoschneid** [simplesamlphp/simplesamlphp#1626]
Is the core:PairwiseID filter removed in Version 1.19.5? The release notes of version 1.19.1 says that the filter is added and in the following releases is no note that the filter is removed.

**Comment by tvdijen** [comment]
Hi @arnoschneid ! They should have probably never ended up in 1.19.1.
We have moved the SubjectID and PairwiseID to a separate [module](https://github.com/simplesamlphp/simplesamlphp-module-subjectidattrs). Sorry for the confusion!
