### ISSUE TITLE
Configure log for AWS Cloudwatch

### ISSUE THREAD

**Issue by nicofari** [simplesamlphp/simplesamlphp#1628]
I have an application deployed on AWS platform and a requirement to use AWS Cloudwatch as log target.
Would it be possible to configure this?
thanks a lot in advance

**Comment by nicofari** [comment]
I have found this solution:
in config you can specify a custom logger class.
So I have created a class implementing SimpleSAML\Logger\LoggingHandlerInterface which implements my logic in log() method. and I have specified this class in config:

    'logging.level' => SimpleSAML\Logger::DEBUG,
//    'logging.handler' => 'file',
    'logging.handler' => 'MyApp\Resolvers\shared\Services\SamlCloudwatchLogger',

I write down this for, perhaps, feedback from people more expert of this library, and also to let  other people that may be interested into this in the future.
bye

**Comment by thijskh** [comment]
That seems like exactly what this config option `logging.handler` was designed to be for. Thanks for reporting back, indeed people should be able to find this issue if they are searching for this specific use case.
