### ISSUE TITLE
Translation, pot, po and mo files

### ISSUE THREAD

**Issue by liedekef** [simplesamlphp/simplesamlphp#1630]
Currently in the old layout you have the translation "definition" json files and in the new layout simplesamlphp uses po files.
However: I see no use of mo files (compiled po files) which are much faster to use, and when you combine a po-file with a pot-file (pot=po template), you get an mo-file that uses the pot-definition for the non-translated strings (which is one of the things simplesamlphp wants to accomplish).
Also the code currently uses a structure as core/locales/<LANGUAGE>/LC_MESSAGES/core.po, which is way too much in my opinion, just using core/locales/<LANGUAGE>.po is more than sufficient and drops 2 directories. Per module the pot-file should always be included in the distribution, so people can then contribute po-files using tools like poedit easily.
(btw: this is my experience as a wordpress plugin developer talking).

**Comment by tvdijen** [comment]
Thanks @liedekef ! I agree that the current implementation is sub-optimal.. Any contributions would be more than welcome!

**Comment by tvdijen** [comment]
@liedekef How does Wordpress deal with .pot-files? I've been looking into this and it seems gettext doesn't have any functionality to deal with them...

**Comment by liedekef** [comment]
wordpress doesn't deal with pot-files. pot-files are po-template filesn so in fact what you normally do:
1) you generate a pot-file based on your sourcode (the strings you want translated). The strings in your sourcode are typically already the english-text variant, so your pot-file then contains english strings as "basis". You can even (based on the convention/function you put into place in your code concerning strings to be translated) add context, so people know that some words need to be translated differently based on the extra context given.
So you could (like wordpress has), have a function __() that has a string to be translated as an argument (and possibly the context as another, or you create a second function that has context as a second argument, wordpress has several such functions in fact)
), create/use a tool hat parses your php-files to search for this function-call so you have the strings and then create the pot-file (I think poedit can do this).
2) using a tool like poedit (or online tools), you open the pot-file and translate each string into your language of choice and save it as a .po-file (no .pot). When new strings appear in the pot-file, you can then open the .po-file and "load" the pot-file (so you can then see which strings are yet to be translated)
3) poedit (and others) also generate an .mo-file (mostly done automatically), which is a compiled po-file. And gettext can directly use these, see: https://www.php.net/manual/en/function.gettext.php

Now, wordpress uses some custom stream-class to open the mo-files in a way so t can cache them (google "php pomo"), but in the end it is just gettext too :-)
