### ISSUE TITLE
Change logging to use DateTime::format instead of strftime (SSP < 2.0)

### ISSUE THREAD

**Issue by areis422** [simplesamlphp/simplesamlphp#1636]
**Describe the bug**
config.php -> logging.format does not allow milliseconds due to use of strftime in logging handlers. strftime is also deprecated in PHP > 8. replace with DateTime object or date_format function call

**Deployment**
Apache 2.4.53 (mpm_event)
PHP 7.4.29 (FPM)
SimpleSamlPHP 1.19.5

**To Reproduce**
1. Change logging.format to include .%v after %S
2. Save, run login
3. check log file, timestamp contains literal $v

**Expected behavior**
Log file shows time in milliseconds (or microseconds if using u instead of v)

**Additional Context**
When using log aggregation tools like Splunk, having milliseconds, at the very least, would have tremendous baring on being able to sort events accurately, instead of having a glob of log entries in a second timeframe. Also, would progress full PHP 8+ compatibility. DateTime::Format and date_format has been available since PHP 5.2.1. Related to #1584 . Is it possible to have this backported to 1.19.6+?

**Suspected update locations**
lib/SimpleSAML/Logger.php
lib/SimpleSAML/Logger/FileLoggingHandler.php

**References:**
[DateTime on php.net](https://www.php.net/manual/en/datetime.format.php)
[strftime on php.net](https://www.php.net/manual/en/function.strftime)

**Comment by thijskh** [comment]
We have fixed this in SSP 2.0. strftime is perfectly compatible with PHP8, and as far as I know there's no known date/version where it will be removed, I suspect that it will not be before PHP9.

Since the config file format is related to strftime's format, this cannot be backported since it would break existing config files. So it seems accurate to fix this in 2.0. I think we'd best focus our efforts on releasing that instead of making invasive changes to the current branch.

**Comment by nathanjrobertson** [comment]
With PHP 8.1 and simpleSAMLphp 1.19.6 you get lots of this in the logs:

Deprecated: Function strftime() is deprecated in /[...]/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Logger/FileLoggingHandler.php on line 120

So strftime() is deprecated as of PHP 8.1, but they haven't announced when it will be removed.

**Comment by thijskh** [comment]
Yes, so this doesn’t hurt a bit?

**Comment by nathanjrobertson** [comment]
Yeah, it does. When configured to print warnings to the screen (in your dev environment), you get a lot of the above message, followed by this:

```
Warning: Cannot modify header information - headers already sent by (output started at /[...]/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Logger/FileLoggingHandler.php:120) in /[...]/vendor/simplesamlphp/simplesamlphp/templates/includes/header.php on line 39
```

Then a stacktrace.
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML\Error\CannotSetCookie: Headers already sent.
Backtrace:
7 lib/SimpleSAML/Utils/HTTP.php:1313 (SimpleSAML\Utils\HTTP::setCookie)
6 lib/SimpleSAML/Session.php:690 (SimpleSAML\Session::doLogin)
5 modules/saml/lib/Auth/Source/SP.php:1206 (SimpleSAML\Module\saml\Auth\Source\SP::handleUnsolicitedAuth)
4 modules/saml/lib/Auth/Source/SP.php:1246 (SimpleSAML\Module\saml\Auth\Source\SP::onProcessingCompleted)
3 modules/saml/lib/Auth/Source/SP.php:1166 (SimpleSAML\Module\saml\Auth\Source\SP::handleResponse)
2 modules/saml/www/sp/saml2-acs.php:269 (require)
1 lib/SimpleSAML/Module.php:266 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)
```

So yeah, a working SP configuration on PHP 8.0 breaks on 8.1 due to a deprecation.

I'm happy to have a go at creating a PR against 1.19 if it'll be considered for merging and release (I'm aware 2.0 is close, so understand if that's not of interest).

**Comment by tvdijen** [comment]
That's because PHP 8.1 changed the default value for the `error_reporting` ini-setting to include deprecations and treat them as errors. It really is a ridiculous change... You could change it back to what it was on your dev-box

**Comment by nathanjrobertson** [comment]
I can't see any change in the default php.ini value for `error_reporting` between 8.0 and 8.1 (at least in the official Docker images):

```
nathanr@indigo:~$ docker run -it --rm php:8.0-fpm grep error_reporting /usr/local/etc/php/php.ini-development
; error_reporting
error_reporting = E_ALL
nathanr@indigo:~$ docker run -it --rm php:8.1-fpm grep error_reporting /usr/local/etc/php/php.ini-development
; error_reporting
error_reporting = E_ALL
nathanr@indigo:~$ docker run -it --rm php:8.0-fpm grep error_reporting /usr/local/etc/php/php.ini-production
; error_reporting
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
nathanr@indigo:~$ docker run -it --rm php:8.1-fpm grep error_reporting /usr/local/etc/php/php.ini-production
; error_reporting
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
nathanr@indigo:~$
```

**Comment by tvdijen** [comment]
My bad, the change I was referring to was between 7.4 and 8.0;  https://php.watch/versions/8.0/error-display-E_ALL

**Comment by thijskh** [comment]
In any case, this is not possible to change this in 1.19 because it's a breaking change for production installations. Since the deprecation problem only exists on dev environments it makes sense to me to adjust your logging there to deal properly with deprecation messages.

**Comment by nathanjrobertson** [comment]
Interestingly enough, the official Docker images for PHP 7.4 changed the default php.ini values as well:

```
nathanr@indigo:~$ docker run -it --rm php:7.4-fpm grep error_reporting /usr/local/etc/php/php.ini-development
; error_reporting
error_reporting = E_ALL
; Eval the expression with current error_reporting().  Set to true if you want
; error_reporting(0) around the eval().
nathanr@indigo:~$ docker run -it --rm php:7.4-fpm grep error_reporting /usr/local/etc/php/php.ini-production
; error_reporting
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
; Eval the expression with current error_reporting().  Set to true if you want
; error_reporting(0) around the eval().
nathanr@indigo:~$
```

Yep, that's all fine. At least it'll be indexed by Google so people know the answer. I'm going to stick with 7.4 or 8.0 to avoid the warning all together, then upgrade to PHP 8.1 when SimpleSAMLphp 2.0 is released. Fortunately I run ssphp in containers, so switching between versions of PHP isn't a big deal.

Thanks for your help and advice. Much appreciated.
