### ISSUE TITLE
Extract the aselect module out of the repository

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#165]
It should get its own repository and allow installation through composer. Is it still in use? @pmeulen @joostd is there anybody still using this?

**Comment by joostd** [comment]
Yes, there are a few universities in the Netherlands that rely on this module for connecting to the national Higher Ed. federation.

**Comment by jaimeperez** [comment]
So is it reasonable to move it out to its own repo and use composer to install it? I'm trying to push a bit with the cleanse for 2.0 and this module is on the list of candidates to be extracted out of the main distribution...

**Comment by joostd** [comment]
Yes, I think a separate repo makes sense.

**Comment by thijskh** [comment]
UvT uses it and has done the most work on it recently, so maybe they can host it @wsldankers?

**Comment by thijskh** [comment]
I've talked a bit about it with Wessel and he's thinks if needed he can find a place to host it, but wonders, since the module is quite simple and uninvolved, if the maintenance burden is actually that significant that it would be a net benefit to moving it out of the repository.

**Comment by jaimeperez** [comment]
Thanks for taking a look into this @thijskh!

There's no burden at all with the module, it just works and I can't even remember any single issue with it. The thing here is that we're trying to make SimpleSAMLphp as lightweight as possible, removing old and unused stuff, and extracting things that are unused by the majority of our users. Since we moved to composer and Olav made the module installer, it's quite easy to install modules in an automated way, so now it's more reasonable to ship a package with the things most people will use, and let everything else be installed by those who actually need it.

Another argument in favor of extracting some modules is that it's way easier to maintain them, since those more actively involved can control their own development, make new releases and update their modules without us being involved and (for most of the time) delaying the process.

We don't really need a place where to host the module, we already have it: github. The idea is to move the module to a separate repo of its own, make it installable through composer, and if possible add somebody who knows about it as an owner, so that someone can maintain it properly.

**Comment by jaimeperez** [comment]
@thijskh, a brief update on this. Is there any organization in github where you would like to host the module? I thought you might want to have it under SURFnet's umbrella, but if not, we can put it under `simplesamlphp/` and I'll add as an admin whoever wants to work on it.

**Comment by thijskh** [comment]
@wsldankers has put it on his todo list and will look for a suitable place, he's welcome at `github.com/SURFnet` if needed

**Comment by thijskh** [comment]
This is now hosted on https://non-gnu.uvt.nl/simplesamlphp-aselect/
@jaimeperez Can you add a link from the modules webpage?

**Comment by jaimeperez** [comment]
Thanks Thijs!

Where is the source code for the module hosted? It would be nice if the module was also installable through composer, as with other modules, so that we keep the way to install modules as homogeneous as we can...

**Comment by jaimeperez** [comment]
Besides, if we have the module's code here in github, I can make sure to provide pull requests when something changes in the core API, so that the module can easily be updated to work with the latest versions of SimpleSAMLphp.

**Comment by wsldankers** [comment]
You can send your patches to the address listed on that web page.

**Comment by jaimeperez** [comment]
Hi @wsldankers!

Unfortunately, preparing patches over code that's not in version control and sending them out to you personally, is not as reliable and straightforward as committing the changes to your own fork and clicking on the "Create Pull Request" button... :cry:

**Comment by wsldankers** [comment]
Well I never was a proponent of removing it from the main SSP repository anyway…

**Comment by jaimeperez** [comment]
When I opened this issue, I started **asking** the status of the module, how many people was still using it, and **if it made sense** to remove it from the standard distribution because it was not commonly used by most of our users.

After agreeing on that (nobody complained), I **suggested** to move it to its own repository here in github, as we've done with many other modules, which is also a quite simple process. I even suggested to host it under the SimpleSAMLphp organization, and adding whoever could or would be willing to help with the module as an admin to the new repo. I could have happily done all of the work to extract the module. And I don't think it's that strange that we would like someone with knowledge to take care of a module we neither use nor understand.

Moving the module out of version control (and more specifically out of github), and making it installable only as a Debian package, has several undesired effects:

* *It's different to every other module*. This means people used to install modules in SimpleSAMLphp the way it is today will have problems installing this module. Not to mention those not using Debian. Not to mention those not even using Linux. It will just confuse your own users.
* *It's a burden for you to maintain*. Having it here in its own repo in github would practically mean no work at all. Having it outside version control or under your own version control means it's much more difficult to make changes to it.
* *It impedes collaboration*. Nobody can submit pull requests to fix things, since it's not in github. Therefore, you need to ask people to submit patches to you personally. Even in case people do so (which is becoming more and more unlikely these days), this means more work for potential collaborators (which sends them the wrong message) and more work for you (as you'll need to apply the patches manually, test them manually, commit to your own version control, if any, and release new versions, again, manually).
* *It makes it more difficult to keep up to date with SimpleSAMLphp's API*. Unfortunately, we're already lacking resources to maintain and develop the software. The idea behind making SSP lighter was to make it easier to maintain with less time. More sustainable, if you want. Impeding collaboration means we need time we don't have to help you out keep a module we don't use up to date with future changes, which I cannot guarantee is going to happen. Up until now, I've always reviewed **every extracted module** when doing changes to the API, making sure nothing breaks, and if that happens, providing pull requests to the modules so that the changes don't break them. When the modules are under the SimpleSAMLphp umbrella, or I have write access to their repos, I've done the changes myself, saving the maintainers from that burden. That won't be possible in this case.

Obviously, it's up to you to decide what you want to do with the module, and I'm terribly sorry that you are disappointed with my suggestion of extracting the module out of the standard distribution / main repository. However, I never imposed such a decision on no one, nor asked nobody to take the responsibility as a maintainer. I suggested a (IMHO) quite simple solution that would be beneficial for both those using A-Select and us maintaining SSP. I'm afraid this solution benefits nobody.

**Comment by wsldankers** [comment]
As Thijs mentioned on Jan 19, back then I already wondered if splitting out this module was really a net benefit. So yes, not a proponent (but not a very strong opponent either, because I do realise that this module is not a very commonly used one).

Could it be that our disagreement is based on a misunderstanding?

For example, it's not just installable as a debian package, there's a perfectly fine tarball that's installable on other platforms, including non-linux ones. I'm more than willing to accept other OS packaging formats (an RPM .spec file for example). I don't think language/framework/application specific packaging systems are a good idea in general, but let's leave that for a discussion over a pint of beer.

Also, it's not out of version control, it's back in the private Subversion repository that it was originally developed in. Having it in my local repository is not a burden for me to maintain, in fact it makes things easier (but just for me, I concede). Then again, we've seen very few patches over the years, I don't think sending in a patch the old-fashioned way is too much to ask.

Keeping it up to date with SimpleSAMLphp's API, for me that would be the number one reason to keep it in the main tree. In fact that's exactly what Linus does with drivers (even the obscure ones) in his kernel, and for the same reason too.

I'll gladly cooperate whether you decide to remove the module or not, but I still think keeping this module in-tree would be most beneficial to for both those using A-Select and to those maintaining SSP and its API. Until now Thijs has been most kind in providing me with a heads-up whenever there was an issue around this module, so I can't claim it has been cumbersome for me either.

**Comment by jaimeperez** [comment]
Hi @wsldankers.

Let's assume then this was a misunderstanding, and agree to discuss it further over a beer. I'll be traveling to the Netherlands at least twice in the next few months, so that could be an option :wink: 

In any case, if you are ok with keeping up to date and managing the module this way, that's obviously your call. I'll list the module in the website and point to the URL Thijs provided before.
