### ISSUE TITLE
https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/cron/docs/cron.md

### ISSUE THREAD

**Issue by jringoot** [simplesamlphp/simplesamlphp#1652]
**Is your feature request related to a problem? Please describe.**
It is not clear to me what the cronjob does, why it is needed. 
What does it do, that can not be done with metarefresh?
It also has no output

**Describe the solution you'd like**
More explanation on what the cronjob does, eg: where is read which tasks must be done?
The ability to have verbose output like metarefresh/fetch.php does or even possibility to have more verbosity.

**Describe alternatives you've considered**
commenting out 
`\SimpleSAML\Utils\Auth::requireAdmin();`

in 
`simplesamlphproot/modules/metarefresh/www/fetch.php`
and put a curl of `https://oursamlserver.ourdomain/module.php/metarefresh/fetch.php`  in cronjob

**Additional context**
Part of the documentation is unaccessible.
https://github.com/simplesamlphp/docs/issues/6

**Comment by thijskh** [comment]
I have updated the docs of the cron module to clarify its purpose and relation to other modules e.g. metarefresh:

```
Modules, like e.g. the metarefresh module, that want to invoke tasks
on set times, can register cron hooks for use by this module. You in turn
configure your system's `cron` or other time based execution functionality
to periodically trigger this module's endpoint, so all registered hooks
will be executed at that time. This module also takes care of reporting
back the result and provides an interface in SimpleSAMLphp's admin
panel to trigger jobs manually.
```

Surely you can change metarefresh to perform cron directly on it, but the cron module is intended as the single interface to any modules requiring periodic tasks to be ran.
