### ISSUE TITLE
Migrating to 2.0: existing sessions do not load

### ISSUE THREAD

**Issue by Paragin** [simplesamlphp/simplesamlphp#1656]
**Describe the bug**

During testing I noticed that there is an migration issue with the session when moving an existing application to 2.0: If the old session doesn't contain a trackid it will keep the `trackid` unset, which later throws an error when the class tries to read it.

**To Reproduce**

- Start an authentication session with SSP v1.19 (for example with the Simple auth source)
- You are redirected the the external IDP
- Switch to SSP v2.0
- Login at your IDP

An error is thrown: `Message: Typed property SimpleSAML\Session::$trackid must not be accessed before initialization`

The error is fixed for the user by clearing cookies (which makes sure a new valid session is created).

**Expected behavior**
To be successfully logged in.

**Screenshots or logs**
Not applicable

**Additional context**
Maybe it's good to have a clear migration path for the situation in which users might be in an authentication session during the upgrade of SSP. I'm not sure if there are any other incompatible changes in the session, but ideally it would always keep working.

**Comment by tvdijen** [comment]
What are you using as a session backend?

**Comment by Paragin** [comment]
In our case we are using memcache...

**Comment by tvdijen** [comment]
OK, I've added a line to the upgrade notes.. There's not much more we can do, I think?

**Comment by Paragin** [comment]
Usually when we work with serialised data we mark it with a version number and implement a upgrade function in the unserialise function. (`if ($data['v'] ?? 0 < 1) { /* do upgrade */ }`).

In this case I think it might be worthwhile to extract the generation of the track-id from the constructor and call it from the unserialise function as well if that will make the upgrade process a bit easier. I can create a PR of course, but I'm not sure if this is the only breaking change in that sense so it might not be worth it it will break anyway further down the line.

**Comment by Paragin** [comment]
Ok, in that case I'll close the issue
