### ISSUE TITLE
Advice for generating entityID

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/simplesamlphp#1659]
As per SSP 2.0 it's compulsory for the user to configure a static entityID. This is so it does not change for unexpected or unrelated reasons and also to make it more independent of SSP itself and whatever paths that uses. We should provide some guidance as what to pick.

Some inputs:

SAML2INT provides the following advice:
> An entityID should be chosen in a manner that minimizes the likelihood of it changing for political or technical reasons, including for example a change to a different software implementation or hosting provider

Shibboleth has an entire page devoted to entity naming:
https://shibboleth.atlassian.net/wiki/spaces/CONCEPT/pages/928645134/EntityNaming

Internet2 also has extended advice:
https://spaces.at.internet2.edu/display/federation/saml-metadata-entityid

**Comment by thijskh** [comment]
Word of God (ScottK) has it that the paragraph from SAML2INT should not be construed to mean ruling out the organization's domain name. Institutions normally keep their previous domains even when changing names and the intention of the text is to provide some backing/something to point to for entity administrators to keep using the old domain name even in the case someone from marketing asks whether that should not be changed.

The internet2 advice seems sound and well-structured to me.

URNs are frowned upon (and disallowed by Internet2) because they would only qualify if the name is properly registered throughout a hierarchy or authorities (e.g. urn:mace:surf.nl:surfnet.nl:sp:something) which is bureaucratic but more importantly, the majority of entities do not even have an URN namespace to begin with. Using `urn:x-something` means the URN can be anything so there's no guarantee at all anymore of global uniqueness. `urn:x-simplesamlphp` even ties it to the specific software product in use at this time.

All in all I propose to follow the Internet2 advice. I'd put a summary/suggestion in the docs and just link to their advice for a detailed "read more".

**Comment by tvdijen** [comment]
I think the URN namespace argument goes lame, because we can use any domain in an entityID without any guarantee that it's registered and under control of the entity..  Other than that, I'm perfectly fine with the commit.

**Comment by thijskh** [comment]
You can do that, but the chance of people actually doing that is small _and_ many registering parties check on this. We can clarify a bit more that you need to actually own it.

I think it's safe to say that for most deployers they will not even have a way to get a properly registered urn in the first place, so it's not a useful path to set people on, and in any case URNs do not do better than this as compared to domain names; at best just as good.
