### ISSUE TITLE
Extract the oauth module out of the repository

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#166]
It should get its own repository and allow installation through composer. For other modules depending on this one, add a composer dependency on the module.

**Comment by tvdijen** [comment]
I have extracted it to https://github.com/simplesamlphp/simplesamlphp-module-oauth1

Right now this needs:
- Registration in packagist.org
- Testing if `composer require` produces the same modules-dir as current release does
- If tests succeed, at `git require simplesamlphp/simplesamlphp-module-oauth1` to `bin/build-release.sh`
- Removal of the module in 2.0

**Comment by jaimeperez** [comment]
Tim, wouldn't the change in the name breaking those already using the module? As far as I can see, it would be installed to `modules/oauth1`, meaning any code using it would break, because `SimpleSAML\Module\oauth\Whatever` is now `SimpleSAML\Module\oauth1\Whatever`. Or maybe I am missing something?

**Comment by tvdijen** [comment]
You're not missing something, I'm just being plain stupid...  Fixed the name back to oauth again

**Comment by tvdijen** [comment]
All done
