### ISSUE TITLE
IdP metadata not getting loaded

### ISSUE THREAD

**Issue by grawity** [simplesamlphp/simplesamlphp#1660]
Just upgraded to git master, and after commit https://github.com/simplesamlphp/simplesamlphp/commit/fc1ffee7388ae65289537ec1348d8b234068e50d the IdP is unable to find any metadata (which is just the default file-based saml20-idp-hosted.php):

```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 www/_include.php:28 (SimpleSAML_exception_handler)
1 vendor/symfony/error-handler/ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Exception: Could not find any default metadata entities in set [saml20-idp-hosted] for host [idp.nullroute.lt : idp.nullroute.lt/simplesamlphp]
Backtrace:
6 src/SimpleSAML/Metadata/MetaDataStorageHandler.php:233 (SimpleSAML\Metadata\MetaDataStorageHandler::getMetaDataCurrentEntityID)
5 modules/saml/src/Controller/WebBrowserSingleSignOn.php:132 (SimpleSAML\Module\saml\Controller\WebBrowserSingleSignOn::singleSignOnService)
4 vendor/symfony/http-kernel/HttpKernel.php:152 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 vendor/symfony/http-kernel/HttpKernel.php:74 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 vendor/symfony/http-kernel/Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
0 www/module.php:14 (N/A)
```

It seems the commit in question now sets `$entry['entityID']` instead of `$entry['entityid']` in both metadata storage handlers. Changing the code back to set the all-lowercase key makes everything work again. But I saw subsequent commits also changing entityid→entityID in some places, so I wouldn't know which direction it's actually supposed to go.

¹ (I'm following git master on my personal/test setup so that I'd be more familiar with the changes needed, when the time comes for upgrading the real IdP at work to 2.0...)

**Comment by tvdijen** [comment]
Both cases were mixed before, so I intended to change everything consistently to `entityID`
