### ISSUE TITLE
2.0: NameIDPolicy set to null on SP authsource is broken

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1668]
**Describe the bug**
Setting `'NameIDPolicy' => null` on a SAML SP authsource results in a NameIDPolicy in the AuthnRequest instead of omitting it.

**To Reproduce**
1. Configure an SP authsource with NameIDPolicy set to `null`
2. Use SAML-tracer to see the generated AuthnRequest

**Expected behavior**
The NameIDPolicy should be omitted completely

**Comment by billdacat** [comment]
This may want some better documentation or a more verbose error -- for 1.x, I was able to use a string here:

'NameIDPolicy' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'

dev-master currently throws an error, it wants an array.

An empty array works for me, but setting it to false or null will also fail, it wants that empty array.  Fortunately the error was somewhat clear with what it wanted, but maybe this will help someone else.

**Comment by billdacat** [comment]
Nevermind -- I see it in the upgrade notes now.  Must have missed that when I was searching for what else I could have done wrong with the upgrade.
