### ISSUE TITLE
Move the SimpleSAML_Auth_LDAP class

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#167]
This is actually more a collection of LDAP-related utilities, so move it to `lib/SimpleSAML/Utils/LDAP.php`. This of course needs refactoring everything using this class.

**Comment by tvdijen** [comment]
Long time since the last comment, but this is still a relevant change for 2.0

**Comment by jaimeperez** [comment]
If it's not a huge amount of work, I'd favour doing this for 2.0.

**Comment by tvdijen** [comment]
A little while back we've discussed this on Whatsapp and decided the class could move to the ldap-module, which I did. The class now only is a wrapper, redirecting to the class in the module for BC-compatibility.
For 2.0 all we have left to do is to remove `lib/SimpleSAML/Auth/LDAP.php` from this repository.
