### ISSUE TITLE
logout redirect is broken

### ISSUE THREAD

**Issue by hollyhw15** [simplesamlphp/simplesamlphp#1674]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
simplesamlphp version: 1.19 upgraded on July 1,2022
two addition module on top of it: 
[simpleSAMLphp Authentication](https://www.drupal.org/project/simplesamlphp_auth) 8.x-3.2 
[SimpleSAMLphp Custom Attribute Mapping](https://www.drupal.org/project/simplesamlphp_custom_attributes) 8.x-1.1 
Current platform to support our application: pantheon 
see screenshot one 
![Screen Shot 2022-07-29 at 10 27 03 AM](https://user-images.githubusercontent.com/69690136/181812933-37dd6540-94d8-454f-bf21-d95fd6e48e73.png)

**Describe the problem**
1. Shib log in works fine 

2. simplesamlphp_auth/local  configuration for Redirect URL after logging out is an HTTPS url, which worked as sign our current user from shibboleth, it stopped working by forwarding STTPS site to HTTP site during sign out step
should be
https://shb.ais.ucla.edu/shibboleth-idp/Logout?entityId=https://developer-stage.api.ucla.edu 
but actually it is
http://shb.ais.ucla.edu/shibboleth-idp/Logout?entityId=https://developer-stage.api.ucla.edu 
see screenshot 2 
![Screen Shot 2022-07-29 at 10 39 17 AM](https://user-images.githubusercontent.com/69690136/181814856-5eb5bd03-c8a5-4203-a05f-a225c944fad5.png)

**what I tried to fix**
after I read about this case: https://github.com/simplesamlphp/simplesamlphp/issues/450 

I have tried to change $protocol and $port, the logout took two click, first click, logout was hanging, second click, logout forward user back to host website, shib logout didn't happen at all

//$protocol = 'http://';
//$port = ':80';
$protocol = 'https://';
$port = ':443';

please advice

**Comment by tvdijen** [comment]
You should probably contact the authors of the Drupal-plugin. We didn't write it.
