### ISSUE TITLE
v2.0.0-rc1 Logout Failure

### ISSUE THREAD

**Issue by yaleman** [simplesamlphp/simplesamlphp#1676]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**

When sending a logout request from my SP, I get an error.

**To Reproduce**
1. Log into my SP
2. Log out of my SP, which sends the user to `https://<domain>/saml2/idp/SingleLogoutService.php`
3. See error

**Expected behavior**

Logout, with redirect to the specified URL.

**Screenshots or logs**

Error displayed in the UI:

```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
1 www/_include.php:31 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Error: Typed property SimpleSAML\Module\saml\Controller\SingleLogout::$idp must not be accessed before initialization
Backtrace:
1 modules/saml/src/Controller/SingleLogout.php:95 (SimpleSAML\Module\saml\Controller\SingleLogout::singleLogout)
0 www/saml2/idp/SingleLogoutService.php:20 (N/A)
            
```

**Additional context**

I'm running v2.0.0-rc1

**Comment by tvdijen** [comment]
Could you please confirm that d85d39f14557731fda6334b8d8fa7faf9ebf2448 fixes your issue?

**Comment by yaleman** [comment]
I can't run it at all on that version - hit a different bug, logged as #1680

**Comment by tvdijen** [comment]
@yaleman Was this issue resolved too?

**Comment by yaleman** [comment]
Looks like this is sorted now too, thanks.
