### ISSUE TITLE
Create an AuthMemCookie module

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#168]
This should be on its own standalone repository and installable through composer. Since the functionality is already there, it's just about moving `www/authmemcookie.php` and `lib/SimpleSAML/AuthMemCookie.php` out and creating the additional module structure.

**Comment by jaimeperez** [comment]
The module has been created, put into [its own repository](https://github.com/simplesamlphp/composer-module-installer) and made installable with composer. We now need to mark the old sources in the code base as deprecated.

**Comment by jaimeperez** [comment]
The old sources have been marked as deprecated in 88ea9b8, and the documentation updated to point to the new module.

Keeping this issue open so that we remember to remove the deprecated sources and configuration templates.

**Comment by tvdijen** [comment]
Our namespaced module is not up to date with current `master`, so we should update it before removing this module in 2.0

**Comment by tvdijen** [comment]
https://github.com/simplesamlphp/simplesamlphp-module-memcookie
