### ISSUE TITLE
2.0-rc1 broken URLs

### ISSUE THREAD

**Issue by drjayvee** [simplesamlphp/simplesamlphp#1681]
I'm describing two separate bugs which look to me to share a root cause, namely broken URL rewrites or similar.

# Issues
## Welcome page doesn't work properly
Multiple CSS and JS assets don't load because their URLs are redirected to the homepage.

The URL `/sso/assets/css/stylesheet.css` redirects to the homepage. Looking at the [source](https://github.com/simplesamlphp/simplesamlphp/tree/v2.0.0-rc1/www/assets/css), there's no such file at that location.

**To Reproduce**
1. Go to home page

**Screenshots or logs**
![image](https://user-images.githubusercontent.com/3079883/185929831-35a6e82f-61fb-4f8e-946b-78d3796c5406.png)

## Login URL doesn't work
Opening the `SimpleSAML\Auth\Simple::getLoginURL()` results in an error message:

> The given page was not found. The reason was: The URL wasn't found in the module. The URL was: https://gerben.alisqi.com.test-xxx.platformsh.site/sso/module.php/core/login/gerben?AuthId=gerben&ReturnTo=https%3A%2F%2Fgerben.alisqi.com.test-xxx.platformsh.site%2F%3Fmod%3Dlogin%26ssoLogin

It looks like the page itself is a half-processed template:
![image](https://user-images.githubusercontent.com/3079883/185931124-022cd3f3-9435-4183-83a2-d97ebeb6f3e4.png)

# Suggestions
* Does 2.0 require any additional rewrites by the web server (over 1.19)?
* Is there a build step missing? (We install SimpleSAMLphp as a composer dependency).

**Comment by tvdijen** [comment]
You forgot to run 'npm install' + 'npm run build' as described in the [documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-install-repo.html). This step is in there since 1.17, but has become mandatory in 2.0

**Comment by drjayvee** [comment]
> as described in the [documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-install-repo.html)

... which is titled "Installing SimpleSAMLphp *from the repository*" (emphasis mine). We're installing through composer, not from the repo.

> This step is in there since 1.17, but has become mandatory in 2.0

Wouldn't it make sense to document explicitly in the 2.0 changelog? It is sort of breaking in that this wasn't necessary in 1.x.

**Comment by tvdijen** [comment]
You contributions are much welcome!

**Comment by tvdijen** [comment]
I didn't fully understand the issue with using composer to pull in SSP as a dependency..
Let's use this issue to discuss how we can automatically include pre-built assets into our repository. Discussed this off-site with @jaimeperez

**Comment by drjayvee** [comment]
Should I create a separate issue for the login URL not working and amend this one to be solely about the "missing" assets?

**Comment by drjayvee** [comment]
> Could you install the assets and see if the error disappears?

Way ahead of you! :)

The error still occurs even with assets installed. See #1682.

**Comment by tvdijen** [comment]
Yeah, I see.. It's because `module.php/core/login` doesn't exist..  I would have to figure out what it's supposed to be and then fix the `getLoginURL`

**Comment by drjayvee** [comment]
Why don't I amend *this* issue to be about the assets and we deal with login URL in in #1682 ?

**Comment by tvdijen** [comment]
@dunkoh You have to build the assets by running `npm install` and `npm run build`, or use the pre-built tarball.

**Comment by dunkoh** [comment]
@tvdijen we load via composer so the npm workflow wouldn't work for our deployment model

**Comment by tvdijen** [comment]
I don't understand why you people install SSP as a composer dependency, as if it were a library...

**Comment by drjayvee** [comment]
> I don't understand why you people install SSP as a composer dependency, as if it were a library... It's a stand-alone application.

Allow me to enlighten you from a user's perspective (at least one who's not also a maintainer). For some context, my B2B SAAS company serves +-100 tenants, a dozen of which use SSO based on SimpleSAMLphp.

First off, `SimpleSAML\Auth\Simple` very much _is_ a library, as I'm sure you'd agree.

As for the rest of the application, I did use to install and maintain it separately for every tenant that used SSO, which was a _nightmare_ for several reasons:
1. Installing SimpleSAMLphp fresh for tenants was always a hassle. I had to install, `npm build`, and then use semi-manual script in our knowledge base to configure it.
2. Upgrading meant upgrading each individual installation. This could have been automated, of course, but nothing can beat `composer upgrade` in dev and `composer install` in production.
3. Synchronizing SimpleSAMLphp's dependencies (most notably Twig) with our own app's has caused some issues in the past. I can't recall how exactly, but I do remember smooth sailing since we install it as a dependency.
4. Synchronizing deployment of SimpleSAMLphp and our app was a concern.

I think all of the above can be summarized by: installing through composer is proper DevOps. No manual install or configuration, versions and config are versioned, deployment is completely automated.

I'm not saying this could not be achieved with separate installs, but using composer is that much easier.

Hope that helps!

**Comment by dunkoh** [comment]
@tvdijen our mindset is along the same lines as @drjayvee even if we don't have a lot of different client tenants to deal with.  While we have discussed internally the idea of moving it to a separate instance that has not happened yet and will take some work to untangle some things that have been in place since we started using simplesamlphp in 2017.

**Comment by tvdijen** [comment]
@drjayvee Why would you install SSP for each and every tenant? Just keep your tenant-config separated from the SSP application by using the `SIMPLESAML_CONFIG_DIR` environment variable.

I'm not saying you shouldn't use composer.. I'm saying it shouldn't be part of your application's composer-file. That also takes away all of your bullets.

**Comment by drjayvee** [comment]
> Why would you install SSP for each and every tenant?

We used to have single-tenant deploys, so we had to install SSP separately on every environment. Now that we've migrated to multi-tenant deploys, we only have a handful (one for each multi-tenant environment).

We do use `SIMPLESAML_CONFIG_DIR` (and more) to configure SSP such that we don't need to do *any* configuration in the code. Instead, our `config.php` and `authsources.php` are dynamic and depend on environment variables to add tenant IdPs.

To enable SSO for a new tenant, we only have to create a single environment variable containing the tenant's IdP metadata URL, and we're done.

This approach could most likely work just as well with SSP installed separately. However, separate install doesn't fit our deployment pipeline well. I don't want to explain why here.

Suffice it to say installing SSP as a dependency works really well currently. Installing it separately would require rework and most likely be kind of awkward.

Aside from this, I think there should be ready-to-go releases of SSP with any assets already built, instead of requiring every user to build it. In fact, I'd argue that it's a little weird for a PHP application to require NodeJS in production just so that CSS and JS can be built. (I just checked, and our app host's PHP container runs Node.js v12. We have no control over it because we're using an off-the-shelf PHP container.)

**Comment by tvdijen** [comment]
> Aside from this, I think there should be ready-to-go releases of SSP with any assets already built, instead of requiring every user to build it.

Then use the tarball? 🤷🏻‍♂️

**Comment by drjayvee** [comment]
> Then use the tarball?

I guess we could automate that. (Running `npm install` during every deployment seems like a waste of energy to me, as we very rarely switch versions.)

Alternatively, we might actually create a repo with the tarballs and publish them on packagist just so it remains easy to manage the dependency using composer.

> I don't understand why you people install SSP as a composer dependency, as if it were a library... It's a stand-alone application.

Well, the composer package does include the whole application, not just the "library" parts. Perhaps that's what's confusing to users as well. I see two possible solutions: ensure the packagist packages are pre-built, or remove the "app" parts from the package.

Our app uses composer as its sole dependency management tool (for the back end, at least), which is why very much prefer managing the dependency on SSP using composer as opposed to a separate tarball install script.

**Comment by thijskh** [comment]
You can install the tarball with composer, right?

**Comment by drjayvee** [comment]
> You can install the tarball with composer, right?

You can? How? Please enlighten me!

Just to be clear, we need both the `SimpleSAML\Auth\Simple` library (autoloaded) in our own app as well as SSP's app.

**Comment by tvdijen** [comment]
```
{
    "name": "saml/myapp",
    "type": "project",
    "require": {
      "simplesamlphp/simplesamlphp": "2.0.0-rc2"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "simplesamlphp/simplesamlphp",
                "version": "2.0.0-rc2",
                "dist": {
                    "type": "tar",
                    "url": "https://github.com/simplesamlphp/simplesamlphp/releases/download/v2.0.0-rc2/simplesamlphp-2.0.0-rc2.tar.gz"
                }
            }
        }
    ]
}

```

**Comment by tvdijen** [comment]
Will this work for you @drjayvee and @dunkoh ?

**Comment by dunkoh** [comment]
@tvdijen In theory yes it seemed like it was going to work when I tried it but there were a boat load of issues with autoloading that I was only partially able to overcome. I don't know if composer does anything different with tarball downloaded files?

We are doing something similar as of earlier this week in our nginx dockerfile to get the pre-built tarball so it would be able to load the js and css assets needed. It's a workaround but it works for now.

**Comment by tvdijen** [comment]
You have an example of those issues?  I think maybe you have to declare the namespaces manually in your composer-file..

**Comment by dunkoh** [comment]
Originally I was getting autoloading issues for SimpleSAML namespace but solved that by adding them to the composer autoload as well as specifying to read from the autoload file:
```
"autoload": {
		"psr-4": {
			"App\\": "src/",
			"SimpleSAML\\": "vendor/simplesamlphp/simplesamlphp/src/SimpleSAML",
			"SimpleSAML\\Module\\admin\\": "vendor/simplesamlphp/simplesamlphp/modules/admin/src",
			"SimpleSAML\\Module\\core\\": "vendor/simplesamlphp/simplesamlphp/modules/core/src",
			"SimpleSAML\\Module\\cron\\": "vendor/simplesamlphp/simplesamlphp/modules/cron/src",
			"SimpleSAML\\Module\\exampleauth\\": "vendor/simplesamlphp/simplesamlphp/modules/exampleauth/src",
			"SimpleSAML\\Module\\multiauth\\": "vendor/simplesamlphp/simplesamlphp/modules/multiauth/src",
			"SimpleSAML\\Module\\saml\\": "vendor/simplesamlphp/simplesamlphp/modules/saml/src"
		},
		"files": ["vendor/simplesamlphp/simplesamlphp/vendor/autoload.php"]
	},
```

I also had to require assert and saml2 libraries since it didn't have those anymore either.
```
"simplesamlphp/assert": "^0.8.0",
"simplesamlphp/saml2": "^4.6",
```

At that point the site loaded ok, but when I tried to logout/login and it actually hit the simplesaml path it is erroring about cache stuff even though we don't have anything set for caching in our config for simplesaml (it seems like it is reading whether the host is doing http_cache)

The error getting is:
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 www/_include.php:31 (SimpleSAML_exception_handler)
1 vendor/symfony/error-handler/ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Symfony\Component\ErrorHandler\Error\ClassNotFoundError: Attempted to load class "PsrCachedReader" from namespace "Doctrine\Common\Annotations".
Did you forget a "use" statement for another namespace?
Backtrace:
11 /tmp/simplesaml/cache/core/Container6MCj9Mr/SimpleSAML_KernelProdContainer.php:241 (Container6MCj9Mr\SimpleSAML_KernelProdContainer::getAnnotations_CachedReaderService)
10 /tmp/simplesaml/cache/core/Container6MCj9Mr/SimpleSAML_KernelProdContainer.php:203 (Container6MCj9Mr\SimpleSAML_KernelProdContainer::getRouting_LoaderService)
9 /tmp/simplesaml/cache/core/Container6MCj9Mr/SimpleSAML_KernelProdContainer.php:190 (Container6MCj9Mr\SimpleSAML_KernelProdContainer::getRouterService)
8 /tmp/simplesaml/cache/core/Container6MCj9Mr/SimpleSAML_KernelProdContainer.php:321 (Container6MCj9Mr\SimpleSAML_KernelProdContainer::getRouterListenerService)
7 /tmp/simplesaml/cache/core/Container6MCj9Mr/getHttpKernelService.php:21 (Container6MCj9Mr\getHttpKernelService::do)
6 /tmp/simplesaml/cache/core/Container6MCj9Mr/SimpleSAML_KernelProdContainer.php:100 (Container6MCj9Mr\SimpleSAML_KernelProdContainer::load)
5 vendor/symfony/dependency-injection/Container.php:237 (Symfony\Component\DependencyInjection\Container::make)
4 vendor/symfony/dependency-injection/Container.php:219 (Symfony\Component\DependencyInjection\Container::get)
3 vendor/symfony/http-kernel/Kernel.php:215 (Symfony\Component\HttpKernel\Kernel::getHttpKernel)
2 vendor/symfony/http-kernel/Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
0 www/module.php:14 (N/A)
```

It's possible that some dependency that was loaded via composer previously is no longer there
```
- Removing symfony/var-exporter (v5.4.10)
  - Removing symfony/twig-bridge (v5.4.14)
  - Removing symfony/framework-bundle (v5.4.14)
  - Removing symfony/cache-contracts (v2.5.2)
  - Removing symfony/cache (v5.4.15)
  - Removing seld/signal-handler (2.0.1)
  - Removing seld/phar-utils (1.2.1)
  - Removing seld/jsonlint (1.9.0)
  - Removing phpmailer/phpmailer (v6.6.5)
  - Removing justinrainbow/json-schema (5.2.12)
  - Removing gettext/translator (v1.1.1)
  - Removing gettext/languages (2.10.0)
  - Removing gettext/gettext (v5.7.0)
  - Removing composer/spdx-licenses (1.5.7)
  - Removing composer/metadata-minifier (1.0.0)
  - Removing composer/composer (2.4.4)
  - Removing composer/class-map-generator (1.0.0)
  - Upgrading cakephp/core (4.4.6 => 4.4.7): Extracting archive
  - Upgrading cakephp/utility (4.4.6 => 4.4.7): Extracting archive
  - Upgrading cakephp/datasource (4.4.6 => 4.4.7): Extracting archive
  - Upgrading composer/pcre (3.0.0 => 3.0.2): Extracting archive
  - Upgrading psr/cache (2.0.0 => 3.0.0): Extracting archive
  - Removing simplesamlphp/simplesamlphp (v2.0.0-rc2)
  - Upgrading symfony/finder (v5.4.11 => v6.1.3): Extracting archive
  - Upgrading symfony/filesystem (v5.4.13 => v6.1.5): Extracting archive
  - Upgrading symfony/console (v5.4.15 => v6.0.15): Extracting archive
  - Upgrading friendsofphp/php-cs-fixer (v3.12.0 => v3.13.0): Extracting archive
  - Upgrading symfony/yaml (v5.4.14 => v6.1.6): Extracting archive
  - Upgrading firebase/php-jwt (v6.3.0 => v6.3.1): Extracting archive
  - Upgrading google/apiclient-services (v0.272.0 => v0.272.1): Extracting archive
  - Upgrading aws/aws-sdk-php (3.240.5 => 3.240.9): Extracting archive
  - Upgrading symfony/translation-contracts (v2.5.2 => v3.1.1): Extracting archive
  - Upgrading symfony/config (v5.4.11 => v6.1.3): Extracting archive
  - Upgrading cakephp/database (4.4.6 => 4.4.7): Extracting archive
  - Upgrading symfony/intl (v5.4.15 => v6.1.7): Extracting archive
  - Upgrading overtrue/phplint (4.3.0 => 5.3.0): Extracting archive
  - Upgrading symfony/dependency-injection (v5.4.13 => v6.1.5): Extracting archive
  - Upgrading psalm/plugin-phpunit (0.17.0 => 0.18.3): Extracting archive
  - Upgrading phpstan/phpstan (1.8.11 => 1.9.0): Extracting archive
  - Upgrading symfony/http-foundation (v5.4.15 => v6.1.7): Extracting archive
  - Upgrading symfony/http-kernel (v5.4.15 => v6.1.7): Extracting archive
  - Upgrading symfony/routing (v5.4.15 => v6.1.7): Extracting archive
  - Upgrading filp/whoops (2.14.5 => 2.14.6): Extracting archive
  - Installing simplesamlphp/simplesamlphp (2.0.0-rc2): Extracting archive
```

**Comment by tvdijen** [comment]
Yeah, I think you have to import the entire composer-file of SimpleSAMLphp to get all the dependencies in place.

**Comment by drjayvee** [comment]
> Will this work for you drjayvee and dunkoh ?

@tvdijen Given dunkoh's struggle, it looks like the answer is "no". Even if it's possible to get working, hacking the composer config is not a robust way of managing a crucial dependency.

I would propose SSP maintainers publish a pre-built release on packagist. Is that a viable solution?

**Comment by tvdijen** [comment]
> I would propose SSP maintainers publish a pre-built release on packagist. Is that a viable solution?

No it's not because of the overhead for the maintainers, but we've come to a proposal that should make everybody happy.

- Assets will be moved to a separate repo where they are automatically built on any change and periodically to auto-update dependencies with known vulnerabilities.
- This repo will be included in the base SSP-repository's composer-file.
- Using composer-trickery the repo will be deployed in the `public/` directory, instead of the default `vendor/` directory.
- We leverage the `simplesamlphp/composer-module-installer` for this trickery. Any package name starting with `simplesamlphp-assets-...` will be deployed in `public/` so that any SSP-module can leverage this.

Some work has already been done to get the above working:
- `simplesamlphp/composer-module-installer` was update to treat packages differently when their name starts with `simplesamlphp-assets-...`
- A `simplesamlphp/simplesamlphp-assets` repository was made, holding our assets.. I'm currently working on getting everything to auto-build on any source-change, but I still have some open issues here.

**Comment by drjayvee** [comment]
> Assets will be moved to a separate repo where they are automatically built on any change and periodically to auto-update dependencies with known vulnerabilities.

That sounds like a great solution!

> Using composer-trickery the repo will be deployed in the public/ directory, instead of the default vendor/ directory.

All right, that should work. Our project doesn't (yet) use `/public` at all, but I'm sure we can create proper web server config to make it work.

Please do let me know once there's a new RC out so I can test this out.

**Comment by mlantz** [comment]
I spent hours digging through this, if you're using Chrome/Brave, make sure the `session.cookie.samesite` config is set to Lax or something, or if still using None then make sure they're secure. Making that change resolved the issue for me.

**Comment by thijskh** [comment]
Indeed for SAML flows to work well you need to send SameSite to None and mark cookies as secure. That is not SimpleSAML specific but a limitation of the (arguably broken) idea of SameSite in general and will be the same for other SAML SP implementations.

We've documented this e.g. here: https://simplesamlphp.org/docs/stable/simplesamlphp-nostate.html

**Comment by drjayvee** [comment]
@tvdijen I tried upgrading to RC-3, but got

```
In ModuleInstaller.php line 35:

  Unable to install module simplesamlphp/simplesamlphp-assets-base, package name must be on the form "VENDOR/simplesamlphp-module-MODULENAME".
```

> A simplesamlphp/simplesamlphp-assets repository was made, holding our assets.. I'm currently working on getting everything to auto-build on any source-change, but I still have some open issues here.

Is this the cause? Has that not yet been fixed?

If I do a completely fresh install, it works just fine:
```
$ composer require simplesamlphp/simplesamlphp:2.0.0-RC3
No composer.json in current directory, do you want to use the one at /app? [Y,n]? n
./composer.json has been created
Running composer update simplesamlphp/simplesamlphp
Loading composer repositories with package information
Updating dependencies
Lock file operations: 61 installs, 0 updates, 0 removals
[...]
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 61 installs, 0 updates, 0 removals
[...]
  - Installing simplesamlphp/assert (v0.8.0): Extracting archive
simplesamlphp/composer-module-installer contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "simplesamlphp/composer-module-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
  - Installing simplesamlphp/composer-module-installer (v1.3.3): Extracting archive
[...]
29 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
47 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found
```

**Comment by drjayvee** [comment]
If I create a new project and install `1.19.3`, then upgrade to `2.0.0-RC3`, I get the error!

To reproduce:
```bash
composer require simplesamlphp/simplesamlphp
sed -i "s/\^1.19/2.0.0-RC3/" composer.json
composer update
```

**Comment by tvdijen** [comment]
Known issue.. You have to do `composer require simplesamlphp/simplesamlphp:^1.3.3` before updating SimpleSAMLphp..

**Comment by drjayvee** [comment]
```
$ composer require simplesamlphp/composer-module-installer:^1.3.3 -W
./composer.json has been updated
Running composer update simplesamlphp/composer-module-installer --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires simplesamlphp/composer-module-installer ^1.3.3 -> satisfiable by simplesamlphp/composer-module-installer[v1.3.3].
    - simplesamlphp/composer-module-installer v1.3.3 requires simplesamlphp/assert ^0.8.0 -> found simplesamlphp/assert[v0.8.0] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - simplesamlphp/composer-module-installer v1.3.3 requires simplesamlphp/assert ^0.8.0 -> found simplesamlphp/assert[v0.8.0] but these were not loaded, likely because it conflicts with another require.
    - simplesamlphp/simplesamlphp v1.19.4 requires simplesamlphp/simplesamlphp-module-statistics ^0.9 -> satisfiable by simplesamlphp/simplesamlphp-module-statistics[v0.9.6].
    - simplesamlphp/simplesamlphp-module-statistics v0.9.6 requires simplesamlphp/composer-module-installer ~1.1 -> satisfiable by simplesamlphp/composer-module-installer[v1.3.3].
    - simplesamlphp/simplesamlphp is locked to version v1.19.4 and an update of this package was not requested.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by tvdijen** [comment]
Crap, that I can't solve.  Only option I see is to nuke your lock-file before updating simplesamlphp to 2.0

**Comment by drjayvee** [comment]
> I'll try removing the package entirely, then adding RC-3 fresh.

That works.

**Comment by tvdijen** [comment]
I'll make sure we add this to the upgrade notes

**Comment by drjayvee** [comment]
> I'll make sure we add this to the upgrade notes

"To upgrade SimpleSAMLphp, first uninstall SimpleSAMLphp, then install SimpleSAMLphp"
😆

**Comment by tvdijen** [comment]
It's clumsy, but there is no easy way to do this better.. Only way I can think of is to remove the `simplesamlphp/assert` dependency from the `composer-module-installer`.  Then we can say;  To upgrade SimpleSAMLphp, first update the composer-module-installer, then upgrade SimpleSAMLphp.

**Comment by billdacat** [comment]
> 

I've followed these steps and have the assets in place in the public folder, but how do I point simplesaml to them without altering any of the files in the vendor folder?   It's still looking in simplesaml/assets/css for stylesheet.css, but it's not going to find it.

My Apache config is set up so that /simplesaml is Alias'ed to vendor/simplesamlphp/simplesamlphp/www, so I'm only exposing that directory to the web.  The new public dir isn't web accessible.

Trying to find a way to get this all to load properly without manually altering the twig files, etc, to point to the right location (and I don't want to expose any more than the www directory for security purposes).  Any advice?

**Comment by drjayvee** [comment]
> My Apache config is set up so that /simplesaml is Alias'ed to vendor/simplesamlphp/simplesamlphp/www, so I'm only exposing that directory to the web. The new public dir isn't web accessible.

SimpleSAMLphp 2.0 moved the public folder to `public`, so you'll need to make that accessible in your web server config.

**Comment by billdacat** [comment]
> > My Apache config is set up so that /simplesaml is Alias'ed to vendor/simplesamlphp/simplesamlphp/www, so I'm only exposing that directory to the web. The new public dir isn't web accessible.
> 
> @billdacat SimpleSAMLphp 2.0 moved the public folder to `public`, so you'll need to make that accessible in your web server config.

Thanks.   I'm going to just start from scratch since that may be part of my issue here.

Is there documentation specifically for installing via composer somewhere?  I just want to make sure I don't miss a step, and don't see any 2.0 documentation yet on the website.

**Comment by drjayvee** [comment]
@billdacat have you tried `composer require simplesamlphp/simplesamlphp:2.0.0-RC3`?

Note that 2.0 final will be released _very_ soon. Presumably, the maintainers will also update/publish the documentation then.

If you're new(ish) to SSP, maybe wait until 2.0 has been released?

**Comment by billdacat** [comment]
Yeah, perhaps I'll just go back to a source install for this week to get my dev sites up and running again and keep an eye out.  Trying to go from the source install of 1.19 -> composer install of a 2.x branch has caused a lot of issues, and there's just not a lot of documentation at the moment on it.  Thanks!

**Comment by tvdijen** [comment]
What kind of issues are you experiencing with 2.0 @billdacat?

**Comment by billdacat** [comment]
> What kind of issues are you experiencing with 2.0 @billdacat?

Hoping I sum this all up right.  Tried to go from 1.19 source to 2.0 composer.  Removed 1.19, installed 2.0-rc3 via composer.  Using Laravel for the framework if it matters.

The best guide I could find to it was here.  https://www.hashbangcode.com/article/installing-simplesamlphp-using-composer

That clued me into that, ok, I need to make changes to Apache to Alias over to the vendor folder.  Haven't had to do that before with any other modules, but seemed to work well enough -- but the assets weren't loading, the stylesheet.css file it was trying to pick up simply didn't exist.  Came here, read through this, installed the assets package, but it put it in 'vendor/simplesamlphp/simplesamlphp/public' -- which is at the same directory level as 'vendor/simplesamlphp/simplesamlphp/www', so I couldn't access it via the browser, and I imagine it would have required some manual template editing even if it had to point there.

Never quite got the authentication down exactly either, but I'm sure that was a misconfiguration -- initially I hadn't set up the Apache alias, so the ADFS server had nothing to talk to when it responded.  Was working on fixing that up, and then my paths were changing slightly since in the 1.19 version, I had the entire simplesaml dir web accessible -- I wanted to change it so that only simplesaml/www was web accessible for security purposes.  I knew I was going to have to get new XML over to the AD guys to install, but then wanted to see if I could get all the assets loading properly before I went and told them "ok, this is where simplesaml lives now".

So for now I'm waiting until the official 2.0 release, but I'd be happy to test the composer instructions/steps if you need anyone.  Thank you!

(I've reverted to 1.19 source successfully for the time being.)

**Comment by tvdijen** [comment]
It all doesn't make much sense to me tbh..

> That clued me into that, ok, I need to make changes to Apache to Alias over to the vendor folder. Haven't had to do that before with any other modules, but seemed to work well enough

What modules are you talking about? Are you installing SimpleSAMLphp through some kind of Laravel-module?

**Comment by billdacat** [comment]
> It all doesn't make much sense to me tbh..
> 
> > That clued me into that, ok, I need to make changes to Apache to Alias over to the vendor folder. Haven't had to do that before with any other modules, but seemed to work well enough
> 
> What modules are you talking about? Are you installing SimpleSAMLphp through some kind of Laravel-module? Also, the `www/`-directory doesn't exist anymore in 2.0.. It was renamed to `public/`, so you will have to adjust your Apache-config as well.
> 
> > I knew I was going to have to get new XML over to the AD guys to install
> 
> Also makes no sense.. No need to exchange metadata if you set the same entityID

I was just installing via composer.  Nothing Laravel specific.  I'll go through the steps again tomorrow to see if I can get it to work -- not sure how I ended up with a www directory if I installed 2.0.  Right now, it's not letting me install 2.0 via composer since 1.19 is on the system and there's a conflict in symfony/console (looks for ^5.4, but 6.0.19 is on the system).

As far as I understand, the URLs are in the XML I send to the AD team -- the SingleLougoutService, AssertionConsumerService bindings, etc.  If simplesaml moves (and I had moved it), then they need the updated location.

**Comment by tvdijen** [comment]
OK, yes, now things are making sense.
You may have to read the upgrade notes, but to upgrade from 1.19 > 2.0 you have to remove the dependency on `simplesamlphp/simplesamlphp` from your project, and then add it again (I know it doesn't make any sense, but we can't work around this).

Yes, our endpoints have changed, _but_ the old ones still work for receiving responses. If you have changed anything on the base-url, then yes you have to exchange metadata again, but that is not related to the upgrade.

**Comment by billdacat** [comment]
> > My Apache config is set up so that /simplesaml is Alias'ed to vendor/simplesamlphp/simplesamlphp/www, so I'm only exposing that directory to the web. The new public dir isn't web accessible.
> 
> @billdacat SimpleSAMLphp 2.0 moved the public folder to `public`, so you'll need to make that accessible in your web server config.

Removed my old version, installed new version with composer.

So I'm on 2.0 now with composer and don't have a public dir, it's still 'www'.  The UI loads but the assets aren't loading in -- pointing an Apache alias to the install, but it doesn't seem to be finding the assets.  Debugging that but the public vs www discrepancy has me concerned.

**Comment by tvdijen** [comment]
It's hard to tell what's wrong, but it must be something on your end.. There is no www-directory in 2.0

**Comment by billdacat** [comment]
Thanks.  I must have some dependency causing it to fallback to v2.0.0-beta99 on install, which is installing the 'www' directory.  I installed it in a new area on the server to compare and that one brought down 2.0.2.

**Comment by billdacat** [comment]
v2.0.2 on Packagist (https://packagist.org/packages/simplesamlphp/simplesamlphp) is fixing symfony/cache to be ^5.4 instead of ^5.4||^6 like the current git composer.json is listing:  https://github.com/simplesamlphp/simplesamlphp/blob/master/composer.json

Is that something you can address so that this package can be installed with composer and using symfony/cache v6 please?

Thank you!

**Comment by tvdijen** [comment]
In a next major release. symfony/cache v6 requires a minimnum of PHP 8.0 and we currently support 7.4

**Comment by billdacat** [comment]
Right, but wouldn’t listing the package in the composer.json as v5.4||6 support both?

Entirely possible I’m missing something.

**Comment by dunkoh** [comment]
While we're discussing dependencies...

v2.0.2 has require of simplesamlphp/simplesamlphp-module-discopower ^1.2.3 but there is no 1.2.3 tag or release of that version.  There is a 1.2.2 tag and a 1.2.0 release

**Comment by tvdijen** [comment]
@dunkoh I'm not sure how that got there, but that's a mistake. We do not include any modules anymore.
