### ISSUE TITLE
2.0-rc1 Login page not found

### ISSUE THREAD

**Issue by drjayvee** [simplesamlphp/simplesamlphp#1682]
**Describe the bug**
After upgrading from 1.19.3, the URL returned by `SimpleSAML\Auth\Simple::getLoginURL()` displays a cryptic error message:

> The given page was not found. The reason was: The URL wasn't found in the module. The URL was: https://gerben.alisqi.com.test-xxx.platformsh.site/sso/module.php/core/login/gerben?AuthId=gerben&ReturnTo=https%3A%2F%2Fgerben.alisqi.com.test-xxx.platformsh.site%2F%3Fmod%3Dlogin%26ssoLogin

![image](https://user-images.githubusercontent.com/3079883/185953763-539ba141-3d34-46fa-a200-8994255daa14.png)

The `config.php` was changed as described in the changelog.

**Comment by tvdijen** [comment]
With just the screenshots it's impossible to help.. What's the backtrace in the logs?
Also, the changelog doesn't mention any changes to `config.php`.. Please specify.

**Comment by mlantz** [comment]
I left a comment in #1681

**Comment by tvdijen** [comment]
@drjayvee @dunkoh how are you guys using the login url? We have removed the possibility to access authentication sources directly, because it had severe security implications. `getLoginURL` should therefore have been removed and is just a leftover.

The correct way to start authentication would be to;

```php
$as = new SimpleSAML\Auth\Simple('default-sp');
$as->requireAuth([
    'ReturnTo' => 'Your return-url',
]);
```

**Comment by drjayvee** [comment]
> @drjayvee @dunkoh how are you guys using the login url? We have removed the possibility to access authentication sources directly, because it had severe security implications. `getLoginURL` should therefore have been removed and is just a leftover.

Oh, really!?

We've been using `getLoginURL` and `getLogoutURL` for five years and one week now. It's difficult for me to figure out why we didn't just use `requireAuth`, but looking at very first commit, it looks like we need(ed) to go step by step to avoid #549:

```php
// close our session and restore session handler
// see https://github.com/simplesamlphp/simplesamlphp/issues/549
$sessionName = session_name();
$sessionId = session_id();

$this->user->closeSession(true);

// let SimpleSAML do its thing, close its session
$ss = new SimpleSAML_Auth_Simple($this->conf->SAMLSource);
if (!$ss->isAuthenticated()) {
	header("Location: {$ss->getLoginURL()}");
	return;
}
$address = $ss->getAuthData('saml:sp:NameID')['Value'];

session_write_close();

// restart our own session
session_name($sessionName);
session_id($sessionId);
$this->user->startSession();

// find user by email
$userId = User::findByAddress($address);
```

These days, we do
```php
// make SimpleSAML redirect back with the ?ssoLogin flag
$response = new RedirectResponse(
    $this->conf->getSSOConfig() // returns \SimpleSAML\Auth\Simple
        ->getLoginURL("{$this->conf->getAlisURL()}/?mod=login&ssoLogin")
);

// store deeplink cookie
if (/* URL isn't deny-listed for deep link */) {
    $response->headers->setCookie(
        new Cookie(self::DEEP_LINK_COOKIE, $request->getQueryString())
    );
}

return $response->send();
```

`requireAuth` might do a little *too much* if you want control over the response (and be able to test it).

In fact, I see plenty of `assert(false)` in the code path, which makes it look like `requireAuth()` will terminate PHP. I haven't debugged, but it looks like out setup would eventually `exit` in `SimpleSAML\Utils\HTTP::redirect`.

That's a no-go for us!

**Comment by dunkoh** [comment]
We check if user has authsource in Session, and if not we use our default one
```
public function getExistingAuthoritySource() {
        try {
            $session = Session::getSessionFromRequest();
        } catch (Exception $e) {
            System::customErrorHandler(E_ERROR, $e->getMessage(), $e->getFile(), $e->getLine());
        }
        if (!empty($session) && $session instanceof Session) {
            $this->extendUserSAMLSession($session->getSessionId());
            $authorities = $session->getAuthorities();
        }

        if (!empty($authorities)) {
            return current($authorities);
        } else {
            return $this->authSource;
        }
    }
```

Which gets called in our Authentication class which does all the interacting with SimpleSAMLPhp as an intermediary 

When we requireAuth we do as such:

We instantiate
```
public function setAuthIDP($authSource = '') {
        if (!empty($authSource)) {
            $this->authSource = $authSource;
        }
        $this->auth = new SimpleSAML\Auth\Simple($this->authSource);
        return $this;
    }
```

and then require auth when needed
```
$authParams = array(
            'ReturnTo' => 'the-return-url'
        );

        $this->setAuthParams($authParams);

        $this->auth->requireAuth($this->params);
```

**Comment by tvdijen** [comment]
@dunkoh Your response seems disconnected from the question.. I asked about `getLoginURL` and all the code you've provided doesn't use that method.

@drjayvee We would have to look into your use-case... Like I said, accessing authsources directly has so many security implications that we can't go back there.

**Comment by dunkoh** [comment]
@tvdijen Ah oops - I was thinking about the accessing authsources directly aspect of your question. As far as I can tell we don't use getLoginURL.

**Comment by tvdijen** [comment]
I wouldn't be surprised if we reinvented the wheel with our `RunnableResponse`.
The many back-compat changes are due to the fact that we are postponing our 2.0 release for almost a decade.

**Comment by drjayvee** [comment]
> The many back-compat changes are due to the fact that we are postponing our 2.0 release for almost a decade.

Oh wow! 😄

I can sympathize. You'd probably prefer to release changes bit by bit. But for a library (specifically, its users), it's better to have very few big BC-breaking releases instead of one every year.

It does mean that 2.x really is quite different from 1.x, so some users might look elsewhere.

Again, no hard feelings at all from my side.

**Comment by tvdijen** [comment]
I think I have a way to accommodate your use-case, so you can keep using getLoginURL()... That would be one bc-break less for you ;)

**Comment by drjayvee** [comment]
> I think you should be able to solve this by using our \SimpleSAML\HTTP\RunnableResponse like this;
> ```php
> $response = new RunnableResponse(
>     $this->conf->getSSOConfig() // handles the session juggling and returns \SimpleSAML\Auth\Simple
>       ->requireAuth()
>  );
>

On second thought, this doesn't really work because of the `exit` statement in `SimpleSAML\Utils\HTTP::redirect`!

`$response` can't ever be used because the program terminates.

> I think I have a way to accommodate your use-case, so you can keep using getLoginURL()... That would be one bc-break less for you ;)

That would be much appreciated!

**Comment by tvdijen** [comment]
You're wrong, because the code isn't run before you call `$response->send()`.

> Then again, the methods are still available in RC-3! Are you planning on deprecating this for the final 3.0, or for later?

It was simply forgotten to remove it. There a PR #1754 that should reinstate and fix it.

**Comment by drjayvee** [comment]
> You're wrong, because the code isn't run before you call $response->send().

Of course, you're right. Thanks for pointing that out!

> It was simply forgotten to remove it. There a PR https://github.com/simplesamlphp/simplesamlphp/pull/1754 that should reinstate and fix it.

Right, so there should be no change between 2.0-RC3 and 2.0, correct?

**Comment by tvdijen** [comment]
It agree it sucks.. Goal for 2.0 was to migrate everything to controllers and twig-templates, so we could drop old-skool www-scripts that mixed code & markup. Next step will be to make everything PSR-3 and PSR-7 compliant, so we can properly unit-test everything.

> Right, so there should be no change between 2.0-RC3 and 2.0, correct?
Correct, functionally no change. The url returned by `getLoginURL()` will be slightly different, but that shouldn't hurt you.

**Comment by drjayvee** [comment]
So I changed the code to use `requireAuth()` instead of `getLoginURL()`, but I'm still getting the same error because the redirect is sending me to the same location!

```
https://[domain]/sso/module.php/core/login/gerben?AuthId=gerben&ReturnTo=%2F%3FssoLogin
```

which shows a 404 page with
```
SimpleSAML\Error\NotFound: The requested page 'https://gerben.alisqi.com.test-t6dnbai-fci6opgp2znx4.de-2.platformsh.site/sso/module.php/core/login/gerben?AuthId=gerben&ReturnTo=%2F%3FssoLogin' could not be found. The URL wasn't found in the module.
```

Did we get sidetracked by `getLoginURL()` vs `requireAuth()` and forgot to address the issue in the opening post? Or is the latter supposed to use a different URL?

**Comment by tvdijen** [comment]
The opening post was a mesh of multiple issues to begin with.. You were missing the assets to start with. The problem here is that the `/core/login` endpoint no longer exists.
I'm really not sure how you still end up there while using `requireAuth()`..

**Comment by drjayvee** [comment]
> The problem at hand is that the /core/login endpoint no longer exists.

Searching through the code base, I do see a few more uses which should be removed then:
* [docs/simplesamlphp-sp-api.md](https://github.com/simplesamlphp/simplesamlphp/blob/v2.0.0-rc3/docs/simplesamlphp-sp-api.md#getloginurl)
  > Note: The URL returned by this function is static, and will not change. You can easily create your own links without using this function. The URL should be:
  > ```
  > .../simplesaml/module.php/core/login/<authentication source>?ReturnTo=<return URL>
  > ```
* [`Simple::getLoginURL`](https://github.com/simplesamlphp/simplesamlphp/blob/v2.0.0-rc3/src/SimpleSAML/Auth/Simple.php#L316)
* [`Exception.php`](https://github.com/simplesamlphp/simplesamlphp/blob/v2.0.0-rc3/modules/core/src/Controller/Exception.php#L78)

> I'm really not sure how you still end up there while using requireAuth().

Sorry, my bad. I was still using `getLoginURL()` in a template. `requireAuth()` actually does work.

I *really* want to keep using the `getLoginURL()`, at least for a while. How about I create a PR which
* removes the old route from the docs, 
* mark `getLoginURL()` and `getLogoutURL()` as `@deprecated`
* but makes them return the actual URLs

Or are you already working on this?

By the way, I am running into yet another issue and will either post findings here or create a new ticket.

**Comment by tvdijen** [comment]
@drjayvee You have found 1 more case I wasn't aware of, but everything else is covered in #1754 
Please open a new ticket for your other issue

**Comment by drjayvee** [comment]
@tvdijen looks like that other issue is on our end. I'll do plenty more testing to make sure everything works and we can safely migrate production later. I'll create new issues if I do run into, well, issues.

That means we seem to be good to go! FYI: I've switched to `requireAuth()` and `logout()` and don't need the URL getters. I'd still like for them to return sometime, since we both agree that `exit` "sucks".

Can you provide me with an ETA for 2.0 final?

**Comment by tvdijen** [comment]
ETA for 2.0 final is Februari 22nd, after we thoroughly tested everything during our hackathon.

**Comment by drjayvee** [comment]
Interesting! I was going to offer to buy you a beverage anyway. See you there! :)
