### ISSUE TITLE
2.0-rc1 home page missing functionality

### ISSUE THREAD

**Issue by drjayvee** [simplesamlphp/simplesamlphp#1683]
**Describe the bug**
The homepage for 1.19.3 has four tabs: Welcome, Configuration, Authentication, Federation.

After upgrading to 2.0-rc1, these are gone. The changelog doesn't mention any such change.

Is it possible to get these (or select) tabs back by making changes to the configuration? How can users find their SP's metadata or test IdPs?

**Comment by thijskh** [comment]
The admin interface is now at <ssp base url>/admin. This is in the docs but indeed should be added to the release notes.

Thanks for testing the RC, really useful!

**Comment by drjayvee** [comment]
I see. This severely limits our use case.

We develop a SaaS app and use SimpleSAMLphp for SSO (our app is the SP). We have a *single installation* (as a composer dependency) for multiple tenants.

With 1.x, we can [tell our customers](https://help.alisqi.com/article/407-set-up-single-sign-on-with-microsoft-azure-active-directory) to go to `$tenant.app.com/sso` to download their tenant's metadata. No login is required.

Customers can also test the integration in SimpleSAMLphp before we turn on SSO in the app.

> `admin.protectindexpage`. Replaced by the admin module which always requires login. 

This change means we can't let customers set up SSO by themselves, since we can't simply share the admin password publicly.

Also, doesn't that mean that `admin.protectmetadata` is legacy as well? If the metadata is only accessible through the `/admin` page (which requires admin login), then the metadata is always protected, no?

**Comment by drjayvee** [comment]
> The metadata in your case would be available at [...]

Thanks. We can link to this URL from within our app for now.

Even better would be to have the metadata accessible *inside* our app (as opposed to a separate app on the same domain). Can you point me towards the class that creates the XML?

> Testing the individual authsources was a security risk that we had to mitigate.

Interesting. A colleague just offered security as a possible reason for the change during our stand-up minutes ago. :)

We already have an SSO wizard (entirely in our app) in our product roadmap. Maybe it's time to implement that.

**Comment by tvdijen** [comment]
Here's the controller that's being called;
https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/src/Controller/ServiceProvider.php#L564-L615

Most of the magic is happening in this class;
https://github.com/simplesamlphp/simplesamlphp/blob/master/src/SimpleSAML/Metadata/SAMLBuilder.php

**Comment by drjayvee** [comment]
Thanks a bunch. Looks like we could call `SimpleSAML\Module\saml\Controller\ServiceProvider::metadata` and forward the response.

The SSO wizard is intended as an in-app UI to replace SimpleSAMLphp's metadata viewer and "test auth source" functionality.

We'd still want to rely on `SimpleSAML\Auth\Simple` for convenience and security instead of rolling our own.

**Comment by drjayvee** [comment]
@tvdijen I came across this once again just now, and we haven't hashed out:

> Also, doesn't that mean that `admin.protectmetadata` is legacy as well?

`config/config.php.dist` describes this option as
> Set this option to true if you want to require administrator password to access the metadata.

But it really does look like this option doesn't do anything.

It's `false` in our config, yet when I open the dedicated metadata URL (shown in the admin's Federation page) in a private window, I am greeted with a login screen.

**Comment by tvdijen** [comment]
Opened a separate issue and asked @drjayvee for additional info
