### ISSUE TITLE
2.0: SP reply URL not backwards compatible

### ISSUE THREAD

**Issue by drjayvee** [simplesamlphp/simplesamlphp#1684]
After upgrading from 1.19.3 to 2.0-rc1, I cannot log in to a Microsoft Azure AD IdP configured using the SP metadata obtained from 1.19.

Azure AD presents the following error message:

> AADSTS50011: The reply URL 'https://gerben.alisqi.com.test-xxx.platformsh.site/sso/module.php/saml/sp/assertionConsumerService/gerben' specified in the request does not match the reply URLs configured for the application 'https://gerben.alisqi.com.test-xxx.platformsh.site/sso/module.php/saml/sp/metadata.php/gerben'. Make sure the reply URL sent in the request matches one added to your application in the Azure portal. Navigate to https://aka.ms/urlMismatchError to learn more about how to fix this. 

The last bit of the URLs is different:
```
old: .../saml/sp/metadata.php/gerben
new: .../saml/sp/assertionConsumerService/gerben
```

Note: in 1.19.x,, we had `entityID => null` in `authsources.php`, which I set it to auto-generated value.

**Comment by thijskh** [comment]
The new URL should be in the newly generated metadata. So in theory the relying party would have refreshed that metadata?

**Comment by drjayvee** [comment]
> The new URL

Did the return URL did change between 1.x and 2.x? If so, doesn't that warrant a warning in the upgrade notes?

> So in theory the relying party would have refreshed that metadata?

That depends on how often the metadata is updated. I don't think we have any control over that unless we ask our customers' sys admins to manually refresh at some particular point in time.

Without any such action, users won't be able to log in when the upgrade to 2.0 is deployed until the IdP has refreshed.

Is it possible to configure the return URL? We could then either make 2.x backwards compatible or change our current 1.x setup to make it forward-compatible.

**Comment by tvdijen** [comment]
You can configure your ACS-endpoints in the `authsources.php` file as per [documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-metadata-endpoints.html)

**Comment by drjayvee** [comment]
> The old endpoints still work.

It looks like the old ACS endpoints are equal to the previously auto-generated metadata URL (if `entityID => null`), correct? Will those keep working as ACS endpoints?

I tried `'AssertionConsumerService' => $entityID`, which fails because
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
3 www/_include.php:28 (SimpleSAML_exception_handler)
2 /app/vendor/sentry/sentry/src/ErrorHandler.php:357 (Sentry\ErrorHandler::handleException)
1 /app/vendor/symfony/error-handler/ErrorHandler.php:541 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: SimpleSAML\Assert\AssertionFailedException: authsources['gerben']: The option 'AssertionConsumerService' is not an array.
```

Even though the documentation you refer to specifically says
>  **A single string**
>  `'AssertionConsumerService' => 'https://sp.example.org/ACS',`
> This is the simplest endpoint format. It can be used when there is only a single endpoint that uses the default binding. 

Configuring `'AssertionConsumerService' => [$entityID, $entityID]` changes the metadata to

```xml
<md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
	<!-- md:KeyDescriptor use="signing" -->
	<!-- md:KeyDescriptor use="encryption" -->
	<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://gerben.alisqi.com.test-xxx.platformsh.site/sso/module.php/saml/sp/singleLogoutService/gerben"/>
	<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://gerben.alisqi.com.test-xxx.platformsh.site/sso/module.php/saml/sp/metadata.php/gerben" index="0"/>
	<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://gerben.alisqi.com.test-xxx.platformsh.site/sso/module.php/saml/sp/metadata.php/gerben" index="1"/>
</md:SPSSODescriptor>
```

*However*, if test the authentication source, I'm still getting the same error as before. Apparently, the request to the IdP still uses the reply URL with `.../saml/sp/assertionConsumerService/...`.

**Comment by thijskh** [comment]
For starters, the old URL is `/module.php/saml/sp/saml2-acs.php/gerben`, not `.../metadata.php/gerben`. 

However, maybe the simplest fix is that we do not change the ACS url at all.

Since it's just an internal thing used for consumption by machines there's really no functional difference between "/module.php/saml/sp/saml2-acs.php/default-sp" and "/module.php/saml/sp/assertionConsumerService/default-sp". Humans don't need to type it or know it.

I agree that it's cumbersome that updating an SP to 2.0 would require upgrading ALL connected IdP's at the same time. Even if they would refresh metadata there would be some time of breakage, that we can avoid by just not changing the URL.

**Comment by tvdijen** [comment]
@drjayvee Do you sign your AuthnRequests towards Azure?

**Comment by drjayvee** [comment]
> It's not a big deal to update the endpoints there

Whether it is a big deal depends on the scale. We would push the upgrade to 2.0 out to all our our tenants at once (that's how our CD and release process works). Over a dozen different companies would need to refresh the metadata at exactly that time.

Therefore, I agree with thijskh here. It *is* quite cumbersome.

> maybe it's even possible to trick Azure by not sending the ACS-URL in the request but just the index.

Is that something I could try? Or do you have an Azure AD available for testing?

> Do you sign your AuthnRequests towards Azure?

I'm not sure. Our `authsources.php` does configure `privatekey` and `certificate` for all tenant SPs.

When trying to log in, SimpleSAMLphp redirects to the IdP with a `SAMLRequest=` parameter that looks base64 encoded. `base64_decode`ing that leads to gibberish, so probably binary?

**Comment by tvdijen** [comment]
> Is that something I could try? Or do you have an Azure AD available for testing?
No, I try to stay away for AAD as much as I possibly can, because it's always a guarantee for trouble.. None of my customers us it.

> I'm not sure. Our authsources.php does configure privatekey and certificate for all tenant SPs.
If you also set `redirect.sign` in your SP outsource then you are signing the requests...

> When trying to log in, SimpleSAMLphp redirects to the IdP with a SAMLRequest= parameter that looks base64 encoded. base64_decodeing that leads to gibberish, so probably binary?
It's gzip deflated, then base64 encoded, so to be able to read it you'd have to revert that process. There are browser plugins like SAML-tracer that can to that for you and let you peek into the SAML messages.

**Comment by drjayvee** [comment]
>  I try to stay away for AAD as much as I possibly can, because it's always a guarantee for trouble.. None of my customers us it.

*Every single one* of ours do. 🥲

Again, our customers' choice and management of IdP is not under our control.

> If you also set redirect.sign in your SP [auth]source then you are signing the requests.

We do not!

> you'd have to revert that process

I did using `gzdeflate(base64_decode($SAMLRequestParam))`. It's still gibberish. I even tried `urldecode()`ing first, with the same result.

Anyway, it's up to you to decide whether backward-breaking the reply URLs is worth it. I'm just telling you as a user that this has significant consequences which we (apparently) can't work around.

**Comment by tvdijen** [comment]
I've been trying to reproduce this, so I set up AAD as an IDP, changed the ACS-url in Azure to simulate the 'ACS url doesn't match the request' case.. Even with an unsigned AuthnRequest, AAD will just fulfill my request..

**Comment by drjayvee** [comment]
Ugh, that sucks.

Would you be willing to test again the way users will actually do this? Specifically:
1. set up SimpleSAMLphp 1.x
2. add AAD app
3. upgrade to 2.0 and test whether authentication is still working

I tried checking the `SAMLRequest` to definitively see whether or not we sign these, but now the IdP metadata has expired. The cron job to refresh it doesn't have any affect (no logs other than "Cron - Summary: Cron did run tag [daily]"), and there's no more "Metarefresh: fetch metadata" link in the "Federation" tab anymore.

I'll report that as a separate issue, but I feel kind of stuck helping out in this issue.

**Comment by tvdijen** [comment]
You have the metarefresh-module installed and enabled? It doesn't come with SimpleSAMLphp out of the box anymore..
I will re-run the AAD scenario again like you described.. You let your customers import the metadata xml, or manually configure the ACS-url?

**Comment by drjayvee** [comment]
> OK, now I was able to reproduce and I can't trick myself around it..

🥳 😉 

> You can't expect metadata to remain the same for years on end.. Even the AAD certificates have a limited lifetime.

Agreed. However, the upgrade from 1.x to 2.x will "abruptly" change the metadata in a breaking way *unless* the way is paved beforehand. Once again I'd like to point out this should be mentioned in the upgrade notes.

> What you can do is manually add the new endpoint to the metadata of your 1.19 install.

This would add the 2.x URLs to the 1.19 setup in addition to the 1.19 ones? How does that work, exactly?

> Exchange it with your peers

Won't that be done automatically by the Azure AAD IdPs? Don't they regularly fetch the SP metadata? (I don't actually see any requests in our web server logs, so I'm afraid the answer is "no".)

**Comment by tvdijen** [comment]
> > What you can do is manually add the new endpoint to the metadata of your 1.19 install.
> 
> This would add the 2.x URLs to the 1.19 setup in addition to the 1.19 ones? How does that work, exactly?

Using the `AssertionConsumerService` setting mentioned earlier in the thread.

> > Exchange it with your peers
> 
> Won't that be done automatically by the Azure AAD IdPs? Don't they regularly fetch the SP metadata? (I don't actually see any requests in our web server logs, so I'm afraid the answer is "no".)

No they don't and I'm glad they don't. Exchanging metadata is the foundation of your trust-relation. It should be a well considered action to import metadata and not some automated process.

PS: I will add a mention in the upgrade notes

**Comment by tvdijen** [comment]
One of the other devs mentioned the option to add a setting in 1.19 that would add the 2.0-endpoints to the metadata.. That way people can already start preparing for a future migration.. I think it's a good idea.

**Comment by drjayvee** [comment]
> It should be a well considered action to import metadata and not some automated process.

I was assuming that since our SP regularly refreshes the IdP's metadata, the reverse is also true. How else can rolling certificates work? This shows my ignorance and the reason to rely on a library.

So once #1692 has been released and deployed, all IdPs will need to re-import the SP metadata to have a pain-free migration to 2.0, correct?

If so, then I think we can close this issue.

**Comment by tvdijen** [comment]
Certificate rollover works by publishing old/new certificates in your metadata simultaneously for a short period of time (rollover period) in which your peers must process the new metadata before you start actively using the new certificate.. The rollover period is something you have to negotiate with your peers, because you don't control the frequency in which refresh your metadata and you have no way of knowing whether they consumed the new metadata.

![image](https://user-images.githubusercontent.com/841045/187924189-0a28485a-bd6e-4d9e-b790-c302373ff136.png)

Whether metadata is being processed automatically or not is a different story.

**Comment by thijskh** [comment]
Just noting that Azure follows the SAML spec here in requiring that an ACS URL in the AuthnRequest is an ACS URL from the service provider in question (see oasis saml profiles 2.0 533-536).

**Comment by tvdijen** [comment]
Endpoint-changes have been reverted for now.

**Comment by drjayvee** [comment]
Thanks so much for reverting the change! I very much appreciate the effort. 👍

**Comment by drjayvee** [comment]
@tvdijen 
> Endpoint-changes have been reverted for now.

The [upgrade notes](https://github.com/simplesamlphp/simplesamlphp/blob/v2.0.0-rc3/docs/simplesamlphp-upgrade-notes-2.0.md) state:
> SAML endpoints have changed, meaning that a metadata exchange with your peers could be necessary depending 
on your configuration.
