### ISSUE TITLE
Broken links / anticipated 2.0 release date

### ISSUE THREAD

**Issue by 4thecause** [simplesamlphp/simplesamlphp#1686]
Is there an anticipated release date for 2.0? I did check the changelog (https://simplesamlphp.org/docs/simplesamlphp-2.0/simplesamlphp-changelog) and [upgrade notes (https://simplesamlphp.org/docs/simplesamlphp-2.0/simplesamlphp-upgrade-notes-2.0) but these links are broken.

**Comment by tvdijen** [comment]
We're working on a second release candidate, to be released soon.. There is no date set for the final release. It's done when it's done?
