### ISSUE TITLE
PHP Fatal Error logging in via OpenIDProvider

### ISSUE THREAD

**Issue by unikent-ms1** [simplesamlphp/simplesamlphp#169]
*I have also logged this in the simplesamlphp-module-openidprovider repo but I don't know if this is a better place. Please advise!*

Latest SimpleSAMLphp distribution (1.13.2) set up to enable OpenID provider module (and with relevant include fixes detailed in https://groups.google.com/forum/#!topic/simplesamlphp/mV6eOxEFBt8) and attempting to hit http://openid-consumer.appspot.com as a simple test fails with:

PHP Fatal error: Call to undefined method Auth_OpenID_AX_Error::iterTypes() in .../modules/openidProvider/lib/Server.php on line 456

Doing a print_r on the $ax_req object after it's been generated reports:

Auth_OpenID_AX_Error Object ( [message] => Expected mode 'fetch_request'; got '' )

This error is not being caught properly and then the code tries to hit a
function on the expected object (iterTypes()) which barfs because it's
the wrong object (at line 456).

Commenting out that forloop results in a "working" (albeit empty)
response to the consumer rather than PHP death.

**Comment by jaimeperez** [comment]
Hi @unikent-ms1,

This is an issue with the OpenID module, and therefore it belongs in the module's issue tracker.

**Comment by unikent-ms1** [comment]
Understood. Thanks.
