### ISSUE TITLE
Is it possible to use SimpleSamlPhp on windows

### ISSUE THREAD

**Issue by Fourquth** [simplesamlphp/simplesamlphp#1690]
Sure it's possible in fact. But as I didn't found any setup on the official site. Only Apache and Nginx. So the question is "is it advisable to use SimpleSamlphp on Windows ?"

**Comment by thijskh** [comment]
If you can run PHP you can run SimpleSAML (as [documented here](https://simplesamlphp.org/docs/stable/simplesamlphp-install.html#prerequisites) you need "A web server capable of executing PHP scripts.") So you should be fine if you have set that up. If you think more Windows-specific documentation is needed we'd gladly hear how we can extend our documentation.
