### ISSUE TITLE
Google Workspace logout UnsupportedBindingException

### ISSUE THREAD

**Issue by kikz0rsk** [simplesamlphp/simplesamlphp#1694]
**Describe the bug**
Logout in Google Workspace fails when SimpleSAMLphp is used as identity provider. The following stack trace appears:
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 www/_include.php:28 (SimpleSAML_exception_handler)
1 vendor/symfony/error-handler/ErrorHandler.php:541 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: SAML2\Exception\Protocol\UnsupportedBindingException: Unable to find the SAML 2 binding used for this request.
Backtrace:
5 vendor/simplesamlphp/saml2/src/SAML2/Binding.php:109 (SAML2\Binding::getCurrentBinding)
4 modules/saml/src/IdP/SAML2.php:621 (SimpleSAML\Module\saml\IdP\SAML2::receiveLogoutMessage)
3 [builtin] (call_user_func_array)
2 src/SimpleSAML/HTTP/RunnableResponse.php:72 (SimpleSAML\HTTP\RunnableResponse::sendContent)
1 vendor/symfony/http-foundation/Response.php:373 (Symfony\Component\HttpFoundation\Response::send)
0 www/module.php:14 (N/A)
```

**To Reproduce**
1. Log in to Google Workspace through SimpleSAMLphp IdP
2. Sucessfully logs on to a google account
4. Click logout in top right menu
5. See error

**Expected behavior**
We should see a logout screen indicating user successfully logged out.

**Screenshots or logs**
These lines are from syslog
```
Sep 03 23:42:21 sso2 simplesamlphp[53102]: 4 [a2e1efb00a] Unable to find the SAML 2 binding used for this request.
Sep 03 23:42:21 sso2 simplesamlphp[53102]: 4 [a2e1efb00a] Request method: 'GET'
Sep 03 23:42:21 sso2 simplesamlphp[53102]: 4 [a2e1efb00a] Content-Type: ''
Sep 03 23:42:21 sso2 simplesamlphp[53102]: 3 [a2e1efb00a] SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Sep 03 23:42:21 sso2 simplesamlphp[53102]: 3 [a2e1efb00a] Error report with id dafd8113 generated.
```
Request to SSphp logout from Google
![image](https://user-images.githubusercontent.com/20465221/188304174-a41835c7-3c6a-4022-9961-3c5a5572ee5f.png)

**Additional context**
SimpleSAMLphp version: master (built from repository, but this issue is the same on 2.0-rc1)
SAML2 package version: 4.6.3
SimpleSAMLphp mode: IdP only, SAML2 only
OS: Ubuntu 22.04

It looks like Google sends GET request to single logout service, but apparently without any parameters SimpleSAMLphp is trying to find. When we use our current ADFS 2.0 SSO solution, this logout works just fine (with the same GET request without any parameters from Google). Maybe Google kills the session on their side and then there's nothing SimpleSAMLphp needs to do?

**Comment by tvdijen** [comment]
Hi @kikz0rsk !
Would you be able to manually apply this patch and tell me if it changes anything?
https://github.com/simplesamlphp/simplesamlphp/commit/89f84a471072ba4222e2f2209ac40d710f4c5443

**Comment by kikz0rsk** [comment]
Hi, thanks for your quick reply. Sure, I'll test and let you know, probably in a few hours.

**Comment by kikz0rsk** [comment]
Unfortunately, this patch didn't solve the issue. Still getting the same error and stacktrace.

**Comment by thijskh** [comment]
I've tried to reproduce it and it seems Google does not send any SAML SLO request, just redirects to the given URL. So you should not configure an SLO endpoint there.

**Comment by tvdijen** [comment]
@thijskh We should probably try and catch this and display a dummy logout-page alike the one OpenConext shows.

**Comment by kikz0rsk** [comment]
> I've tried to reproduce it and it seems Google does not send any SAML SLO request, just redirects to the given URL. So you should not configure an SLO endpoint there.

I've tried setting /logout.php as a SLO URL, which, to my understanding, does nothing but displays a logout page. But, I think the problem with that was, accessing Single Login URL after logout logged me in immediately. I will test this again to be sure.

**Comment by thijskh** [comment]
@tvdijen I think if someone configures an SLO url we should be explicit if they do not send a protocol message. Otherwise you sweep misconfigurations under the carpet.

**Comment by thijskh** [comment]
I'll remove the instruction from our docs that you configure the SLO url there since Google quite explicitly says "URL to redirect users to when they sign out" (!= SLO)

**Comment by tvdijen** [comment]
@thijskh OK, agreed

**Comment by kikz0rsk** [comment]
Okay, I've managed to test it again and now I'm sure how it behaves. Google logs me out and redirects me to a static page. So after this, when I go to, for example, gmail.com, it shows me I'm properly logged out. But when I go to SimpleSAMLphp's single sign on page (because I want to log in again, perhaps with different account), it will log me in automatically, SSphp remembers me and it shouldn't.

**Comment by tvdijen** [comment]
Yes it should.. You log out at Google, not at SSP..
If that's the behaviour you're after, ask Google to implement SLO..

**Comment by kikz0rsk** [comment]
I don't know why Google decided for this non-standard logout implementation. I manually implemented a quick and dirty workaround to delete session data on logout page. Thanks for your cooperation guys :) I think we can close this now.

**Comment by tvdijen** [comment]
They are not the only ones..
It's because the whole concept of SLO is broken by design / gives users a false sense of security.
