### ISSUE TITLE
Differences between dev-master and the simplesamlphp-2.0 branch

### ISSUE THREAD

**Issue by Berdir** [simplesamlphp/simplesamlphp#1696]
This is maybe more of a question about your workflows than a bug.

We noticed that there's a very large amount of differences between dev-master and the simplesamlphp-2.0 branch: https://github.com/simplesamlphp/simplesamlphp/compare/simplesamlphp-2.0

Mostly, it seems to be documentation, coding standards and typos, but there are also some functional changes hidden between those it seems.

Would it make sense to merge that back into dev-master, that should also make futher updates and cherry-picks between those branches easier

**Comment by tvdijen** [comment]
The compare is misleading, because some changes _do_ exist in both branches.. I did cherry-pick a few changes back to master that were forgotten at some point

**Comment by tvdijen** [comment]
I went over this again and merged 2.0 into master.. The compare is real bullshit though
