### ISSUE TITLE
SimpleSamlphp & java

### ISSUE THREAD

**Issue by Fourquth** [simplesamlphp/simplesamlphp#1697]
**Is your feature request related to a problem? Please describe.**
We own java applications needing authentication. As we already use simplesamlphp, is there an additionnal simplesamplphp module that transforms received claims from an IDP into variables usable in a java application ? 

**Describe the solution you'd like**
When claims are received from IDP, simplesampl transforms them into java variables. 

**Describe alternatives you've considered**
If not, is there any experience existing about this kind of tranformation ?

**Comment by tvdijen** [comment]
You could try; https://github.com/simplesamlphp/simplesamlphp-module-memcookie
I'm not aware of anyone using it, so I can't guarantee it's still a working module.

You'll have more chance in getting useful answers on our [mailing list](https://simplesamlphp.org/lists).. This is an issue tracker only.
