### ISSUE TITLE
Sending error report fails if email address is not filled in

### ISSUE THREAD

**Issue by MicWit** [simplesamlphp/simplesamlphp#1704]
When you get an error (in this case as we were doing the implementation, were getting an Unhandled exception), you get the error page and an option to send error report. If you click send error report without putting in an email address in the field that states "Optionally enter your email address, for the administrators to be able contact you for further questions about your issue:" you come up with a reply to error as follows:

> SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
> 
> Backtrace:
> 1 www/_include.php:17 (SimpleSAML_exception_handler)
> 0 [builtin] (N/A)
> Caused by: PHPMailer\PHPMailer\Exception: Invalid address:  (Reply-To): 
> Backtrace:
> 3 vendor/phpmailer/phpmailer/src/PHPMailer.php:1094 (PHPMailer\PHPMailer\PHPMailer::addOrEnqueueAnAddress)
> 2 vendor/phpmailer/phpmailer/src/PHPMailer.php:1059 (PHPMailer\PHPMailer\PHPMailer::addReplyTo)
> 1 lib/SimpleSAML/Utils/EMail.php:123 (SimpleSAML\Utils\EMail::addReplyTo)
> 0 www/errorreport.php:54 (N/A)

From what I can tell, the PHP mailer is not liking not having a reply-to address. Because the error reporting page states that this field is optional, can we do a basic sanity check that an email address has been entered there and if not, just put the technical contact email (the one it goes to) in there? Another option would be to just not submit the form and force the user to put in an email address (if they choose to put in a fake one thats their choise).

I am using simpleSAMLphp 1.19.6 if that helps.

**Comment by tvdijen** [comment]
Thanks @MicWit ! We had already fixed this in our development-branch, but I just backported it; 48e063ed1
