### ISSUE TITLE
KvStore size is constantly growing

### ISSUE THREAD

**Issue by zoghlamikaiseruqam** [simplesamlphp/simplesamlphp#1718]
# **Perfomance issues**
Database table KvStore size is constantly growing. It seems that the _value attribute should be optimized (up to 70Mb / entry). This causes performance issues and  downtime for the SSO. Since, we've update simpleSAMLPhp from 1.18.5 to 1.19.6 (7 days) database table reached 227Go.
Do you have any idea why this table size is growing so fast?

**Comment by thijskh** [comment]
What is in a typical entry?

**Comment by tvdijen** [comment]
What table is this? Are you using SQL as session store? Or is it the logout-store?

**Comment by zoghlamikaiseruqam** [comment]
When setting SimpleSamlPhp session to SQL, sessions are stored into KvStore table. Lately, this size of this table grew substantially (227Go). Using SQL optimize command help (reduces 227Go to 30Mb) but still don't understand why _value attribute can grow up to 70Mb per row. Is there a way to optimize values in the _value attribute ?

**Comment by thijskh** [comment]
The size reduction after optimize is because of frequent deletes and can be solved by choosing a different mysql storage engine for the table.

As for the size of individual entries, can you share what is in a typical _value attribute?

**Comment by thijskh** [comment]
@zoghlamikaiseruqam Any specific info you can share here?
