### ISSUE TITLE
Support for Oauth2's SAML2-Bearer Assertions

### ISSUE THREAD

**Issue by aacotroneo** [simplesamlphp/simplesamlphp#172]
Hi,
From what I see, SAML2 assertions are always intended to be decoded by the SP which makes the request (Audience, Recipient). 
Is there any way we can make assertions for a 3rd (trusted) party (Oauth2 server in my case)? 

I want to redirect the user to the IDP, authenticate and bring me back a saml2-token, which I'll then forward to the Oauth2-server. The server will validate the token, and expects to be part of the audience, recipient, etc.

I can code, test, but I need some direction!

Thank you!

**Comment by girgen** [comment]
27 jan 2015 kl. 22:01 skrev Alejandro Cotroneo <notifications@github.com>:
> 
> Hi,
> From what I see, SAML2 assertions are always intended to be decoded by the SP which makes the request (Audience, Recipient).
> Is there any way we can make assertions for a 3rd (trusted) party (Oauth2 server in my case)?
> 
> I want to redirect the user to the IDP, authenticate and bring me back a saml2-token, which I'll then forward to the Oauth2-server. The server will validate the token, and expects to be part of the audience, recipient, etc.

Sounds to me the OAuth server should be the SP. Your "SP" is more like an OAuth client, no?

Palle

**Comment by aacotroneo** [comment]
> Your "SP" is more like an OAuth client, 
Yes you are right

> Sounds to me the OAuth server should be the SP
Not quite. The problem with that the OAuth server wouldn't be able to authenticate the client which is going to use the token. And it needs to know because different clients have different scopes. Also, in the saml2-bearer token flow oauth tokens are handled between servers (back channel), which is better when clients are in trust

**Comment by tvdijen** [comment]
I don't see this ever implemented other than in a module..  The oauth-module is removed/deprecated, so perhaps this could go into the oidc-module, if still desired
