### ISSUE TITLE
2.0 UI back-button glitch

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1720]
**Describe the bug**
When pressing the back-button after successfully login in, the login-form is shown with a disabeled submit-button.

On top of that, refreshing that page leads to a page-not-found error.

The back-button leads me to:
`https://idp.moo-archive.nl/module.php/core/loginuserpass?AuthState=_f39cfb541de5dd79f5973c2d2782e9270f7cc76504%3Ahttps%3A%2F%2Fidp.moo-archive.nl%2Fmodule.php%2Fcore%2Flogin%2FAD-LDAP%3FAuthId%3DAD-LDAP%26ReturnTo%3Dhttps%253A%252F%252Fidp.moo-archive.nl%252Fmodule.php%252Fadmin%252Ftest%252FAD-LDAP` which seems broken in the first place.. There is no query param after the AuthState one.

After refreshing I end up with a 404 without AuthState var.
https://idp.moo-archive.nl/module.php/core/login/AD-LDAP?AuthId=AD-LDAP&ReturnTo=https%3A%2F%2Fidp.moo-archive.nl%2Fmodule.php%2Fadmin%2Ftest%2FAD-LDAP

**To Reproduce**
1. Go to Admin module > Test authsources
2. Select one and log in
3. On the 'show attributes' page press the back-button
4. See error 1; the button is disabled
5. Refresh the page
6. See error 2; 404 error

**Expected behavior**
Using the back-button has always been problematic in authentication flows, so either we prevent the use of it, or we make it work.

**Screenshots or logs**

![error 1](https://user-images.githubusercontent.com/841045/202917357-9875cdf9-8d6f-4e11-bd1a-a8e2631003e5.png)

![error 2](https://user-images.githubusercontent.com/841045/202917402-ec57e96b-abdc-477b-989f-5ff04d81bb41.png)

**Additional context**
Running v2.0.0-rc2 / Centos Stream (latest) / PHP 7.4 (fpm)

**Comment by thijskh** [comment]
The button is disabled with JS after the first click to prevent impatient and/or boomer users to double click it. Double clicking it yields errors for the users (assertion already used, state issues etc). Maybe the JS can be made more robust to re-enable the button if the user should return at some point.

**Comment by MKodde** [comment]
Would adding a check if the authentication is still in flight be an elegant solution here? That way when state does not contain the reference to the AR-ID we can simply 302 the user to a suitable (error) page. Or even back to the SP?
