### ISSUE TITLE
Remove abandoned modules

### ISSUE THREAD

**Issue by fstark-fms** [simplesamlphp/simplesamlphp#1727]
When running composer update, these modules are abandoned:

`
Package simplesamlphp/simplesamlphp-module-authfacebook is abandoned, you should avoid using it. No replacement was suggested.`
`Package simplesamlphp/simplesamlphp-module-authwindowslive is abandoned, you should avoid using it. No replacement was suggested.`
`Package simplesamlphp/simplesamlphp-module-oauth is abandoned, you should avoid using it. No replacement was suggested.`
`Package simplesamlphp/simplesamlphp-module-riak is abandoned, you should avoid using it. No replacement was suggested.
`

I am not using any of these modules. When I try to remove it, composer does not remove it since simplesaml 1.19.7 requires it:
`Removal failed, simplesamlphp/simplesamlphp-module-authfacebook is still present, it may be required by another package.`
`simplesamlphp/simplesamlphp  v1.19.7  requires  simplesamlphp/simplesamlphp-module-authfacebook (^0.9) `

Can you please remove them from the required dependencies?

**Comment by tvdijen** [comment]
We have removed them in v2.0.0 (currently in RC-state).
Before, we used to include every module we had.. In v2.0.0 you only get the minimum set and you have to add functionality by requiring the modules you need.
