### ISSUE TITLE
Declaration of Symfony\Component\HttpFoundation\ResponseHeaderBag::all() must be compatible with Symfony\Component\HttpFoundation\HeaderBag::all(?string $key = null)

### ISSUE THREAD

**Issue by adityafullstackdeveloper** [simplesamlphp/simplesamlphp#1730]
Declaration of Symfony\Component\HttpFoundation\ResponseHeaderBag::all() must be compatible with Symfony\Component\HttpFoundation\HeaderBag::all(?string $key = null)

on laravel 9 showing this error after sso successfully login
require_once("/var/simplesamlphp/lib/_autoload.php");
$auth = new \SimpleSAML_Auth_Simple('default-sp');
$auth->requireAuth();
if($auth->isAuthenticated()){
    $attributes = $auth->getAttributes();
}

**Comment by tvdijen** [comment]
We don't use `ResponseHeaderBag` in our code.. I think you have to talk to Laravel devs
