### ISSUE TITLE
Installing SimpleSAMLphp from the repository - Is documentation outdated?

### ISSUE THREAD

**Issue by steinmb** [simplesamlphp/simplesamlphp#1732]
**Describe the bug**
Following https://simplesamlphp.org/docs/devel/simplesamlphp-install-repo.html and cloning out HEAD on the master branch. Config and metadata templates are missing/moved.

**To Reproduce**

```
git clone git@github.com:simplesamlphp/simplesamlphp.git simplesamlphp
cd simplesamlphp
```
Follow [install instructions](https://simplesamlphp.org/docs/devel/simplesamlphp-install-repo.html)

```
cp -r config-templates/* config/
zsh: no matches found: config-templates/*

cp -r metadata-templates/* metadata/
zsh: no matches found: metadata-templates/*
```

**Expected behavior**

Files should be there.

**Screenshots or logs**
NA

**Additional context**
NA

**Comment by tvdijen** [comment]
Thanks for reporting! Yes, the docs are outdated here. We removed the `xx-templates` dirs and put the configuration templates as `.dist` files in the `config` and `metadata` dirs.

**Comment by steinmb** [comment]
Wow, hank you for your swift reply! Perhaps the cron module also should follow this pattern? Warning, new to this project and are just poking around in the code and doc to get to know it. Created - https://github.com/simplesamlphp/simplesamlphp/pull/1733
