### ISSUE TITLE
IdP parameter to finishLogout deprecated

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/simplesamlphp#1743]
Since b163ce840686a5b185aad8b7544b4e0c081e07ee the `$idp` parameter to `IdP::finishLogoutRedirect()` [is deprecated](https://github.com/simplesamlphp/simplesamlphp/blob/4b959dff6633f7d978475c3fc41452247071e89a/src/SimpleSAML/IdP.php#L547) with no clear course of action.

Either we should remove it now after being deprecated for so long, or just remove the notice that it's deprecated.

**Comment by tvdijen** [comment]
I opt for removing it. It's not used in the method and the IdP-class is not something I expect people to extend from.

**Comment by tvdijen** [comment]
Closed in 8c901218b
