### ISSUE TITLE
Broken changelog and upgrade notes links in RC 3 release

### ISSUE THREAD

**Issue by drjayvee** [simplesamlphp/simplesamlphp#1753]
The links in the [latest RC release](https://github.com/simplesamlphp/simplesamlphp/releases/tag/v2.0.0-rc3) don't work:

* https://simplesamlphp.org/docs/simplesamlphp-2.0/simplesamlphp-changelog
* https://simplesamlphp.org/docs/simplesamlphp-2.0/simplesamlphp-upgrade-notes-2.0

Both provide 404s.

**Comment by thijskh** [comment]
Thanks, I've updated the links now, they will be versioned once the release is final.
