### ISSUE TITLE
Small wiki update suggestion regarding Twig translation migration

### ISSUE THREAD

**Issue by cicnavi** [simplesamlphp/simplesamlphp#1756]
Hi, just a small hint on the outdated wiki info which I stumbled upon... I would do a pull request, but as it seems - can't do that for wikis...

On SimpleSAMLphp wiki page https://github.com/simplesamlphp/simplesamlphp/wiki/Migrating-translation-in-Twig

There is a notion of 'language.i18n.backend' config option, which doesn't exist (anymore).

Also, it states an example of using tag translation method which doesn't work (anymore): 

`{% trans 'Short string' %}`

This (now) throws:

`Twig\Error\SyntaxError: Unexpected token. Twig was looking for the "with", "from", or "into" keyword.`

From [Symfony Translations in Templates](https://symfony.com/doc/current/translation.html#translations-in-templates) it is now noted that when using 'tags' for translations, the %var% notation of placeholders is required.

Here is the suggested patch:

[Update_twig_translation_migration_page.patch](https://github.com/simplesamlphp/simplesamlphp/files/10578138/Update_twig_translation_migration_page.patch)

Best regards

**Comment by tvdijen** [comment]
Wiki was updated!
