### ISSUE TITLE
Conditional AuthProcFilter 

### ISSUE THREAD

**Issue by malavolti** [simplesamlphp/simplesamlphp#1766]
**Problem**
I didn't find an easy way to support the REFEDS Assurance Framework and MFA without a third-part module developed by CIRRUS[1]. Their module allowed me to respect the requirements about the AuthnContextClassRef that an IdP and an SP have to respect for asking and answering MFA. 
The Request (SP) and the Response (IdP) have to contain the right value of AuthnContextClassRef **only if** they ask/provide a MultiFactorAuthentication. 
CIRRUS has implemented an easy way to use one or another AuthProcFilter through a condition and this made possible to address the REFEDS Assurance Framework. Their module allow me to activate an AuthProcFilter only on a specific condition: if an SP requests MFA, than the IdP answers with MFA, else... The IdP answers with a username/password login page only. 

https://github.com/cirrusidentity/simplesamlphp-module-cirrusgeneral/#phpconditionalauthprocinserter

**Describe the solution you'd like**

I ask to do the same with only official SimpleSamlPhp code. I hope to find an official way to use the AuthProcFilters conditionally to be able to manage different behaviors of SPs or other. 

**Describe alternatives you've considered**
I didn't find any other easy solution other than CIRRUS Plugin:

https://github.com/cirrusidentity/simplesamlphp-module-cirrusgeneral/#phpconditionalauthprocinserter

**Comment by tvdijen** [comment]
Hi @malavolti ! I think for your use-case you can use the `RequestedAuthnContextSourceSelector` in SSP v2.0;
https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/core/docs/authsource_selector.md

It allows you to use different authsources based on the RequestedAuthnContext (and will return the appropriate AuthnContextClassRef)

**Comment by malavolti** [comment]
Thanks Tim,

I see that you mentioned "`authsources`", but I think I need an "**Authentication Process Filters**" that allows me to add the request of the second factor in addition to the the first one and only if the SP requires it with the `AuthnContextClassRef` into its assertion.

I didn't understand if the solution you proposed asks the username/password first and then the second factor or not.

Can you help me to understand this, please?

Thank you Tim.

**Comment by tvdijen** [comment]
> of the second factor in addition to the the first one [...] into its assertion.
You can only add one `AuthnContextClassRef` in a Response...

Anyway, in my proposed solution the authsource has to take care of the second factor. If you want to ask for the second factor in a second step, you have to use an authproc-filter. What's the reason you don't want to use cirrus' version of the conditional authproc?

**Comment by malavolti** [comment]
Thanks Tim for your availability,
I think that there are several reasons:
1) As a third part plugin, it can be broken by the future version of SimpleSAMLphp
2) As a third part plugin, Cirrus can decide to not maintain it anymore in the future
3) As a third part plugin, I need to check every time what it does to be sure that it is not dangerous to import it  into my IdPs

I think it is a good feature to be implemented into the Core of SimpleSAMLphp.

What do you think about?

**Comment by tvdijen** [comment]
I'm OK with importing the filter into SSP core, but there is no reason to distrust Cirrus.
In fact, they are a close partner represented in the SSP board and also one of our main donors.
