### ISSUE TITLE
2.0: TypeError on IDP-initiated logout

### ISSUE THREAD

**Issue by htto** [simplesamlphp/simplesamlphp#1776]
**Describe the bug**
When trying to initiate a logout directly from the IDP a TypeError is thrown: `TypeError: Argument 2 passed to SimpleSAML\IdP\TraditionalLogoutHandler::startLogout() must be of the type string, null given`

**To Reproduce**
1. Go to `http://idp/simplesaml/module.php/saml/idp/initSingleLogout?RelayState=http://idp`
2. See error

**Expected behavior**
Expected to get logged out of all known SPs.

**Screenshots or logs**
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 .../vendor/simplesamlphp/simplesamlphp/public/_include.php:31 (SimpleSAML_exception_handler)
1 .../vendor/symfony/error-handler/ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: TypeError: Argument 2 passed to SimpleSAML\IdP\TraditionalLogoutHandler::startLogout() must be of the type string, null given
Backtrace:
4 .../vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/IdP/TraditionalLogoutHandler.php:85 (SimpleSAML\IdP\TraditionalLogoutHandler::startLogout)
3 [builtin] (call_user_func_array)
2 .../vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/HTTP/RunnableResponse.php:72 (SimpleSAML\HTTP\RunnableResponse::sendContent)
1 .../vendor/symfony/http-foundation/Response.php:394 (Symfony\Component\HttpFoundation\Response::send)
0 .../vendor/simplesamlphp/simplesamlphp/public/module.php:14 (N/A)
```

**Additional context**
There seems to be some confusion if `assocId` in `startLogout` is/should be nullable:
```
src/SimpleSAML/IdP/LogoutHandlerInterface.php
    public function startLogout(array &$state, string $assocId): void;
src/SimpleSAML/IdP/IFrameLogoutHandler.php
    public function startLogout(array &$state, ?string $assocId): void
src/SimpleSAML/IdP/TraditionalLogoutHandler.php
    public function startLogout(array &$state, string $assocId): void
modules/core/src/Controller/Logout.php
        $assocId = $state['core:TerminatedAssocId'];
        return new RunnableResponse([$idp->getLogoutHandler(), 'startLogout'], [&$state, $assocId]);
src/SimpleSAML/IdP.php
        if ($assocId !== null) {
            $handler = $this->getLogoutHandler();
            $handler->startLogout($state, $assocId);
```

Since this is IDP-initiated there's no association that initiated the logout, which in several places is accounted for. Looking at the code I suspect, that the interface for `startLogout` should get a nullable `assocId` as well as all implementations of it. Marking `TraditionalLogoutHandler::startLogout`'s `assocId` nullable allows for proper logout.

**Comment by tvdijen** [comment]
Confirmed; Between 1.19 and 2.0 type-hints have been added. Based on the phpdocs `IFrameLogoutHandler` could take `null` for assocId, the others not. So the next step is to figure out if the phpdocs were wrong or not

**Comment by htto** [comment]
This frankly is a bit fishy... The commit b7306fa8097e403b255ab0187438b6402466f250
```
commit b7306fa8097e403b255ab0187438b6402466f250
Author: Tim van Dijen <tvdijen@gmail.com>
Date:   Sun Feb 3 01:09:49 2019 +0100

    Fixes for lib/SimpleSAML/IdP
```
changed the docblock typehint for `LogoutHandlerInterface::startLogout`'s `assocId` from `string|null` to `string`. Unfortunately, I cannot make much out of "Fixes". Additionally `TraditionalLogoutHandler::startLogout` seems to have never used the `assocId` parameter, but documented it non-nullable.

So I'd say it should be the other way around, i.e. `assocId` nullable on the interface and all implementations.

**Comment by tvdijen** [comment]
I believe that commit was to fix issues reported by Psalm. I will have to investigate this further, because honestly I wasn't even aware of the fact that you could initiate SLO from an IDP.

**Comment by htto** [comment]
The corresponding endpoint should be `SingleLogout::initSingleLogout` in `simplesamlphp/modules/saml/src/Controller/SingleLogout.php`:
```
    /**                                                                                                                 
     * This endpoint will initialize the SLO flow at the SAML 2.0 IdP.                                                  
     *                                                                                                                  
     * @param \Symfony\Component\HttpFoundation\Request $request                                                        
     * @return \SimpleSAML\HTTP\RunnableResponse                                                                        
     */                                                                                                                 
    public function initSingleLogout(Request $request): RunnableResponse  
```

**Comment by htto** [comment]
@tvdijen Thank you for fixing this and releasing 2.0.1! Our downstream integration runs fine and the error log is clean as well :)
