### ISSUE TITLE
[QQ] guide about how to migrate from v1.19 to v2.0

### ISSUE THREAD

**Issue by sunhubs** [simplesamlphp/simplesamlphp#1784]
hi there,
    as the new stable v2.0.0 released, and I just want to know the difference between the old v1.19, and the maintaince plan of old version, including new feature and security issues fix?
    if v1.19 will plan out, do you have a guide to help migration?
Thanks.

**Comment by tvdijen** [comment]
v1.19 will receive security bugfixes until the end of this year.
For migration;  it really depends on what features you have been using in the past. Start by reading the upgrade notes?
