### ISSUE TITLE
Old sessions from v1 to v2 upgrade

### ISSUE THREAD

**Issue by nnillni** [simplesamlphp/simplesamlphp#1788]
Hello,

We are trying to upgrade from v1 to v2.0.0 but we seem to have an issue with older sessions.
It seems like trying to authenticate with an old session ends up with an "unserialize" error on the following file.

```
simplesamlphp/src/SimpleSAML/SessionHandlerPHP.php (line 249)
Warning: Class SimpleSAML\Session has no unserializer
```
I get a warning because I am in development, but skipping the warning will still break other stuff that is supposed to exist (session attributes from the unserialize, etc).

What is the best way forward here? 
I was experimenting by doing a try/catch in these cases that redirects to a logout flow so the user has to sign in again, is that how we should go around that?
I am worried as this seems to be a Warning, which does not trigger in Production so it might not work unless changed to an Exception.

Any advice is welcome, thanks!

**Comment by tvdijen** [comment]
Hi @nnillni !

As you can read in the [upgrade notes](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-upgrade-notes-2.0.md), you have to clear your session cache when upgrading.
There is absolutely no way to get this working in a backwards compatible way.
