### ISSUE TITLE
Unable to get metadata from idp after upgrading from 2.0-rc1 to 2.0.2; federation page is blank

### ISSUE THREAD

**Issue by surfrock66** [simplesamlphp/simplesamlphp#1789]
**Describe the bug**
I had been testing 2.0-rc1 and it was working fine.  I finally got around to upgrading to 2.0.2, and after following the upgrade guide AND the "1.19->2.0" doc (including making changes to things like www->public) my site works, however when I log into the administration page and go to "Federation" there is no metadata listed.  I have also attempted to remove the metadata directory copied from previous installations and start with a fresh one, but the federation page remains blank.

Neither the saml, php, nor apache logs show any error at all.

My auth sources appear to be working; I can test my ldap, admin, and default auth sources successfully, but without metadata I cannot federate with my sp's.

**To Reproduce**
1. Go to the admin page
2. Click on 'Federation'
3. See error

**Expected behavior**
The metadata for the idp should be visible to enter into the sp's

**Screenshots or logs**
![image](https://user-images.githubusercontent.com/1345467/225074886-899f1a44-80a3-4d3d-9a86-df484757cd4e.png)

**Comment by tvdijen** [comment]
I've seen this myself and remember it was a stupid mistake, but I cannot recall the exact cause.
Have you set an entityID for your hosted IdP?

**Comment by tvdijen** [comment]
Make sure `enable.saml20-idp` is set to `true` and that entries in `saml20-idp-hosted.php` have an entityID as their array index (setting it to __DYNAMIC:1__ is no longer supported)
