### ISSUE TITLE
Using ${var} in strings is deprecated, use {$var} instead

### ISSUE THREAD

**Issue by murraycollingwood** [simplesamlphp/simplesamlphp#1790]
**Describe the bug**
LASTERROR: Array (    
[type] => 8192    
[message] => Using ${var} in strings is deprecated, use {$var} instead    
[file] => vendor/simplesamlphp/simplesamlphp/modules/saml/lib/Auth/Source/SP.php
[line] => 916

**To Reproduce**
Some situation when ->requireAuth() is run.  Not sure why specifically.

**Expected behavior**
Code change to {$var}

**Comment by thijskh** [comment]
I guess you’re not using 2.0.0 final or later? This has been fixed since.

**Comment by murraycollingwood** [comment]
Is 2.0.0 backward compatible?  (Are there any breaking changes if I update?)

**Comment by tvdijen** [comment]
Depending on your setup there could be few or many BC breaks.
We can help you with upgrading! Can you tell us a bit more about your environment? What features are you using, and what modules?

The [upgrade-notes](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-upgrade-notes-2.0.md) should be a good starter for you to inventory the changes that affect you.

**Comment by tvdijen** [comment]
PS: How is the `${var}` thing bothering you besides warnings in your logs? It's a deprecation notice, not an error, so it shouldn't affect your 1.19.x install.

**Comment by tvdijen** [comment]
Never seen anything like a 'shutdown event', and I'm running 8.2 as well..
What's the value of the 'error_reporting' setting (php.ini) on your install?

**Comment by murraycollingwood** [comment]
It's a way of capturing errors at the end of a php script:
`register_shutdown_function("my_shutdown_function");`

**Comment by tvdijen** [comment]
Ah, ah custom shutdown function! Makes sense!
You should be able to ignore the `E_DEPRECATED` class in there.

I _did_ backport the fix for this to 1.19.x, but we don't really have any new releases coming up for that branch unless it's a security patch.

Please let us know if we can help you with your upgrade!

**Comment by murraycollingwood** [comment]
Thanks - you guys are awesome!

**Comment by tvdijen** [comment]
Closing this issue; will be resolved in a future release
