### ISSUE TITLE
No folder and file in public/assets

### ISSUE THREAD

**Issue by krisskals** [simplesamlphp/simplesamlphp#1793]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
After installing simplesamlphp using the composer require simplesamlphp/simplsamlphp command, there is no file in the /vendor/simplesamlphp/simplesamlphp/public/assets directory.
I also noticed a symfony/console library compatibility problem. I currently have version ^6 and it requires simplesamlphp 5^. I had to use composer commands with -W

**Comment by tvdijen** [comment]
So your project uses symfony 6, and we support up to 5.4.. This is not going to work
