### ISSUE TITLE
website simplesamlphp.org gone

### ISSUE THREAD

**Issue by willemb2** [simplesamlphp/simplesamlphp#1799]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
Contents related to SimpleSAMLphp disappeared from simplesamlphp.org. It shows links to 'discount leather jackets', 'internet dating' etc.

**To Reproduce**
1. [Go to '...'](https://simplesamlphp.org/)

**Expected behavior**
See contents like https://web.archive.org/web/20230404233010/https://simplesamlphp.org/

**Screenshots or logs**
See attached screenshot

**Additional context**
Newby here, just learned about SimpleSAMLphp on a forum and a bit disappointed by the website.

![2023-04-18 13_59_22-Simplesamlphp org](https://user-images.githubusercontent.com/35876924/232771213-5ad907d9-1768-4074-9bb9-2a2c1e1e07dc.jpg)

**Comment by thijskh** [comment]
😱 Thanks for reporting! We'll get this fixed ASAP

**Comment by tvdijen** [comment]
Our website is back! Thanks for reporting!

**Comment by willemb2** [comment]
Thanks, that was quick 👏Nu kan opa leren SAMLlen.
