### ISSUE TITLE
MDQ expiration issues

### ISSUE THREAD

**Issue by liedekef** [simplesamlphp/simplesamlphp#1803]
**Describe the bug**
MDQ cacheDuration and validUntil are not used

**To Reproduce**
1. An MDQ url contains (or should) "cacheDuration" and "validUntil"
2. simplesamlphp only looks at validUntil and stores it in an array key "expire" (in SAMLParser.php )
3. MDQ code checks the cached data but searches for the key "expires" (mark the extra "s"), see lib/SimpleSAML/Metadata/Sources/MDQ.php , function getMetaData (around line 293)

**Expected behavior**
Correct interpretation of cacheDuration and validUntil: when cacheDuration expires, an attempt should be done to redownload the wanted xml. When validUntil expires, the xml should be invalidated (if not refreshed this can happen)

**Comment by tvdijen** [comment]
Have you tried removing the extra `s`? Did that solve the issue for you?

**Comment by liedekef** [comment]
Removing the "s" solves it (adding extra debug to make sure):
```
        if ($data !== null && array_key_exists('expire', $data) ) {
            Logger::debug(__CLASS__ . ': Checking expiry date: ' . $data['expire'] . '.');
            if ($data['expire'] < time()) {
                    // metadata has expired
                    $data = null;
                    Logger::debug(__CLASS__ .' : metadata has expired ');
            }
        }
```
I also went a little further and found that simplesamlphp uses a setting 'cachelength' per mdq-source (and not cacheDuration from the xml), so that's fine by me (now that I know it :-) )

**Comment by tvdijen** [comment]
Ah wait, you are using SSP 1.19.x...
I'm a little hesitant removing the `s` in 2.0/master, because so much stuff has been changed.
Any chance you could verify this behavior with 2.0?

**Comment by liedekef** [comment]
I verified MDQ.php in 2.0 and it contains the same error:

```
        if (isset($data)) {
            if (array_key_exists('expires', $data) && $data['expires'] < time()) {
                // metadata has expired
                $data = null;
            } else {
                // metadata found in cache and not expired
                Logger::debug(sprintf('%s: using cached metadata for: %s.', __CLASS__, $entityId));
                return $data;
            }
        }
```
There the "expires" is also present, but currently I'm not able to test that (yet).
What I also see (and recommend against) is the use of serialize/unserialize for mdq cache. The recommended way is to use json_encode/decode there (to avoid object injection in any way).

**Comment by tvdijen** [comment]
Do you have an example of how this could be abused?

**Comment by liedekef** [comment]
If the xml contains weirdly formatted data (from an SP for example), there's a theoretical possibility. In this case, I'm just providing "best practice" avoiding the possibility 100%. But feel free to not react on this :-)

**Comment by tvdijen** [comment]
Oh no it's not like that at all, I'm just trying to understand what could possibly go wrong. I will definitely take this into account

**Comment by liedekef** [comment]
Well, like I said: it is a theoretical possible to do php object injection in a serialized file (which, upon unserialize, is then interpreted). For reference: https://pagely.com/blog/object-injection-vulnerabilities-in-php/

**Comment by tvdijen** [comment]
This is what I was looking for! Thansk @liedekef !

**Comment by tvdijen** [comment]
Fixed both the `s` issue as well as the object injection issue. Will be released in 1.19.8 and 2.0.4

**Comment by liedekef** [comment]
Thanks. But what about existing cache files? These will fail on json_decode (if they were saved as serialized files)

**Comment by tvdijen** [comment]
Yes, so cache has to be cleared on update. I will add a note in the changelog
