### ISSUE TITLE
SSP 1.13.2 - FriendlyName for the SP attributes don't work

### ISSUE THREAD

**Issue by malavolti** [simplesamlphp/simplesamlphp#181]
Hi,

few days ago I've installed a new instance of SimpleSAMLphp SP 1.13.2 on a personal virtual machine.

On [this page](https://simplesamlphp.org/docs/stable/saml:sp) I've seen that is possible to add the FriendlyName for the RequestedAttributes of SP's metadata:

**attributes**
List of attributes this SP requests from the IdP. This list will be added to the generated metadata.
The attributes will be added without a NameFormat by default. Use the attributes.NameFormat option to specify the NameFormat for the attributes.
An associative array can be used, mixing both elements with and without keys. When a key is specified for an element of the array, it will be used as the friendly name of the attribute in the generated metadata.
*Note*: This list will only be added to the metadata if the `name`-option is also specified.

This is my "authsources.php" configuration for attributes:

         'attributes' => array(
            'cn' => 'urn:oid:2.5.4.3',
            'mail' => 'urn:oid:0.9.2342.19200300.100.1.3',
            'eduPersonTargetedID' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
            'eduPersonPrincipalName' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
         ),
         'attributes.required' => array(
              'urn:oid:1.3.6.1.4.1.5923.1.1.1.10', 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
         ),

and this is the result on the SP metadata:

        <md:RequestedAttribute Name="urn:oid:2.5.4.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"/>
        <md:RequestedAttribute Name="urn:oid:0.9.2342.19200300.100.1.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri"/>
        <md:RequestedAttribute Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.10" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true"/>
        <md:RequestedAttribute Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" isRequired="true"/>

I have understood, from the pull request #122 , that the issue was solved, but seems not it is so... right?

The fix is simple. It is enough change the line 126 on "`modules/saml/www/sp/metadata.php`" file from:
`$attributes = array_values($spconfig->getArray('attributes', array()));`
to
`$attributes = $spconfig->getArray('attributes', array());`

I have done this change on my ssp-sp code and this is the result:

      <md:RequestedAttribute Name="urn:oid:2.5.4.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="cn"/>
      <md:RequestedAttribute Name="urn:oid:0.9.2342.19200300.100.1.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="mail"/>
      <md:RequestedAttribute Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.10" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="eduPersonTargetedID" isRequired="true"/>
      <md:RequestedAttribute Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="eduPersonPrincipalName" isRequired="true"/>

After that change I have modified also my "authsources.php" file in the way suggested from the [Documentation Examples](https://simplesamlphp.org/docs/stable/saml:sp):

         'attributes' => array(
            'cn' => 'urn:oid:2.5.4.3',
            'mail' => 'urn:oid:0.9.2342.19200300.100.1.3',
            'eduPersonTargetedID' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.10',
            'eduPersonPrincipalName' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.6',
         ),
         'attributes.required' => array(
              'eduPersonTargetedID', 'eduPersonPrincipalName',
         ),
 
and this is the result:

      <md:RequestedAttribute Name="urn:oid:2.5.4.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="cn"/>
      <md:RequestedAttribute Name="urn:oid:0.9.2342.19200300.100.1.3" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="mail"/>
      <md:RequestedAttribute Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.10" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="eduPersonTargetedID"/>
      <md:RequestedAttribute Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.6" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri" FriendlyName="eduPersonPrincipalName"/>

the attributes that should be " `isRequire='true'`" appear as desired.

I have done something wrong or there is an error into the simplesamlphp code?

Thank you so much!
Marco

**Comment by jaimeperez** [comment]
Hi @malavolti!

Please note that SimpleSAMLphp 1.13.2 was released before issue #122 was submitted. Therefore, the fix is not included there.

**Comment by malavolti** [comment]
Hi @jaimeperez!

Thank you so much for the information and sorry for the question.

**Comment by jaimeperez** [comment]
No problem at all! :smiley:
