### ISSUE TITLE
Admin page incorrectly states that hosted IdP metadata is not present

### ISSUE THREAD

**Issue by JeffLCN** [simplesamlphp/simplesamlphp#1810]
**Describe the bug**
On a working installation of version 2.0.4, the front admin page seems to report incorrectly that hosted IdP metadata is not present, when it is in fact present.

**To Reproduce**
Go to the /simplesaml/admin page and scroll to the bottom under "Your PHP installation"

**Expected behavior**
When hosted IdP metadata is present, a checkmark should appear next to that item, instead of a circle with a slash.

**Screenshots or logs**
This is incorrectly displayed:
![unnamed](https://github.com/simplesamlphp/simplesamlphp/assets/134621558/d289390a-14ac-41c8-8d48-9a6487e91aee)

**Comment by thijskh** [comment]
The check is for the "current" entityID. If you browse to the admin interface on an URL that does not correspond to a listed hosted IdP, it will think there's not an hosted IdP. Is this indeed the case for you?

**Comment by tvdijen** [comment]
For me that was the case. My other issue was a severe case of PEBCAK 🤐

**Comment by tvdijen** [comment]
Since we haven't heard back from @JeffLCN, I'm closing this issue

**Comment by affiqs** [comment]
I'm testing IdP setting. Admin page incorrectly states that hosted IdP is unable to download server.pem. But it works if I change server.pem permissions to 444. Also, it works correctly with the server.pem permissions 400 and www-data:www-data ownership.
Both give the same result like on the image below. What are right settings?
![server-pem](https://github.com/simplesamlphp/simplesamlphp/assets/61951378/ebc12901-7969-4d21-a068-faaf9c6a9e39)

**Comment by tvdijen** [comment]
Your webserver needs read-permissions on the entire simplesamlphp installation-dir, including the contents of the `cert/` directory. How you achieve this (i.e. ownership, permissions, or ACL) is entirely up to you.
