### ISSUE TITLE
cron.php checks the file owner and not the user running the script

### ISSUE THREAD

**Issue by skloepp2** [simplesamlphp/simplesamlphp#1821]
With the commit https://github.com/simplesamlphp/simplesamlphp/commit/153d109daede7597e593e0e7fcc9a6ddd2660318 you changed the code inside the cron.php. The new code does not longer check the user running the script but checks the file owner. The ownership shouldn't be a problem as long as the script is not executed as root.

https://github.com/simplesamlphp/simplesamlphp/blob/fdbe0017488f831cfd857ceefb0cd807088b5d83/modules/cron/bin/cron.php#L27

**Comment by tvdijen** [comment]
What was I thinking ?!?
I reverted the change. Thanks for reporting!
