### ISSUE TITLE
Composer 2.3.0 is vulnerable - update composer version used for dependencies

### ISSUE THREAD

**Issue by slaweknaczynski** [simplesamlphp/simplesamlphp#1827]
Based on "plugin-api-version" information in the composer.lock file - https://github.com/simplesamlphp/simplesamlphp/blob/master/composer.lock - the current version of composer used for managing dependencies is 2.3.0. This version has a High / Critical vulnerability and it's highly recommended to upgrade  (https://github.com/advisories/GHSA-x7cr-6qr6-2hh6). As there are a lot of dependencies it would be good to make sure that non-vulnerable version of composer is used for managing them.

**Comment by tvdijen** [comment]
![afbeelding](https://github.com/simplesamlphp/simplesamlphp/assets/841045/afa2a8cf-fc99-4351-b1c1-98966dba0a85)

I'm not sure where you're looking, but we ship SimpleSAMLphp with a non-vulnerable version...
