### ISSUE TITLE
bug , it's failing to load

### ISSUE THREAD

**Issue by ylapin** [simplesamlphp/simplesamlphp#1830]
I'm using php 7.4 as fpm I'm getting the following error

[24-Jul-2023 15:14:36 UTC] PHP Fatal error:  Uncaught Exception: Unable to load Composer autoloader /usr/share/php/simplesamlphp in /usr/share/php/simplesamlphp/src/_autoload.php:20
Stack trace:
#0 /usr/share/php/simplesamlphp/www/_include.php(6): require_once()
#1 /usr/share/php/simplesamlphp/www/index.php(7): require_once('/usr/share/php/...')
#2 {main}
  thrown in /usr/share/php/simplesamlphp/src/_autoload.php on line 20
[24-Jul-2023 15:57:41 UTC] PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/simplesamlphp/public/_include.php on line 52
[24-Jul-2023 15:57:43 UTC] PHP Parse error:  syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/simplesamlphp/public/_include.php on line 52

checking syntax I get the following error

Parse error: syntax error, unexpected ')', expecting variable (T_VARIABLE) in /var/simplesamlphp/public/_include.php on line 52
Errors parsing /var/simplesamlphp/public/_include.php

what's wrong???

**Comment by tvdijen** [comment]
You can't use the `master` branch together with PHP 7.4.. Use a tagged release instead.

**Comment by ylapin** [comment]
which version work with PHP 7.4???

**Comment by jaimeperez** [comment]
The [upgrade notes](https://simplesamlphp.org/docs/stable/simplesamlphp-upgrade-notes-2.0.html) clearly state the software requirements for each release. `2.0` supports PHP `7.4`.

**Comment by ylapin** [comment]
I success to install version 2 form the correct branch but still there is an error

[25-Jul-2023 09:10:55 UTC] PHP Fatal error:  Uncaught Exception: Unable to load Composer autoloader in /var/simplesamlphp/src/_autoload.php:19
Stack trace:
#0 /var/simplesamlphp/public/_include.php(6): require_once()
#1 /var/simplesamlphp/public/index.php(7): require_once('/var/simplesaml...')
#2 {main}
  thrown in /var/simplesamlphp/src/_autoload.php on line 19


***@***.***
Yair Lapin | Head Webmaster

Information Systems
The Hebrew University of Jerusalem
T +972.2.6584384 | F +972.26586930
***@***.***

**Comment by tvdijen** [comment]
It seems like you didn't run a `composer install`... Perhaps you are better of with a pre-built release?

**Comment by ylapin** [comment]
Yes I needed to go into /var/simplesamlphp directory and do

composer require simplesamlphp/simplesamlphp-module-ldap --update-no-dev

but it's not clear in the install explain also it's not clear you must do git clone using branch like this

git clone --branch simplesamlphp-2.0  https://github.com/simplesamlphp/simplesamlphp.git

the best is to suggest a composer installation because it can do everything easy in one command



***@***.***
Yair Lapin | Head Webmaster

Information Systems
The Hebrew University of Jerusalem
T +972.2.6584384 | F +972.26586930
***@***.***
