### ISSUE TITLE
Getting PHP error while calling requireAuth() API

### ISSUE THREAD

**Issue by b0dhib** [simplesamlphp/simplesamlphp#1837]
**Describe the bug**
I am running the following lines of code:

$auth = new \SimpleSAML\Auth\Simple('default-sp');
if($auth->isAuthenticated()){
        $attributes = $auth->getAttributes();
        print_r($attributes);
}else{
        $auth->requireAuth();
        echo $auth->getLoginUrl();
        echo "Not authenticated";
}

Now if I am logged in to simplesamlphp from a separate tab in the same browser and then running this code I am getting the attributes printed successfully on the screen. But when I am not logged in, then $auth->requireAuth() is getting called and giving the following error:
( ! ) Fatal error: Uncaught Error: Typed static property SimpleSAML\SAML2\Compat\ContainerSingleton::$container must not be accessed before initialization in /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Compat/ContainerSingleton.php on line 22

Please help me to resolve the issue

**To Reproduce**

**Expected behavior**
It should redirect to the IdP login screen

**Screenshots or logs**
I am attaching screenshots of the code snippet that I am running and the issue that I am getting on browser for reference:
![image](https://github.com/simplesamlphp/simplesamlphp/assets/130538091/6b56df5e-c416-4525-8f59-672f06adc396)
![image](https://github.com/simplesamlphp/simplesamlphp/assets/130538091/315b01f2-31e0-4998-9700-86395f693b21)

**Additional context**

**Comment by tvdijen** [comment]
Hi @b0dhib !

Please use a released version of SimpleSAMLphp instead of our developement-branch.

**Comment by b0dhib** [comment]
@tvdijen Thanks for the reply
Can you give me the link of the released version to download please ?

Please not that I have installed this version from the github repo
https://github.com/simplesamlphp/simplesamlphp.git

**Comment by tvdijen** [comment]
`git clone -b v2.0.5 https://github.com/simplesamlphp/simplesamlphp.git` should work for you.
