### ISSUE TITLE
ReturnCallback parameter in login api giving error

### ISSUE THREAD

**Issue by b0dhib** [simplesamlphp/simplesamlphp#1840]
**Describe the bug**
I am trying to utilize the ReturnCallback parameter of login api as below:
 $auth->login([
        'ReturnCallback' => 'https://www.example.org/saml_callback.php',
 ]);
But it is giving me error as in the given screenshot below

![image](https://github.com/simplesamlphp/simplesamlphp/assets/130538091/81152e70-9fbe-454c-a8c8-f143e1f29788)

My requirement is that post authentication, I should be redirected first to the url mentioned in ReturnCallback parameter and then 
to the current page from where the api is called

Please let me now what I am doing wrong here 
 
**To Reproduce**

**Expected behavior**

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.

**Additional context**

**Comment by tvdijen** [comment]
The `ReturnCallback`-parameter does something completely different than what you want to achieve.
What you need to use is the `ReturnTo`-parameter.
