### ISSUE TITLE
SimpleSAML 2.0.5: version incompatibility for authorize and metarefresh modules during composer installation

### ISSUE THREAD

**Issue by s0rin** [simplesamlphp/simplesamlphp#1845]
**Describe the bug**
Requirements could not be resolved to an installable set of packages

**To Reproduce**
1. SimpleSAML 2.0.5 is present
2. `statistics` and `memcookie` modules could be installed (they are compatible with `assert` module v1.1.8)
3. Attempt to install `authorize` and/or `metarefresh` will fail due to conflicts with `assert` module version

```
# composer require simplesamlphp/simplesamlphp-module-authorize

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires simplesamlphp/simplesamlphp-module-authorize ^1.3 -> satisfiable by simplesamlphp/simplesamlphp-module-authorize[v1.3.0].
    - simplesamlphp/simplesamlphp-module-authorize v1.3.0 requires simplesamlphp/assert ^1.0.4 -> found simplesamlphp/assert[v1.0.4] but it conflicts with your root composer.json require (^0.8.0).

# composer require simplesamlphp/simplesamlphp-module-metarefresh

  Problem 1
    - Root composer.json requires simplesamlphp/simplesamlphp-module-metarefresh ^1.1 -> satisfiable by simplesamlphp/simplesamlphp-module-metarefresh[v1.1.0].
    - simplesamlphp/simplesamlphp-module-metarefresh v1.1.0 requires simplesamlphp/assert ^1.0.0 -> found simplesamlphp/assert[v1.0.0, ..., v1.0.4] but it conflicts with your root composer.json require (^0.8.0).
```

4. Attempt to install a newer version of `assert` would fail

```
# composer require simplesamlphp/assert

  Problem 1
    - simplesamlphp/simplesamlphp-module-statistics is locked to version v1.1.8 and an update of this package was not requested.
    - simplesamlphp/simplesamlphp-module-statistics v1.1.8 requires simplesamlphp/assert ^0.8.0 -> found simplesamlphp/assert[v0.8.0] but it conflicts with your root comp   oser.json require (^1.0).
  Problem 2
    - simplesamlphp/xml-security is locked to version v0.6.6 and an update of this package was not requested.
    - simplesamlphp/xml-security v0.6.6 requires simplesamlphp/assert ^0.8.0 -> found simplesamlphp/assert[v0.8.0] but it conflicts with your root composer.json require (   ^1.0).
  Problem 3
    - simplesamlphp/xml-security v0.6.6 requires simplesamlphp/assert ^0.8.0 -> found simplesamlphp/assert[v0.8.0] but it conflicts with your root composer.json require (   ^1.0).
    - simplesamlphp/simplesamlphp-module-adfs v2.0.1 requires simplesamlphp/xml-security ~0.6.6 -> satisfiable by simplesamlphp/xml-security[v0.6.6].
    - simplesamlphp/simplesamlphp-module-adfs is locked to version v2.0.1 and an update of this package was not requested.

```

**Expected behavior**
To be able to install any simplesamlphp module

**Comment by tvdijen** [comment]
Hi @s0rin !  Is this still a problem with a freshly downloaded version of v2.0.5?
Something went wrong during the building of the release, so we re-released it last week and uploaded a fresh tarball that shouldn't have this issue.

**Comment by s0rin** [comment]
It seems this still a problem, I downloaded it yesterday and today again [1], the `composer.json` contains:
`       ...
       "simplesamlphp/assert": "^0.8.0",
       ...`
[1] https://github.com/simplesamlphp/simplesamlphp/releases/download/v2.0.5/simplesamlphp-2.0.5.tar.gz

**Comment by tvdijen** [comment]
I can understand where this is going wrong.. The assert-lib has been a pain in the ass before because we started versioning below < 1.0.0 .. Composer treats this differently.
What probably would work for you is if you install the problematic modules first, and then the other ones.. Composer should be smart enough to stick with v0.8 of the assert library

I will tag new versions of the problematic modules later today

**Comment by tvdijen** [comment]
Just out of curiousity; have you installed SSP 2.0.x before and has this issues popped up in 2.0.5, or are you upgrading from 1.1x.x?

**Comment by s0rin** [comment]
Nope, I won't work, `authorize` or `metarefresh` module expect `assert` version 1.0.0

```
# composer require simplesamlphp/simplesamlphp-module-authorize

  Problem 1
    - Root composer.json requires simplesamlphp/simplesamlphp-module-authorize ^1.4 -> satisfiable by simplesamlphp/simplesamlphp-module-authorize[v1.4.0].
    - simplesamlphp/simplesamlphp-module-authorize v1.4.0 requires simplesamlphp/assert ^1.0.4 -> found simplesamlphp/assert[v1.0.4, v1.0.5] but it conflicts with your root composer.json require (^0.8.0).

# composer require simplesamlphp/simplesamlphp-module-metarefresh

  Problem 1
    - Root composer.json requires simplesamlphp/simplesamlphp-module-metarefresh ^1.2 -> satisfiable by simplesamlphp/simplesamlphp-module-metarefresh[v1.2.0].
    - simplesamlphp/simplesamlphp-module-metarefresh v1.2.0 requires simplesamlphp/assert ^1.0.0 -> found simplesamlphp/assert[v1.0.0, ..., v1.0.5] but it conflicts with your root composer.json require (^0.8.0).
```

I created the Dockerfile for SSP 2.0.2 or 2.0.3 some time ago (but never on the production) and at that time the composer didn't complain about any version incompatibilities.

**Comment by tvdijen** [comment]
Maybe because I tagged compatible releases for the two modules (1.4 and 1.2).
