### ISSUE TITLE
For logout-iframe-post URL the old script name is used instead of routing

### ISSUE THREAD

**Issue by danielrickers** [simplesamlphp/simplesamlphp#1846]
https://github.com/simplesamlphp/simplesamlphp/blob/bd129fef672a766400c19510b266d86fb6e3e39c/modules/saml/src/IdP/SAML2.php#L765

When using this and having first SLO happen, it failed because of unknown script "core/idp/logout-iframe-post.php". The new routing expects "core/logout-iframe-post" here to work properly.

**Comment by tvdijen** [comment]
Thanks for reporting @danielrickers !

**Comment by danielrickers** [comment]
Hi @tvdijen, in commit #1846 you removed the ".php", also the path "idp/" has to be removed for routing to work.

**Comment by tvdijen** [comment]
Good catch! Done!
