### ISSUE TITLE
Use best available encryption in pwgen.php

### ISSUE THREAD

**Issue by johnxba** [simplesamlphp/simplesamlphp#1848]
The current version of pwgen.php uses the php default BCRYPT. 

[OWASP recommends](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#introduction) to use ARGON2ID. 

ARGON2ID was not available until php version 7.3.0. The alternative ARGON2I was added to php version 7.2.0. 
Additionally, php will need to be compiled with support for ARGON2.

BCRYPT was added in php 5.5.0.

I have changed pwgen.php to accommodate the best available password algorithm in password_hash(). I've attached it.

Features:
- Order of preference ARGON2ID, ARGON2I, BCRYPT
- Options: m: 64MiB, t=4, p=1 similar to recommendations
- Removes trailing line ending \r\n or \n and leaves space which trim() would remove
- Repeats password entry question if the password is empty

References
https://www.rfc-editor.org/rfc/rfc9106.html#name-recommendations
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#argon2id
https://www.erianna.com/introducing-support-for-argon2id-in-php73/
Issue #996 Rewrite Crypto::passwordHash() to use BCRYPT instead of unsafe algorithms

Attached pwgen.php version:
[pwgen.zip](https://github.com/simplesamlphp/simplesamlphp/files/12393167/pwgen.zip)

**Comment by jaimeperez** [comment]
Hi @johnxba!

Would you mind providing your suggested changes as a pull request?

**Comment by tvdijen** [comment]
Closed in #1849
