### ISSUE TITLE
Dead link in docs on how to report security vulnerabilities

### ISSUE THREAD

**Issue by defnull** [simplesamlphp/simplesamlphp#1850]
The documentation on how to report security vulnerabilities points to https://www.uninett.no/cert, which forwards to https://sikt.no/cert, which shows a page not found error.

See https://simplesamlphp.org/security/ and https://github.com/simplesamlphp/simplesamlphp/security

I have something to report. Should I send the report via [github](https://github.com/simplesamlphp/simplesamlphp/security/advisories/new) instead?

**Comment by tvdijen** [comment]
Github is fine, thank you!

@olavmo-sikt @olavmrk @knumor You guys have a new link for us?

**Comment by thijskh** [comment]
Why not change the docs link to Github? Seems like a fine place to me?

**Comment by defnull** [comment]
Some security folks may not trust github, so an alternative channel is always nice to have. For this particular report, github is fine though.

**Comment by tvdijen** [comment]
I found the proper link and updated the documentation + website accordingly
