### ISSUE TITLE
Invalid Composer dependency name - assets base module install fails

### ISSUE THREAD

**Issue by Veraxus** [simplesamlphp/simplesamlphp#1853]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**
Composer has started throwing errors while installing simplesamlphp...

```
Composer has started outputting the following message while installing SimpleSAMLphp...

In ModuleInstaller.php line 40:
  Unable to install module simplesamlphp/simplesamlphp-assets-base, package name must be on the form "VENDOR/simplesa
  mlphp-module-MODULENAME".
```

It appears that this dependency does not follow Composers naming convention.

**To Reproduce**
1. Add simplesamlphp/simplesamlphp:2.* to your composer.json
2. Run composer install/update
3. Approve plugin simplesamlphp/composer-module-installer

**Expected behavior**
simplesamlphp installs via composer without errors.

**Screenshots or logs**
![image](https://github.com/simplesamlphp/simplesamlphp/assets/587527/5462843d-924b-4d76-bc5c-076943e18f4f)

**Comment by tvdijen** [comment]
Hi @Veraxus ! Could it be that you're upgrading from an older 1.1x install?

**Comment by davereid** [comment]
Looking at the current module code it looks like this should work now that https://github.com/simplesamlphp/composer-module-installer/pull/21 was fixed.

**Comment by abielefeldt** [comment]
Deleting the vendor directory worked for me to get around this issue.

**Comment by davereid** [comment]
I can confirm that you must upgrade `simplesamlphp/composer-module-installer` first before you do any composer updates on `simplesamlphp/simplesamlphp`
