### ISSUE TITLE
Move composer/composer dependency to require-dev

### ISSUE THREAD

**Issue by owenbush** [simplesamlphp/simplesamlphp#1855]
**Is your feature request related to a problem? Please describe.**
We are attempting to update to simplesamlphp 2.x from 1.19.x and are struggling with the composer/composer dependency, because one of our other package dependencies explicitly blocks composer/composer with:

```json
"conflict": {
  "composer/composer": "*"
}
```

The reason this conflict is defined is because there were a number of issues using composer within the DDEV local environment alongside composer/composer inside the vendor directory. We ended up with two versions of composer which were out of sync and it was just a mess.

**Describe the solution you'd like**
Having looked through the simplesamlphp code I was struggling to see why composer/composer would need to be a required dependency, I noticed composer being used in the github actions, but presumably if it was necessary that could be added as a step/task in the github action. 

Is there any way that the dependency on composer/composer could be moved to being a dev dependency, or have I missed where it is used in this package?

**Describe alternatives you've considered**
We are looking into seeing if we can remove the conflict on composer/composer elsewhere, but because we had a lot of trouble with it in the past, it is unlikely that we will want to reintroduce composer/composer into our dependency chain.

**Comment by delaneyceo** [comment]
+1 for moving this to a dev dependency as this is causing issues in my projects as well. It seems like several other projects use this pattern as well and I'm not seeing composer being used at runtime.
