### ISSUE TITLE
sspmod_oauth_OAuthSignatureMethodRSASHA1 misses implementation for fetch_private_cert

### ISSUE THREAD

**Issue by iwanluijks** [simplesamlphp/simplesamlphp#186]
Affects: simplesamlphp-1.13.2

The oauth module contains the class "sspmod_oauth_OAuthSignatureMethodRSASHA1" which extends "OAuthSignatureMethod_RSA_SHA1". The former class doesn't implement the abstract method fetch_private_cert declared in "OAuthSignatureMethod_RSA_SHA1" though.

The class should implement this method or changed to abstract.

**Comment by jaimeperez** [comment]
This problem was probably introduced in subversion revision 2843, 4 years ago, so it's been broken since then. Are you using this module @iwanluijks?

**Comment by olavmrk** [comment]
Since this class has been broken for so long, I have committed a patch that removes this class. If you are using this class, pleas let us know, and we can discuss whether we should reintroduce it..
