### ISSUE TITLE
Cannot use SimpleSAML\Stats as Stats because the name is already in use 

### ISSUE THREAD

**Issue by DEstebanJV** [simplesamlphp/simplesamlphp#1868]
**Describe the bug**
Fatal error: Cannot use SimpleSAML\Stats as Stats because the name is already in use in /code/vendor/simplesamlphp/simplesamlphp/modules/core/src/Controller/Logout.php on line 13

**To Reproduce**
go to path/simplesaml/ 

**Expected behavior**
get started simplesaml

**Additional context**

The problem occurred to me with the update of the logout.php file 3 days ago

**Comment by tvdijen** [comment]
Seems to me your application is also declaring a `Stats` class.. Nothing _really_ changed in the mentioned update last week.
