### ISSUE TITLE
bc3fecbf30

### ISSUE THREAD

**Issue by ehovlsen** [simplesamlphp/simplesamlphp#1869]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.

**Additional context**

**Comment by tvdijen** [comment]
Thanks for your tireless effort on this one @jaimeperez 🤣
