### ISSUE TITLE
Updated from 2.0.6 to 2.1.0

### ISSUE THREAD

**Issue by benmastrangelo** [simplesamlphp/simplesamlphp#1875]
I updated from 2.0.6 to 2.1.0 because of the Symfony version I needed is 6 and not 5.

I had to update because of Laravel 10. I am using SimpleSAMLphp in a subdirectory.

After updating it no longer redirects to the login.

This is where the redirect would happen $this->simpleSamlAuth->requireAuth() but it no longer does.

It used to redirect to authenticate/module.php/core/loginuserpass?AuthState=_95a6b49561ad02dde6ca9d2605b73bd7660ca7f246,

**Comment by tvdijen** [comment]
What kind of session storage are you using? Have you cleared your session store?

**Comment by benmastrangelo** [comment]
I am using phpsession. Is there a way to clear phpsession?

**Comment by tvdijen** [comment]
They are stored as files on disk somewhere, but this may be a dead end anyway...
What Drupal-plugin are you using? I know [simplesamlphp_auth](https://www.drupal.org/project/simplesamlphp_auth/issues/3349278#comment-15257807) has a new version `4.0.0-rc1` that should be compatible with SimpleSAMLphp 2.1

**Comment by tvdijen** [comment]
You solved it?

**Comment by benmastrangelo** [comment]
I solved it by downloading the zip file instead of doing a git clone of master.
