### ISSUE TITLE
Wrong version in header

### ISSUE THREAD

**Issue by wilecoyte78** [simplesamlphp/simplesamlphp#1879]
https://github.com/simplesamlphp/simplesamlphp/blob/a145770f9d3ce64278b0121223ed846def778db7/docs/simplesamlphp-upgrade-notes-2.2.md?plain=1#L1

This says 2.1 when it should read 2.2

**Comment by tvdijen** [comment]
Closed in 60486a02e6c4e0ef13bd29302e3cdff1647efd7a
Thanks @wilecoyte78 !
