### ISSUE TITLE
Nullcheck to prevent exception being thrown when attribute is null in StatisticsWithAttribute

### ISSUE THREAD

**Issue by RhiannonPurnell** [simplesamlphp/simplesamlphp#1880]
I've been having an exception thrown - and am adding a null check to overcome it. Perhaps not the best way to address this, but I'm just making an issue to add it as a Pull Request in case it is helpful to others.

Line 48 of simplesamlphp/simplesamlphp/modules/core/src/Auth/Process/StatisticsWithAttribute.php

`Invalid attribute name given to core:StatisticsWithAttribute filter.`

**Comment by tvdijen** [comment]
I'm not sure I follow.. You're using the `core:StatisticsWithAttribute` filter, but your haven't configured the `attributename`?

**Comment by RhiannonPurnell** [comment]
You're right, apologies - this is in code that has already been refactored. My composer was pinning an old dev version of this module - closing.
