### ISSUE TITLE
Error Installing 2.1RC

### ISSUE THREAD

**Issue by safetypins** [simplesamlphp/simplesamlphp#1881]
I'm working in a local docker development environment, testing an upgrade to Drupal 10. When trying to actually perform the upgrade, I get the following error, which seems to be related to this code:

`Unable to install module simplesamlphp/simplesamlphp-assets-base, package name must be on the form "VENDOR/simplesamlphp-module-MODULENAME".`

I believe this error is being generated by composer v2.

**Comment by tvdijen** [comment]
Try upgrading `simplesamlphp/composer-module-installer` prior to upgrading SimpleSAMLphp.

**Comment by safetypins** [comment]
It doesn't appear that I am able to upgrade that component separately. There's a cascade effect of dependencies that require several things, including simplesamlphp/simplesamlphp to be upgraded to the 2.1 RC at the same time as Drupal 10. Drupal 9.5 (the version I'm currently on) requires `psr/log:^1.1` and the 2.1.0-rc version of this library requires `psr/log:^3.0`.

**Comment by tvdijen** [comment]
Then maybe an in-place upgrade is not the best approach for you.. Hard to tell, since I have zero knowledge of Drupal.

**Comment by aj-dol** [comment]
@safetypins - Delete the vendors folder and try installing again.

**Comment by safetypins** [comment]
Removing vendor folder worked. Thanks!
