### ISSUE TITLE
Composer install does not install simplesamlphp/simplesamlphp-assets-base

### ISSUE THREAD

**Issue by aj-dol** [simplesamlphp/simplesamlphp#1882]
I have installed SimpleSAMLphp 2.1rc1 on a Drupal installation with dependencies managed via composer. 

I have the following in the root composer.json

        "simplesamlphp/simplesamlphp": "*",
        "simplesamlphp/composer-module-installer": "*",
        "simplesamlphp/simplesamlphp-assets-base": "*",

The first composer install command does not install assets/base/* into the public folder. This however gets installed when you run composer install the second time.

I was able to work around this by using a composer post-install-cmd and running "composer install --no-scripts  --no-interaction" there.

Am I missing something or is this something that should be addressed as a bug?

**Comment by tvdijen** [comment]
Try setting the composer file to:

```
"simplesamlphp/simplesamlphp": "^2.1.0-rc1",
```
