### ISSUE TITLE
Upgrade notes for 2.1rc1 from the releases page leads to 404

### ISSUE THREAD

**Issue by aj-dol** [simplesamlphp/simplesamlphp#1883]
The link https://simplesamlphp.org/docs/simplesamlphp-2.1/simplesamlphp-upgrade-notes-2.1 

linked from "upgrade notes" under SimpleSAMLphp 2.1.0-RC1 

on this page

https://github.com/simplesamlphp/simplesamlphp/releases

leads to a 404 page.

**Comment by tvdijen** [comment]
Fixed
