### ISSUE TITLE
IDP-initiated Logout missing Destination in LogoutResponce from 2.0.6 simpleSamlPHP SP

### ISSUE THREAD

**Issue by Glowsome** [simplesamlphp/simplesamlphp#1885]
**Specifics of your environment**
1. Acting as SP
2. SimpleSAMLphp: 2.0.6
3. PHP:  8.1.14
4. Platform: Linux/RockyLinux 9.2
5. Webserver: Apache/httpd

**Describe the bug**
Situation : upgrading from v1.19.18 to v2.0.4 or v2.0.6 (both tried) 
When i trigger an IDP-initiated logout the logout-responce does not contain a Destination attribute, therefore the IDP throws an error.
This behaviour was not seen on the 1.19.x version

**To Reproduce**
1. upgrade working setup from 1.19.18 -> 2.0.4 ( or 2.0.6)
2. perform authentication-test, and then issue (from IDP) logout ( with SAML-tracer in browser active)
3. observe LogoutResponce in SAML-Tracer where Destination is missing (compared to 1.9.18, where it is present)

**Expected behavior**
Destination should be part of the LogoutResponce.

**Comment by tvdijen** [comment]
This was already reported and fixed in https://github.com/simplesamlphp/simplesamlphp/commit/0c6a65a1e16ca1811f858b16afb1103ffaa2095a (new 2.0.7 release pending)

Thanks for reporting!

**Comment by Glowsome** [comment]
Thankyou for the quick reply ! ... keep up the good work
