### ISSUE TITLE
SimpleSAML 2.1.0: version incompatibility for authorize module during composer installation 

### ISSUE THREAD

**Issue by s0rin** [simplesamlphp/simplesamlphp#1886]
**Describe the bug**
Requirements could not be resolved to an installable set of packages

**To Reproduce**
1. SimpleSAML 2.1.0 is present
2. Attempt to install `authorize` will fail due to conflicts with `ldap` module version

```
# composer require simplesamlphp/simplesamlphp-module-authorize

Your requirements could not be resolved to an installable set of packages.

   Problem 1
     - simplesamlphp/simplesamlphp-module-ldap is locked to version v2.2.0 and an update of this package was not requested.
     - simplesamlphp/simplesamlphp-module-ldap v2.2.0 requires ext-ldap * -> it is missing from your system. Install or enable PHP's ldap extension.
```

**Expected behavior**
To be able to install any simplesamlphp module

**Comment by tvdijen** [comment]
You can't install the ldap-module without installing `ext-ldap` first.

**Comment by s0rin** [comment]
ok, but I don't want to install ldap explicitly, but authorize. This command

`# composer require simplesamlphp/simplesamlphp-module-authorize`

has worked in SSP 2.0.6 without `ldap` or `ldap-ext`.

**Comment by tvdijen** [comment]
Then why do you pick the full-release if the only module you need is `authorize`?

**Comment by s0rin** [comment]
Now I got it, I need to install 3 different modules and I have to add the option to each one:

```
# composer require simplesamlphp/simplesamlphp-module-authorize --ignore-platform-req=ext-ldap \
 && composer require simplesamlphp/simplesamlphp-module-memcookie:dev-master --ignore-platform-req=ext-ldap \
 && composer require simplesamlphp/simplesamlphp-module-metarefresh --ignore-platform-req=ext-ldap
```

**Comment by tvdijen** [comment]
authorize + metarefresh are already included in the full-release, so you should only need require memcookie.

**Comment by s0rin** [comment]
this is correct, `require memcookie` is sufficient

`# composer require simplesamlphp/simplesamlphp-module-memcookie --ignore-platform-req=ext-ldap`
