### ISSUE TITLE
Update $config['auth.adminpassword'] related documentation to reflect changes introduced in #1419

### ISSUE THREAD

**Issue by balazswmann** [simplesamlphp/simplesamlphp#1889]
This is not an actual bug, rather just a documentation adjustment. The documentation for [auth.adminpassword](https://github.com/simplesamlphp/simplesamlphp/blob/master/config/config.php.dist#L198) is misleading since #1418 was closed. It says that a hashed password generated by `pwgen.php` can be used as an admin password, but that's not the case anymore.

Furthermore, the documentation of the [authcrypt](https://simplesamlphp.org/docs/contrib_modules/authcrypt/authcrypt.html) module is also affected as I see.

**Comment by thijskh** [comment]
I think the documentation is accurate. You can still use a hashed password in the config.

**Comment by balazswmann** [comment]
Well, for me [pwValid()](https://github.com/simplesamlphp/simplesamlphp/blob/master/src/SimpleSAML/Utils/Crypto.php#L397) throws an exception if I use a hashed password generated by `pwgen.php`. But perhaps I misunderstand something.

**Comment by balazswmann** [comment]
I seems like I seriously overlooked something. Now, I checked it again and it works as expected. Ok, sorry for the noise I think this can be closed.
