### ISSUE TITLE
Error logout after upgrading from simplesamlphp 1.19 to 2.1

### ISSUE THREAD

**Issue by mordonez** [simplesamlphp/simplesamlphp#1894]
After upgrading from simplesamlphp version 1.19 to version 2.1, I encountered an error during the logout process. The issue can be traced to [this specific line](https://github.com/simplesamlphp/simplesamlphp/blob/c0b37f702efb3d59ef88af5e7822a61a22de5982/modules/saml/src/Controller/ServiceProvider.php#L410). In this code, when the identity provider doesn't send a nameId, the variable `saml:logout:Type` is changed to "saml1" for convenience, but it causes a disruption in the logout functionality.

**Specifics of your environment**
1. Using simplesaml to authenticate with an ADFS provider.
2. SimpleSAMLphp version: 2.1
3. PHP version: 8.1
4. Operating System: Unix
5. Web server: Nginx

**Describe the bug**
When I test the Authentication Sources, and I click on the logout button, an exception is raised:

`SimpleSAML\Assert\AssertionFailedException: Expected one of: "saml2". Got: "saml1" in SimpleSAML\Assert\Assert::__callStatic() (line 364 of /code/vendor/simplesamlphp/assert/src/Assert.php). `

However, if I refresh the page and send the logout request again, it successfully logs me out with the message "You have been logged out."

**To Reproduce**
1. Go to /simplesaml/admin
2. Click on 'test'
3. Scroll down to the entity-id 'default-sp'
4. Click the logout button
5. Observe the error.

`SimpleSAML\Assert\AssertionFailedException: Expected one of: "saml2". Got: "saml1" in SimpleSAML\Assert\Assert::__callStatic() (line 364 of /code/vendor/simplesamlphp/assert/src/Assert.php). `

**Expected behavior**
The expected behavior is to return to the test page after clicking the logout button.

**Screenshots or logs**

![imagen](https://github.com/simplesamlphp/simplesamlphp/assets/293837/e6ee79bd-5780-45c7-b63b-a9c018c2dda2)

**Additional context**
I have attached the relevant log for reference:

```
Nov 13 15:20:58 simplesamlphp DEBUG [04a9fdd0a1] Session: Valid session found with 'admin'.
Nov 13 15:20:58 simplesamlphp DEBUG [04a9fdd0a1] Session: Valid session found with 'default-sp'.
Nov 13 15:20:58 simplesamlphp DEBUG [04a9fdd0a1] Session: doLogout('default-sp')
Nov 13 15:20:58 simplesamlphp DEBUG [04a9fdd0a1] Session: 'default-sp' not valid because we are not authenticated.
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] Backtrace:
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 2 /code/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/Error/ExceptionHandler.php:32 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 1 /code/vendor/symfony/error-handler/ErrorHandler.php:537 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 0 [builtin] (N/A)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] Caused by: SimpleSAML\Assert\AssertionFailedException: Expected one of: "saml2". Got: "saml1"
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] Backtrace:
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 6 /code/vendor/simplesamlphp/assert/src/Assert.php:364 (SimpleSAML\Assert\Assert::__callStatic)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 5 /code/vendor/simplesamlphp/simplesamlphp/modules/saml/src/Auth/Source/SP.php:1042 (SimpleSAML\Module\saml\Auth\Source\SP::logout)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 4 /code/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/Auth/Simple.php:217 (SimpleSAML\Auth\Simple::logout)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 3 [builtin] (call_user_func_array)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 2 /code/vendor/simplesamlphp/simplesamlphp/src/SimpleSAML/HTTP/RunnableResponse.php:68 (SimpleSAML\HTTP\RunnableResponse::sendContent)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 1 /code/vendor/symfony/http-foundation/Response.php:423 (Symfony\Component\HttpFoundation\Response::send)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] 0 /code/vendor/simplesamlphp/simplesamlphp/public/module.php:24 (N/A)
Nov 13 15:20:58 simplesamlphp ERROR [04a9fdd0a1] Error report with id 062453d1 generated.
Nov 13 15:20:58 simplesamlphp DEBUG [04a9fdd0a1] Session: Valid session found with 'admin'.
Nov 13 15:20:58 simplesamlphp DEBUG [04a9fdd0a1] Localization: load domain 'messages' at '/code/vendor/simplesamlphp/simplesamlphp/locales'
Nov 13 15:20:58 simplesamlphp DEBUG [04a9fdd0a1] Trying langpath for 'es' as '/code/vendor/simplesamlphp/simplesamlphp/locales/es/LC_MESSAGES/'
Nov 13 15:20:58 simplesamlphp DEBUG [04a9fdd0a1] /simplesaml/module.php/admin/test/default-sp - Localization file 'messages.mo' not found or not readable in '/code/vendor/simplesamlphp/simplesamlphp/locales/es/LC_MESSAGES/', falling back to default
Nov 13 15:21:00 simplesamlphp DEBUG [04a9fdd0a1] Session: Valid session found with 'admin'.
Nov 13 15:21:00 simplesamlphp DEBUG [04a9fdd0a1] Session: 'default-sp' not valid because we are not authenticated.
```

**Comment by tvdijen** [comment]
Thanks for reporting! This is an unintended side-effect of SimpleSAMLphp dropping support for SAML 1.1.
I just fixed it in 36be02af604a511b11197c68fb6634c3d98c8482 and it will be part of the next release.
