### ISSUE TITLE
"file not found" error after upgrade to simplesamlphp 2.1.0

### ISSUE THREAD

**Issue by HollyWangUCLA** [simplesamlphp/simplesamlphp#1897]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?
SP
2. SimpleSAMLphp: What version are you using?
upgraded from 1.19 to 2.1.0
3. PHP: What version are you using?
8.1
4. Platform: unix or Windows?
Local: Mac, remote: pantheon platform
5. Webserver: Apache/Nginx/ISS?
Nginx

**Describe the bug**
Hi, we have been using simplesamlphp (1.0?) in our Drupal 9 project for several years, and it works with our shibboleth idp server smoothly.  We recently upgraded to  simplesamlphp 2.1.0 per Drupal project upgrade, and we encountered problem. 

Our drupal site still forward user login to shibboleth idp, and after successfully verify user login, shibboleth idp forward the traffic to  
https://<mysite>/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp  
and "File not found." error showed up on the page

1.  For URL: "/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp",  verified saml2-acs.php   existes in simplesamlphp (1.0?)
 but not in simplesamlphp 2.1.0. 
 
simplesamlphp (1.0?): /simplesamlphp1.0_archived/modules/saml/www/sp/saml2-acs.php 

simplesamlphp 2.1.0: I can't find this  sp/saml2-acs.php anywhere in 2.1. 
/simplesamlphp/modules/saml/src/SP/LogoutStore.php
/simplesamlphp/public/saml2/ no SP folder

2. I searched our config for "/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp" but doesn't see any place defined this forwarding address. Only saw an example file which has this address in one of the sample metadata file 
<myproject>/simplesamlphp1.0/metadata/saml20-sp-remote.php 
/*
 * Example SimpleSAMLphp SAML 2.0 SP
 */
$metadata['https://saml2sp.example.org'] = [
    'AssertionConsumerService' => 'https://saml2sp.example.org/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp',
    'SingleLogoutService' => 'https://saml2sp.example.org/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp',
];

3. I can't find anywhere in my project defined  'AssertionConsumerService'. I talked with our Shibleth admin, he said "SP ACS URL is provided to us to be configured on the IdP".  

So which URL I should provide for our Shib admin? 

Thank you so much for your help

Holly Wang from UCLA

**Comment by tvdijen** [comment]
The endpoint is defined here: https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-2.1/modules/saml/routing/routes/routes.yml#L39

It should work, but I suspect that Drupal doesn't play nice here..

**Comment by HollyWangUCLA** [comment]
Hi, in Drupal 9, with simplesamlphp 1.19, we can display all SP endpoint and send them to our Shib admin with this url

https://<ourdrupal9site>/simplesaml/module.php/saml/sp/metadata.php/default-sp?output=xhtml

However, this file doesn't exist in simplesamlphp 2.1.0. Do you know which file will perform the same function? 

This document: [SimpleSAMLphp, ](https://simplesamlphp.org/docs/stable/simplesamlphp-sp.html)  mentioned "Exchange metadata with the IdP
In order to complete the connection between your SP and an IdP, you must exchange the metadata of your SP with the IdP. The metadata of your SP can be found in the Federation tab of the web interface. Copy the SAML 2.0 XML Metadata document automatically generated by SimpleSAMLphp and send it to the administrator of the IdP. " 

Where is the "Federation tab of the web interface"?

**Comment by tvdijen** [comment]
> ourdrupal9siteadministratorinterface/simplesaml/module.php/saml/sp/metadata.php/default-sp?output=xhtml
> 
> However, this file doesn't exist in simplesamlphp 2.1.0. Do you know which file will perform the same function?

It's `/module.php/saml/sp/metadata/default-sp?output=xhtml`, so without the `.php`

> Where is the "Federation tab of the web interface"?

It's in the admin-pages. Access them on `/module.php/admin`

**Comment by tvdijen** [comment]
This is an issue tracking, not a support forum.
