### ISSUE TITLE
Inconsistent PO-file generation

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#1902]
**Describe the bug**
When the PO-files are regenerated, the order of the contents is different, leading to 'updated' (not really) files being committed.

**To Reproduce**
See commits like https://github.com/simplesamlphp/simplesamlphp/commit/2218fa6cfb0014115b34dcb549d46de51fae9800

**Expected behavior**
PO-files shouldn't change if the translatable strings haven't changed.

**Additional context**
I've already tried sorting the translations alphabetically, but the randomness seems to occur during the generation/writing of the PO-files.

**Comment by monkeyiq** [comment]
I think https://github.com/simplesamlphp/simplesamlphp/pull/1961 solves this issue?
