### ISSUE TITLE
Official Container For This Project

### ISSUE THREAD

**Issue by Bwvolleyball** [simplesamlphp/simplesamlphp#1903]
**Is your feature request related to a problem? Please describe.**

I wish there was an official Docker container for this project so that it was easy to run this project in Kubernetes or Docker for local development concerns.

**Describe the solution you'd like**

A Docker Container that of this project with all the necessary configurations and PHP setup for AMD & ARM architectures (at a minimum)

**Describe alternatives you've considered**

Other forks of this project that try to provide a container, but there is no support to these random forks. This project should provide it's own official container.

**Additional context**

**Comment by tvdijen** [comment]
Have you tried https://hub.docker.com/r/cirrusid/simplesamlphp ?

**Comment by Bwvolleyball** [comment]
Unfortunately that project won't work for me @tvdijen - I specifically need one that has both AMD and ARM support, since our team has both chipsets for their development laptops.  There was one we were using before, but it has the same problem in that it doesn't support ARM yet and we can't get that multi-arch build to work correctly.

**Comment by tvdijen** [comment]
I wouldn't even know where to start when it comes to Docker and I don't think anyone on our team does. It's really not in our interest to support this kind of stuff, so I think you are better off making your own container.

**Comment by tvdijen** [comment]
@quartje We'd still be interested as a project, even if your solution wouldn't have the multi-arch support the OP requests.

There are currently two known docker-projects to me:
- https://github.com/cirrusidentity/docker-simplesamlphp
- https://github.com/simplesamlphp/docker-simplesamlphp

The first one being the better-maintained version..

**Comment by tvdijen** [comment]
@Bwvolleyball The guys at Cirrus already provided you with a container that had amd64+arm support, [but you never got back to them](https://github.com/cirrusidentity/docker-simplesamlphp/issues/5)..

Please let us know how their solution worked for you. We're closely cooperating with them.

**Comment by Bwvolleyball** [comment]
Hey @tvdijen , that container can work for now, thank you, we can close these issues
