### ISSUE TITLE
page rendering differences between 2.0.x and 2.1.x

### ISSUE THREAD

**Issue by restena-sw** [simplesamlphp/simplesamlphp#1909]
**Specifics of your environment**
1. IdP
2. 2.0.8 vs. 2.1.0
3. PHP 8.1
4. Debian Linux
5. Apache 2

**Describe the bug**
This is a weird one. A page in the simplesamlphp-module-webauthn module renders differently depending on the underlying SSP version, with no other changes.

I deployed with the exact same Ansible script, the same composer module settings, and merely flipped SSP versions between 2.0.x (tried with .6 and .8) and 2.1.x (tried with .0 and .1).

With identical module sources, the rendering is different. It's a "display:grid" div with three columns and four rows; each comprising <div> has unique positions with grid-column and grid-row styles.

On 2.0.x, the page renders correctly (screenshot) . On 2.1.x, the grid becomes a one-column sequence of all the comprising divs.
What makes this so unexplicable is that a download of the HTML sources on both branches, tidied and diff'ed is: empty.

The environment with both versions is live and accessible:

**To Reproduce**

Browse to the 2.0.8 URL: https://demo.goingpasswordless.lu/auth-test/module.php/webauthn/registration
Browse to the 2.1.0 URL: https://demo.goingpasswordless.lu/auth-dev/module.php/webauthn/registration

Observe the rendering difference.

**Expected behavior**
With both version branches, the page should look identical.

**Screenshots or logs**

2.0.8:

![2 0 8](https://github.com/simplesamlphp/simplesamlphp/assets/6346943/7ce61c64-14a7-46a5-92b2-d805426f096f)

2.1.0:

![2 1 0](https://github.com/simplesamlphp/simplesamlphp/assets/6346943/3cdbe4ce-d26a-48d3-a081-cddb4f9ce23d)

**Additional context**
Access to sources to the Ansible script, or the admin password of this demo site, or even shell access can be arranged, if it helps in any way.

**Comment by restena-sw** [comment]
Ah, the page being displayed is simplesamlphp-module-webauthn/templates/supercharged.twig

**Comment by restena-sw** [comment]
(live and screenshot now differ slightly as I found a mismatching form start and end position. Doesn't change the issue at hand though.)

**Comment by tvdijen** [comment]
Could you try downgrading `simplesamlphp/simplesamlphp-assets-base` to `~2.0.0` and see if this makes any difference?

**Comment by restena-sw** [comment]
Redeployed the "dev" portion with this change, composer.lock now has

```
            "name": "simplesamlphp/simplesamlphp-assets-base",
            "version": "v2.0.6",
```

but the rendering is still identically broken.

**Comment by tvdijen** [comment]
OK, at least we can rule out the assets. This means there must have been a change in the base-templates between 2.0.x and 2.1.x that we need to pinpoint

**Comment by restena-sw** [comment]
Turns out the issue was because the module used inline CSS styles, which became forbidden by default in SSP 2.1.x. I have fixed the module in question, and now everything renders as it should. Thanks for the support!

**Comment by tvdijen** [comment]
Upgrade notes were added! Thanks for reporting @restena-sw
