### ISSUE TITLE
download link for 2.1.1 not working

### ISSUE THREAD

**Issue by HollyWangUCLA** [simplesamlphp/simplesamlphp#1910]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

hi, the download link for 2.1.1 is broken
https://simplesamlphp.org/download/ 
[Latest release (2.1.1)](https://github.com/simplesamlphp/simplesamlphp/releases/download/v2.1.1/simplesamlphp-v2.1.1-full.tar.gz)

https://github.com/simplesamlphp/simplesamlphp/releases/download/v2.1.1/simplesamlphp-v2.1.1-full.tar.gz 
"Not Found"

please fix it

Thank you

**Comment by tvdijen** [comment]
Fixed
