### ISSUE TITLE
SimpleSAML 2.1.1: version incompatibility for memcookie module during composer installation

### ISSUE THREAD

**Issue by s0rin** [simplesamlphp/simplesamlphp#1912]
**Describe the bug**
Requirements could not be resolved to an installable set of packages

**To Reproduce**
1. SimpleSAML 2.1.1 is present
2. Attempt to install _memcookie_ will fail (has worked for 2.1.0 see [#1886](https://github.com/simplesamlphp/simplesamlphp/issues/1886))

```
# composer require simplesamlphp/simplesamlphp-module-memcookie --ignore-platform-req=ext-ldap

   Problem 1
     - symfony/options-resolver v7.0.0 requires php >=8.2 -> your php version (8.1.26) does not satisfy that requirement.
     - simplesamlphp/simplesamlphp-module-ldap v2.2.1 requires symfony/ldap ^6.0 -> satisfiable by symfony/ldap[v6.4.0].
     - symfony/ldap v6.4.0 requires symfony/options-resolver ^5.4|^6.0|^7.0 -> satisfiable by symfony/options-resolver[v7.0.0].
```

**Expected behavior**
To be able to install any simplesamlphp module

**Comment by tvdijen** [comment]
I don't understand why it's trying to install an incompatible version of `symfony/options-resolver` because v7 requires PHP 8.2 and I would expect it to install v6.4 of that package.

Could you run `composer prohibits symfony/options-resolver 6.4` and post the output here?

**Comment by tvdijen** [comment]
This is probably the best solution. We intent to stop generating the tarballs in the future because of problems like this.
