### ISSUE TITLE
error related with table: simplesaml_saml_LogoutStore

### ISSUE THREAD

**Issue by HollyWangUCLA** [simplesamlphp/simplesamlphp#1913]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?
SP
2. SimpleSAMLphp: What version are you using?
2.1.1
3. PHP: What version are you using?
8.1
4. Platform: unix or Windows?
Local development: MAC
Remote platform: Pantheon
5. Webserver: Apache/Nginx/ISS?
Local:Apache 
Remote Pantheon platform:Nginx

**Describe the bug**
Hi, after we upgraded our Drupal project to drupal 10, which changed the default MySQL database  transaction isolation level from "REPEATABLE READ" to "READ COMMITTED", this error showed up for my local development site, remote pantheon sandbox site, and remote pantheon development site: 

Transaction isolation level
READ-COMMITTED
For this to work correctly, all tables must have a primary key. The following table(s) do not have a primary key: forum_index, simplesaml_saml_LogoutStore. See the [setting MySQL transaction isolation level](https://www.drupal.org/docs/system-requirements/setting-the-mysql-transaction-isolation-level) page for more information.

I checked this table, it has three primary keys
DESC simplesaml_saml_LogoutStore; 
The primary key columns are:_authSource, _nameId,  _sessionIndex

However,  with our remote Pantheon Test site, which completed the configuration with a Shibboleth IDP server, we don't see this table has such problem. No error associate with this table. 

**Expected behavior**
Hope this error won't displayed for local and remote Dev/sandbox sites. 

**Screenshots or logs**
Pantheon Sandbox site screenshot
![Screenshot 2023-12-04 at 4 16 24 PM](https://github.com/simplesamlphp/simplesamlphp/assets/69690136/dc1f9a85-c487-4652-9303-c2f67f8a84e9)

Pantheon Test site screenshot (connect to a Shib IDP server) Please ignore that Acquia_monitor table. 
![Screenshot 2023-12-04 at 4 18 35 PM](https://github.com/simplesamlphp/simplesamlphp/assets/69690136/cefa8934-0c03-4a3a-9bff-57954c346bf8)

Database information
DESC simplesaml_saml_LogoutStore; 
The primary key columns are:_authSource, _nameId,  _sessionIndex

**Additional context**
For reference: for table forum_index, Drupal already fix this bug and will deploy the fixing in future deployment. Here is the case link:
https://www.drupal.org/project/drupal/issues/3365945 

Thank you so much

**Comment by tvdijen** [comment]
We set a primary key [here](https://github.com/simplesamlphp/simplesamlphp/blob/v2.1.0/modules/saml/src/SP/LogoutStore.php#L122-L129). What version of the schema does your table have?

**Comment by tvdijen** [comment]
Maybe this suggestion will work for you?
https://www.drupal.org/project/simplesamlphp_auth/issues/3349278#comment-15223819

**Comment by HollyWangUCLA** [comment]
Thank you, above comment from Drupal site was really helpful.
