### ISSUE TITLE
SimpleSAMLphp 2.1.0 as SP prefers HTTP Artifact bindings even when required configuration is missing

### ISSUE THREAD

**Issue by juhassi** [simplesamlphp/simplesamlphp#1916]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?
2. SimpleSAMLphp: What version are you using?
3. PHP: What version are you using?
4. Platform: unix or Windows?
5. Webserver: Apache/Nginx/ISS?

SP. SimpleSAMLphp 2.1.0. PHP 8.1. Ubuntu 22.04. Apache.

**Describe the bug**
After upgrading SimpleSAMLphp to 2.1.0 (from 1.xx), we've noticed that users from one federated organization are unable to log on to this particular service. This is caused by their idP supporting HTTP ARTIFACT bindings and SimpleSAMLphp 2.1.0 always preferring ARTIFACTs, even when it's not actually possible to use them due to local server configuration ('store.type' is set to 'phpsession').

**Expected behavior**
If server configuration is unsuitable for using ARTIFACTs, SimpleSAMLphp should not announce / accept them. Or at least there should be a simple way to disable ARTIFACT support via a config.php option.

**Screenshots or logs**

```
Backtrace:
2 src/SimpleSAML/Error/ExceptionHandler.php:32 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
1 vendor/symfony/error-handler/ErrorHandler.php:537 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Exception: Unable to send artifact without a datastore configured.
Backtrace:
8 vendor/simplesamlphp/saml2/src/SAML2/HTTPArtifact.php:46 (SAML2\HTTPArtifact::getRedirectURL)
7 vendor/simplesamlphp/saml2/src/SAML2/HTTPArtifact.php:87 (SAML2\HTTPArtifact::send)
6 modules/saml/src/Auth/Source/SP.php:658 (SimpleSAML\Module\saml\Auth\Source\SP::sendSAML2AuthnRequest)
5 modules/saml/src/Auth/Source/SP.php:642 (SimpleSAML\Module\saml\Auth\Source\SP::startSSO2)
4 modules/saml/src/Auth/Source/SP.php:691 (SimpleSAML\Module\saml\Auth\Source\SP::startSSO)
3 [builtin] (call_user_func_array)
2 src/SimpleSAML/HTTP/RunnableResponse.php:68 (SimpleSAML\HTTP\RunnableResponse::sendContent)
1 vendor/symfony/http-foundation/Response.php:423 (Symfony\Component\HttpFoundation\Response::send)
0 public/module.php:24 (N/A)
```

**Additional context**
Commenting out row 656 (C::BINDING_HTTP_ARTIFACT) from modules/saml/src/Auth/Source/SP.php has temporarily solved this issue for us.

```
            $dst = $idpMetadata->getEndpointPrioritizedByBinding(
                'SingleSignOnService',
                [
                    C::BINDING_HTTP_ARTIFACT,
                    C::BINDING_HTTP_REDIRECT,
                    C::BINDING_HTTP_POST,
                ]
            );
```

**Comment by tvdijen** [comment]
Closed in 1fbfd55a6

As a temporary fix you can remove the Artifact-endpoint from the IdP's metadata
