### ISSUE TITLE
Support for automatic fetching of the SAML metadata file from IdP

### ISSUE THREAD

**Issue by locksleyu** [simplesamlphp/simplesamlphp#192]
I am looking for a way to have simplesamlphp automatically download the latest meta data from a link I provide (in the form "... /saml20/metadata" which returns an XML file) and then store the information from that for use during the authentication process. For example, it would store the cert contained within and use that to verify the auth response.

However, looking through the documentation, it is not clear if this is supported or not. I only reference to using a script to convert the XML if inputted manually.

Is this supported?

**Comment by jaimeperez** [comment]
Hi @locksleyu!

This is an issue tracker, so it's intended to report issues, not for usage questions. The [mailing list](https://simplesamlphp.org/lists) is more appropriate for that.

In any case, yes, you can very easily fetch SAML metadata periodically from an external URL and dump it as SimpleSAMLphp configuration files. Just take a look at the [documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-automated_metadata).

Hope that helps!
