### ISSUE TITLE
Where is the Radius module in the package?

### ISSUE THREAD

**Issue by T3chGuy77** [simplesamlphp/simplesamlphp#1921]
**Is your feature request related to a problem? Please describe.**
Working on configuring Radius. I noticed the config file does not have it listed as stated in documentation. Looking in the modules folder I don't see it there either. Documentation does not state to install it if missing. I see it's listed here as a project but no documentation on how to install it. Do I just download the files and dump it into the modules folder?

**Describe the solution you'd like**
Include the Radius module in the main Simplesamlphp installation or update documentation and the project with the steps to install Radius. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by tvdijen** [comment]
Any module can be installed using composer. Just run `composer require simplesamlphp/simplesamlphp-module-radius` and you're good to go.

**Comment by T3chGuy77** [comment]
Thanks but I discovered I was a little behind on my install. The updated download was a 'full' one with all the modules including Radius. So now I'm playing with a full deck. Also thanks for updating the documentation/README.
