### ISSUE TITLE
nocookie UNHANDLEDEXCEPTION [With fix]

### ISSUE THREAD

**Issue by VM-IPLNet** [simplesamlphp/simplesamlphp#1923]
**Specifics of your environment**
1. Are you acting as IDP
2. SimpleSAMLphp: 2.1.1
3. PHP: 8.2
4. Platform: unix
5. Webserver: Nginx

**Describe the bug**
After upgrading from 1.19 to 2.1.1, started seeing some errors in the logs (see error log below).
When getting the error for nocookie, got a error that was not a valid assertion.
The problem seems to be the order of the path in the core route files the "core-error-nocookie" is placed after the "core-error", making it always match the "core-error"

**Fix Found**
The solution found was to edit the /modules/core/routing/routes/routes.yml file
and place the route "core-error-nocookie" before the "core-error"

**To Reproduce**
Go to <your_base_url>/module.php/core/error/nocookie

**Expected behavior**
should be getting the no_cookie.twig page.

**Screenshots or logs**
```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 /simplesamlphp-2.1.1/src/SimpleSAML/Error/ExceptionHandler.php:32 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
1 /simplesamlphp-2.1.1/vendor/symfony/error-handler/ErrorHandler.php:541 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: SimpleSAML\Assert\AssertionFailedException: Expected one of: "IDENTIFICATION_FAILURE", "AUTHENTICATION_FAILURE", "AUTHORIZATION_FAILURE", "OTHER_ERROR". Got: "nocookie"
Backtrace:
6 /simplesamlphp-2.1.1/vendor/simplesamlphp/assert/src/Assert.php:364 (SimpleSAML\Assert\Assert::__callStatic)
5 /simplesamlphp-2.1.1/modules/core/src/Controller/Exception.php:59 (SimpleSAML\Module\core\Controller\Exception::error)
4 /simplesamlphp-2.1.1/vendor/symfony/http-kernel/HttpKernel.php:163 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 /simplesamlphp-2.1.1/vendor/symfony/http-kernel/HttpKernel.php:75 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 /simplesamlphp-2.1.1/vendor/symfony/http-kernel/Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 /simplesamlphp-2.1.1/src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
0 /simplesamlphp-2.1.1/public/module.php:17 (N/A)
```

**Comment by tvdijen** [comment]
Closed in b7e28ecef. Thanks @VM-IPLNet !
