### ISSUE TITLE
Test local http domain in Chrome browser result in "State Information Lost" errors

### ISSUE THREAD

**Issue by drupal-spider** [simplesamlphp/simplesamlphp#1924]
I use 2.1.1 for a local test. So my test domain is http, since I can't have a https domain locally. 
After installing and configuring, the welcome page is showing as expected. But when I access admin/ path, I came across the "State Information Lost" error in a Chrome browser. It is working fine in other browser, such as Firefox.

I inspect the request header and figure out that the 'SimpleSAMLSessionID' cookie wasn't sent with the request if I use Chrome browser, but Firefox did.

As the [document](https://simplesamlphp.org/docs/stable/simplesamlphp-nostate.html) advised, cookies will not be sent when a POST request is performed between websites, which is typical for the SAML WebSSO flow. The lack of cookies will cause SimpleSAMLphp's session to be lost when receiving an assertion via the HTTP-POST binding.

To resolve this, you can set the session.cookie.samesite attribute in config.php to None . You also need to enable the session.cookie.secure setting.

But the 'session.cookie.secure' can't be enabled for a http domain. So the suggest solution is not working for Chrome browser.

Is there a workaround for that?

Thanks.

**Comment by tvdijen** [comment]
Setting `session.cookie.secure` to `false` should work.
For IDPs you also have to set `session.cookie.sameSite` to `None`.
If your SP's are also on HTTP, you must also set `enable.http_post` to `true`

**Comment by drupal-spider** [comment]
Thanks @tvdijen for replying. 

The error came out right after I installed 2.2.1, I didn't even start config it as IdP or an SP yet. 

According to the installation document (https://simplesamlphp.org/docs/stable/simplesamlphp-install.html), once the installation is done successfully,  you can now also access the admin module via /admin/ URL without any error. At this point, the IdP or SP hasn't been configured yet. Regardless using it as IdP or SP, it shouldn't throw the  "State Information Lost" errors.

Yes, once I set "session.cookie.secure" to false,  then it worked with Firefox browser but Chrome didn't.

**Comment by tvdijen** [comment]
I've proposed a change so that the right value for `session.cookie.secure` is automatically determined by the software. This should fix the `State information lost` error on new and unconfigured installed.
