### ISSUE TITLE
Cached SP Metadata XML file accessible for all

### ISSUE THREAD

**Issue by drupal-spider** [simplesamlphp/simplesamlphp#1926]
**Environment**
1. Are you acting as SP/IdP/proxy?
SP
3. SimpleSAMLphp: What version are you using?
2.1.1
5. PHP: What version are you using?
8.1.18
7. Platform: unix or Windows?
Unix
9. Webserver: Apache/Nginx/ISS?
Nginx
10. Web cache server
Varnish reverse proxy
11. Configuration
'production' => false,
'admin.protectmetadata' => true,

**Describe the bug**
We are using Varnish reverse proxy as the web cache service and set the 'admin.protectmetadata' as true in the config.php file to prevent non-admin user from accessing our SP metadata.
But once an admin user (after logging) access the SP metadata via the url (../module.php/saml/sp/metadata/{sourceId}), that metadata XML file will be cached by the web cache service, in our case is the Varnish, as a public resource and the caching time (max-age) is set to 86400 (1 day) as default. Until that time is over, anyone can access/download the SP metadata XML file from anywhere (any IP) as a public cached file.

**Expected behavior**
Only admin user can access/download the SP metadata XML file when 'admin.protectmetadata'  is set to true.

**Comment by drupal-spider** [comment]
Add following line after https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/src/Controller/ServiceProvider.php#L651C9-L651C34

might fix this problem.

```php
    $response->setCache([
      'no_cache' => true,
      'public' => false,
      'private' => true
    ]);
```
According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#response_directives
If the cache control in the response header of the metadata XML file is set to private and no-cache, all those cache service won't cache this XML file, particularly when user hasn't signed in. 

> You should add the private directive for user-personalized content, especially for responses received after login and for sessions managed via cookies.

**Comment by thijskh** [comment]
Just to understand your requirements better... what goal are you trying to achieve with disabling access to metadata? Will not anyone who can log into the site have the information in the metadata anyway?

**Comment by tvdijen** [comment]
What Thijs is asking is what your use-case is for putting the metadata XML behind a password login. We are considering to remove this config setting because it makes zero sense.

**Comment by drupal-spider** [comment]
It is not about individual use case, it is about that a setting variable is not working as designed. 

Either removing that option or making it works as it is supposed to.  

Relative issue was raise as early as 2015.
https://github.com/simplesamlphp/simplesamlphp/pull/140

**Comment by tvdijen** [comment]
The patch will be part of a next release
