### ISSUE TITLE
Unable to resolve path to XML schemas when SimpleSAMLphp is a composer dependency of another project

### ISSUE THREAD

**Issue by mediabounds** [simplesamlphp/simplesamlphp#1928]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?
SP

2. SimpleSAMLphp: What version are you using?
2.1.1

3. PHP: What version are you using?
8.1.23

4. Platform: unix or Windows?
unix

5. Webserver: Apache/Nginx/ISS?
Unit/Nginx

**Describe the bug**
When I try to validate a known valid XML file using `XML::isValid`, I get a schema validation error:
```
Schema validation failed on XML string: level=1,code=1549,line=0,col=0,msg=failed to load external entity "/app/vendor/simplesamlphp/simplesamlphp/vendor/simplesamlphp/saml2/schemas/saml-schema-metadata-2.0.xsd" level=2,code=1757,line=0,col=0,msg=Failed to locate the main schema resource at '/app/vendor/simplesamlphp/simplesamlphp/vendor/simplesamlphp/saml2/schemas/saml-schema-metadata-2.0.xsd'.
```

The issue seems to be in where SimpleSAMLphp is expecting to find the metadata. `XML::isValid` attempts to find the schema in `vendor/simplesamlphp/saml2/schemas`. This seems to assume that the directory structure is something like this:
* SimpleSAML application
  * vendor
    * simplesamlphp
      *  saml2

However, in my application, my directory structure looks like this:
* vendor
  * simplesamlphp
    * simplesamlphp
      * SimpleSAML application
    * saml2

I assume this is because I am using SimpleSAMLphp as a dependency of another composer project.

**To Reproduce**
```
# Create a composer project
composer init --name test/test

# Install simplesamlphp
composer require simplesamlphp/simplesamlphp

# Configure simplesamlphp
cp vendor/simplesamlphp/simplesamlphp/config/config.php.dist vendor/simplesamlphp/simplesamlphp/config/config.php
```

Create a simple test PHP file:
```
<?php

use SimpleSAML\Configuration;

require 'vendor/autoload.php';

$config = Configuration::getInstance();
echo $config->resolvePath('vendor/simplesamlphp/saml2/schemas');
```

And execute it:
```
php test.php
```

**Expected behavior**
The path would resolve to: `/app/vendor/simplesamlphp/saml2/schemas`

**Actual behavior**
The path resolved to: `/app/vendor/simplesamlphp/simplesamlphp/vendor/simplesamlphp/saml2/schemas`
This path does not exist.

**Additional context**
I am using SimpleSAMLphp with a Drupal application with the https://www.drupal.org/project/simplesamlphp_auth project. SimpleSAMLphp is a dependency of the Drupal module. My project declares the Drupal module as a dependency making SimpleSAMLphp an indirect dependency.

If I set `basedir` in `config.php` (i.e. `'basedir' => '/app'`), it fixes this error...but then SimpleSAMLphp can no longer find any of its modules.

**Comment by tvdijen** [comment]
Thanks @mediabounds ! You think you can test the fix I've created in the attachted PR?

**Comment by mediabounds** [comment]
I used this code to test the PR:
```
(new XML)->isValid('<root></root>', 'saml-schema-metadata-2.0.xsd');
```

And it seems like the vendor directory was still one level higher than expected.

I also backported the changes to the `simplesamlphp-2.1` branch and verified they worked in my application:
https://github.com/simplesamlphp/simplesamlphp/pull/1930

(Not sure what the policy is on backporting fixes to other versions of SimpleSAMLphp.)
