### ISSUE TITLE
[Documentation] : SAML, OpenIDConnect, LDAP Service Provider support status

### ISSUE THREAD

**Issue by nmarie276** [simplesamlphp/simplesamlphp#1963]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?    SP
2. SimpleSAMLphp: What version are you using?    migrating from 1.15.2 to 2.x
3. PHP: What version are you using?    migrating from 7.0 to 8.2
4. Platform: unix or Windows?    Linux
5. Webserver: Apache/Nginx/ISS?    Apache

**Describe the bug**
Our internal application still relying on PHP 7.0, but we're migrating to PHP 8.2. So we're moving PHPSimpleSAML to a newer version. All the informations are stored in MemCache. We're using PHPSimpleSAML as Service Provider and is pluggind to different Identity Providers:
* A Azure AD as SAML IdP.
* A Google Workspace Directory as OpenIDConnect IdP.
* An internal LDAP.

After reading the documentation, I understand that SAML is still working as before, but either OpenIDConnect Service Provider is deprecated then not supported anymore, or needs an internal database to work.

**Expected behavior**
Maintaining SAML and OpenIDConnect Service Provider and limiting the configuration changes while upgrading PHPSimpleSAML

**Additional context**
This ticket is probably another one about this subject, but I was unable to validate the support status of these protocols. If not, I will looking for a replacement library.

Thanks in advance.

**Comment by tvdijen** [comment]
When v1.15 was released no one had ever heard of 'OpenID Connect'.. It's a fairly new protocol that is supported by the `simplesamlphp-module-oidc` module.

We _did_ have support for the old `OpenID` protocol, but no one is using this today, so support for that was removed.

I can understand the confusion between `OpenID` and `OpenID Connect`, but they are truly different protocols. Does this answer your question?

**Comment by nmarie276** [comment]
Thanks for this answer. So I need to study myself how to implement the different module, for example, I will also follow path for LDAP.

Regards.

**Comment by tvdijen** [comment]
There is also [simplesamlphp-module-ldap](https://github.com/simplesamlphp/simplesamlphp-module-ldap) available for you.

Modules can be installed using `composer`.
