### ISSUE TITLE
Issue Initializing Login Page On WebApp hosted in Azure

### ISSUE THREAD

**Issue by DycoreSolutions** [simplesamlphp/simplesamlphp#1965]
I created, a login page per SAML documents to initialize the login process into webapp, but encounter issues. Any help is greatly appreciated. 

Using PHP 8.2
SAML V. 2.1.3

 Here are the results: 

1. Warning: Class SimpleSAML\Session has no unserializer 
2. Fetal error: Uncaught Error: Typed property SimpleSAML\Session::$trackid must not be accessed before initialization
3. Error: Typed property SimpleSAML\Session::$trackid mut not be accessed before initialization

**Comment by tvdijen** [comment]
You still have old sessions in your session store?

**Comment by DycoreSolutions** [comment]
Hi tvdijen, 

Here is the latest error after I cleared session(s):

SimpleSAML\Assert\AssertioNFaieldException: 'saml_id' is not a valid RFC3986, even though I have the config authsource file configured the same as the old version of Saml.

**Comment by tvdijen** [comment]
I don't know where this is coming from.. There is no such thing as `saml_id` withing our codebase.

> [..] even though I have the config authsource file configured the same as the old version
That's a problem.. I suggest you start reading the upgrade notes
