### ISSUE TITLE
simplesamlphp installation with selinux enabled

### ISSUE THREAD

**Issue by Alice-1** [simplesamlphp/simplesamlphp#197]
Hi,

I am installing simplesamlphp on centos 6.6. I am able to install it with selinux disabled but with selinux enabled i am getting the below error in apache logs

[Thu Apr 30 16:09:06 2015] [error] [client 10.164.43.255] PHP Warning:  require_once(/var/simplesamlphp/vendor/autoload.php): failed to open stream: Permission denied in /var/simplesamlphp/lib/_autoload.php on line 13
[Thu Apr 30 16:09:06 2015] [error] [client 10.164.43.255] PHP Fatal error:  require_once(): Failed opening required '/var/simplesamlphp/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/simplesamlphp/lib/_autoload.php on line 13

Any help is appreciated

**Comment by jaimeperez** [comment]
Hi @Alice-1!

This is an issue tracker, and hence is intended for reporting issues with SimpleSAMLphp. I see no sign in your report that this might be an issue in SimpleSAMLphp itself, but a *selinux* configuration error.

I would recommend you to post your question to the [user's mailing list](https://simplesamlphp.org/lists), where other people using *selinux* might be able to help you out.
