### ISSUE TITLE
State::validateStateId() should be backported

### ISSUE THREAD

**Issue by nathanjrobertson** [simplesamlphp/simplesamlphp#1979]
The changeset in `master` which implements SimpleSAML\Auth\State::validateStateId() is in https://github.com/simplesamlphp/simplesamlphp/commit/ce01a59037b9f9f44e8d01ca144f713845c3b035 which was committed in March 2023. I would have expected this changeset to be in the 2.1 branch, or at least in the 2.2 branch.

Has this been committed to master then forgotten to be backported? It seems like a good / sensible change that I was accidentally using in code and got a stacktrace:

```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 src/SimpleSAML/Error/ExceptionHandler.php:35 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
1 /var/www/simplesamlphp_idp/vendor/symfony/error-handler/ErrorHandler.php:531 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: Symfony\Component\ErrorHandler\Error\UndefinedMethodError: Attempted to call an undefined method named "validateStateId" of class "SimpleSAML\Auth\State".
Backtrace:
[...]
```

because it isn't in the 2.1 or 2.2 branches.

If this is deliberate, then that's fine - feel free to close this issue. But it seemed like it was more likely forgotten than deliberate.

**Comment by tvdijen** [comment]
Definitely forgotten! Will backport this to 2.1 and 2.2

**Comment by tvdijen** [comment]
Just done so. Will be in the next relase
