### ISSUE TITLE
SP->authenicate() broken in master branch

### ISSUE THREAD

**Issue by nathanjrobertson** [simplesamlphp/simplesamlphp#1986]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy? **SP**
2. SimpleSAMLphp: What version are you using? **GitHub master**
3. PHP: What version are you using? **8.2**
4. Platform: unix or Windows? **Linux (WSL on Windows in Docker containers)**
5. Webserver: Apache/Nginx/ISS? **Apache with php-fpm**

**Describe the bug**
The return types don't match up through `SimpleSAML\Module\saml\Auth\Source\SP.php`, producing the following stacktrace:

```
Fatal error: Uncaught TypeError: SimpleSAML\Module\saml\Auth\Source\SP::authenticate(): Return value must be of type Symfony\Component\HttpFoundation\Response, null returned in /var/www/simplesamlphp/modules/saml/src/Auth/Source/SP.php:817 Stack trace:
#0 /var/www/simplesamlphp/src/SimpleSAML/Auth/Source.php(201): SimpleSAML\Module\saml\Auth\Source\SP->authenticate(Object(Symfony\Component\HttpFoundation\Request), Array)
#1 /var/www/simplesamlphp/src/SimpleSAML/Auth/Simple.php(175): SimpleSAML\Auth\Source->initLogin('http://localhos...', NULL, Array) 
#2 /var/www/simplesamlphp/src/SimpleSAML/Auth/Simple.php(113): SimpleSAML\Auth\Simple->login(Array)
#3 /usr/local/apache2/htdocs/index.php(6): SimpleSAML\Auth\Simple->requireAuth()
#4 {main} thrown in /var/www/simplesamlphp/modules/saml/src/Auth/Source/SP.php on line 817
```

Following this through:

[`public function authenticate(Request $request, array &$state): Response`](https://github.com/simplesamlphp/simplesamlphp/blob/80cff8c9a9622d246fb17ed608593543f00398d4/modules/saml/src/Auth/Source/SP.php#L769)

calls:

[`public function startSSO(Configuration $config, string $idp, array $state): ?Response`](https://github.com/simplesamlphp/simplesamlphp/blob/80cff8c9a9622d246fb17ed608593543f00398d4/modules/saml/src/Auth/Source/SP.php#L715)

calls:

[`private function startSSO2(Configuration $idpMetadata, array $state): void`](https://github.com/simplesamlphp/simplesamlphp/blob/80cff8c9a9622d246fb17ed608593543f00398d4/modules/saml/src/Auth/Source/SP.php#L462)

So, the end result is that the `startSSO2()` function that can only return null is supposed to be providing the object that the `authenicate()` function must return. Looks like an incomplete, broken check-in.

**Comment by tvdijen** [comment]
The `master`-branch is broken and shouldn't be used. Please use a released version.
