### ISSUE TITLE
The default config.php still uses the core:StatisticsWithAttribute authproc-filter

### ISSUE THREAD

**Issue by pverbaan** [simplesamlphp/simplesamlphp#1999]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy? IdP
2. SimpleSAMLphp: What version are you using? 2.2.0
3. PHP: What version are you using? 8.2.16
4. Platform: unix or Windows? unix
5. Webserver: Apache/Nginx/ISS? Apache + Nginx

**Describe the bug**
When processing an incoming authentication request, an UNHANDLEDEXCEPTION is thrown after the session is logged in.

**To Reproduce**
1. Go to `/simplesaml/module.php/admin/test` on your SP
2. Click on the SAML source for your IdP
3. See the error on your IdP

**Expected behavior**
The SP displays the attributes of the user

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.

```
[Mon Mar 11 13:52:20 2024] simplesamlphp INFO [0322c5e4d3] SAML2.0 - IdP.SSOService: Accessing SAML 2.0 IdP endpoint SSOService
[Mon Mar 11 13:52:20 2024] simplesamlphp INFO [0322c5e4d3] SAML2.0 - IdP.SSOService: incoming authentication request: '<snipped>'
[Mon Mar 11 13:52:20 2024] simplesamlphp DEBUG [0322c5e4d3] Session: 'admin' not valid because we are not authenticated.
<snipped>
[Mon Mar 11 13:52:24 2024] simplesamlphp DEBUG [0322c5e4d3] Session: doLogin("admin")
[Mon Mar 11 13:52:24 2024] simplesamlphp DEBUG [0322c5e4d3] Session: Valid session found with 'admin'.
[Mon Mar 11 13:52:24 2024] simplesamlphp DEBUG [0322c5e4d3] Session: Valid session found with 'admin'.
[Mon Mar 11 13:52:24 2024] simplesamlphp ERROR [0322c5e4d3] SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
[Mon Mar 11 13:52:24 2024] simplesamlphp ERROR [0322c5e4d3] Backtrace:
[Mon Mar 11 13:52:24 2024] simplesamlphp ERROR [0322c5e4d3] 2 /var/www/vhosts/<snipped>/simplesamlphp-2.2.0/src/SimpleSAML/Error/ExceptionHandler.php:32 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
[Mon Mar 11 13:52:24 2024] simplesamlphp ERROR [0322c5e4d3] 1 /var/www/vhosts/<snipped>/simplesamlphp-2.2.0/vendor/symfony/error-handler/ErrorHandler.php:535 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
[Mon Mar 11 13:52:24 2024] simplesamlphp ERROR [0322c5e4d3] 0 [builtin] (N/A)
[Mon Mar 11 13:52:24 2024] simplesamlphp ERROR [0322c5e4d3] Caused by: Exception: Could not resolve 'core:StatisticsWithAttribute': The class 'SimpleSAML\Module\core\Auth\Process\StatisticsWithAttribute' isn't a subclass of '\SimpleSAML\Auth\ProcessingFilter'.
```

**Additional context**
The `core:StatisticsWithAttribute` authproc-filter was removed in this release. However, the default `config.php` still uses this filter in lines 96-100. A workaround is to enable the `statistics` module and replace the filter with `statistics:StatisticsWithAttribute`, but since the filter is no longer available in core, perhaps it is better to disable the filter in the default `config.php` file.

The upgrade notes do mention the removal of this filter, but I wasn't aware this filter is used in the default configuration until I ran into the issue while testing the new release from an SP.

This seems like a low priority issue, and I reported it more as a heads-up for other people that might encounter the same thing.

**Comment by tvdijen** [comment]
Good catch! Will fix after my vacantion

**Comment by nathanjrobertson** [comment]
Yep, this one caught us out, and will likely catch a lot of people upgrading out, as it's triggered by the old default configuration. The best thing that could be done is to add an explicit note in the changelog about it.

**Comment by nathanjrobertson** [comment]
> A PR with a concrete text suggestion would be ideal 😃

[PR 2022](https://github.com/simplesamlphp/simplesamlphp/pull/2002) ready for review.

**Comment by monkeyiq** [comment]
merged
