### ISSUE TITLE
Fix for bin/initMDSPdo.php wasn't ported to v2.2

### ISSUE THREAD

**Issue by cicnavi** [simplesamlphp/simplesamlphp#2000]
Line in branch simplesamlphp-2.1: https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-2.1/bin/initMDSPdo.php#L13

Line in branch simplesamlphp-2.2: https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-2.2/bin/initMDSPdo.php#L11

Would it be possible to keep the latest branch the same as master? And then only cherry pick for older releases...

**Comment by monkeyiq** [comment]
This is the PR against master https://github.com/simplesamlphp/simplesamlphp/pull/1892

**Comment by tvdijen** [comment]
Cherry-picked into the 2.2 and 2.3 release branches.
