### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by MattexD** [simplesamlphp/simplesamlphp#2001]
While logging into the site with credentials it keeps throwing this error:
&&grave; An exception was thrown and was not handled.

If you submit this error, please also report this tracking ID, it will make It is possible for the system administrator to track your session in the logs: 7eea171dfa

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 public/_include.php:28 (SimpleSAML_exception_handler)
1 vendor/symfony/error-handler/ErrorHandler.php:607 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: SimpleSAML\Error\Exception: URL not allowed: https://2023.aulaweb.unige.it/login/index.php
Backtrace:
6 src/SimpleSAML/Utils/HTTP.php:431 (SimpleSAML\Utils\HTTP::checkURLAllowed)
5 modules/saml/src/Controller/ServiceProvider.php:307 (SimpleSAML\Module\saml\Controller\ServiceProvider::assertionConsumerService)
4 vendor/symfony/http-kernel/HttpKernel.php:163 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 vendor/symfony/http-kernel/HttpKernel.php:75 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 vendor/symfony/http-kernel/Kernel.php:202 (Symfony\Component\HttpKernel\Kernel::handle)
1 src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
0 public/module.php:17 (N/A)

**Comment by thijskh** [comment]
This happens when you want to redirect to a URL not listed in `trusted.url.domains` in your `config.php`.

**Comment by MattexD** [comment]
I didn't understand correctly, so there's nothing I can do about it?

**Comment by thijskh** [comment]
You could for example change the setting I mentioned. It’s documented what it does.

**Comment by tvdijen** [comment]
https://github.com/simplesamlphp/simplesamlphp/blob/simplesamlphp-2.2/config/config.php.dist#L213-L235
