### ISSUE TITLE
Support Laravel 11 (with Symfony 7.0)

### ISSUE THREAD

**Issue by pip-delorean** [simplesamlphp/simplesamlphp#2008]
**Is your feature request related to a problem? Please describe.**
Laravel 11 came out this week, with a minimum required Symfony version of 7.0. We will be upgrading our sites in the coming months, and would like to know if support for these frameworks is being considered anytime soon.

**Describe the solution you'd like**
Add support for Laravel 11 by bumping Symfony to 7.0.

**Describe alternatives you've considered**
We may have to consider an alternative solution like `shibd` if we can't fit this in our time-frame.

Thanks for your consideration.

**Comment by tvdijen** [comment]
We will not be supporting Symfony 7 until they release their 7.4 (LTS), which is not until Nov 2025

**Comment by pip-delorean** [comment]
> We will not be supporting Symfony 7 until they release their 7.4 (LTS), which is not until Nov 2025

Thanks for the quick response.

**Comment by m0n1ker** [comment]
@tvdijen is there any chance this could be reconsidered? I understand the desire to stick with LTS versions of Symfony, but Laravel is one of if not the most popular PHP framework. Laravel 10 will stop receiving updates in August 2024, and more importantly security patches in February 2025. Without support for Laravel 11 SimpleSAMLphp will be unusable in any kind of enterprise environment. This is going to force a lot of developers away from this library.

**Comment by tvdijen** [comment]
This time it's Laravel, next time it's Drupal, and then next time something else. It's impossible for us to keep everybody happy.

Also, you don't _have_ to include SimpleSAMLphp in your Laravel-project. It's perfectly possible to install it as a separate project next to your Laravel-project so the different Symfony-versions can work independently.
