### ISSUE TITLE
Allow setting AudienceRestriction / Audience in an AuthnRequest

### ISSUE THREAD

**Issue by brianV** [simplesamlphp/simplesamlphp#201]
The IDP we are connecting to allows us to request multiple audiences for an Assertion by specifying multiple Audience elements within an AudienceRestriction in our AuthnRequest.

It appears that SSP has no way to accommodate this and instead only looks at AudienceRestrictions in the SAML response.

What would it take to support this in SSP?

**Comment by jaimeperez** [comment]
Hi @brianV!

Thanks for the suggestion!

I guess a pull request could be a good way to start :smile:

**Comment by bjorpe** [comment]
I managed to implement this for a similar use-case. Just submitted pull requests for saml2 and simplesamlphp.

**Comment by tvdijen** [comment]
Both were merged, so I assume this is implemented as requested
