### ISSUE TITLE
Perhaps respect the gettext domain for modules

### ISSUE THREAD

**Issue by monkeyiq** [simplesamlphp/simplesamlphp#2013]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy: n/a
2. SimpleSAMLphp: 2.2.1
3. PHP: 8.2.16
4. Platform: Fedora 38
5. Webserver: Apache httpd-2.4.58

**Describe the bug**
The gettext po files contain an `x-domain` setting, for example, the admin module has `X-Domain: admin` in modules/admin/locales/fr/LC_MESSAGES/admin.po. The 2.1 series used to compile these po files to mo binary files and would drop the domain in that process. This would put all translation strings in the top level domain.

It may be useful to retain and respect the domain for modules. This would give each module it's own domain and translation strings could not clash and existing translations would not be overriden by loading new .po files from different domains.

The update would need to retain the domain and update the code that is looking for a translation to look in the correct domain when inside code for a module.

**To Reproduce**
Take a 2.2.1 release and update to revert this PR https://github.com/simplesamlphp/simplesamlphp/pull/2010 so that the domain is retained. Translations will no longer be found.

**Expected behavior**
Perhaps domains should be retained and a module can indicate which domain it is in and translations applicable to that module will be found in that domain.

The commands in https://github.com/simplesamlphp/simplesamlphp/pull/2010#issuecomment-2002165916 can be useful for inspecting the gettext domain in binary files and general manipulation on the command line.

**Comment by monkeyiq** [comment]
I now have a prototype that respects the domains. 

It makes sense to fallback to the messages domain here if the selected domain does not have a translation. For example the admin domain might wish to get a translation from the `locales/en/LC_MESSAGES/messages.po` file. It seems reasonable to allow that to happen so that the admin domain gets native access to it's own explicit translations from `modules/admin/locales/en/LC_MESSAGES/admin.po` first and then can fallback to those offered already in `locales/en/LC_MESSAGES/messages.po` as well.

The domain name spacing would however keep the items in `modules/admin/locales/en/LC_MESSAGES/admin.po` from being interacted with by `modules/examplemodule/locales/en/LC_MESSAGES/examplemodule.po`. These two domains would be explicitly separate. Either of them could access strings from `locales/en/LC_MESSAGES/messages.po` from their own modules though. If they overwrite a translation in their module then it would be taken in preference to the `locales/en/LC_MESSAGES/messages.po` string.

It is a bit complex to have got the code for but it does allow some name spacing of translations between modules.

**Comment by tvdijen** [comment]
This is great stuff @monkeyiq !

**Comment by monkeyiq** [comment]
I have kept the test translation strings in https://github.com/monkeyiq/simplesamlphp/tree/2024/march/i18n-domains2 and made a real PR at https://github.com/simplesamlphp/simplesamlphp/pull/2037 which does the same thing but does not disturb the translation files with extra entries.

Maybe it is not so bad to actually add some permanent test entries in messages.po, core.po and admin.po which are not used by the regular twig files but can allow for easier testing if we want to ensure that such translation strings are correctly found.

**Comment by tvdijen** [comment]
How about we add a twig template + translations to the tests-directory for this purpose?
If we would add them to the production-translations they would be automatically removed by the 'remove unused translations' job.

**Comment by monkeyiq** [comment]
That sounds good. Having a few test translation strings around will help with debugging

**Comment by tvdijen** [comment]
Closed in  #2037
