### ISSUE TITLE
After update to 2.1.5 and going to startpage, only a Welcome screen appears

### ISSUE THREAD

**Issue by freebrowser1** [simplesamlphp/simplesamlphp#2028]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?  NO
3. SimpleSAMLphp: What version are you using? 2.1.5
4. PHP: What version are you using? 8.1
5. Platform: unix or Windows? Windows 
6. Webserver: Apache/Nginx/ISS? Apache 2.4

**Describe the bug**

```
    $tmpdirwin = "E:/tmp";


    'loggingdir' => 'log/',
    'logging.level' => SimpleSAML\Logger::NOTICE,
    'logging.handler' => 'file',
    'cachedir' => "$tmpdirwin/simplesamlphp/cache",    
```

**To Reproduce**
1. Go to 'https://<mydomain>>/simplesaml/'
2. Redirects to 'https://<mydomain>>/simplesaml/module.php/core/welcome'
with the text 

"Welcome
This is the front page of the SimpleSAMLphp authentication software. There's not much to see here.
If you are the administrator of this installation, please refer to the SimpleSAMLphp documentation for how to configure and interact with the software."

No error messages or error logs occur into logging despite setting logging on the highest level and the log folders do exist and are writeable.

**Expected behavior**
An Admin login screen should appear.

**Screenshots or logs**
No logs appear.

**Additional context**

Furthermore I copied the [metadata], [cert] and [config] folders from the old into the new one.
I used the config.php.dist from the new one and added some settings from the old config.php into it.

It is a Windows server running Apache 2.4 and PHP 8.1..

httpd.conf:
```
<Directory E:/docroot/simplesamlphp>
    Require all denied
</Directory>
<Directory E:/docroot/simplesamlphp/public>
    <IfModule !mod_authz_core.c>
    # For Apache 2.2:
    Order allow,deny
    Allow from all
    </IfModule>
    <IfModule mod_authz_core.c>
    # For Apache 2.4:
    Require all granted
    </IfModule>
</Directory>

```
httpd-ssl.conf:
```
<VirtualHost _default_:443>

  SetEnv SIMPLESAMLPHP_CONFIG_DIR "e:/docroot/simplesamlphp/config"
  Alias /simplesaml "e:/docroot/simplesamlphp/public" 
  #Redirect 307 /simplesaml e:/docroot/simplesamlphp/public
  
  <Directory "e:/docroot/simplesamlphp/public">
    AllowOverride None
    AllowOverrideList None
    Order allow,deny
    Allow from all
  </Directory>
.....

```

What am I doing wrong ?

**Comment by thijskh** [comment]
> What am I doing wrong ?

Probably not reading the [upgrade notes](https://simplesamlphp.org/docs/stable/simplesamlphp-upgrade-notes-2.0.html), second bullet under _Functional changes_

Also the page itself tells you what to do as quoted above:
> If you are the administrator of this installation, please refer to the SimpleSAMLphp documentation for how to configure and interact with the software

**Comment by tvdijen** [comment]
To add to this:  You can control the behaviour of the welcome page in `config.php`, so you can make it redirect to `/module.php/admin` if you want to restore the old behaviour.

**Comment by freebrowser1** [comment]
> .

That indeed works and can log in, but I still get an exception in Federation with missing entityID.

> Caused by: SimpleSAML\Assert\AssertionFailedException: authsources['default-sp']: Could not retrieve the required option 'entityID'.

While it is defined in authsources.php as null, should there be a value ?
What should be filled in ? The documentation is unclear about this.

```
 'default-sp' => [
        'saml:SP',

        // The entity ID of this SP.
        // Can be NULL/unset, in which case an entity ID is generated based on the metadata URL.
        'entityID' => null,
```

**Comment by tvdijen** [comment]
As of SimpleSAMLphp 2.0 the entityID can no longer be empty. See last entry in the [upgrade notes](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-upgrade-notes-2.0.md#functional-changes).
It's the unique identifier for your SP, so you have to think of a value that makes sense for you. It has to be formatted as a valid URI (so either a URL or a URN).

**Comment by tvdijen** [comment]
Since this is not an issue but a support question, I'm closing this. Feel free to join us on Slack or our mailing list for support.
