### ISSUE TITLE
Session store in mysql cause too many connections error

### ISSUE THREAD

**Issue by cly19891215** [simplesamlphp/simplesamlphp#203]
Hi All,

I configure the simplesamlphp as a SP and store session information in mysql db.

When a lot of user are authenticating, mysql database feedback too many connections error. The log is below.

May 15 06:12:17 simplesamlphp ERROR [XXXXXXXXXX] Error loading session: SQLSTATE[08004] [1040] Too many connections
May 15 06:12:17 simplesamlphp ERROR [XXXXXXXXXX] Error loading session: SQLSTATE[08004] [1040] Too many connections
May 15 06:12:17 simplesamlphp ERROR [XXXXXXXXXX] SimpleSAML_Error_NoState: NOSTATE
May 15 06:12:17 simplesamlphp ERROR [XXXXXXXXXX] Backtrace:
May 15 06:12:17 simplesamlphp ERROR [XXXXXXXXXX] 2 /opt/o365/simplesaml/lib/SimpleSAML/Auth/State.php:232 (SimpleSAML_Auth_State::loadState)
May 15 06:12:17 simplesamlphp ERROR [XXXXXXXXXX] 1 /opt/o365/simplesaml/modules/saml/www/sp/saml2-acs.php:54 (require)
May 15 06:12:17 simplesamlphp ERROR [XXXXXXXXXX] 0 /opt/o365/simplesaml/www/module.php:135 (N/A)

I found all db query are short connection. 

Is there some way to enable connection pool for db query ?

Thanks.

**Comment by jaimeperez** [comment]
Hi @cly19891215!

I don't think this is an issue in SimpleSAMLphp, but more of a question for the [users mailing list](https://simplesamlphp.org/lists). Maybe you could ask your question there?

Thanks!
