### ISSUE TITLE
2.1+: Translations are off

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#2036]
**Specifics of your environment**
1. SimpleSAMLphp: What version are you using?
At least 2.1+, but earlier versions could be affected

2. PHP: What version are you using?
PHP 8.2

3. Platform: unix or Windows?
Red Hat 8+

4. Webserver: Apache/Nginx/ISS?
Apache

**Describe the bug**
![afbeelding](https://github.com/simplesamlphp/simplesamlphp/assets/841045/c48e4b79-dfec-467e-88f9-b6abf189e0c2)

**To Reproduce**
1. Go to the /admin endpoint
2. Switch languages several times
3. See more than two languages being used

**Expected behavior**
Strings should be translated in the selected language (first), or the fallback language should be used (second). The fallback is always English. How we end up with three languages in one page is (at this point) beyond my comprehension.

**Screenshots or logs**
See screenshot above

**Comment by tvdijen** [comment]
I just noticed on a vanilla SSP that the issue is not there.. I use a custom theme-module and I do override some translations there, but only for EN/NL, while the enabled languages are EN/NL/ES/DE/FR..
I guess this has something to do with the issue I'm seeing..

Some other thing I noticed is that the language selector doesn't work at all on a mobile phone.

What strikes me most ...  The .po files should be mentioning the tag (from /modules/core/tempates/welcome.twig) `This is the front page of the SimpleSAMLphp authentication software. There's not much to see here.` but it is not there.. It's gone.. So the translations-scanner is not doing it's job well.

**Comment by monkeyiq** [comment]
Digging into the last part of the comment it doesn't seem that `This is the front page of the SimpleSAMLphp authentication software. There's not much to see here.` is in the po files from 2.0.7, 2.0.11 or 2.1.0 just to select a few. I guess this is a separate issue as well as if this string should is `foo|trans` or use `{% trans %}` wrappers in the welcome.twig file.

```
grep -R 'front page of the SimpleSAMLphp' .
./simplesamlphp-2.0.7/modules/core/templates/welcome.twig:    <p>{{ 'This is the front page of the SimpleSAMLphp authentication software. There\'s not much to see here.' }}</p>
./simplesamlphp-2.0.11/modules/core/templates/welcome.twig:    <p>{{ 'This is the front page of the SimpleSAMLphp authentication software. There\'s not much to see here.' }}</p>
./simplesamlphp-2.1.0/modules/core/templates/welcome.twig:    <p>{{ 'This is the front page of the SimpleSAMLphp authentication software. There\'s not much to see here.' }}</p>
```

**Comment by monkeyiq** [comment]
Assuming rh8 is similar to fedora, what do you see in journalctl -f as far as things like the following.
```
Apr 04 x Trying langpath for 'fr' as '/opt/sspdev/modules/core/locales/fr/LC_MESSAGES/'
Apr 04 x Localization: load domain 'mymodule' at '/opt/sspdev/modules/mymodule/locales'
Apr 04 x Trying langpath for 'fr' as '/opt/sspdev/modules/mymodule/locales/fr/LC_MESSAGES/'
```

I normally only see en, fr, de, etc here in a single page load. I made a little mymodule theme with some `en` and `fr` and that doesn't seem to confuse things at the head of the `simplesamlphp-2.2` branch.

**Comment by monkeyiq** [comment]
Do you have errant .mo files in your install directory? Can you share your theme for me to try to reproduce the issue here?

**Comment by monkeyiq** [comment]
Which mobile phone is having the problem. I just tried Firefox and the "Internet" browsers on an S20 and they both allowed language selection. Again using `simplesamlphp-2.2` for the test.

**Comment by tvdijen** [comment]
It's not related to mobile phones.. Just make your browser screen small enough to make it switch to mobile layout and try to select a language.. Nothing happens

**Comment by tvdijen** [comment]
I think I understand how I could get three languages in one page..
We are missing a lot of translations in the FR/ES/DE languages. SSP will then try the default language (in my case NL) and if that doesn't work it will fall back to EN.

What strikes me is that there are no entries for the translations in the .po files.. I would expect an English msgid with an empty msgstr for every string that we don't have a translation for.

**Comment by monkeyiq** [comment]
The three languages on one page explanation makes sense. Though I was initially wondering how it was possible.

It might also make sense to have a command to show coverage in the po files. And allow a listing of TODO items to ease updates. This might be especially handy for themes where one might easily miss one or two strings (or more) and those might not be noticed until some slightly strange situation pops up a fallback language (possibly english after NL or maybe falling back to NL from french). 

I might dig into the po file updates now that `|trans` is added on that one string.
