### ISSUE TITLE
Adding Microsoft or Google MFA application support.

### ISSUE THREAD

**Issue by breisig** [simplesamlphp/simplesamlphp#2039]
Simplesamlphp is excellent as running as a SAML iDP. But one requirement is having MFA support especially with an app that can be freely downloaded from the app/play store. [Microsoft or Google Authenticate app]. If we could use the Microsoft/Google Authenticator app with Simplesamlphp as both iDP+mfa, that would be perfect. I have tried searching and there's no talk about this kind of feature. Any information would be grateful. Thanks

**Comment by tvdijen** [comment]
You don't read about it, because it's not possible (at least for Microsoft). Their API doesn't provide a way to trigger MFA. The only way this could work is to configure Azure as an authsource, completely offloading the authentication to Azure.

**Comment by tvdijen** [comment]
If you want to discuss anything like this, please join our Slack channel or mailing list (and respect the 'keep our issue tracker clean' message you disregarded when opening this issue)
