### ISSUE TITLE
assertion encryption: mcrypt iv size doesnt match extracted string length

### ISSUE THREAD

**Issue by caritoz** [simplesamlphp/simplesamlphp#204]
I've been using simpleSAMLphp without assertion encryption, and everything was great! Now I've been asked to accept encrypted assertions, and I'm getting the following warning:

Warning: mcrypt_generic_init(): Iv size incorrect; supplied length: 23, needed: 16 in /path/to/myproject/simplesaml/vendor/simplesamlphp/xmlseclibs/xmlseclibs.php on line 454

Debugging this, I found that xmlseclibs is trying to extract the iv string using a substr($data, 0, 16), and this is returning a string(23). My first guess was a multibyte issue, but mb_substr didn't do the trick either.

I've been debugging this all afternoon, and got nowhere. Any ideas?

Thanks!!

**Comment by relaxnow** [comment]
@caritoz did you ever find the issue? Maybe you could supply a simple testcase where substr($data, 0, 16) gives a string of more than 16 bytes on http://3v4l.org ?
Also maybe this issue needs to be moved to https://gihub.com/robrichards/xmlseclibs ?

**Comment by thijskh** [comment]
I can't reproduce this so it would be nice if @caritoz could share this info. Also, indeed, @caritoz I would recommend to file it under robrichards/xmlseclibs.

**Comment by thijskh** [comment]
No feedback from reporter.
