### ISSUE TITLE
console command does not respect module parameter

### ISSUE THREAD

**Issue by drupal-spider** [simplesamlphp/simplesamlphp#2042]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?
SP
2. SimpleSAMLphp: What version are you using?
2.1.5
3. PHP: What version are you using?
PHP 8.3.3
4. Platform: unix or Windows?
unix
5. Webserver: Apache/Nginx/ISS?
Nginx

**Describe the bug**
When I run the following console command in the terminal to print out routes that defined by the admin module

php bin/console --module=admin debug:router

I got the list of routes defined by the core module which is the default. In other words, the module parameter does not work as expected.

**To Reproduce**
1. Go to root folder the SimpleSAMLphp installed.
2. run command 'php bin/console --module=admin debug:router'
3. All routes defined by the core module are displayed.

**Expected behavior**
The expected result is the routes defined by the admin module.

**Screenshots or logs**
Output by that command

--------------------------------- ---------- -------- ------ ---------------------------------- 
  Name                              Method     Scheme   Host   Path                              
 --------------------------------- ---------- -------- ------ ---------------------------------- 
  remove_trailing_slash             GET        ANY      ANY    /{module}/{url}                   
  add_trailing_slash                GET        ANY      ANY    /{url}                            
  admin-shortcut                    GET        ANY      ANY    /admin                            
  core-welcome                      GET        ANY      ANY    /core/welcome                     
  core-account-disco-clearchoices   GET        ANY      ANY    /core/account/disco/clearchoices  
  core-legacy-login                 GET        ANY      ANY    /core/login/{as}                  
  core-loginuserpass                GET|POST   ANY      ANY    /core/loginuserpass               
  core-loginuserpassorg             GET|POST   ANY      ANY    /core/loginuserpassorg            
  core-error-nocookie               GET        ANY      ANY    /core/error/nocookie              
  core-cardinality                  GET        ANY      ANY    /core/error/cardinality           
  core-error                        GET        ANY      ANY    /core/error/{code}                
  core-warning-shortssointerval     GET        ANY      ANY    /core/warning/short_sso_interval  
  core-post-redirect                GET        ANY      ANY    /core/postredirect                
  core-legacy-welcome               GET        ANY      ANY    /core/frontpage_welcome.php       
  core-legacy-config                GET        ANY      ANY    /core/frontpage_config.php        
  core-legacy-auth                  GET        ANY      ANY    /core/frontpage_auth.php          
  core-legacy-federation            GET        ANY      ANY    /core/frontpage_federation.php    
  core-logout                       GET        ANY      ANY    /core/logout/{as}                 
  core-logout-resume                GET        ANY      ANY    /core/logout-resume               
  core-logout-iframe                GET        ANY      ANY    /core/logout-iframe               
  core-logout-iframe-done           GET        ANY      ANY    /core/logout-iframe-done          
  core-logout-iframe-post           GET        ANY      ANY    /core/logout-iframe-post          
  core-error-report                 GET|POST   ANY      ANY    /core/errorReport                 
 --------------------------------- ---------- -------- ------ ---------------------------------- 

**Additional context**
No matter what module name specified by --module parameter, it always display the result for core module.

**Comment by tvdijen** [comment]
Closed in 0f53e5b93f159bbb8e0a67ad2c59c93eb45274b9

Thanks @drupal-spider
