### ISSUE TITLE
AuthData is an empty array in the database but user still can login.

### ISSUE THREAD

**Issue by drupal-spider** [simplesamlphp/simplesamlphp#2045]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?
SP
2. SimpleSAMLphp: What version are you using?
2.1.5
3. PHP: What version are you using?
8.1.27
4. Platform: unix or Windows?
unix
5. Webserver: Apache/Nginx/ISS?
Nginx

**Describe the bug**
We use SQL (database) to store sessions, in the config.php file we set
`'store.type' => 'sql',`

Somehow, a user has the latest session in the SimpleSAMLphp_kvstore data table, in which  the authData is an empty array,

So at the end of the  _value of that session is 'authData%22%3Ba%3A0%3A%7B%7D%7D', which is after decode,

  ["authData"]=>
  array(0) {
  }

But the user still can login and expire time is updated to next 8 hours after login.

After IDP respond to /module.php/saml/sp/saml2-acs.php/SP_Name

The Simple::isAuthenticated() return true and the getAuthDataArray() function return the authData array with all data.
Such as "saml:AuthnInstant", "saml:sp:SessionIndex", "LogoutState", "Attributes" and "Expire".

But the session data in the database still remain the same, the _value still end with 'authData%22%3Ba%3A0%3A%7B%7D%7D' and _expire is updated to next 8 hours. So the user's session remain valid. 

**To Reproduce**
Don't know how to reproduce this session data

**Expected behavior**
The Simple::isAuthenticated() is supposed to return false according the session data in the database.

**Comment by tvdijen** [comment]
What happens if you move this line: https://github.com/simplesamlphp/simplesamlphp/blob/master/src/SimpleSAML/Session.php#L616
To here: https://github.com/simplesamlphp/simplesamlphp/blob/master/src/SimpleSAML/Session.php#L662 ?

**Comment by drupal-spider** [comment]
I know, It is weird. 

I will try to figure out how to reproduce this session data in a database.

**Comment by drupal-spider** [comment]
After tracing the http traffic, I found an unexpected behaviour. Somehow, our logout page was reloaded itself in a very short period of time, less than 1 second. 
The problem is that the first time of the logout page is loaded, it was redirected to the IDP logout endpoint to start the SSO logout process from their end, but as the logout page was reload before the IDP had a chance to respond to our SP logout endpoint, the page was reloaded in the browser. 
The result is that our SP SimpleSAML logout endpoint wasn't called and the session clean up wasn't triggered but IDP had already logged the user out.

**Comment by drupal-spider** [comment]
I couldn't reproduce it in Firefox browser. So far it only occurred in Chrome browser. It might be a bug with Chrome.

https://issues.chromium.org/issues/41276238

**Comment by tvdijen** [comment]
The comments in that link tell me it's not a bug... It tells us how this could happen in specific situations.

**Comment by drupal-spider** [comment]
Quite frankly, I am still not sure what exactly happened. What I saw is that the outcome are different between browsers (Firefox and Chrome). You are right, it is not necessary a bug of the browser. But the point I tried to make at 

> After tracing the http traffic, I found an unexpected behaviour. Somehow, our logout page reloaded itself in a very short period of time, less than 1 second. The problem is that the first time of the logout page was loaded, it was redirected to the IDP logout endpoint to start the SSO logout process in their end, but as the logout page was reload before the IDP had a chance to redirect to our SP logout endpoint to respond the logout request, the page was reloaded in the browser. The result is that our SP SimpleSAML logout endpoint wasn't called and the session clean up wasn't triggered but IDP had already logged the user out.

is that in a situation where the SSO logout process was interrupted, for example the logout page was reloaded before the IDP had a chance to redirect to the SP's logout endpoint, the SimpleSAML\Module\saml\ControllersingleLogoutService()
https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/src/Controller/ServiceProvider.php#L454
won't be called.
In this situation, there might be corrupted data with session caused.

Since this discussion has been derived to another topic, I am happy with closing this issue if no one came across similar situation. 

Thanks again for looking into it.

**Comment by tvdijen** [comment]
We've done quite a lot of rewriting of the SSO logout-code to make it more robust. Maybe upgrading will help. We haven't seen this error since 2016.
