### ISSUE TITLE
SimpleSAML 1.18.7 - ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by ibarragan2004** [simplesamlphp/simplesamlphp#2049]
Hello all,

After a successful login I got an error, with ERR_EMPTY_RESPONSE. Only by restarting the apache service, this works again.

Can you help me with this?

**Comment by tvdijen** [comment]
We can't help you with this because this is not an error originating from our software.
Besides, SSP 1.18 has been out of support for several years already.

**Comment by ibarragan2004** [comment]
Maybe in a new version this bug has been fixed?

**Comment by tvdijen** [comment]
This appears to have been a bug in PHP. It was mentioned by someone else in 2016:
https://github.com/simplesamlphp/simplesamlphp/issues/293#issuecomment-184909258
