### ISSUE TITLE
bug in AttributAlter.php

### ISSUE THREAD

**Issue by fulvioscorza** [simplesamlphp/simplesamlphp#2081]
Hi,
If AttributeAlter is used in saml20_idp_hosted with regexp as follows:
                79 => array(
                'class' => 'core:AttributeAlter',
                'subject' => 'mail',
                'pattern' => '/@realm.it$/',
                'target' => 'eduPersonScopedAffiliation',
                'replacement' =>  'member@realm.it',
                '%merge',
                ),
eduPersonScopedAffiliation contains something like:   Nickname_member@realm.it . 
Nickname is the string in email address before @
This behaviour happens only with %merge action.
There's mistake in last lines of attributeAlter.php.  
$diff is not forged correctly
I've changed from:

                _if ($this->merge === true) {
                    /** @psalm-suppress InvalidArgument */
                               $attributes[$this->target] = array_merge($diff, $attributes[$this->target] ?? []);
                } else {
                    /** @psalm-suppress InvalidArgument */
                    $attributes[$this->target] = $diff;_

To

                if ($this->merge === true) {
                    /** @psalm-suppress InvalidArgument */
                    **$diff[0]=$this->replacement;**
                    $attributes[$this->target] = array_merge($diff, $attributes[$this->target] ?? []);
                } else {
                    /** @psalm-suppress InvalidArgument */
                    $attributes[$this->target] = $diff;

line     _$diff[0]=$this->replacement_ added
and it works for me.

**Comment by thijskh** [comment]
Can you specify what you expect to achieve? What value do you get and what value do you expect?

**Comment by fulvioscorza** [comment]
If  generic user has mail ***@***.*** and the filter in auth_proc flow is
something like
                79 => array(
                'class' => 'core:AttributeAlter',
                'subject' => 'mail',
                'pattern' => ***@***.***$/',
                'target' => 'eduPersonScopedAffiliation',
                'replacement' =>  ***@***.***',
                '%merge',
                ),
I look for "unipmn.it" in email address. If present, I write/add
***@***.*** value  to eduPersonScopedAffiliation attribute. This is
expected behavior.
But code cut off @unipmn.it from email address and attach  a.b to
***@***.***, so attribute eduPersonScopedAffiliation become
 ***@***.***" instead of ***@***.***"

Below output of a real test:

*Attributes**affiliation*: ***@***.***
***@***.***>***@***.****cn*: Fulvio
Scorza*displayName*: Fulvio Scorza

Expected behaviour is:

*Attributes**affiliation*: ***@***.******@***.****cn*:
Fulvio Scorza*displayName*: Fulvio Scorza

My workaround is adding following line  $diff[0]=$this->replacement;
                if ($this->merge === true) {
                    /** @psalm-suppress InvalidArgument */
*                    $diff[0]=$this->replacement;*
                    $attributes[$this->target] = array_merge($diff,
$attributes[$this->target] ?? []);
                } else {
                    /** @psalm-suppress InvalidArgument */
                    $attributes[$this->target] = $diff;
                }
*replacement *already contains string to merge to array, diff with subject
and pattern no needed IMHO.


Il giorno mar 7 mag 2024 alle ore 09:43 Thijs Kinkhorst <
***@***.***> ha scritto:

**Comment by tvdijen** [comment]
This isn't really helping with all the *** obfuscations..
Please give us an example input, config and expected output

**Comment by tvdijen** [comment]
Maybe it's because you are replying to this issue by email that things get obfuscated... Could you try again by using the Github website?

**Comment by fulvioscorza** [comment]
If  generic user has mail attribute set to a.b@unipmn.it and the filter in auth_proc flow is something like:

                79 => array(
                'class' => 'core:AttributeAlter',
                'subject' => 'mail',
                'pattern' => '/@unipmn.it$/',
                'target' => 'eduPersonScopedAffiliation',
                'replacement' =>  'member@unipmn.it',
                '%merge',
                ),

I searchr unipmn.it realm  in email address. If present, member@unipmn.it value is set in eduPersonScopedAffiliation attribute. This is expected behavior.
But code cut off @unipmn.it from email address and attach  remaining a.b to member@unipmn.it, so attribute eduPersonScopedAffiliation becomes 
 a.bmember@unipmn.it instead of member@unipmn.it

Below output of a real test (staff value already present before merge with member value):

Attributes
affiliation: fulvio.scorzamember@unipmn.it;staff@unipmn.it
cn: Fulvio Scorza
displayName: Fulvio Scorza

Expected behaviour is:

Attributes
affiliation: member@unipmn.it;staff@unipmn.it
cn: Fulvio Scorza
displayName: Fulvio Scorza

My workaround is adding following line  $diff[0]=$this->replacement;

                if ($this->merge === true) {
                    /** @psalm-suppress InvalidArgument */
                    $diff[0]=$this->replacement;
                    $attributes[$this->target] = array_merge($diff, $attributes[$this->target] ?? []);
                } else {
                    /** @psalm-suppress InvalidArgument */
                    $attributes[$this->target] = $diff;
                }
 replacement already contains string to merge to array, diff with subject and pattern no needed IMHO.

**Comment by tvdijen** [comment]
I think this works as designed and you just need to prepend your pattern with `.*` to get the result you want.

**Comment by tvdijen** [comment]
Also check out the other filters that are designed to deal with scopes;
`core:ScopeAttribute` and `core:ScopeFromAttribute`

**Comment by thijskh** [comment]
I agree with @tvdijen's analysis here. It seems you're not using the right option for the goal you want to achieve, hence the filter does not do what you expect. I would follow his advice to look into the specific filters for dealing with scopes first.

**Comment by fulvioscorza** [comment]
I agree with you. I'll follow your advice.
Many thanks.


Il giorno mer 8 mag 2024 alle ore 11:22 Thijs Kinkhorst <
***@***.***> ha scritto:
