### ISSUE TITLE
[PHP 8.3] Deprecated function: Calling get_class() without arguments is deprecated in SimpleSAML\Auth\Source->initLogin()

### ISSUE THREAD

**Issue by Berdir** [simplesamlphp/simplesamlphp#2083]
**Specifics of your environment**
PHP version 8.3

This apparently has been changed on the master branch as part of a huge commit (https://github.com/simplesamlphp/simplesamlphp/commit/a6458f5b21297eac76df0565f9f395575871c1b6) but not backported to 2.2/2.3 branches.

Code search shows another get_class() call in \SimpleSAML\Auth\Simple::logout()

**Expected behavior**
No deprecation warnings.

**Screenshots or logs**

**Additional context**

**Comment by tvdijen** [comment]
Thanks @Berdir ! We have backported this fix now
