### ISSUE TITLE
OAuth: Class naming collisions with PHP's OAuth module (was #299)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#21]
_From [thomas.z...@freenet.de](https://code.google.com/u/108330137531469242352/) on March 23, 2010 10:07:56_

simplesamlphp's OAuth module defines an OAuthException.

Now that has a naming collission with the same class in the PHP OAuth module: http://se.php.net/manual/en/class.oauthexception.php Since PHP's OAuth module is somewhat semi-official and simplesamlphp's
OAuthException doesn't do anything, maybe the name could be changed?

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=299_

**Comment by tvdijen** [comment]
This has been fixed in the external library, which was imported in https://github.com/simplesamlphp/simplesamlphp/commit/50c593020b9c072f016fc71807448263d47414ca and was released in 1.15
