### ISSUE TITLE
Minimal PHP mentionned in documentation is incorrect

### ISSUE THREAD

**Issue by guillomovitch** [simplesamlphp/simplesamlphp#2104]
Unless I'm mistaken, the latest reference to minimal PHP version in [SimpleSAMLphp release notes](https://simplesamlphp.org/docs/stable/simplesamlphp-changelog) is related to version 2.1.0 (2023-10-30):
Raise minimum PHP version to 8.0

It may be true for SimpleSAMLphp itself, but not the dependencies shipped alongside: symfony 6.4 requires PHP >= 8.1, according to its [documentation](https://symfony.com/releases).

Using PHP 8.0 riggers the following issue;
PHP Parse error:  syntax error, unexpected token ")" in /usr/share/simplesamlphp/vendor/symfony/finder/Finder.php on line 647

That's quite minor, but ought to be mentioned I think. Or symfony version downgraded to 6.0 eventually if you prefer compatibility with PHP 8.0 (the one shipped by default on CentOS 9).

**Comment by tvdijen** [comment]
You must be doing something wrong. SimpleSAMLphp 2.1.x has the symfony-dependencies specifically set to `^6.0 <6.4`
If the admin pages say you need PHP 8.1, you are running a newer version.

**Comment by guillomovitch** [comment]
I forgot to mention I'm using the latest version of SimpleSAMLphp, 2.2.2.

**Comment by guillomovitch** [comment]
Indeed, I just missed it. May I suggest turning the "see the upgrade notes" mention in the release notes to a link to those upgrade notes ?

**Comment by tvdijen** [comment]
Done!

**Comment by guillomovitch** [comment]
Thanks!
