### ISSUE TITLE
Hash session ID in the database

### ISSUE THREAD

**Issue by drupal-spider** [simplesamlphp/simplesamlphp#2105]
**Is your feature request related to a problem? Please describe.**
The session ID is a sensitive credential information as important as user's password, which need to be hashed in the database.

**Describe the solution you'd like**
In the SimpleSAML\Store\SQLStore class, check whether the key is a session id, if so then hash the key before get or set from the database.

**Comment by drupal-spider** [comment]
Created a pull request for this new feature.
#2106

**Comment by monkeyiq** [comment]
This has been merged and backported to the 2.3 branch. Thanks @drupal-spider & @tvdijen!
