### ISSUE TITLE
PHP 8.3 error:  Calling get_class() without arguments is deprecated

### ISSUE THREAD

**Issue by BurninLeo** [simplesamlphp/simplesamlphp#2116]
With PHP 8.3 a deprecated warning appears for different instances of `get_class()` without an argument in simpleSAMLphp 2.2.2, especially `/src/SimpleSAML/Auth/Source.php on line 177`

```
'LoginCompletedHandler' => [get_class(), 'loginCompleted'],
'LogoutCallback' => [get_class(), 'logoutCallback'],
```

> Calling get_class() without arguments is deprecated

As there is no class to give to `get_class()`, this shall be changed to

```
'LoginCompletedHandler' => [static::class, 'loginCompleted'],
'LogoutCallback' => [static::class, 'logoutCallback'],
```

**Comment by tvdijen** [comment]
Already been fixed in the 2.3 branch. We don't fix deprecation notices in bugfix-releases.

**Comment by Olifant1990** [comment]
@tvdijen Will there be an update for this deprecated message anytime soon?
We just updated our servers to PHP 8.3 and with a lot of applications using simplesamlphp we are getting a lot of those messages in our logs.

**Comment by tvdijen** [comment]
I think we have enough for a new bugfix release, and/or a new minor.  Grant me a little bit of time to do some testing & getting the changelog up to date.. I should be able to release at least the v2.2.3 this week.

**Comment by tvdijen** [comment]
v2.2.3 is out!

**Comment by Olifant1990** [comment]
Thank you!
Switched to 2.3.0 and no warnings/deprecated stuff yet 👍
