### ISSUE TITLE
It does not support Laravel version 11

### ISSUE THREAD

**Issue by zachary** [simplesamlphp/simplesamlphp#2122]
Larave version 11 used Symfony\Http-foundation:^7.0, however simplesamlphp 2.2.2 only supports Symfony\Http-foundation:^6.4

Please check that, thanks

**Comment by tvdijen** [comment]
We don't have to check anything. We don't support Symfony 7 and will not support it any time soon.

**Comment by matthiasPOE** [comment]
@tvdijen would you be open to receiving a PR to upgrade it?  (Haven't actually checked yet how deeply integrated the symfony modules are)

**Comment by tvdijen** [comment]
Not until Symfony reaches it's 7.4 LTS

**Comment by tvdijen** [comment]
We have a `simplesamlphp-2.5` release-branch now that you can use. There are no tagged releases in that branch yet, but I can tag a beta or rc on request. A final 2.5.0 release will come as soon as Symfony tags 7.4 in november.
