### ISSUE TITLE
checkCookie

### ISSUE THREAD

**Issue by enricocavalli** [simplesamlphp/simplesamlphp#213]
sorry for being vague, but I'm getting different results regarding the deprecated checkCookie (depending on ubuntu version which I use in a test environment)

this was deprecated
SimpleSAML_Utilities::checkCookie(\SimpleSAML\Utils\HTTP::getSelfURL());		
and substited  by this one

			\SimpleSAML\Utils\HTTP::checkCookie(\SimpleSAML\Utils\HTTP::getSelfURL());

But I cannot find the definition of \SimpleSAML\Utils\HTTP::checkCookie

Am I wrong? I can be more precise if required about php versions in use but not immediately

**Comment by jaimeperez** [comment]
Hi @enricocavalli!

The documentation of the deprecated method solves your doubt:

```php
    /**
     * @deprecated This method will be removed in SSP 2.0. Please use
     * SimpleSAML\Utils\HTTP::checkSessionCookie() instead.
     */
```

**Comment by enricocavalli** [comment]
> Il giorno 31/mag/2015, alle ore 11:28, Jaime Pérez Crespo <notifications@github.com> ha scritto:
> 
> Hi @enricocavalli!
> 
> The documentation of the deprecated method solves your doubt:
> 
>     /**
>      * @deprecated This method will be removed in SSP 2.0. Please use
>      * SimpleSAML\Utils\HTTP::checkSessionCookie() instead.
>      */
> —
> Reply to this email directly or view it on GitHub.
> 
Hi, I read it. But I was getting errors thtat 

\SimpleSAML\Utils\HTTP::checkCookie() is not defined

backtrace in the error logs points here

$ grep checkCookie ./modules/saml/lib/IdP/SAML2.php
					\SimpleSAML\Utils\HTTP::checkCookie(\SimpleSAML\Utils\HTTP::getSelfURL());

**Comment by jaimeperez** [comment]
Oh, I see! I thought you were using it yourself.

That looks like a bug. I'll try to take a look into it asap. Thanks for reporting!

**Comment by jaimeperez** [comment]
It looks like something went wrong in the refactoring done in 60ec160. I've just fixed it.

Thanks again!

**Comment by enricocavalli** [comment]
I thought it could be easily corrected but I'm no so expert. 
Thank you for your work !
