### ISSUE TITLE
Undefined array key

### ISSUE THREAD

**Issue by PitWenkin** [simplesamlphp/simplesamlphp#2130]
When connecting to the IDP the errorlog throws:

`PHP Warning:  Undefined array key "index" in /var/www/saml/modules/saml/src/IdP/SAML2.php on line 228`
https://github.com/simplesamlphp/simplesamlphp/blob/d7a7357c842552b5385d67873fa929aab0f83caf/modules/saml/src/IdP/SAML2.php#L246

Dumping `$ep` shows only 'Location' and 'Binding', with:
'Location' consisting of 'AssertionConsumerService' of the given SP
'Binding'  beeing 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'

I'm not sure if this is due to a configuration mishap on my part, or an oversight, or intended?

`saml20-sp-remote.php`  has multiple simple entries in form of: 
```
$metadata['https://domain.tld'] = [
        'AssertionConsumerService' => 'https://domain.tld/endpoint1',
        'SingleLogoutService' => 'https://domain.tld/endpoint2'
];
```

```
Version 2.2.2. 
Linux Ubuntu 22.04.4
PHP 8.1.2
```

**Comment by tvdijen** [comment]
That's a bug ...  What version are you using?

You can easily resolve this as a workaround by specifying the endpoint in the 'array of arrays' style in `saml20-sp-remote.php`. See https://simplesamlphp.org/docs/stable/simplesamlphp-metadata-endpoints.html

**Comment by tvdijen** [comment]
Ok, so I did some digging and apparently the 'single-string' format has been deprecated 9yrs ago, but was never fully removed. We should probably remove it and only support the array-style.

**Comment by PitWenkin** [comment]
> That's a bug!
> 
> You can easily resolve this as a workaround by specifying the endpoint in the 'array of arrays' style in `saml20-sp-remote.php`. See https://simplesamlphp.org/docs/stable/simplesamlphp-metadata-endpoints.html

That's a fix! ;-)

I can confirm that the login/authentification still works after changing the configuration from `single-string`-format to `array of arrays`-format. And there are no more warnings in the error log.

Do you want me to close this issue or keep it open as a reminder to update:

- Documentation
- Default/template setup
-  …

**Comment by tvdijen** [comment]
I'm closing it now. I have a pull request waiting for a review and this issue is linked there as a reference. Thanks for reporting this!
