### ISSUE TITLE
Unable to create the "cache" directory

### ISSUE THREAD

**Issue by briskt** [simplesamlphp/simplesamlphp#2139]
While upgrading to version 2.2.2, I started seeing this exception:

```
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION<br>Backtrace:
      1 www/_include.php:17 (SimpleSAML_exception_handler)
      0 [builtin] (N/A)
      Caused by: RuntimeException: Unable to create the "logs" directory (vendor/simplesamlphp/simplesamlphp//log/).
      Backtrace:
      5 vendor/symfony/http-kernel/Kernel.php:686 (Symfony\Component\HttpKernel\Kernel::buildContainer)
      4 vendor/symfony/http-kernel/Kernel.php:593 (Symfony\Component\HttpKernel\Kernel::initializeContainer)
      3 vendor/symfony/http-kernel/Kernel.php:136 (Symfony\Component\HttpKernel\Kernel::boot)
      2 vendor/symfony/http-kernel/Kernel.php:196 (Symfony\Component\HttpKernel\Kernel::handle)
      1 lib/SimpleSAML/Module.php:198 (SimpleSAML\Module::process)
      0 www/module.php:10 (N/A)
```

Manually creating the `log` directory bypasses this problem, but it makes me wonder why this is necessary. It's also worth noting that nothing appears to be writing to that directory. We are installing SimpleSAMLphp using composer and running inside a Docker container, with the image build executed as root. 

I have since changed config.php to add `'cachedir' => '/var/cache/simplesamlphp'` and remove `'tempdir' => '/tmp/simplesaml'` but that only changes the text of the error message from "Unable to create the "logs" directory" to "Unable to create the "cache" directory". I'm not opposed to making appropriate changes to our Dockerfile, but it is surprising to me that we're doing anything unusual that would cause this issue. This seems to be related to [this symfony documentation](https://symfony.com/doc/current/setup/file_permissions.html) page.

**Specifics of my environment**
1. Are you acting as SP/IdP/proxy? all three, depending on the final configuration
2. SimpleSAMLphp: What version are you using? 2.2.2
3. PHP: What version are you using? PHP 8.1.2-1ubuntu2.17 
4. Platform: unix or Windows? Ubuntu 22.04.4 LTS
5. Webserver: Apache/Nginx/ISS? Apache
6. Base Docker image: [silintl/php8:8.1](https://github.com/silinternational/docker-php8)

**Comment by tvdijen** [comment]
It's just what Symfony demands, whether it's using the directory or not... It's not really something we can fix.

**Comment by briskt** [comment]
I wondered if that was the case. More a matter of documentation, then, right?

**Comment by monkeyiq** [comment]
I was looking into this a bit. As to what documentation we might like to update.

It seems you need to set either `tempdir` or `cachedir` in config.php. If that is set it needs to be writable by the web server user.
https://github.com/simplesamlphp/simplesamlphp/blob/c23e0f3b02590682e4a7e1e9d40ebe4ea30b3ccd/src/SimpleSAML/Kernel.php#L57

**Comment by monkeyiq** [comment]
I have added some information to the docs about this.
