### ISSUE TITLE
Merge "state information lost" guidelines into the documentation

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#214]
We have some [guidelines to help debug *state information lost*](https://code.google.com/p/simplesamlphp/wiki/LostState) errors. They should be merged into the official documentation, and extended with more information (for instance, from the comments in that page).

**Comment by thijskh** [comment]
I started this once, but now pushed forward and finished it. Good to have it part of the standard documentation, since Google Code will be going away.

**Comment by jaimeperez** [comment]
Thanks a lot Thijs!
