### ISSUE TITLE
SimpleSAML\Auth\Simple against and authsource fails with "Authsource must be of type saml:SP"

### ISSUE THREAD

**Issue by monkeyiq** [simplesamlphp/simplesamlphp#2143]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy? **SP(?)**
2. SimpleSAMLphp: What version are you using? **2.2.2** or branch **simplesamlphp-2.2**
3. PHP: What version are you using? **8.2.18**
4. Platform: unix or Windows? **Linux**
5. Webserver: Apache/Nginx/ISS? **Apache**

**Describe the bug**
The "SimpleSAMLphp SP API reference" https://simplesamlphp.org/docs/stable/simplesamlphp-sp-api.html mentions making an `Auth\Simple(string $authSource)` object using the authSource. When this is done and the login URL is used it can result in the exception "Authsource must be of type saml:SP". For example https://github.com/filesender/filesender/issues/1938 and when using something like `example-userpass`, or an auth source setup for `sqlauth:PasswordVerify`.

If this check is disabled https://github.com/simplesamlphp/simplesamlphp/blob/cc8d947b1c74f92c32e8fa67b59f71c69d0b3863/modules/saml/src/Controller/ServiceProvider.php#L111 then the authentication proceeds. 

**Note**
This is likely to be a degenerate use of SSP. You are really just telling it to directly authenticate with a single auth source and not act as a service provider contacting an IdP to perform the auth. The bigger question is if we wish to allow this to happen (perhaps with a config.php variable) in order to allow basic use of SSP directly against auth sources.

**To Reproduce**
1. Call `Auth\Simple(string $authSource)` with an auth source reference. 
2. Call getLoginURL() on that simple object and follow it.
3. Notice an exception when trying to login "Authsource must be of type saml:SP"

The direct use of an authentication source like this was functional in 1.x. If we are not wishing to allow it in the `Simple` API then we should update the documentation... For example, change `string $authSource` to `string $sp` in the Simple constructor.

**Expected behavior**

If the credentials are correct then a login. The expected behaviour occurs when this check block https://github.com/simplesamlphp/simplesamlphp/blob/cc8d947b1c74f92c32e8fa67b59f71c69d0b3863/modules/saml/src/Controller/ServiceProvider.php#L111 is disabled.

**Comment by tvdijen** [comment]
We have discussed this before. It would be an exposure of individual (non-SP) authsources and that imposes a severe security breach. It's like this for a reason.

**Comment by frajer** [comment]
> We have discussed this before. It would be an exposure of individual (non-SP) authsources and that imposes a severe security breach. It's like this for a reason.

Could you give me a definition example of "SP authsource"  that pointing to local "LDAP ID authsource" (example-ldap) which is defined in the same authsources.php file? Or point me to the tutorial that shows how to write simplesaml configuration files to achive that functionality?

**Comment by monkeyiq** [comment]
Thank you for the clarification of why this was removed in 2.x.

I would imagine that the way to move an existing configuration that is attempting to directly use an authsource instead of an SP is... To direct it to use an SP and configure that to use just a single IdP. On the IdP front you would configure that to use an Authentication module which would be perhaps ldap or sqlauth:SQL.

**Comment by frajer** [comment]
I don't know much about saml. I would just like to authorize Filesender users with our Active Directory. With simplesamlphp v1.19.9 I configured LDAP IDp authsource and called it within filesender config. With simplesamlphp v2.2.2 this is not posible anymore. If I understand correctly I should define SP authsource in simplesamlphp? My question is how should I configure simplesamlphp v2.2.2 as Service Provider for our Active Directory? Could you give me a hint, or even better point me to the tutorial how to do it?
