### ISSUE TITLE
Login URL using LDAP module error - SAML instead of LDAP

### ISSUE THREAD

**Issue by quentin-rey** [simplesamlphp/simplesamlphp#2151]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy? **SP**
2. SimpleSAMLphp: What version are you using? **simplesamlphp-2.2.2**
3. PHP: What version are you using? **PHP 8.2.13**
4. Platform: unix or Windows? **Unix - RHEL 8.10**
5. Webserver: Apache/Nginx/ISS? **Apache 2.4.37**

**Describe the bug**

I use SimpleSAMLphp with FileSender.
I use the ldap module (which I installed via `composer`). The saml module is disbaled.
I've created my ldap authsource (`filesender-ldap`) 👇
```php
$config = array(
    'admin' => array(
        'core:AdminPassword',
    ),
    'filesender-ldap' => array(
        'ldap:Ldap',
        'connection_string' => 'ldap://MYLDAPURL',
        'encryption' => 'ssl',
        'version' => 3,
        'ldap.debug' => false,
        'options' => array(
            'referrals' => 0x00,
            'network_timeout' => 3,
        ),
        'connector' => '\SimpleSAML\Module\ldap\Connector\Ldap',
        'attributes' => array(
            'sAMAccountName',
            'mail'
        ),
        'attributes.binary' => array(
            'jpegPhoto',
            'objectGUID',
            'objectSid',
            'mS-DS-ConsistencyGuid'
        ),
        'dnpattern' => 'uid=%username%,ou=people,dc=example,dc=org',
        'search.enable' => true,
        'search.base' => array(
            'MYOU1',
            'MYOU2'
        ),
        'search.scope' => 'sub',
        'search.attributes' => array('sAMAccountName', 'mail'),
        'search.filter' => '(&(objectClass=person)(objectClass=user))',
        'search.username' => 'MYUSER',
        'search.password' => 'MYPWD',
    ),
);
```

When I test my ldap connection via the admin interface, it works.

FileSender uses the SimpleSAMLphp API to create the connection URLs. The problem is that the URL constructed is in the form:
`https://MYURL/simplesaml/module.php/saml/sp/login/filesender-ldap?ReturnTo=...`

As I understand it, SimpleSAMLphp ALWAYS uses ` saml/sp/login/` to build its URL 👇
https://github.com/simplesamlphp/simplesamlphp/blob/c23e0f3b02590682e4a7e1e9d40ebe4ea30b3ccd/src/SimpleSAML/Auth/Simple.php#L319

When I try to connect to FileSender, I get this error:
`SimpleSAML\Error\NotFound: The requested page 'https://MYURL/simplesaml/module.php/saml/sp/login/filesender-ldap?ReturnTo=...' could not be found. The module 'saml' was either not found, or wasn't enabled.`

How, then, do I use ldap? Is this a misunderstanding?

**Expected behavior**
The URL created should use the ldap module.

**Comment by tvdijen** [comment]
What you're doing is basically trying to add ldap-authentication to your website. This has nothing to do with SAML-authentication and you are not an SP as you said in the first question.

**Comment by quentin-rey** [comment]
Hello,

I'm using SimpleSAMLphp as a proxy in this case then?

I would like to set up LDAPS authentication.
Version 1.X of SimpleSAMLphp allowed an LDAP authentication source, so this is no longer the case for security reasons?
However, the documentation presents the ldap module: https://simplesamlphp.org/docs/contrib_modules/ldap/ldap.html

**Comment by tvdijen** [comment]
> I'm using SimpleSAMLphp as a proxy in this case then?

No, you're not using any of the SAML-roles at all.

> However, the documentation presents the ldap module: https://simplesamlphp.org/docs/contrib_modules/ldap/ldap.html

Yes, but it's not meant to be used the way you want to use it.

**Comment by quentin-rey** [comment]
OK, thanks for the info.
So, how is the LDAP module used, and in what context?

I'm going to go for a configuration with KeyCloak as IdP.

**Comment by quentin-rey** [comment]
Thanks for your feedback, using Keycloak works fine.
