### ISSUE TITLE
emailAddress atribute for Tableau

### ISSUE THREAD

**Issue by werxes** [simplesamlphp/simplesamlphp#218]
Tableau requires to send attribute emailAddress for authentication.
I'm using "exampleauth" module, so I'm using uid as real email. How I can guess SimpleSAMLphp does not send this emailAddress attribute to Tableau.

From Tableau I'm receiving: Incoming SAML message has no valid value for EmailAddress attribute

**Comment by jaimeperez** [comment]
Hi,

This is not an issue with SimpleSAMLphp, but an enquiry about usage. Please send your question to the [user's mailing list](https://groups.google.com/forum/#!forum/simplesamlphp).
