### ISSUE TITLE
Integrating SimpleSAMLphp with Apple Business Manager

### ISSUE THREAD

**Issue by tanzhenchao** [simplesamlphp/simplesamlphp#2201]
Dear SimpleSAMLphp Community,

I am trying to integrate SimpleSAMLphp with Apple Business Manager, but I'm having some challenges. I've reviewed the configuration guide on the Apple website (https://support.apple.com/en-hk/guide/apple-business-manager/axmfcab66783/web), but I can't find any information on how to configure SimpleSAMLphp to work with Apple Business Manager.

Specifically, the Apple documentation mentions a "Shared Signals Framework (SSF)" that seems to be required for the integration, but I can't find any information about this in the SimpleSAMLphp documentation or community.

I was hoping the SimpleSAMLphp community might be able to provide some guidance on how to configure SimpleSAMLphp to work with Apple Business Manager.

Any help or advice you can provide would be greatly appreciated. Please let me know if you have any questions or need any additional information from me.

Thank you in advance for your assistance!

Best regards

**Comment by tvdijen** [comment]
This is a bug tracker, not a support forum. Please use the mailing list
