### ISSUE TITLE
Missing link to 2.3 upgrade notes / broken URLs

### ISSUE THREAD

**Issue by jaakristioja** [simplesamlphp/simplesamlphp#2211]
In v2.3.0 the [SimpleSAMLPHP Upgrade Notes index page](https://github.com/simplesamlphp/simplesamlphp/blob/74c4130659d1574f44aa2606090a8d87ffc95ebb/docs/simplesamlphp-upgrade-notes.md) is missing the link to [Upgrade notes for SimpleSAMLphp 2.3](https://github.com/simplesamlphp/simplesamlphp/blob/74c4130659d1574f44aa2606090a8d87ffc95ebb/docs/simplesamlphp-upgrade-notes-2.3.md).

Also the links appear to be broken on GitHub due to the missing `.md` extension in link URLs.

**Comment by tvdijen** [comment]
Link added.

It is true that the links do not work on GitHub.
They are not supposed to work here, but on our website:  https://simplesamlphp.org/docs/stable/simplesamlphp-upgrade-notes.html

I can understand that browsing docs on GitHub can be convenient, but I'm not sure we can make things work for both GitHub and our website..  If you have any smart ideas, your contributions are much appreciated!

**Comment by jaakristioja** [comment]
I don't know enough about how the docs end up on the website. I suppose you are using some static code generation and perhaps it can be fixed or post-processed somehow?

**Comment by tvdijen** [comment]
All the magic is done here: https://github.com/simplesamlphp/docs
It's really not my expertise to be honest.
