### ISSUE TITLE
Incorrect language.available values in config/config.php.dist

### ISSUE THREAD

**Issue by jaakristioja** [simplesamlphp/simplesamlphp#2214]
**Specifics of your environment**
SimpleSAMLphp 2.3.0

**Describe the bug**
In `config/config.php.dist`:

https://github.com/simplesamlphp/simplesamlphp/blob/74c4130659d1574f44aa2606090a8d87ffc95ebb/config/config.php.dist#L819-L826

Note that the array contains strings like `pt-br` which are longer than the 2 characters as directed in the documentation:

https://github.com/simplesamlphp/simplesamlphp/blob/74c4130659d1574f44aa2606090a8d87ffc95ebb/docs/simplesamlphp-maintenance.md#L281-L294

**To Reproduce**
1. `cp config/config.php{.dist,}`

**Expected behavior**
`config.php.dist` fixed not to contain such `language.available` values. Alternatively, adding support for such values.

**Screenshots or logs**

Errors in the logs.

```
ERROR [8be668a6db] Language "pt-br" not installed. Check config.
ERROR [8be668a6db] Language "zh-tw" not installed. Check config.
ERROR [8be668a6db] Language "pt-br" not installed. Check config.
ERROR [8be668a6db] Language "zh-tw" not installed. Check config.
```

I'm not entirely sure, but these errors in the logs seem to be a regression in comparison with SimpleSAMLphp version 2.2.2.

**Comment by tvdijen** [comment]
Good catch!  We used to deal with languages ourselves and at some point added some dialects to the list. In v2.3 we migrated our custom code to Symfony languages and they don't recognize these four dialects.. I'll try and fix this asap.

**Comment by tvdijen** [comment]
I think I may have made a mistake by using the `Languages`-class from Symfony instead of the `Locale`-class. Should be an easy fix.

**Comment by monkeyiq** [comment]
Looking at the Language/Locale class and `Languages::getNames()` vs `Locales::getNames()` this makes sense. The value Portuguese is in the former but   ["pt_BR"]=>"Portuguese (Brazil)" is only in the later.
