### ISSUE TITLE
What is the recommended way to handle config files and composer usage of simplesamlphp?

### ISSUE THREAD

**Issue by dialogik** [simplesamlphp/simplesamlphp#222]
I have included simplesamlphp via composer. Now I've modified

* `vendor/simplesamlphp/config/config.php`,
* `vendor/simplesamlphp/config/authsources.php` and
* `vendor/simplesamlphp/metadata/saml20-idp-remote.php`

to my needs. My problem is that I want to avoid editing any file in `vendor/` folder as I've learned this to be a good practice (so that e.g. updates don't interfere with my modifications).

Another use case of not changing files in the `vendor/` folder is that I might want to publish my own code as a repository without having to include the `vendor/` folder into my repository.

What is your recommendation to both, handle necessary modifications in order to get this repository running for own purposes and keeping the vendor files unchanged? Couldn't this repository be improved by renaming files above (and others in the repository) as `*-sample.php` and advice users to place productivity config files in a folder next to `vendor/`?

**Comment by thijskh** [comment]
Would the approach in #221 work for you?

**Comment by dialogik** [comment]
I'm not calling anything via CLI, I'm simply running simplesamlphp as a regular script on my Apache2 by including following lines into my own script [as recommended in the documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-sp#section_6):

    require_once('../../lib/_autoload.php');
    $as = new SimpleSAML_Auth_Simple('default-sp');
    $as->requireAuth();

So passing the `SIMPLESAMLPHP_CONFIG_DIR` as parameter is not applicable in my case (and probably neither is for others, too). Any other recommendation?

**Comment by dialogik** [comment]
Any idea how to solve this problem?

**Comment by thijskh** [comment]
Why would it be a problem to set an environment variable in your script? I think with the solution in that PR you could also call setConfigDir before you call another function, no?

**Comment by dialogik** [comment]
As written, I'm not calling anything via CLI, and #221 offers a way where

> "the environment variable can be passed via cli"

but I'll try to call `setConfigDir()` instead, this might work. Are there methods for setting the `cert/` and `metadata/` directories as well?

**Comment by thijskh** [comment]
The environment variable can be passed via CLI but of course also via other ways.

Note that you do need to apply the change in that PR first, just to be clear.

I don't think you can set those other dirs via a method, however, you can specify their locations in the config.php you refer to.

**Comment by dialogik** [comment]
Uh year, I see. Thank you for pointing me into the right direction...

Will the PR somewhen be applied to the repo?

**Comment by thijskh** [comment]
You confirming that it works for you would certainly help

**Comment by dialogik** [comment]
How do I use `SimpleSAML_Configuration::setConfigDir()` (also asking @tldev)? I tried like this

    SimpleSAML_Configuration::setConfigDir('my-config');
    $auth = new SimpleSAML_Auth_Simple('my-auth');

but get this error

> You have not yet created the simpleSAMLphp configuration files.

while `$configdir` in `www/_include.php` is pointing to the `config/` in `/vendor/simplesamlphp/simplesamlphp/`, but should be `/config/`.

**Comment by dialogik** [comment]
I also tried using `putenv()`

    putenv('SIMPLESAMLPHP_CONFIG_DIR=my-config');
    $auth = new SimpleSAML_Auth_Simple('my-auth');

**Comment by dialogik** [comment]
Let's continue in #221.
