### ISSUE TITLE
Fix deprecation of Twig spaceless-filter

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#2228]
**Describe the issue**
Twig has deprecated the `spaceless` filter, which is used in three places:

templates/base.twig
templates/_table.twig
modules/admin/templates/metadata_converter.twig

The first two are not problematic to remove, but the last one exists because of a bug in clipboard.js.
We need an alternative for spaceless, or figure out the bug in clipboard.js.

**Comment by monkeyiq** [comment]
This has been fixed with PR 2229 linked above
