### ISSUE TITLE
Too few arguments to function SimpleSAML\SAML2\XML\md\EntityDescriptor::__construct()

### ISSUE THREAD

**Issue by rohittb** [simplesamlphp/simplesamlphp#2236]
**Specifics of your environment**
1. Acting as an idp/sp
2. SimpleSAMLphp: 2.3.0
3. PHP: 8.1
4. Platform: mac
5. Webserver: Apache

**Describe the bug**
SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Backtrace:
2 src/SimpleSAML/Error/ExceptionHandler.php:35 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
1 vendor/symfony/error-handler/ErrorHandler.php:538 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
0 [builtin] (N/A)
Caused by: ArgumentCountError: Too few arguments to function SimpleSAML\SAML2\XML\md\EntityDescriptor::__construct(), 0 passed in /Users/admin/Developer/samlPhp/src/SimpleSAML/Metadata/SAMLBuilder.php on line 69 and at least 1 expected
Backtrace:
8 vendor/simplesamlphp/saml2/src/SAML2/XML/md/EntityDescriptor.php:53 (SimpleSAML\SAML2\XML\md\EntityDescriptor::__construct)
7 src/SimpleSAML/Metadata/SAMLBuilder.php:69 (SimpleSAML\Metadata\SAMLBuilder::__construct)
6 modules/admin/src/Controller/Federation.php:367 (SimpleSAML\Module\admin\Controller\Federation::getHostedSP)
5 modules/admin/src/Controller/Federation.php:128 (SimpleSAML\Module\admin\Controller\Federation::main)
4 vendor/symfony/http-kernel/HttpKernel.php:181 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
3 vendor/symfony/http-kernel/HttpKernel.php:76 (Symfony\Component\HttpKernel\HttpKernel::handle)
2 vendor/symfony/http-kernel/Kernel.php:197 (Symfony\Component\HttpKernel\Kernel::handle)
1 src/SimpleSAML/Module.php:228 (SimpleSAML\Module::process)
0 public/module.php:17 (N/A)

**To Reproduce**
1. Go to 'admin' and click on fedration tab

**Expected behavior**
need to see attributes
**Scre<img width="1440" alt="Screenshot 2024-09-06 at 4 36 29 PM" src="https://github.com/user-attachments/assets/428736b7-c883-40e5-ae98-3d71a76096eb">

**Additional context**

i am attaching my files too so if any issue there 
 idp-hosted.php
 
 
$metadata['__DYNAMIC:1__'] = array(
    'host' => '__DEFAULT__',
    'privatekey' => 'idp.pem',
    'certificate' => 'idp.crt',
    'auth' => 'example-userpass',
);

sp-remote.php

$metadata['http://sp.local/'] = [
    'AssertionConsumerService' => 'https://sp.local/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp',
    'SingleLogoutService' => 'https://sp.local/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp',
    'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
    'certificate' => 'sp.crt',
];

idp-remote.php

$metadata['http://simplesaml.local/saml-idp'] = [
    'host' => '__DEFAULT__',
    'privatekey' => 'ipd.pem',
    'certificate' => 'idp.crt',
    'auth' => 'example-userpass',
   
];

**Comment by tvdijen** [comment]
You are missing the `entityId` key in your hosted metadata files

**Comment by rohittb** [comment]
can you mention which file

**Comment by tvdijen** [comment]
Both `saml20-idp-hosted.php` and `authsources.php`.
The `DYNAMIC:1` doesn't work anymore since 2.0 as mentioned in the upgrade notes.

**Comment by tvdijen** [comment]
Also, I think your not running v2.3.0, because `modules/admin/src/Controller/Federation.php:367` that line-number doesn't match.
