### ISSUE TITLE
Icons in admin panel no longer displayed correctly

### ISSUE THREAD

**Issue by NoseSnatcher** [simplesamlphp/simplesamlphp#2237]
**Specifics of your environment**
1. Are you acting as SP/IdP/proxy? IdP
2. SimpleSAMLphp: What version are you using? 2.3.1
3. PHP: What version are you using? 8.2.23
4. Platform: unix or Windows? Unix
5. Webserver: Apache/Nginx/ISS? Apache
6. SimpleSAMLphp basedir? /simplesaml/

**Describe the bug**
The configuration panel of the admin interface used to show check mark symbols for enabled modules and a ban-symbols for disabled ones. In version 2.3.1 the check marks and bans are replaced by Unicode placeholders.

**To Reproduce**
1. Go to the admin panel of simpleSAMLphp
2. Open the configuration panel

**Expected behavior**
Check marks and ban-symbols should be displayed for enabled/disabled modules.

**Screenshots or logs**
![Screenshot_20240906_150748](https://github.com/user-attachments/assets/43d780ae-d17e-4a8b-878c-3158381f76c8)

**Additional context**
The issue seems to be caused by the admin page not being able to load the Font Awesome font. The browsers developer console shows multiple error messages indicating that the fonts `https://my.idps.address.com/assets/base/fonts/fa-solid-900.ttf` and `https://my.idps.address.com/assets/base/fonts/fa-solid-900.woff2` could not be found. 
The requested assets can be found on the server at for example `https://my.idps.address.com/simplesaml/assets/base/fonts/fa-solid-900.ttf`

Doing a bit of digging, I think the issue was introduced in the SimpleSAMLphp asset repository in [this commit](https://github.com/simplesamlphp/simplesamlphp-assets-base/commit/81ca0a104865216cf3157831a92f8c96a98f1785)

**Comment by tvdijen** [comment]
Confirmed. Will fix ASAP

**Comment by tvdijen** [comment]
Fixed in 58229bb198a5d4110393b2280da7de1e95f1e919 . Release will follow soon
