### ISSUE TITLE
Inbox flooded with attempted code injection attacks from error reporting page

### ISSUE THREAD

**Issue by aaronbauman** [simplesamlphp/simplesamlphp#2245]
I haven't found a way to turn off the error reporting pages, but that's ultimately what i'd like to do.

Basically, I'd like to make it as hard as possible for anyone to figure that i'm using simplesamlphp, which means i definnitely don't want to show them a page like the "Bad request received" page, and definitely don't want a contact form available to so spambots can flood my inbox.

Besides just setting an invalid email address, is this possible?

**Comment by tvdijen** [comment]
Sure, you can set `'errorreporting' => true` in config.php. Please don't use this issue-tracker to ask support-questions
