### ISSUE TITLE
SSO login not working for the first time, after a specific period for only some of the users

### ISSUE THREAD

**Issue by swapnil91** [simplesamlphp/simplesamlphp#2252]
Instead of getting the login page with /user?ReturnTo= and then the needed query parameters, the url gets redirected to-> /sso/saml2/idp/

It happens occasionally, but many users have reported it.

**Comment by tvdijen** [comment]
Where is this `/user?ReturnTo=` coming from? It's not an endpoint of SimpleSAMLphp

**Comment by swapnil91** [comment]
Its written in library/simplesamlphp/modules/drupalauth/lib/Auth/Source/External.php

`/**
     * Log in using an external authentication helper.
     *
     * @param array &$state  Information about the current authentication.
     */
    public function authenticate(&$state)
    {
        assert(is_array($state));

        // Get user. If at this point a cookie is still present (which once was set
        // by the drupal module), this may be from an older login attempt to another
        // site that was terminated halfway. So if it's invalid, delete the cookie
        // and continue to Drupal site for authentication (rather than throwing an
        // exception, which would likely make SimpleSAMLphp redirect back to the
        // SP with the exception message at this point, meaning any login attempts
        // would fail until the cookie was deleted manually).
        $attributes = $this->getUser(false);
        if ($attributes !== null) {
            /*
             * The user is already authenticated.
             *
             * Add the users attributes to the $state-array, and return control
             * to the authentication process.
             */
            $state['Attributes'] = $attributes;
            return;
        }

        /*
         * The user isn't authenticated. We therefore need to
         * send the user to the login page.
         */

        /*
         * First we add the identifier of this authentication source
         * to the state array, so that we know where to resume.
         */
        $state['drupalauth:AuthID'] = $this->authId;


        /*
         * We need to save the $state-array, so that we can resume the
         * login process after authentication.
         *
         * Note the second parameter to the saveState-function. This is a
         * unique identifier for where the state was saved, and must be used
         * again when we retrieve the state.
         *
         * The reason for it is to prevent
         * attacks where the user takes a $state-array saved in one location
         * and restores it in another location, and thus bypasses steps in
         * the authentication process.
         */
        $stateId = SimpleSAML_Auth_State::saveState($state, 'drupalauth:External');

        /*
         * Now we generate an URL the user should return to after authentication.
         * We assume that whatever authentication page we send the user to has an
         * option to return the user to a specific page afterwards.
         */
        $returnTo = SimpleSAML_Module::getModuleURL('drupalauth/resume.php', array(
            'State' => $stateId,
        ));

        /*
         * Get the URL of the authentication page.
         *
         * Here we use the getModuleURL function again, since the authentication page
         * is also part of this module, but in a real example, this would likely be
         * the absolute URL of the login page for the site.
         */
        $authPage = $this->drupal_login_url . '?ReturnTo=' . $returnTo;

        /*
         * The redirect to the authentication page.
         *
         * Note the 'ReturnTo' parameter. This must most likely be replaced with
         * the real name of the parameter for the login page.
         */
        SimpleSAML_Utilities::redirect($authPage, array(
            'ReturnTo' => $returnTo,
        ));

        /*
         * The redirect function never returns, so we never get this far.
         */
        assert(FALSE);
    }`
