### ISSUE TITLE
Converted metadata copy button copies the title instead of converted content

### ISSUE THREAD

**Issue by ethiel4** [simplesamlphp/simplesamlphp#2253]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Specifics of your environment**
1. Are you acting as SP/IdP/proxy? IdP
2. SimpleSAMLphp: What version are you using? 2.3.2
3. PHP: What version are you using? 8.3.10
4. Platform: unix or Windows? unix
5. Webserver: Apache/Nginx/ISS? Apache

**Describe the bug**
Copy button for converted metadata under XML to SimpleSAMLphp feature copies the title of element rather than the converted php metadata. 

**To Reproduce**
1. Log in to your simplesamlphp admin console
2. Click on Federation tab, then click 'XML to SimpleSAMLphp metadata converter'
3. Parse metadata 
4. Click copy icon in the upper right hand of the Converted metadata result, inline with the title 'saml20-sp-remote'
5. Error: the content copied to the clipboard is the 'saml20-sp-remote' title, not the converted metadata

**Expected behavior**
Clicking copy under Converted metadata copies the converted result rather than the title.

**Screenshots or logs**
The target for the copy button is #metadata1, and the div for the h3 title and the converted metadata div both have id="metadata1" applied for the 2.3.2 update. 2.3.1 and 2.3.0 have the expected IDs and functioned as expected in my testing.
![ssp_2_3_2_copyError](https://github.com/user-attachments/assets/a72a4367-943a-4b14-8434-78c82f140fac)

**Additional context**

**Comment by tvdijen** [comment]
What browser is this? I just get the parsed metadata..
We should fix the duplicate ID though

**Comment by tvdijen** [comment]
Closed in 64d828932
