### ISSUE TITLE
Error Authenticating via OAthens

### ISSUE THREAD

**Issue by bridget459** [simplesamlphp/simplesamlphp#2259]
# **Help us to keep this issue-tracker clean!  For questions or support, please refer to our [mailing lists](https://simplesamlphp.org/lists)**

**Specifics of your environment**
1. Are you acting as SP/IdP/proxy? Yes
2. SimpleSAMLphp: What version are you using? 2007-2019 [UNINETT AS](http://uninett.no/)
3. PHP: What version are you using?
4. Platform: unix or Windows?
5. Webserver: Apache/Nginx/ISS?

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or logs**
If applicable, add screenshots and/or log files to help explain your problem.
![image](https://github.com/user-attachments/assets/a4ad9ea3-6162-4463-acc8-ef82078dd382)

We are unable to authenicate using OAthens. May you please assist. 

**Additional context**

**Comment by thijskh** [comment]
We are just making the software your institution uses and do not control the installation your institution has done with it. You can best contact your server's administrator, the IT administrator of fstest.uj.ac.za.
