### ISSUE TITLE
Metadata-converter: The input for uploading a file is not displayed

### ISSUE THREAD

**Issue by felixparra** [simplesamlphp/simplesamlphp#2271]
_Simplesamlphp Version 2.3.2_

**Steps to reproduce the behavior:**
1. Go to '...module.php/admin/federation/metadata-converter'
2. Error: The input for uploading a file is not displayed

**Describe the bug**
When accessing the specified URL, the input for uploading a file is not displayed, and the PHP file upload variable is enabled.

**Solution**
It is necessary to correct the variable declared _file_upload to **file_uploads**_ in the line : modules/admin/src/Controller/Federation.php:482 

**Path**
https://github.com/simplesamlphp/simplesamlphp/blob/d3efb4965ed3d50c01143e17fab09ad2188b7f6a/modules/admin/src/Controller/Federation.php#L482

**Change**
` 'upload' => boolval(ini_get('file_upload')),`
` 'upload' => boolval(ini_get('file_uploads')),`

**Comment by tvdijen** [comment]
Good catch!

**Comment by tvdijen** [comment]
Closed in 4b20c11bfeb046dd4fb339704e190cfcd3dd9d17
