### ISSUE TITLE
multiauth:MultiAuth documentation needs refresh for SSP 2.x

### ISSUE THREAD

**Issue by monkeyiq** [simplesamlphp/simplesamlphp#2281]
The steps shown on https://simplesamlphp.org/docs/stable/multiauth/multiauth.html seem to need an update. I am testing with the latest `simplesamlphp-2.3` branch. My understanding is that in SSP 2.x one should not pass just any auth source to the `\SimpleSAML\Auth\Simple` class but must pass the name of an auth source that is of type `saml:SP`. 

If I setup a configuration like that shown on the multiauth.html page using FileSender as a test application and point it at the `example-multi` auth source then I get the error `Authsource must be of type saml:SP.`

```
Backtrace:
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] 2 /opt/sspdev/src/SimpleSAML/Error/ExceptionHandler.php:36 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] 1 /opt/sspdev/vendor/symfony/error-handler/ErrorHandler.php:538 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] 0 [builtin] (N/A)
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] Caused by: SimpleSAML\Error\Exception: Authsource must be of type saml:SP.
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] Backtrace:
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] 5 /opt/sspdev/modules/saml/src/Controller/ServiceProvider.php:117 (SimpleSAML\Module\saml\Controller\ServiceProvider::login)
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] 4 /opt/sspdev/vendor/symfony/http-kernel/HttpKernel.php:181 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] 3 /opt/sspdev/vendor/symfony/http-kernel/HttpKernel.php:76 (Symfony\Component\HttpKernel\HttpKernel::handle)
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] 2 /opt/sspdev/vendor/symfony/http-kernel/Kernel.php:197 (Symfony\Component\HttpKernel\Kernel::handle)
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] 1 /opt/sspdev/src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
Oct 25 18:47:41 simplesamlphp ERROR [1257be9cfd] 0 /opt/sspdev/public/module.php:17 (N/A)
```

If I disable the SP check then things fall over trying to call `isRequestInitiation` on the multiauth.

```
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] SimpleSAML\Error\Error: UNHANDLEDEXCEPTION
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] Backtrace:
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 2 /opt/sspdev/src/SimpleSAML/Error/ExceptionHandler.php:39 (SimpleSAML\Error\ExceptionHandler::customExceptionHandler)
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 1 /opt/sspdev/vendor/symfony/error-handler/ErrorHandler.php:538 (Symfony\Component\ErrorHandler\ErrorHandler::handleException)
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 0 [builtin] (N/A)
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] Caused by: Symfony\Component\ErrorHandler\Error\UndefinedMethodError: Attempted to call an undefined method named "isRequestInitiation" of class "SimpleSAML\Module\multiauth\Auth\Source\MultiAuth".
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] Backtrace:
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 6 /opt/sspdev/modules/saml/src/Controller/ServiceProvider.php:146 (SimpleSAML\Module\saml\Controller\ServiceProvider::loginHandler)
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 5 /opt/sspdev/modules/saml/src/Controller/ServiceProvider.php:122 (SimpleSAML\Module\saml\Controller\ServiceProvider::login)
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 4 /opt/sspdev/vendor/symfony/http-kernel/HttpKernel.php:181 (Symfony\Component\HttpKernel\HttpKernel::handleRaw)
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 3 /opt/sspdev/vendor/symfony/http-kernel/HttpKernel.php:76 (Symfony\Component\HttpKernel\HttpKernel::handle)
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 2 /opt/sspdev/vendor/symfony/http-kernel/Kernel.php:197 (Symfony\Component\HttpKernel\Kernel::handle)
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 1 /opt/sspdev/src/SimpleSAML/Module.php:234 (SimpleSAML\Module::process)
Oct 25 18:49:53 simplesamlphp ERROR [1257be9cfd] 0 /opt/sspdev/public/module.php:17 (N/A)
```

If I add a stub to the MultiAuth.php module

```
    public function isRequestInitiation(): bool
    {
        return false;
    }
```

Then I can select the auth source to login with and continue on.

Perhaps we should update the documentation on the multiauth.html page around `\SimpleSAML\Auth\Simple`  to mention that the parameter should be to an authsource of type `saml:SP` and that SP should then use an IdP which in turn uses the 'auth' parameter to select the multiauth auth source?

**Comment by juhassi** [comment]
Hello :-)

I originally reported this to the filesender project (see https://github.com/filesender/filesender/issues/2055). Our usecase would be to connect filesender to two different user federations with simplesamlphp, setting filesender to authenticate against a Multiauth defined in filesender's configuration. This configuration has worked with simplesamlphp 1.9.9 but simplesamlphp 2.2.x (and 2.3.x) throw exceptions.

I'd request that simplesamlphp would officially support this usecase -- allowing applications using `\SimpleSAML\Auth\Simple` to use an authsource of type `multiauth::MultiAuth` if that itself is referring only to authsources of type `saml:SP`. IMO adding a separate IdP (proxy) layer would be a needless complication when you only want to select between existing saml SP's.

**Comment by tvdijen** [comment]
> Hello :-)
> 
> I originally reported this to the filesender project (see [filesender/filesender#2055](https://github.com/filesender/filesender/issues/2055)). Our usecase would be to connect filesender to two different user federations with simplesamlphp, setting filesender to authenticate against a Multiauth defined in filesender's configuration. This configuration has worked with simplesamlphp 1.9.9 but simplesamlphp 2.2.x (and 2.3.x) throw exceptions.
> 
> I'd request that simplesamlphp would officially support this usecase -- allowing applications using `\SimpleSAML\Auth\Simple` to use an authsource of type `multiauth::MultiAuth` if that itself is referring only to authsources of type `saml:SP`. IMO adding a separate IdP (proxy) layer would be a needless complication when you only want to select between existing saml SP's.

You shouldn't be using multiauth for this.. You need 1 `saml:SP` authsource that you can call from `\SimpleSAML\Auth\Simple` .. If you have multiple remote IdP's the discovery service will ask you which one to use.

`multiauth` is meant to be used as a selector for different authentication methods..

**Comment by monkeyiq** [comment]
I think perhaps because `saml:SP` and the places that do the authentication (`authentication methods`) such as `sqlauth:SQL`  are defined in `authsources.php` can create some confusion about where things should fit into a deployment picture.

It might make sense to mention briefly on [1] that one normally would use discovery to connect to multiple remote IdPs. Since the first example on [1] shows a multiauth with an SP as one of two multiauth `sources` options it can easily lead the reader to think maybe multi auth might be used in front of the SP.
[1] https://simplesamlphp.org/docs/stable/multiauth/multiauth.html

**Comment by tvdijen** [comment]
Yes, agreed. A `saml20-sp-hosted` file would have made more sense than the `saml:SP` authsource.

**Comment by monkeyiq** [comment]
I like this idea. 

We could add support for `saml20-sp-hosted` and at some point deprecate defining a hosted SP in `authsources.php`.

**Comment by monkeyiq** [comment]
I have carried the sp-hosted idea over to https://github.com/simplesamlphp/simplesamlphp/issues/2299
