### ISSUE TITLE
Argument 1 passed to SimpleSAML\Module::isModuleEnabledWithConf() must be of the type string

### ISSUE THREAD

**Issue by msaustral** [simplesamlphp/simplesamlphp#2290]
Hi we just install simplesamlphp 1.19.9 on server and we are getting this error:

SimpleSAML\Error\Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:20 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: TypeError: Argument 1 passed to SimpleSAML\Module::isModuleEnabledWithConf() must be of the type string, bool given, called in /var/www/vhosts/xxxxxx.com/simplesamlphp/lib/SimpleSAML/Module.php on line 111
Backtrace:
3 lib/SimpleSAML/Module.php:322 (SimpleSAML\Module::isModuleEnabledWithConf)
2 lib/SimpleSAML/Module.php:111 (SimpleSAML\Module::isModuleEnabled)
1 lib/SimpleSAML/Module.php:156 (SimpleSAML\Module::process)
0 www/module.php:10 (N/A)

we know that this version does not have support but we need to use php 7.2
 
any idea?

**Specifics of your environment**
1. Are you acting as SP/IdP/proxy? -> SP
2. SimpleSAMLphp: What version are you using? -> 2
3. PHP: What version are you using?-> 7.2
4. Platform: unix or Windows? -> linux 
5. Webserver: Apache/Nginx/ISS? -> nginx

**Comment by tvdijen** [comment]
The problem is with Nginx.. It doesn't set the `PATH_INFO` server variable correctly and you need to mess with nginx-configuration to get it right.

Have you seen our configuration example?
https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-install.md#configuring-nginx

**Comment by msaustral** [comment]
Hi, if we add the setting that you suggest, we get 502, without it, the page opens but give us the variable type error

![image](https://github.com/user-attachments/assets/bb2ea6bd-203f-47ea-b920-e17e7d9756ab)
