### ISSUE TITLE
SAML 2 IdP should obey Format-attribute in NameIDPolicy. (was #303)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#23]
_From [olavmrk@gmail.com](https://code.google.com/u/olavmrk@gmail.com/) on March 26, 2010 11:22:52_

The IdP should check which NameIDFormat the SP requests, and try to send 
back that format.

It must also be possible to limit which NameIDFormats the IdP is willing 
to give to various SPs.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=303_

**Comment by tvdijen** [comment]
Not sure if this is still an issue in 2018.. Feedback appreciated!

**Comment by tvdijen** [comment]
Closed in #935
