### ISSUE TITLE
Incorrect language code en_LS used for Sesotho

### ISSUE THREAD

**Issue by ghalse** [simplesamlphp/simplesamlphp#2305]
Issues #2269 together with pull requests #2274 and all those mentioned in #2277 erroneously change the language code for Sesotho from `st` to `en_LS`.

This makes no sense whatsoever. Sesotho is a language in its own right, used in Lesotho, South Africa and Zimbabwe. However, `en_LS` suggests it is a Lesotho variant of English. So it's fundamentally the wrong language code for the language.

`st` is the correct ISO639-1 Alpha2 code: https://www.loc.gov/standards/iso639-2/php/langcodes_name.php?iso_639_1=st

In Symfony's locale format, it should be `st_LS`. Or perhaps `st_ZA` since the original translators who produced it [#1260] speak the South African variant of Sesotho (although for these purposes it shouldn't matter). However, this doesn't make sense because the regionalised versions presume a base variant of `st` as a [fallback locale](https://symfony.com/doc/current/translation.html#fallback-translation-locales). Meaning `st` is correct, and should work.

The real problem appears to be that Symfony itself has no idea that Sesotho is a language, irrespective of the regionality of it ([see here](https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/Intl/Resources/data/locales/en.php#L566-L567)).

Symfony appears to derive that data from the Unicode ICU and claims that [6.4 is up-to-date to ICU 75.1](https://github.com/symfony/symfony/blob/v6.4.14/src/Symfony/Component/Intl/Resources/data/git-info.txt). The ICU includes the st language code (and st_ZA and st_LS) from [release 76.1](https://github.com/unicode-org/icu/blob/release-76-1/icu4c/source/data/locales/st.txt).

So the original st that was there before this change will be correct, when Symfony updates its locale information to match the next release of of the ICU locale data...

**Comment by tvdijen** [comment]
Well, this kind of explains why I had a hard time finding the right code for it..
My suggestion would be to rename it to the appropriate `st_ZA` and then hopefully we can locally fix this until Symfony updates their version of ICU.

**Comment by ghalse** [comment]
I think the original `st` is the right answer, rather than `st_ZA`. I'm opening a separate issue at Symfony for them to update the ICU data, since it affects many official languages of many African countries.

**Comment by ghalse** [comment]
I guess the more subtle problem with #2269 is that the [error message](https://github.com/simplesamlphp/simplesamlphp/blob/master/src/SimpleSAML/Locale/Language.php#L152)

> Language "st" not installed. Check config.

is misleading. The language is installed and is a valid language. The real error is that the language code "st" is not known [to Symfony].

**Comment by tvdijen** [comment]
Thanks @ghalse ! I hope this all didn't cause too much trouble for you..
We're trying to offload things like this to Symfony so we don't have to do all the heavy lifting ourself, but missing languages in symfony/intl ... I didn't see that one coming.

**Comment by ghalse** [comment]
> Thanks @ghalse ! I hope this all didn't cause too much trouble for you.. We're trying to offload things like this to Symfony so we don't have to do all the heavy lifting ourself, but missing languages in symfony/intl ... I didn't see that one coming.

This all makes good sense. And fortunately we caught it in QA, so no real impact. Seems Symfony are are already working on the issue.

**Comment by monkeyiq** [comment]
I have moved 2.3, 2.4 and master back to `st`. I will look at the modules next.

**Comment by monkeyiq** [comment]
I updated the 4 modules. I'll do another sweep to make sure nothing was missed.

**Comment by tvdijen** [comment]
> I have moved 2.3, 2.4 and master back to `st`. I will look at the modules next.

You've missed a bit and now the change is only partially reverted...

Good news is that Symfony has updated the ICU files and now we have to wait for v6.4.15 to be tagged.

**Comment by monkeyiq** [comment]
I just took a look at the three branches on github. I am very keen to make sure things are reverted properly, do you have info or hints on which bit I missed?

https://github.com/simplesamlphp/simplesamlphp/tree/simplesamlphp-2.3/locales/st/LC_MESSAGES

**Comment by tvdijen** [comment]
I noticed at least this bit:
https://github.com/simplesamlphp/simplesamlphp/blob/master/src/SimpleSAML/Locale/Language.php#L130-L140

**Comment by monkeyiq** [comment]
I see one or two. A grep -R is my friend :)

**Comment by monkeyiq** [comment]
I will fix this in the morning. Having a little issue with some new network gear.

**Comment by monkeyiq** [comment]
I also noticed the line with `$configuredAvailableLanguages`

**Comment by monkeyiq** [comment]
The network gear thing was "not fun" but seem to be back now.
https://github.com/simplesamlphp/simplesamlphp/pull/2311

**Comment by tvdijen** [comment]
Symfony v6.4.15 was released yesterday, so if we can update the error message we can tag a new release where st-language is working again

**Comment by monkeyiq** [comment]
Error message updated in 2.3, 2.4 and master

**Comment by tvdijen** [comment]
Great work @monkeyiq !
I suggest to merge #2312 to 2.4 and master only.

**Comment by monkeyiq** [comment]
I have merged 2312 now.  Cherry picked the 2 core commits and used the GHA scripts to do the translation run.

**Comment by monkeyiq** [comment]
So it is in master && 2.4

**Comment by tvdijen** [comment]
Released v2.3.3
