### ISSUE TITLE
Maximum Supported PHP version in documentation

### ISSUE THREAD

**Issue by origamifreak2** [simplesamlphp/simplesamlphp#2310]
**Is your feature request related to a problem? Please describe.**
There is no maximum supported php version listed in the documentation for the different SimpleSamlPHP versions.

**Describe the solution you'd like**
Have the maximum php version listed in the documentation. This might be the same for all of them, but it would be nice to have it clearly stated.

**Describe alternatives you've considered**
N/A

**Additional context**
I searched the web, and all I found was that some older versions of SimpleSamlPHP had issues with php 8.

**Comment by origamifreak2** [comment]
Thank you @tvdijen . I read the docs a little more and I see that php 7.4 or greater is supported for SimpleSamlPHP
https://simplesamlphp.org/docs/2.0/simplesamlphp-install.html
![php74 or greater](https://github.com/user-attachments/assets/b4cabcd3-e498-4a34-bd4a-e4528cbb4f35)

I was specifically looking at the "Upgrade Notes" page. It states the minimum version of php but not the max.
https://simplesamlphp.org/docs/2.0/simplesamlphp-upgrade-notes-2.0.html
![simplesamlphp_min_max_php](https://github.com/user-attachments/assets/78f72d13-6867-4f18-bbd7-6a26263064e8)

Sorry about the confusion. I read that some older versions of SimpleSamlPHP had issues with php 8, so I was thinking there might be a max supported version as well as a minimum.

**Comment by tvdijen** [comment]
I'm not sure why you are looking at unsupported versions of SimpleSAMLphp, but 2.0 is long gone..
