### ISSUE TITLE
Unable to acess to simplesamlp web page

### ISSUE THREAD

**Issue by IsmailBenjelloun** [simplesamlphp/simplesamlphp#232]
Hi,

I am using ISS7 on Windows server 2008 and I tried to install Simplesamlphp.
1. I installed php from this web site http://php.iis.net/ and I added this configuration on php.ini file:
- fastcgi.impersonate = 1. 
- cgi.fix_pathinfo = 1.
- cgi.force_redirect = 0.
- open_basedir = C:\inetpub\wwwroot (ISS location)
You can see phpinfo return as attachement.

2. I installed simplesamlphp following this procedure "http://www.wayf.dk/wayfweb/howto%27s_attchmt/SimplesamlPHP%20on%20windows%202003%20server%20minimal%20installguide.pdf"
But it does not work, I have a blanck web page when I try to access to: http://localhost:8080/simplesamlphp/modules/core/www/frontpage_welcome.php
![phpinfo 1](https://cloud.githubusercontent.com/assets/13523625/8909788/9e8ab140-3483-11e5-8c9c-69ad685114a3.jpg)
![phpinfo 2](https://cloud.githubusercontent.com/assets/13523625/8909791/9fb24682-3483-11e5-96cc-de641997240b.jpg)

I am still blocked, anyone have an idea ?

Thanks in advance,

Ismail

**Comment by thijskh** [comment]
The issue tracker is for bugs in the software, not for questions on how to use it. Please use the simpleSAMLphp mailinglist for that.

As a first hint, if you get a blank page there's probably something in your webserver's error logs.
