### ISSUE TITLE
PHP 8.4 incompatibility

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#2324]
From the PHP 8.4 changelog:

Gettext:
bind_textdomain_codeset, textdomain and d(*)gettext functions now throw an exception if the domain argument is empty.
      
We have one case where this affects us:

https://github.com/simplesamlphp/simplesamlphp/blob/76109fbcce35c00d4244ab6cee4c7bf879508091/src/SimpleSAML/Locale/Translate.php#L95-L99

**Comment by monkeyiq** [comment]
I think here the only po files without a domain (`X-Domain` in the po file) are the attributes file in locales/en/LC_MESSAGES.  We could make that domain "attributes" and update this fallback to using that.

**Comment by tvdijen** [comment]
I was hoping it was that simple, yes :D  If you could test this for us, that would be great!

**Comment by monkeyiq** [comment]
Will do. As I am not on the latest Fedora I think I will either update a secondary machine or install F41 in a VM to be able to verify that php 84 is happy with this as well. Having a "Works on 8.3" is weaker than a works on 8.4 goal.

**Comment by monkeyiq** [comment]
more to do on the pr when testing it in anger.

**Comment by monkeyiq** [comment]
After a bit of chasing my tail I see that the `dgettext` call in SSP is actually to a php library:
https://github.com/php-gettext/Translator/blob/a4fa5ed740f304a0ed7b3e169b2b554a195c7570/src/Translator.php#L121

Running current 2.3 (`d31b3b3`) in a Fedora 41 VM with an updated 8.4.1 php version seems to work fine.

**Comment by monkeyiq** [comment]
I will also take a look at composer generating binary mo files in master soon.
