### ISSUE TITLE
ScopeAttribute and ScopeFromAttribute treat source with multiple @ differently

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/simplesamlphp#236]
When presenting with an attribute value that has multiple `@`-signs, like `john@doe@example.com`, ScopeAttribute will consider everything after the first `@` the scope, while ScopeFromAttribute considers only everything from the lastmost `@` the scope.

This should probably be unified. I'm quite indifferent in which direction because I don't think it's a common case. Opinions?

**Comment by jaimeperez** [comment]
I agree, both should be unified.

Regarding which approach to follow, I believe there was some guidelines somewhere regarding what to consider the realm in a case like this. I'll have to do some research.

**Comment by thijskh** [comment]
AttributeRealm has a third approach: if the source attribute has multiple `@`'s, the authprocfilter just does nothing.

**Comment by jaimeperez** [comment]
I found something, though not very promising. The [eduPerson specification](http://software.internet2.edu/eduperson/internet2-mace-dir-eduperson-201310.html#eduPersonScopedAffiliation) refers to this problem. The __recommendation__ there is to use the first @ sign, considering the realm the rest of the value starting there.

In Feide, we are doing the opposite, actually. We are splitting `eduPersonPrincipalName` by the last @ sign when obtaining the realm from there, as that allows us to detect the case where a user is typing his or her email address as the username.

I don't have any strong feelings towards one or the other. However, taking into account the recommendation in the eduPerson specification, I'm inclined to just follow that and unify all the filters to split in the first @ sign. Does it sound reasonable? Objections?

I'm also wondering about `core:ScopeFromAttribute` and `core:AttributeRealm`. Both look for a realm in an existing attribute, and create a new one with it. Do you see any difference between them, apart from the fact that the latter uses the `userid.attribute` configuration option to determine where to fetch the realm from? I'm deprecating this option right now as per #3, so I'm wondering why would we want to maintain both.

**Comment by thijskh** [comment]
If their behaviour is unified, I believe that ScopeFromAttribute can be seen as a generalised version of AttributeRealm.

**Comment by jaimeperez** [comment]
Yes, and that's why I'm quite eager to deprecate `core:AttributeRealm` and get rid of it later.

What about the two options to parse realms? Come on, take a risk! :stuck_out_tongue:

**Comment by thijskh** [comment]
So in Feide you actually create ePPN based on the user's own input into the login form?

**Comment by jaimeperez** [comment]
Not exactly. We use that user input to try to log the user in. Then we fetch all his/her attributes from the directory. Remember we have one IdP connected via LDAP to all our institutions. The IdP lets you also choose your organization, and sometimes the one pre-selected for you could be wrong. This small trick we are doing allows us to disregard the pre-selected organization and select another one based on what the user entered, then authenticate, then fetch the attributes. So if I previously logged in with my UNINETT account and reach Feide login again, UNINETT will be pre-selected for me. But then I want to use my NTNU account, so I just need to append a @ntnu.no to my NTNU credentials, and all will work.

No other side effects in the attributes, anyway.

**Comment by thijskh** [comment]
I personally do not have any preference for a specific interpretation, although the no-op route seems a strange choice to me so I'd discard that as an option. Making it configurable is obviously the most flexible. I'd set the default to the eduPerson one and (that is missing in all three now) document the behaviour explicitly.

**Comment by jaimeperez** [comment]
Having it configurable with a common default behaviour sounds like the way to go. I also agree about no-op, I wasn't even considering that as an option.

**Comment by thijskh** [comment]
Rereading this item I conclude that we'll:
- [ ] Follow the eduPerson recommendation to use the first @ sign, considering the realm the rest of the value starting there, consistently in all places;
- [ ] Deprecate AttributeRealm in favour of ScopeFromAttribute.

**Comment by thijskh** [comment]
I have filed #512 for the deprecation since it's essentially a different issue than the treatment of `@`.
