### ISSUE TITLE
SSO session timeout error in assertion

### ISSUE THREAD

**Issue by tsmgeek** [simplesamlphp/simplesamlphp#244]
SessionNotOnOrAfter keeps moving forwards each time an loginrequest is submitted to the SSO server rather than returning the correct expiry for the existing SSO session.

        <saml:AuthnStatement AuthnInstant="2015-08-20T16:34:09Z"
                             SessionNotOnOrAfter="2015-08-21T00:39:49Z"
                             SessionIndex="_XXXXXXXXXXXXXXXXXXXXX"
                             >

**Comment by jaimeperez** [comment]
Hi @tsmgeek,

Thanks a lot for opening this issue! It's quite strange that nobody noticed this bug before. I'll commit a fix for it asap.
