### ISSUE TITLE
PHP fatal error after login 

### ISSUE THREAD

**Issue by enricocavalli** [simplesamlphp/simplesamlphp#247]
On a test IDP where we track simplesaml development, I found a problem after login (blank page with a PHP fatal error)

[Tue Aug 25 13:55:02 2015] [error] [client 131.175.0.10] PHP Notice:  Undefined variable: authId in /var/simplesamlphp/lib/SimpleSAML/Auth/Source.php(165) : assert code on line 1, 
[Tue Aug 25 13:55:04 2015] [error] [client 131.175.0.10] PHP Notice:  Undefined index: core:IdP in /var/simplesamlphp/lib/SimpleSAML/IdP.php on line 156

[Tue Aug 25 13:55:04 2015] [error] [client 131.175.0.10] PHP Fatal error:  Call to a member function getString() on a non-object in /var/simplesamlphp/lib/SimpleSAML/IdP.php on line 104,

The problem  should be in one of the last commits (starting from 8e4c8b69d900c31105a350dd5b1c3aecc13958bb) but I'm not able to track it down right now.

**Comment by enricocavalli** [comment]
The issue seems related to extractPersistentAuthState. Later on (after a successful login) the code expects $state['core:IdP'] which now seems not saved by the new PersistentAuthState.

**Comment by jaimeperez** [comment]
Thanks a lot for notifying us @enricocavalli!

This was a mistake due to a confusion. The state array should not be modified by `extractPersistentAuthState()`, and that was leading to the missing information on it showing up as undefined key errors and code breaking horribly. My bad.

It's now fixed as working as it should.

**Comment by enricocavalli** [comment]
Thank you very much!

**Comment by sachinkiet** [comment]
[https://odd.blog/2015/02/12/php-notice-undefined-variable-_server-in/](url)

**Comment by sachinkiet** [comment]
[https://odd.blog/2015/02/12/php-notice-undefined-variable-_server-in/](https://odd.blog/2015/02/12/php-notice-undefined-variable-_server-in/)
