### ISSUE TITLE
Dependency issue with openid/php-openid

### ISSUE THREAD

**Issue by dialogik** [simplesamlphp/simplesamlphp#249]
There seems to be a dependency issue with [openid/php-openid](https://github.com/openid/php-openid):

	$ composer update

	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.

	  Problem 1
	    - simplesamlphp/simplesamlphp v1.13.2 requires openid/php-openid dev-master#ee669c6a9d4d95b58ecd9b6945627276807694fb as 2.2.2 -> no matching package found.
	    - simplesamlphp/simplesamlphp v1.13.1 requires openid/php-openid dev-master#ee669c6a9d4d95b58ecd9b6945627276807694fb as 2.2.2 -> no matching package found.
	    - simplesamlphp/simplesamlphp v1.13.0 requires openid/php-openid dev-master#ee669c6a9d4d95b58ecd9b6945627276807694fb as 2.2.2 -> no matching package found.
	    - Installation request for simplesamlphp/simplesamlphp ~1.13 -> satisfiable by simplesamlphp/simplesamlphp[v1.13.0, v1.13.1, v1.13.2].

**Comment by jaimeperez** [comment]
Hi @dialogik, thanks for your report!

This has been discussed several times (#52, #92), and is already fixed in master.

**Comment by dialogik** [comment]
Oh, my bad, sorry!
