### ISSUE TITLE
CR: Find Alternative for OpenIdP

### ISSUE THREAD

**Issue by gfaust-qb** [simplesamlphp/simplesamlphp#250]
> The OpenIdP will be shut down the 1st of January 2016. If your are using it to test your SAML Service Provider or you rely on it in any way, we advise you to look for alternatives before that date. We will study meanwhile the ways we have available to offer similar or equivalent funcionality if needed.

There should be an alternative for OpenIdP and enough time to adjust the Documentation.

**Comment by jaimeperez** [comment]
Hi @gfaust-qb!

As stated, we are studying possible alternatives and we are even in contact with some organizations that suggested offering resources to host it.

In any case, the OpenIdP as it is today (at least the self-testing feature) will shut down by the end of the year. It has never been a service in production, and it's consuming many resources that we simply cannot afford, so there's no discussion around that. Whether we continue to offer an alternative or not is unfortunately not a priority, as it has always been just a commodity and is in no way essential for SimpleSAMLphp.

**Comment by gfaust-qb** [comment]
Hi @jaimeperez!

I agree with you in many of the points you mention, but I looked at SimpleSAMLphp and OpenIdP separately - having another point of view ;)

**Comment by jaimeperez** [comment]
We'll see how this develops. Hopefully we'll find a compromise solution that allows us to provide a much better service without the economical implications it has today for UNINETT :wink:
