### ISSUE TITLE
Absolute paths for cert and metadata?

### ISSUE THREAD

**Issue by dialogik** [simplesamlphp/simplesamlphp#251]
#221 introduces a smart way to decouple the config file from the SimpleSMLphp library. But as far as I can see, the directories `cert/` and `metadata/` are relative to the library. Or am I wrong here? How can I define absolute paths for both?

**Comment by thijskh** [comment]
You can just set the `certdir` and `metadatadir` config options?

**Comment by jaimeperez** [comment]
Hi!

Thijs is right, you can set both in the `config.php` file.

**Comment by dialogik** [comment]
Right, I wasn't aware of that, I thougt only relative paths are allowed.
