### ISSUE TITLE
IE send old cookie for the second logout

### ISSUE THREAD

**Issue by cly19891215** [simplesamlphp/simplesamlphp#252]
Hi,

We configure the SimpleSAMLphp@1.12 as a SP.
There is a logout issue in IE 11.

Produce step,

1. First time, SSO success and SLO success.

2. Donnot close IE and SSO again. Then SLO failure.

I print the cookie in simplesaml log, found IE send the same cookie for these two SLO request.

Cookies for first time SLO:
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] _ga is GA1.2.1952344204.1441173472
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] pls_login_rememberme is mcgrady-dev50
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] _gat is 1
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] UID is d93b861b-3572-467f-a190-5cd5bba79bbf
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] timestamp is 1441199451
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] ip is 104.42.109.38
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] signature is AO1Amadg/iTqyBoe5nw2a6wPB+UKp0NtU2GOIsIC8gG+D6uKSdOB5/LfPbHveyCXWQJbQeLqCrpQjQwrHzU9x+utAtjfSSr0STCCpoOnEIKQ5WpFM/HkTvnSlYK0o7u0v5MckTTMIFIuxFF7VOblILQw7PuJM2PWUGUnT+mO0P3wZn4tgvGl0xj5PtPeOlZ7FKV924SQOYU1k1yELJNJVuOPqM0Sd66Q/gExJ3MwdNeM7R6bUTCJ+h0Jgz6jaHi72uXea/mazUijiUhGMgARFxWpHxaSR2qAWvUWJaFTGOR8QiGOqCHGsG1aigy6w/8kc+RXGYFtKLko96YJXfTY4g==
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] PHPSESSID is mkfqdo67qcg5irvob88ksnvrc1
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] SimpleSAMLSessionID is d1dd5674292807cb2d4ef48ae591b7a4
Sep 02 13:10:31 simplesamlphp ERROR [15ebd9961a] SimpleSAMLAuthToken is _54ddf4979be3c7b13edfe6c02171cd43e22bfeaea9

Cookies for second time SLO:
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] _ga is GA1.2.1952344204.1441173472
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] pls_login_rememberme is mcgrady-dev50
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] _gat is 1
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] UID is 5327ac28-6d2c-4107-a1ce-f0609686b7d5
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] timestamp is 1441199469
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] ip is 104.42.109.38
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] signature is gnTM93XhSkuyLpBL9lIUKTywXLRT8Xz9rRDxfmSbJnqyGdVBw1t1EzA/YEF+CV9o3aJiz5XLeTv26mDYO6/U6PC5eHrnMWNIdIrvRW/MCYVzRIbfEeocbmIv+dl0CV+E3IUFhnEhJoeaAa81qex2ElnpbRZ3qU2T7uZnw0kAHxig2ZzY2wiR8+1wnt9k5RGDH/266vQniSf7bW1ABNdRCZotVVEqe4DAkStIyi76BBNEmAB2mcvB/zMhBMWM4zzIJ+ljQQJnKvgh43gnNtVniXQq4IvkeeBuvVZveJQIZJlPY0aWAyCFwbp4/qG7NbDfaPWLXh9rrcoTjlCtW510UA==
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] PHPSESSID is mkfqdo67qcg5irvob88ksnvrc1
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] SimpleSAMLSessionID is d1dd5674292807cb2d4ef48ae591b7a4
Sep 02 13:11:00 simplesamlphp ERROR [15ebd9961a] SimpleSAMLAuthToken is _54ddf4979be3c7b13edfe6c02171cd43e22bfeaea9

Could any body give some suggestion or explain how simplesamlphp refresh the "SimpleSAMLAuthToken" cookie ?

Thanks

**Comment by jaimeperez** [comment]
Hi,

For an SP, the `SimpleSAMLAuthToken` is randomly generated every time the service provider processes successfully a SAML response from an IdP (provided that there was no previous session or it was invalid). For an IdP, this cookie is also randomly generated every time the user logs in. Therefore, if you are running an SP, it's not normal that the cookie keeps its value from one session to another.

Could you please provide the network traces of the entire process (conveniently anonymized, of course)?  If Internet Explorer is not changing the value of this cookie as told by the server, then that's a bug in IE, not in SSP, and I'm afraid there's not much we can do. It might be possible though that the problem is somewhere else, but without proper traces it's difficult to tell.

You need to ensure that when the SAML response is posted to `saml2-acs.php`, an HTTP **Set-Cookie** header is set in the response by the server, containing different values across sessions.

**Comment by cly19891215** [comment]
Hi Jaimeperez,

Thanks for your answers.

I think set-cookie header is set. It works well in Chrome and Firefox.
And, if I press F12 to open "Developer Tools" and capture network, IE will send the correct cookies.

It looks like IE ignore or cache the Set-Cookie header in some situation.

Thanks~

**Comment by jaimeperez** [comment]
So you confirm that the cookie sent by IE gets correctly updated during the second login, right?

What's exactly the error you get when trying to log out for the second time?

**Comment by cly19891215** [comment]
Yes, I think the second login set the correct cookie. Chrome and Firefox could log out successfully for the second. But IE send the old "SimpleSAMLAuthToken" when log out for second time, do not log out from IdP.

**Comment by jaimeperez** [comment]
Hi!

What is the domain of your service provider, and what's the cookie configuration you have in `config/config.php`? Could you post here a capture of the network traffic while reproducing the error (including both the first and the second login)?

**Comment by cly19891215** [comment]
Hi Jaimeperez

After I monitor the IE network traffic, I found the root cause. IE get the response of "module.php/core/authenticate.php?as=tmss365-sp-dev" from cache. I add a random query string after this request to walk around this issue and it works. 

<entry method="GET" URL="https://auth-stg.tmcas.trendmicro.com/module.php/core/authenticate.php?as=tmss365-sp-dev">
	<pageref idref="page_90" />
	<started>01:02:21.420</started>
	<startedDateTime>2015-09-08T12:18:57.211</startedDateTime>
	<time>0.003</time>
	<sent>0</sent>
	<received>0</received>	<result>(Cache)</result>
	<overview>
		<action name="Display URL" status="Completed">Normal browser lookup of URL https://auth-stg.tmcas.trendmicro.com/module.php/core/authenticate.php?as=tmss365-sp-dev</action>
		<action name="Started At" status="Completed">08-Sep-2015 12:18:57.211 (local time)</action>
		<action name="Redirect" status="">A redirect to https://admin-stg.tmcas.trendmicro.com/ui_sso_login?token=zI3-QaOc09Muilgq-3CoNQ.5hYU4pQxeIeKIAIyKL_IePjP3lDargzzPE8Bi_hSwt24T3Q79LC4YaRcctobdLQS7A4TBjk_rkGsqpbeV_nq0UcV6UuXHhyKGp6mvp1WRlb_PXrD8K-5HRGUocqin_OSvqjEf6bDMXH50WhnwMlmzkCzonI-vnRJywma5H7nYF34KnDkz8RRPLa3gnaPDtq4oaeRd8hUPVGxCJyvaTkUIAl_29rjzkRE9wSaOfmC9aDIPNpzi2GLJEDaLvsDt2078lVAMK_EyiOsLa4_wfpgrRMPkp91VSEG6hrsgTenK6YbR6XGlV4YlsDTfaxLV7eyiy-yYrHk2THY7z7fxMhd65Zokc9niUWA3FKra8piN6NCfyIMrZUIc6Ir1PwL3gsSDyX6mD2ESTmr9bkTSeS6X4juGf8cJvVYz1VeP6TMMrw8S9dHajibfhpC-A0mh44E4KF1JkwOLdpuIiUziAHHYSdaOBP0KWSg-3ETZGC2pOA.1441682172836.3540000.HbIHagHTGMyMDjbI6fC-82MD8eJ05Tldkh6OojFS14U&amp;tenant_id=tm was read from the cache</action>
	</overview>
	<request>
		<requestMethod></requestMethod>
		<cookies></cookies>
		<headers></headers>
		<queryString>
			<parameter name="as">tmss365-sp-dev</parameter>
		</queryString>
	</request>
	<response>
		<responseStatus></responseStatus>
		<cookies></cookies>
		<headers></headers>
		<content>
			<error>(Content not found in cache)</error>
			<mimeType>text/html</mimeType>
		</content>
		<redirectURL>https://admin-stg.tmcas.trendmicro.com/ui_sso_login?token=zI3-QaOc09Muilgq-3CoNQ.5hYU4pQxeIeKIAIyKL_IePjP3lDargzzPE8Bi_hSwt24T3Q79LC4YaRcctobdLQS7A4TBjk_rkGsqpbeV_nq0UcV6UuXHhyKGp6mvp1WRlb_PXrD8K-5HRGUocqin_OSvqjEf6bDMXH50WhnwMlmzkCzonI-vnRJywma5H7nYF34KnDkz8RRPLa3gnaPDtq4oaeRd8hUPVGxCJyvaTkUIAl_29rjzkRE9wSaOfmC9aDIPNpzi2GLJEDaLvsDt2078lVAMK_EyiOsLa4_wfpgrRMPkp91VSEG6hrsgTenK6YbR6XGlV4YlsDTfaxLV7eyiy-yYrHk2THY7z7fxMhd65Zokc9niUWA3FKra8piN6NCfyIMrZUIc6Ir1PwL3gsSDyX6mD2ESTmr9bkTSeS6X4juGf8cJvVYz1VeP6TMMrw8S9dHajibfhpC-A0mh44E4KF1JkwOLdpuIiUziAHHYSdaOBP0KWSg-3ETZGC2pOA.1441682172836.3540000.HbIHagHTGMyMDjbI6fC-82MD8eJ05Tldkh6OojFS14U&amp;tenant_id=tm</redirectURL>
	</response>


Thanks very much for your help.

**Comment by jaimeperez** [comment]
Thanks for letting us know @cly19891215!
