### ISSUE TITLE
RelayState issue with simplesamlphp

### ISSUE THREAD

**Issue by ksreeejith** [simplesamlphp/simplesamlphp#254]
We have integrated simplesamlphp  as SP and integrated Gigya IDP.

We are able to login successfully, but while calling logout(), after IDP logs out, its redirecting back to the URL mentioned in the function.

$samlObj->logout($homePage); // This function makes a call to $homepage, but its not redirecting.

While checking the SAML request we have seen that the RelayState is passing as some number, RelayState: _61a9021fb90fb94a21fb9b12d14692d4f502050155, instead of the url given.

Please help

**Comment by jaimeperez** [comment]
Hi @ksreeejith!

This is an issue tracker, not a support forum. Please use [the mailing list](https://groups.google.com/forum/#!forum/simplesamlphp) to ask for support.
