### ISSUE TITLE
Get rid of the enabled SAML 2.0 and Shib 1.3 lights in the configuration tab (was #341)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#26]
_From [andreass...@gmail.com](https://code.google.com/u/102889613336421617108/) on September 22, 2010 11:38:44_

As the SAML functionality is moved out in modules, the enabled traffic lights are not longer as valid as they once were. We shuold remove this box from the UI.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=341_

**Comment by jaimeperez** [comment]
Since we will stop to support SAML 1.1, these can just go away.

**Comment by tvdijen** [comment]
They're gone in new UI, therefore closing this
