### ISSUE TITLE
Feature request: configurable module, metadata and config locations (was #349)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#27]
_From [ivojansc...@gmail.com](https://code.google.com/u/112316471515613173611/) on October 27, 2010 12:33:50_

I'm developing a project which uses simplesamlphp. I'm developing, among other things, a custom authsource. It would be great if I can create a project in my own SVN server that uses simplesamlphp as an svn external, so I can easily keep up to date with simplesamlphp's development.

This is currently not possible because all modules, metadata and configurations are always stored in a subdir of simplesamlphp; it would be great if this could be externalized to directories outside of the main simplesamlphp directory, so an svn external can easily do a drop in of simplesamlphp into an existing svn project.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=349_

**Comment by jaimeperez** [comment]
This was already possible for metadata.

The configuration directory can also now be located somwhere else thanks to #221.
