### ISSUE TITLE
Modules should be enabled in configuration, not filesystem

### ISSUE THREAD

**Issue by ntoniazzi** [simplesamlphp/simplesamlphp#274]
I'm using simplesamlphp on a project, loading it as a composer requirement. Thus, I can't (or shouldn't) change anything under the vendor directory. Modules are enabled by renaming a file (default-disable → default-enabled), which causes me some trouble.
Is there (or will there be) another way to enable modules in the configuration file?

**Comment by szabogyula** [comment]
Take a look at the config-templates/config.php

line: 214

```
    /*
     * Module enable configuration
     *
     * Configuration to override module enabling/disabling.
     *
     * Example:
     *
     * 'module.enable' => array(
     * 	// Setting to TRUE enables.
     * 	'exampleauth' => TRUE,
     * 	// Setting to FALSE disables.
     * 	'saml' => FALSE,
     * 	// Unset or NULL uses default.
     * 	'core' => NULL,
     * ),
     *
     */
```

**Comment by ntoniazzi** [comment]
I missed this one, sorry.
Thanks.
