### ISSUE TITLE
Using an image input for multiauth fails in Firefox

### ISSUE THREAD

**Issue by forevermatt** [simplesamlphp/simplesamlphp#287]
When using multiauth, we tried using image inputs similar to the following to show a clickable logo for the user's selection screen: 

```
<input type="image" src="abcd-logo.png" value="abcd" name="src-YWJjZA==">
```

However, Firefox only sends the x and y parameters (from where the user clicked) for an image input (rather than also including the original name/value pair).

Example:
**src-YWJjZA==.x** 150
**src-YWJjZA==.y** 83  

See this Firefox bug report for why they consider this the correct behavior:
https://bugzilla.mozilla.org/show_bug.cgi?id=583211

Some other browsers also include the original name/value pair:
**src-YWJjZA==** abcd  

The problem is in the logic that simplesamlphp uses when it doesn't find the actual name/value pair.  It searches the request array for an entry starting with "src-", then tries to base64-decode the rest of that parameter name.  When something like "YWJjZA==.x" is decoded, however, you end up with a bit of garbage on the end, and so it doesn't match any of the defined options.

This seems to be taking place on this line of code:
https://github.com/simplesamlphp/simplesamlphp/blob/af24da40fd3e4b9067a661952c28b3b5e4413940/modules/multiauth/www/selectsource.php#L34

```
$source = base64_decode($k[1]);
```

Something like the following might fix this problem.  It detects the first character that couldn't have come from base64_encode, and strips off it and all the following characters (thus removing the ".x" suffix, leaving us with the desired string):  

```
$source = base64_decode(preg_replace('/[^A-Za-z0-9+\/=]+.*/', '', $k[1]));
```

I haven't fully tested that yet, but it seems like some approach like that would resolve this.

**Comment by jaimeperez** [comment]
Hi @forevermatt!

Thanks for your report! Since you modified the input element, I'm assuming you are using your own theme / template, right? In that case, wouldn't the same goal be achieved by leaving the input as a button, and styling it with CSS (including an image as the background of the button)?

**Comment by forevermatt** [comment]
Hi @jaimeperez. I think the reason we used an image input element (rather than a button with an image background) was because of how they each worked with material design light, which we were using for the UI. For better or worse, that project is now on hold, so this is no longer a priority at the moment. Feel free to leave it as a low-priority issue until someone has the time/need to really test it and decide whether to incorporate this suggestion.

**Comment by tvdijen** [comment]
HI @forevermatt ! I'd like to know if this is still relevant in 2018?

**Comment by forevermatt** [comment]
Hi @tvdijen. Thanks for checking. This is not affecting any of our current work, so feel free to close this issue unless/until it affects someone else.

**Comment by tvdijen** [comment]
Thanks for  getting back to us @forevermatt
