### ISSUE TITLE
AssertionConsumerServiceURL gives Exception: Missing SAMLRequest or SAMLResponse parameter.

### ISSUE THREAD

**Issue by rw3iss** [simplesamlphp/simplesamlphp#289]
I was told to file this issue as this exception seems to be a bit generic, and not related to the ACS response.

How I achieved this was by trying to hit the ACS url:
    'AssertionConsumerService' => 'http://weiss.dev2.rowanonline.com/simplesaml/module.php/saml/sp/saml2-acs.php/drupalauth'

When I get there, it gives:
>SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
>Backtrace:
>0 /var/www/weiss.dev2.rowanonline.com/webroot/simplesamlphp/www/module.php:179 (N/A)
>Caused by: Exception: Missing SAMLRequest or SAMLResponse parameter.
>Backtrace:
>2 >/var/www/weiss.dev2.rowanonline.com/webroot/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML>2/HTTPRedirect.php:99 (SAML2_HTTPRedirect::receive)
>1 /var/www/weiss.dev2.rowanonline.com/webroot/simplesamlphp/modules/saml/www/sp/saml2-acs.php:17 (require)
>0 /var/www/weiss.dev2.rowanonline.com/webroot/simplesamlphp/www/module.php:134 (N/A)

Supposedly this is the wrong error?

**Comment by jaimeperez** [comment]
Hi!

I've just realized this one was fixed way before it was reported 😄 

I fixed the issue more than a year ago in b20fa79506439906323663ac15c9ddb07bbb063b. However, the last stable release available at the time this issue was opened did not include it since it predated the commit in question.

**Comment by rw3iss** [comment]
Awesome! hah.
