### ISSUE TITLE
Remove dependency on jQuery UI (was #372)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#29]
_From [olavmrk@gmail.com](https://code.google.com/u/olavmrk@gmail.com/) on December 17, 2010 08:54:20_

jQuery UI isn't used for any advanced features, so we should be able to remove it. Doing that will make it easier to keep jQuery versions up to date.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=372_

**Comment by jaimeperez** [comment]
jQuery-UI is no longer present since 6941a55.
