### ISSUE TITLE
Maybe a forgotten urldecode

### ISSUE THREAD

**Issue by 540Grunkspin** [simplesamlphp/simplesamlphp#290]
I could not get the server to work and i think i found a bugg

I added a urldecode to the the receive method in file vendor/simplesaml/saml2/src/HTTPRedirect.php before the base64_decode and it now works like a charm.

Maybe i did something wrong in the SP (The SP is written i python using python-saml) i don't know but that added line made the whole thing work.

Best Regards
Anton Holmberg

PS
Thanks for the great project it helped me a lot!

**Comment by thijskh** [comment]
Can you provide the raw base64 encoded SAML message that was sent to your IdP which required this change? It should be in the GET parameters that are sent to your simpleSAML installation so should be easy to catch from you Apache logs or alternatively with the Firefox SAML-Tracer extension.

**Comment by 540Grunkspin** [comment]
It was my client that was sending the wrong stuff. Sorry about that.
