### ISSUE TITLE
Periodic 500 instead of 303 for requests to /simplesaml/module.php/saml/sp/saml2-acs.php/default-sp

### ISSUE THREAD

**Issue by gb321** [simplesamlphp/simplesamlphp#292]
We appear to have an identical issue to what was reported here:

https://groups.google.com/forum/#!topic/simplesamlphp-dev/SwSEQ8wzER8

Specifically, we sporadically get 500s and not 303s for the URL /simplesaml/module.php/saml/sp/saml2-acs.php/default-sp.  Looking at the SAML dialogue via a SAML tracer plugin (Firefox), things appear to be okay, but it's unclear why a 500 is being returned.  We're wondering how to debug this issue as well.  The poster of the original issue above was advised to log it here, but I do not see that he did (or apologies if I missed it), so I'm wondering if anyone can advise.

Thanks

**Comment by jaimeperez** [comment]
Hi @gb321!

What version of SimpleSAMLphp are you running? I suspect this could be related to the issue #260, which is now fixed in master. If you are not running master, could you try doing so (of course with all due precautions) and tell us if you still have the issue or it disappears?

Thanks!

**Comment by gb321** [comment]
I'm sorry, I should have updated this a couple of weeks ago.  After further debugging, the issue was found to be unstable clocks on the IdP side and window for the SAML transaction was being exceeded (artificially).  Oddly, this wasn't happening regularly, it would happen sporadically, which is what confused me.  However, since the clocks at the IdP have been repaired, we have not had this problem since, so I feel it is quite likely the reason we had those issues.  I'll close the issue.

**Comment by jaimeperez** [comment]
Thanks a lot for the feedback! Glad you solved the issue :smile:
