### ISSUE TITLE
Open ID version update for Composer Install

### ISSUE THREAD

**Issue by praveen77** [simplesamlphp/simplesamlphp#294]
OpenId version 2.2.2 on dev-master is no longer available or has been updated to 2.3.0, can we please update the dependency requirement.

**Comment by jaimeperez** [comment]
Hi @praveen77,

No OpenID modules are part of SimpleSAMLphp any longer, so obviously there's no such dependency requirement here. In any case, this issue should be opened for the modules themselves.
