### ISSUE TITLE
Documentation out of date.

### ISSUE THREAD

**Issue by vfdev** [simplesamlphp/simplesamlphp#299]
The `metadata` and `config` directories are currently untracked by the repository, making the sequence of commands seen here: https://simplesamlphp.org/docs/development/simplesamlphp-install-repo ineffective without including `mkdir config; mkdir metadata;`.

Adding .gitkeep files will keep the folders within the repository, and the rest of the contents of those folders can be ignored. This will achieve parity with the installation instructions and doesn't change the process for installation.

There is a pull request that addresses this issue: https://github.com/simplesamlphp/simplesamlphp/pull/298

**Comment by jaimeperez** [comment]
Merged!
