### ISSUE TITLE
Extend NameID filters to work with SAML 1.1 IdP (was #373)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#30]
_From [olavmrk@gmail.com](https://code.google.com/u/olavmrk@gmail.com/) on December 21, 2010 13:46:14_

Currently, only the SAML 2.0 IdP supports different NameID formats. We should also add support for those in SAML 1.1.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=373_

**Comment by tvdijen** [comment]
It was decided that we shouldn't put any effort in supporting SAML 1.1
