### ISSUE TITLE
Fix issue when building for PHP versions 5.3 and 5.4

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#302]
When building in Travis, we are requiring the development dependencies (`--dev`) in order to install *satooshi/php-coveralls*. A recent change in the dependencies definition of this library makes composer install the latest 3.0 branch of the *symfony/** dependencies (composer always tries to install the latest version by default). This branch requires **at least** PHP 5.5.9. Therefore, when building on top of PHP 5.3 or 5.4, build fails.

The problem is skipped by modifying the build script and telling composer to install the lowest version available (`--prefer-lowest`), but this is a hack and should be fixed properly, either by *satooshi/php-coveralls* by specifying different branches supporting both 2.X and 3.0 branches of *symfony/** or by including dependencies ourselves on the original branches.

**Comment by jaimeperez** [comment]
I reported this issue upstream to satooshi/php-coveralls#158, without much collaboration. The problem IMHO is in their composer requirements, but they refused to acknowledge the issue and obviously to offer a fix.

Using `--prefer-lowest` was ok as a temporary fix to have our builds work again, but I think we should get rid of that ASAP. I see three options at this point, assuming satooshi/php-coveralls continues to refuse the problem:

* Specify the conflictive dependencies on our own composer requirements (maybe even modify them on the fly when PHP 5.3 or 5.4 are used), even though we don't really use the _symfony/*_ packages directly, and see if that works.
* Downgrade our dependency on satooshi/php-coveralls to some version prior to the breaking changes. That means no new features or bugfixes.
* Find an alternative to satooshi/php-coveralls and switch to it. Is there an alternative?

@thijskh, @DRvanR, @relaxnow comments? Opinions? I see we are using a quite outdated version in the SAML2 library, 0.6.1. Should I just downgrade to that and forget about this?

**Comment by DRvanR** [comment]
As long as still supporting PHP 5.3 (which will end in the foreseeable future), for [OpenConext-engineblock][3] we defined a [target-platform][2], see [here][1]. This basically instructs composer to pick the latest possible versions of packages, matching all requirements _and that still work on php 5.3.9_. Perhaps something similar could be done here? Alternatively:

>Specify the conflictive dependencies on our own composer requirements

would be the best option imo.

Hope it helps a bit.

[1]: https://github.com/OpenConext/OpenConext-engineblock/blob/c07adf4f4a723f52835d943c5000beb3c510b03e/composer.json#L89-L93
[2]: https://getcomposer.org/doc/06-config.md#platform
[3]: https://github.com/OpenConext/OpenConext-engineblock

**Comment by jaimeperez** [comment]
Problem solved. The issue here was that we are committing the `composer.lock` file, and we were also running `composer install` in the travis configuration, instead of `composer update`. Since _install_ tries to blindly install whatever it is told by `composer.lock`, it was always trying to force some particular versions that didn't work for PHP versions 5.3 and 5.4. Using _update_ forces to update the `composer.lock` file too, and then it just works.

One less thing to care about.
