### ISSUE TITLE
Documenting a new metarefresh capability

### ISSUE THREAD

**Issue by trscavo** [simplesamlphp/simplesamlphp#303]
In section 1.9 (metarefresh), we find:

> Added the possibility to specify which types of entities to load.

Can you elaborate on this, please? (Just a bit more detail and/or clarification would help)

**Comment by jaimeperez** [comment]
Hi @trscavo!

Please, take a look at [the documentation](https://simplesamlphp.org/docs/1.14/simplesamlphp-automated_metadata).
