### ISSUE TITLE
Show Metadata redirect

### ISSUE THREAD

**Issue by MrJootta** [simplesamlphp/simplesamlphp#306]
Hello guy i need your help i have a installation of SSP and im trying to get authentication fro surfconext i think i have everything setup but when i press show metadata he just redirect to the Homepage.
Any tips?
Regards

**Comment by jaimeperez** [comment]
Hi @MrJootta!

This is an issue tracker, not a help forum. Please try to send your question to the [user's mailing list](https://groups.google.com/forum/#!forum/simplesamlphp).

Thanks!
