### ISSUE TITLE
Don't show "no state" error on logout (was #375)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#31]
_From [olavmrk@gmail.com](https://code.google.com/u/olavmrk@gmail.com/) on December 22, 2010 14:03:41_

If the user closes the browser after or during logout, but saves the tabs that the browser has open, the user will receive an error message about missing state information when starting the browser again.

It would be better to just display a "you have been logged out" message in those cases.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=375_

**Comment by bradjones1** [comment]
Can't recreate with these basic instructions, FWIW.

**Comment by tvdijen** [comment]
Cannot reproduce either, and probably not relevant after ~5yrs
