### ISSUE TITLE
[SimpleSamlPHP] Facebook Authentication

### ISSUE THREAD

**Issue by priyaekbote** [simplesamlphp/simplesamlphp#320]
Hi there,

We have integrated a simplesamlphp with authfacebook module.
authfacebook is enabled and we can use it for login.
It returns the data except the facebook email id.

We need the email id used to facebook to make an entry in our custom database.

Could you please help us out to get the email id from facebook in attributes list ?

Thanks.

**Comment by jaimeperez** [comment]
Hi @priyaekbote!

This is a issue tracker, not an user support forum. Can you please send your question to the [mailing list](https://groups.google.com/forum/#!forum/simplesamlphp)?

Thanks!

**Comment by priyaekbote** [comment]
Hi @jaimeperez 

I though it is a issue in the authfacebook module.

Thanks for the help !!
