### ISSUE TITLE
Cannot install module when installing from composer

### ISSUE THREAD

**Issue by akinspe** [simplesamlphp/simplesamlphp#321]
Consider a project that wishes to use simplesamlphp and a module in a project, and install via composer:
```
{
    "require": {
        "simplesamlphp/simplesamlphp": "1.14.0-rc1",
        "simplesamlphp/simplesamlphp-module-examplecomposer": "1.*"
    }
}
```
Because the module is installed with https://github.com/simplesamlphp/composer-module-installer it is installed in /modules but simplesamlphp expects modules to be in vendor/simplesamlphp/simplesamlphp/modules

It is clear that the composer-module-installer expects to be used when simplesamlphp is the root project.

Is there a means to install modules when simplesamlphp is NOT the root project?

**Comment by jaimeperez** [comment]
Hi @akinspe!

I believe you meant the other way around, that is, SimpleSAMLphp expects the modules to be installed in the `modules` directory.

In any case, the module installer does not contemplate this possibility, as we are currently not supporting this way of installing the library. I'll get back to you to see if we can fix this easily.

**Comment by akinspe** [comment]
Thanks for your response! 

I think what I meant was that when you install the library in this manner it would be installed in `/vendor/simplesamlphp/simplesamlphp` and therefore it would expect its modules to be in the `modules` directory relative to that path. 

I imagine that in the meantime we might create an alternative composer installer that still installs in the root `modules` directory, but then symlinks the module into the simplesamlphp modules directory.

Of course, another possibility would be for allowing additional module search directories.

**Comment by jaimeperez** [comment]
Hi again!

[`simplesamlphp/composer-module-installer`](https://github.com/simplesamlphp/composer-module-installer/) [`v1.1.4`](https://github.com/simplesamlphp/composer-module-installer/releases/tag/v1.1.4) should fix this issue (at least it works for me). Provided the module you are trying to install has not a specific and strict requirement for a previous version of the installer, it should just work fine from now on.

Let me know if you still have any problem!

**Comment by akinspe** [comment]
Brilliant. Works just as you'd expect. One thing I would note to future people looking at this: you MUST include simplesamlphp/simplesamlphp as a require in your module's composer.json. Otherwise the installer might install your module first and simplesamlphp might not be present (and then it would fallback to the ./modules path). You would experience this on a project you just cloned prior to installing the defined packages.

Thanks for the quick response and fix!

**Comment by jaimeperez** [comment]
No problem! Glad it worked :smile: 

You are right regarding the order limitation. It kind of makes sense to me to work that way, but I understand other people would think that requiring a module should install SimpleSAMLphp and everything should just work. I can't see a way to solve that, though, so if you have any ideas, they'll be more than welcome :wink:
