### ISSUE TITLE
No interface/function to retrieve error data by "tracking number"

### ISSUE THREAD

**Issue by bradjones1** [simplesamlphp/simplesamlphp#322]
Errors are logged with both a specific error ID and a "tracking number," the latter of which is tied to the session and does not change on repeated errors.

The `error.php` template tells the user, _"If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator..."_

There doesn't appear to be a function or admin UI page to retrieve saved error data by tracking number, which makes me wonder if I'm missing something obvious or the expectation is that an admin would search the session tables for the logged ID or "number."

In the case of memcache storage, this is easier said that done. Any thoughts on the admin side of this process?

**Comment by jaimeperez** [comment]
Hi @bradjones1!

The [logpeek module](https://github.com/simplesamlphp/simplesamlphp-module-logpeek) was created with that purpose.

**Comment by bradjones1** [comment]
Thanks. For others who may be in a similar boat, if you log to something other than a flat file (e.g., syslog) this isn't the module you're looking for. In my case I hooked into the custom error show function capability already in simplesamlphp, and logged some additional info. See this Gist - https://gist.github.com/bradjones1/f8c16d640ca8d1f2d559 - though it does depend on the changes I've proposed to Syslog logging in https://github.com/simplesamlphp/simplesamlphp/pull/311

**Comment by jaimeperez** [comment]
Yes, that's true.

One of the things that we would like to accomplish with 2.0 is full separation of the user and the admin web interface. This would be the kind of thing that I would definitely like to see in the admin interface. The idea would then be to have some interface implemented by logger modules, that can be used transparently by the web interface to look for track IDs in the logs. It would just need to instantiate the right logger as per configuration, then call the appropriate method.

Would you be able to help with something like that?

**Comment by bradjones1** [comment]
I'm happy to help, though I suppose not every log interface will have a retrieval mechanism built in to the UI. Case in point, syslog, which I'm using to ship off log messages to a log aggregation service. Have you given some thought to adopting PSR-3 logging interfaces? https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-3-logger-interface.md

**Comment by jaimeperez** [comment]
Hi!

I didn't have a look at PSR-3 until now. I think it should be fairly easy to make our logger PSR-3 compliant since most of it is already in place. It's probably not a bad idea to stop using static methods and get all the classes producing logs to implement the `Psr\Log\LoggerAwareInterface`. That would notably simplify unit testing in many cases, and would also help the SAML2 library, I think.

I'll open a new issue for this, setting 2.0 as milestone.
