### ISSUE TITLE
initMDSPdo.php does not take into account SIMPLESAMLPHP_CONFIG_DIR

### ISSUE THREAD

**Issue by akinspe** [simplesamlphp/simplesamlphp#326]
initMDSPdo.php should utilize SimpleSAML\Utils\Config::getConfigDir()

**Comment by jaimeperez** [comment]
Thijs, I understand you reopened the issue to mark this as needed for **1.14.0**, right?

In that case, I've just cherry picked the fix, so I guess we can close it.

**Comment by thijskh** [comment]
Yes. Just a reminder that this needed to be done.
