### ISSUE TITLE
Auth Proc Filter for converting casing of attribute

### ISSUE THREAD

**Issue by jornane** [simplesamlphp/simplesamlphp#328]
[My user has an IdP that provides usernames in upper case](https://github.com/jornane/mwSimpleSamlAuth/issues/27) for some reason. Assuming that it's not feasible to ask the IdP to change that, I think it's SimpleSamlPHP's job to fix this on the SP-end. However, it looks like the [core:authproc_attributealter](https://simplesamlphp.org/docs/stable/core:authproc_attributealter) module is not able to do this at this time.

For the meantime, I have instructed the user to use [core:authproc_php](https://simplesamlphp.org/docs/stable/core:authproc_php) instead.

**Comment by jaimeperez** [comment]
This is a corner-case, more intended to solve issues that other parties are having rather than addressing a legitimate, wide need. In any case, it would nice to have some generic capabilities to fix things like this in _attributealter_, so I'm keeping this open with low priority.

**Comment by pradtke** [comment]
@jaimeperez Maybe something like an option `'transformFunction' => 'strtolower'` and then the authproc filter would call `array_map($transformFunction, $attributes[$subject])`.  Though I'm not sure if using a transformation function should make the pattern part optional. e.g. you can do either or both.    Perhaps it just makes AttributeAlter too complicated, and its better to just have an `AttributeTransform` filter.

**Comment by tvdijen** [comment]
I don't think we should be manipulating usernames at all ..  our backend authstore may very well ve case sensitive

**Comment by pradtke** [comment]
I agree that changing username is likely a bad idea.  Our use case for wanting to change case is that group membership were `prefix-Student`, `prefix-Staff`, etc. We removed the `prefix-` with `attributealter` but still need to lower case the result since `eduPersonAffiliation` wants student, staff, etc. Anyhow, it's easy enough to use the `authproc_php` to lower case things

**Comment by tvdijen** [comment]
Closing this one, as I feel we really shouldn't be manipulating anything.. Garbage in = garbage out.
I the edge-cases where it is still desired the core:PHP authproc can be used
