### ISSUE TITLE
Doc Block Datatypes (was #458)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#33]
_From [pan...@traileyes.com](https://code.google.com/u/115787459646554091505/) on November 23, 2011 17:46:26_

Mark this one as low priority. Hope I'm not bugging you too much, I just like to help open source projects that I use, return the favor. :)

I use a IDE product called phpStorm, which has deep code insight. As I develop custom modules, the IDE reports many errors of wrong data types. Same happens when I look at SimpleSAMLphp files. The issue is missing datatypes in the doc block @param lines. Would you care if I go through and fix these with a patch? It would be helpful so I don't have to fix them when upgrading SimpleSAMLphp. Just want to check before putting the effort into such a big task. Thanks http://manual.phpdoc.org/HTMLSmartyConverter/HandS/phpDocumentor/tutorial_tags.param.pkg.html

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=458_

**Comment by jaimeperez** [comment]
@Panman8201, did you have time to take a look at this? I use phpStorm myself and I see the doc datatypes are wrongly reported still in the last version, but it would be nice to know if you progressed with this...

**Comment by Panman8201** [comment]
@jaimeperez No, I never did go through everything to fix it. I thought phpStorm was going to make an option to enable/disable this type of format. You might want to look through the preferences. I don't have the specific issue number that I talked about. Sorry

**Comment by thijskh** [comment]
Much progress already made on this. Need to fix individually where's it's still wrong; this generic issue is done/not actionable.
