### ISSUE TITLE
Exception handler not compatible with PHP7

### ISSUE THREAD

**Issue by moffe42** [simplesamlphp/simplesamlphp#330]
The exception handler function is potential not compatible with PHP 7.

See http://php.net/manual/en/migration70.incompatible.php

**Comment by bradjones1** [comment]
This doesn't appear to be an issue any longer with the refactoring going on in the master branch, but [here is a patch](https://github.com/simplesamlphp/simplesamlphp/files/278540/SSP-typing.patch.txt) against 1.14.3 which was enough to get me seeing Exceptions again.

**Comment by jaimeperez** [comment]
Thanks guys! It should be solved now. There's no problem at all with the `SimpleSAML_Error_Exception` class extending the generic `Exception`, and expecting `Exception` objects as parameters to its methods. After all, it's us using this particular exception. The only thing which we needed to address is the fact that the error handler will now also get `Error` objects thrown by internal functions, and therefore we can no longer assume the parameter it receives will be of type `Exception`.
