### ISSUE TITLE
Simplesamlphp facebook

### ISSUE THREAD

**Issue by cmesah** [simplesamlphp/simplesamlphp#338]
Hi There

I have a problem beetwen SAML and fecabook , 
Error getting user profile

when I use https in my IDP the autentication does not work, but with http everything works very well

Please,  can anybody help me?

Thanks

**Comment by jaimeperez** [comment]
Hi @cmesah!

This is an issue tracker, not a support forum. You may have better help if you ask in the [mailing list](https://groups.google.com/forum/#!forum/simplesamlphp).
