### ISSUE TITLE
[patch] rewrite sspmod_sqlauth_Auth_Source_SQL class to be extendible (was #462)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#34]
_From [gordonfr...@googlemail.com](https://code.google.com/u/101602539502063056770/) on December 07, 2011 12:37:41_

What steps will reproduce the problem? 1. I will extends the sspmod_sqlauth_Auth_Source_SQL class and use my own password check method What version of the product are you using? On what operating system? trunk Please provide any additional information below. At the moment it is not possible to extends the sspmod_sqlauth_Auth_Source_SQL class and override only one method to validate the password.
So i have rewrite the class. It has a little bc break you must change the sql query it is documented in the docs see patch only remove the password from where and add it to the selected fields.

No it is possible to extends the class and only override the checkPassword() method.

Also it has now a filterAttributes method.

**Attachment:** [sqlauth_extenable.patch](http://code.google.com/p/simplesamlphp/issues/detail?id=462)

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=462_

**Comment by tvdijen** [comment]
I don't see why this class cannot be overridden when additional functionality is wanted..
