### ISSUE TITLE
AllowCreate hardcoded when building request

### ISSUE THREAD

**Issue by AngelAlvarado** [simplesamlphp/simplesamlphp#346]
This is for the version 1.13. Reference code Message.php (simplesamlphp-1.13/modules/saml/lib/Message.php)  lines 399-410. 

I'm setting a different NameIdPolicy in the configuration of my SP which is working perfectly. However, I noticed that there's no way to set the 'AllowCreate' property to FALSE. 

I'm attaching a diff which will let  users set it in the authsources.php as follows: 

> 
'idp-dev' => [
   'saml:SP',
   'NameIDPolicy' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
   'AllowCreate' => FALSE,
   ...
],

[message.php.diff.zip](https://github.com/simplesamlphp/simplesamlphp/files/168103/message.php.diff.zip)

I'll create a PR if the above makes sense. Prolly, the key name should be something like AllowCreatePolicy?

**Comment by jaimeperez** [comment]
I'm closing this issue since you submitted a PR already.
