### ISSUE TITLE
Error running bin/pw_gen.php on current master

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#348]
Something I ran into on the latest master.. 1.14.2 is fine..

[simplesamlphp-master]$ bin/pwgen.php
PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to load Composer autoloader' in /tmp/simplesamlphp-master/lib/_autoload.php:18
Stack trace:
#0 /tmp/simplesamlphp-master/bin/pwgen.php(13): require_once()
#1 {main}
  thrown in /tmp/simplesamlphp-master/lib/_autoload.php on line 18

**Comment by jaimeperez** [comment]
Hi Tim!

I can't reproduce the issue with master. Are you sure everything is fine with your composer installation? Remember that if you just checked out the repository, you need to run composer first to download everything and generate the autoloader...

**Comment by tvdijen** [comment]
Ah, I didn't know that, sorry!
That kinda sucks though, because I have no internet connection on the machines I work on...
Oh well, back to the 1.14.2 release then!

**Comment by jaimeperez** [comment]
Uhm, just out of curiosity... How do you checkout the repository in those machines then?

**Comment by tvdijen** [comment]
GitHub.com comes with a nice 'Download ZIP' button and from there I transfer it from the client-machine I work on to the isolated machine using SCP.

**Comment by jaimeperez** [comment]
Ah, I see! Quite unfortunate then :disappointed:

**Comment by tvdijen** [comment]
Let's just say it's one of the many joys of working in secretive governmental environments...
You'd be surprised by the number of firewalls and web-proxy's I have to deal with :')

**Comment by thijskh** [comment]
So what could work for you is a simple shell-script that does: unzip; composer install; zip?
