### ISSUE TITLE
Support for conditional GET in metadata aggregator (was #474)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#35]
_From [vis...@terena.org](https://code.google.com/u/107089553467553648499/) on February 08, 2012 23:23:03_

Add support for conditional HTTP GET requests in the aggregator module. This would enable clients to efficiently poll for aggregated metadata.
Could be implemented using Last-Modified/If-Modified-Since and ETag/If-None-Match headers.
The aggregator2 module seems to already have some caching logic onboard, so it makes sense to implement it there.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=474_

**Comment by jaimeperez** [comment]
The `aggregator` module is quite dead in favour of *aggregator2*, so this should be a feature of the latter, indeed. In any case, this issue should be moved to the [*aggregator2* issue tracker](https://github.com/simplesamlphp/simplesamlphp-module-aggregator2/issues).

**Comment by jaimeperez** [comment]
Migrated to simplesamlphp/simplesamlphp-module-aggregator2#1.
