### ISSUE TITLE
Update authYubiKey library to the latest version. (was #479)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#36]
_From [olavmrk@gmail.com](https://code.google.com/u/olavmrk@gmail.com/) on February 16, 2012 08:14:20_

We should update the library in modules/authYubiKey/libextinc to the latest version from http://code.google.com/p/php-yubico/

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=479_

**Comment by tvdijen** [comment]
This composer-installable library may be a good replacement:
https://github.com/enygma/yubikey

**Comment by tvdijen** [comment]
This issue was moved to the external repository for the authyubikey module
