### ISSUE TITLE
Specifying a faulty store.type in config.php causes unknown fatal error

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#369]
I accidentally defined store.type as 'memcachen' (typo) and ran into a HTTP/500 error.

Apache logs only gave me as much as:
PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0

Apparently the 'default' case in /lib/SimpleSAML/Store.php isn't doing what it should, but I'm not really sure what It's supposed to do, let alone fix it.. Perhaps it should just abort and log an error in the simplesamlphp.log

**Comment by jaimeperez** [comment]
Thanks for telling us about this @tvdijen!

This was **perfect** timing, actually, as I just committed some new exceptions to handle configuration errors, one of them for critical errors that we cannot recover from (like this one). I've just fixed the issue by throwing a critical exception and changing the offending option to be `phpsession`, which will always be available and working with defaults.
