### ISSUE TITLE
metarefresh config requires validateFingerprint option instead of certificate path (was #494)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#37]
_From [trsc...@gmail.com](https://code.google.com/u/106030987824749427349/) on May 09, 2012 14:25:59_

To verify the signature on the metadata, the validateFingerprint option must be configured in the metarefresh module. Thus the configuration must be changed whenever the federation operator's verification certificate changes EVEN IF THE KEY BOUND TO THE CERTIFICATE DOES NOT CHANGE. An organization that owns dozens of entities would have to touch all of those entities in response to such a certificate renewal.

In the InCommon Federation, this is a regular occurrence. The FedOp has used the same private signing key for over 8 years, but the verification certificate containing the corresponding public key has been renewed often. The next such transition will occur on May 14, 2012. All simpleSAMLphp deployments in the InCommon Federation must replace the "old" fingerprint with the "new" fingerprint sometime between Friday, May 11 (after refreshing metadata) and Monday, May 14 (before refreshing metadata), otherwise their metadata refresh processes will break.

The best solution is to make the verification certificate available to simpleSAMLphp such that the key can be extracted and used to verify the signature on the metadata. This is what Shibboleth does in fact. All Shibboleth deployments are immune to this bug.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=494_

**Comment by jaimeperez** [comment]
This is no longer an issue since 95f0487.
