### ISSUE TITLE
How to add default mail headers: for example Return-Path

### ISSUE THREAD

**Issue by dbollaer** [simplesamlphp/simplesamlphp#372]
We would like to add additional headers to the mails we send with simplesamlphp, to handle our bounce mails more effectively.

We are using the selfregister module and we are sending lots of mails using simplesamlphp.

I don't mind submitting a pull request myself. 
I was thinking of adding an additional field to the constructor, headers=[].
- adding a property in the config.php: additionalMailHeaders => ['Return-Path' => 'bounces@client.com']

Feedback more than welcome.

**Comment by thijskh** [comment]
Return-Path isn't an actual mail header by itself: it contains a copy of the value of the SMTP envelope FROM. So you'd want to have a way to set the envelope-from I presume?

**Comment by dbollaer** [comment]
You are correct.

**Comment by jaimeperez** [comment]
Hi!

As always, PRs are more than welcome :-)

However, bear one thing in mind: not all mails should be treated the same. For instance, when someone reports an issue, their mail (if specified) is used as the from address, while for mails sent to the user from __selfregister__ or other modules should probably be sent from a generic, customizable address. So the sender of each mail should be handled differently on a per-use basis.

If you have a real need for it and you are willing to submit a pull request that we can discuss, that'll be great 😄

**Comment by tvdijen** [comment]
Now that we use PHPmailer for sending emails, your life may have become much much easier @dbollaer !
https://github.com/simplesamlphp/simplesamlphp/blob/cf467cfbf9e088c9851ff9f129c2aae5078f4758/lib/SimpleSAML/Utils/EMail.php#L120

**Comment by dbollaer** [comment]
@tvdijen thank you for informing me :)
