### ISSUE TITLE
Error validating SubjectConfirmation in Assertion:

### ISSUE THREAD

**Issue by danharper83** [simplesamlphp/simplesamlphp#375]
I can't get to the bottom of the following issue.

```
Caused by: SimpleSAML_Error_Exception: Error validating SubjectConfirmation in Assertion: Recipient in SubjectConfirmationData does not match the current URL. Recipient is 
'http://livehappierstg.prod.acquia-sites.com/', 
current URL is 'http://livehappierstg.prod.acquia-sites.com/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp'.
```

It seems that in the following xml the recipient seems to take on the entity id in my authsources config file but the idp is redirecting to this url 

> http://livehappierstg.prod.acquia-sites.com/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp

```
      <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml:SubjectConfirmationData InResponseTo="_805030fbe28127d00ec24d724ea0dcfe2a5478010e" NotOnOrAfter="2016-04-22T14:21:08.796Z" Recipient="http://livehappierstg.prod.acquia-sites.com/"/>
      </saml:SubjectConfirmation>
```
If I leave the entity ID null then the recipient ends up being 

> http://livehappierstg.prod.acquia-sites.com/simplesaml/module.php/saml/sp/metadata.php/default-sp

Apologies if this support and I'm posting in the wrong place.

**Comment by jaimeperez** [comment]
Hi @danharper83!

This looks like the IdP you are trying to connect to is using your `entityID` in the `Recipient` element of the `SubjectConfirmation`. However, that's completely incorrect according to the specification:

>554 *  The bearer `<SubjectConfirmation>` element described above MUST contain a
>555    `<SubjectConfirmationData>` element that contains a `Recipient` attribute containing the service
>556    provider's assertion consumer service URL and a `NotOnOrAfter` attribute that limits the window
>557    during which the assertion can be delivered. It MAY contain an `Address` attribute limiting the client
>558    address from which the assertion can be delivered. It MUST NOT contain a `NotBefore` attribute. If
>559    the containing message is in response to an `<AuthnRequest>`, then the `InResponseTo` attribute
>560    MUST match the request's ID.

I'm afraid SimpleSAMLphp is just following the specification here, so I'm closing the issue. You will need to talk to the operators of the IdP to get them fix their deployment.
