### ISSUE TITLE
Duplicate lines of code in handleAuthenticationRequest

### ISSUE THREAD

**Issue by adam-rehin** [simplesamlphp/simplesamlphp#384]
In **handleAuthenticationRequest** in simplesamlphp/lib/SimpleSAML/IdP.php [https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/IdP.php](url)

Duplicate code on lines 390-393 see below - did someone mean to put in some other comparison?

```
        if (isset($state['SPMetadata']['entityid'])) {
            $spEntityId = $state['SPMetadata']['entityid'];
        } elseif (isset($state['SPMetadata']['entityID'])) {
            $spEntityId = $state['SPMetadata']['entityID'];
        } else {


```

**Comment by trscavo** [comment]
Doesn't look like duplicate code. It's checking `'entityid'` vs. `'entityID'`, which is case sensitive.

**Comment by adam-rehin** [comment]
how embarrassing I missed that...
