### ISSUE TITLE
Composer module install broken?

### ISSUE THREAD

**Issue by lonoak** [simplesamlphp/simplesamlphp#388]
Hi,

   I'm having problems installing our 'idp installer' module that in the past was working fine. The module now cries:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package satooshi/php-coveralls (locked at 0.8.x-dev, required as ^1.0) exists as satooshi/php-coveralls[0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 1.0.x-dev, dev-master, 2.0.x-dev, v0.6.0, v0.6.1, v0.7.0, v0.7.1, v1.0.0, v1.0.1] but these are rejected by your constraint.

Installation failed, reverting ./composer.json to its original content.

And the dependency seems to come –I believe – from https://github.com/simplesamlphp/simplesamlphp/blob/master/composer.json#L37

I'm not completely sure why it happens, I think "^1.0" as a "require-dev" should match "1.0.x-dev", if I'm not wrong... but in any case my module dos not require satooshi/php-coveralls, only "composer-module-installer": "~1.0":
https://github.com/rediris-es/simplesamlphp-module-idpinstaller/blob/master/composer.json#L18

How could I fix this error?

Thanks in advance!

**Comment by thijskh** [comment]
Which version of simpleSAMLphp are you using? A clean 1.14.3 tarball does not reproduce this behaviour for me, nor does git master.

**Comment by lonoak** [comment]
Hi Thijs, 

  not a tarball... installing SSp using composer (also version 1.14.3).

I use this script to run all the install process:

`curl -sS https://www.rediris.es/sir2/IdP/install/?v1 | sh -x`

(some Spanish messages in between, ignore them)

In short, SimpleSAMLphp is installed with:

`php composer.phar require simplesamlphp/simplesamlphp:1.14.3 --update-no-dev`

And the IdP installer module with:

`php composer.phar require --update-no-dev rediris-es/simplesamlphp-module-idpinstaller:1.0.5`

My environment is RedHat Enterprise 7, w/ PHP 5.6.21 installed from Remi repository.

**Comment by lonoak** [comment]
After following hints by @jaimeperez, the problem was located in our install script, which prior to call the idp installer module removes all the dependences computed until that moment. It has been fixed in the install script, and is now working as expected.

This issue can be closed. Thanks!
