### ISSUE TITLE
Attribute values are not sorted when giving consent (was #505)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#39]
_From [j...@wayf.dk](https://code.google.com/u/112409101112243306120/) on July 04, 2012 14:36:49_

The attribute values are not sorted before the attribute hash is calculated in the consent module.

If you are using the attribute values in consent, that the attribute hash will change if the order of the attribute values change but the actual values are the same.

The values should be sorted, so the attribute hash persists even if the order of the attribute values change.

The following will fis this:

```
Index: modules/consent/lib/Auth/Process/Consent.php
===================================================================
--- modules/consent/lib/Auth/Process/Consent.php    ( revision 3128 )
+++ modules/consent/lib/Auth/Process/Consent.php    (working copy)
@@ -309,6 +309,9 @@
     {
         $hashBase = null;  
         if ($includeValues) {
+            foreach ($attributes AS &$values) {
+                sort($values);
+            }
             ksort($attributes);
             $hashBase = serialize($attributes);
         } else {
```

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=505_

**Comment by thijskh** [comment]
@moffe42: Will you create a PR for this?

**Comment by moffe42** [comment]
PR is waiting to be merged
