### ISSUE TITLE
 Undefined index: ExpectedIssuer in saml2-acs.php

### ISSUE THREAD

**Issue by a-fro** [simplesamlphp/simplesamlphp#393]
in /var/www/simplesamlphp-1.14.3/modules/saml/www/sp/saml2-acs.php

The strange thing is, if I test authentication sources in the admin interface, I get the correct attributes returned. Then, I'm able to log in without the above error. However, once I log out and try to log back in, I get the ExpectedIssuer error again. I'm then unable to log in again until I test the auth source another time. 

Here is a list of the keys in `$state`:

```
'SimpleSAML_Auth_State.restartURL',
'SimpleSAML_Auth_Default.id',
'SimpleSAML_Auth_Default.Return',
'SimpleSAML_Auth_Default.ErrorURL',
'LoginCompletedHandler',
'LogoutCallback',
'saml:sp',
'SimpleSAML_Auth_State.id',
'SimpleSAML_Auth_State.stage',
```

**Comment by jaimeperez** [comment]
Hi @a-fro!

I'm unable to reproduce the issue, even though it should be pretty straightforward as you are describing it. Also, I don't think this is causing the login failure, since this is just a warning. What does your log says? What error message do you get in your browser, if you get one? Is there anything in the error log of your server?

**Comment by a-fro** [comment]
Thanks for your response! 

The error message in the browser is:

```
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION

Backtrace:
0 /var/www/simplesamlphp-1.14.3/www/module.php:170 (N/A)
Caused by: SimpleSAML_Error_Exception: The issuer of the response does not match to the identity provider we sent the request to.
Backtrace:
1 /var/www/simplesamlphp-1.14.3/modules/saml/www/sp/saml2-acs.php:98 (require)
0 /var/www/-1.14.3/www/module.php:127 (N/A)

```

I'm pretty sure that error is causing the login failure, as the code reads:

```
if ($state['ExpectedIssuer'] !== $idp) {
  $idpMetadata = $source->getIdPMetadata($idp);
  $idplist = $idpMetadata->getArrayize('IDPList', array());
  if (!in_array($state['ExpectedIssuer'], $idplist)) {
    throw new SimpleSAML_Error_Exception(
        'The issuer of the response does not match to the identity provider we sent the request to.'
    );
 }
}
```

Given that there is no `ExpectedIssuer` key in the $states array, that exception gets thrown and the login fails, from what I can tell. I'll look into the logs.

**Comment by jaimeperez** [comment]
Hi again!

If the `ExpectedIssuer` is not set, that will clearly lead to an error as _void_ won't match with the issuer of the SAML assertion. Hence the error message you see in your browser. However, this should never happen as the `ExpectedIssuer` should always be set as the user picks an IdP.

Can you please describe thoroughly your setup, and how are you testing this, step by step?

**Comment by a-fro** [comment]
Thanks! We've been using simplesamlphp with shibboleth for ~3 years now. I've had issues in the past trying to upgrade, so we've been pinned to v 1.10.0. I finally had some time to test and troubleshoot the updgrade this week, which led to this post. 

It's configured to use saml20-idp-remote for the metadata. I can test the response using the admin interface, "Test configured authentication sources", which works perfectly. As I described previously, _once_ I've tested the configuration, I'm able to log in to our Drupal implementation, which is paired with the simplesamlphp_auth module. However, once I log out, I am unable to log in again until I test the configured auth sources again. 

The error message led me to the code I mentioned above, where I added some php debugging to see what was stored in the $state array. Version 1.10.0 still works fine for us, but I'd still love to upgrade.

**Comment by jaimeperez** [comment]
Hi again @a-fro!

I've tried again, this time making a simple script emulating what the Drupal plugin should be doing (basically, instantiate `SimpleSAML_Auth_Simple` and call `requireAuth()`), and followed your indications. I logged first in the SimpleSAMLphp web interface (test auth sources -> SAML SP), then went to that script. Everything fine. Then I logged out from the web interface (where I tested authentication), go back to the script, and authentication is triggered again and I'm redirected to the IdP. After logging in, I'm back at the script, and everything works fine.

So unless I'm missing something, this must be a configuration issue or some kind of issue with the Drupal plugin, or maybe even related to PHP 7.

Could you paste your Drupal plugin configuration, your SimpleSAMLphp configuration (authsources and relevant parts of `config.php`) and remote IdP metadata?

**Comment by jaimeperez** [comment]
Hi @a-fro!

Just a quick question. What metadata storage source are you using? Are you using anything different than the plain files in the `metadata` directory?

**Comment by a-fro** [comment]
I'm using a sqlite file in the /tmp folder

**Comment by a-fro** [comment]
Wait, that's for the session store. For the storage source, I have 

```
'metadata.sources' => array(
        array('type' => 'flatfile'),
    ),
```

**Comment by jaimeperez** [comment]
Then I must admit I'm completely lost. I discovered an issue with the PDO and MDQ metadata storage handlers, which don't automatically fill in a key in the metadata containing the entity ID of the IdP. Still, this could lead to the `ExpectedIssuer` being empty in the state if it was unset in the original metadata, but it would be set anyway.

Could you please increase the log level to `SimpleSAML_Logger::DEBUG`, activate debugging (`debug` and `logging.level` configuration options in `config/config.php`), and paste the logs here, both for a login that works when testing in the web interface, and for one that fails triggered from Drupal?

**Comment by a-fro** [comment]
Here's the most relevant portion of the failed log: 

```
Jul  6 19:20:24 ilr-website simplesamlphp[3948]: 7 [250b2e3bab] Session: Valid session found with 'cornell'.
Jul  6 19:20:24 ilr-website simplesamlphp[3948]: message repeated 3 times: [ 7 [250b2e3bab] Session: Valid session found with 'cornell'.]
Jul  6 19:20:24 ilr-website simplesamlphp[3948]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/dictionaries/status]
Jul  6 19:20:24 ilr-website simplesamlphp[3948]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/dictionaries/attributes]
Jul  6 19:20:57 ilr-website simplesamlphp[3961]: 7 [250b2e3bab] Session: Valid session found with 'cornell'.
Jul  6 19:20:57 ilr-website simplesamlphp[3961]: 7 [250b2e3bab] Session: doLogout('cornell')
Jul  6 19:20:57 ilr-website simplesamlphp[3961]: 7 [250b2e3bab] Session: 'cornell' not valid because we are not authenticated.
Jul  6 19:20:57 ilr-website simplesamlphp[3961]: 7 [250b2e3bab] Saved state: '_5410f5dedf6d9993d4bc0cd46d1fb44e6a15516a17'
Jul  6 19:20:57 ilr-website simplesamlphp[3961]: 6 [250b2e3bab] No logout endpoint for IdP 'https://test-idp.cornell.edu/idp/shibboleth'.
Jul  6 19:20:57 ilr-website simplesamlphp[3949]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/dictionaries/logout]
Jul  6 19:21:00 ilr-website simplesamlphp[3947]: 7 [250b2e3bab] Session: 'admin' not valid because we are not authenticated.
Jul  6 19:21:00 ilr-website simplesamlphp[3947]: 7 [250b2e3bab] Session: 'login-admin' not valid because we are not authenticated.
Jul  6 19:21:00 ilr-website simplesamlphp[3947]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/modules/core/dictionaries/frontpage]
Jul  6 19:21:00 ilr-website simplesamlphp[3947]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/modules/core/dictionaries/frontpage]
Jul  6 19:21:02 ilr-website simplesamlphp[3948]: 7 [250b2e3bab] Session: 'admin' not valid because we are not authenticated.
Jul  6 19:21:02 ilr-website simplesamlphp[3948]: 7 [250b2e3bab] Session: 'login-admin' not valid because we are not authenticated.
Jul  6 19:21:02 ilr-website simplesamlphp[3948]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/modules/core/dictionaries/frontpage]
Jul  6 19:21:02 ilr-website simplesamlphp[3948]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/modules/core/dictionaries/frontpage]
Jul  6 19:22:22 ilr-website drupal: http://www.ilr-website.dev|1467832942|user|192.168.88.1|http://www.ilr-website.dev/user/logout|http://www.ilr-website.dev/user|26||Session closed for Aaron Thomas Froehlich.
Jul  6 19:22:22 ilr-website drupal: http://www.ilr-website.dev|1467832942|php|192.168.88.1|http://www.ilr-website.dev/user/logout|http://www.ilr-website.dev/user|0||Warning: session_destroy(): Session callback expects true/false return value in user_logout() (line 178 of /var/www/ilr-website/docroot/modules/user/user.pages.inc).
Jul  6 19:22:22 ilr-website drupal: http://www.ilr-website.dev|1467832942|php|192.168.88.1|http://www.ilr-website.dev/user/logout|http://www.ilr-website.dev/user|0||Warning: session_destroy(): Session object destruction failed in user_logout() (line 178 of /var/www/ilr-website/docroot/modules/user/user.pages.inc).
Jul  6 19:22:32 ilr-website drupal: http://www.ilr-website.dev|1467832952|php|192.168.88.1|http://www.ilr-website.dev/|http://www.ilr-website.dev/user|0||Warning: session_destroy(): Session callback expects true/false return value in drupal_session_commit() (line 314 of /var/www/ilr-website/docroot/includes/session.inc).
Jul  6 19:22:32 ilr-website drupal: http://www.ilr-website.dev|1467832952|php|192.168.88.1|http://www.ilr-website.dev/|http://www.ilr-website.dev/user|0||Warning: session_destroy(): Session object destruction failed in drupal_session_commit() (line 314 of /var/www/ilr-website/docroot/includes/session.inc).
Jul  6 19:23:14 ilr-website simplesamlphp[3965]: 7 [250b2e3bab] Loading state: '_5391a96d60991645bb3e458c2d8752e39f5b67293b'
Jul  6 19:23:14 ilr-website simplesamlphp[3965]: 3 [250b2e3bab] SimpleSAML_Error_Assertion: Assertion failed: 'array_key_exists("ExpectedIssuer", $state)'
```

And here is the successful login:

```
Jul  6 19:52:58 ilr-website simplesamlphp[3964]: 7 [250b2e3bab] Session: Valid session found with 'cornell'.
Jul  6 19:52:58 ilr-website simplesamlphp[3964]: message repeated 3 times: [ 7 [250b2e3bab] Session: Valid session found with 'cornell'.]
Jul  6 19:52:58 ilr-website simplesamlphp[3964]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/dictionaries/status]
Jul  6 19:52:58 ilr-website simplesamlphp[3964]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/dictionaries/attributes]
```

**Comment by a-fro** [comment]
Then, I can login using Drupal, and I get:

```
Jul  6 19:52:58 ilr-website simplesamlphp[3964]: 7 [250b2e3bab] Session: Valid session found with 'cornell'.
Jul  6 19:52:58 ilr-website simplesamlphp[3964]: message repeated 3 times: [ 7 [250b2e3bab] Session: Valid session found with 'cornell'.]
Jul  6 19:52:58 ilr-website simplesamlphp[3964]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/dictionaries/status]
Jul  6 19:52:58 ilr-website simplesamlphp[3964]: 7 [250b2e3bab] Template: Reading [/var/www/ilr-website/simplesamlphp-1.14.3/dictionaries/attributes]
Jul  6 19:56:46 ilr-website drupal: http://www.ilr-website.dev|1467835006|simplesamlphp|192.168.88.1|http://www.ilr-website.dev/saml_login|http://www.ilr-website.dev/user|0||_simplesamlphp_auth_get_authname: Valid local session exist
Jul  6 19:56:46 ilr-website drupal: http://www.ilr-website.dev|1467835006|simplesamlphp|192.168.88.1|http://www.ilr-website.dev/saml_login|http://www.ilr-website.dev/user|0||Authname is [atf46] userid is [0]
Jul  6 19:56:46 ilr-website drupal: http://www.ilr-website.dev|1467835006|simplesamlphp|192.168.88.1|http://www.ilr-website.dev/saml_login|http://www.ilr-website.dev/user|0||Load user [atf46]
Jul  6 19:56:46 ilr-website drupal: http://www.ilr-website.dev|1467835006|user|192.168.88.1|http://www.ilr-website.dev/saml_login|http://www.ilr-website.dev/user|26||Session opened for Aaron Thomas Froehlich.
```

That seems like useful info!

**Comment by jaimeperez** [comment]
Hi again!

First, I would recommend you to send SimpleSAMLphp logs to its own file. Though I have to admit it is handy in this case. I don't see much information there, and I'm definitely missing all the debugging information (redirections, SAML messages sent and received, etc). Did you turn it on?

In any case, there's something in the log that gave me a clue. Are you using PHP sessions both in Drupal and SimpleSAMLphp? In that case, did you make sure to configure them properly so that they don't clash with each other? The version of SimpleSAMLphp you are using (1.14.3) should allow you without problem to have both sessions coexist, but it might be that the Drupal plugin needs modifications. In any case, the fastest approach would be to setup a memcache server and use it as the session storage for SimpleSAMLphp. If the problem disappears, then you are certain that the root of your trouble is SSP's and Drupal sessions clashing.

This would also make sense, since every time you ask for authentication the SAML SP class will record the `ExpectedIssuer` in the session state, so the only way for it to vanish like that would be that there's other code messing around with the session.

**Comment by a-fro** [comment]
Hi Jaime, thanks for all your help! I was able to track down the problem. It turned out to be a variable setting in the Drupal simplesamlphp_auth module. I was pointing to the old 1.10.0 path to the library, rather than the newer 1.14.3 version.  I didn't dig through the code to isolate the exact issue, but I'm guessing that the storage layer was looking for a session that didn't exist, since it was created by a different version of simplesamlphp. Basically, the Drupal module bootstraps the specified library and passes the process off to simplesamlphp. However, upon returning (and bypassing Drupal, therefore loading the 1.14.3 version), it seems like there was a session mismatch that triggered the logout and failure. Thanks again! Happy to finally get an upgrade working.

**Comment by jaimeperez** [comment]
That's great! Congratulations, and thanks for sharing the good news. I'm glad you managed to solve it 😄
