### ISSUE TITLE
SAML2.0 logout throws SimpleSAML_Error_NoState

### ISSUE THREAD

**Issue by lehmayr** [simplesamlphp/simplesamlphp#402]
I'm doing a SP and an IdP on localhost. Works fine - but when I call SimpleSAML_Auth_Simple::logout(['ReturnTo' => 'http://...']) I get a NoState exception from lib\SimpleSAML\Auth\State.php:263 after the redirect. I "fixed" this by changing modules\saml\lib\Auth\Source\SP.php:481 to use $state['ReturnTo'] instead of $id - but since I manually pass the 'ReturnTo' parameter (i.e. it's not there by default) I'm not really sure that's how it's supposed to work... so is this just wrong configuration, usage or a real error?

simplesamlphp v1.14.3
saml2 v1.9

authsources:

    'sp' => array(
        'saml:SP',
        'idp' => 'https://localhost/simplesaml/saml2/idp/metadata.php',
        'privatekey' => 'saml.key',
        'certificate' => 'saml.crt',
    ),
    'idp' => array(
        'sqlauth:SQL',
         ...
    ),

saml20-idp-remote

    $metadata['https://localhost/simplesaml/saml2/idp/metadata.php'] = array (
      'metadata-set' => 'saml20-idp-remote',
      'entityid' => 'https://localhost/simplesaml/saml2/idp/metadata.php',
      'SingleSignOnService' => 
      array (
        0 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
          'Location' => 'https://localhost/simplesaml/saml2/idp/SSOService.php',
        ),
      ),
      'SingleLogoutService' => 
      array (
        0 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
          'Location' => 'https://localhost/simplesaml/saml2/idp/SingleLogoutService.php',
        ),
      ),
      'certData' => '...',
      'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
    );

saml20-sp-remote

    $metadata['https://localhost/'] = array(
        'AssertionConsumerService' => 'https://localhost/simplesaml/module.php/saml/sp/saml2-acs.php/sp',
        'SingleLogoutService'      => 'https://localhost/simplesaml/module.php/saml/sp/saml2-logout.php/sp',
    );

**Comment by lehmayr** [comment]
ah - it seems the problem was issuing the "logout" command on the SP instead of the IdP. now it works without that error.

**Comment by himanshusindhwani55** [comment]
Hey @lehmayr , can you help how you solved it, I am getting the same error while logout.
