### ISSUE TITLE
SimpleSAML\Utils\HTTP fails with RewriteRule

### ISSUE THREAD

**Issue by lehmayr** [simplesamlphp/simplesamlphp#403]
simplesamlphp v1.14.3

When using simplesamlphp in my project I got it in a subdirectory "vendor\simplesamlphp\simplesamlphp" which of course is a horrible URL. Therefore I added a .htaccess entry to redirect /simplesaml there.
SimpleSAML\Utils\HTTP::getSelfURLNoQuery uses SCRIPT_NAME which then no longer works (because it uses the vendor... path).
This works though:

        $url = self::getSelfURLHost();
        $url .= $_SERVER['REQUEST_URI'];
        if (($pos = strpos($url, '?')) !== false) {
            $url = substr($url, 0, $pos);
        }
        return $url;`

**Comment by lehmayr** [comment]
possibly slightly nicer solution:

        $url .= parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);

**Comment by jaimeperez** [comment]
Hi @lehmayr!

It is unclear to me whether you have configured your server to have an alias named `/simplesaml` pointing to your `vendor/simplesaml/simplesaml/www` (as the documentation recommends), or you have a URL rewrite rule telling you that the server should change one URL for the other. If we are talking about the former case, it just works, while the latter I'm uncertain about. In any case, that would be a web server configuration issue, and I definitely wouldn't recommend you to do URL rewriting in the context of the SAML protocol, as it could create a nightmare for you.

I'm closing the issue. Feel free to comment of course and give more information if you really think this is an issue in SimpleSAMLphp.
