### ISSUE TITLE
session timeout

### ISSUE THREAD

**Issue by ch3k1** [simplesamlphp/simplesamlphp#404]
hi, i have similar problem like it http://stackoverflow.com/questions/15547429/simplesamlphp-stay-logged-in.

Any Solutions?

**Comment by jaimeperez** [comment]
Hi @ch3k1!

This is an issue tracker, not a support forum, so it is only intended to report actual issues with SimpleSAMLphp. You might be able to find help in [our mailinglist](https://groups.google.com/forum/#!forum/simplesamlphp).
