### ISSUE TITLE
SAML2: unable set "Format" attribute for saml:Issuer

### ISSUE THREAD

**Issue by ciwidda** [simplesamlphp/simplesamlphp#407]
Implementing a SAML2 SP (HTTP-Redirect binding) the technical specification request me to specify a Issuer like:
`<saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">{issuer value}</saml:Issuer>`
but:
 - No constant defines "urn:oasis:names:tc:SAML:2.0:nameid-format:entity" which is part of the [SAML2 core specification](https://docs.oasis-open.org/security/saml/v2.0/saml-core-2.0-os.pdf) (8.3.6 Entity Identifier)
 - Line 427, file: ./vendor/simplesamlphp/saml2/src/SAML2/Message.php: the code/configuration doesn't allow in any way to add attributes to the saml:Issuer element

Am I misunderstanding something? Do I have to use saml:Extensions?

Thanks a lot for the support

**Comment by thijskh** [comment]
Maybe I'm misunderstanding something, but reading the SAML2 spec 2.2.5, the value `urn:oasis:names:tc:SAML:2.0:nameid-format:entity` is the default when omitted. So why would there be a need to make that configurable?

**Comment by thijskh** [comment]
By the way, you are referring to the code in the simplesamlphp/saml2 project. Please file the issue at the appropriate project.

**Comment by ciwidda** [comment]
I'm sorry, I didn't notice that, thanks a lot for the support.
I'll pay more attention to issue to correct project in the future.
