### ISSUE TITLE
SAML2: Impossible to insert ds:X509IssuerSerial with HTTP-POST Binding

### ISSUE THREAD

**Issue by ciwidda** [simplesamlphp/simplesamlphp#408]
The static method `XMLSecurityDSig::staticAdd509Cert` (Line 886, file ./vendor/robrichards/xmlseclibs/src/XMLSecurityDSig.php) in the `XMLSecurityDSig::add509Cert` function supports $options parameter - needed to generate "ds:X509IssuerSerial" in a SAML2 HTTP-POST Binsing SSO request; but there are no calls of this function where this $option parameter is passed with a consistent value, so I'm unable to generate ds:X509IssuerSerial for any SAML2 auth request.

Am I misunderstanding something?

**Comment by jaimeperez** [comment]
Hi @ciwidda,

Is this an issue report or a support question? If the former, what's exactly the issue, what is it that is not working or working in an unexpected way? If the latter, please use [the mailinglists](https://simplesamlphp.org/lists) to formulate your question. Also try to be more descriptive of what you need, how are you trying to do it, etc.

**Comment by ciwidda** [comment]
Hi @jaimeperez and thanks for the support,
I'm quite new to SAML2 and SimpleSAMLphp world and I'm really sorry if my questions are too general.
I didn't notice there were those discussions groups, I'll ask them an initial help.
Thanks again.

**Comment by jaimeperez** [comment]
Hi!

No problem at all. Try asking there and if you confirm there's an issue or would like to request some new feature, do not hesitate to come back here and report it 😉
