### ISSUE TITLE
SAML2: "Comparison" attributed ignored

### ISSUE THREAD

**Issue by ciwidda** [simplesamlphp/simplesamlphp#409]
In my SAML2 SP (HTTP-POST Binding) I need to specify "Comparison='minimum'" attribute on my "samlp:RequestedAuthnContext", but every call of "SAML2_AuthnRequest::setRequestedAuthnContext" or every assignment to the attribute "SAML2_AuthnRequest::requestedAuthnContext" just doesn't include this configuration in the value array.

Am I misunderstanding some usage?

**Comment by jaimeperez** [comment]
Hi again,

As before, are you reporting an issue or asking how to do something? Also, is this related to SimpleSAMLphp or the SAML2 library?

**Comment by ciwidda** [comment]
Hi @jaimeperez 
I'll try on the forum for this request too, thanks again for the support.
