### ISSUE TITLE
SimpleSAMLphp Metadata Signing Algorithm is not user configurable

### ISSUE THREAD

**Issue by sosumi** [simplesamlphp/simplesamlphp#411]
The automated metadata signing algorithm is not user configurable.

While SAML assertion signing preferences can be configured in config/authsources.php to use either SHA-1 or SHA-2, with the stated intent (as I understand it) being to change the default to SHA-2 in SimpleSAMLphp 2.0, metadata signing is currently hard-coded to use SHA-1.

As far as I can tell, this is set in a combination of the files “simplesamlphp-[version]/lib/SimpleSAML/XML/Signer.php” (around lines 99 and 249) and “simplesamlphp-[version]/lib/SimpleSAML/Metadata/Signer.php” (around lines 190 and 210).

**Comment by jaimeperez** [comment]
Thanks @sosumi!

I've just committed an implementation for this. Check the documentation for the development version (advanced features, metadata signing) to see how to specify the algorithm.

Please tell me if it works for you.
