### ISSUE TITLE
Better assignation of levels to log messages.

### ISSUE THREAD

**Issue by jaccino** [simplesamlphp/simplesamlphp#416]
It seems that almost all of actions related to "normal" flow (let us say, "Session: doLogout('foodle')" are in DEBUG log level. So we have to choose between an almost empty INFO log (named as "verbose" in config.php file) or a DEBUG level, clearly overfed for normal daily usage.

**Comment by tvdijen** [comment]
Point taken!  But this issue is not actionable as it is right now. Also, I'm uncertain that this is still as much of a problem as it was two years ago.. Therefore closing this one!
