### ISSUE TITLE
Bug in SimpleSAML\Utils\HTTP::getSelfURL(), new in 1.14.5

### ISSUE THREAD

**Issue by kloostec** [simplesamlphp/simplesamlphp#418]
We are using SimpleSAMLPHP integrated with Drupal, Moodle, and Mahara.  They are all exhibiting a new issue after the upgrade to 1.14.5 due to the rewrite of the getSelfURL function.

Specifically, sometimes through the module I'm getting the following values in the variables:

$url: https://sdsdev.smus.ca/simplesaml/
$baseDir: /var/simplesamlphp-1.14.5/
$rel_path: module.php
$pos: 22
Full return value: https://sdsdev.smus.ca/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp?SAMLResponse=fZJNa8QgEIb&RelayState=_fe9a4c1c2821225f0dc5d479020ce9b59f77303351&Signature=eR&SigAlg=http.w3.org-more-sha256

Abbreviated backtrace on the above variables:

SimpleSamlPHP modules/saml/www/sp/saml2-logout.php
-> SimpleSAML\Utils\HTTP->getSelfURLNoQuery
SimpleSamlPHP lib/SimpleSAML/Utils/HTTP.php
-> SimpleSAML\Utils\HTTP->getSelfURL

This works great and redirects as expected.

Sometimes, though, I'm getting the following values:

$url: https://sdsdev.smus.ca/simplesaml/
$baseDir: /var/simplesamlphp-1.14.5/
$rel_path: /var/www/sites/sdsdev.smus.ca/www/seniorlibrary/index.php
$pos: 57
Full return value: https://sdsdev.smus.ca/simplesaml//var/www/sites/sdsdev.smus.ca/www/seniorlibrary/index.php

Abbreviated backtrace on the above variables:

Drupal modules/simplesamlphp_auth/simplesamlphp_auth.module
-> SimpleSAML_Auth_Simple->requireAuth
SimpleSamlPHP lib/SimpleSAML/Auth/Simple.php
-> SimpleSAML_Auth_Simple->login
SimpleSamlPHP lib/SimpleSAML/Auth/Simple.php
-> SimpleSAML\Utils\HTTP->getSelfURL

This doesn't work, as the $rel_path variable is set to the script that's including simpleSamlPHP (Drupal's index.php, in this case).  This is just getting appended to the $url, resulting in a URL that's incorrect (and insecure -- it's exposing the directory structure of our server.

**Comment by jaimeperez** [comment]
Hi @kloostec!

Thanks a lot for reporting this. It is indeed a critical bug that we should address as soon as possible in a new release.

I've just committed a solution to both `master` and the `1.14` branch. It resolved the issue for me, but could you please update to the latest commit in `1.14` and confirm that it also resolves the issue for you?

This fix, in any case, introduces new challenges. We are now always using the `baseurlpath` configuration option to tell SimpleSAMLphp how to build URLs. However, URLs that don't belong to SSP will not use it (they shouldn't, of course), and that means any setup using reverse proxies with URL rewriting or similar, will be broken for the app using SSP. Not that it should work properly before, but I could imagine scenarios where such a setup was working and will stop working now. Controlling that and telling SimpleSAMLphp the right URL where to return to after authentication is now the complete responsibility of the application in case the URL to use is not the same as seen from the web server.

I'll await your feedback before having a new release.

**Comment by kloostec** [comment]
I had some issues testing this, for the following reasons:

1) The commit hasn't been made to the simplesamlphp-1.14 branch yet (last commit was 3 days ago)
2) Trying to use a git clone of the master branch resulted in bustage (Exception: Unable to load Composer autoloader in require_once() (line 18 of /var/simplesamlphp-1.15-git/lib/_autoload.php) -- I'm assuming this is because there are additional steps I need to follow once I have git cloned the master branch beyond our normal internal upgrade procedure
3) Copying the HTTP.php file from the git master to 1.14.5 resulted in a function not found (Fatal error: Call to undefined method SimpleSAML_Configuration::getBasePath() in /var/simplesamlphp-1.14.5/lib/SimpleSAML/Utils/HTTP.php on line 586)

In order to test, I ended up patching the diff from:

git diff e6fffdcbf4f565cdf6fc1549b89825720db2e85a e8ee8c83ef535273428f4c330107415b8ac6050d

into a fresh copy of 1.14.5 downloaded from the SSP website.  This was mostly successful, and applied the important code changes correctly.  I got an error merging changes to tests/lib/SimpleSAML/Utils/HTTPTest.php, probably because that file doesn't exist in the 1.14 branch.

Once I did this, the functionality worked as expected and I no longer got redirected to the wrong URL.

If you need me to do any more testing on the 1.14 branch once the commit has been made there, let me know!

Thanks!

**Comment by jaimeperez** [comment]
Hi @kloostec!

I pushed the changes in the 1.14 branch to a different repository 😅 

In any case, I have just released 1.14.6, which should fix the issue.
