### ISSUE TITLE
Patch for /trunk/modules/openidProvider/lib/Server.php - Allows SReg and AX Requests (was #518)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#42]
_From [moyanos...@gmail.com](https://code.google.com/u/111594543446045097873/) on October 15, 2012 21:17:28_

This patch allows SReg and AX requests. It uses AttributeMap to map attributes from the authentication source. It uses the 'authproc.idp' array in config.php and 'authproc' array inside module_openidProvider.php. For example to obtain email from authentication source, you could add 

```php
'authproc' => array(
    10 => array(
        'class'=>'core:AttributeMap', 
        'mail'=>array('email', ' http://axschema.org/contact/email' )
    )
)
```

to your module_openidProvider.php.

**Attachment:** [Server.php.patch](http://code.google.com/p/simplesamlphp/issues/detail?id=518)

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=518_

**Comment by thijskh** [comment]
The module now lives in simplesamlphp/simplesamlphp-module-openidprovider. Does not seem useful to migrate issue over.
