### ISSUE TITLE
Array reference on string - PHP Notice on $path

### ISSUE THREAD

**Issue by david-sc** [simplesamlphp/simplesamlphp#422]
https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Configuration.php#L539

On or around line 539 in /lib/SimpleSAML/Configuration.php

$path[0]
looks like it should be...
$path{0}

**Comment by tvdijen** [comment]
According to the [manual](http://www.php.net/language.types.string):

Characters within strings may be accessed and modified by specifying the zero-based offset of the desired character after the string using square array brackets, as in $str[42]. Think of a string as an array of characters for this purpose.

Note: Strings may also be accessed using braces, as in $str{42}, for the same purpose. However, this syntax is deprecated as of PHP 6. Use square brackets instead.

**Comment by david-sc** [comment]
I'm running PHP 7.0.8 and the bracket syntax throws:
PHP Notice:  Uninitialized string offset: 0 in /....path..../lib/SimpleSAML/Configuration.php on line 539

**Comment by tvdijen** [comment]
Could it be that one of the paths in your config.php-file is empty or set to a non-string value?

    'baseurlpath' => 'simplesaml/',
    'certdir' => 'cert/',
    'loggingdir' => 'log/',
    'datadir' => 'data/',
    'tempdir' => '/tmp/simplesaml',

**Comment by david-sc** [comment]
You know what? This is my bad. There's something else really weird going on with this installation, and the PHP Notice is probably related to that, not the syntax. The bracket reference syntax works fine in a vacuum, so I'm going to close this. Thanks.
