### ISSUE TITLE
Check for Session Data Before Inserting

### ISSUE THREAD

**Issue by tdiscuit** [simplesamlphp/simplesamlphp#423]
When using an SQL store for sessions, SSP attempts to insert session data into the database and if that fails (assumes it's failing because of a duplicate entry), updates the existing record. This happens on every page view, unless you're using MySQL or sqlite (which use `REPLACE INTO` and `INSERT OR REPLACE INTO` respectively).

In cases where users are not using MySQL or sqlite, this adds additional time to the request on each page view. Very basic testing showed 0.5ms additional querying time under 0% load on the database (0.5ms is very small, but that may vary with additional load/users). This also causes a lot of insert failed errors in the database logs.

Checking for the session first by doing `SELECT (_type, _key) FROM _kvstore;`, then doing a insert or update based on the result of that is faster and removes the errors in the database logs.

In my case, we're using PostgreSQL. I thought about adding a condition for PostgreSQL to make use of the `ON CONFLICT` clause on the insert statement, but that is only available in PostgreSQL 9.5+ which was released this year. I'd rather not break backwards compatibility for anyone using a slightly older version of PostgreSQL.

I haven't created a PR for this at the time of writing this as what I had initially thought was a simple fix turned into a rabbit hole of code updates to make it work since Store is used in multiple places. I initially thought that only the Session class made use of it, but I was mistaken.

Also, while going through more of the code for the SQL store I notice it's largely remained untouched for 6 years and there is more that I'd like to address, but that turned into more work than I wanted to do without a discussion around it. I also know that there is a desire to use namespaces and I didn't want to partially move the session stuff to a namespace without, again, a discussion.

**Comment by jaimeperez** [comment]
Hi Tyler!

I guess the approach to perform a _select_ previous to the _insert_ should always work, right?

In any case, this change should be completely transparent for the rest of the code base. The Session class uses the session handlers to store sessions and data, but the interface is the same for every handler and therefore the change should not affect any other code.

The SQL store is indeed not very much updated. Few people use it, IMHO. In any case, it would be definitely nice to give it a revamp and it will sooner or later be moved to namespaces indeed. Regarding this, it's completely safe to move it to a namespace and rename the class, as our autoloader will automatically handle the case and act accordingly (if someone tries to load `SimpleSAML_Store_SQL`, the loader will look for `SimpleSAML\Store\SQL`, and if it exists, load it and create an alias for it with the old name). Even if you want to refactor the class in a way that would break the autoloader, [we can manually resolve that too](https://github.com/simplesamlphp/simplesamlphp/blob/c762ea526ae511c89498afb9aa9315d2210b9170/lib/_autoload_modules.php#L27).

Just let me know if you have any other doubts or concerns, and of course, thanks a lot for helping us out!

**Comment by tdiscuit** [comment]
Hey Jaime!

Yeah since the logic would essentially be: select all rows from the kvstore that are session type and match the session ID (`SELECT _key FROM _kvstore WHERE _type = "session" AND _key = :sessionid;` for example) and if there is a matching row, update it; otherwise create a new one.

What I was thinking of was creating \SimpleSAML\SessionHandler\Database and limit the scope of its support to purely handling of session data, rather than providing memcached-like functionality with a database backing. With the existing implementation of the store, it'll be difficult to determine the table index or the relevant columns from the provided arrays of data.

You can see this from the function definition `public function insertOrUpdate($table, array $keys, array $data)` that you provide an array of keys, then a associative array of data to map to the keys. Since there is a table input, I can't assume that all columns will be the same. I noticed the store is also used by sspmod_saml_SP_LogoutStore to store sessions in _saml_LogoutStore which has completely different column names than _kvstore.

If the intention is for Store to solely be use for sessions, then I have no problem updating the SQL portion, but I'll have to update sspmod_saml_SP_LogoutStore as well to not have specific config if you have an SQL store or tie into the \SimpleSAML\Database directly and do it's own thing which it pretty much is doing today in terms of session tracking in a db.

When you say few people use it, do you mean that not many people use a central datastore for sessions? or memcached has more popularity? or this class is barely used outside of the sessionhandler?

**Comment by abnovak** [comment]
@tdiscuit Did you ever implement this fix? I'm also using Postgres and am getting a "[DATABASE] [6-1] ERROR:  duplicate key value violates unique constraint "simplesamlphp_kvstore_pkey" error that causes all users to receive an access denied error.

**Comment by tvdijen** [comment]
Can anyone confirm that this is still relevant after two years?

**Comment by robef** [comment]
Still valid when using postgres as the store, repeated log entries for below running v1.15.4

```
ERROR:  duplicate key value violates unique constraint "simplesamlphp_kvstore_pkey"
DETAIL:  Key (_key, _type)=(*****, session) already exists.
```

**Comment by tvdijen** [comment]
@robef Lots has changed since 1.15.4 and btw you're vulnerable to a lot of nasty stuff..
Can you confirm this issue against 1.17?

**Comment by robef** [comment]
I thought the only security issue was SSPSA 201812-01 which only affected 1.16.x? If that's not the case then the release info isn't accurate.

Anyway, I'll test with 1.17 and let you know. Thanks

**Comment by tvdijen** [comment]
Have you been able to run the test @robef

**Comment by tvdijen** [comment]
I have just send in a fix for this, but it needs to be tested by one of you guys.. I don't have postgresql available for testing.

**Comment by robef** [comment]
Sorry, I'm no longer working on this project so cannot test. Thanks anyway!
