### ISSUE TITLE
XML attribute values are lost when serializing the session

### ISSUE THREAD

**Issue by jaimeperez** [simplesamlphp/simplesamlphp#424]
simplesamlphp/saml2#60 changed the way we parse attribute values. Instead of getting them as text no matter the value, we now support attribute values that are not text, but for example, an XML chunk. This is even common in attributes like [_eduPersonTargetedID_](http://software.internet2.edu/eduperson/internet2-mace-dir-eduperson-201602.html#eduPersonTargetedID).

The problem is that `DOM*` objects in PHP are not serializable, and we almost always redirect before returning control to the script calling SimpleSAMLphp, so when the session is serialized, the values are lost.

We need to detect attribute values that are not strings or integers, and keep a string version of their XML representation. That way, we can serialize the session and save the values in the backend, and restore them from the XML string when unserializing the session.

**Comment by gollmann** [comment]
Unfortunately even in 1.14.7 I get empty eduPersonTargetedID attributes from Shibboleth IdPs. I can recreate the problem using a SimpleSAML test-idp with:

> 	'authproc' => array(
> 		// Generate the persistent NameID.
> 		2 => array(
> 			'class' => 'same:PersistentNameID',
> 			'attribute' => 'mail',
> 		),
> 		// Add the persistent to the eduPersonTargetedID attribute
> 		60 => array('class' => 'saml:PersistentNameID2TargetedID'),
> 	),
> 	'attributeencodings' => array('eduPersonTargetedID' => 'raw'),

Does the 1.14.7 SP need a special configuration for the fix to take effect ?
Thanks!
Georg

**Comment by jaimeperez** [comment]
Hi @gollmann!

It works fine for me. How are you accessing the contents of the attribute? Can you capture a response and paste here the relevant `saml:Attribute` that's causing trouble?

**Comment by gollmann** [comment]
Hi Jaime,

thanks for the quick reply. I am currently out of office so my means for investigations are limited.

> It works fine for me. How are you accessing the contents of the attribute? 

Good point. This raises belatedly the question what SimpleSAML_Auth_Simple getAttributes() is supposed to return for eduPersonTargetedID attributes. If it no longer returns the content of the NameID element as SSP 1.13 did existing applications will break one way or another.

Kind regards
Georg Gollmann

**Comment by jaimeperez** [comment]
Hi again!

I've just made a quick test, using `master` in the IdP, and 1.14.7 in the SP. I'm also using the same configuration as you to generate a permanent `NameID` and put it inside _eduPersonTargetedID_. Here's a snippet of the SAML assertion I'm sending:

```XML
<saml:Attribute Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.10"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
    <saml:AttributeValue>
        <saml:NameID NameQualifier="IdP-Entity-ID"
                     SPNameQualifier="SP-Entity-ID">
            73e06f7501746a9cfd20d14307c4f1c5bf24fb08
        </saml:NameID>
    </saml:AttributeValue>
</saml:Attribute>
```

When I arrive at the page presenting the attributes at the SP, this is what I get:

| Attribute | Value |
| --- | --- |
| Persisten pseudonymous ID<br/>`eduPersonTargetedID` | **NameID**<br/>&nbsp;&nbsp;&nbsp;&nbsp;73e06f7501746a9cfd20d14307c4f1c5bf24fb08<br/>**NameQualifier**<br/>&nbsp;&nbsp;&nbsp;&nbsp;IdP-Entity-ID<br/>**SPNameQualifier**<br/>&nbsp;&nbsp;&nbsp;&nbsp;SP-Entity-ID |

**Comment by gollmann** [comment]
Hi Jaime,

thanks for running the test. It confirms that applications need to be updated since they no longer receive plain ID-strings but structures with the ID one level down.

Thanks for the clarification !

Kind regards
Georg

**Comment by jaimeperez** [comment]
Hi Georg!

Yes, that's true. The [upgrade notes for 1.14](https://simplesamlphp.org/docs/1.14/simplesamlphp-upgrade-notes-1.14) were indeed updated for 1.14.7 to warn about this change and give an example on how to obtain the value of the attribute.
