### ISSUE TITLE
Remove support for certificate validation by fingerprint

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/simplesamlphp#431]
simpleSAMLphp allows one to configure trusted certificates either in full, or with just the fingerprint. These two ways of working complicate the code, documentation etc significantly, while the advantage of using fingerprints seems marginal. We should therefore transition to only accept full certificates.

When this is completed the code can also be removed from the saml2 library: simplesamlphp/saml2#68.

Discussion at https://groups.google.com/forum/#!topic/simplesamlphp-dev/MTbTGxAWniw

**Comment by tvdijen** [comment]
Work on the SAML2 lib has been done.. Will be release in 4.0
