### ISSUE TITLE
SimpleSAML_Error_NoState: NOSTATE

### ISSUE THREAD

**Issue by zyme-anshul** [simplesamlphp/simplesamlphp#435]
Hi Team,

I am getting the below error :

SimpleSAML_Error_NoState: NOSTATE

Backtrace:
2 /var/simplesamlphp/lib/SimpleSAML/Auth/State.php:263 (SimpleSAML_Auth_State::loadState)
1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:78 (require)
0 /var/simplesamlphp/www/module.php:137 (N/A)

I am using the  simplesamlphp [(1.14.7)] and mediawiki (1.27.0) 
connecting both of them i am using "https://www.mediawiki.org/wiki/Extension:SimpleSamlAuth"

I have tried with changing the domain name from default to our domain name in config/config.php
but still getting the above error. Please help me out.

**Comment by jaimeperez** [comment]
Hi @zyme-anshul!

Please note this is an issue tracker, not a support forum, so unless you are certain that there is a bug in the software, you should ask for support in the [mailing list](http://groups.google.com/group/simplesamlphp).

Apart from that, this error is pretty typical and we even have a [set of possible causes](https://github.com/simplesamlphp/simplesamlphp/wiki/State-Information-Lost).
