### ISSUE TITLE
Attribute filter per SP

### ISSUE THREAD

**Issue by tsmgeek** [simplesamlphp/simplesamlphp#438]
I do auth against LinOTP then connect to LDAP to retrieve additional attributes to return via SAML.
Is there a way to limit which attributes are sent to a particular SP? I have some that I do not wish to see certain attributes.

**Comment by jaimeperez** [comment]
Hi @tsmgeek!

This is an issue tracker, not a support forum, so unless you are certain that there is an issue in the software, you should ask your questions on how to use it in the [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, what you are looking for is pretty simple functionality and described [in](https://simplesamlphp.org/docs/stable/simplesamlphp-reference-sp-remote) the [documentation](https://simplesamlphp.org/docs/stable/core:authproc_attributelimit).
