### ISSUE TITLE
[patch] PDO backend for storing Metadata entries (was #529)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#44]
_From [mooknarf@gmail.com](https://code.google.com/u/mooknarf@gmail.com/) on December 26, 2012 16:15:29_

Hi,

I want to store the metadata entries (particularly the saml20-idp-remote and saml20-sp-remote) in an SQL database. I didn't find any (publicly) available implementation for this so I wrote my own. Unfortunately it does not seem to be possible to do this as a module, but needs to be implemented in core.

It is rough around the edges and documentation is not really available, but I wanted to get this code out there.

The reason for doing this is to make it possible to have an easy management API. If the API only needs to interact with JSON objects in the database it becomes very easy to write a REST API and use a HTML5 + JavaScript client side app to do the management. As most configuration for SPs and IdPs can be done through the metadata for the respective types it can most likely be a very simple JANUS replacement.

The module stores a json_encode of the existing metadata format in the database, keeping stuff as simple as possible. The getMetadataSet function is a bit heavy still, but I hope this call is not used during regular IdP/SP interaction.

The configuration takes place in config/config.php, e.g.:

```php
        'metadata.sources' => array(
                array('type' => 'flatfile'),
                array('type' => 'pdo',
                      'usePersistentConnection' => FALSE,
                      'dsn' => 'sqlite:/tmp/ssp.sqlite',
                      'username' => NULL,
                      'password' => NULL,
                ),
        ),
```

See the attached patch to trunk.

To add the entries to the database use the following snippet for IdPs, it just imports the existing entries:

```php
require_once "saml20-idp-remote.php";
foreach($metadata as $k => $v) {
	echo "INSERT INTO `saml20-idp-remote` ('entityId', 'entityData') VALUES ('" . $k . "','" . json_encode($v) . "');" . PHP_EOL;
}
```

Or this one for SPs:

```php
require_once "saml20-sp-remote.php";

foreach($metadata as $k => $v) {
	echo "INSERT INTO `saml20-sp-remote` ('entityId', 'entityData') VALUES ('" . $k . "','" . json_encode($v) . "');" . PHP_EOL;
}
```

**Attachment:** [simplesamlphp-add-pdo-metadata-source.diff](http://code.google.com/p/simplesamlphp/issues/detail?id=529)

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=529_

**Comment by jaimeperez** [comment]
We now have a PDO metadata storage handler thanks to @tdiscuit's contribution, so I'm closing this issue.

**Comment by Joe-U-Questionmark** [comment]
This looks great! However am I correct in saying that it doesn't cover the authsources.php file? 
Is there a way to store the authsources config in the database as well? Isn't that needed for a full database backed configuration store?

**Comment by tdiscuit** [comment]
Thanks @Joe-U-Questionmark!

The code that I submitted in #189 was specifically for the metadata storage handler and the SimpleSAML\Database class. At this time only the PDO metadata storage handler uses SimpleSAML\Database which is only addressing metadata, not the information in `authsources.php`.

**Comment by Joe-U-Questionmark** [comment]
Are their plans to do the same thing for authsources.php? That way it would also cover the non SAML SSO options.
