### ISSUE TITLE
Wrong Twig files extension

### ISSUE THREAD

**Issue by sgomez** [simplesamlphp/simplesamlphp#443]
I don't know if there are a reason to switch the twig file extensions from the usual `html.twig` to `twig.html` so, before to send a PR to fix this I'd like to ask if there a cause or if it is a mistake.

IMHO there are two reasons to use the format `html.twig`: First, it's a Twig file, not an HTML. And second, if the last extension suffix is not 'twig' you lost the syntax highlights and autocompletion twig code in the mains IDE like PHPStorm.

**Comment by jaimeperez** [comment]
¡Hola Sergio!

I honestly don't know if there's a reason to use `.twig.html` instead of `.html.twig`, but I agree with you. @hmpf, any objections to what Sergio is proposing?

**Comment by jaimeperez** [comment]
Hola de nuevo Sergio.

I just had a chat with Hanne and there's no strong reason to have the extensions like that, so I would actually consider removing the `.html` completely and leave all files with just a `.twig` extension. Does that sound ok?

**Comment by sgomez** [comment]
@jaimeperez It's perfect. If you want I can send a PR with the changes.

**Comment by jaimeperez** [comment]
That would be great!
