### ISSUE TITLE
frontpage_config.php check for mysql_* fails on PHP 7 

### ISSUE THREAD

**Issue by mfprimo** [simplesamlphp/simplesamlphp#448]
The healt checker verifies the presence of the function mysql_connect(), but it has been removed from PHP 7.
It seems nowhere mysql_* functions are invoke directly, everything is handled by PDO.
Probably this check can be dropped.

**Comment by tvdijen** [comment]
I don't think PHP 7 is officially supported, but it's probably safe to replace this check with extension_loaded('PDO')

**Comment by jaimeperez** [comment]
I don't think it's officially unsupported either 😉 

As far as I see, nothing is using directly those functions, indeed, so we can substitute that check with one for PDO.

**Comment by thijskh** [comment]
Agreed, PHP 7 is getting common enough that there's no other option than to support it. Also, the Travis checks do check PHP 7 and will fail if the code fails checks on PHP 7.

The proposed change by Tim seems correct indeed.

**Comment by jaimeperez** [comment]
Done!
