### ISSUE TITLE
allow whitelisting of OpenID SPs (was #536)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#45]
_From [jason.h...@gmail.com](https://code.google.com/u/115257806878558125614/) on January 28, 2013 20:39:06_

What steps will reproduce the problem?
1. simplesamlphp supports OpenID but doesn't allow restricting what websites (pseudo-SPs) can use it
2.
3. What is the expected output? What do you see instead? What version of the product are you using? On what operating system? Please provide any additional information below. Not a bug but a feature request. I can imagine organizations using SAML wanting to support OpenID - but only if it can be restricted to websites in a similar way to SAML

A SAML IdP allows an organization to "trust" certain SPs with details from its internal Identity Management system. As such it requires a formal agreement between the two entities. Allowing OpenID to be treated in the same way seems to me to be something some organizations would find attractive. 

Jason

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=536_

**Comment by jaimeperez** [comment]
This issue should now move to the [openid module issue tracker](https://github.com/simplesamlphp/simplesamlphp-module-openid/issues).

**Comment by jaimeperez** [comment]
Migrated to simplesamlphp/simplesamlphp-module-openid#2.
