### ISSUE TITLE
Login and logout redirect is broken

### ISSUE THREAD

**Issue by feroivanko** [simplesamlphp/simplesamlphp#450]
I have upgraded from version 1.13.2 to 1.14.8 and login,logout are not working correctly.

After login, logout with ADFS a I am redirected to the correct url but with port "80".

I tried also version 1.14.0 but it is also not working.

**Comment by jaimeperez** [comment]
Hi @feroivanko 

That looks like a configuration issue. I would guess that you may have a reverse proxy in front of your SimpleSAMLphp installation. What's the value of you `baseurlpath` configuration option?

**Comment by feroivanko** [comment]
Hi @jaimeperez,

'baseurlpath' => 'https://' . $_SERVER['HTTP_HOST'] . '/simplesaml/',

everything was working on 1.13.2.

Thanks

**Comment by jaimeperez** [comment]
Is the server doing TLS termination? Or do you have a proxy in front doing TLS?

**Comment by jaimeperez** [comment]
In any case, if you are specifying the full URL in the configuration, SimpleSAMLphp will not get creative about it. Can you paste an example of requests that produce incorrect redirections? You can use the SAML tracer firefox plugin to capture them and share it here afterwards.

**Comment by feroivanko** [comment]
@jaimeperez Is this what you mean?

<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID="_9bca9b8ce4c3746f4bd0119a0e1ce39c06a61f94c9"
                    Version="2.0"
                    IssueInstant="2016-08-24T14:44:22Z"
                    Destination="https://abc.xxxxx.com/adfs/ls/"
                    AssertionConsumerServiceURL="https://dev-xxx.xxxxx.com/simplesaml/module.php/saml/sp/saml2-acs.php/xxxxx-sp"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    >
    <saml:Issuer>urn:drupal:adfs-saml-dev</saml:Issuer>
</samlp:AuthnRequest>

**Comment by feroivanko** [comment]
@jaimeperez Is this what you mean?
`<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
                    xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"
                    ID="_9bca9b8ce4c3746f4bd0119a0e1ce39c06a61f94c9"
                    Version="2.0"
                    IssueInstant="2016-08-24T14:44:22Z"
                    Destination="https://abc.xxxxx.com/adfs/ls/"
                    AssertionConsumerServiceURL="https://dev-xxx.xxxxx.com/simplesaml/module.php/saml/sp/saml2-acs.php/xxxxx-sp"
                    ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
                    >
    <saml:Issuer>urn:drupal:adfs-saml-dev</saml:Issuer>
</samlp:AuthnRequest>
`

**Comment by feroivanko** [comment]
@jaimeperez 
> Is the server doing TLS termination? Or do you have a proxy in front doing TLS?
- nginx loadbalancer is doing TLS

**Comment by jaimeperez** [comment]
No, I mean capturing the entire HTTP session, as in the HTTP requests and the corresponding responses. The SAML messages exchanged here are probably worthless...

**Comment by feroivanko** [comment]
Hi @jaimeperez,

i found out that SAML2_HTTPRedirect is already making a request with wrong relayState.

`GET https://sts.xxxx.com/adfs/ls/?SAMLRequest=fZHLbsIwEEV%2FJfI%2BcRJMAhYg0bIoElURpF10U5l4ApHiRz0OKn%2FfJLQq3bCy5nGu5l7PUKjG8mXrT3oHny2gD75Uo5EPgzlpneZGYI1cCwXIfcn3y%2BcNT6OYW2e8KU1DbpD7hEAE52ujSbBezckHA2DJtJrKyTSFUQ5ZniR5LhiwLK8OLMlKJidsPJIZCd7AYUfOSSfU4YgtrDV6oX3XipMsjCdhOi7inLOUx9N3Eqw6N7UWfqBO3lvklKLHSLaVu0SlUVTICmmDlATL39MejcZWgduDO9clvO42f7CEc6guR%2BHhRgNrZRvozVNlZNtAZE%2BWDjVe3zQUJQ7dgQrRkmD7E95DrWWtj%2FdzO1yXkD8VxTbcvuwLspj1ynzIwS16WLrWiob3lsJ%2BFnbXzujt1rX6%2F92Lbw%3D%3D&RelayState=https%3A%2F%2Fdev-mygate.xxxx.com%3A80%2Fsaml_login%3Fquery%5Bdestination%5D%3D%2Ffront&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=h7vPTHTf4OSo%2BXgLy8Wvr48UFnAWEiMPzwp8gn9NEDZSeGazlnBxi%2F3rqvVjuHavBCgKRcHMdZqrm1LlI8mUdpJZqIKnWsFLpGW8Zm1OFiYotQhH40t7bAlaBiip4Osqp2uullaQk7Ybw7mT8tTD3iluMQLZ7hej%2F7F0RfEyVcXd%2BUi7TIRUNq5K2GAuKJCm2uSWqi4RyAB0VgVX5X56uYTL9nDktps2VqhxjJHutHbrl9ZNGZAD%2B5jO9JPQqQzB4TqED4Rit%2FW0KoEufhO4L3SAkQivZMH0W1PUTsIzbKPrQJrNDOu1pPn%2B%2F3IePURUJSdVSM6CuhMUxS%2FQihZRew%3D%3D HTTP/1.1
Host: sts.xxxx.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:40.0) Gecko/20100101 Firefox/40.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: https://dev-mygate.xxxx.com/user/login?destination=/front
Cookie: MSISLoopDetectionCookie=MjAxNi0wOC0yNTowNzoxNzo0OVpcMQ==; _ga=GA1.2.1421441593.1472049118; _gat=1

HTTP/?.? 200 OK
Cache-Control: no-cache,no-store
Pragma: no-cache
Content-Length: 16806
Content-Type: text/html; charset=utf-8
Expires: -1
Server: Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
X-Frame-Options: DENY
Date: Thu, 25 Aug 2016 07:42:00 GMT
`

I hope it is helpfull for you.

Thanks

**Comment by jaimeperez** [comment]
Yes, it's quite helpful, thanks!

The issue is in the application that's starting authentication, the script that's calling `requireAuth()`.

Since you have an _nginx_ doing TLS termination in front of your server, your server is actually accessed in port 80. Apparently, though, your PHP environment is telling SimpleSAMLphp that HTTPS is enabled. So if you go to the script invoking SimpleSAMLphp and debug somehow the `$_SERVER` global variable, you will see that `$_SERVER['HTTPS']` is `on` and `$_SERVER['SERVER_PORT']` is `80`. This is why SSP yields a `RelayState` parameter like that.

You need to either fix your PHP environment, or tell SSP what `RelayState` to use yourself. The former can be solved by setting the port manually if you know your website will always be accessed via HTTPS, at least at this point:

```php
$_SERVER['SERVER_PORT'] = 443;
```

If you prefer to build the return URL yourself, do it as the [documentation says](https://simplesamlphp.org/docs/stable/simplesamlphp-sp-api#section_4_1):

```php
$auth->requireAuth(array(
    'ReturnTo' => 'https://sp.example.org/'
));
```
