### ISSUE TITLE
Adding custom query string parameters when sending SAML2 message using HTTP-Redirect binding

### ISSUE THREAD

**Issue by piepkrak** [simplesamlphp/simplesamlphp#452]
We have an IdP in place which requires an organisation to be selected next to username and password.

In some SP's we already know what the organisation should be set to and therefor don't want to bother/confuse users with that anymore. 

I have been looking into the code, but there does not seem to be a way to add custom query string parameters to the redirect destination. Is this even possible without modifying SimpleSAMLPHP code?

**Comment by tvdijen** [comment]
This is not an issue, it's a support request... Please use the mailinglist for that.

To get to your question... You don't reveal much of how you've configured your IdP, but I assume you're using the multiLDAP module with several LDAP stores?
Anyway, you could make a custom authentication module that tries to read a home realm from the query string. A more elegant solution would probably be to have the SP sent the home realm as a SAML attribute in the authentication request.

**Comment by piepkrak** [comment]
Hi Tim,
My bad. I am aware it is not an issue.
We are already using a custom auth module.
Thank you for the pointers.
