### ISSUE TITLE
Pre-migrate: simplify translations

### ISSUE THREAD

**Issue by hmpf** [simplesamlphp/simplesamlphp#455]
Ensure that there are no usage of `t()` that uses concatenation in the tag, or deprecated arguments. Use only two arguments: the `$tag`, which must be a string or a variable, and optional `$replacements`, which stays a key-value array.

**Comment by hmpf** [comment]
Also ensure that absolutely all translations uses `t()` and nothing else.

**Comment by hmpf** [comment]
The following modules have templates with translations that needs simplifying:

- authorize
- authX509

(List not exhaustive)

**Comment by hmpf** [comment]
The following modules need no simplification:

- expirycheck
- negotiate

(List not exhaustive)

**Comment by hmpf** [comment]
The very worst modules to fix are:

- consentAdmin
- feide
- core
- saml
- discopower
- consent

**In that order**

**Comment by hmpf** [comment]
See the link for an attempt at an analysis of all existing usage of `t()`: [Translation analysis](https://github.com/simplesamlphp/simplesamlphp/files/458939/translation-analysis.txt)

### Format

Each line starts with the filename of a file the `t()`-usage was found in. If the same content is translated several times in a single file, there will be only one entry in the file.

After the filename comes what was found between the parentheses of the `t()`:

An opening brace (`{`) on a line means the string is namespaced. Two colons after the brace means the domain has a subdomain. **We don't want any subdomains.**

`, array` near the end of a line means the translation has placeholders. If the `array` is followed by anything, the `t()` uses deprecated arguments. **Get rid of the deprecated arguments.**

` . concat` near the end of a line means the string is concatenated and not findable by an extractor. **We don't want any of these!**

` $` right after the leftmost colon (which marks the end of the filename) means there is no string to translate, but a variable. **We need a `noop()` version of the actual contents of the variable somewhere so that extractors can find it!**

`NL` means the contents of the `t()` is spread over multiple lines. Do we want that?

The final possibility is only found in 
`modules/core/templates/frontpage_federation.tpl.php`: translating the returned value from a function, in this case `mtype`. **Let's move that mtype out of the template.**

**Comment by hmpf** [comment]
Keep subdomains for 1.15, switch to strings instead of tags for 2.0 which also solves the subdomain problem.

**Comment by tvdijen** [comment]
@hmpf Would it be possible to run another analysis on this? I asume you've scripted that before...
Right now it's kinda hard to see what's left to be done..

**Comment by hmpf** [comment]
It was pipes and unix tools and a lot of vimming and regular expressions so it'd take a while. Let's see, started by grepping for usage of `t()` and all its variants, then modified with several rounds of regexpes to only home in on the value to be translated. Grepping for `'{` should also help.

Or, a script that worked through the existing analysis and checked if the right hand side were still there would catch quite a lot.

**Comment by thijskh** [comment]
Described cases not used anymore outside of old templates
