### ISSUE TITLE
PSR-2 compliant whitespace

### ISSUE THREAD

**Issue by hmpf** [simplesamlphp/simplesamlphp#458]
Fix whitespace as per PSR-2.

When fixing whitespace, ONLY do that for that commit, as this makes `git blame -w` work better.
Reference this issue in the commit message, for instance in the body as "For: #458". Don't do too many files in one go, only one module per commit for instance.

If fixing whitespace in a template leads to it rendering differently, the template is bugged. Take screenshots of before and after, add them to a new issue referencing this one, and also mention what browser you are using.

**Comment by tvdijen** [comment]
Whitespace is done..
I've just ran phpcs and there are a handful of other PSR-2 issues that I can address later today.
