### ISSUE TITLE
When trying to login using google-openId I was getting "PHP strict error". I sending you the solution. (was #556)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#46]
_From [alevi...@gmail.com](https://code.google.com/u/103970910997224698172/) on July 16, 2013 07:07:26_

I was getting this error:

>""
>Declaration of sspmod_openid_StateStore::storeAssociation() should be compatible with >Auth_OpenID_OpenIDStore::storeAssociation($server_url, $association) >[APP/simplesamlphp/modules/openid/lib/StateStore.php, line 14]

looking at the code I have noticed that in class "stateStore", line 167 of version: simplesamlphp-1.11.0, the method definition is:
```php
public function storeAssociation($server_url, Auth_OpenID_Association $association) {
...
}
```

and it should be:
```php
public function storeAssociation($server_url, $association) {
...
}
```
_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=556_

**Comment by thijskh** [comment]
Filed as simplesamlphp/simplesamlphp-module-openid#1
