### ISSUE TITLE
Get rid of Translate->getAttributeTranslation()

### ISSUE THREAD

**Issue by hmpf** [simplesamlphp/simplesamlphp#461]
Find a way to use `t()` instead. For #455

**Comment by tvdijen** [comment]
Another case was introduced in the new admin module:
`modules/admin/lib/TestController.php`

**Comment by thijskh** [comment]
Is this the fix? 303e51b9f4457dea80e1637e9971f854d9d6fb42

Or am I missing something here? We can just apply a similar fix to those two modules and it's done.

**Comment by tvdijen** [comment]
Uhm... That doesn't translate attributes anymore, or am I missing something?
The idea is to translate them to user-friendly names like we do in the consent screen and the attributes overview.

I think we need a Twig-filter that uses the attributes.po to translate attribute names

**Comment by thijskh** [comment]
One thing the current method does is support the 'attributes.extradictonary' setting.

https://github.com/simplesamlphp/simplesamlphp/blob/1d24a64b46e8b4b1e648cecf409f24b3112fbc13/config-templates/config.php#L777-L801

I doubt we still need that? If you want to provide a module with extra attribute translations in a module, just ship them in your module's po file?

**Comment by tvdijen** [comment]
Yes, if we make sure that our logics consider an `attributes.po` in the configured theme-module, that config option can probably go away
