### ISSUE TITLE
Is One login Mandatory while using samlphp

### ISSUE THREAD

**Issue by varvinya** [simplesamlphp/simplesamlphp#467]
Hi,
I am new to samlphp. Should we use a third party like one login to act as Idp for our php application?.Can we use Saml library and create our own Idp and have it interact with our web application

**Comment by jaimeperez** [comment]
Hi @varvinya!

This is an issue tracker, and as such it's intended for reporting issues, not to ask for support. Please use the [mailing list](http://groups.google.com/group/simplesamlphp).

Regarding your question, why would be One Login mandatory to use SimpleSAMLphp? You can use SimpleSAMLphp in the way you want, as an SP, as an IdP, or even as both.
