### ISSUE TITLE
Possibility to select theme based on request / Service provider

### ISSUE THREAD

**Issue by spaceone** [simplesamlphp/simplesamlphp#468]
It seems currently not possible to change/select the theme based on the current request.
In the mailing list I found a patch which make it possible to set different themes for different service providers:
https://groups.google.com/forum/#!topic/simplesamlphp-dev/WQ6EQv8ThQc

My specific use case is to change the theme for a specific AuthNRequest. I am showing the simplesamlphp-IDP login form inside of an iframe on my service provider site because the site relies on the current javascript state and can therefore not redirect the user in the main window.
To do this I currently just prefix the RelayState with 'IFRAME' and check this in the template ~ala:
```
$qs = parse_url(explode(':', $this->data['stateparams']['AuthState'], 2)[1], PHP_URL_QUERY);
$a = array();
parse_str($qs, $a);
if(!(isset($a['RelayState']) && substr($a['RelayState'], 0, strlen('IFRAME-')) === 'IFRAME-')) {
 include('othertheme.php');
 die(0);
}
```
Maybe something more generic could be implemented to select the theme? See attached patch.

**Comment by spaceone** [comment]
https://github.com/spaceone/simplesamlphp/commit/d8e8fd746d8be1349ff5617a13ac8cf9f79ef9dc

**Comment by jaimeperez** [comment]
Hi @spaceone!

I'm a bit hesitant about this. Obviously, this will only make sense when several SPs are connected to the same IdP. However, in that case, you would have SSO, and the login page would change depending on where the user is trying to access first. That's not very intuitive for the user, as the login form will change its appearance, and furthermore, it will induce people to think changes in the login form are normal, and therefore that it is ok to type his/her credentials even if the login page is not what he/she's used to (with all the security implications regarding phishing).

Apart from that, I believe there are some mechanisms in place to prevent the login form to be shown inside an iframe (to avoid Cross Frame Scripting attacks), so I'm not even sure that could work...

**Comment by spaceone** [comment]
I see your point for the general simplesamlphp project.
In our environment we have the same design in the IDP and in the SP so that the change will not be noticeable to the end user.
The security mechanism are set via the X-Frame-Options and X-Content-Security-Policy HTTP response headers which are respectively correctly set up in my environment to allow the specific service provider.

**Comment by jaimeperez** [comment]
Ah, so if I understand correctly, the IdP already looks like the SP, and you would need to have a specific, slightly different design, to adapt to the fact that you are running on an iframe, right?

**Comment by spaceone** [comment]
Exactly! I need to strip out e.g. the header/footer and load some specific CSS file.

**Comment by jaimeperez** [comment]
Ok, now I understood 😄 

In that case, couldn't you do that just by detecting the iframe using javascript in your theme, and stripping that header and footer out (or just hiding them, actually)? That way you won't need two different themes (that would be almost identical) nor a modification to SimpleSAMLphp (which could take a long time to be in a stable release), and we wouldn't need to add a feature that could be abused to introduce a security weakness. Does that sound reasonable?

**Comment by jaimeperez** [comment]
Hi @spaceone!

I'm closing this since I believe there are alternative ways to solve your use case without introducing this change in SimpleSAMLphp, and without undesired side effects possibly affecting the security of the users.

Of course, feel free to comment if you don't agree, and we can discuss it.

**Comment by spaceone** [comment]
Well, we are patching simplesamlphp by ourself already.
We can't solve everything of this with Javascript / on client side. Also the <noscript> users are affected then.
But I can understand your point of view.
