### ISSUE TITLE
Return the group name rather than the group DN in ldap:AttributeAddUsersGroups

### ISSUE THREAD

**Issue by vittala** [simplesamlphp/simplesamlphp#482]
At the moment, it seems that the group values returned from ldap:AttributeAddUsersGroups are always the DNs of the group. The configuration for this module allows for `attribute.groupname`, but changing this doesn't seem to have any effect on the module's results.

If the purpose of `attribute.groupname` is to select which LDAP attribute to return as the group's name, then this commit will do so:
https://github.com/vittala/simplesamlphp/commit/f731853a100846c7c48d93bdc4f4598fcb1c6817

Regards
Vittal

**Comment by tvdijen** [comment]
Fixed on master through fb0e79265abe0530b4ed48608c3b110a552b967d
