### ISSUE TITLE
URL not allowed

### ISSUE THREAD

**Issue by adteja** [simplesamlphp/simplesamlphp#484]
Hi,
When I try to log in as administrator on the simplesamlphp interface. I get the following error-

SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
0 /srv/bindings/953b1a2e29694ba48a67beea8f81c386/code/simplesaml/module.php:180 (N/A)
Caused by: SimpleSAML_Error_Exception: URL not allowed: https://dev-horizonblue.devportal.apigee.com:15133/simplesaml/module.php/core/login-admin.php?ReturnTo=https%3A%2F%2Fdev-horizonblue.devportal.apigee.com%3A15133%2Fsimplesaml%2Fmodule.php%2Fcore%2Ffrontpage_config.php
Backtrace:
2 /srv/bindings/953b1a2e29694ba48a67beea8f81c386/code/private/simplesamlphp-1.14.8/lib/SimpleSAML/Utils/HTTP.php:331 (SimpleSAML\Utils\HTTP::checkURLAllowed)
1 /srv/bindings/953b1a2e29694ba48a67beea8f81c386/code/private/simplesamlphp-1.14.8/modules/core/www/as_login.php:21 (require)
0 /srv/bindings/953b1a2e29694ba48a67beea8f81c386/code/simplesaml/module.php:137 (N/A)

Pretty new to simplesaml, so any help is welcome.
Thanks,

**Comment by jaimeperez** [comment]
Hi @adteja!

This is an issue tracker, not a [support forum](https://groups.google.com/forum/#!forum/simplesamlphp).

Regarding your issue, it looks like SimpleSAMLphp thinks its own URL is different than the one you are using to access it. Set the `baseurlpath` configuration option to the base URL where you can reach SimpleSAMLphp from your point of view (i.e. `https://dev-horizonblue.devportal.apigee.com:15133/simplesaml/`).
