### ISSUE TITLE
Better Support for SPs with multiple NameId Formats

### ISSUE THREAD

**Issue by pradtke** [simplesamlphp/simplesamlphp#487]
https://groups.google.com/forum/#!topic/simplesamlphp/3aZiNn6mFkM

Some SPs advertise multiple NameID formats in their metadata. When parsed by SSP, only the first one is kept. This complicates integrations where the SSP (as the IdP) supports one of the formats that is not listed first since it only knows about the first format.

Maybe a solution is to:
- keep all NameId metadata
- Update buildAssertion() to check if any of the NameIds are transient, and then use that (assuming format wasn't in the authnrequest)
- else look at which namedIdFormat keys in $state['saml:NameID'] overlap with what is in the metadata and pick one.

**Comment by jaimeperez** [comment]
Thanks Patrick!

Your suggestion sounds reasonable, though I haven't looked at the code and I don't know right now if that would be enough. A PR would be really helpful here. Do you have time for that?

**Comment by tvdijen** [comment]
I tried to convert some metadata with 2 NameIdFormats and it parsed just fine, keeping both in place..
@pradtke could you please verify this, so we can close this issue?

**Comment by tvdijen** [comment]
We're assuming this issue no longer exists. We can reopen if proven otherwise
