### ISSUE TITLE
ADFS IdP Metadata Signing

### ISSUE THREAD

**Issue by tdiscuit** [simplesamlphp/simplesamlphp#494]
While I was looking into using SimpleSAMLphp as an ADFS IdP, I came across an error.

Looks like the following code:

```
    // sign the metadata if enabled
    $metaxml = SimpleSAML_Metadata_Signer::sign($metaxml, $idpmeta->toArray(), 'ADFS IdP');
```

causes PHP to throw the error: `Fatal error: Maximum function nesting level of '100' reached, aborting! in /var/simplesamlphp/vendor/composer/ClassLoader.php on line 344`

My test server is using `PHP 5.5.9-1ubuntu4.20`. A previous version (forgot to check what it was before I upgraded php. It was likely 5.4 on Ubuntu 14.04 LTS) of PHP doesn't display anything at all and Chrome shows an error indicating the server sent no data.

**Comment by jaimeperez** [comment]
Hi Tyler!

Could it be a problem with the composer dependency loader? Did you try running composer again to make sure everything is up to date?

**Comment by tdiscuit** [comment]
Composer has been run fairly recently on that install. However, It looks like it's working on one of my other test IdPs (running php5-fpm and nginx)...

Not sure if it's specific to mod_php with Ubuntu, or because of something I have done with that instance of SimpleSAMLphp as it is the one that I use to build changes for the PRs that I submit here. I'll try a fresh copy on another Ubuntu host and see if that gives me any problems. I now have a feeling it's something specific to my dev install haha.

**Comment by tvdijen** [comment]
@tdiscuit Was this resolved eventually?
