### ISSUE TITLE
Exception if memcache_store.prefix is null

### ISSUE THREAD

**Issue by danepowell** [simplesamlphp/simplesamlphp#496]
In the config.php template file, `memcache_store.prefix` is set to null.

If you do not modify this value, the comments indicate that it should default to SimpleSAMLphp.

Instead, Config::getString throws an exception when you try to actually use the memcache store:

> The option 'memcache_store.prefix' is not a valid string value

It seems like Config::getString() is not behaving as intended. It's pretty clear that it should return the default value (provided in [Memcache.php](https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Store/Memcache.php#L26)), not throw an exception.

This is simplesamlphp v1.14.8.

**Comment by tvdijen** [comment]
This should fix it: [8d251b7](https://github.com/simplesamlphp/simplesamlphp/commit/09e0596f66129d9e37c1fa373945b072746755f1)

**Comment by danepowell** [comment]
Yeah, I thought about opening a PR with that simple solution, but don't you think there's something deeper wrong with getString() here? I'm pretty sure there are other places where strings are set to null by default.

**Comment by tvdijen** [comment]
Well, I think it's simply a choice of architecture... getString expects a string, or else it fails.. Same thing for getArray, getBoolean, etc.

I could use getValue to get the null-value from the config, but then I'd have to 'fix' any non-string values in Memcache.php because I can't prefix with a boolean or an array..

**Comment by jaimeperez** [comment]
Hi again @danepowell!

As Tim was mentioning, that is intended behaviour, as `getString()` is supposed to make sure that the value is indeed a string and nothing else. The configuration example in this case was just very unfortunate...
