### ISSUE TITLE
Migrate: twigified templates

### ISSUE THREAD

**Issue by hmpf** [simplesamlphp/simplesamlphp#499]
We're switching to twig. Mention this issue in the commit when all templates in that commit are completely converted. This makes it easy to see what is already done.

Append the commit message with "For #499".

**Comment by tdiscuit** [comment]
With the switch to twig, does this mean that existing template modules will break?

**Comment by jaimeperez** [comment]
Existing templates will need to be migrated to twig, yes. However, the plan is to have both the old and the new templating system coexist in 1.15, so that people can migrate them while they are still working, and remove the old (current) templating system in 2.0.

**Comment by tdiscuit** [comment]
Excellent. I knew that I would have to do it at one point, just trying to figure out how soon I need to be worrying about it. Thanks @jaimeperez!

**Comment by MicWit** [comment]
I left a comment in #781, however that issue is closed. There needs to be somewhere with steps that need to be taken to move over to the twig templates. I can NOT get my project to swap over to TWIG templates and I want to create my own TWIG templates.

**Comment by thijskh** [comment]
This is done, there are individual issues for loose ends.
