### ISSUE TITLE
Implement SAML2 sender-vouches subject confirmation method (followup to #333) (was #600)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#50]
_From [fefefan...@googlemail.com](https://code.google.com/u/109263125316745138061/) on November 27, 2013 09:53:46_

What steps will reproduce the problem? 

1. Configure an IdP which uses the 'urn:oasis:names:tc:SAML:2.0:cm:sender-vouches' SubjectConfirmation-Method

2. Use the Authentication test page

I would expect to be authenticated, but get an exception:

>Backtrace:
>0 /var/simplesamlphp/www/module.php:180 (N/A)
>Caused by: SimpleSAML_Error_Exception: Error validating SubjectConfirmation in Assertion: Invalid Method on SubjectConfirmation: 'urn:oasis:names:tc:SAML:2.0:cm:sender-vouches'
>Backtrace:
>3 /var/simplesamlphp/modules/saml/lib/Message.php:694 (sspmod_saml_Message::processAssertion)
>2 /var/simplesamlphp/modules/saml/lib/Message.php:528 (sspmod_saml_Message::processResponse)
>1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:81 (require)
>0 /var/simplesamlphp/www/module.php:135 (N/A) What version of the product are you using? On what >operating system? 1.11.0 on Ubuntu 13.10.

This is a follow-up for Issue #333 .

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=600_

**Comment by brianV** [comment]
I've taken a stab at this. See the two pull requests referenced above (https://github.com/simplesamlphp/saml2/issues/41 and https://github.com/simplesamlphp/simplesamlphp/issues/200)

**Comment by jaimeperez** [comment]
Thanks @brianV for your pull requests! :smile:
