### ISSUE TITLE
Cannot use consent-module with mysql 5.7 or newer

### ISSUE THREAD

**Issue by hmpf** [simplesamlphp/simplesamlphp#504]
Mysql 5.7 changes how fields of type TIMESTAMP is handled. If you try to create the consent-table for the consent-module, you get the error `ERROR 1067 (42000): Invalid default value for 'usage_date'`.

See http://shankargopal.blogspot.no/2013/03/mysql-566-timestamp-columns-and-default.html 

Workarounds:
- Do not runmysql under strict mode: See http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html
- Explicitly turn off compatibility-mode: See https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp

We need to change the documentation to warn about this.

A fix involves changing the sql create-statement into something that will work on all supported mysqls, and document that.

**Comment by hmpf** [comment]
This also affects the consentAdmin module.

**Comment by tvdijen** [comment]
@hmpf do you have an MySQL-instance available to test something for me?
Because I think the fix is as easy as can be:
https://github.com/tvdijen/simplesamlphp/commit/e868675ada508f0112fab8913930cadb38d2c7a0

**Comment by tvdijen** [comment]
I've verified the fix myself and it works.
Fixed it in https://github.com/simplesamlphp/simplesamlphp/commit/36a3ff9248787fe7ab40367a6cc736313503add6
