### ISSUE TITLE
Namespace translation tags

### ISSUE THREAD

**Issue by hmpf** [simplesamlphp/simplesamlphp#505]
Change all instances of `t('something')` into `t('{somemodule:somedictionary:something}')` (module) or  `t('{somedictionary:something}')` (not module) where the tag is traceable to a dictionary. 

If the tag is not from a dictionary, add a comment here with a link to the line-number of the tag in question and where the tag comes from. See https://help.github.com/articles/getting-permanent-links-to-files/ on how to get canonical links to source, but basically: choose the line in github, press  `y`. The address in the address-bar in the browser will change to include a hash and a lilenumber at the end. Paste that address into your comment.

**Comment by hmpf** [comment]
The template in consentAdmin has two non-namespaceable tags, `spname` and `spdescription`:

* https://github.com/simplesamlphp/simplesamlphp/blob/674028a7939d67135c22e0a8c6f97c3681fa947c/modules/consentAdmin/templates/consentadmin.php#L74
* https://github.com/simplesamlphp/simplesamlphp/blob/674028a7939d67135c22e0a8c6f97c3681fa947c/modules/consentAdmin/templates/consentadmin.php#L76
* https://github.com/simplesamlphp/simplesamlphp/blob/674028a7939d67135c22e0a8c6f97c3681fa947c/modules/consentAdmin/templates/consentadmin.php#L78

They are loaded by `includeInlineTranslation`:

https://github.com/simplesamlphp/simplesamlphp/blob/674028a7939d67135c22e0a8c6f97c3681fa947c/modules/consentAdmin/templates/consentadmin.php#L71-L72

We also need to find an alternative to `includeInlineTranslation` that does not run in the template, see #463.

**Comment by tvdijen** [comment]
There are still a lot of these cases left.. Not sure why this is an issue though.

**Comment by jaimeperez** [comment]
This was part of the work previous to migrating to twig. If I understand correctly, not referencing any specific dictionary makes it difficult to migrate because the strings may be in the wrong place. In any case, I don't think this is relevant anymore since we're moving away from tags.
