### ISSUE TITLE
Export NameIDFormat in metadata according to configuration (was #604)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#51]
_From [jaim...@gmail.com](https://code.google.com/u/117104869761456643866/) on December 09, 2013 16:27:32_

It should be possible to export the list of supported NameID formats in the generated metadata without explicitly telling with the NameIDFormat option (which currently supports only one format). By just looking into the NameID generation filters (1) generally available, an IdP should be able to tell which formats it supports, so there's no need to manually specify them.

The current configuration mechanism is error prone and may lead to configurations such as an IdP claiming to support only the persistent format, but actually not supporting it because there's no generation filter in place. The NameIDFormat option could be kept as an array that filters the list of formats supported, namely to remove transient support.

On the SP side, the NameIDFormat directive should be an array specifying the list of formats supported, mainly for metadata generation.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=604_

**Comment by thijskh** [comment]
This has been fixed at some point in the past.
