### ISSUE TITLE
documentation for SP remote metadata reference

### ISSUE THREAD

**Issue by martin-kuba** [simplesamlphp/simplesamlphp#510]
The documentation at https://simplesamlphp.org/docs/stable/simplesamlphp-reference-sp-remote
for the **simplesaml.nameidattribute** should mention that its value (name of the attribute which should be used as the value of the NameID) is the name **after** it is translated by the name2oid filter to OID URN (the default setting), thus not **eduPersonPrincipalName**, but **urn:oid:1.3.6.1.4.1.5923.1.1.1.6**. It took me a couple of hours to figure this out.

**Comment by jaimeperez** [comment]
Hi @martin-kuba!

Not really. The `name2oid` authproc filter is not mandatory, (nor any other), so it doesn't make much sense to indicate that, as it all depends on your configuration. Furthermore, the documentation doesn't mention any attribute at all.

On the other hand, it could make sense to indicate that this is run **after** authproc filters. It's kind of implicit by the given text, but making it more obvious wouldn't do harm.
