### ISSUE TITLE
Logs not getting generated

### ISSUE THREAD

**Issue by SalilLambe** [simplesamlphp/simplesamlphp#511]
i configured my simplesamlphp but it is not generating logs, this is how my config.php of simplesamlphp plugin is configured -

![image](https://cloud.githubusercontent.com/assets/13847054/20208081/a90b4cbc-a811-11e6-82bf-00b91c2c988d.png)

Please check with the issue

**Comment by jaimeperez** [comment]
Hi @SalilLambe,

This is not a support forum, but an issue tracker. Logging works fine in SimpleSAMLphp, so this must be a configuration issue on your side.

**Comment by comradebeck** [comment]
@SalilLambe I am definitely a year late to somehow give my discovery about the logging function. 

By default, 'logging.handler' on config has a value of syslog. So unless you turn on the syslog module, no logs get generated. So for the logging to work, you can either enable the syslog module and do some configuration based here: https://simplesamlphp.org/docs/stable/statistics:statistics  or set the value of 'logging.handler' to either 'file' (puts the log file to the directory set on 'loggingdir') or 'errorlog' (puts the log in to the apache error log). 

I hope everyone who's having this issue notice this :)

**Comment by rameshnaik5521** [comment]
Thanks @comradebeck 
Its helped me a lot :)

**Comment by ElijahLynn** [comment]
> Hi @SalilLambe I am definitely a year late to somehow give my discovery about the logging function.
> 
> By default, 'logging.handler' on config has a value of syslog. So unless you turn on the syslog module, no logs get generated. So for the logging to work, you can either enable the syslog module and do some configuration based here: https://simplesamlphp.org/docs/stable/statistics:statistics or set the value of 'logging.handler' to either 'file' (puts the log file to the directory set on 'loggingdir') or 'errorlog' (puts the log in to the apache error log).
> 
> I hope everyone who's having this issue notice this :)

Very nice tip here, I set the handler in config.php (or was it authsources.php?) to 'file' and then the log type to DEBUG. Then I still couldn't find it and refreshed the simplesaml endpoint and got a notice printed to the screen that it couldn't create the file due to permissions, AND that had the path of where the file should be so I fixed permissions and still had to manually create the 'log' directory then I finally had a log working that I could `tail`!

**Comment by samhaldia** [comment]
Thanks @comradebeck , setting it to file does the job.

**Comment by hseritt** [comment]
Setting it to file still does not work.
