### ISSUE TITLE
Installation fails with composer (was #611)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#52]
_From [kay.stro...@gmail.com](https://code.google.com/u/116691116915588645773/) on January 23, 2014 08:53:40_

I have a working composer install for TYPO3 FLOW

then i added:       "simplesamlphp/simplesamlphp": "dev-trunk"

I get:

> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for simplesamlphp/simplesamlphp dev-trunk -> satisfiable by simplesamlphp/simplesamlphp[dev-trunk].
> - simplesamlphp/simplesamlphp dev-trunk requires openid/php-openid dev-master#ee669c6a9d4d95b58ecd9b6945627276807694fb as 2.2.2 -> no matching package found.
> 
> Potential causes:
> - A typo in the package name
> - The package is not available in a stable-enough version according to your minimum-stability setting
>   see < https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion > for more details.
> 
> Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Is there any chance to fix that? Perhaps you just need to adjust the version of php-openid

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=611_

**Comment by newmen** [comment]
It still fuck my mind

```
13:16 $ cat composer.json 
{
    "require": {
        "simplesamlphp/simplesamlphp": "~1.13.2"
    }
}
13:16 $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for simplesamlphp/simplesamlphp ~1.13.2 -> satisfiable by simplesamlphp/simplesamlphp[v1.13.2].
    - simplesamlphp/simplesamlphp v1.13.2 requires openid/php-openid dev-master#ee669c6a9d4d95b58ecd9b6945627276807694fb as 2.2.2 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by jaimeperez** [comment]
Hi @newmen,

SimpleSAMLphp 1.13.2 was released before fixing this issue. Therefore, if you want to avoid this problem, you need to point to dev-master or to a specific commit of SSP.

**Comment by jdufresne** [comment]
Any chance of getting this fix in a release so that it is easier to install SimpleSAMLphp through composer?

**Comment by gfaust-qb** [comment]
Haven't tried it in this special case but it helped me with some other projects not to use composer install and use: composer update --with-dependencies --prefer-lowest 
This is not the solution for the problem, but it might give you the possibility to keep your work going on.

**Comment by jaimeperez** [comment]
Hi,

Since this is already in master, the next release will obviously have it fixed. Hopefully we'll have 1.14.0 quite soon.
