### ISSUE TITLE
Line endings for schema files

### ISSUE THREAD

**Issue by danepowell** [simplesamlphp/simplesamlphp#523]
SimpleSAMLphp uses CRLF line endings for its schemas (in `schemas/`), but LF for pretty much everything else. This causes problems for downstream projects committing the vendor directory (i.e. for a build artifact), because Git will persistently show those schema files as overridden and want to convert them to LF.

Seems like schema files should be converted to LF to be consistent with the rest of the project, and the composer/php community as a whole, would you agree?

**Comment by jaimeperez** [comment]
I agree :-)

Thanks for the suggestion @danepowell! It is now fixed in master.

**Comment by danepowell** [comment]
Awesome, thanks for the swift response!
