### ISSUE TITLE
mcrypt deprecated in PHP 7.1

### ISSUE THREAD

**Issue by moffe42** [simplesamlphp/simplesamlphp#526]
mcrypt have been deprecated i PHP 7.1 - http://php.net/manual/en/migration71.deprecated.php

This should be fixed, so an update to PHP 7.1 is possible. OpenSSL extension should work on all supported versions of SSP.

**Comment by sgomez** [comment]
AFAIK mcrypt is not longer used from SSP 1.14. I'm using it with PHP 7.1 without problems.

**Comment by jaimeperez** [comment]
Hi @moffe42!

Updating to PHP 7.1 shouldn't be a problem, given that _deprecated_ doesn't mean it won't be available. Actually, the very same note is very explicit: mcrypt will be removed from PHP **7.2**.

Apart from that, mcrypt is only used for symmetric encryption/decryption, which is not something usual in SAML.

In any case, this is not something we can do anything about. SimpleSAMLphp does not require mcrypt, but robrichards/xmlseclibs, so until the latter [removes that dependency](https://github.com/robrichards/xmlseclibs/pull/101), we can't do anything.
