### ISSUE TITLE
500 error after login test

### ISSUE THREAD

**Issue by PradipShrestha** [simplesamlphp/simplesamlphp#528]
Hi,

I have configured saml login and everything seems okay. I do not have mcrypt installed and I have saml20-remote-idp with 
```php
 'keys' =>
    array (
      0 =>
        array (
          'encryption' => false,
          'signing' => true,
          'type' => 'X509Certificate',
          'X509Certificate' => '
```

However, when I test it, it shows saml login screen and gives 500 error after attempting to login. From log I got:
`Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] SimpleSAML_Error_Exception: Error 8 - Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128'
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] Backtrace:
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 10 /var/simplesamlphp/www/_include.php:75 (SimpleSAML_error_handler)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 9 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:89 (XMLSecurityKey::__construct)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 8 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecEnc.php:340 (XMLSecEnc::locateKey)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 7 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:388 (SAML2_Utils::doDecryptElement)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 6 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:529 (SAML2_Utils::decryptElement)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 5 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php:88 (SAML2_EncryptedAssertion::getAssertion)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 4 /var/simplesamlphp/modules/saml/lib/Message.php:371 (sspmod_saml_Message::decryptAssertion)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 3 /var/simplesamlphp/modules/saml/lib/Message.php:550 (sspmod_saml_Message::processAssertion)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 2 /var/simplesamlphp/modules/saml/lib/Message.php:524 (sspmod_saml_Message::processResponse)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:120 (require)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 0 /var/simplesamlphp/www/module.php:137 (N/A)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] SimpleSAML_Error_Exception: Error 8 - Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC'
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] Backtrace:
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 10 /var/simplesamlphp/www/_include.php:75 (SimpleSAML_error_handler)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 9 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:90 (XMLSecurityKey::__construct)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 8 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecEnc.php:340 (XMLSecEnc::locateKey)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 7 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:388 (SAML2_Utils::doDecryptElement)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 6 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:529 (SAML2_Utils::decryptElement)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 5 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php:88 (SAML2_EncryptedAssertion::getAssertion)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 4 /var/simplesamlphp/modules/saml/lib/Message.php:371 (sspmod_saml_Message::decryptAssertion)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 3 /var/simplesamlphp/modules/saml/lib/Message.php:550 (sspmod_saml_Message::processAssertion)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 2 /var/simplesamlphp/modules/saml/lib/Message.php:524 (sspmod_saml_Message::processResponse)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:120 (require)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 0 /var/simplesamlphp/www/module.php:137 (N/A)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] SimpleSAML_Error_Exception: Error 8 - Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128'
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] Backtrace:
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 9 /var/simplesamlphp/www/_include.php:75 (SimpleSAML_error_handler)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 8 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:293 (XMLSecurityKey::loadKey)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 7 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:466 (SAML2_Utils::doDecryptElement)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 6 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:529 (SAML2_Utils::decryptElement)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 5 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php:88 (SAML2_EncryptedAssertion::getAssertion)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 4 /var/simplesamlphp/modules/saml/lib/Message.php:371 (sspmod_saml_Message::decryptAssertion)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 3 /var/simplesamlphp/modules/saml/lib/Message.php:550 (sspmod_saml_Message::processAssertion)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 2 /var/simplesamlphp/modules/saml/lib/Message.php:524 (sspmod_saml_Message::processResponse)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:120 (require)
Dec 06 16:59:10 SimpleSAMLphp ERROR [8ba63b550d] 0 /var/simplesamlphp/www/module.php:137 (N/A)
~                                                                                                                                                                                                  
~                                                                                                  `

**If I refresh the page, I gets different set of error with log as** 

`Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] SimpleSAML_Error_Exception: Error 8 - Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128'
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] Backtrace:
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 10 /var/simplesamlphp/www/_include.php:75 (SimpleSAML_error_handler)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 9 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:89 (XMLSecurityKey::__construct)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 8 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecEnc.php:340 (XMLSecEnc::locateKey)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 7 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:388 (SAML2_Utils::doDecryptElement)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 6 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:529 (SAML2_Utils::decryptElement)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 5 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php:88 (SAML2_EncryptedAssertion::getAssertion)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 4 /var/simplesamlphp/modules/saml/lib/Message.php:371 (sspmod_saml_Message::decryptAssertion)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 3 /var/simplesamlphp/modules/saml/lib/Message.php:550 (sspmod_saml_Message::processAssertion)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 2 /var/simplesamlphp/modules/saml/lib/Message.php:524 (sspmod_saml_Message::processResponse)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:120 (require)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 0 /var/simplesamlphp/www/module.php:137 (N/A)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] SimpleSAML_Error_Exception: Error 8 - Use of undefined constant MCRYPT_MODE_CBC - assumed 'MCRYPT_MODE_CBC'
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] Backtrace:
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 10 /var/simplesamlphp/www/_include.php:75 (SimpleSAML_error_handler)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 9 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:90 (XMLSecurityKey::__construct)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 8 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecEnc.php:340 (XMLSecEnc::locateKey)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 7 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:388 (SAML2_Utils::doDecryptElement)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 6 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:529 (SAML2_Utils::decryptElement)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 5 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php:88 (SAML2_EncryptedAssertion::getAssertion)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 4 /var/simplesamlphp/modules/saml/lib/Message.php:371 (sspmod_saml_Message::decryptAssertion)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 3 /var/simplesamlphp/modules/saml/lib/Message.php:550 (sspmod_saml_Message::processAssertion)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 2 /var/simplesamlphp/modules/saml/lib/Message.php:524 (sspmod_saml_Message::processResponse)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:120 (require)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 0 /var/simplesamlphp/www/module.php:137 (N/A)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] SimpleSAML_Error_Exception: Error 8 - Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128'
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] Backtrace:
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 9 /var/simplesamlphp/www/_include.php:75 (SimpleSAML_error_handler)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 8 /var/simplesamlphp/vendor/robrichards/xmlseclibs/src/XMLSecurityKey.php:293 (XMLSecurityKey::loadKey)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 7 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:466 (SAML2_Utils::doDecryptElement)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 6 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Utils.php:529 (SAML2_Utils::decryptElement)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 5 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/EncryptedAssertion.php:88 (SAML2_EncryptedAssertion::getAssertion)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 4 /var/simplesamlphp/modules/saml/lib/Message.php:371 (sspmod_saml_Message::decryptAssertion)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 3 /var/simplesamlphp/modules/saml/lib/Message.php:550 (sspmod_saml_Message::processAssertion)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 2 /var/simplesamlphp/modules/saml/lib/Message.php:524 (sspmod_saml_Message::processResponse)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:120 (require)
Dec 06 17:08:53 SimpleSAMLphp ERROR [8ba63b550d] 0 /var/simplesamlphp/www/module.php:137 (N/A)
Dec 06 17:09:04 SimpleSAMLphp WARNING [8ba63b550d] Unable to find the SAML 2 binding used for this request.array (
)
Dec 06 17:09:04 SimpleSAMLphp WARNING [8ba63b550d] Request method: 'GET'array (
)
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] SimpleSAML_Error_Error: ACSPARAMS
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] Backtrace:
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] 1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:21 (require)
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] 0 /var/simplesamlphp/www/module.php:137 (N/A)
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] Caused by: Exception: Unable to find the current binding.
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] Backtrace:
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] 2 /var/simplesamlphp/vendor/simplesamlphp/saml2/src/SAML2/Binding.php:97 (SAML2_Binding::getCurrentBinding)
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] 1 /var/simplesamlphp/modules/saml/www/sp/saml2-acs.php:16 (require)
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] 0 /var/simplesamlphp/www/module.php:137 (N/A)
Dec 06 17:09:04 SimpleSAMLphp ERROR [8ba63b550d] Error report with id f480b179 generated.
`

Any suggestions?

Thanks,

CIsSharp

**Comment by tvdijen** [comment]
Well yes, my suggestion would be very easy...

|"Use of undefined constant _*MCRYPT*__RIJNDAEL_128"|

The clues won't get any clearer...
It's either installing /php-mcrypt/ or setting /'signing'////=>//false./

-Tim

Op 6-12-2016 om 18:26 schreef CIsSharp:

**Comment by jaimeperez** [comment]
Hi @PradipShrestha,

First of all, this is an issue tracker, not a [support forum](http://groups.google.com/group/simplesamlphp).

Apart from that, Tim is right. If you don't have _mcrypt_ installed and it complains about an undefined constant named _MCRYPT_RIJNDAEL_128_, it is pretty obvious what's going on.

**Comment by PradipShrestha** [comment]
Sure, appreciate it. Thanks
