### ISSUE TITLE
NameIDFormat not changing from transient despite being hardcoded to unspecified

### ISSUE THREAD

**Issue by KillerSquid** [simplesamlphp/simplesamlphp#535]
I'm going to start this by saying that I'm a complete newbie to SSO and SAML so be gentle.

I'm trying to use SimpleSAMLPHP (SSPHP from here on out) to connect a site (as SP) hosted on Dreamhost to our organization's log-in process for protected resources.  I've talked with our security officer and he set me up with the metadata for our IDP.  All is good there- we've got a connection being _requested_.  

Where we're running into a problem is that I need to send a request of NameIDFormat = `unspecified` from our SP on Dreamhost and no matter where I change it in the SSPHP  source code it's still sending a request for `transient`.

I see in the documentation for SSPHP that the saml20-sp-remote.php file takes priority so I added the line `'NameIDFormat' =>  'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',` to the metadata for our SP but it's still sending a transient request.  I've even gone so far in desperation as to do a global search of the SSPHP folder and hardcode that same line in everywhere the word 'transient' or 'nameidformat' appears.  Still no luck.

Any help is greatly appreciated

Here's the code from saml20-sp-remote.php:

	     $metadata['https://www.ourdomain.com'] = array(

 	     'AssertionConsumerService' => 'https://www.ourdomain.com/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp',

	     'SingleLogoutService' => 'https://www.ourdomain.com/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp',

         'NameFormat'=>'urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified',

         'NameIDFormat' =>  'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified',

         'description' => 
      	     array (
       	      'en' => 'our description',
      	     ),

      	     'OrganizationName' => 
      	     array (
        	     'en' => 'our org name',
      	     ),

     	      'name' => 
      	     array (
        	     'en' => 'our org name',
      	     ),

      	     'OrganizationDisplayName' => 
      	     array (
        	     'en' => 'our org name',
     	      ),

      	     'OrganizationURL' => 
      	     array (
        	     'en' => 'our org home site url',
      	     ),

	     );

**Comment by tvdijen** [comment]
Hello Dan,

I think you should set the |NameIDPolicy |in the authsource 
(config/authsources.php)

- Tim

Op 16-12-2016 om 17:38 schreef Dan Kaufman:

**Comment by KillerSquid** [comment]
@tvdijen - I tried that as well.  Still showing transient and not connecting.
![screen shot 2016-12-16 at 10 11 27 am](https://cloud.githubusercontent.com/assets/7477800/21273782/5a3d7092-c382-11e6-8f18-068852ca0e2f.png)

**Comment by tvdijen** [comment]
Well, I've just confirmed in a test that setting NameIdPolicy in 
authsources _does_ force the SP to request the 'unspecified' format in 
the authentication request.
The screenshot you provide seems to show what the IdP is sending you back..

Op 16-12-2016 om 19:25 schreef Dan Kaufman:

**Comment by tvdijen** [comment]
By the way..  The fact that you are able to provide the screenshot tells me that you have successfully authenticated against the IdP... So I wonder what the problem is you're having now...
Anyway, it's probably a good idea to take this to the [mailing list](https://simplesamlphp.org/lists), since this is a issue tracker and not a support-forum.. You'll get much more response there as well!

**Comment by KillerSquid** [comment]
@tvdijen Hmm.. I'll have to check with IT again.  The request they were showing yesterday was transient but we may have missed something on their end.  I'm gonna close for now but if anyone else has any thoughts please hit me up.  Thanks!

**Comment by tvdijen** [comment]
It's probably a good idea to install SAMLtracer, a plugin for Firefox.
It allows you to see the exact SAML XML of both the request and the response.
You can also make exports of it to attach to your support-requests on the mailing list.
