### ISSUE TITLE
IIS REQUEST_URI is not set

### ISSUE THREAD

**Issue by tamas-nagy-px** [simplesamlphp/simplesamlphp#540]
Hi,

Looks like the Internet Information Services has no `REQUEST_URI` defined in the PHP's `$_SERVER` array, and this is causing the simplesamlphp to thrown an exception:

```
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
1 C:\Project\simplesamlphp\www\_include.php:43 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: InvalidArgumentException: Unable to parse base url: http://localhost
Backtrace:
3 C:\Project\simplesamlphp\lib\SimpleSAML\Utils\HTTP.php:901 (SimpleSAML\Utils\HTTP::resolveURL)
2 C:\Project\simplesamlphp\lib\SimpleSAML\Utils\HTTP.php:753 (SimpleSAML\Utils\HTTP::normalizeURL)
1 C:\Project\simplesamlphp\lib\SimpleSAML\Utils\HTTP.php:832 (SimpleSAML\Utils\HTTP::redirectTrustedURL)
0 C:\Project\simplesamlphp\www\index.php:5 (N/A)
```

And also there are the undefined index notices: 

```
Notice: Undefined index: REQUEST_URI in C:\Project\simplesamlphp\lib\SimpleSAML\Utils\HTTP.php on line 652
Notice: Undefined index: REQUEST_URI in C:\Project\simplesamlphp\lib\SimpleSAML\Utils\HTTP.php on line 677
```

The "URL Rewrite 2.0" module is installed for IIS.
PHP version: 7.0.11 (the same happens with 5.6 as well)

**Comment by tvdijen** [comment]
https://davidwalsh.name/iis-php-server-request_uri

**Comment by tvdijen** [comment]
Hello Tamás!

I'm not sure IIS is officially supported, but the suggested fix in the link above seems pretty straightforward...
Could you replace your HTTP.php file with [this](https://raw.githubusercontent.com/tvdijen/simplesamlphp/c2fb66f570d93c15b7c85a5910471865283f2bcb/lib/SimpleSAML/Utils/HTTP.php) one to see if things work for you?

This is probably not a permanent fix since several modules rely on REQUEST_URI as well, but I think it would help to see if IIS-support is even possible with this little amount of effort..

**Comment by mimaen** [comment]
Hello,

The referenced post (Fixing IIS...) is from 2007! Maybe things have changed a bit since then...

I've checked a system with IIS 7.5 + PHP 5.3.1 and REQUEST_URI is set correctly. I think it's not IIS fault.

Could you check phpinfo? (there is a link on the Configuration tab of SSP)

Regards

**Comment by jaimeperez** [comment]
Hi @ycecube!

This looks like a bug in IIS. Could you please try with a later version of it?

In any case, it's probably a good idea to try to get around this issue if we detect that `$_SERVER['REQUEST_URI']` is missing.

**Comment by ycecube** [comment]
Hi all,

@jaimeperez I think I've the latest version of the IIS (bundled with win10): 10.0.14393.576

@tvdijen I would rather not hack the library :) It would be better to find a solution which doesn't include altering the release.

The REQUEST_URI was indeed provided by IIS in previous versions, I don't know why it was removed.

**Comment by tvdijen** [comment]
No feedback on the suggested fix and no more new cases of this 'bug'
