### ISSUE TITLE
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION

### ISSUE THREAD

**Issue by SalilLambe** [simplesamlphp/simplesamlphp#541]
We have deployed simplesamlphp plugin into one of our production application and have started facing an issue, when a user tries to login he gets to see a page 

![image](https://cloud.githubusercontent.com/assets/13847054/21774179/b5d9a7f2-d6b7-11e6-994f-e1b1e4d80198.png)

I have enabled the debug log and this is the piece from the logs 

Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457] Loading state: '_bae4dbe6d54c01f939321b1652c48c3d859f2b1aab'
Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457] Received SAML2 Response from 'https://xyz.abc.com:443/pqr'.
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] Backtrace:
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] 0 E:\wamp\www\AuthSP\www\module.php:180 (N/A)
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] Caused by: sspmod_saml_Error: Responder
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] Backtrace:
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] 3 E:\wamp\www\AuthSP\modules\saml\lib\Message.php:392 (sspmod_saml_Message::getResponseError)
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] 2 E:\wamp\www\AuthSP\modules\saml\lib\Message.php:499 (sspmod_saml_Message::processResponse)
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] 1 E:\wamp\www\AuthSP\modules\saml\www\sp\saml2-acs.php:120 (require)
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] 0 E:\wamp\www\AuthSP\www\module.php:137 (N/A)
Jan 09 09:15:11 simplesamlphp ERROR [b2cdbc1457] Error report with id bdbd09a1 generated.
Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457] Template: Reading [E:\wamp\www\AuthSP\dictionaries/errors]
Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457] Received message:
Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457] <samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="s255954b636186ae0f380f8472aca404e887cf726b" InResponseTo="_bae4dbe6d54c01f939321b1652c48c3d859f2b1aab" Version="2.0" IssueInstant="2017-01-09T14:15:11Z">
Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457]   <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://xyz.abc.com:443/openam</saml:Issuer>
Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457]   <samlp:Status xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457]     <samlp:StatusCode xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" Value="urn:oasis:names:tc:SAML:2.0:status:Responder"/>
Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457]   </samlp:Status>
Jan 09 09:15:11 simplesamlphp DEBUG [b2cdbc1457] </samlp:Response>

**Comment by jaimeperez** [comment]
Hi @SalilLambe,

This is an issue tracker, not a support forum. I don't see any issue in SimpleSAMLphp here, but just an error message being sent back to you from the IdP, so I recommend you to ask in the [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, I doubt anybody can help you out with such small amount of information. You really need to get in touch with the IdP to figure out what's going on.

**Comment by SalilLambe** [comment]
@jaimeperez Thanks for the information. Do you know someone who can help me out with this. Being it a production server, its really important that I should get to the roor cause or atleast find a fix to avoid these errors

**Comment by thijskh** [comment]
The IdP is sending an error message. You should look in the logs of the IdP to find out why it does that.

**Comment by SalilLambe** [comment]
@jaimeperez this is the error at iDP end 

libPlugins:01/09/2017 09:17:30:563 AM EST: Thread[http-nio-149.25.153.123-443-exec-10,5,main]
FMSessionProvider.getSession: Could not get the session from the HTTP request: Invalid session ID.

**Comment by SalilLambe** [comment]
@thijskh this is the error at iDP end

libPlugins:01/09/2017 09:17:30:563 AM EST: Thread[http-nio-149.25.153.123-443-exec-10,5,main]
FMSessionProvider.getSession: Could not get the session from the HTTP request: Invalid session ID.

**Comment by thijskh** [comment]
That software is not simpleSAMLphp. So you're not in the right place to ask questions about it.

**Comment by SalilLambe** [comment]
@thijskh the iDP is a product of openAM but the SP is simplesamlphp

**Comment by jaimeperez** [comment]
@SalilLambe as I just told you in the mailing list, the error is in the IdP, not in the SP. Therefore, there's no relation at all with SimpleSAMLphp.
