### ISSUE TITLE
State information lost when accessing a link from word document

### ISSUE THREAD

**Issue by SalilLambe** [simplesamlphp/simplesamlphp#542]
I have a link of my application which when accessed directly works well also when accessed through a mail works as expected but when the same link is pasted in a word document, the link gives a state information lost error.

**Comment by jaimeperez** [comment]
Hi @SalilLambe,

As I said previously somewhere else, this is an issue tracker, not a support forum. From SimpleSAMLphp's perspective, there's no difference between all the cases you are mentioning, so there can't be a bug in the software depending on that.

**Comment by SalilLambe** [comment]
@jaimeperez this is surely a bug i even checked https://groups.google.com/forum/#!topic/simplesamlphp/LcykPSQj_IQ . Please go through this.

**Comment by thijskh** [comment]
This is not a bug _in SimpleSAMLphp_ so it has no place here. The link you mention has several solutions on how to approach the problem, all of them do not require to modify SSP. I recommend you follow those.
