### ISSUE TITLE
Namespace not included on assertion

### ISSUE THREAD

**Issue by sebakerckhof** [simplesamlphp/simplesamlphp#543]
Simplesamlphp generates responses like:
```xml
<samlp:Response
	xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol"
	xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ...>
        ...
   	<saml:Assertion
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns:xs="http://www.w3.org/2001/XMLSchema" ...>
        ...
        </saml:Assertion>
</samlp:Response>
```

Almost any SAML response example you find also includes the namespace (`xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion"`) on the inner `saml:Assertion` tags.

While I believe it's not strictly necessary according to the XML spec, the problem is some libraries depend on this (e.g. https://github.com/Clever/saml2 ) and fail on responses from SimpleSamlPhp...

**Comment by thijskh** [comment]
The assertions are indeed valid according to spec. We run a different SAML implementation which also does not add this extra namespace and works fine with over 1000 different SPs. I think just Clever/saml2 is being too strict here and prefer to fix it there. I'm not convinced there's a wide-ranging compatibility issue here in SSP.
