### ISSUE TITLE
Problems with custom session_set_save_handler

### ISSUE THREAD

**Issue by drjayvee** [simplesamlphp/simplesamlphp#549]
`SessionHandlerPHP` does a neat job of detecting existing sessions, starting its own, and then restoring the previous session when `cleanup` is called (what a sweet feature!).

There is one issue that is overlooked, namely custom session handlers set through [`session_set_save_handler`](php.net/manual/en/function.session-set-save-handler.php). I could find no warning in the documentation, nor did the log contain any useful hints (even in `DEBUG` level).

Here's how I ran into this problem. Our application sets a database session handler and starts a session. When `Session::getSessionFromRequest()` is called, `SessionHandlerPHP::__construct` calls `session_write_close()` and reconfigures `session_id`, `session_name` and `cookie_params`. Then, a new session is started. This session is however stored using the custom session handler (and stored in the database).
When our application redirects the UA to SimpleSAML's own web UI, the browser sends SimpleSAML's cookie, but SimpleSAML cannot find the session (because the web UI uses the default session handler), and therefore starts a new session.
The reverse happens once the UA returns from the IdP and SimpleSAML redirects back to our application. Our application first sets the custom session handler, and SimpleSAML again cannot find the session, and creates a new one.

I'm not sure `SessionHandlerPHP` can or even should try to detect custom session handlers. As long as the SP and SimpleSAML's UI _use the same_ session handler, everything is fine. Unfortunately, there's no PHP function to determine and compare session handlers.

What would have helped though is a message in SimpleSAML's log when `SessionHandlerPHP` could not find the session even though a session cookie is set. The documentation should also contain warnings that any custom session handlers need to be unset (using `session_set_save_handler(new SessionHandler(), true);`) _before_ any calls to SimpleSAML (or more specifically, any calls that try to load a session), _unless_ the web UI uses the same one.

**Comment by jaimeperez** [comment]
Hi @drjayvee!

Thanks for opening this issue! We are aware of this and we've discussed a bit about it some time ago. Unfortunately, as you have noticed, it's not easy to resolve this in a completely transparent way.

We need to take a closer look at it and see if there is a way to avoid this issue. Of course, any help would be much appreciated!

**Comment by drjayvee** [comment]
Hey @jaimeperez, thanks for the quick reply.

I agree that this is going to be tricky to avoid. I think at least the documentation should contain a warning about this. Hopefully that will save other users time.

Also, `SessionHandlerPHP` could write a NOTICE or WARNING log when a session can't be found. The more likely scenario for a missing session is probably garbage collection (so WARNING is probably too high), but it took me a long time to find out _why_ SimpleSAML kept sending a new session cookie.

**Comment by drjayvee** [comment]
Hi @jaimeperez. I'm running into problems upgrading from 1.16.2 (with the two fixes for NameIDPolicy - see #771) to 1.17.0-rc3. (We have to upgrade because our application conflicts with Twig 1.x used by SimpleSAML 1.16).

I can log in using SimpleSAML's own "test authentication sources" feature. But when I test the integration with our application, it doesn't work.

Were there any changes between 1.16.2 and 1.17 that could cause issues with session handling? The changelog doesn't list any (as far as I can tell).

Here are the last lines of the (DEBUG) log:
```
 Decryption with key #0 succeeded.
 Has 1 candidate keys for validation.
 Validation with key #0 succeeded.
 Filter config for http://fs.koppert.com/adfs/services/trust->https://bestico.alis-asp.nl/newauth/module.php/saml/sp/metadata.php/default-sp: array (  0 =>   SimpleSAML\Module\core\Auth\Process\LanguageAdaptor::__set_state(array(     'langattr' => 'preferredLanguage',     'priority' => 90,  )),)
 Deleting state: '_a3d8894fddd08572319b908ca3dc8add7a8900698a'
 Session: doLogin("default-sp")
 Received message:
 <samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" ID="_379b4b5b-f5ed-41f6-87d7-733e65681f95" Version="2.0" IssueInstant="2019-02-26T13:41:25.809Z" Destination="https://bestico.alis-asp.nl/newauth/module.php/saml/sp/saml2-acs.php/default-sp" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" InResponseTo="_a3d8894fddd08572319b908ca3dc8add7a8900698a">
   <Issuer xmlns="urn:oasis:names:tc:SAML:2.0:assertion">http://fs.koppert.com/adfs/services/trust</Issuer>
   <samlp:Status>
     <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/>
   </samlp:Status>
   <EncryptedAssertion xmlns="urn:oasis:names:tc:SAML:2.0:assertion">
     <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Type="http://www.w3.org/2001/04/xmlenc#Element">
       <xenc:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"/>
       <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#">
         <e:EncryptedKey xmlns:e="http://www.w3.org/2001/04/xmlenc#">
           <e:EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
             <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
           </e:EncryptionMethod>
           <KeyInfo>
             <ds:X509Data xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
               <ds:X509IssuerSerial>
                 <ds:X509IssuerName>E=info@alis.nl, CN=bestico.alis-asp.nl, O=Alis, S=Utrecht, C=NL</ds:X509IssuerName>
                 <ds:X509SerialNumber>10975649900615904805</ds:X509SerialNumber>
               </ds:X509IssuerSerial>
             </ds:X509Data>
           </KeyInfo>
           <e:CipherData>
             <e:CipherValue>...</e:CipherValue>
           </e:CipherData>
         </e:EncryptedKey>
       </KeyInfo>
       <xenc:CipherData>
         <xenc:CipherValue>...</xenc:CipherValue>
       </xenc:CipherData>
     </xenc:EncryptedData>
   </EncryptedAssertion>
 </samlp:Response>
 Session: 'default-sp' not valid because we are not authenticated.
```

Everything seems to go fine until the very last line, which doesn't tell me what's going on.

Would you prefer if I wrote this up on the mailing list?

**Comment by jaimeperez** [comment]
Hi @drjayvee!

Yes, this is more for the mailing list, as you are not identifying any specific bug in the library. In any case, as far as I can tell, there weren't any changes that could break your integration from 1.16.2. The log you are showing looks perfectly normal, in fact.

**Comment by drjayvee** [comment]
Hey @jaimeperez,

After diving back into this problem after your helpful pointers in the [mailing list](https://groups.google.com/forum/#!topic/simplesamlphp/ntrczYHVvuM), I'm now very confident we should consider this a _documentation bug_.

[The documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-sp) advises to call
```
$session = SimpleSAML_Session::getSessionFromRequest();
$session->cleanup();
```
Unfortunately, _that does not work_ when the application uses a custom session handler, as we have discussed earlier.

Like I said in my first post, `SessionHandlerPHP` is smart enough to detect an active session and restore its config (id, name, cookie params) after `cleanup`. However, applications that use a custom session handler _must_ close their session by themselves, and restore the default session handler. `SessionHandlerPHP` will therefore not detect an active session, and will not do anything in `restorePrevious`.

Therefore, I think the documentation should explicitly warn users that session close and restore must be done manually if a custom session save handler is used.

If you agree, I'd be happy to create a PR for the documentation.

**Comment by jaimeperez** [comment]
Hi @drjayvee!

Sorry so much for the late response. You are right and I fully agree with you, this should be properly documented. Would you be able to provide a PR to update the documentation?

**Comment by drjayvee** [comment]
Hi @jaimeperez! Better late than never, right? :)

Yes, I will create a PR this week.

**Comment by tvdijen** [comment]
This issues can be closed now that the docs have been improved
