### ISSUE TITLE
Include simplesamlphp/modules/.gitignore in next release

### ISSUE THREAD

**Issue by clinta** [simplesamlphp/simplesamlphp#557]
The file simplesamlphp/modules/.gitignore has been in master since December 2015, but has not been included in any of the tagged releases.

Managing custom modules in a simplesamlphp installation that tracks the latest release is difficult without this.

**Comment by jaimeperez** [comment]
Hi @clinta!

Since that change didn't make it for 1.14, it was never included in any of the bugfix releases there. The problem will resolve itself in 1.15 as that will branch out of current master, but we can also try to include it if we release a 1.14.15 version.

**Comment by thijskh** [comment]
Since it's in master, this issue can just be closed I think?

**Comment by jaimeperez** [comment]
I just kept it open as a reminder to add the file to 1.14 in case we have another bugfix release.

**Comment by jaimeperez** [comment]
This is now in 1.14.15, so we can close the ticket.
