### ISSUE TITLE
Simplesamlphp SP testing behind reverse proxy

### ISSUE THREAD

**Issue by sharmaamitt16** [simplesamlphp/simplesamlphp#558]
I have configured my application and  simplesamlphp behind reverse proxy. I have created a test SP But when I am going to test the SP, it redirects to https://web-server-ip/adfs/ls/?SAMLRequest=nZL instead of redirecting to ADFS server url https://adfs.server.com/adfs/ls/?SAMLRequest=nZL

I have changed the baseurlpath in config.php to "https://web-server-ip/simplesaml". But still same error.
SP is working with App server. If I am trying to test the SP using https://app-server-ip/simplesaml, all working fine. 

But no luck via web server.

Please suggest any solution.

**Comment by jaimeperez** [comment]
Hi @sharmaamitt16,

This is an issue tracker, not a support forum. Please use our [user's mailing list](http://groups.google.com/group/simplesamlphp) to ask your question.
