### ISSUE TITLE
Cant get front page to load on SimpleSaml web page with ngnix

### ISSUE THREAD

**Issue by jesrig** [simplesamlphp/simplesamlphp#560]
I am trying to run simplesamlphp on nginx (config file listed below) but when I try loading the page, it redirects me here http://simplesamlphp.test/simplesaml/module.php/core/frontpage_welcome.php and says file not found. What is the issue here?

I have downloaded simplesamlphp via composer to a web project of my own (as its a dependency) and have symlinked the folder in the vendor folder to /var/www/simplesamlphp

server {
    listen 80;
    server_name simplesamlphp.test;
    error_log /var/log/nginx/error.log info;
    root /var/www/simplesamlphp/simplesamlphp/www;
    index index.php index.html index.htm;
    location / {
        # Don't touch PHP for static content.
        try_files $uri /index.php?$query_string;
    }
    location /simplesaml {
        alias /var/www/simplesamlphp/simplsamlphp/www;
        index index.php;
        location  ~ \.php$ {
            fastcgi_split_path_info ^(.+?\.php)(|/.*)$;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            fastcgi_intercept_errors on;
            fastcgi_read_timeout 60;
            include fastcgi_params;
            fastcgi_pass 127.0.0.1:9000;
        }
    }
    # Use fastcgi for all php files.
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+?\.php)(|/.*)$;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_intercept_errors on;
        fastcgi_read_timeout 60;
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
    }
}

**Comment by jaimeperez** [comment]
Hi @jesrig,

This is an issue tracker, not a support forum. Please use the [mailing list](http://groups.google.com/group/simplesamlphp) if you need help setting up your environment.
