### ISSUE TITLE
SimpleSAMLPHP + Encrypted Assertion from IDP

### ISSUE THREAD

**Issue by vlas** [simplesamlphp/simplesamlphp#562]
Good day,

Could you please assist if it is possible to use SimpleSAMLPHP project when response from the IdP is completely encrypted (not separate fields but the whole object). Looking at SAML2_EncryptedAssertion class it looks like it is completely empty (in comparison with SAML2_Assertion). Is there some working example of configuring/using simplesamlphp when response is encrypted ?

Thanks in advance!

**Comment by jaimeperez** [comment]
Hi @vlas!

This is an issue tracker, not a support forum. If you need assistance configuring or using SimpleSAMLphp, please use the [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, yes, SimpleSAMLphp supports of course both encrypted assertions and encrypted responses.
