### ISSUE TITLE
Simplesaml + Microsoft multi-tenant not working for external organisation email account

### ISSUE THREAD

**Issue by eawoonor** [simplesamlphp/simplesamlphp#563]
Hello Jamie et. al.,

I have setup simplesaml for my application and the following is my problem:

1. Single Sign On (SSO) works for users in my microsoft azure AD.
2. I enabled Multi-Tenant in my application configuration on Microsoft Azure
3. SSO fails for users who are not in my AD with "Bad request error".
4. I contacted Microsoft and we did a trace and it is evident that the users do not hit the endpoints for multi-tenant so they suggested these endpoints:
a. https://login.microsoftonline.com/external users home tenant guid/saml2?SAMLRequest
b. https://login.microsoftonline.com/common/saml2?SAMLRequest

I then modified simplesamlphp/metadata/saml20-idp-remote.php entered endpoint "b" from Microsoft for both **SingleSignOnService** and **SingleLogoutService**. 

> (How do I need to use or configure this endpoint?)

Now the external login works but crashes after the user is authenticated and shows the simplesaml error page with this information:

```
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION

Backtrace:
0 /var/www/simplesamlphp/www/module.php:180 (N/A)
Caused by: SimpleSAML_Error_Exception: Cannot retrieve metadata for IdP 'https://sts.windows.net/815abe80-2b90-467c-ac5e-b8849851356f/' because it isn't a valid IdP for this SP.
Backtrace:
2 /var/www/simplesamlphp/modules/saml/lib/Auth/Source/SP.php:112 (sspmod_saml_Auth_Source_SP::getIdPMetadata)
1 /var/www/simplesamlphp/modules/saml/www/sp/saml2-acs.php:91 (require)
0 /var/www/simplesamlphp/www/module.php:137 (N/A)
```

Kindly help.

Best regards,
Manny.

**Comment by jaimeperez** [comment]
Hi @eawoonor!

This is an issue tracker, not a support forum. If you need assistance configuring or using SimpleSAMLphp, please use the [mailing list](http://groups.google.com/group/simplesamlphp).
