### ISSUE TITLE
Library - LDAP bind(): Bind failed with DN

### ISSUE THREAD

**Issue by judokan9** [simplesamlphp/simplesamlphp#565]
I don't get my LDAP IdP up and running.

>  Authentication error in source 'ldap'. The reason was: 'Library - LDAP bind(): Bind failed with DN
>  \'uid="username",ou=people,dc="thecorrectdc",dc=de\'; cause: \'Can\'t contact LDAP server\' (0xffffffffffffffff)'

Output from /var/log/messages

> Library - LDAP bind(): Bind failed with DN 'uid="username",ou=people,dc="thecorrectdc",dc=de'; cause: 'Can't contact LDAP server' (0xffffffffffffffff)
> Unsuccessful login attempt from "CLIENT-IP"

My Setup:
CentOS Linux release 7.3.1611 (Core)
3.10.0-514.6.1.el7.x86_64

nginx version: nginx/1.10.2
PHP 7.0.16 (remi repo)

Configs:
[saml20-idp-hosted.txt](https://github.com/simplesamlphp/simplesamlphp/files/793531/saml20-idp-hosted.txt)
[authsources.txt](https://github.com/simplesamlphp/simplesamlphp/files/793532/authsources.txt)

On the LDAP server:
No entrys in the logs.

**Comment by jaimeperez** [comment]
Hi @judokan9!

This is an issue tracker, not a support forum. If you need assistance configuring or using SimpleSAMLphp, please use the [mailing list](http://groups.google.com/group/simplesamlphp).
