### ISSUE TITLE
allow easier integration of simplesaml as IDP in other projects

### ISSUE THREAD

**Issue by kaystrobach** [simplesamlphp/simplesamlphp#57]
Hello guys,

i do need to integrate simplesaml into an TYPO3 FLOW project.
I currently have a version, which is partly working based on a lot of reflection code.
IMHO there should be a guide / better way to integrate your great solution into ZF / TYPO3 FLOW / Symfony, what ever Framework, as this would spread the word a lot more.
If interested i can share my code with some thoughts lateron.

Thank you 
Kay

**Comment by jaimeperez** [comment]
Hi again @kaystrobach, and sorry for the delay!

This issue should now be solved as I just merged a contribution that makes it possible to specify the location of the `config` directory by means of an environment variable. It should no longer be necessary to have the configuration files or the metadata inside the source code directory.
