### ISSUE TITLE
LDAP Referrals flag, cannot set via config.

### ISSUE THREAD

**Issue by tsmgeek** [simplesamlphp/simplesamlphp#571]
In file "./modules/ldap/lib/Auth/Process/BaseFilter.php" on 251, I have to manually force referrals for AD lookups else my logins hang till timeout.
It would be good if this attribute can be set via 'ldap.referrals'.
I am having this problem when using 'AttributeAddFromLDAP'

**Comment by mschwager** [comment]
I can look into this for you! Should be a quick enough fix :+1:

**Comment by tvdijen** [comment]
I think this should cover it:
https://github.com/tvdijen/simplesamlphp/commit/9b57e5569f7981bfc3ce06b8f70d792f16520621

**Comment by mschwager** [comment]
@tvdijen that looks good, although I think you want `referrals` not `referals`.

**Comment by tvdijen** [comment]
Ohhhh crap... Today turns out to be not my day :(

New attempt:
https://github.com/tvdijen/simplesamlphp/commit/ac2fb6658df0ac284bcd9c60b9b79052d8bfea8c

**Comment by mschwager** [comment]
That looks good to me! Unfortunately I'm not able to test it right now. I'm sure it'd be fine to open the PR and discuss things there!

**Comment by tsmgeek** [comment]
Just updated to latest release and then realised that this had yet been merged in.

**Comment by tvdijen** [comment]
Stil happy to make a PR if someone, preferably @mschwager, can confirm to me that it works.

**Comment by jaimeperez** [comment]
@tvdijen wasn't #587 addressing precisely this issue? Did @mschwager or @tsmgeek test that?

**Comment by tvdijen** [comment]
Ohhh right, I already did the PR.. No, nothing has been tested yet...

**Comment by jaimeperez** [comment]
It's good to see I'm not the only one who does something and then forgets... 😅 

In any case, this has a 👍  from me as long as someone can test it properly.
