### ISSUE TITLE
assert() with string as the assertion is DEPRECATED as of PHP 7.2

### ISSUE THREAD

**Issue by moffe42** [simplesamlphp/simplesamlphp#573]
Just a heads up. From http://php.net/manual/en/function.assert.php 

Using string as the assertion is DEPRECATED as of PHP 7.2.

SSP is littered with assertions taking a string argument.

**Comment by jaimeperez** [comment]
Thanks for the heads up!

We'll need to address this, though luckily we have time if this is being deprecated in 7.2. In any case, I think it would be wise to go away from `assert()` completely, as we've been discussing several times...

**Comment by camilo-globant** [comment]
Hi. Was this already solved?

By taking a look at the assert functions in _v1.16.2_ I can see that the string parameter is not used anymore.

Should we consider this as solved?

**Comment by TomasVotruba** [comment]
Thanks for the pull-request reference, it helped me verify the A → B change.

I've added `assert` *unstringify* change to Rector, a tool for instant upgrades - https://github.com/rectorphp/rector/pull/842/commits/ea884bb6d874bd4c055971c6d36ee53666642303#diff-358dd3c214994e89517e0881c9206c3f

Basically the PR, just automated
