### ISSUE TITLE
Support for Redis as session storage

### ISSUE THREAD

**Issue by ssurenr** [simplesamlphp/simplesamlphp#574]
Simplesamlphp have a facility for configuring memcached as session storage. With increasing popularity of Redis, simplesamlphp should consider native support for redis as caching backend.

**Comment by jaimeperez** [comment]
Hi @ssurenr!

I'm not entirely sure what you mean with _caching backend_, but I understand you mean using Redis to store sessions the same way we use memcache or a SQL backend.

In any case, contributions are always welcome! 😉

**Comment by tvdijen** [comment]
https://github.com/ColourboxDevelopment/simplesamlphp-module-redis

**Comment by mschwager** [comment]
I was actually thinking about this recently too. I'll work on a PR.
