### ISSUE TITLE
Passing domain_hint to avoid AADSTS50020 error

### ISSUE THREAD

**Issue by kbrabrand** [simplesamlphp/simplesamlphp#576]
Disclaimer: I'm new to and a bit confused by the world of SAML, azure, idps and service providers. I might mix the different terms, so if something is unclear - please ask!

I've set up a service provider that authenticates against SAML2.0 from azure ad which in turn authenticates users agains the company identity provider. Everything works fine, and my application gets the correct information. Everyone is happy. But.

The application in azure ad is [obviously] set up to authenticate using the company tenant, and not live.com, but for some reason users who are logged into their microsoft/live.com account gets an [error message similar to this one](https://www.stephenmann.net/single-post/2016/11/03/Fix-Azure-AD-Error-AADSTS50020-when-logged-in-user-doesnt-have-permissions-to-selected-Application). It seems as if the login url misses a piece of information (the `domain_hint` parameter?), and everything stops when the live.com user doesn't exist in the tenant.

How do I go about fixing this? This article https://www.stephenmann.net/single-post/2016/11/03/Fix-Azure-AD-Error-AADSTS50020-when-logged-in-user-doesnt-have-permissions-to-selected-Application refers to a `domain_hint` parameter that is supposed to fix it. I tried setting the `discoHints` in the `saml20-idp-remote.php` config file:

```php
$metadata['https://sts.windows.net/0c7d7191-c91c-47ee-a394-60d65903fb55/'] = [
  ...,
  'DiscoHints' => [
    'DomainHint' => ['customerdomain.com']
  ]
]
```

I was kind of hoping that ☝️ would catch the fact that the logged in user didn't have an email address that ended with @customerdomain.com, but it didn't seem to have any affect at all.

**Comment by jaimeperez** [comment]
Hi @kbrabrand!

This is an issue tracker, not a support forum. If you need assistance configuring or using SimpleSAMLphp, please use the [mailing list](http://groups.google.com/group/simplesamlphp).

Anyway, this looks like a Microsoft issue. There's no such parameter `domain_hint` defined in the SAML standard, and therefore SimpleSAMLphp doesn't allow you to set that. The `DiscoHints` option is for [something completely different](https://simplesamlphp.org/docs/stable/simplesamlphp-metadata-extensions-ui#section_2).

**Comment by kbrabrand** [comment]
👍 It was indeed a Microsoft "issue". For the record, if anyone finds this thread by search, appending `whr=customerdomain.com` to the `Single*ServiceUrl` like this works and the user is immediately redirected to the correct tenant for that domain:

```
https://login.microsoftonline.com/[tenantid]/saml2?whr=customerdomain.com
```

**Comment by jaimeperez** [comment]
Great! I'm glad you solved it, and thanks for sharing the solution here with us! 😄

**Comment by wongjustin99** [comment]
That saved me! I was banging my head trying to use that `domain_hint` parameter.
