### ISSUE TITLE
SP dont' work

### ISSUE THREAD

**Issue by olivierbrochard** [simplesamlphp/simplesamlphp#577]
Hi,

I have 2 servers:
server 1 : simplesamlphp - IDP
server 2 : simplesamlphp - SP

the implementation on IDP in server 1 works 👍 
i used "example-userapss", and i succeed connect 
http://myidp/simplesaml
Authentification > example-userpass
log : student
pwd : studentpass
-> Attributes are dispplayed

the implementation on SP in server 2 doesn't work 
 
config/authsources.php
<?php
$config = array (
'default-sp' => array (   
'saml:SP',    
 ),
)
?>

metadata/saml20-idp-remote.php
<?php
$metadata['http://myidp']= array (
      'name' => array ('fr => 'My SSO',),
      'SingleSignOnService' => 'http://myidp/simplesaml/saml2/idp/SSOService.php',
      'SingleLogoutService' => 'http://myidp/simplesaml/saml2/idp/SingleLogoutService.php',
);
?>

Error
Caused by: Exception: Invalid <username>:<password> for authentification sourc exemple-userpass: entityID

Why login SSO doesn't dispayed ?!?

**Comment by jaimeperez** [comment]
Hi @olivierbrochard!

This is an issue tracker, not a support forum. If you need assistance configuring or using SimpleSAMLphp, please use the [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, the contents of your `authsources.php` and `metadata/saml20-idp-remote.php` files look wrong. Make sure you follow the documentation and use the configuration templates for both.
