### ISSUE TITLE
Issue with long site names and SQL session Logout store

### ISSUE THREAD

**Issue by sergiofcasado** [simplesamlphp/simplesamlphp#579]
After switching from memcache to MySQL as session backend, I have been getting an exception when inserting a new row in <prefix>_saml_LogoutStore table.

SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
0 /simplesamlphp/www/module.php:180 (N/A)
Caused by: PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column '_authSource' at row 1

After inspecting the code, I saw that _authSource contains the sitename, and in /simplesamlphp/modules/saml/lib/SP/LogoutStore.php the table that is being created limits the size of this value to 30.
In our company we allow for longer names, so the problem is fully understood.

The obvious workaround for us would be increase that value to comply with our company's naming policies, but I would like to ask if you foresee any side effect in doing so.

Cheers.

**Comment by jaimeperez** [comment]
Hi @sergiofcasado!

The enhancement you are suggesting is probably a bit of an overkill, as I don't think you'll ever have authIDs so long, but I don't think it'll harm anyway.

I'm curious, why are you using authIDs that long?

**Comment by thijskh** [comment]
Because it's _VAR_CHAR there's no difference in storage between using 30 or 255 if you have short id's, so I think 255 is fine.

**Comment by rwmanos** [comment]
Hello @jaimeperez,

We use the domain name as the authID. So we avoid collisions with other web applications that use the same identity provider or something like unique incremental numbers. And a domain name can exceed the 30 characters if a long hostname is used since we already append a pretty long subdomain of about 13 characters.

Thanks a lot for the reply and the comments on the PR!

**Comment by jaimeperez** [comment]
Thanks for the explanation @rwmanos! I certainly see why you are doing it like that...

Anyway, I'm closing the issue here given that we have #596. Let's continue the discussion there so that we can merge it as soon as possible.
