### ISSUE TITLE
State ID Generation

### ISSUE THREAD

**Issue by phillclark** [simplesamlphp/simplesamlphp#582]
Not an issue but struggling to identify where the code base the random state ID is generated for use within the XML (eg. `ID="_3dc8d334356929bf0997ffb357d6108c521605c43b"`).

Can anyone point me in the right direction please?

**Comment by thijskh** [comment]
https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/Random.php

**Comment by phillclark** [comment]
Thanks @thijskh
