### ISSUE TITLE
Inline JavaScripts do not allow secure Content Security Policy

### ISSUE THREAD

**Issue by martin-kuba** [simplesamlphp/simplesamlphp#593]
I have an installation of SimpleSamlPHP 1.14 and I have tried to achieve "A" rating of my site at https://securityheaders.io/ The tool checks for having a Content Security Policy defined by a HTTP header. 
The problem is that SimpleSamlPHP uses a lot of in-line JavaScripts and CSS styles, so the policy must contain "style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline';" to keep them working, but such setting is considered as insecure because in-line scripts and styles can be injected by an attacker.

The recommended solution is to move all scripts and style into separate files and link them.

See https://en.wikipedia.org/wiki/Content_Security_Policy and https://hacks.mozilla.org/2016/02/implementing-content-security-policy/ for details on CSP.

**Comment by thijskh** [comment]
There's an ongoing effort to move to Twig templates. The move of JS from inline to separate files will be tackled as part of that effort, and/or be much simpler after that change. You're welcome to help move the Twig changes forward!

**Comment by tvdijen** [comment]
Only two cases left:
- consent/www/getconsent.php for showing/hiding attribute-values
- templates/includes/header.php does an onload for autofocus

**Comment by thijskh** [comment]
Largely solved in new UI.
See #950 for remaining case.
Any other cases found should also have new issues created.
