### ISSUE TITLE
Error report emails not delivered because of wrong from address

### ISSUE THREAD

**Issue by kjkooistra-youwe** [simplesamlphp/simplesamlphp#595]
File: https://github.com/simplesamlphp/simplesamlphp/blob/master/www/errorreport.php
Lines: 104 and 107

The from address is set to either the email address filled in in the report form or a default address. However these emails are blocked because of SPF records. The from address should be explicitly set to an email address matching the domain. Overriding it to a hard coded value with matching domain solved the issue for me on a production environment.

Possible solution: Introduce a configuration option to set the value.

Relevant information:
http://www.html-form-guide.com/email-form/php-script-not-sending-email.html
http://stackoverflow.com/questions/27198715/spf-issue-when-sending-automatic-email-with-php#answer-27198758

**Comment by thijskh** [comment]
Yes, would be a nice improvement. Could you provide a PR?

**Comment by kjkooistra-youwe** [comment]
Hi. I have no idea how to create a new bugfix branch here, so I've added a patch file instead (git diff).
[patch.patch.zip](https://github.com/simplesamlphp/simplesamlphp/files/909493/patch.patch.zip)

**Comment by tvdijen** [comment]
Would it help if I make a PR from the patch-file so we can close this issue?

**Comment by thijskh** [comment]
Yes, definitely.

**Comment by tvdijen** [comment]
There you go
