### ISSUE TITLE
Parsing relayState

### ISSUE THREAD

**Issue by Mojster** [simplesamlphp/simplesamlphp#598]
Hi,

we're using simplesamlphp with shibboleth.
So the display language is set on user browser setting.

We've put a language param into relayState. And now I'm searching for an option to get this param out of relayState and set it as current language. Ignoring the browser one.

After a turning simplesamlphp around, I still didn't find a way to decrypt relayState.

Could you please advise me further how to make this possible. Thanks.

**Comment by jaimeperez** [comment]
Hi @Mojster!

This is an issue tracker, not a support forum. If you need assistance configuring or using SimpleSAMLphp, please use the [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, the `RelayState` is not intended to be consumed by others than the same entity that set it originally, and in that case if you are the one setting `RelayState`, you should find alternative ways to change the language than this. Is SimpleSAMLphp the IdP or the SP? How are you setting the `RelayState`?
