### ISSUE TITLE
How to use SSL server with simplesamlphp

### ISSUE THREAD

**Issue by rakicivan** [simplesamlphp/simplesamlphp#609]
![image](https://cloud.githubusercontent.com/assets/17475034/25773951/50099f00-3287-11e7-8abf-e62def3fce69.png)
i cant register because i have SSL cert. on domain..  ? 

how to fix that? 

tnx all!

**Comment by thijskh** [comment]
This is not a support forum. Please send your questions to the [user mailinglist](https://simplesamlphp.org/lists).
