### ISSUE TITLE
After login if user hit back button, an exception happens

### ISSUE THREAD

**Issue by hosseinis** [simplesamlphp/simplesamlphp#61]
To solve the problem, I updated the following code starting on line `217` in `saml/lib/SimpleSAML/Auth/State.php`:

```
$id = $tmp[0];
    if (count($tmp) === 2 || isset($_REQUEST['RelayState'])) {
            $restartURL = (count($tmp) === 2 && !isset($_REQUEST['RelayState'])) ? $tmp[1] : $_REQUEST['RelayState'];
    } else {
            $restartURL = NULL;
    }
```

**Comment by tvdijen** [comment]
This may have been an issue 4 1/2 years ago, but I can't reproduce this anymore..
Hitting the back-button shows me the IDP's login screen again

**Comment by peterjc-123** [comment]
Hair coco friendship
