### ISSUE TITLE
Dead website links

### ISSUE THREAD

**Issue by mschwager** [simplesamlphp/simplesamlphp#611]
Hey all,

I've been working on this new tool [riplink](https://github.com/mschwager/riplink), which finds dead links. It appears to have found some on the SimpleSAMLphp website:

```
$ riplink -timeout 5 -url https://simplesamlphp.org -depth 5 -same-domain
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.6 404
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.5 404
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.11 404
https://simplesamlphp.org/simplesamlphp-changelog 404
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.12 404
https://simplesamlphp.org/./saml:sp 404
https://simplesamlphp.org/./simplesamlphp-scoping 404
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.10 404
https://simplesamlphp.org/simplesamlphp-sp 404
https://simplesamlphp.org/simplesamlphp-install-repo 404
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.14 404
https://simplesamlphp.org/./simplesamlphp-artifact-idp 404
https://simplesamlphp.org/simplesamlphp-hok-sp 404
https://simplesamlphp.org/./consentAdmin:consentAdmin 404
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.9 404
https://simplesamlphp.org/simplesamlphp-sp-migration 404
https://simplesamlphp.org/./consent:consent 404
https://simplesamlphp.org/./simplesamlphp-customauth 404
https://simplesamlphp.org/simplesamlphp-reference-idp-remote 404
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.13 404
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.8 404
https://simplesamlphp.org/simplesamlphp-idp 404
https://simplesamlphp.org/simplesamlphp-upgrade-notes-1.7 404
https://simplesamlphp.org/simplesamlphp-maintenance 404
https://simplesamlphp.org/simplesamlphp-errorhandling 404
https://simplesamlphp.org/simplesamlphp-reference-sp-remote 404
https://simplesamlphp.org/simplesamlphp-translation 404
https://simplesamlphp.org/simplesamlphp-automated_metadata 404
https://simplesamlphp.org/./saml:keyrollover 404
https://simplesamlphp.org/simplesamlphp-idp-more 404
https://simplesamlphp.org/./autotest:test 404
https://simplesamlphp.org/simplesamlphp-theming 404
https://simplesamlphp.org/./simplesamlphp-authsource 404
https://simplesamlphp.org/simplesamlphp-reference-idp-hosted 404
https://simplesamlphp.org/simplesamlphp-install 404
https://simplesamlphp.org/./simplesamlphp-artifact-sp 404
https://simplesamlphp.org/simplesamlphp-hok-idp 404
https://simplesamlphp.org/./aggregator:aggregator 404
https://simplesamlphp.org/simplesamlphp-authproc 404
https://simplesamlphp.org/./InfoCard:usage 404
https://simplesamlphp.org/simplesamlphp-subversion 404
https://simplesamlphp.org/./authorize:authorize 404
https://simplesamlphp.org/simplesamlphp-modules 404
https://simplesamlphp.org/simplesamlphp-nostate 404
https://simplesamlphp.org/simplesamlphp-googleapps 404
https://simplesamlphp.org/./statistics:statistics 404
https://simplesamlphp.org/simplesamlphp-advancedfeatures 404
https://simplesamlphp.org/./riak:simplesamlphp-riak 404
https://simplesamlphp.org/pack 404
https://simplesamlphp.org/./openidProvider:provider 404
https://simplesamlphp.org/simplesamlphp-ukaccess 404
https://simplesamlphp.org/./radius:radius 404
https://simplesamlphp.org/./authwindowslive:windowsliveid 404
https://simplesamlphp.org/./multiauth:multiauth 404
https://simplesamlphp.org/./core:authproc_attributealter 404
https://simplesamlphp.org/./core:authproc_scopefromattribute 404
https://simplesamlphp.org/./authlinkedin:oauthlinkedin 404
https://simplesamlphp.org/./simplesamlphp-upgrade-notes-1.6 404
https://simplesamlphp.org/./simplesamlphp-metadata-endpoints 404
https://simplesamlphp.org/./core:authproc_php 404
https://simplesamlphp.org/./core:authproc_attributemap 404
https://simplesamlphp.org/./saml:nameid 404
https://simplesamlphp.org/./aggregator2:aggregator2 404
https://simplesamlphp.org/./authmyspace:oauthmyspace 404
https://simplesamlphp.org/./cas:cas 404
https://simplesamlphp.org/./simplesamlphp-hok-sp 404
https://simplesamlphp.org/./simplesamlphp-hok-idp 404
```

From here we can find the offending code:

```
$ git grep "upgrade-notes-1.6"
docs/index.md:    * [Upgrade notes for version 1.6](simplesamlphp-upgrade-notes-1.6)
docs/simplesamlphp-changelog.md:[Upgrade notes](./simplesamlphp-upgrade-notes-1.6)
```

**Comment by jaimeperez** [comment]
Hi @mschwager!

Thanks for the feedback! However, I'm failing to find the sources of these dead links. The two examples you are giving for `simplesamlphp-upgrade-notes-1.6` are just fine, given that both files (`docs/index.md` and `docs/simplesamlphp-changelog.md`) are accessed through `simplesamlphp.org/docs/stable/` and `simplesamlphp.org/docs/stable/simplesamlphp-changelog`.

Do you have any examples that we can verify live on a specific URL?

**Comment by mschwager** [comment]
Thanks for the info! This actually helped me find one bug in my tool: https://github.com/mschwager/riplink/commit/ca3b3dbee7ea1c57c64b1179566d40398d5fccc3

That commit fixed the bug with finding "dead" links like `https://simplesamlphp.org/./consent:consent`.

It appears as though there's another bug that needs fixing though. My tool appears to have issues with redirects, which makes sense since it's just doing string processing with hrefs and the current domain it's searching. E.g.

On https://simplesamlphp.org the Documentation link points to https://simplesamlphp.org/docs, but when you visit that link you're actually redirected to https://simplesamlphp.org/docs/stable/. That's why it's 404'ing on links like `https://simplesamlphp.org/simplesamlphp-changelog` because it should really be `https://simplesamlphp.org/docs/stable/simplesamlphp-changelog`.

I'm going to close this issue since it appears as though none of the links are actually "dead." I have one question though. How is this redirect or URL rewrite being performed? Is your webserver taking some action to make it happen?

Thanks for helping me improve my tool!

**Comment by jaimeperez** [comment]
Hi @mschwager!

It's not the web server doing the redirection, or any kind of URL rewrite. It's just the PHP code serving the pages, that performs a redirect when no version of the documentation has yet been selected.

In any case, your tool should never see links like the ones you are describing (e.g. `https://simplesamlphp.org/simplesamlphp-changelog`). It's not like the links are there and the web server rewrites the URL or some magic script _translates_ those into the real URLs. There are no such links in the website. Note that when you are building URLs from relative links, thinks like `something/something` or `./something/something` must be considered relative to the _directory_ of the current URL, that is, the target of the redirection if you just got one.

**Comment by mschwager** [comment]
I think you just found the bug:

> Note that when you are building URLs from relative links, thinks like something/something or ./something/something must be considered relative to the directory of the current URL, that is, the target of the redirection if you just got one.

My issue is I'm making relative links relative to the hostname, not the hostname and the directory of the current URL. I'll investigate, thanks again!
