### ISSUE TITLE
Error: 34444ffbf4 in setup SimpleSAMLphp

### ISSUE THREAD

**Issue by seemajain0891** [simplesamlphp/simplesamlphp#614]
HI,

I am setting up SSO using SimpleSAMLPHP in drupal, I have set this up but once i login It throws below error:
Unhandled exception
An unhandled exception was thrown.
If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator:

34444ffbf4
I have setup this urgently, PLease help me on this issue so I can resolve the problem.

Thanks
Seema

**Comment by thijskh** [comment]
This is not a support forum. Please use the mailing list for support questions. https://simplesamlphp.org/lists

When you contact the mailing list, make sure to include the full error message that you can find in your webserver log with the given ID.
