### ISSUE TITLE
Display issues on mobile devices: no submit (login) button visible

### ISSUE THREAD

**Issue by poikilotherm** [simplesamlphp/simplesamlphp#618]
Hey guys,

while creating a custom theme, I discovered that on mobile devices the login button is missing, see screenshots below.

I'm pretty sure you guys fixed this in #359, but making valid XHTML in #479 (found via blame) introduced the third `<td></td>`. This makes things valid, but breaks the view.

Shall I open a PR? How did you guys ensure XHTML validity, so not to break goals of #479 by the new fix?

Cheers,
Oliver

![ssp-error-portrait](https://cloud.githubusercontent.com/assets/5468333/26404937/e9239d66-4093-11e7-8883-ef635b838c5c.png)
![ssp-error-landscape](https://cloud.githubusercontent.com/assets/5468333/26404938/e949bac8-4093-11e7-8f10-e17a3b9028ca.png)

**Comment by jaimeperez** [comment]
Hi @poikilotherm! Thanks for reporting this!

Of course, a PR fixing the issue would be really nice, if you don't mind 😄

**Comment by poikilotherm** [comment]
Here you are... ;-) Also this doesn't fix the table width issue, but this is a story for another day...

**Comment by tvdijen** [comment]
I've tried on my own IdP on several phones and they do show a login-button, however it is outside of the screen, so one would have to scroll to the right...

The fix to this is actually a lot less complicated as what you're suggesting in your PR..
My suggestion would be this:

https://github.com/tvdijen/simplesamlphp/commit/bbcbc8c83a33e023183da29bff9102552f22c412

**Comment by poikilotherm** [comment]
Hi @tvdijen,

I agree that my description of "invisible" was not very precise - I sticked with the wording in #359.

About the complexity: I tried to revert the hacky workaround of hiding different table row via CSS introduced in daafee5, as it introduced more HTML and CSS code than necessary. One could argue that it would be even cleaner to use a proper `rowspan="3"`, a `vertical-align: top;` for the icon `<td>` and remove one of the empty cells, but this would break the current design and I intended to avoid that all cost (users complain even about moved icons on their desktop...)

I tried your fix on my IdP and noted the design break (the button moves to the outer left). Was that on purpose?

Cheers,
Oliver

**Comment by tvdijen** [comment]
That was on purpose yes.. I must admit I didn't take the time to see what it looked like on mobile phones before the #359/#479 changes... The username/password fields are also way too wide on my phones..

We shouldn't put to much effort in this, since we're moving to Twig templates in the next major release (i think).

**Comment by poikilotherm** [comment]
Oh, didn't know about that planned change.

I fixed the width issue in my custom template by adding a `width: 95%` to the mobile style of `input#username` and `input#password`.

Please continue as you dev guys prefer... :-) Don't know how much effort this is, as a PR already exists.

**Comment by thijskh** [comment]
Merged #618 fixing this issue
