### ISSUE TITLE
Encrypted attributes are not decrypted on assertion decryption

### ISSUE THREAD

**Issue by thebuh** [simplesamlphp/simplesamlphp#621]
Hi all, 

Im receiving assertions from idP in which both body of assertion and attributes are encrypted. And while SSP is decrypting body of assertion correctly attributes are left encrypted. 

There is a code for handling encrypted attributes in assertion ( https://github.com/simplesamlphp/saml2/blob/master/src/SAML2/Assertion.php#L811 ) but its not referenced anywhere within SSP.

For example if i would add call to attribute decryption here:
https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Message.php#L367
change from
```
try {
                $ret = $assertion->getAssertion($key, $blacklist);
                SimpleSAML\Logger::debug('Decryption with key #'.$i.' succeeded.');
                return $ret;
            }
```
to
```
try {
                $ret = $assertion->getAssertion($key, $blacklist);
                $ret->decryptAttributes($key,$blacklist);
                SimpleSAML\Logger::debug('Decryption with key #'.$i.' succeeded.');
                return $ret;
            }
```

Everything works as expected and attributes show up correctly later in session. 

I was wondering if this is a bug or expected behaviour (for example if i supposed to decrypt attributes later manually).
Theres nothing about this case in documentation or in mailing list so i assume its a bug.

**Comment by jaimeperez** [comment]
Hi @thebuh!

That sounds like a bug, yes. However, your fix is not proper, as it only takes into account the case where both the assertion and the attributes are encrypted, while the latter should be decrypted regardless of whether the assertion was encrypted or not.

I've implemented a fix for this, but unfortunately I don't have access right now to a test setup that I can use to test that it works fine. Would you mind applying this patch and telling me if it works for you?

```patch
diff --git a/modules/saml/lib/Message.php b/modules/saml/lib/Message.php
index 36d0e28..c555d61 100644
--- a/modules/saml/lib/Message.php
+++ b/modules/saml/lib/Message.php
@@ -408,6 +408,51 @@ class sspmod_saml_Message


     /**
+     * Decrypt any encrypted attributes in an assertion.
+     *
+     * @param SimpleSAML_Configuration $srcMetadata The metadata of the sender (IdP).
+     * @param SimpleSAML_Configuration $dstMetadata The metadata of the recipient (SP).
+     * @param \SAML2\Assertion|\SAML2\Assertion $assertion The assertion containing any possibly encrypted attributes.
+     *
+     * @return void
+     *
+     * @throws \SimpleSAML_Error_Exception if we cannot get the decryption keys or decryption fails.
+     */
+    private static function decryptAttributes(
+        SimpleSAML_Configuration $srcMetadata,
+        SimpleSAML_Configuration $dstMetadata,
+        \SAML2\Assertion &$assertion
+    ) {
+        if (!$assertion->hasEncryptedAttributes()) {
+            return;
+        }
+
+        try {
+            $keys = self::getDecryptionKeys($srcMetadata, $dstMetadata);
+        } catch (Exception $e) {
+            throw new SimpleSAML_Error_Exception('Error decrypting attributes: '.$e->getMessage());
+        }
+
+        $blacklist = self::getBlacklistedAlgorithms($srcMetadata, $dstMetadata);
+
+        $error = true;
+        foreach ($keys as $i => $key) {
+            try {
+                $assertion->decryptAttributes($key, $blacklist);
+                SimpleSAML\Logger::debug('Attribute decryption with key #'.$i.' succeeded.');
+                $error = false;
+                break;
+            } catch (Exception $e) {
+                SimpleSAML\Logger::debug('Attribute decryption failed with exception: '.$e->getMessage());
+            }
+        }
+        if ($error) {
+            throw new SimpleSAML_Error_Exception('Could not decrypt the attributes');
+        }
+    }
+
+
+    /**
      * Retrieve the status code of a response as a sspmod_saml_Error.
      *
      * @param \SAML2\StatusResponse $response The response.
@@ -609,6 +654,7 @@ class sspmod_saml_Message
         assert('is_bool($responseSigned)');

         $assertion = self::decryptAssertion($idpMetadata, $spMetadata, $assertion);
+        self::decryptAttributes($idpMetadata, $spMetadata, $assertion);

         if (!self::checkSign($idpMetadata, $assertion)) {
             if (!$responseSigned) {
```

**Comment by thebuh** [comment]
Sorry, unfortunately i don't have access to the idP with this specific configuration anymore so i can't verify your fix.

**Comment by thijskh** [comment]
@jaimeperez Postpone to 1.16 milestone then?

**Comment by jaimeperez** [comment]
Yep, I've just changed it.

**Comment by californiumguy** [comment]
Hi @jaimeperez,

I've just verified provided patch against 1.15.4 and it works fine. After applying this patch all encrypted attributes have been successfully decrypted in the case of the encrypted/non-encrypted assertion.

**Comment by thijskh** [comment]
@jaimeperez Given @californiumguy's configirmation do you think you can turn your patch into a PR and/or commit it?

**Comment by jaimeperez** [comment]
Done!
