### ISSUE TITLE
PHP 7 Support

### ISSUE THREAD

**Issue by manuelDistefano** [simplesamlphp/simplesamlphp#636]
I'm sorry but i can't find any clear info about that. Is simplesamlphp supporting PHP 7? If yes, is it supporting php 7.1?

From which version php 7 is supported? I'm currently using 1.14.11

Tnx

**Comment by thijskh** [comment]
Yes, the requirement as documented is PHP version >= 5.3.0, so PHP 7 is supported.

If you find any error with 7 please file an issue or better, a pull request.
