### ISSUE TITLE
Adding email to google android account ERROR please help

### ISSUE THREAD

**Issue by amg21608** [simplesamlphp/simplesamlphp#645]
Sign In   SSPU   TSTC Edu
Bad request received

There is an error in the request to this page. The reason was: Missing AuthState parameter.
If you report this error, please also report this tracking number which makes it possible to locate your session in the logs available to the system administrator:	29a7dff1ef
Debug information

The debug information below may be of interest to the administrator / help desk:

SimpleSAML_Error_BadRequest: BADREQUEST('%REASON%' => 'Missing AuthState parameter.')
Backtrace:
1 /opt/simplesamlphp-1.12.0/modules/core/www/loginuserpass.php:14 (require)
0 /opt/simplesamlphp-1.12.0/www/module.php:135 (N/A)
Report errors

Optionally enter your email address, for the administrators to be able contact you for further questions about your issue:

E-mail address: 

The error I receive:

Send error report

How to get help

This error probably is due to some unexpected behaviour or to misconfiguration of simpleSAMLphp. Contact the administrator of this login service, and send them the error message above.

simpleSAMLphp is Copyright © 2007-2014 Feide RnD

**Comment by thijskh** [comment]
This is not a support forum. We also are not involved with running that aervice. Please contact the TSTC helpdesk.

**Comment by amg21608** [comment]
Thanks
