### ISSUE TITLE
getSelfURL() function returns URL with port number

### ISSUE THREAD

**Issue by karolflis** [simplesamlphp/simplesamlphp#651]
Hello guys.

Could you review it and decide if this is something that can be changed?

Not sure if this can be treated as bug, but it caused an issue in SAML implementation for Moodle plugin auth_saml2 which includes simplesamlphp as external library.

URL returned by this function (with port number appended to it) couldn't be matched to FQDN causing unexpected error. I have hotfixed it, in my use case and it did the job.

Unfortunately I don't have knowledge if this function is used anywhere else and requires this port number appended.

This is in file:
lib/simplesamlphp/lib/SimpleSAML/Utils/HTTP.php

`771: return $protocol.$hostname.$port.$_SERVER['REQUEST_URI'];`

URL generated by this code contains port number appended to it.
I have encountered a case where this URL is compared against application URL and mismatched because of port value appended to domain name.

Ended up in error about mismatched URLs:

Destination in response doesn't match the current URL.
Destination is "https://example.domain.com/auth/saml2/sp/saml2-acs.php/foobar", current URL is
"https://example.domain.com:443/auth/saml2/sp/saml2-acs.php/foobar".

**Comment by jaimeperez** [comment]
Hi @karolflis!

The function is fine. That code is only triggered when something goes seriously wrong or when the code is reached from a URL that doesn't belong to SimpleSAMLphp.

Set the `baseurlpath` configuration option to your canonical URL and the problem will be gone.
