### ISSUE TITLE
Password reset/change feature

### ISSUE THREAD

**Issue by bizmate** [simplesamlphp/simplesamlphp#652]
I hope it is ok to open this issue.
I cannot really find any documentation is SimpleSAMLPHP implements the possibility to request either a password change or reset from the IDP and if it does where is the documentation that shows an example?

I am already implementing a number of methods for remote authentication/validation of users through the IDP but I am lacking this password change feature.
Any suggestion is very much appreciated.

**Comment by tvdijen** [comment]
You can ask future questions at the [mailing lists](https://simplesamlphp.org/lists)..

It would be kinda difficult to transparently implement this in SimpleSAMLphp, because there are so many different back-end user stores that would require different implementations...
At this point,  I don't think there is any authentication module at all that implements this...
However, if you're using an LDAP-store, there are quite decent third-party tools that can provide this functionality for you, like [PWM](https://github.com/pwm-project/pwm)

**Comment by bizmate** [comment]
hi @tvdijen 
thanks for the fast reply. I am actually implementing custom auth sources in a module inside SimpleSamlphp so it is not LDAP but rather an auth source talking to external custom APIs. Our options are to be considered because if SimpleSAMLphp had a way to expose lets say a password reset or a password change service then it would be cleaner on the IDP. IF this needs to happen on the actual system holding users and password then there would be no way to send the user back to the SP or IDP with the right service reference. 

Not sure the above makes sense. So we might have x amount of Services SPs that call the IDP. Out IDP uses a number of remote Auth sources. IF I send the user to the Auth app to change the password this is not the IDP and it will not be aware of the user session/origin and so after the password is reset the user cannot be sent to the IDP or SP consistently.

I think a module to extend the IDP should be the right thing but I am quite new to SimpleSAMPphp to know how to modify or create this extra piece of functionality.

**Comment by tvdijen** [comment]
`IF this needs to happen on the actual system holding users and password then there would be no way to send the user back to the SP or IDP with the right service reference.`
I think this is beyond the scope of SAML, but I think it would work fine if you'd send them back to the referrer-url after the password-change?

So what you need to do is extend your custom auth module with a password-reset button / page that allows one to change their password and then redirect them back to where they came from.. This is all custom for your API though, so it's not something that SimpleSAMLphp is likely going to facilitate.

Also, I have to ask:  there are so many options for auth sources.. why a custom one?

**Comment by bizmate** [comment]
@tvdijen  because there is single API with an abstraction that is actually using multiple DB sources and Auth providers that connect to a mix of proprietary and opensource systems.

About the custom forgotten password then I can add a module in the IDP login page -> user goes to change the password on the external system -> when done the user is sent back to the original/referred IDP page?

**Comment by tvdijen** [comment]
Yes, I think that should work just fine...

**Comment by poVoq** [comment]
If you are using the sql auth backend this might work:
https://github.com/GEANT/simplesamlphp-module-selfregister

There is also a modern compatible theme:
https://github.com/Prodrivers/simplesamlphp-module-theme-prodrivers

and you probably also want to use this if you are starting a new sql database:
https://github.com/Prodrivers/simplesamlphp-module-sqlauthphppassword

**Comment by bizmate** [comment]
@poVoq  thanks for the comment. Although those modules might not be exactly what I need they might help to understand how to integrate/build a new module that does exactly what I want. I cannot seem to find anything so specific but if I had to create a module for simplesamlphp to do the password reset what documentation can i rely on? 
Are there articles describing how to hook into the SimpleSamlphp framework ?

**Comment by jaimeperez** [comment]
Hi @bizmate!

[This](https://simplesamlphp.org/docs/stable/simplesamlphp-modules) is the relevant document in the documentation 😉
