### ISSUE TITLE
core:PHP uses create_function(), which is deprecated in 7.2

### ISSUE THREAD

**Issue by pradtke** [simplesamlphp/simplesamlphp#656]
**Jaime**:

An idea I had to avoid adding code as a string was to use anonymous functions instead. However, those can’t be serialized, and therefore can’t be used as the authproc filters are stored in the session object (which needs serialization to be stored). I’m afraid the only alternative here would be to use a callable (either a function or a method from a class).

Given the deprecation, create_function() will probably go away in 7.3, and even though we are still far from that, I think it’s a good idea to start preparing for it. Do you mind opening an issue so that we keep this in mind?

From https://groups.google.com/d/msg/simplesamlphp/QhK15VvcinQ/S42Ni0uECQAJ

**Comment by thijskh** [comment]
I've created #754 to address this; @pradtke is this OK for you?

**Comment by pradtke** [comment]
#754 looks good to me.
