### ISSUE TITLE
FriendlyName doesn't appear to work with latest code

### ISSUE THREAD

**Issue by gregharvey** [simplesamlphp/simplesamlphp#667]
Hi,

Similar to https://github.com/simplesamlphp/simplesamlphp/issues/181 but this time I'm actually operating in the 'master' branch, so latest code.

It's entirely possible I'm doing something stupid, but I can't see what. I really need the `FriendlyName` attribute to work in order to get AWS integration working safely (without it you can't restrict login by LDAP group) but for some reason it's not working as the docs (and indeed the code) suggest!

I've checked the code - https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Metadata/SAMLBuilder.php#L412 - and it *looks* like it should take any array key passed in the attributes array as a 'friendly name' and build the appropriate XML.

My SP config for attributes looks like this:

```
  'attributes' =>
    array (
      'https://aws.amazon.com/SAML/Attributes/Role',
      'https://aws.amazon.com/SAML/Attributes/RoleSessionName',
      'eduPersonAffiliation' => 'urn:oid:1.3.6.1.4.1.5923.1.1.1.1',
    ),
```

That's inline with the AWS SAML attribute docs here: http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_assertions.html#saml-attribute-mapping

Yet my SAML XML looks like this:

```
        <saml:AttributeStatement>
            <saml:Attribute Name="https://aws.amazon.com/SAML/Attributes/Role"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">arn:aws:iam::XXXXXXXXXXXX:role/codeenigmaSamlAdmin,arn:aws:iam::XXXXXXXXXXXX:saml-provider/codeenigmaSAML</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="https://aws.amazon.com/SAML/Attributes/RoleSessionName"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">USERNAME</saml:AttributeValue>
            </saml:Attribute>
            <saml:Attribute Name="urn:oid:1.3.6.1.4.1.5923.1.1.1.1"
                            NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
                            >
                <saml:AttributeValue xsi:type="xs:string">GID</saml:AttributeValue>
            </saml:Attribute>
        </saml:AttributeStatement>
```

So all the attributes are appearing, but I would expect that last attribute to have `FriendlyName=eduPersonAffiliation` included in the saml:attribute element - but it doesn't. I have no idea why!

Clues? :-)

Thanks,

Greg

**Comment by jaimeperez** [comment]
Hi @gregharvey!

_Friendly names_ are intended to display in SAML metadata, not in SAML responses. If you go to your SP SAML metadata, you will notice the `FriendlyName` attribute appearing there in the `<md:RequestedAttribute>` element for _eduPersonAffiliation_, but it won't affect in any way what the IdP sends you back.

**Comment by gregharvey** [comment]
Ahh, thanks - indeed, this seems to be working. Part of my problem is it seems AWS caches policies for a few minutes, so I wasn't leaving enough time for the AWS policy to update. I can confirm with the above this is working and restricting users by LDAP group, which is great! :-)
