### ISSUE TITLE
SimpleSamlPHP problem with SimpleLogoutService

### ISSUE THREAD

**Issue by wszychta** [simplesamlphp/simplesamlphp#673]
Hi,

We have working SimpleSAMLPHP instance with several SP connected. Everything is working without problem. Now we are trying to connect with some Software Vendor, but we are facing with one problem.

Login works without problem, but when user is trying to logout in browser he see this communicate:
```You accessed the SingleLogoutService interface, but did not provide a SAML LogoutRequest or LogoutResponse. Please note that this endpoint is not intended to be accessed directly.```

```
SimpleSAML_Error_Error: SLOSERVICEPARAMS
Backtrace:
0 /var/www/XXX/www/saml2/idp/SingleLogoutService.php:28 (N/A)
Caused by: Exception: Unable to find the current binding.
Backtrace:
2 /var/www/XXX/vendor/simplesamlphp/saml2/src/SAML2/Binding.php:97 (SAML2_Binding::getCurrentBinding)
1 /var/www/XXX/modules/saml/lib/IdP/SAML2.php:487 (sspmod_saml_IdP_SAML2::receiveLogoutMessage)
0 /var/www/XXX/www/saml2/idp/SingleLogoutService.php:23 (N/A)
```
Unfortunatelly our Vendor said that "They does not support Single Logout service"
They only redirect logout button to specified URL. 

**Can we do something to give possibility to logout user and end session after directly access to SingleLogoutService URL?**

We are using LDAP as users base and here is configuration:

```
<?php

$config = array(
    // This is a authentication source which handles admin authentication.
    'admin' => array(
        // The default is to use core:AdminPassword, but it can be replaced with
        // any authentication source.

        'core:AdminPassword',
    ),

    ///*
    // Example of a LDAP authentication source.
    'ldap' => array(
        'ldap:LDAP',
        'hostname' => 'XXX.XXX.XXX.XXX',
        'enable_tls' => FALSE,
        'debug' => FALSE,
        'timeout' => 0,
        'port' => 389,
        'referrals' => TRUE,
        'attributes' => NULL,
        'dnpattern' => 'cn=%username%,ou=XXX,dc=XXX,dc=com',
        'search.enable' => FALSE,
        'search.base' => 'ou=XXX,dc=XXX,dc=com',
        'search.attributes' => array('cn', 'mail'),
        'search.username' => NULL,
        'search.password' => NULL,
        'priv.read' => FALSE,
        'priv.username' => NULL,
        'priv.password' => NULL,

    ),
```

Here is our Vendor SP metadata configuration:
```
$metadata['XXXXX'] = array(
        'AssertionConsumerService' => 'https://XXXXX/login/saml',
        'SingleLogoutService' => 'https://XXXXX/logout',
        'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:email',
        'simplesaml.nameidattribute' => 'mail',
        'simplesaml.attributes' => FALSE,
);
```

**Comment by jaimeperez** [comment]
Hi @wszychta!

This is an issue tracker, not a support forum. If you need assistance configuring or using SimpleSAMLphp, please use the [mailing list](http://groups.google.com/group/simplesamlphp).
