### ISSUE TITLE
Help with login

### ISSUE THREAD

**Issue by lucapada** [simplesamlphp/simplesamlphp#688]
Hi! I'm using this solution to do the login to a remote IdP. Nowly all is working...
The only thing I want to realize is that when I have to do the login, I mustn't to pass through the "core" interface of simplesamlphp. How could I do?
Thank u so much!

**Comment by thijskh** [comment]
This is an issue tracker, not a support forum. Please direct your question to the [simpleSAMLphp user's mailing list](https://simplesamlphp.org/lists).
