### ISSUE TITLE
Where did simplesamlphp/xmlseclibs repo go?

### ISSUE THREAD

**Issue by SvHu** [simplesamlphp/simplesamlphp#694]
Hey,
Just to clarify where did simplesamlphp/xmlseclibs go? 
SSP 13.1 depends on it.  What would be easy fix for it?

**Comment by thijskh** [comment]
It was a copy of robrichards/xmlseclibs. I was not aware that people still use that old versions of SimpleSAMLphp but do run composer on them. 

Best fix is to upgrade SimpleSAMLphp. We could clone the repo again but that might just stimulate people not to upgrade..?

**Comment by thijskh** [comment]
I have re-created the fork for now, hope it solves your problem. But it will go away (should be able to go away) at some point in the future again.
