### ISSUE TITLE
1.15rc1: theme modules break on missing templates-dir

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#695]
As per mailinglist-discussion:

> Thanks Thijs!
> 
> That’s a bug we need to fix then. Could you please add an issue to the issue tracker so that I remember to look into it when I’m back?
> 
> On 25 Sep 2017, at 17:15 PM, Thijs Kinkhorst <thijs.kinkhorst@surfnet.nl> wrote:
> > I believe it's specifically about themes (like Tim's themejustitie). I 
> > can confirm that it indeed breaks when enabling a theme (that has no 
> > templates/ directory):
> > 
> > Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1]
> > SimpleSAML_Error_Error: UNHANDLEDEXCEPTION Sep 25 15:01:54 thki-sid 
> > simplesamlphp[31753]: 3 [08b22304f1] Backtrace:
> > Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1] 1
> > /srv/simplesamlphp/www/_include.php:45 (SimpleSAML_exception_handler) 
> > Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1] 0 
> > [builtin] (N/A) Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 
> > [08b22304f1] Caused by:
> > InvalidArgumentException: The module 'themeSURFnet' has no templates 
> > directory.
> > Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1] Backtrace:
> > Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1] 5
> > /srv/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:304
> > (SimpleSAML_XHTML_Template::getModuleTemplateDir)
> > Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1] 4
> > /srv/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:176
> > (SimpleSAML_XHTML_Template::setupTwigTemplatepaths)
> > Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1] 3
> > /srv/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:198
> > (SimpleSAML_XHTML_Template::setupTwig)
> > Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1] 2
> > /srv/simplesamlphp/lib/SimpleSAML/XHTML/Template.php:130
> > (SimpleSAML_XHTML_Template::__construct)
> > Sep 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1] 1
> > /srv/simplesamlphp/modules/core/www/loginuserpass.php:76 (require) Sep 
> > 25 15:01:54 thki-sid simplesamlphp[31753]: 3 [08b22304f1] 0
> > /srv/simplesamlphp/www/module.php:135 (N/A) Sep 25 15:01:54 thki-sid 
> > simplesamlphp[31753]: 3 [08b22304f1] Error report with id 52aafcf1 
> > generated.

**Comment by jaimeperez** [comment]
Thanks for moving the discussion here @tvdijen! It should be fine now.
