### ISSUE TITLE
SimpleSAML_Error_Exception: Error 1 - Class 'SimpleSAML\Error\Errorcodes' not found

### ISSUE THREAD

**Issue by enricocavalli** [simplesamlphp/simplesamlphp#700]
https://github.com/simplesamlphp/simplesamlphp/blob/a5948af7ec8a15b9913ef47c45b4b2620b4c9adc/modules/core/www/loginuserpassorg.php#L84

while doing some testing i discovered that the line above generates an exception on Debian 9 with its latest php7, while it does not for instance on ubuntu xenial

I think I don't have the necessary experience to understand why ... (this specific line is not present on the latest released version of ssp).

Thank you

**Comment by thijskh** [comment]
It was a capitalisation issue. Thanks for reporting!
