### ISSUE TITLE
Video Tutorial down

### ISSUE THREAD

**Issue by efreed** [simplesamlphp/simplesamlphp#705]
At the bottom of: https://simplesamlphp.org/docs/stable/ There is a "Video tutorials" section, but the link leads to a 502 server error.   http://rnd.feide.no/content/video-tutorial-installing-and-configuring-simplesamlphp

Is the video still available?

**Comment by jaimeperez** [comment]
Hi @efreed!

To the best of my knowledge, [the video is gone](https://rnd.feide.no/2008/04/27/video_tutorial_installing_and_configuring_simplesamlphp/). In any case, that video was deprecated as it was recorded with a version of SimpleSAMLphp that's very old now.
