### ISSUE TITLE
Changes in class name in simplesamlphp/lib/SimpleSAML/Auth/Simple.php breaking Drupal implementations

### ISSUE THREAD

**Issue by camoa** [simplesamlphp/simplesamlphp#715]
As the class name changed from SimpleSAML_Auth_Simple to just Simple in V1.15 the Drupal module is breaking if this version is used.

The issue is that moving to PHP 7.1 the  php-memecache module is deprecated, there is a fix in v1.15 that is not on 1.14 for this (checking if either memecache or memcached class exist) the problem is once you upgrade to PHP 7.1 memecache does not exist and the library v.1.14 breaks, but if you upgrade to v.1.15 then the Drupal module breaks since there is no Backwards compatibility on this class change...

I truly believe this may stand true for many other implementations.

**Comment by jaimeperez** [comment]
Hi @camoa!

I don't know what's the Drupal module doing. However, both 1.15 and `master` include a custom autoloader that allows for the migration of classes to namespaces transparently for users. It is still perfectly possible to use the old class names, and backwards compatibility is definitely not broken. In fact, you can use both the old names and the new ones (with namespaces) at the same time, as I've just tested manually:

```php
php > $as = new SimpleSAML_Auth_Simple('default-sp');
php > $as = new \SimpleSAML\Auth\Simple('default-sp');
php >
```

If this is not working in this Drupal module, they are doing something wrong. Most likely, not using the composer autoloader they should be using. In any case, it's something they have to fix.

**Comment by camoa** [comment]
Gracias...

I will report back to them then

**Comment by jaimeperez** [comment]
De nada 😉 

If they need help fixing the issue, point them in our direction so that we can tell them what's wrong.

**Comment by camoa** [comment]
My customer went and updated to 1.15-RC1 and was getting this error:

`02-Oct-2017 14:01:59 America/Chicago] PHP Fatal error:  Cannot declare class SimpleSAML\Auth\Simple, because the name is already in use in /mnt/www/html/syscocustomerportalstg/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Auth/Simple.php on line 18 request_id="v-36434e1c-a7a4-11e7-9ca3-063f2feb7b10"`

Can't figure out the exact reason. 

http://cgit.drupalcode.org/simplesamlphp_auth/tree/?h=8.x-3.x

**Comment by jaimeperez** [comment]
How was SimpleSAMLphp updated? Could it be that it was updated without running composer again, to regenerate the autoloader?

**Comment by camoa** [comment]
Update so far: the composer.json that loads the library, is part of the module, when I try to force it to 1.15 without changing the module it causes an error. 

Created this issue in D.O:

https://www.drupal.org/project/simplesamlphp_auth/issues/2925106
