### ISSUE TITLE
multiauth help configuration

### ISSUE THREAD

**Issue by geemang2000** [simplesamlphp/simplesamlphp#719]
Multiauth has an i18n text definition to customize the button used to select the authSource. It's likely the end-user might need additional instructions to help choose the correct authSource.  

I'd like to propose the following additional configuration.

'help' => array(
   'en' => 'some message',
),

Add an optional (if help exists) area on the template. 

I have already implemented this. It's a minor patch.  Do you want the patch?

**Comment by thijskh** [comment]
That sounds like a good idea, please send a pull request so we can review it. Thanks!

**Comment by geemang2000** [comment]
Created #721

**Comment by tvdijen** [comment]
Since the PR was merged, I'm closing this one.
