### ISSUE TITLE
MDX breaks metadata query flow

### ISSUE THREAD

**Issue by bajnokk** [simplesamlphp/simplesamlphp#723]
It seems that if an entity is not found during MDX query (or the query fails), the MetadataStorageSource throws an exception instead of returning null. Subsequentially, it prevents additional metadata sources from being consulted.

I can submit a pull request if you agree that it's a bug.

I think the following line is relevant here: https://github.com/simplesamlphp/simplesamlphp/blob/57df7b25fa558531c1e76aa686c5daec199b3fdc/lib/SimpleSAML/Metadata/Sources/MDQ.php#L300

**Comment by jaimeperez** [comment]
Hi Kristof!

That sounds like a bug, yes. PRs are always welcome! 👍
