### ISSUE TITLE
Add Account Google feature

### ISSUE THREAD

**Issue by Mathi05** [simplesamlphp/simplesamlphp#724]
Hi,

I have configured simplesamlphp in my application for Google SSO (G-mail login). It works like a gem. Is that possible to achieve the  Google's Add Account feature with simplesamlphp.  If yes kindly tell me the procedures. 

Thanks,

**Comment by jaimeperez** [comment]
Hi @Mathi05!

This is an issue tracker, not a support forum. You can ask in the [mailing list](https://groups.google.com/forum/#!forum/simplesamlphp) to see if someone has experience with that and can help you out.
