### ISSUE TITLE
ldap:AttributeAddUsersGroups and openldap and versoin 1.15RC3

### ISSUE THREAD

**Issue by ChessSpider** [simplesamlphp/simplesamlphp#726]
Hi guys 👍 

Question time. I am using release candidate of version 1.15 as it added "unsupported" support for AttributeAddUsersGroups and OpenLDAP.   See https://simplesamlphp.org/docs/1.15/ldap:ldap

I am using the following configuration in my **saml2-idp-phosted.php** file

```php
.........
    'authproc' => array(
         50 => array(
         
             'class' => 'ldap:AttributeAddUsersGroups',
             'ldap.basedn' => 'dc=example,dc=org',
             'ldap.product' => 'OpenLDAP',

             'authsource' => 'my-ldap',
             'attribute.dn' => 'entryDN',
             'attribute.username' => 'entryDN',
             
             'attribute.member' => 'cn',
             'attribute.memberof' => 'uniqueMember',
             'ldap.username' => 'cn=testuser,ou=people,dc=example,dc=org',
             'ldap.password' => 'somesupersecurepasswordnobodywilleverguessbutthisisnotit',
         ), 
        // Convert LDAP names to oids.
        100 => array('class' => 'core:AttributeMap', 'name2oid'),
    ),
.........
```

What I see in the OpenLDAP logfile is that SimpleSAML searches for ```uniqueMember=%uid%``` but I want it to search for ```uniqueMember=%entryDN%``` instead.. 
How can I do that? Nothing I change in the configuration seem to have that effect

**Comment by ChessSpider** [comment]
by the way, I now manually made the ```uid``` value the same as the ```entryDN``` value and it works. 
See my evidence:

```
openldap_1  | 5a0bee86 conn=1169 op=0 BIND dn="cn=testuser,ou=people,dc=example,dc=org" mech=SIMPLE ssf=128
openldap_1  | 5a0bee86 conn=1169 op=0 RESULT tag=97 err=0 text=
openldap_1  | 5a0bee86 conn=1169 op=1 SRCH base="dc=example,dc=org" scope=2 deref=0 filter="(uniqueMember=cn=anothertest,ou=people,dc=example,dc=org)"
openldap_1  | 5a0bee86 conn=1169 op=1 SRCH attr=cn
openldap_1  | 5a0bee86 <= bdb_equality_candidates: (uniqueMember) not indexed
openldap_1  | 5a0bee86 conn=1169 op=1 SEARCH RESULT tag=101 err=0 nentries=1 text=
openldap_1  | 5a0bee86 conn=1169 op=2 UNBIND
openldap_1  | 5a0bee86 conn=1169 fd=15 closed
```

```xml
<saml:Attribute Name="groups" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:uri">
	<saml:AttributeValue xsi:type="xs:string">myexamplegroup</saml:AttributeValue>
</saml:Attribute>
```

**Comment by thijskh** [comment]
Indeed the `OPENLDAP` option uses hardcoded `uid` to search for. It should instead use the value of `attribute.username`. We can change that, but it would also change the default since `attribute.username` defaults to `samAccountName`. But that can be updated in the docs.

**Comment by ChessSpider** [comment]
if that gets changed now, will it be incorporated in the next RC or final of 1.1.15?

**Comment by thijskh** [comment]
Can you confirm that #727 solves the problem for you?

**Comment by ChessSpider** [comment]
I  can check that now. 

I also recommend changing other defaults too then. 

E.g. memberUID is the default for POSIX groups in OpenLDAP. I suggest to change it to 'member' as I beleive groupOfNames is the de facto standard for groups in OpenLDAP  (or `groupOfUniqueNames` in my case, which uses uniqueMember).  It may also be 'roleOccupant' for 'organizationalUnit'.  

In all cases except for POSIX groups it stores the DN, so it should by default use EntryDN entry instead of UID.

**Comment by ChessSpider** [comment]
I can confirm it works. I did the following, roughly :

```
git clone simplesaml
(some steps of me installing composer and dependencies) 
git checkout  93ac84c 
```

The uid is set to its normal value. The configuration is as follows:

```php
         50 => array(
             'class' => 'ldap:AttributeAddUsersGroups',
             'ldap.basedn' => 'dc=example,dc=org',
             'ldap.product' => 'OpenLDAP',

             'authsource' => 'ldap',
             'attribute.dn' => 'entryDN',
             'attribute.username' => 'entryDN',
             
             'attribute.member' => 'cn',
             'attribute.memberof' => 'uniqueMember',
             'ldap.username' => 'stuff',
             'ldap.password' => 'otherstuff',
         ), 
```

Awesome 👍 

Thanks for the quick fix!

On an unrelated note, this OpenLDAP unsupported 'support' seems a bit of a hack? E.g. my OpenLDAP database does have a 'memberOf' attribute for the user (with the memberof-overlay) and it could use that perfectly to just fetch the CN of those groups.

**Comment by thijskh** [comment]
>  E.g. memberUID is the default for POSIX groups in OpenLDAP. I suggest to change it to 'member' as 
> I beleive groupOfNames is the de facto standard for groups in OpenLDAP (or groupOfUniqueNames 
> in my case, which uses uniqueMember). It may also be 'roleOccupant' for 'organizationalUnit'.

The defaults are global for this auth proc filter and not specific to any of the products (AD/OpenLDAP), so you need to change your settings for each of the products already. This is explained in the documentation.

> On an unrelated note, this OpenLDAP unsupported 'support' seems a bit of a hack

I'm not sure why it's marked as "unsupported", but that's probably related to what you describe. Of course PR's that improve the filter are very welcome.

I'll merge the bugfix for 1.15.

**Comment by thijskh** [comment]
Fixed in 89bff5a / 61875dec.

**Comment by ChessSpider** [comment]
do you know when the latest RC or final is set for 1.15 ?

**Comment by thijskh** [comment]
I expect 1.15 to be released any moment now. @jaimeperez ?

**Comment by jaimeperez** [comment]
It's really busy here ATM, hopefully tomorrow I can spare a few minutes for it.

**Comment by ChessSpider** [comment]
I hope you have time this week, as I need v1.15 in order to put simplesaml in production  :)

**Comment by jaimeperez** [comment]
1.15.0 is out now 😄

**Comment by ChessSpider** [comment]
aweosme, thanks :) its going live tomorrow 👍
