### ISSUE TITLE
CheckSign method is hard coded

### ISSUE THREAD

**Issue by jeremyfrench** [simplesamlphp/simplesamlphp#728]
Hi

I am using SSP and I'm having an issue with a message with the following in `<ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>`

It is saying that it is unable to verify the signature of this message. I'm looking at the code and I see [this](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Message.php#L211) `            $key = new XMLSecurityKey(XMLSecurityKey::RSA_SHA1, array('type' => 'public'));` in `Message::checkSign()`

It looks to me that this is hard coding the check to be SHA1, which would be why the signature is failing, when other types are valid. If I'm correct in this diagnosis then I will sort out a patch, but I want to make sure I am understanding the issue first.

Can you confirm this is a valid issue?

**Comment by tvdijen** [comment]
Hi Jeremy!
Could you send in some debug logging?

**Comment by jeremyfrench** [comment]
Sure. Thanks for the quick response. 

So with debug turned on I get 

```
Nov 23 16:20:23 simplesamlphp DEBUG [2506d32222] Has 1 candidate keys for validation.
Nov 23 16:20:23 simplesamlphp DEBUG [2506d32222] Validation with key #0 failed with exception: Unable to validate Signature
Nov 23 16:20:23 simplesamlphp ERROR [2506d32222] SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
```

The error is `simplesamlphp/saml2/src/SAML2/Utils.php:157 (SAML2_Utils::validateSignature)`

The Digest header is this 

```
<ds:SignedInfo>
    <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
    <ds:SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
    <ds:Reference URI="#_8ca598342655a89a157b2e5a25d2d404">
        <ds:Transforms>
            <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
            <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
        </ds:Transforms>
        <ds:DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
        <ds:DigestValue>-SNIPPED-</ds:DigestValue>
    </ds:Reference>
</ds:SignedInfo>
```
One thing that may be related to the validation fail is that there are some encripted attributes.

```
<saml2:EncryptedAssertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">
    <xenc:EncryptedData xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_280f028fb9ec493da1644f600ed6c05f" Type="http://www.w3.org/2001/04/xmlenc#Element">
    <xenc:EncryptionMethod xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Algorithm="http://www.w3.org/2001/04/xmlenc#aes128-cbc"/>
    <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
    <xenc:EncryptedKey xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Id="_9616a8f0dc6ea2926c491ee817dc5901" Recipient="wkuk.net:default:entityId">
    <xenc:EncryptionMethod xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" Algorithm="http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p">
    <ds:DigestMethod xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
</xenc:EncryptionMethod>
....
```

So I'm not sure if the issue I posted is correct but it at least seemed to be unusual.

**Comment by tvdijen** [comment]
Okay, this has got me a little bit confused now...
It seems as if you are the SP and you're receiving an encrypted assertion from an IdP, is that correct?

Anyway... I'd suggest we take this discussion to the [mailinglist](https://simplesamlphp.org/lists), since this is an issue tracker, not a support forum.
Please clarify your use-case and provide full SAML logs and perhaps some more insight in your configuration (the signature-related parts).

**Comment by jaimeperez** [comment]
Hi!

Just for the record, SHA-1 is not hardcoded for signatures. It is just the way the keys are initialized by default, but the hashing algorithm is changed later in the code to reflect the actual algorithm used in the signature.
