### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by Billaboong** [simplesamlphp/simplesamlphp#733]
I have successfully configured this library with an idp and the next step is to use it in my own application which is a based on a php framework but the problem is when I set the session and do a redirect the session data is unset so is the problem with the php framework or this library?

**Comment by jaimeperez** [comment]
Hi,

This is an issue tracker, so for support we always use our [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, if you are using PHP sessions both in your application and in SimpleSAMLphp, you need to make sure they both use different sessions (different cookie names). You'll also need to clean SimpleSAMLphp's session up after calling it for authentication. Please read [the documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-sp#section_6) to learn how to do that.
