### ISSUE TITLE
Cannot Specify Audience for SAML 2.0 Remote Metadata

### ISSUE THREAD

**Issue by tdiscuit** [simplesamlphp/simplesamlphp#737]
So I'm setting up AWS as a SP and they require that you specify the AudenceRestriction as shown here:

```
<Conditions>
  <AudienceRestriction>
    <Audience>https://signin.aws.amazon.com/saml</Audience>
    <Audience>urn:amazon:webservices</Audience>
  </AudienceRestriction>
</Conditions>
```
I see that you can override the audience from the EntityID to whatever you want on a Shib 1.3 metadata set, but not SAML 2.0.

Is there a reason behind that? or is it just something that was never added? If it's the latter I can start up a PR to do that.

**Comment by thijskh** [comment]
The saml2 library supports this, so I guess it was just never added to simpleSAMLphp because no-one needed it before.

**Comment by tvdijen** [comment]
@tdiscuit This seems  to be addressed in https://github.com/simplesamlphp/simplesamlphp/pull/998
Could you please confirm that this has been resolved for you?

**Comment by tvdijen** [comment]
@tdiscuit What is the entityID of the AWS SP? Is is different?

From what I read [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_create_saml_assertions.html) you have to either send one or the other and not both as you describe..

Also, SAML specs require that you at least add the SP entityID as an audience, and you may add others, so overwriting it completely as the Shib1.3 code does is probably not a good idea..

**Comment by sitecode** [comment]
This would be a nice option to have for SAML 2.0 also. I could use it.
