### ISSUE TITLE
Google Chrome 63 May Cache 302 Redirects

### ISSUE THREAD

**Issue by LukeLeber** [simplesamlphp/simplesamlphp#749]
Hello,

I've noticed that the 302 redirect to the IdP can now be stored in the local disk cache with the new Chrome release.  This can cause stale requests to be sent to the IdP.

Please see the pull request [here](https://github.com/simplesamlphp/simplesamlphp/pull/748) for more details and a solution.

Regards,
Luke

**Comment by thijskh** [comment]
Fixed in #748

**Comment by LukeLeber** [comment]
Hi @thijskh ,

Sorry if this isn't the right spot for general questions, but...

We are using simplesamlphp with our Drupal application and have noticed that version 1.15.2 may have some conflicts with the connector module that is being used.

Would it be accurate to tell my project managers that there will be no SimpleSAML 1.14.18 release and that we need to either keep the temporary patch or address the conflicts between the Drupal connector and 1.15.2?

Thanks in advance,
Luke

**Comment by thijskh** [comment]
I don’t think a 1.14.18 is likely, sorry. If course it’s most future proof to resolve the conflicts...
