### ISSUE TITLE
Configuration for Nginx

### ISSUE THREAD

**Issue by nivv** [simplesamlphp/simplesamlphp#751]
There is nothing on this topic in the official docs. I've been trying for a couple of hours but have had no success so far.

It feels a bit dated to have an application like this so tightly coupled to a specific web server.

Anyways, I've gathered that there should be an alias to the `www` directory.

```
    location /simplesaml {
		
		# add alias root to global simple saml install (default location)
		#alias /var/simplesamlphp/www;
		alias /home/forge/saml.infab.io/www;
		
                index index.php;
		
                # simple saml php-fpm config
	       # based on: http://casadelkrogh.dk/code/2014/09/30/embedding-simplesamlphp-using-nginx/
	       location ~ \.php(/|$) {
               fastcgi_split_path_info ^(.+\.php)(/.+)$;
               fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
               fastcgi_index index.php;
               include fastcgi_params;
        }
		
    }
```

When I visit https://site.org/simplesaml I'm redirected to `https//site.org/simplesaml/module.php/core/frontpage_welcome.php`. All I see on this page is the message `No input file specified`

Would love an official config on how to get this to work with nginx.

**Comment by tvdijen** [comment]
I think you're missing a 'root' directive pointing to the `/var/simplesamlphp/www` directory...
And then you're nesting two location-statements which seems invalid.. Your source doesn't do that either

**Comment by tvdijen** [comment]
```
server {
    listen 8443 ssl;
    server_name idp.moo-archive.nl simplesamlphp-2.ext.moo-archive.nl;

    ssl_certificate     /etc/pki/tls/certs/idp.moo-archive.nl.crt;
    ssl_certificate_key /etc/pki/tls/private/idp.moo-archive.nl.key;
    ssl_protocols       TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    location / {
        root /apps/tenants/moo-archive.nl/www;
        index  index.php;
    }

    location ~ \.php$ {
        root           /apps/tenants/moo-archive.nl/www;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        include        fastcgi_params;
        index  index.php;
    }
}
```

I have no experience with Nginx whatsoever, but this works for me...
I have however no experience with Nginx, so I have no idea whether this is safe config..
If we don't get comments about this, I'll make sure it ends up in the docs

**Comment by mschwager** [comment]
Here's what I've used, which works:

```
server {
    listen 80;

    location ^~ /simplesaml {
        alias /var/simplesamlphp/www;

        # The prefix must match the baseurlpath configuration option
        location ~ ^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
            include fastcgi_params;
            fastcgi_pass phpfpm:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$phpfile;

            # Must be prepended with the baseurlpath
            fastcgi_param SCRIPT_NAME /simplesaml$phpfile;

            fastcgi_param PATH_INFO $pathinfo if_not_empty;
        }
    }
}
```

Adding SSL is left as an exercise to the reader :)

I've actually been playing around with this a bit lately in [Docker Compose](https://docs.docker.com/compose/). I'll put up my configuration file in a bit!

**Comment by mschwager** [comment]
Finally got around to putting the files on Github: https://github.com/mschwager/docker-simplesamlphp

I've been running SimpleSAMLphp on Docker Compose lately. There are a few places that need some ironing out, but it generally works :)

And it provides a good example of running SimpleSAMLphp with `nginx` and `php-fpm` :+1:

**Comment by tvdijen** [comment]
Still need docs in the SSP-repo for nginx

**Comment by tvdijen** [comment]
Added a section in the docs with a basic configuration example: https://github.com/simplesamlphp/simplesamlphp/commit/91479a4d42ade5d9d02712147c5a5d774915f26f
More will be added when needed

**Comment by niallfleming** [comment]
Using an ungreedy regex seems to be the simplest, and deals nicely with URIs with multiple occurences of .php like:

https://<hostname.domain>/simplesaml/module.php/core/frontpage_auth.php
```
location ^~ /simplesaml {
    alias /var/simplesamlphp/www;

    location ~ \.php(/|$) {
        include fastcgi_params;
        fastcgi_pass unix:/run/php-fpm/www.sock;
        fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        fastcgi_param PATH_INFO $fastcgi_path_info if_not_empty;
    }
}
```

Most users can probably unnest the location blocks. But for my use I want this to only apply in this location.

**Comment by stefan-1st** [comment]
> Here's what I've used, which works:
> 
> ```
> server {
>     listen 80;
> 
>     location ^~ /simplesaml {
>         alias /var/simplesamlphp/www;
> 
>         # The prefix must match the baseurlpath configuration option
>         location ~ ^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
>             include fastcgi_params;
>             fastcgi_pass phpfpm:9000;
>             fastcgi_index index.php;
>             fastcgi_param SCRIPT_FILENAME $document_root$phpfile;
> 
>             # Must be prepended with the baseurlpath
>             fastcgi_param SCRIPT_NAME /simplesaml$phpfile;
> 
>             fastcgi_param PATH_INFO $pathinfo if_not_empty;
>         }
>     }
> }
> ```
> 
> Adding SSL is left as an exercise to the reader :)
> 
> I've actually been playing around with this a bit lately in [Docker Compose](https://docs.docker.com/compose/). I'll put up my configuration file in a bit!

This one fixed it for me!!! Thanks a lot.

**Comment by tvdijen** [comment]
Hi Stefan! Should we fix anything in our docs?

**Comment by stefan-1st** [comment]
Hey @tvdijen 

It is hard to say. I used simplesamlphp in a composed docker environment. Perhaps the settings of the nginx are a bit weird, i am not used to set up servers since the days of apache 2.0.

Non the less, the settings mentioned in the documentation didn't work at all. Simplesamlphp didn't work but didn't produce any errors i could attach. So perhaps it makes sense to mention the alternative nginx configuration in the documentation.

I am using:
PHP 7.4.2 (fpm-fcgi) (built: Jan 24 2020 07:18:09)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies
    with Xdebug v2.9.2, Copyright (c) 2002-2020, by Derick Rethans
nginx 1.17.0

PHP is served by an alpine docker image.

**Comment by thijskh** [comment]
So I think what is in the development branch now https://simplesamlphp.org/docs/development/simplesamlphp-install#section_6 matches the solution stated above. We've ensured the same snippet will land in the stable documentation.

Given the positive experiences in this thread with that version of the docs I'm closing this now. But please _do_ let us know if we should improve on https://simplesamlphp.org/docs/development/simplesamlphp-install#section_6 even further.

**Comment by ZaneCEO** [comment]
Hi @thijskh ! I'm trying to setup ssp for the very first time. The documentation shows this:

`location ~ ^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {`

What should I replace `<prefix>`, `<phpfile>`, `<pathinfo>` with? These are just placeholders, right?

Thanks

**Comment by ZaneCEO** [comment]
Ok, i think I worked it out. The example provided in the documentation is non-sense to me (sorry, it's probabily my fault, but the placeholders means absolutely nothing to me).

So I combined https://github.com/simplesamlphp/simplesamlphp/issues/751#issuecomment-393509612 with a bit of nginx basic and got this:

````
server {

    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    
    server_name mysite.io;
    root /var/www/simplesaml/www;

    error_log //var/www/simplesaml/var/log/nginx-error.log;
    access_log /var/www/simplesaml/var/log/nginx-access.log;


    ## Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/mysite.io/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mysite.io/privkey.pem;

    index index.php index.html index.htm index.nginx-debian.html;

    location ^~ /simplesaml {
        alias /var/www/simplesaml/www;

        location ~ \.php(/|$) {
            include fastcgi_params;
            fastcgi_pass unix:/run/php/php7.4-fpm.sock;
            fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            fastcgi_param PATH_INFO $fastcgi_path_info if_not_empty;
        }
    }
}
````

This seems to be working as expected.

Thanks.

**Comment by niallfleming** [comment]
No they're capturing variables. If you note, it utilises $phpfile further down in the stanza.

**Comment by niallfleming** [comment]
But using my ungreedy regex works too!

**Comment by ZaneCEO** [comment]
Thanks @niallfleming ! https://github.com/simplesamlphp/simplesamlphp/issues/751#issuecomment-393509612 is actually yours, and is the only one that works for me

**Comment by hseritt** [comment]
```
 server {
        listen       443 ssl ;
        server_name  idp.alfresco-consulting.com;
        root /var/simplesamlphp/www;

        ssl_certificate /etc/letsencrypt/live/alfresco-consulting.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/alfresco-consulting.com/privkey.pem;
        ssl_protocols       TLSv1.3 TLSv1.2;
        ssl_ciphers            EECDH+AESGCM:EDH+AESGCM;

        index index.php;

        location ^~ /simplesaml {
             alias /var/simplesamlphp/www;
             location ~ ^(?<prefix>/simplesaml)(?<phpfile>.+?\.php)(?<pathinfo>/.*)?$ {
                include          fastcgi_params;
                fastcgi_index    index.php;
                fastcgi_pass     unix:/run/php-fpm/www.sock;
                fastcgi_param SCRIPT_FILENAME $document_root$phpfile;

                # Must be prepended with the baseurlpath
                fastcgi_param SCRIPT_NAME /simplesaml$phpfile;

                fastcgi_param PATH_INFO $pathinfo if_not_empty;
            }
        }
    }
```

None of this seems to work. What am I doing wrong?

**Comment by tvdijen** [comment]
Loose the space;  https://github.com/simplesamlphp/simplesamlphp/commit/42e321480c685bb9c47492ca9698aeca8b96a819
