### ISSUE TITLE
better security scrutiny: enable Scrutinizer security checks

### ISSUE THREAD

**Issue by restena-sw** [simplesamlphp/simplesamlphp#755]
I see that simpleSAMLphp is using Scrutinizer  at https://scrutinizer-ci.com/g/simplesamlphp/simplesamlphp/?branch=master - great! We use it for eduroam CAT as well and it is awesome.

You do not seem to have Security Analysis enabled. It is free for open-source projects. CAT got it enabled simply contacting the team via the chat box - within minutes. They also state that this is how it is supposed to work:

"Unfortunately, the security analysis is currently not available for your project. If you are a non-commercial open-source project, please contact support to gain access."

In CAT, we found a number of security issues with almost no false positives. I can only recommend enabling this feature.

**Comment by jaimeperez** [comment]
Hi Stefan!

I did that indeed long time ago (I’d say years by now), and I’m still waiting for a response... 😔

**Comment by tvdijen** [comment]
I think they've dropped the 'open-source' requirement.. I was able to enable it in the configuration

**Comment by jaimeperez** [comment]
I tried contacting them last week again, and this time I got a response pretty fast...
