### ISSUE TITLE
Fatal Error on Crypto.php 415

### ISSUE THREAD

**Issue by reya276** [simplesamlphp/simplesamlphp#757]
I keep getting an fatal error.
Fatal error: Call to undefined function SimpleSAML\Utils\mb_strlen() in /var/simplesamlphp/lib/SimpleSAML/Utils/Crypto.php on line 415

I followed the instructions for the install but it seems as though I'm missing something.
I created the secret salt but still getting the same fatal error.

**Comment by tvdijen** [comment]
You need to install the php-mbstring module in order to make SimpleSAMLphp work.
If you need any further assistence, please use the [mailing lists](https://simplesamlphp.org/lists).

**Comment by reya276** [comment]
I do have it installed :(

**Comment by tvdijen** [comment]
Then for some reason it isn't loaded...
Is it mentioned on this page? `/admin/phpinfo.php`?

**Comment by reya276** [comment]
Oh that throws the same error.

**Comment by reya276** [comment]
It looks like I needed to re-install it. that fixed the issue. Thanks!
