### ISSUE TITLE
core/authenticate.php is reachable without admin password

### ISSUE THREAD

**Issue by unt01d** [simplesamlphp/simplesamlphp#758]
Hi,

I notice that I can still reach the `core/authenticate.php` page without logging in as an admin when using `'admin.protectindexpage' => true`.  Is there a reason for this?  I'm keen to ensure that the admin resources aren't available in production.  Happy to submit a PR with a fix.

The `sanitycheck/index.php` page has the same issue, but I can work-around that by disabling the module.  Probably not an option with `core`  :)

Thanks,
Chris

**Comment by tvdijen** [comment]
Sanitycheck should probably adhere to the `admin.protectindexpage` setting because it could leak file paths, but the `core/authenticate.php` doesn't leak any information and is incredibly useful for debugging purpuses.

**Comment by unt01d** [comment]
Hi @tvdijen,

Thanks for the reply.   I get that the page doesn't leak particularly sensitive information, but would it hurt to at least have the option of hiding it in a way that's consistent with the other admin features?  My feeling is that any resource that's solely used for debugging and isn't directly involved in serving SAML requests shouldn't be openly available in production.

Thanks,
Chris

**Comment by thijskh** [comment]
Perhaps this is something to incorporate in the new layout (branch `Xnew-ui`) which has a more clear separation between user- and admin ui's?

**Comment by tvdijen** [comment]
Yes, but how are we going to accomodate this, because different people have different needs when it comes to securing pages like this.

**Comment by tvdijen** [comment]
1.17 came with an experimental admin module.. It's not completely usable, but will be in 1.18 the replacement for the current interface..
For our next major, the solution would be to disable the admin module.. It may take a while, but for now I'm closing this issue since there is no actual issue and things will resolve eventually
