### ISSUE TITLE
Support custom instantiation of Auth Source classes

### ISSUE THREAD

**Issue by unt01d** [simplesamlphp/simplesamlphp#762]
I'm pretty keen to get some unit tests written for the Auth Source I've created, however it's difficult to do so because I don't have control over instantiation of the Auth Source class, and hence am not able to inject the class's dependencies.

Can we do something to enable custom instantiation of these classes?

**Comment by unt01d** [comment]
Added an example of how this could potentially be achieved [here](https://github.com/simplesamlphp/simplesamlphp/pull/763).

**Comment by tvdijen** [comment]
This was closed in #763
