### ISSUE TITLE
Requirement for grouping multiple countries

### ISSUE THREAD

**Issue by shijuckl** [simplesamlphp/simplesamlphp#764]
We have a requirement to implement SSO for list websites using single Identity Provider(IDP) based on below 
1) Countries - One country website user should not login to other country website
2) Security Level - each website is having a security level. user should not login if security level is different.

**Comment by thijskh** [comment]
This seems more like a support question than a bug. This is an issue tracker, not a support forum. Please direct your question to the [simpleSAMLphp user's mailing list](https://simplesamlphp.org/lists).
