### ISSUE TITLE
Strict Redirect URI Matching (authfacebook)

### ISSUE THREAD

**Issue by jozefbriss** [simplesamlphp/simplesamlphp#765]
Facebook wrote on Dec 19th, 2017:
------
In 90 days, we're making a security update to Facebook Login that will invalidate calls from URIs not listed in the Valid OAuth redirect URIs field of your Facebook Login settings.

This update comes in response to malicious activity we saw on our platform, and we want to protect your app or website by requiring a new strict mode for redirect URIs. Take action now to ensure your redirect traffic continues to work. 

https://developers.facebook.com/docs/facebook-login/security/#strict_mode
------

authfacebook module uses AuthState variable that makes each returning URL unique and these cannot be listed all in the Facebook Login App.

The fix should be to use state variable instead. Which is send to Facebook when initializing the call and Facebook is automatically adding it to return URL.

**Comment by thijskh** [comment]
Fixed in #767
