### ISSUE TITLE
Remote IDP option to support base64 encoded RelayState

### ISSUE THREAD

**Issue by geemang2000** [simplesamlphp/simplesamlphp#766]
I have a usecase with a complex RelayState. The RelayState needs to be encoded in order to preserve the original URL encoding. E.g. decoded version: http://idp.host.com?RelayState=https://somehost?p1=https://somehost2?p1=1&p2=2 etc 

I'd like to add an option to https://simplesamlphp.org/docs/stable/simplesamlphp-reference-idp-remote e.g. base64relaystate that would allow the ./modules/saml/www/sp/saml2-acs.php
to decode the RelayState prior to the checkURLAllowed processing. 

How does this sound?

**Comment by jaimeperez** [comment]
Hi @geemang2000!

I'm not entirely sure I see the need. What's the problem with URL encoding the RelayState? The IdP **must** return it untouched to your SP...

**Comment by geemang2000** [comment]
Thanks Jaime, you're correct. Found our issue, the is RelayState is bad. 

NOTE: I did learn that PHP urldecodes GET & POST parameters, which is what I was trying to get around.

**Comment by jaimeperez** [comment]
No prob, thanks for the feedback!
