### ISSUE TITLE
Is It Possible to Disable the Administration Web Page?

### ISSUE THREAD

**Issue by mino922** [simplesamlphp/simplesamlphp#769]
Is there a configuration option to disable the simpleSAML Administration Web Page?

**Comment by thijskh** [comment]
This is not a support forum, but set `admin.protectindexpage` to true and set a good password, and no-one can access you admin web pages.

**Comment by iluuu1994** [comment]
Our customer insists. Would you be interested in this contribution? If so could you instruct me on what's the best way to achieve this?

**Comment by jaimeperez** [comment]
Hi @iluuu1994!

We are already working on an _admin_ module holding all the admin-related pages, which can of course be disabled like any other module. You can test it in the current development version (master). If you can give it a try and give us feedback, that'll be greatly appreciated! Not to speak if you notice anything and contribute with a PR to fix/add/remove it 😉

**Comment by iluuu1994** [comment]
@jaimeperez That's great news! I'll try it and let you know how it works out. Do you know when this is scheduled to be released?

Just a heads up. Wanted to switch to master:

> simplesamlphp/simplesamlphp-module-negotiate v0.9.1 requires ext-krb5 * -> the requested PHP extension krb5 is missing from your system.

This module is disabled by default so this should probably be a composer suggestion instead of a hard error.
