### ISSUE TITLE
1.15.0 HTTP based SP - requireAuth() not working as intended

### ISSUE THREAD

**Issue by restena-sw** [simplesamlphp/simplesamlphp#776]
I have a SSP SP running 1.15.0. The software is accessible both on HTTP and HTTPS.

With identical code, on HTTPS, all is working fine: admin pages call requireAuth() which either authenticates the user or immediately comes back.

On HTTP, requireAuth() *always* redirects to the IdP; it's like it doesn't recognise that there's a valid session.

It then comes back to the original URL, which calls requireAuth(), which makes it go into a tight loop.

In config, session.cookie.secure is set to FALSE like it should for such cases.

With logging level DEBUG, I indeed see that the session is not considered valid. A tight loop with three runs is below.

Jan 30 09:55:17 simplesamlphp DEBUG [1521c36ea6] Loading state: '_46d53ac7a6ea0084e9ee2194db95919c52a6974d65'
Jan 30 09:55:17 simplesamlphp WARNING [1521c36ea6] Could not load state specified by InResponseTo: NOSTATE Processing response as unsolicited.
Jan 30 09:55:17 simplesamlphp DEBUG [1521c36ea6] Received SAML2 Response from 'https://monitor.eduroam.org/sp/saml2/idp/metadata.php'.
Jan 30 09:55:17 simplesamlphp DEBUG [1521c36ea6] Has 1 candidate keys for validation.
Jan 30 09:55:17 simplesamlphp DEBUG [1521c36ea6] Validation with key #0 succeeded.
Jan 30 09:55:17 simplesamlphp DEBUG [1521c36ea6] Has 1 candidate keys for validation.
Jan 30 09:55:17 simplesamlphp DEBUG [1521c36ea6] Validation with key #0 succeeded.
Jan 30 09:55:17 simplesamlphp DEBUG [1521c36ea6] Filter config for https://monitor.eduroam.org/sp/saml2/idp/metadata.php->http://ticker.eduroam.lu/simplesaml/module.php/saml/sp/metadata.php/default-sp: array (  0 =>   sspmod_core_Auth_Process_GenerateGroups::__set_state(array(     'generateGroupsFrom' =>     array (      0 => 'eduPersonAffiliation',    ),     'priority' => 60,  )),  1 =>   sspmod_core_Auth_Process_AttributeAdd::__set_state(array(     'replace' => false,     'attributes' =>     array (      'groups' =>       array (        0 => 'users',        1 => 'members',      ),    ),     'priority' => 61,  )),  2 =>   sspmod_core_Auth_Process_LanguageAdaptor::__set_state(array(     'langattr' => 'preferredLanguage',     'priority' => 90,  )),)
Jan 30 09:55:17 simplesamlphp DEBUG [1521c36ea6] GenerateGroups - attribute 'eduPersonAffiliation' not found.
Jan 30 09:55:17 simplesamlphp DEBUG [1521c36ea6] Session: doLogin("default-sp")
Jan 30 09:55:17 simplesamlphp WARNING [1521c36ea6] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Jan 30 09:55:17 simplesamlphp DEBUG [f13288168b] Session: 'default-sp' not valid because we are not authenticated.
Jan 30 09:55:17 simplesamlphp DEBUG [f13288168b] Saved state: '_c946bea109362eedb9c370bd7e0e2a6e822274391f'
Jan 30 09:55:17 simplesamlphp DEBUG [f13288168b] Sending SAML 2 AuthnRequest to 'https://monitor.eduroam.org/sp/saml2/idp/metadata.php'
Jan 30 09:55:17 simplesamlphp DEBUG [f13288168b] Redirect to 686 byte URL: https://monitor.eduroam.org/sp/saml2/idp/SSOService.php?SAMLRequest=nZJLjxMxEIT%2Fysj3iWcmu3lYSaSwESLSwkY7gQMX1Bl3NhZ%2BDO42j3%2BPM1lg4ZAD127XV%2BVSLwic7dU68ck%2F4peExMV3Zz2pYbEUKXoVgAwpDw5Jcafa9dt71Ywq1cfAoQtWvJBcVwARRjbBi2K7WYpP3fxmckCoq%2Fl40iDqw7wbT6uDnmKFDUxw1jTN9GY8r4%2Bi%2BICRsnIpMijLiRJuPTF4zqOqnpVVXY6rfTVTt7eqnn4UxSb%2FxnjgQXVi7klJ6YI3HOIIdYoB3CjEJ0m9PGdvpNG9bNuHFuNX0%2BGoP%2FWiWP%2FKfBc8JYfxefv%2B8f5CzVA23Wf8w7RJknG9xTM1O%2BpkB9jg8tuthI6GqcYjJMslZbfdc6evjNfGP12v83B5ROrNfr8rdw%2FtXqwWZ7Ya6omr%2F4znkEEDwz%2FpFvIle3E5nXc51XazC9Z0P4rXITrg66HPE6PL4%2FBUcQRPBj3noq0N3%2B4iAuNScEwo5Opi%2BfeBrn4C&RelayState=http%3A%2F%2Fticker.eduroam.lu%2Fcat-trunk%2Fadmin%2Foverview_user.phparray (
)
Jan 30 09:55:17 simplesamlphp WARNING [f13288168b] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Jan 30 09:55:18 simplesamlphp DEBUG [2b39d0f766] Loading state: '_c946bea109362eedb9c370bd7e0e2a6e822274391f'
Jan 30 09:55:18 simplesamlphp WARNING [2b39d0f766] Could not load state specified by InResponseTo: NOSTATE Processing response as unsolicited.
Jan 30 09:55:18 simplesamlphp DEBUG [2b39d0f766] Received SAML2 Response from 'https://monitor.eduroam.org/sp/saml2/idp/metadata.php'.
Jan 30 09:55:18 simplesamlphp DEBUG [2b39d0f766] Has 1 candidate keys for validation.
Jan 30 09:55:18 simplesamlphp DEBUG [2b39d0f766] Validation with key #0 succeeded.
Jan 30 09:55:18 simplesamlphp DEBUG [2b39d0f766] Has 1 candidate keys for validation.
Jan 30 09:55:18 simplesamlphp DEBUG [2b39d0f766] Validation with key #0 succeeded.
Jan 30 09:55:18 simplesamlphp DEBUG [2b39d0f766] Filter config for https://monitor.eduroam.org/sp/saml2/idp/metadata.php->http://ticker.eduroam.lu/simplesaml/module.php/saml/sp/metadata.php/default-sp: array (  0 =>   sspmod_core_Auth_Process_GenerateGroups::__set_state(array(     'generateGroupsFrom' =>     array (      0 => 'eduPersonAffiliation',    ),     'priority' => 60,  )),  1 =>   sspmod_core_Auth_Process_AttributeAdd::__set_state(array(     'replace' => false,     'attributes' =>     array (      'groups' =>       array (        0 => 'users',        1 => 'members',      ),    ),     'priority' => 61,  )),  2 =>   sspmod_core_Auth_Process_LanguageAdaptor::__set_state(array(     'langattr' => 'preferredLanguage',     'priority' => 90,  )),)
Jan 30 09:55:18 simplesamlphp DEBUG [2b39d0f766] GenerateGroups - attribute 'eduPersonAffiliation' not found.
Jan 30 09:55:18 simplesamlphp DEBUG [2b39d0f766] Session: doLogin("default-sp")
Jan 30 09:55:18 simplesamlphp WARNING [2b39d0f766] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Jan 30 09:55:18 simplesamlphp DEBUG [39bdeefbe8] Session: 'default-sp' not valid because we are not authenticated.
Jan 30 09:55:18 simplesamlphp DEBUG [39bdeefbe8] Saved state: '_89abc2316d348a04f587878f04002717eb38975760'
Jan 30 09:55:18 simplesamlphp DEBUG [39bdeefbe8] Sending SAML 2 AuthnRequest to 'https://monitor.eduroam.org/sp/saml2/idp/metadata.php'
Jan 30 09:55:18 simplesamlphp DEBUG [39bdeefbe8] Redirect to 678 byte URL: https://monitor.eduroam.org/sp/saml2/idp/SSOService.php?SAMLRequest=nZLLbtswEEV%2FReBeJuVHpBC2ASdGUANpYkRuF9kEtDSOifChcoZ5%2FH1oOW3TLrwIuJuZe%2B7lYKaorOnkItLe3cGvCEjZqzUOZd%2BYsRic9Ao1SqcsoKRG1ovv13I4ELILnnzjDfskOa1QiBBIe8ey1XLGHqpztW2Go%2BKsHY0rJca7SVWmtxNjIYZlUcJ2VJ2Xk%2FJMsOwnBEzKGUugJEeMsHJIylEqiaLKRZGPxEZUcjKRRXXPsmX6jXaKetWeqEPJufVOkw8DaGPwyg58eOTY8UP2Iddtx%2Bv6tobwrBsYdPuOZYvfmS%2B9w2ghfHR%2F3F0fqQlKunmCv0wTOWrbGThQk2MbTQ%2FrXf645arBvtrCTkVDOSa39cdOL7RrtXs8vc7tcQjlt81mna9v6w2bTw9s2a8nzL8YzwKpVpH6L92Uf2ZPj6dzk1KtlmtvdPOWXflgFZ0OfajoNt%2F1o5KCcqjBUVq0Mf7lMoAimDEKERifHy3%2FPdD5Ow%3D%3D&RelayState=http%3A%2F%2Fticker.eduroam.lu%2Fcat-trunk%2Fadmin%2Foverview_user.phparray (
)
Jan 30 09:55:18 simplesamlphp WARNING [39bdeefbe8] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Jan 30 09:55:20 simplesamlphp DEBUG [304ff7201b] Loading state: '_89abc2316d348a04f587878f04002717eb38975760'
Jan 30 09:55:20 simplesamlphp WARNING [304ff7201b] Could not load state specified by InResponseTo: NOSTATE Processing response as unsolicited.
Jan 30 09:55:20 simplesamlphp DEBUG [304ff7201b] Received SAML2 Response from 'https://monitor.eduroam.org/sp/saml2/idp/metadata.php'.
Jan 30 09:55:20 simplesamlphp DEBUG [304ff7201b] Has 1 candidate keys for validation.
Jan 30 09:55:20 simplesamlphp DEBUG [304ff7201b] Validation with key #0 succeeded.
Jan 30 09:55:20 simplesamlphp DEBUG [304ff7201b] Has 1 candidate keys for validation.
Jan 30 09:55:20 simplesamlphp DEBUG [304ff7201b] Validation with key #0 succeeded.
Jan 30 09:55:20 simplesamlphp DEBUG [304ff7201b] Filter config for https://monitor.eduroam.org/sp/saml2/idp/metadata.php->http://ticker.eduroam.lu/simplesaml/module.php/saml/sp/metadata.php/default-sp: array (  0 =>   sspmod_core_Auth_Process_GenerateGroups::__set_state(array(     'generateGroupsFrom' =>     array (      0 => 'eduPersonAffiliation',    ),     'priority' => 60,  )),  1 =>   sspmod_core_Auth_Process_AttributeAdd::__set_state(array(     'replace' => false,     'attributes' =>     array (      'groups' =>       array (        0 => 'users',        1 => 'members',      ),    ),     'priority' => 61,  )),  2 =>   sspmod_core_Auth_Process_LanguageAdaptor::__set_state(array(     'langattr' => 'preferredLanguage',     'priority' => 90,  )),)
Jan 30 09:55:20 simplesamlphp DEBUG [304ff7201b] GenerateGroups - attribute 'eduPersonAffiliation' not found.
Jan 30 09:55:20 simplesamlphp DEBUG [304ff7201b] Session: doLogin("default-sp")
Jan 30 09:55:20 simplesamlphp WARNING [304ff7201b] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.
Jan 30 09:55:20 simplesamlphp DEBUG [09114ad976] Session: 'default-sp' not valid because we are not authenticated.
Jan 30 09:55:20 simplesamlphp DEBUG [09114ad976] Saved state: '_aec1d59bf8d94db79e4f1b449c20fae06934c82111'
Jan 30 09:55:20 simplesamlphp DEBUG [09114ad976] Sending SAML 2 AuthnRequest to 'https://monitor.eduroam.org/sp/saml2/idp/metadata.php'
Jan 30 09:55:20 simplesamlphp DEBUG [09114ad976] Redirect to 684 byte URL: https://monitor.eduroam.org/sp/saml2/idp/SSOService.php?SAMLRequest=nZLNj9MwEMX%2Flcj31Ek2hcZqK5WtEJUWttoUDlyQa0%2B2Fv4InjEf%2Fz1uusDCoQeuM36%2F9%2Fw0S5TOjmKT6OQf4EsCpOK7sx7FtFixFL0IEg0KLx2gICX6zds70cwqMcZAQQXLnkmuKyQiRDLBs2K3XbFPElSt591xWOiu1ceXHbRDfWzbTjXVIKF60d20atHUdc2KDxAxK1csg7IcMcHOI0lPeVTVi7Kqy5vqUC3EfC6a6iMrtvk3xkuaVCeiEQXnLnhDIc5Apxikm4X4yHHk5%2BwNN3rkfX%2FfQ%2FxqFMzG08iKza%2FMt8FjchCftu8f7i7UDCWjPsMfpk0cjRstnKnZUSc7wSaX326lVDhNNQwyWSoxu%2B2fOn1lvDb%2B8Xqdx8sjFG8Oh325v%2B8PbL08s8VUT1z%2FZzwHJLUk%2BU%2B6JX%2FOXl5O511OtdvugzXqR%2FE6RCfpeujzxOhymJ4KitKjAU%2B5aGvDt9sIkmDFKCZgfH2x%2FPtA1z8B&RelayState=http%3A%2F%2Fticker.eduroam.lu%2Fcat-trunk%2Fadmin%2Foverview_user.phparray (
)
Jan 30 09:55:20 simplesamlphp WARNING [09114ad976] The class or interface 'SimpleSAML_Logger' is now using namespaces, please use 'SimpleSAML\Logger'.

**Comment by jaimeperez** [comment]
Hi Stefan!

Can you paste here the code you are using?

Also, what's the `baseurlpath` you have configured? The log is not indicating that your session is invalid (I reckon the log message might be a bit unfortunate here), but more likely that the session is missing. All the failures to restore the state clearly indicate a problem when saving it to the session.

I'd recommend you to use the SAML tracer to trace the entire exchange and analyze the responses you get from SSP to see if a session cookie is set, and in that case, with what parameters, and whether the browser sends it back in subsequent requests or not.

**Comment by restena-sw** [comment]
Okay, this is more strange than just this. This also doesn't work on HTTPS, and the trigger is ... somewhere. If one enters the target URL directly, login works (and SSP's cookie is there), but if called from a JavaScript XHR, it does not.

The code in our authentiate() function goes like this:

        $authSimple = new \SimpleSAML\Auth\Simple(CONFIG['AUTHENTICATION']['ssp-authsource']);
        $session = \SimpleSAML_Session::getSessionFromRequest();
        $authSimple->requireAuth();
        $admininfo = $authSimple->getAttributes();
        $session->cleanup();

And we don't get past requireAuth() in those strange circumstances.

**Comment by restena-sw** [comment]
Okay... we maybe have an idea what the difference in click path is.

Calling the URL manually immediately triggers requireAuth().

Displaying another page before first calls our own isAuthenticated():
        $authSimple = new \SimpleSAML\Auth\Simple(CONFIG['AUTHENTICATION']['ssp-authsource']);
        $session = \SimpleSAML_Session::getSessionFromRequest();
        $status = $authSimple->isAuthenticated();
        $session->cleanup();
        return $status;

We are doing this $session stuff newly in 1.15 because we want our own PHP session back (you may remember our ML discussion).

Now my suspicion is that $session->cleanup() might destroy the SSP session entirely, and a subsequent call to requireAuth() needs to start fresh then? Is my understanding correct here?

**Comment by jaimeperez** [comment]
What happens if you try this?

```patch
--- test1.php	2018-01-30 12:14:32.000000000 +0100
+++ test2.php	2018-01-30 12:14:46.000000000 +0100
@@ -1,7 +1,7 @@
 <?php
 $authSimple = new \SimpleSAML\Auth\Simple(CONFIG['AUTHENTICATION']['ssp-authsource']);
-$session = \SimpleSAML_Session::getSessionFromRequest();
 $authSimple->requireAuth();
 $admininfo = $authSimple->getAttributes();
+$session = \SimpleSAML_Session::getSessionFromRequest();
 $session->cleanup();
```

**Comment by restena-sw** [comment]
I switched the position, but to no effect.

As noted earlier, the code actually calls ->cleanup() in another function before this snippet. Maybe all SSP state is thrown away by that?

**Comment by jaimeperez** [comment]
The thing is `cleanup()` doesn't throw away or destroy anything. It just saves the session and restores the previously existing one, if there was. It doesn't matter if you call it (and unload SSP's session) and then call `requireAuth()` again, because that'll load SSP's session again. It's just a waste of resources, but other than that it should work.

Now that I read more carefully, though, I see you mentioned it works fine except if you perform the request via javascript. What's the value of the `session.phpsession.httponly` configuration option?

**Comment by restena-sw** [comment]
'session.phpsession.httponly'    => FALSE,

Also, while there is JS involved - the JS only does a window.location.repalce to the URL that one can call successfully directly. I don't think httponly would play a role here? This is not XHR of any kind.

Here's what I'm talking about:

$auth = new \web\lib\admin\Authentication();
                if ($auth->isAuthenticated()) {
                    $out .= '<script type="text/javascript">goAdmin()</script>';
                } else {

... and then ...
  
  function goAdmin() {
   waiting('start');
   window.location.replace("<?php echo $Gui->skinObject->findResourceUrl("BASE", "admin/overview_user.php")?>?lang="+lang);
}

**Comment by restena-sw** [comment]
Okay, I found the trigger for this behaviour. I just don't understand it :-)

Our own cookie handling is done centrally in a function like this:

function CAT_session_start() {
    if (session_status() != PHP_SESSION_ACTIVE) {
        session_set_cookie_params(0, "/", $_SERVER['SERVER_NAME'], (isset($_SERVER['HTTPS']) ? TRUE : FALSE ));
        session_start();
    }
}

This leads to the behaviour we are discussing.

HOWEVER:

As soon as I comment out the line with session_set_cookie_params() - all work s gain.

But why? I'm a bit clueless here.

We were asked to set the SECURE flag on HTTPS by our secure code audit team, which is the only reason for calling the function. All the other parameters are pretty much the default values (which is what we were using before; no call to that function at all).

I've also confirmed that the secure flag is set as planned - debug output of the corresponding get function shows FALSE on HTTP.

**Comment by jaimeperez** [comment]
Hi Stefan!

I only mentioned `httponly` because you said previously that the request that was failing was being performed via Javascript XHR...

In any case, what are the names of your app's session and SSP's session? I understand you have two different session names there. Are you setting that explicitly by calling `session_name()`? If you don't do that, calling the `CAT_session_start()` function (which doesn't set the session name) after returning from SSP could be the reason for the session disappearing.

Would you mind tracing the HTTP requests and responses during a failure, and publishing it here? I'm absolutely sure that the problem here is that something is smashing SimpleSAMLphp's session, and that should be evident by inspecting the HTTP traces.

**Comment by restena-sw** [comment]
Here's the session name in SSP config:

        'session.cookie.name' => 'SimpleSAMLSessionID',

and you are correct that we don't add a name for our own handler. Not sure how that can have an effect only when calling session_set_cookie_params(). I would think there's either a clash or not, as that set function doesn't interfere with the cookie name.

The php.ini default (which we then use) is:

; Name of the session (used as cookie name).
; http://php.net/session.name
session.name = PHPSESSID

Digging deeper into this, I now see this comment on the session_set_cookie_params() doc page:

"i found it somewhat difficult to work with sessions due to the documentation not really denoting the necessity for the session name to be set via session_name() in order for session_set_cookie_params() to be of any use.  i found no reference to session_name() in this article, and my session functions would have been a disastrous mess were it not for a friend familiar with session.

so, in essence, for anybody wondering about where to start: declare a session name before using session_set_cookie_params(), otherwise you might agitate php to the point of committing some atrocity against your webserver."

So maybe not setting a name is (unintuitively) breaking that function? I'll try this ASAP...

**Comment by restena-sw** [comment]
Indeed. Calling session_name("foo") before session_set_cookie_params(...) makes things work.

"Funny" that only a nine year old comment on a PHP documentation page talks about that :-(

Anyway: I guess that solves my issue. Thanks for guiding me in the right direction!

**Comment by jaimeperez** [comment]
No problem Stefan, glad you got it to work!

And yes, the PHP documentation regarding session management leaves a lot to be desired, IMHO.
