### ISSUE TITLE
Theming documentation does not cover Twig

### ISSUE THREAD

**Issue by ghalse** [simplesamlphp/simplesamlphp#781]
The [upgrade notes for 1.15](https://simplesamlphp.org/docs/stable/simplesamlphp-upgrade-notes-1.15) note that a new templating system has been introduced. However, the [theming documentation](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-theming.md) makes no reference to Twig at all.

A cursory check shows that if I've customised `header.php` and/or `footer.php` in `modules/mymodule/themes/fancytheme/default/includes/` as suggested in the theming documentation, then at least the sanitycheck module ignores the old templates from the theme in favour of the default Twig template. I would imagine that the number of things broken in this way will grow as modules migrate and that, for some time to come, we need to be maintaining both Twig and legacy versions of the templates.

Since theming to an institutional look and feel is a very common requirement, it would make sense for the upgrade notes to give some guidance on how to handle this in the upgrade notes. It would also make sense to update the theming documentation to provide updated guidance to people trying to produce new themes.

**Comment by lonoak** [comment]
Hi Guy,  not sure [these](https://github.com/simplesamlphp/simplesamlphp/wiki/Twig:-Migrating-templates) [two](https://github.com/simplesamlphp/simplesamlphp/wiki/New-UI) articles by Olimpia could be a starting point. 

In any case, we have plans to create a new skin using Twig, so maybe we could help on documenting this.

@thijskh , I think @jaimeperez  mentioned the current documentation is not yet included in github... any conventions to contribute documentation to SimpleSAMLphp?  could we use the github wiki for this purpose? is markdown a good format that could be easily adapted to the official documentation pages?

**Comment by ghalse** [comment]
I should have referenced this issue from #800, where I had a go at producing some documentation.

**Comment by lonoak** [comment]
Oooops... true. I didn't see that other issue. Thanks Guy!

**Comment by MicWit** [comment]
I am new to simplesamlpphp and have the test authentication running, but am now up to creating my own theme. I want to use the twig template (as I have used Symfony a lot in the past so know twig), but can not get it to take over. I have made my own theme which has the following files (in modules/modulename/themes/themename/default/:
includes/footer.php
includes/header.php
base.twig
_footer.twig
_header.twig
index.twig
From the documentation, if you copy the twig files in, twig is meant to take over, but it isn't. I saw somewhere about a 'usenewui' => true and added that to the config.php but still doesn't work. In all this, if I edit includes/header.php I see the change, so I know its not using the twig system.
Is there something else I need to do? If so, this really should be added to https://simplesamlphp.org/docs/stable/simplesamlphp-theming
I notice there is a bit more in the development section (which seems is still not enough to get it to work -https://simplesamlphp.org/docs/development/simplesamlphp-theming), but as this is now a feature that has been in stable for a while, it should be added to the stable branch of the docs.

**Comment by tvdijen** [comment]
I think you need to set `'language.i18n.backend' => 'gettext/gettext'`.

**Comment by MicWit** [comment]
I modified that line to be:
```
'language.i18n.backend' => 'gettext/gettext',
'usenewui' => true,
```
in config/config.php but still nothing. Is the line:
`'theme.use' => 'fancymodule:fancytheme',`
still correct for Twig?

**Comment by tvdijen** [comment]
Should be fine.. Is your fancy module enabled?

**Comment by MicWit** [comment]
It sure is, as the .php files in there are being used. Just need it to prioritise the twig files.

**Comment by tvdijen** [comment]
Any hints in the debug-log?
