### ISSUE TITLE
Is `redirect.trustedsites` still correct, or should it be `trusted.url.domains`?

### ISSUE THREAD

**Issue by forevermatt** [simplesamlphp/simplesamlphp#786]
https://github.com/simplesamlphp/simplesamlphp/blob/558ec6e527db770da45987bf3d65c9560fabd987/lib/SimpleSAML/Utils/HTTP.php#L971

The doc. comment on `HTTP::redirectUntrustedURL()` references using `redirect.trustedsites`, but looking at the code, it appears that the correct config entries to use are `trusted.url.domains` or `trusted.url.regex`.

Is `redirect.trustedsites` still in use?

**Comment by thijskh** [comment]
You are right, `redirect.trustedsites` has been removed in SSP 1.14 (7be5684e41effce46df3cf48dbfdefb3b876d749).
