### ISSUE TITLE
Stuck on redirecting to Consent page 

### ISSUE THREAD

**Issue by stardocs-services** [simplesamlphp/simplesamlphp#809]
Not sure if this is a configuration issue: 
When I log into my site https://www.site.com/Login, it redirects me to my IDP login and consent page(SSOCircle). Once I verify my identity, it is supposed to redirect me back to my login page which is https://www.site.com/Login. 
However, currently instead of loading to my login page, it just goes back to the IDP consent page and asks me to reverify that I am not a robot.
When I test it through the simplesaml admin page it verifies properly and sends data back to the admin page though. Not sure what is wrong with my configuration. 
This is my login page code

```
        public function index()
	{
           $sp_auth = 'default-sp';
           $as = new SimpleSAML_Auth_Simple($sp_auth);
           if(!$as->isAuthenticated()){
               $params = array("ErrorURL"=>BASE_URL,"ReturnTo"=>BASE_URL);
               $as->login($params);
           }
           $attributes = $as->getAttributes();
           var_dump($attributes);
	}
```

Hope someone sees this.

**Comment by jaimeperez** [comment]
Hi,

This is an issue tracker, not a support forum. For questions about the software you should use the [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, what's the value of `BASE_URL` here? You don't need to specify the return URL, SimpleSAMLphp will automatically detect it and redirect back there. What version of the software are you running?
