### ISSUE TITLE
Can not filter IdPs by SP

### ISSUE THREAD

**Issue by pkroh** [simplesamlphp/simplesamlphp#814]
Hi,
Currently I can define one IdP related to one SP by setting 'idp' in authsources.php. When I set it to null I get all the IdPs in $metadata. It would be great to be able to provide a list of IdPs that I want to show In my SP.
I now have the problem that students will be confused because in the dropdown there are Universities (IdPs) now that don't have anything to do with their use case.

**Comment by gfaust-qb** [comment]
`    'example-multi' => array(
        'multiauth:MultiAuth',
        /*
         * The available authentication sources.
         * They must be defined in this authsources.php file.
         */
        'sources' => array('default-sp', 'training-sp'),
    ),
`
Isn't it possible to use this for your needs?

**Comment by pkroh** [comment]
Wouldn't that mean I have to set up a SP for every IdP? Thats definitely not what I want.

**Comment by mschwager** [comment]
Isn't this already possible via simplesamlphp's [scoping rules](https://simplesamlphp.org/docs/stable/simplesamlphp-scoping#section_2)? Which says you can specify something like:

```
'IDPList' => array(
    'IdPEntityID1',
    'IdPEntityID2',
    'IdPEntityID3',
),
```

In the following places:

- as a state parameter to the authentication source
- in the saml:SP authentication source configuration
- in the saml20-idp-remote metadata
- in the saml20-sp-remote metadata

**Comment by tvdijen** [comment]
I think @mschwager has given the right answer..
