### ISSUE TITLE
Don't try to autoload the 'Throwable' interface

### ISSUE THREAD

**Issue by kfonce** [simplesamlphp/simplesamlphp#818]
In Configuration.php there is a check on the 'Throwable' interface to give meaningful error messages in PHP7.
https://github.com/simplesamlphp/simplesamlphp/blob/03babb1a0d7bd0423af2f830b54af124c188ed58/lib/SimpleSAML/Configuration.php#L121
The default functionality of `interface_exists` is to try and autoload the given interface_name. This behaviour made my application fail. I think its safe to _not_ autoload the interface that's being tested for.

**Comment by tvdijen** [comment]
Yes, ik makes total sense to add `false` as a second parameter here. Thanks Ken!
