### ISSUE TITLE
Session: 'default-sp' not valid because we are not authenticated.

### ISSUE THREAD

**Issue by nitin-gwl** [simplesamlphp/simplesamlphp#838]
Session: 'default-sp' not valid because we are not authenticated.
Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] Saved state: '_7d238a236062653bf1cac8e0ebdf8537c7712b0f6a'
Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] Sending SAML 2 AuthnRequest to 'https://********/saml/metadata/743365'
Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] Sending message:
Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_7d238a236062653bf1cac8e0ebdf8537c7712b0f6a" Version="2.0" IssueInstant="2018-04-20T13:01:20Z" Destination="https://***********/trust/saml2/http-redirect/sso/743365" AssertionConsumerServiceURL="https://www.********/sso/module.php/saml/sp/saml2-acs.php/default-sp" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST">
Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb]   <saml:Issuer>https://www.************/sso/module.php/saml/sp/metadata.php/default-sp</saml:Issuer>
Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb]   <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" AllowCreate="true"/>
Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] </samlp:AuthnRequest>

**Comment by jaimeperez** [comment]
Hi @nitin-gwl,

This is an issue tracker, not a support forum. Please use the [mailing list](http://groups.google.com/group/simplesamlphp) for support questions. Also, make sure to describe what your problem is with all details available, as the log you are pasting here does not include any error at all.

**Comment by jaimeperez** [comment]
Hi,

As I told you here:

https://github.com/simplesamlphp/simplesamlphp/issues/838

There is no error message at all in there.

What is the problem?

On 23 Apr 2018, at 08:40 AM, nitin-gwl <notifications@github.com> wrote:
> Session: 'default-sp' not valid because we are not authenticated.
> Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] Saved state: '_7d238a236062653bf1cac8e0ebdf8537c7712b0f6a'
> Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] Sending SAML 2 AuthnRequest to 'https:///saml/metadata/743365'
> Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] Sending message:
> Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] <samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" ID="_7d238a236062653bf1cac8e0ebdf8537c7712b0f6a" Version="2.0" IssueInstant="2018-04-20T13:01:20Z" Destination="https://***/trust/saml2/http-redirect/sso/743365" AssertionConsumerServiceURL="https://www.********/sso/module.php/saml/sp/saml2-acs.php/default-sp" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST">
> Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] saml:Issuerhttps://www.************/sso/module.php/saml/sp/metadata.php/default-sp</saml:Issuer>
> Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] <samlp:NameIDPolicy Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient" AllowCreate="true"/>
> Apr 20 08:01:20 simplesamlphp DEBUG [42e3f4cadb] </samlp:AuthnRequest>

—
Jaime Pérez
Uninett / Feide

jaime.perez@uninett.no
jaimeperez@protonmail.com
9A08 EA20 E062 70B4 616B  43E3 562A FE3A 6293 62C2

"Two roads diverged in a wood, and I, I took the one less traveled by, and that has made all the difference."
- Robert Frost
