### ISSUE TITLE
add_authority not working in smartattributes

### ISSUE THREAD

**Issue by djdevin** [simplesamlphp/simplesamlphp#841]
https://github.com/simplesamlphp/simplesamlphp/blob/57df7b25fa558531c1e76aa686c5daec199b3fdc/modules/smartattributes/lib/Auth/Process/SmartID.php#L85-L89

It looks like `$request['saml:AuthenticatingAuthority'][0]` should be `$request['saml:sp:State']['saml:AuthenticatingAuthority'][0]`

This is the only way I could get the default configuration on https://simplesamlphp.org/docs/1.15/smartattributes:smartattributes to work.

**Comment by tvdijen** [comment]
Proposed change makes sense.. I've created a PR for this
