### ISSUE TITLE
Typo in SimpleSAML_Error_BadUserInnput

### ISSUE THREAD

**Issue by htto** [simplesamlphp/simplesamlphp#842]
Not quite sure if it is actually intended or has already been discussed, but while implementing an auth processing filter for our simplesamlphp-based IDP I noticed, that `BadUserInnput` of `SimpleSAML_Error_BadUserInnput` (`lib/SimpleSAML/Error/`) is written with two 'n'. Looks like a typo in filename and classname to me.

Kind regards,

Heiko

**Comment by tvdijen** [comment]
Thanks @htto !  I've addressed this in 87ddd04
