### ISSUE TITLE
lost data

### ISSUE THREAD

**Issue by inesdukic** [simplesamlphp/simplesamlphp#843]
As a user of AAI identity within EDuHr I got the information that my data are lost, I could not log in in the on-line course in progress and was given following code to help you (simpleSAMLphp) 
to track the problem
d030ed0ce7
Please, respond

**Comment by thijskh** [comment]
I’m afraid you’ve come to the wrong place, we’re not involved in running eduhr.

I believe that this page should help you further: http://www.carnet.hr/en/helpdesk
