### ISSUE TITLE
Unit test suite not executing fully

### ISSUE THREAD

**Issue by unt01d** [simplesamlphp/simplesamlphp#860]
It looks like there are several issues with the unit test suite at the moment which are producing unwanted log output and causing the test run to exit early.

Here's the output I'm getting (this is reflected in the builds too):

```
$ vendor/bin/phpunit -c tools/phpunit/phpunit.xml
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

................May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
May 22 13:00:41 SimpleSAMLphp WARNING [CL78e7bc2e] SimpleSAML_Configuration::getBaseURL() is deprecated, please use getBasePath() instead.
...............................................  63 / 358 ( 17%)
....May 22 13:00:41 SimpleSAMLphp ERROR [CL78e7bc2e] Language "foo" not installed. Check config.
May 22 13:00:41 SimpleSAMLphp ERROR [CL78e7bc2e] Language "bar" not installed. Check config.
.......May 22 13:00:42 SimpleSAMLphp INFO [CL78e7bc2e] Template: Looking up [Blablabla]: not translated at all.
May 22 13:00:42 SimpleSAMLphp WARNING [CL78e7bc2e] Deprecated use of new SimpleSAML\Locale\Translate::t(...) at /opt/7city/simplesamlphp/tests/lib/SimpleSAML/Locale/TranslateTest.php:37. This parameter will go away, the fallback will become identical to the $tag in 2.0.
May 22 13:00:42 SimpleSAMLphp INFO [CL78e7bc2e] Template: Looking up [Blablabla]: not translated at all.
.......May 22 13:00:42 SimpleSAMLphp WARNING [CL78e7bc2e] Invalid attempt to override registrationAuthority 'https://incommon.org' with 'overrides-are-ignored'
............................................. 126 / 358 ( 35%)
............................................................... 189 / 358 ( 52%)
............................................................... 252 / 358 ( 70%)
..........................................May 22 15:00:45 SimpleSAMLphp WARNING [CL78e7bc2e] AttributeValueMap: unknown configuration flag ''%test''
........<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="refresh" content="0;URL='http://localhost/simplesaml/module.php/core/cardinality_error.php?StateId=_9628dc8ebd28e377d880f4c0ee9211c606e9198509'">
    <title>Redirect</title>
  </head>
  <body>
    <h1>Redirect</h1>
      <p>You were redirected to: <a id="redirlink" href="http://localhost/simplesaml/module.php/core/cardinality_error.php?StateId=_9628dc8ebd28e377d880f4c0ee9211c606e9198509">http://localhost/simplesaml/module.php/core/cardinality_error.php?StateId=_9628dc8ebd28e377d880f4c0ee9211c606e9198509</a>
        <script type="text/javascript">document.getElementById("redirlink").focus();</script>
      </p>
  </body>
</html>
```

**Comment by unt01d** [comment]
Hi @tvdijen - are all the tests executing though?  I assumed that they weren't since I'd expect to see some summary output at the bottom along the lines of number of tests/assertions etc...

**Comment by tvdijen** [comment]
Ohh, I see.. I have been too quick here, sorry... Will investigate!!

**Comment by tvdijen** [comment]
It started after merging #848

**Comment by tvdijen** [comment]
And the culprit is this file:
tests/modules/core/lib/Auth/Process/CardinalityTest.php

**Comment by tvdijen** [comment]
Got it!
https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/HTTP.php#L201

@ghalse `testMissingAttribute` is supposed to raise an exception according to the Phpdoc, but that doesn't seem to be the case... I also noticed that many tests end with `$result = self::processFilter()` but are not followed by an actual assertion on the result.. Is that supposed to be?

**Comment by unt01d** [comment]
This is a good example of why both echoing output inline (rather than returning) and using either `exit` or `die` are bad ideas and should generally be avoided.  Having said that, if we're looking for a way to test the existing code without modifying then there's a couple of hacktastic things we can do.

Capturing the output is simple enough; we can just use the output buffer, e.g.:

```
ob_start();

$sut = new MyEchoingClass;
$sut->echoSomething();

$output = ob_get_clean();
$this->assertEquals('something', $output);
```

Overriding `exit` is slightly trickier, but doable via namespace overriding.  So we can declare our own version of `exit` under the namespace of the class under test within our test file, like so:

```
<?php
namespace SimpleSAML\Utils{
    function exit()
    {
        return;
    }
}

class Test_Core_Auth_Process_CardinalityTest extends \PHPUnit_Framework_TestCase
{
    // ...
}
```

**NB** I haven't run either of the above, but it gives you a general idea.  Hope that helps!

**Comment by thijskh** [comment]
FYI, I marked the affected tests as skipped for now. Ideal is to fix them, but the test suite should not be broken in the mean time. In fact, when I did this the testsuite uncovered an actual bug that was hidden because the tests were not executed properly...

**Comment by unt01d** [comment]
Had another look at this, and it turns out the namespace hack won't work here, since `exit` is a language construct and not a function.

So I've [submitted a better fix](https://github.com/simplesamlphp/simplesamlphp/pull/864) which has require some modification to the Cardinality auth process filter classes.

The basic intention here is to assert the redirect using a mock object.  Unfortunately we couldn't mock the HTTP helper in its current form because it uses static methods (which is why static methods are bad).  So what I've done is create a wrapper class for the static methods and used this as the basis for the mock instead.
