### ISSUE TITLE
is it Support SOAP logout?

### ISSUE THREAD

**Issue by stanleyyuenyiu** [simplesamlphp/simplesamlphp#876]
in this file -> simplesamlphp/modules/saml/www/sp/metadata.php 

if ($binding == SAML2_Const::BINDING_SOAP && !($store instanceof SimpleSAML_Store_SQL)) {
        // we cannot properly support SOAP logout
        continue;
    }

it mean it will not support soap logout? 

i have 2 sp demo with mysql and i modify the binding to be only SOAP, when i init a logout request from Idp, it will fail

**Comment by tvdijen** [comment]
This is an issue-tracker, not a support forum..
Please use the mailinglist and add debug-information that we can use to help you, like error messages..
