### ISSUE TITLE
Error using configuration template in 1.16.0-rc1

### ISSUE THREAD

**Issue by dsubires** [simplesamlphp/simplesamlphp#881]
Using the configuration template (config-templates / config.php) of version 1.16.0-rc1 the application gives the following error:

SimpleSAML_Error_Error: UNHANDLEDEXCEPTION
Backtrace:
1 www/_include.php:17 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: Exception: /var/www/simplesamlphp/config/config.php: The option 'proxy.auth' is not a valid string value.
Backtrace:
2 lib/SimpleSAML/Configuration.php:714 (SimpleSAML_Configuration::getString)
1 modules/core/www/frontpage_config.php:70 (require)
0 www/module.php:135 (N/A)

Maybe it would be good to change false by null in the template. Line 354. Thanks for your work.

**Comment by jaimeperez** [comment]
Hi @dsubires!

Thanks a lot for testing the release candidate and giving us feedback! That's really valuable!

Fortunately, Thijs noticed (and fixed) this one already 😄 in 8b26a9f.
