### ISSUE TITLE
Encryption Key must be .pem?

### ISSUE THREAD

**Issue by toddkc** [simplesamlphp/simplesamlphp#883]
I am using simplesamlphp as the IdP in an IdP-initiated sso setup.  I'm having some issues figuring out the certificates and assertion encryption.  I have a public and private signing certificate, but for the encryption I only have a public key (.der).  The SP has the private key.  I have no access to that, and cannot use a different public key.  I've tried various combinations of:

`'assertion.encryption' => true`

and

`'certificate' => 'encryption_cert.der'`

inside of `saml20-sp-remote` and `saml20-idp-hosted`, and every time I get an error about 'could not find a .pem certificate.'  Isn't that the point of encryption?  That I am encrypting with a public key, and don't have access to the private key?

**Comment by trscavo** [comment]
On Thu, Jul 5, 2018 at 3:33 PM, Todd Belcher <notifications@github.com> wrote:
> I am using simplesamlphp as the IdP in an IdP-initiated sso setup. I'm
> having some issues figuring out the certificates and assertion encryption. I
> have a public and private signing certificate, but for the encryption I only
> have a public key (.der). The SP has the private key.

Yup, that's the way it's supposed to be.

> I have no access to that

I hope not! :-)

> Isn't the point of encryption? That I am encrypting with a public key, and
> don't have access to the private key?

That is correct, yes.

Tom

**Comment by toddkc** [comment]
Really?  My question is:

Why do I get an error stating I need a private key (.pem) to encrypt my assertion, when all I have (as I should) is a public key (.der).  Why won't the assertion encrypt using a non-pem key?

I appreciate the help, but seriously?  That was your takeaway from what I wrote?  Clearly I am missing something about these certificate formats, but I know what public and private keys are for...

**Comment by tvdijen** [comment]
Hi @toddkc!  Really, your question should have gone to the [mailinglist](https://simplesamlphp.org/lists) instead.. This is an issue-tracker, not a support forum.

**Comment by toddkc** [comment]
That's fair, and also why I closed the ticket.  I wasn't sure if this was an issue or just lack of knowledge, which obviously it was.  Thanks!

**Comment by tvdijen** [comment]
No big deal!
