### ISSUE TITLE
Prefer HTTP-Redirect binding for authnRequest if supported by IDP

### ISSUE THREAD

**Issue by peter-** [simplesamlphp/simplesamlphp#885]
In accordance with saml2int (both old and new) SimpleSAMLphp should prefer use of the `HTTP-Redirect` protocol binding for transmission of SAML 2. 0 authentication requests to the IDP over any other binding, as long as the IDP announces support for that.  
Only if that's not supported by the IDP should SSP fall back to using the "first" (current behaviour) or any other of the unordered set of SSO endpoints published by the IDP.

Discussion context and saml2int references:
https://groups.google.com/forum/#!topic/simplesamlphp/-tmdgsxZhgo

**Comment by thijskh** [comment]
This has been fixed by @jaimeperez in 396187164b9afb8e2e8ec3c7bd76ab31e5c39b62.
