### ISSUE TITLE
BUG: Fix it ASAP class module/saml/lib/IdP/SAML2.php line 58

### ISSUE THREAD

**Issue by stanleyyuenyiu** [simplesamlphp/simplesamlphp#888]
in class module/saml/lib/IdP/SAML2.php

line 56 -63

`$association = array(
            'id'                => 'saml:'.$spEntityId,
            'Handler'           => '\SimpleSAML\Modulesaml\IdP\SAML2',
            'Expires'           => $assertion->getSessionNotOnOrAfter(),
            'saml:entityID'     => $spEntityId,
            'saml:NameID'       => $state['saml:idp:NameID'],
            'saml:SessionIndex' => $assertion->getSessionIndex(),
        );`

there is no such class "Modulesaml", it should be "Module\saml"

it make the single signout is not working any more

lucky i have the previous version to diff

please fix it asap

**Comment by jaimeperez** [comment]
Thanks for letting us know @stanleyyuenyiu!
