### ISSUE TITLE
initMDSPdo returns "Failed to initialized metadata database" even though it was successful (MySQL)

### ISSUE THREAD

**Issue by BAGELreflex** [simplesamlphp/simplesamlphp#889]
The `initDatabase()` function of `lib/SimpleSAML/Metadata/MetaDataStorageHandlerPdo.php` assumes that the `CREATE TABLE IF NOT EXISTS ...` statement will return a positive integer for the # of rows affected when the table is created. MySQL does not return a positive number for rows affected for the `CREATE TABLE` statement. You can see examples of this at the following links:
* MySQL 5.6: https://dev.mysql.com/doc/refman/5.6/en/create-table-select.html
* MySQL 5.7/8.0: https://dev.mysql.com/doc/refman/5.7/en/create-table-select.html#comment-listing

```
[centos@auth simplesamlphp]$ php bin/initMDSPdo.php
/Initializing Metadata Database...
Jul 19 18:26:48 simplesamlphp WARNING [CL7add6a36] The configuration file '/var/www/html/simplesamlphp/config/config.php' generates output. Please review your configuration.
Failed to initialize metadata database.
```

The above prints failed, however all tables were created as expected:
```
[centos@auth simplesamlphp]$ mysql -u USERNAME -p -h HOST -D AuthSaml -e "SHOW TABLES"
Enter password:
+--------------------+
| Tables_in_AuthSaml |
+--------------------+
| adfs_idp_hosted    |
| adfs_sp_remote     |
| saml20_idp_hosted  |
| saml20_idp_remote  |
| saml20_sp_remote   |
| shib13_idp_hosted  |
| shib13_idp_remote  |
| shib13_sp_hosted   |
| shib13_sp_remote   |
| wsfed_idp_remote   |
| wsfed_sp_hosted    |
+--------------------+
```

This is not a critical issue, but the error is misleading.

**Comment by tvdijen** [comment]
Thanks for reporting this @BAGELreflex !
I think it should be fixed in https://github.com/simplesamlphp/simplesamlphp/commit/2f6f022cd713699060253a9883dcf229e9bfcedb.. Could you verify for me?

**Comment by tvdijen** [comment]
Closing after receiving positive feedback that the fix is working
