### ISSUE TITLE
\SimpleSAML\Utils\XML::checkSAMLMessage does not find the schemas

### ISSUE THREAD

**Issue by simevo** [simplesamlphp/simplesamlphp#894]
I get:
```
.../vendor/simplesamlphp/simplesamlphp/schemasPHP Warning:  DOMDocument::schemaValidate(): Invalid Schema in .../vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/XML.php on line 438
Jul 25 19:20:35 simplesamlphp WARNING [CL77866641] Schema validation failed on XML string:
level=1,code=1549,line=0,col=0,msg=failed to load external entity ".../vendor/simplesamlphp/simplesamlphp/schemas./saml-schema-metadata-2.0.xsd"
level=2,code=1757,line=0,col=0,msg=Failed to locate the main schema resource at '.../vendor/simplesamlphp/simplesamlphp/schemas./saml-schema-metadata-2.0.xsd'.
```
and indeed https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Utils/XML.php#L435 is appending `./` to `$config->resolvePath('schemas')` but latter returns a "path [that] will never end with a '/'." (https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/Configuration.php#L559)

**Comment by thijskh** [comment]
So removing the `.` indeed fixes the problem?

**Comment by simevo** [comment]
well, at least it gets past that; still fails due to:
```
PHP Warning:  DOMDocument::schemaValidate(http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd): failed to open stream: HTTP request failed!  in .../vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/XML.php on line 438
PHP Warning:  DOMDocument::schemaValidate(http://www.w3.org/TR/2002/REC-xmlenc-core-20021210/xenc-schema.xsd): failed to open stream: HTTP request failed!  in .../vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/XML.php on line 438
PHP Warning:  DOMDocument::schemaValidate(http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd): failed to open stream: HTTP request failed!  in .../vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/XML.php on line 438
PHP Warning:  DOMDocument::schemaValidate(http://www.w3.org/TR/2002/REC-xmlenc-core-20021210/xenc-schema.xsd): failed to open stream: HTTP request failed!  in .../vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/Utils/XML.php on line 438
...
```

**Comment by tvdijen** [comment]
Removing the `.` makes sense.

Are you using any hardening-mechanisms like SElinux that may prevent PHP from downloading those schema-files?

**Comment by simevo** [comment]
no, I don't have `selinux-basics` installed

**Comment by tvdijen** [comment]
What does the command `getenforce` tell you?

**Comment by simevo** [comment]
"command not found"

**Comment by tvdijen** [comment]
I think it's just timing out...
I did a `curl http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd` locally and it took forever to load

Anyway, I have fixed the `.` issue on master

**Comment by thijskh** [comment]
This would defintely something that could be covered by a unit test...

**Comment by pmeulen** [comment]
Regarding your curl check above. Just to be sure: SSP must never download the XSD schema files (i.e. load external entities), doing this is a security issue and introduces a completely unnecessary dependency on the availability of someone else's server. The W3C has deliberately slowed down downloading schema files from their servers to discourage this practice. Use locally stored schema's instead. Loading external entities should already be is disabled in libxml. If you see external entities being resolved, this is something to be investigated.

**Comment by tvdijen** [comment]
The schemas that were externally referenced have been included in the repository now, effectively closing this issue.

@thijskh What exactly did you want to cover in a unit test?
