### ISSUE TITLE
Quality control of the Google Apps Installation instructions (was #177)

### ISSUE THREAD

**Issue by sspghost** [simplesamlphp/simplesamlphp#9]
_From [andreass...@gmail.com](https://code.google.com/u/102889613336421617108/) on July 18, 2009 10:17:19_

Document was updated on 2009-07-18, but Andreas is leaving on vacation and do not have time 
for proper testing of the guide.

_Original issue: http://code.google.com/p/simplesamlphp/issues/detail?id=177_

**Comment by tvdijen** [comment]
I think this one can be closed... The docs were modified to better reflect entityId configuration and the last part of the issue is more or less a support question dating back from 2009..

**Comment by thijskh** [comment]
I have also updated them recently indeed. If any issues remain they should be filed specifically.
