### ISSUE TITLE
Infinite Redirection

### ISSUE THREAD

**Issue by jaydp** [simplesamlphp/simplesamlphp#900]
For more information, please check below link:
https://stackoverflow.com/questions/51588230/simplesamlphp-infinite-redirection

When I debug this then got "simplesamlphp WARNING [81d1339efe] Could not load state specified by InResponseTo: NOSTATE Processing response as unsolicited." error to log file.

**Comment by jaimeperez** [comment]
Hi @iefrati,

This is an issue tracker, not a support forum. It'd be better if you ask for support in our [mailing list](http://groups.google.com/group/simplesamlphp).

In any case, your problem looks like a misconfiguration. Check your session cookie configuration in the SP. It's clearly saying it cannot load the state, meaning the session is lost.
