### ISSUE TITLE
a request: NameIDFormat as array

### ISSUE THREAD

**Issue by id812510** [simplesamlphp/simplesamlphp#91]
With a reference to [this conversation](https://groups.google.com/d/msg/simplesamlphp/LNVd_ZhuBIk/tlrZ2m0RfbwJ) I'd like to ask for a change of `NameIDFormat` to an array.

This would allow me to set something like

```
'NameIDFormat' => array(
   'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent',
   'urn:oasis:names:tc:SAML:2.0:nameid-format:transient'
  ),
```

in `saml20-idp-hosted.php` thus satisfying more easily Cesnet NREN EduID's vicious adminstrator.

**Comment by tvdijen** [comment]
Was fixed&merged
