### ISSUE TITLE
SSL behind load balance issue

### ISSUE THREAD

**Issue by stanleyyuenyiu** [simplesamlphp/simplesamlphp#910]
the code in SimpleSAML\Utils\HTTP;

getServerHTTPS is too simple, it should check the proxy like HTTP_X_FORWARDED_PROTO

please reference to OneLogin
https://github.com/onelogin/php-saml

i have already modify it by myself

/**
     * Retrieve HTTPS status from $_SERVER environment variables.
     *
     * @return boolean True if the request was performed through HTTPS, false otherwise.
     *
     * @author Olav Morken, UNINETT AS <olav.morken@uninett.no>
     */
    public static function getServerHTTPS()
    {
        if (!array_key_exists('HTTPS', $_SERVER)) {
            // not an https-request
            return false;
        }

        if ($_SERVER['HTTPS'] === 'off') {
            // IIS with HTTPS off
            return false;
        }

        // otherwise, HTTPS will be non-empty
        return !empty($_SERVER['HTTPS']);
    }

**Comment by tvdijen** [comment]
Please read the following discussions:
https://github.com/simplesamlphp/simplesamlphp/issues/343
https://github.com/simplesamlphp/simplesamlphp/pull/376
https://github.com/simplesamlphp/simplesamlphp/pull/816
https://github.com/simplesamlphp/simplesamlphp/pull/491

The `HTTP_X_FORWARDED-*` headers are unsafe and should not be used.
You should properly set the `baseurlpath` in `config.php` to make SimpleSAMLphp aware it is behind a load balancer
