### ISSUE TITLE
Cannot provide default MultiAuth source from SP to IdP using method in documentation

### ISSUE THREAD

**Issue by BAGELreflex** [simplesamlphp/simplesamlphp#912]
Per the docs located here: https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/multiauth/docs/multiauth.md

The documentation outlines two methods of defaulting the source based on the SP. The first is to pass a `GET` parameter of `?source=myPreferredSource` "to the calling URL, when accessing a service". As best I can tell, this means redirecting to a URL of this format:
```
https://mysite.com/auth/idp/saml2/idp/SSOService.php?source=myPreferredSource&SAMLRequest=…
```
when calling `$auth->login()` or `$auth->requireAuth()`.

There has been discussion about this topic: https://groups.google.com/forum/#!topic/simplesamlphp/9QAJXhZ8b1o
In this discussion, one suggestion was to modify core code, but that is just not acceptable for an enterprise-level environment, as it introduces much more work for future upgrades. The route they finally took was leveraging the `ReturnTo` parameter, and parsing that value in a custom `mymodule/themes/multiauth/selectsource.php`, then setting `$source` to the parsed value.

The second suggestion is to use a non-standard `multiauth:preselect` parameter to the `login()` or `requireAuth()` functions of `\SimpleSAML\Auth\Simple`. This seemed the most appropriate method for my use-case, however after trying to implement it, I was unsuccessful. After further review, I have found that this non-standard key is not passed on from the SP to the IdP, unless the SP and IdP are running on the same server, using the same SSP installation. This is because the `multiauth:preselect` is saved to the state on the SP, and is not passed as part of the `\SAML2\AuthnRequest`. See https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Auth/Source/SP.php#L319. The state is saved here https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/Auth/Source/SP.php#L284 but that will only be available to the SP. When the IdP receives the request, and the state is loaded here https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/multiauth/www/selectsource.php#L18 the `multiauth:preselect` would never be available, unless the IdP and the SP are on the same server.

So, how do we make this work?

After an hour or two of tracing through the code, I have finally figured out that I can simply tack on `?source=myPreferredSource` to the **Location** index of the **SingleSignOnService** inside `metadata/saml20-idp-remote.php`.

```php
$metadata['https://mysite.com/auth/saml2/idp/metadata.php'] = array (
  'metadata-set' => 'saml20-idp-remote',
  'entityid' => 'https://mysite.com/auth/saml2/idp/metadata.php',
  'SingleSignOnService' =>
  array (
    0 =>
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://mysite.com/auth/saml2/idp/SSOService.php?source=myPreferredSource',
    ),
  ),
  'SingleLogoutService' =>
  array (
    0 =>
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://mysite.com/auth/saml2/idp/SingleLogoutService.php',
    ),
  ),
  'certData' => 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'NameIDFormat' => 'urn:oasis:names:tc:SAML:2.0:nameid-format:transient',
  'contacts' =>
  array (
    0 =>
    array (
      'emailAddress' => 'it@mysite.com',
      'contactType' => 'technical',
      'givenName' => 'Information Technology Department',
    ),
  ),
);
```

This solution requires no code changes to core code, but it does limit the ability to automate updates of metadata. We use database storage to store the metadata, with a worker that runs every so often to query for metadata from the IdP and update it within our SP. We can build the logic of tacking on the `?source=myPreferredSource` into our synchronization, but that is more of a workaround than a solution.

Can anyone provide me a more appropriate method getting the `?source=myPreferredSource` onto the SSOService request without having to modify the IdP's metadata at the SP? I can alter the `SingleSignOnService` at the IdP level too, which would fix the issue of having to add the source during my sync, however this is not transferrable across multiple SP. My SP1 needs to default to myPreferredSource, while my SP2 needs to default to myOtherPreferredSource. So doing this in the IdP metadata is not a verbose enough solution.

If no better solution can be provided, then the documentation should at least be updated with some of the above information, so others don't have to go through the deep dive I did to get this working.

**Comment by tvdijen** [comment]
> [...] but this works only if you don't have redirections during the authentication process.
I don't see how much clearer it can be... What you want is not possible without core code-alteration.

**Comment by Lasering** [comment]
This use case is really useful. It is akin to [5.7 Requesting a specific authentication method](https://simplesamlphp.org/docs/stable/saml:sp#section_5_7). Ideally the same mechanism could be used.

**Comment by jaimeperez** [comment]
Hi @Lasering,

If I understand correctly, the requested functionality here is to select a specific auth source on an IdP using multiauth, from an SP. That's simply not possible, as the SAML standard doesn't provide any means to do that.

However, it could be possible to implement this in multiauth, by assigning authentication context class references to each configured method, and then offering only those covering the requested `AuthnContextClassRef` (or just proceeding with one if there is only one that fits). In any case, this would be a new feature in multiauth that could be useful indeed. Contributions are always welcome!

**Comment by Lasering** [comment]
Maybe I can contribute. Looking at the code seems the problem comes down to having access to the `AuthnContextClassRef` from the SP either:

1. In [function authenticate](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/multiauth/lib/Auth/Source/MultiAuth.php#L140).
2. In [www/selectsouce.php](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/multiauth/www/selectsource.php)

If you can guide me regarding this problem, I think I can do the rest of the necessary implementation.

**Comment by Lasering** [comment]
@jaimeperez inside the authenticate I should have access to `$state` will it contain `$state['saml:AuthnContextClassRef']` or similar?

In selectsource the state is being fetched with:
```php
$state = \SimpleSAML\Auth\State::loadState($authStateId, \SimpleSAML\Module\multiauth\Auth\Source\MultiAuth::STAGEID);
```
Is is the same state? Would that grant me access to the AuthnContextClassRef?
