### ISSUE TITLE
Add support for SQL PDO driver options

### ISSUE THREAD

**Issue by sdemi** [simplesamlphp/simplesamlphp#913]
I am implementing simplesamlphp with Drupal hosted on Azure.

After setting 'store.type' => 'sql' I started getting the following error:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [9002] SSL connection is required. Please specify SSL options and retry. in C:\xxx\simplesamlphp\lib\SimpleSAML\Store\SQL.php:60 Stack trace: #0 C:\xxx\simplesamlphp\lib\SimpleSAML\Store\SQL.php(60): PDO->__construct('mysql:host=xxx...', 'xxx...', 'xxx...', NULL) #1 C:\xxx\simplesamlphp\lib\SimpleSAML\Store.php(52): SimpleSAML\Store\SQL->__construct() #2 C:\xxx\simplesamlphp\lib\SimpleSAML\SessionHandler.php(122): SimpleSAML\Store::getInstance() #3 C:\xxx\simplesamlphp\lib\SimpleSAML\SessionHandler.php(41): SimpleSAML\SessionHandler::createSessionHandler() #4 C:\xxx\simplesamlphp\lib\SimpleSAML\Session.php(155): SimpleSAML\SessionHandler::getSessionHandler() #5 C:\xxx\simplesamlphp\lib\SimpleSAML\Session.php(410): SimpleSAML_Session->__construct(true) #6 C:\xxx\simplesamlphp\lib\SimpleSAML\Session.php(262): SimpleSAML_Session::useTransientSession() #7 C:\xxx\simplesa in C:\xxx\simplesamlphp\lib\SimpleSAML\Store\SQL.php on line 60`

This error is happening because Azure MySQL database requires an SSL certificate to connect to.

Usually, PHP uses the following syntax if you need to provide an SSL cert:

`<?php
$pdo = new PDO(
    'mysql:host=hostname;dbname=ssldb',
    'username',
    'password',
    array(
        PDO::MYSQL_ATTR_SSL_KEY    =>'/path/to/client-key.pem',
        PDO::MYSQL_ATTR_SSL_CERT=>'/path/to/client-cert.pem',
        PDO::MYSQL_ATTR_SSL_CA    =>'/path/to/ca-cert.pem'
    )
);
?>`

However in \simplesamlphp\lib\SimpleSAML\Store\SQL.php on line 60 the code is missing the option to add these additional driver options. See:

`$this->pdo = new \PDO($dsn, $username, $password);`

I had to manually hardcode the driver options like this:

`
$driver_options = array(\PDO::MYSQL_ATTR_SSL_CERT => '/xxx.crt.pem');
$this->pdo = new \PDO($dsn, $username, $password, $driver_options);
`

After this change, the db connection worked.

My recommendation is to add 'store.sql.driver_options' so that users are able to add it through the config if they need to.

**Comment by tvdijen** [comment]
Hi @sdemi !
This issue has already been addressed in https://github.com/simplesamlphp/simplesamlphp/pull/637 and the fix will be part of the new 1.16 release.
