### ISSUE TITLE
[rubber ducking] SimpleSAML_Error_Exception: Error 2 - PDOStatement::execute(): SSL operation failed with code 1. OpenSSL  Error messages:#012error:0906D06C:PEM routines:PEM_read_bio:no start line#012error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by ElijahLynn** [simplesamlphp/simplesamlphp#917]
Rubber ducking this error here as we are seeing while updating to a new IDP. 

> SimpleSAML_Error_Exception: Error 2 - PDOStatement::execute(): SSL operation failed with code 1. OpenSSL
 Error messages:#012error:0906D06C:PEM routines:PEM_read_bio:no start line#012error:0906D06C:PEM routines:PEM_read_bio:no start line

**Comment by ElijahLynn** [comment]
very similar issue, going through workarounds now: https://bugs.php.net/bug.php?id=69524

**Comment by ElijahLynn** [comment]
K, issue appears to be because of the above bug. Adding 

```
 $query = $this->pdo->prepare($query);
 while ($msg = openssl_error_string()) {};
 $query->execute($params);
```
to `/lib/SimpleSAML/Store/SQL.php253` (version 1.12) does get our Saml working again. I suspect it may be the bug OR maybe an issue with a new certificate we are using.

**Comment by tvdijen** [comment]
My concern with the proposed solution is that it also discards errors that are legit.
There's also multiple similar cases of running `prepare` followed by `execute`, so we have to fix those as well, not just the mentioned one..

And please @ElijahLynn, upgrade your SimpleSAMLphp!

**Comment by ElijahLynn** [comment]
Agreed, this is the first step of "get it working, get it right, get it fast". I realize there is a bug in PHP but haven't yet figured out why it didn't happen before this migration to a new SAML endpoint. 

Upgrading is on the roadmap, just didn't want to mix it with this migration. We were wondering if the OpenSSL error stack is popped in more locations in the new version, it has been refactored so I wasn't able to easily see.

**Comment by tvdijen** [comment]
Changes since 1.12 are just minor, so I expect 1.16 to behave exactly the same.
If you would be able to confirm this, we can perhaps fix this in a 1.16.1 bugfix-release.

**Comment by thijskh** [comment]
I'm not very charmed with adding workarounds to PHP bugs in our code; basically then every software project needs to add the same workarounds. It has been fixed in PHP 7.1, so people experiencing this can upgrade to 7.1.

**Comment by tvdijen** [comment]
Could an abstraction layer like symfony/dbal perhaps help us out here?

**Comment by thijskh** [comment]
I don't think it's SimpleSAML's place to work around generic PHP problems not directly related to what SimpleSAML does. Might be structurally fixed in database abstractions like dbal pdo etc.
