### ISSUE TITLE
Support Twig 2

### ISSUE THREAD

**Issue by ofriedrich** [simplesamlphp/simplesamlphp#918]
It would be great if simpleSAMLphp supports not only twig 1 but also twig 2.

If you want to use this library in projects that only supports twig 2, you cannot use simpleSAMLphp anymore.

https://github.com/simplesamlphp/simplesamlphp/blob/e7ed8c4f1fd2ee9384b832f5a37b533d76f81c06/composer.json#L42

**Comment by tvdijen** [comment]
Duplicate: #753
