### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function SimpleSAML\openssl_random_pseudo_bytes() 

### ISSUE THREAD

**Issue by jpichlerCirrus** [simplesamlphp/simplesamlphp#920]
Doing a new install on my localhost / https / windows.  I think this is due to openssl not loading correctly...in my phpinfo() on https I see this:

OpenSSL support | disabled (install ext/openssl)

So I assume somehow I need to get this enabled?  From php command line (php -m) can see that it is there, but somehow I must have to configure it in apache?  Help is appreciated!!!

**Comment by thijskh** [comment]
This is a question about configuring PHP on Windows, not about simpleSAMLphp and this is an issue tracker, not a support forum. Likely Google can help you find useful resources.
