### ISSUE TITLE
Add check for REDIRECT_SIMPLESAMLPHP_CONFIG_DIR

### ISSUE THREAD

**Issue by jpegram2** [simplesamlphp/simplesamlphp#921]
Any chance we could get a change to lib/SimpleSAML/Utils/Config.php line 71
from this:
`$configDirEnv = getenv('SIMPLESAMLPHP_CONFIG_DIR');`
to this: 
`$configDirEnv = (false !== getenv('SIMPLESAMLPHP_CONFIG_DIR')) ? getenv('SIMPLESAMLPHP_CONFIG_DIR') : getenv('REDIRECT_SIMPLESAMLPHP_CONFIG_DIR');`

The use case is when you don't have the ability to set environment variables at the server level and you set SIMPLESAMLPHP_CONFIG_DIR in an .htaccess, if php is running as a CGI wrapper then the environment variable is changed to be prefixed with REDIRECT_ due to internal redirect handling which prevents symlinks from working. The simple fall back to check for the REDIRECT_ var solves the problem.

**Comment by thijskh** [comment]
This is already done in 1.16!
