### ISSUE TITLE
Consent form doesn't load in 1.16.0

### ISSUE THREAD

**Issue by dsieborger** [simplesamlphp/simplesamlphp#923]
After logging in to my SSP IdP, the consent page doesn't load:

`PHP Notice:  Undefined variable: srcName in /usr/ru/www/simplesamlphp-1.16.0/modules/consent/www/getconsent.php on line 113`
`PHP Notice:  Undefined variable: srcName in /usr/ru/www/simplesamlphp-1.16.0/modules/consent/www/getconsent.php on line 113`
`PHP Notice:  Undefined variable: dstName in /usr/ru/www/simplesamlphp-1.16.0/modules/consent/www/getconsent.php on line 114`
`PHP Notice:  Undefined variable: dstName in /usr/ru/www/simplesamlphp-1.16.0/modules/consent/www/getconsent.php on line 114`
`PHP Notice:  Undefined variable: translator in /usr/ru/www/simplesamlphp-1.16.0/modules/consent/www/getconsent.php on line 116`
`PHP Fatal error:  Call to a member function t() on null in /usr/ru/www/simplesamlphp-1.16.0/modules/consent/www/getconsent.php on line 116`

Looking at the code, it'd seem to me that the undefined variables ($srcName, $dstName, $translator) are intended to be defined in consent/templates/consentform.php but that is only require()ed later, when $t->show() is called (line 190 of getconsent.php).

Have I missed something or messed something up?

**Comment by sitya** [comment]
Same here.

**Comment by tvdijen** [comment]
Somehow I messed up my fix for an earlier mess-up 💩 :(

**Comment by tvdijen** [comment]
Fixed in abeba76

**Comment by sitya** [comment]
Thanks. 

Can you please update the tag to point your latest commit? https://github.com/simplesamlphp/simplesamlphp/commits/v1.16.0

**Comment by thijskh** [comment]
That would become a new tag, 1.16.1.

@sitya @dsieborger Can you confirm that the fix indeed works for you both?

**Comment by dsieborger** [comment]
Yes, I've applied the patch to my (otherwise unmodified 1.16.0) installation and it has fixed the problem.

Thanks very much for your quick response.

**Comment by thijskh** [comment]
v1.16.1 is now tagged/released
