### ISSUE TITLE
Add support for WebAuthn

### ISSUE THREAD

**Issue by kbabioch** [simplesamlphp/simplesamlphp#928]
Since this new API/standard allows for hardware based crypto to be used in the browser, backend support within simpleSAMLphp would be valuable feature to enhance the overall security of a typical deployment. This will probably require some special setup (in order to store the public keys), with simpleSAMLphp being the interface for that.

**Comment by tvdijen** [comment]
Contributions are welcome

**Comment by thijskh** [comment]
This could just be a module, right? See https://simplesamlphp.org/docs/stable/simplesamlphp-modules how to create one.

**Comment by kbabioch** [comment]
Yes, this can be implemented as module (I guess), but it needs some storage backend (SQL, LDAP, etc.) to store the public keys for each users.

**Comment by tvdijen** [comment]
WIP: https://github.com/mrvanes/authWebauthn

**Comment by tvdijen** [comment]
@kbabioch Perhaps you can give the module mentioned a try and let us know if it suits your needs?

**Comment by tvdijen** [comment]
OK, so I've been playing around with the mentioned module and while still a bit rough around the edges, I think it does exactly what you're looking for. Therefore closing this issue

**Comment by jaimeperez** [comment]
Hi @kbabioch,

JFYI, we've got a contribution for a new webauthn/Fido2 module, which we've been working on lately. It's still work in progress as well, but much more complete than the one Tim was referrering to previously.
