### ISSUE TITLE
Documentation needs to include session cleanup() calls and comments explaining the usage

### ISSUE THREAD

**Issue by sirisian** [simplesamlphp/simplesamlphp#932]
I ran into this "simple" mistake and saw a lot of other people did also when using $_SESSION on the SP. A simple example:

```php
$auth = new \SimpleSAML\Auth\Simple($authSource);
$auth->isAuthenticated(); // Replaces our session
// $_SESSION['myvalue'] = 10; // Whoops, this is transparently saved to the SimpleSAMLphp session
$session = SimpleSAML_Session::getSessionFromRequest();
$session->cleanup();
// Save to my session
$_SESSION['myvalue'] = 10;
```

The documentation located: https://simplesamlphp.org/docs/stable/simplesamlphp-sp-api specifically should include calls to the session cleanup with a comment explaining that you must revert to your own session if you intend to modify your $_SESSION members.

**Comment by thijskh** [comment]
Thanks, the source for that file is here: https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-sp-api.md
Would be great if you could propose a pull request to update the documentation.

**Comment by sirisian** [comment]
I'm not 100% confident with that PR, but I believe those are the only functions that replace the current session. Someone more familiar with the codebase would know for sure. It might be useful to specifically state the functions that have that behavior. In any case just adding that call in the documentation like I did with a note should prevent people from having the same bug.

**Comment by tvdijen** [comment]
I've created the PR because I think it's valuable docs.. But it needs work to get it up to today's standards (mostly the namespaces).. @sirisian could you help us out here by updating your branch?
