### ISSUE TITLE
broken in 1.16.1: oauth consumer sends 'resource' instead of array to HTTP::fetch

### ISSUE THREAD

**Issue by pradtke** [simplesamlphp/simplesamlphp#933]
The OAuth consumer class was made proxy-aware in 249e13128bee6208535ea634bc9b4d415ff4c575 however in getUserInfo() in the method converts the fetch options into a resource prior to sending to HTTP::fetch. This results in two things:
1. The incorrect options get sent to the OAuth endpoint. For linkedin, at least, this means you don't get any user attributes back.
2. You can warning: 
`PHP Warning:  stream_context_create() expects parameter 1 to be array, resource given in /opt/cirrus/bbom/ssp-soc/lib/SimpleSAML/Utils/HTTP.php`

I'll submit a quick PR against master, however this should also make it into an ssp 1.16.2 release

**Comment by pradtke** [comment]
In PR #934

**Comment by tvdijen** [comment]
PR was merged
