### ISSUE TITLE
Unclear deprecation of userid.attribute

### ISSUE THREAD

**Issue by peter-** [simplesamlphp/simplesamlphp#936]
As mentioned in [recent](https://groups.google.com/forum/#!topic/simplesamlphp/HQqm8RejFe0) [discussions](https://groups.google.com/d/msg/simplesamlphp/pVnzRJUBkOY/PAem1aP-FgAJ), some features require the use of the `userid.attribute` option, e.g. generating persistent NameIDs when not using [NameID generation filters](https://simplesamlphp.org/docs/stable/saml:nameid) (e.g. if persistent NameIDs are undesired, cf. #935) or [consent](https://simplesamlphp.org/docs/development/consent:consent#section_1). Setting this option in SSP 1.16.1 logs a deprecation message at warning level:

```
WARNING The 'userid.attribute' option has been deprecated.
```

It's unclear to me what should be used instead, so the warning does not help me to prepare for changes coming in 2.0.

Other log messages (such as the one about failure to generate a persistent NameID) still refer to this option:

```
ERROR Unable to generate NameID. Check the userid.attribute option.
```

Looking at [that code](https://github.com/simplesamlphp/simplesamlphp/blob/master/modules/saml/lib/IdP/SAML2.php#L704) I see use of another option `simplesaml.nameidattribute`, though when searching for that I only see this documented in the [Google Apps](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-googleapps.md) and [sp-remote](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-reference-sp-remote.md) docs, but not also for IDPs (though it's also being used for IDPs).

Is that what should be used instead? If so it should be documented in idp-hosted.

**Comment by tvdijen** [comment]
https://github.com/simplesamlphp/simplesamlphp/issues/3

**Comment by peter-** [comment]
Ah, I missed that. Thanks.

**Comment by tvdijen** [comment]
@thijskh : the desired alternative as discussed in #3 is to basically move the metadata-global `userid.attribute` to the individual authproc-filters that use it, which shouldn't be too hard to do...
Let's put our efforts there and keep the deprecation notice in place for the global setting.

**Comment by thijskh** [comment]
We log that on every login so systems using it get a lot of these warnings. It should be clear and evident for them what to do to remove the warning.

At least in 1.16 it's not per definition possible to not use this setting, and your logs will be full of warnings regardless. I'd consider to remove the warning there at least. And for master goes, great if it is fixed the proper way, but who knows when exactly that will happen? Why not just comment the warning out till we have all ingredients in place?

**Comment by jaimeperez** [comment]
@thijskh, would it be reasonable for you to change the logging level of that warning from *warning* to *debug*?

**Comment by thijskh** [comment]
This has been done in 46cb12c8866da4785ff9b29b495621b815ce5ba0
