### ISSUE TITLE
Add modules/*/enable to .gitignore

### ISSUE THREAD

**Issue by drjayvee** [simplesamlphp/simplesamlphp#943]
I followed the documentation for [automated metadata management](https://simplesamlphp.org/docs/stable/simplesamlphp-automated_metadata) and ended up with two untracked files:
```
modules/cron/enable
modules/metarefresh/enable
```

Should these be added to .gitignore? I'd be happy to create a PR for this ;)

**Comment by thijskh** [comment]
yes please!

**Comment by drjayvee** [comment]
This was actually already committed to master by Clint Armstrong in e51829f169 :)

**Comment by thijskh** [comment]
I already thought I'd seen this before! Was committed after 1.16 was branched off. Have cherry-picked them to 1.16 so will be part of a next release for that branch.
