### ISSUE TITLE
newUI: Twigification of modules/core/templates/logout-iframe.php

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#944]
This old template needs Twigification.. It's the last one to go and it's a leftover from #717!

**Comment by tvdijen** [comment]
@jaimeperez on the discussion board you've mentioned that you've already Twigified this file for Feide.. Could you look it up?

**Comment by jaimeperez** [comment]
Sure! Do you want to see how it was done, or do you want me to twigify it myself?

**Comment by tvdijen** [comment]
I can handle the twigification, I just think it would save me a lot of work if I have an example

**Comment by jaimeperez** [comment]
Done! Check your email! 😉

**Comment by tvdijen** [comment]
Thanks, I have my homework for this weekend ;)

**Comment by thijskh** [comment]
@jaimeperez Did you have a chance to look into this? It's not really something in my comfort zone either.
