### ISSUE TITLE
newUI: old templates don't work together with i18n

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#945]
Old style templates do not work any more, since the new Twig-templates take precedence over the old ones and language.i18n.backend => 'SimpleSAMLphp' is therefore not doing what it's supposed to do.
See Jaime's comment on this issue here: #905 

@jaimeperez: you've mentioned a working fix for this, that was supposedly presented in a feature-branch.. The stage is yours ;)

**Comment by tvdijen** [comment]
#966

**Comment by thijskh** [comment]
Fixed in 0e4c83dd19d5baf7f4c67731f884502752f0090c on `experiment/routing`.
