### ISSUE TITLE
newUI: translation issues

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#948]
- NOSTATE errors are not translated properly
![43726604-e56c7e98-999f-11e8-9e46-301424214532 1](https://user-images.githubusercontent.com/841045/46558417-4da0fa80-c8ed-11e8-9c66-32d2ee0fcd61.png)

- Metadata not found are errors not translated properly
https://user-images.githubusercontent.com/841045/43832207-ee10efee-9b06-11e8-883a-d261d77aa6c6.png

This issue is probably bigger than the two mentions above...

**Comment by tvdijen** [comment]
I remember us talking about this in Valencia, but was this fixed eventually? @thijskh @jaimeperez

**Comment by jaimeperez** [comment]
I haven't really worked on this, not even tested. If, by any chance, it is already fixed, that was accidental 😄

**Comment by tvdijen** [comment]
I can confirm this is still an issue

**Comment by tvdijen** [comment]
Marked for 1.17 milestone since old UI is working perfectly

**Comment by tvdijen** [comment]
Mixing up old/new UI... All is fine
