### ISSUE TITLE
newUI: admin dashboard lack logoff-button

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#951]
There is no way to logoff from your admin dashboard.

**Comment by thijskh** [comment]
This is also not currently possible in the old ui. While it's a nice feature, not a blocker for 1.17 since not a regression.

**Comment by tvdijen** [comment]
Well, it;s possible when going to 'Test authentication sources' > 'admin', so it would only be a matter of integrating the logout-url on the header-template...
Without arguing your decision to remove the 1.17 milestone, shouldn't this just be a part of any UI nonetheless? And shouldn't we fix the lack of a logoff-link in a new UI if we're working on one?

**Comment by thijskh** [comment]
I'm not at all against the idea. It's just not something that should hold back anything because SSP has been without it for years.

**Comment by thijskh** [comment]
Indeed better to just fix it instead of discussing priorities :-)
