### ISSUE TITLE
core:idp-ssotime not removed on logout

### ISSUE THREAD

**Issue by dgersh** [simplesamlphp/simplesamlphp#962]
The issue is that on 
https://github.com/simplesamlphp/simplesamlphp/blob/master/lib/SimpleSAML/IdP.php#L488
the separator is a : (colon) whereas the other two places in the code which this item is referenced, including where it is added use ; (semicolon)

How can we reproduce the bug?
Log in, view session
Log out, view session if still present

Is it reproducible in other environments (for example, on different browsers or devices)?
Probably

How critical is this bug? Does it impact a large amount of users?
Likely, but unknown how critical

**Comment by tvdijen** [comment]
Thanks for reporting this @dgersh!
