### ISSUE TITLE
\SimpleSAML\Store\SQL use of CREATE INDEX

### ISSUE THREAD

**Issue by happydude** [simplesamlphp/simplesamlphp#963]
I have begun testing upgrading to simplesamlphp 1.16.2, we use the SQL store with MySQL. One challenge I ran into is the table updates use the CREATE INDEX command to add an index to the _expire column.  The problem was even though our db user had CREATE & ALTER permissions the CREATE INDEX command requires the system level INDEX permission.

I was able to workaround this but if the index was created as either part of the CREATE TABLE or used ALTER TABLE then the db/table level permission would be sufficient.

I am most familiar with MySQL, so I don't know if this limitation is an oddity of MySQL or how changing index creation would effect other database software.

For reference https://bugs.mysql.com/bug.php?id=59767

**Comment by happydude** [comment]
I agree, I just wanted to raise the question if it was feasible to create the index as part of the CREATE TABLE statement. 

I could not find a list of supported database servers for this project, but I did check into sqlite and postgresql and it doesn't appear that either support creating indexes in CREATE TABLE. 

Since this is a mysql limitation and I don't have a better solution to offer I'll close this issue.

**Comment by tvdijen** [comment]
I think we could create the index in the CREATE TABLE statement for new deployments... For migrations we cannot, because sqlite doesn't support ALTER on table-fields...  I'd like to keep this open because I want to investigate if an abstraction layer like symfony/dbal would help us here.. A future 2.0 release would be a time to squash the current migration code..

**Comment by tvdijen** [comment]
OK, just to summarize this one for myself..
Some research shows that the syntax with most support is the 'ALTER TABLE'-syntax.. This would solve the issue for MySQL, but would kill SQLite..
I have therefore come up with a patch that uses ALTER TABLE by default and CREATE INDEX for SQLite,.
I think that would cover all common use-cases..

@happydude would you be able to test if #1169 would fix your issue?

**Comment by happydude** [comment]
Looks good, tested upgrading from 1.15.4 to dev-master and letting dev-master make new tables on mysql.

Thanks!
