### ISSUE TITLE
AttributeMap can't overwrite an attribute

### ISSUE THREAD

**Issue by happydude** [simplesamlphp/simplesamlphp#970]
We use ldap as our auth source and among the attributes returned two of them are uid and uidNumber.  We have an edge case where a vendor is asking us to return the number stored in uidNumber as uid. AttributeMap up to 1.15.4 handled this without issue.  I think the fix in issue #828 is the cause of this difference.

Our workaround has been to map uid to something we will discard. A possible solution might be to check if the array key exists before copying attributes not in the map.

```php
<?php
class test {

    private $duplicate = false;

    private $map = array(
//        'uid' => 'testuid',
        'uidNumber' => 'uid',
    );

    public function process1_15_4(&$request)
    {
        assert('is_array($request)');
        assert('array_key_exists("Attributes", $request)');
        $attributes =& $request['Attributes'];
        foreach ($attributes as $name => $values) {
            if (array_key_exists($name, $this->map)) {
                if (!is_array($this->map[$name])) {
                    if (!$this->duplicate) {
                        unset($attributes[$name]);
                    }
                    $attributes[$this->map[$name]] = $values;
                } else {
                    foreach ($this->map[$name] as $to_map) {
                        $attributes[$to_map] = $values;
                    }
                    if (!$this->duplicate && !in_array($name, $this->map[$name], true)) {
                        unset($attributes[$name]);
                    }
                }
            }
        }
    }

    public function process1_16_2(&$request)
    {
        assert(is_array($request));
        assert(array_key_exists('Attributes', $request));

        $mapped_attributes = array();

        foreach ($request['Attributes'] as $name => $values) {
            if (array_key_exists($name, $this->map)) {
                if (!is_array($this->map[$name])) {
                    if ($this->duplicate) {
                        $mapped_attributes[$name] = $values;
                    }
                    $mapped_attributes[$this->map[$name]] = $values;
                } else {
                    foreach ($this->map[$name] as $to_map) {
                        $mapped_attributes[$to_map] = $values;
                    }
                    if ($this->duplicate && !in_array($name, $this->map[$name], true)) {
                        $mapped_attributes[$name] = $values;
                    }
                }
            } else {
                $mapped_attributes[$name] = $values;
            }
        }

        $request['Attributes'] = $mapped_attributes;
    }
}

$request = array(
    'Attributes' => [
        'uidNumber' =>
            array(
                0 => '123456',
            ),
        'uid' =>
            array(
                0 => 'jdavis',
            ),
    ]
);

$request2 = $request;

$t = new test();
$t->process1_15_4($request);
echo "1.15.4\n";
var_export($request);

$t->process1_16_2($request2);
echo "\n1.16.2 \n";
var_export($request2);
```

returns
```
1.15.4
array (
  'Attributes' => 
  array (
    'uid' => 
    array (
      0 => '123456',
    ),
  ),
)
1.16.2 
array (
  'Attributes' => 
  array (
    'uid' => 
    array (
      0 => 'jdavis',
    ),
  ),
)
```

**Comment by tvdijen** [comment]
I'm not sure AttributeMap was meant to replace existing attributes in the first place....
This filter lacks the '%replace' setting that some of them have...

**Comment by tvdijen** [comment]
@mschwager since you've wrote the 1.16-version of this authproc-filter, could you have a look at this?

**Comment by tvdijen** [comment]
Thanks a ton @mschwager for investigating this!
Since this is undocumented behaviour, we can go any way... I see similarities in that matter in https://github.com/simplesamlphp/simplesamlphp/issues/771 where we decided to break + document...

Consistency would have my preference here (option 1), but others may have different thoughts... It's on my radar for our November hackthon to discuss, but perhaps @thijskh or @jaimeperez have thoughts here

**Comment by thijskh** [comment]
I think I'd lean towards 2 because it keeps the authproc simpler, less config, just does what one expects a "map" function to do (that is, I think the general understanding of a "map" function is that it will not add to a list, but rather replace/deliver a new list with the results).

**Comment by thijskh** [comment]
There is already the option `%duplicate`. This seems to me the way to indicate that you do not want the values to be replaced but want to keep the originals.

I'm going for option 2: "Change AttributeMap to be consistent with its previous behavior, i.e. replace by default. Pros: code that used to depend on this behavior will continue to work."
Especially since the previous behaviour has been there for years and has been working fine for people for years.

**Comment by thijskh** [comment]
@mschwager  Would be great if you could prepare a fix for this including the necessary testcases!

**Comment by jaimeperez** [comment]
I'm closing this since I just merged a PR with a fix. Thanks for reporting @happydude!
