### ISSUE TITLE
How to customize multiauth

### ISSUE THREAD

**Issue by umardraz** [simplesamlphp/simplesamlphp#971]
I have successfully installed Simplesaml and also verified implementing and successfully integrate with my sites.

Here is my authsource configuration for multiauth

```

'example-multi' => array(
    'multiauth:MultiAuth',
    'sources' => array(
        'example-sql' => array(
            'text' => array(
                'en' => 'Log in with internal database'
            )
        ),
        'linkedin' => array(
            'text' => array(
                'en' => 'Log in with LinkedIn'
            )
        ),
        'facebook' => array(
            'text' => array(
                'en' => 'Log in with Facebook'
            )
        )
    ),
),

```

On the multiath login page three buttons are appear 

> Login in with internal database
> Login in with Linkedin
> Login in with Facebook
> 

Now I want this multiauth page should have username and password form of example-sql on the same page instead of I click on the first button. For this purpose I had modifed selectsource.php file and added a new form but that is not working.. Here is my code
```

<?php
$this->data['header'] = $this->t('{multiauth:multiauth:select_source_header}');
$this->includeAtTemplateBase('includes/header.php');
?>

<h2><?php echo $this->t('{multiauth:multiauth:select_source_header}'); ?></h2>
<p><?php echo $this->t('{multiauth:multiauth:select_source_text}'); ?></p>

<form action="<?php echo htmlentities($_SERVER['PHP_SELF']); ?>" method="get">
<input type="hidden" name="AuthState" value="<?php echo htmlspecialchars($this->data['authstate']); ?>" />
<ul>
<?php
foreach($this->data['sources'] as $source) {
        echo '<li class="' . htmlspecialchars($source['css_class']) . ' authsource">';
        if ($source['source'] === $this->data['preferred']) {
                $autofocus = ' autofocus="autofocus"';
        } else {
                $autofocus = '';
        }
        $name = 'src-' . base64_encode($source['source']);
        echo '<input type="submit" name="' . htmlspecialchars($name) . '"' . $autofocus . ' ' .
                'id="button-' . htmlspecialchars($source['source']) . '" ' .
                'value="' . htmlspecialchars($this->t($source['text'])) . '" />';
        echo '</li>';
}
?>
</ul>
</form>

<form action="?" method="post" name="f" class="form-horizontal">
<input id="username" name="username" <?php echo ($this->data['forceUsername']) ? 'disabled="disabled"' : ''; ?> placeholder="your email" class="form-control" required="true" value="" type="text" <?php if (!$this->data['forceUsername']) { echo 'tabindex="1"';} ?> value="<?php echo htmlspecialchars($this->data['username']); ?>">
<input id="password" name="password" placeholder="your password" class="form-control" required="true" value="" type="password">
<input type="hidden" name="AuthState" value="<?php echo htmlspecialchars($this->data['authstate']); ?>" />
</form>

<?php $this->includeAtTemplateBase('includes/footer.php');

```
Would you please help me how I can achieve this?

**Comment by tvdijen** [comment]
Hi @umardraz,

This is an issue tracker, not a support form.. Please refer to our [mailinglists](https://simplesamlphp.org/lists)

**Comment by tvdijen** [comment]
PS.:  You're posting your form to "?" which equals module.php/multiauth/selectsource.php.. I think you should post to module.php/core/loginuserpass.php

**Comment by umardraz** [comment]
Well I did that but no luck

**Comment by lhilton** [comment]
> Well I did that but no luck

Did you ever find a solve for this? I have the same spec.

**Comment by tvdijen** [comment]
@lhilton there have been similar discussions on our mailing lists.. Please check then out and use them as a support forum!

**Comment by lhilton** [comment]
I have only found unanswered deadends on this topic in the mailing list. If you have specific articles that actually present solutions, it would be helpful. Unfortunately this github issue is a very high result in Google searches, with many queries leading back here.

**Comment by tvdijen** [comment]
I have a hunch there is a solution for this, but to find it... @sgomez my memory may let me down, but did you have a similar use-case for this and worked out a solution?

**Comment by jaimeperez** [comment]
@tvdijen are you thinking about [this PR](https://github.com/simplesamlphp/simplesamlphp/pull/1005)?

**Comment by tvdijen** [comment]
Excellent @jaimeperez! Thanks!
