### ISSUE TITLE
docs: preprodwarning authproc-filter is undocumented

### ISSUE THREAD

**Issue by tvdijen** [simplesamlphp/simplesamlphp#973]
**Is your feature request related to a problem? Please describe.**
There's a link [here](https://github.com/simplesamlphp/simplesamlphp/blob/master/docs/simplesamlphp-authproc.md) to docs for the preprodwarning authproc-filter that has been pointing to limbo for the last 9 years (docs never existed).

**Describe the solution you'd like**
Add documentation for this authproc-filter

**Describe alternatives you've considered**
Remove the link from the authproc index page

**Comment by thijskh** [comment]
See #994
