### ISSUE TITLE
Autoloading classes from modules

### ISSUE THREAD

**Issue by markusu49** [simplesamlphp/simplesamlphp#977]
I'm trying to use a custom [twig function](https://twig.symfony.com/doc/1.x/advanced.html#functions) in my theme on simplesamlphp 1.16.2.

As it needs to be registered in the `Twig_Environment`, I identified a custom template controller (implementing `TemplateControllerInterface`) as the right place to do it. According to a comment in `SimpleSAML_XHTML_Template`, I need to set the `theme.controller` config option for this. I could not find any further documentation.

The problem is, my controller class is not found. As it is part of my custom module, it lives in `/modules/`, and the composer autoloader is limited to `/lib/SimpleSAML` according to `composer.json`. How can I make the custom controller available to simpleSAMLphp?

**Comment by tvdijen** [comment]
This is an issue-tracker, not a support form...

**Comment by markusu49** [comment]
I think this is an issue, I just tried to add my usecase... Let me say it more clearly:

I think we should have a way to autoload classes from modules. Maybe we could add /modules to the autoload part in composer.json?

**Comment by jaimeperez** [comment]
Hi @markusu49,

How did you install your module?

There is already an autoloader for modules, but you need to give appropriate names to your classes. You can either follow PSR-0 (old, deprecated): `sspmod_modulename_Foo_Bar` which would point to a class with that name in `SSPROOT/modules/modulename/lib/Foo/Bar.php`, or use PSR-4 to point to a class named `Bar` with the same path in the filesystem, and namespace `SimpleSAML\Module\modulename\Foo`.

**Comment by markusu49** [comment]
Thank you @jaimeperez , this solved my problem. I even found some hints about the naming in the [documentation](https://simplesamlphp.org/docs/stable/simplesamlphp-modules#section_2) ("lib" directory), although it still uses PSR-0. Maybe PSR-4 could be mentioned there, too?
